# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np




dataset = pd.read_csv("trevignano2018.csv", encoding="utf-8")


dataset["text"] = dataset["text"].str.replace("\"ma io prego!\"", "'ma io prego!'")
dataset["text"] = dataset["text"].str.replace("Amen\. \"", "Amen.")
dataset["text"] = dataset["text"].str.replace("Amen\. \”", "Amen.")
dataset["text"] = dataset["text"].str.replace("Amen\"", "Amen.")
dataset["text_en"] = dataset["text_en"].str.replace("Amen\"", "Amen.")
dataset["text"] = dataset["text"].str.replace("Tu sei il nostro Re!!\”", "'Tu sei il nostro Re!!'")
dataset["text"] = dataset["text"].str.replace("miei figli\”", "miei figli")
dataset["text"] = dataset["text"].str.replace("Amore e Vita\”", "Amore e Vita")
dataset["text"] = dataset["text"].str.replace("Amen Figli miei", "Amen. Figli miei")
dataset["text"] = dataset["text"].str.replace("Ora vi do la mia santa benedizione nel nome del Padre, del Figlio, dello Spirito Santo\. Amen Il segno di oggi :", "Ora vi do la mia santa benedizione nel nome del Padre, del Figlio, dello Spirito Santo. Amen. Il segno di oggi: 'Amore'")
dataset["text"] = dataset["text"].str.replace("Amen Durante", "Amen. Durante")
dataset["text"] = dataset["text"].str.replace("Amen Ecco", "Amen. Ecco")
dataset["text"] = dataset["text"].str.replace("Spirito Santo \.", "Spirito Santo.")
dataset["text"] = dataset["text"].str.replace("Amen ''Popolo Mio'' SEGNI DAL CIELO ''I H S''", "Amen. Sign: 'Popolo Mio'. Segni Dal Cielo: 'I H S'")
dataset["text"] = dataset["text"].str.replace("''IO SONO CON VOI \" ", "'IO SONO CON VOI'")
dataset["text"] = dataset["text"].str.replace("\"", "")
dataset["text"] = dataset["text"].str.replace("AmenLa", "Amen. La")
dataset["text"] = dataset["text"].str.replace("Amen La", "Amen. La")
dataset["text"] = dataset["text"].str.replace("AmenIn", "Amen. In")
dataset["text"] = dataset["text"].str.replace("Santo \. Amen", "Santo. Amen.")
dataset["text"] = dataset["text"].str.replace(" : ", ": ")
dataset["text"] = dataset["text"].str.replace("Spirito santo", "Spirito Santo")
dataset["text"] = dataset["text"].str.replace("Dio Figli", "Dio. Figli")
dataset["text"] = dataset["text"].str.replace("Amen Oggi", "Amen. Oggi")
dataset["text"] = dataset["text"].str.replace("Continua a leggere\. \. \. \»", "")
dataset["text"] = dataset["text"].str.replace("sinistro\.\.", "sinistro.")
dataset["text"] = dataset["text"].str.replace("Amen Il ", "Amen. Il ")
dataset["text"] = dataset["text"].str.replace("Amen \.", "Amen.")
dataset["text"] = dataset["text"].str.replace("Amen ", "Amen.")
dataset["text"] = dataset["text"].str.replace("uno per uno", "uno per uno.")
dataset["text"] = dataset["text"].str.replace("Gesu'", "Gesù")
dataset["text"] = dataset["text"].str.replace("\(13 04", "(13 04)")
dataset["text"] = dataset["text"].str.replace("insultato mortificato", "insultato, mortificato")
dataset["text"] = dataset["text"].str.replace("la Germania \.", "la Germania.")
dataset["text"] = dataset["text"].str.replace("Il Vostro Gesù", "Il Vostro Gesù.")
dataset["text"] = dataset["text"].str.replace("disperazione \.", "disperazione.")
dataset["text"] = dataset["text"].str.replace("voce \. ", "voce. ")
dataset["text"] = dataset["text"].str.replace("Bagnoregio 26 08", "")
dataset["text"] = dataset["text"].str.replace("\.Amen", ". Amen")
dataset["text"] = dataset["text"].str.replace("vostro Si di", "vostro 'Si' di")
dataset["text"] = dataset["text"].str.replace("facendo \.", "facendo .")
dataset["text"] = dataset["text"].str.replace("\"Beati coloro che verranno perseguitati a causa del mio nome\"", "'Beati coloro che verranno perseguitati a causa del mio nome'")
dataset["text"] = dataset["text"].str.replace("\"quando capirete i segni la mia venuta sarà vicina\"", "'quando capirete i segni la mia venuta sarà vicina'")
dataset["text"] = dataset["text"].str.replace("noi \.", "noi.")
dataset["text"] = dataset["text"].str.replace("AmenDopo", "Amen. Dopo")
dataset["text"] = dataset["text"].str.replace("pubblicamente \.", "pubblicamente.")
dataset["text"] = dataset["text"].str.replace("preghiera \.", "preghiera.")
dataset["text"] = dataset["text"].str.replace(" \.", ".")
dataset["text"] = dataset["text"].str.replace("Amen Alle", "Amen. Alle")
dataset["text"] = dataset["text"].str.replace("pregate pregate", "pregate, pregate")




dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 2)), "Beloved children, thank you for being gathered here for the prayer of the Holy Rosary. Beloved children, love is God, but how little love and faith I sometimes see in the hearts of men; pray for conversion; the time is ripe for everything to be fulfilled. I bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 3)), "Beloved children, today how many blessings will descend upon you for being here in prayer. Children, please listen to the cry of love of my Son who does not give up and does not want to lose His children. I am a mother who can no longer look on with sorrow, those who surrender to Satan. Soon, I will come together with my Son Jesus into the world and I will take you in my arms. Beloved children, continue to be always on the way of faith and continue to be my soldiers and true apostles. This will be a year of changes. Now I bless you leaving peace in your hearts, in the name of the Most Holy Trinity, Father Son and Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 4)), "Beloved children, I am approaching, I am ready, grace is with you. My daughter, you must tell everyone as soon as possible that they must pray for my coming. You will be glorified by my love, you have enormous grace and you do not understand it. Children, give yourselves peace among yourselves, you must be together and ready, soon you will be able to enjoy the things My Father has prepared for you, love one another, love all of you. Have faith, have faith all of you. Love yourselves more than your own children, the devil will not win, but you with your faith will have won all eternity for life. Do not be angry, do not be nervous, I leave you Peace, all the rest comes from Satan, who tries to insinuate himself into your lives, do not allow him to do so, your salvation will soon arrive together with me glorious, smile and rejoice. Do not reason too much, reasoning comes from satan, do not reason for the things of your life, entrust everything to me who am your Savior Jesus Christ. My Father sends me for the salvation of men, please do not reason too much, you will never understand my Father's plans. Thank you for accepting me. Your Jesus. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 6)), "Dear children, thank you for listening to my call in your hearts. May peace be with you. Beloved children, always remember the Word, always remember the Mass and the Eucharist, these are the principles of faith. Do not listen to the false peace that is seen in the world. The powerful have already put into action the project of the antichrist. Soon you will see signs from heaven. Jerusalem will be destroyed again, as it was two thousand years ago. Those who do not believe these messages, must remember what happened in the time of Noah, with the universal flood, now history will repeat itself in a greater way. Always be ready. I am near to protect you. Now I bless you in the name of the Father of the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 13)), "Brothers, I am beside you ... My priests have bowed their heads to Satan and this is what they are doing to me (Jesus shows a torn chest), embrace and love my cross. thank you for consoling me. I bless you all in my name, in the name of my Father and the Holy Spirit. Amen. At 10:00 p.m. 2nd message of Jesus: Brothers, you will hear my strong powerful call, always be united, fight against Satan, I am here with you, I am in your midst, have pity on my cross, do not abandon one another, always be united in my name, my mother will come with me to welcome you into the new paradise, from tonight everything will begin, I only want to love you, my cry of love will not stop here, I will go further in love, love one another as I love you. My brothers I am always here, next to you, I will follow your minds, your hearts, I just want you to allow it. I love you, I bless all of you present, on your families will descend blessings every day, let me into your hearts. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 16)), "Dear children, thank you for listening to my call in your hearts. My beloved ones, pray, pray, always be ready in spirit, the warning is getting closer and closer. I, your Mother, am present on earth to implore you to redeem yourselves urgently, the sacraments, the Holy Mass and the Most Holy Trinity must be your greatest loves. I weep for what awaits you and feel great sorrow when I listen to the hearts of my children who do not feel love either for my Son or for their brother. Great is the love of the Father for His children, accept this love and rejoice. Now, together with the Most Holy Trinity, I bless you in the name of the Father and of the Son and of the Holy Spirit. Our Lady blessed all the sacred objects including those worn." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 18)), "Beloved children, thank you for being here, behold, my stirring of love has been accepted in your hearts. This is what I desire now, you have understood that you must stay united in prayer groups, intensify the rosary, this year will be really in need of prayer, given what I see. You must tell the priests to continue with the sacraments, many of them will no longer obey what is not from God, be on the alert and use discernment from what is from heaven and not. You have comforted me and made my heart rejoice. Thank you my jewels. I now bless you in the name of the Father of the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 20)), "Beloved children, thank you for being gathered here in prayer. My little ones, remember that our Lord is Love, whoever sows evil does not come from God. God is love towards His brother, love towards the weakest, love is the only way that leads to the light, do not behave like the Pharisees. Dear beloved children, my messengers, thank you for sacrificing your life for me, for being willing every day to criticize, know that you will be the first to be elevated and embraced by me and my Son Jesus. Pray for Europe. I now bless you in the name of the Father of the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 23)), "Beloved children, thank you for listening to my call in your hearts. My beloved ones, the Antichrist who will be presented will take the world into his hands and will be supported by the powerful, he will make his way into the Church and into people's lives. Be careful My loves, acclaim only your Jesus, who is Love and Life. I bless you one by one, that you may bring Peace into your homes. I bless you, in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 25)), "Beloved children, thank you for having listened to the call in your hearts. Dear children, the devil wants to take your hearts, always stay close to the Eucharist and to confession, know how to recognize good from evil. I will support you in all the trials you will have to endure in this year. I will be close to you, because humanity is facing the abyss. This evening graces will descend upon you. I now bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 27)), "Beloved children, thank you for being gathered here, pray children, pray so much, as I predicted, now in some churches my Son has disappeared, the Eucharist no longer has any value, this modernity is spreading, do not follow these false extravagances, they do not come from God. The arrival of Jesus is imminent, just as imminent will be signs from Heaven. Love one another and always be in Grace. I now bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 28)), "Brothers, be careful because iniquity is going through the world. They will make you believe what does not exist so that I am no longer present in this world. I do not force you to love Me, I do not force you to trust Me ... but why do you not trust Me with everything! When you are in Me, you must rest assured, do not believe unrighteous men. My Father, soon He will eliminate His enemies, the many enemies of God. The cold war has begun and before it is too late repent while there is still time. The devil is attacking you, he is attacking you every day, but I will be here with you. Stay in grace, I will never leave you alone, entrust everything to me. I bless you in the name of the Most Holy Trinity, in the name of the Father of the Son and of the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 30)), "Dear children, thank you for being gathered here. Where are my beloved children? My beloved ones, you must be united in prayer, the war is at its next step and America has lost all closeness to God and will suffer much because of this. Europe will also be attacked in every sense. My invitation is to watch the signs that will come from heaven, through which you will understand many things! Everything that belongs to the devil will be destroyed. You must tell priests to stay connected to the true Magisterium of the Church because the devil will try to brainwash them by making them approach rituals that are exclusively satanic. My little ones pray, pray, pray, I will be beside you every time you invoke my name. I now bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 1)), "Beloved children, thank you for listening to my call in your hearts. Dear children, this is the time of your courage, entrust everything to my Jesus. It will be a difficult journey, where you will be mocked and many will turn away, the angels of hell are on earth to catch you with cunning, be careful. This is the time when the Lord will give you many gifts, especially that of discernment, be calm, I will be with you, I will take you by the hand, be united to the Holy Rosary every day, so that the demons may be weakened. I bless you in the name of the Father of the Son and of the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 3)), "Dear children, thank you for having responded to my call in your hearts. My beloved children, how difficult is the way that leads to light and sanctification, but I give you the strength to go forward. Do not stop before the obstacles that there will be on this path that leads to Jesus. I tell priests to follow their hearts and to beware of the pitfalls wherever they come. My dear children, soon the cross will appear in the sky and it will be before the warning. Have peace in your hearts and take it into your homes. I now bless you in the name of the Father of the Son and of the Most Holy Trinity. Amen Our Lady then said: Today, many graces will descend on my children. During the apparition, I saw the blue cross turn red-hot." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 3) & (dataset["author"] == "Jesus Christ")), "My brothers, pray, pray so much, I am on my way to you, have mercy on me, my body is desecrated by those who say they love me and do not listen to their voices, it is a continuous uproar inside the churches. Those who say they love me and speak in my name and profane the Eucharist will burn in the fire of hell. Beware My children, beware!!! The new church will rise, you are part of my people, I love you, be united always in prayer. Now I bless you in the name of My Father, in My Name and in the Holy Spirit. Be patient with everyone, it will be the great virtue. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 13)), "My beloved children, thank you for listening to my call in your heart. Today, I am among you once again to shout my love for you and to ask you to follow my Son Jesus, please do not forget the reason for His death, all His sufferings, for your salvation and for the redemption of mankind. The evil one is unleashed in your families, but take the rosary in hand, it is the only anchor of salvation you have. This call of mine is urgent, soon you will hear the sound of the last trumpet before the coming of Jesus, remember children, that He does not come to unite but to separate. My beloved ones, pray for this sinful Italy and for Japan, where the earth will soon tremble. I now bless you in the name of the Father of the Son and of the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 17)), "Beloved children, thank you for listening to my call in your heart. Blessed children, a part of humanity has a petrified heart because it does not have true faith, it does not listen to the word and does not pray with the heart, but only out of hypocrisy. In this beginning of Lent, remember why Jesus died, contemplate His cross, thinking of forgiveness, this must be your Easter. Listen to my appeals, convert, love Him who died for your salvation. The worst times will come and when the most terrible earthquakes will break out, remember it will be a sign that Jesus is coming, this event will be anticipated by the three days of darkness. Now I bless you in the name of the Father, the Son and the Holy Spirit. (During Our Lady's apparition I saw Jesus blessing all those present )." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 27)), "Dear brothers, how much joy your prayers give me, they succeed in soothing my wounds that still today burn and bleed. Open your hearts, pray a lot, and I will accompany you hand in hand and all your obstacles I will help you to overcome. I love you and I beg you do not lose faith and do not get confused, soon, everything will be clearer in your eyes and finally the happiness you will feel will be unimaginable. I now bless you in the name of the Holy Trinity." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Beloved children, thank you for being gathered here again today. How much faith I feel in your hearts and in your prayers. Never be afraid, go to prayer meetings, witness your faith everywhere, evangelize the world, beginning with your families. My little flowers, thank you for always being attentive to my requests and suggestions, today Jesus is here with me and in spite of His sufferings He loves you and is ready to forgive all your sins because He is merciful, but I beg you my children, sincerely confess especially your mortal sins, do not wait any longer. Beloved children, you are now passing through the narrowest path that will lead you to glory. Pray for Japan. Now I bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8)), "Beloved children, lighted torches, thank you for being gathered here in this domestic church. My beloved ones, at last I feel your hearts beating for the great Faith. The hard times are before your eyes, please continue to pray so much. I desire that these prayer circles be held more often in your homes where I am and will always be present. My loves, make yourselves ready and purified to welcome us. Go out into the world to evangelize, do not stand idly by, there is no more time. The grace and blessings of my Son will descend upon you today. Pray for Italy, Spain, France and England. I leave you now in peace. I bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8) & (dataset["author"] == "Jesus Christ")), "Brethren, thank you for being gathered here in this blessed home, I am here among you to leave you peace. Today I am very sad, so sad, I am praying to My Father that His justice will not be worse than the flood or worse than what happened in the days of Noah. My Father does not want to listen to me anymore, you have done too much harm. Brothers, how I love you! I want your salvation, that is why I will give you my love, love me as I love you, you did not welcome me the first time when I was born and you do not want to welcome me today for my second coming. Oh! Children, stay with me, do not be afraid, spread my word, stay close to the Gospel and the Eucharist. Stay united, please stay united. In the name of the Most Holy Trinity, I bless you in my name, in my Father and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 10)), "Beloved children, thank you for listening to my call in your hearts. Dear children, I have come here not to put fear in you, but to assist you and your soul. After so many years of apparitions, you still do not believe my messages; not everyone realizes the great Grace that my Father has given you. My beloved ones, the demons are all on earth and you will never imagine how much place has been made in hell for all the souls who will fall into sin, there is an immense chasm. Please, open your eyes and do not listen to the false peace, for the powerful are planning a great war. Pray, pray, pray. Now I give you my motherly blessing in the name of the Father of the Son and of the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 13)), "Beloved children, thank you for having responded to my call in your hearts. Dear children, remember that my Son, when He gathered His apostles, did not call the doctors of the Church, but simple and righteous people of heart. Enough with the pretense of putting doubts in the heads of the brothers, the devil is playing with your minds and hearts. Remember children, you will all stand before God's justice. Pray, pray, pray much, listen to the winds of war. Now I bless you in the name of the Father and of the Son and of the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 24)), "Dear children, thank you for listening to my call in your hearts. Dear children, as I feel the great faith in your hearts, so also do I feel the great frost of hearts that do not flinch before me. Arrogance and pride do not come from God. This period you will feel the quiet, but soon everything will precipitate. This Easter, there will be many signs that will anticipate the end of time. I would like to raise you up to me and for this I ask you to pray a lot. I am your Mother, now I bless you in the name of the Father of the Son and of the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 27)), "My children, do not be cruel to Me, I love you, stay united in peace, in the Word and in the Gospel. Enough, continue to love Me, surrender to your King, I am everything, love, the beginning and the end. Why do you want to abandon Me, love My wounds, My Cross. Now I bless you in the name of the Father of the Son and of the Holy Spirit, thank you for accepting Me, thank you My children." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 31)), "My beloved, children of my heart, time is drawing to a close. I turn to the priests, be solicitous to receive as many souls as possible, so that they may take the way of holiness. This is a period of purification, so that you may be ready for the coming of Jesus. My children, do not be afraid to fight heresy; Satan, believing he has won, is celebrating for all the souls he has managed to attract to himself. Pray, pray, pray for peace. I bless you in the name of the Father of the Son and of the Holy Spirit. Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 3)), "My beloved, children of my heart, time is drawing to a close. I turn to the priests, be solicitous to receive as many souls as possible, so that they may take the way of holiness. This is a period of purification, so that you may be ready for the coming of Jesus. My children, do not be afraid to fight heresy; Satan, believing he has won, is celebrating for all the souls he has managed to attract to himself. Pray, pray, pray for peace. I bless you in the name of the Father of the Son and of the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 7)), "Beloved children, thank you for being here united in prayer. Dear children, how much suffering there is in your heart, but this is the way to reach Jesus. He always takes you by the hand, especially when He looks at your suffering. My Son and I suffer and feel your pain, do not fear my children, you are not alone, I only ask you to entrust yourselves completely to us, remember that you are in the world, but you are not of the world. I now bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 14)), "Beloved children, thank you for listening to my call in your hearts. Beloved children, what sorrow causes me so much suffering, especially that of your families. Now, the war that has just begun, will have consequences all over the world, but why does man persist in indifference and not yet understand that the only salvation is that of prayer! My little ones, always be ready at night, what has been foretold is coming, the rapture will happen soon. Now, we need the best souls, so that they can join the army of salvation. I love you my children, I leave you now with my motherly blessing, in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 17)), "Beloved children, thank you for being gathered here in prayer. Your souls sweeten my sufferings and your faith eases the pains of my Son. Beloved children, the church will remain as it has always been, the devil who thinks he can be the master will be cast out, only because souls have allowed themselves to be taken by pride and arrogance. Nothing can be changed, because the truth is one, before, now and always. Be strong in faith and attached to the only truth that my Son has left you. Whoever thinks to change everything blasphemes against God. Now, I bless you and all sacred objects, in the name of the Father of the Son of the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21)), "Beloved children, thank you for being here in this blessed home. Today is the anniversary of my arrival to my beloved daughter, so that my messages may be heard by as many people as possible. I already knew, that the heart of this daughter and her sweet husband would break down all barriers by spreading my messages of love and peace, because in their hearts there is love and hope. Continue to pray for all those who do not believe and who are far from God, that they may be protected, and I intercede with my Son Jesus and they will be saved. I love you with a love so great that you could not imagine. I bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21) & (dataset["author"] == "Jesus Christ")), "My brothers, I will always be with you, my grace will descend upon you, have faith and never abandon me. Love me, as I love you; pray, that I may anticipate my return. Please, children, stay united, now I give you my blessing in the name of the Father, in my name and in the name of the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 24)), "Dear children, thank you for listening to the call in your hearts. My children, change your lives and convert, not only when you feel pain, but truly open your hearts to God's love. Dear children, the righteous will be persecuted and provoked continually, but I know their hearts and therefore they will be protected from all evil. I will give you all strength, but you approach the Eucharist often, be faithful to the laws of the Lord. Pray for the Vatican, something very serious will happen soon. My blessings will descend upon you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 1)), "Beloved children, thank you for being here in prayer. My little ones, the Church will always remain intact, even if there are blind people leading other blind people, no one will ever be able to touch it, because it will be sustained by the Holy Spirit. Never as today, graces will descend upon you, so that all may look with children's eyes at how good and merciful God is. Dear children, always invoke mercy. Now I give you my holy blessing, in the name of the Father, the Son and the Holy Spirit. Amen. " , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 3)), "Beloved children of my heart, thank you for listening to my call in your hearts. Dear children, begin this month to consecrate yourselves in my immaculate heart, here you will find peace and my protection. My beloved ones, follow my Son Jesus, for He is love, pure love, He does not come only to judge you, but to make new heavens and a new earth, this earth which is now invaded by the sin of war and by the 'I' who is not God. Children, I am still here to follow you and to protect you, recite the rosary, the weapon that stops evil, the one that is spreading in the world. Satan will not win, and I will triumph with my angels. My beloved ones, be faithful to God's laws and always be consistent. Speak to God, as to a father or best friend, do not be afraid, He hears all who call upon Him. Pray for Rome, terrorism will not be long in coming. Now, I give you my Holy Blessing, in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 5)), "Beloved children, thank you for your prayers for you and for all those who will make prayer circles and for the rosaries prayed in families, I will be there and I will bless one by one and intercede through my Son for all the graces that you will ask of me at that moment. Dear children, always prepare yourselves, before taking the Eucharist, only after having forgiven everything in your heart. Pray for Chile. Now, I bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 8)), "Beloved children of my immaculate heart, thank you for listening to my call in your hearts. My daughter, I desire, that you tell the priests not to be afraid, the hours of persecution have come, but you cling to my Son Jesus and continue to evangelize always the truth. Dear children, heaven and earth will soon unite and the pain will disappear, for you will taste Paradise. I love you, for you are my beloved children and my lighted lamps, go forth and witness your faith always. Remember, where there is God, there is love and where there is love, there is mercy. Now, I bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit, may the fire of the Holy Spirit descend upon you. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 12)), "My dear children, thank you for being gathered here in prayer. My beloved ones, how much confusion is in your heads and in your hearts, this is what the devil wants to sow, destruction and confusion, I, on the other hand, desire that you can cling only to the recitation of the Holy Rosary, approach prayer, the Eucharist and confession with love towards my Son Jesus. I am beside you and will always accompany you and take you by the hand. Let me accompany you! Soon, everything will change and you will be able to be in the light and see the true Paradise. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 19)), "Beloved children, thank you for listening to my call in our hearts. How much sadness I see in your hearts, but for so long I have been reminding you that this is a time of purification, surely many will be your sorrows, but do you wonder how much Jesus has suffered for you? My little ones, do not be anxious, soon you will be able to taste the new Paradise, what is written must happen before the return of Jesus. Now I leave you with my motherly blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 22)), "My beloved children, thank you for being gathered here in prayer. I know how much sadness there is in your hearts, I know you one by one and I know your anxieties and weaknesses. Behold, I am here to console you, to guide you and to love you with a motherly love so great that I would like only to see you smile, having my Son Jesus in your hearts. My beloved ones, the return of Jesus is soon, welcome Him, be ready and be found on the way of holiness. The devil is creating the greatest schism the Church has ever felt, but do not lose hope, I will be with you, do not turn back in faith, but continue on your way, today stronger than before. I love you and bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 26)), "Beloved children, thank you for listening to my call in your heart. Beloved daughter, sometimes silence and meditation are needed, I am always with you. My daughter, a day will come when any human being will love my Son, shouting, 'You are our King!!!', but if this does not happen soon, nothing will be granted, because the false penitents will feel only Divine justice. Open your hearts to the love of my Son, for everything is speeding up, be ready. Dear children, soon you will be taken away, protected by my blessed mantle, which is already on earth. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 29)), "My brothers, thank you for listening to the call to prayer of the Holy Rosary. I invite you to reflect. When My Mother asks you to be ready for My Second Coming, you often think, 'But I pray!' Make an examination of conscience. How often do you bring me your joys and sorrows, how often do you thank me for the beautiful things I give you? Do you wonder if you have judged your brothers and sisters unfairly? How many good works have you done in your lives and how many works of mercy? How many souls have you brought to me by snatching them away from the devil? Brothers and sisters, these are the reasons why you will be judged; know that those who blaspheme will never see my face. Be united and pray for Italy, for great will be its suffering, even nature will rebel against man. Now I bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 2)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 3)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 5)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 9)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 12)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 16)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 19)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 23)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 26)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 30)), "" , dataset["text_pl"])

dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 2)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 3)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 4)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 6)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 13)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 16)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 18)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 23)), "" , dataset["text_pl"])


dataset["text"] = dataset["text"].str.replace("Amen\"", "Amen.")
dataset["text_en"] = dataset["text_en"].str.replace("Amen\"", "Amen.")



dataset.to_csv("trevignano2018_cleaned.csv", encoding="utf-8", index=False)





