# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np




dataset = pd.read_csv("trevignano2019.csv", encoding="utf-8")


dataset["text"] = dataset["text"].str.replace("Amen\”\. Regina del Rosario ", "Amen.")
dataset["text"] = dataset["text"].str.replace(" amen", " Amen")
dataset["text"] = dataset["text"].str.replace("\"ma io prego!\"", "'ma io prego!'")
dataset["text"] = dataset["text"].str.replace("Amen\. \"", "Amen.")
dataset["text"] = dataset["text"].str.replace("Amen\. \”", "Amen.")
dataset["text"] = dataset["text"].str.replace("Amen\"", "Amen.")
dataset["text_en"] = dataset["text_en"].str.replace("Amen\"", "Amen.")
dataset["text"] = dataset["text"].str.replace("Tu sei il nostro Re!!\”", "'Tu sei il nostro Re!!'")
dataset["text"] = dataset["text"].str.replace("miei figli\”", "miei figli")
dataset["text"] = dataset["text"].str.replace("Amore e Vita\”", "Amore e Vita")
dataset["text"] = dataset["text"].str.replace("Amen Figli miei", "Amen. Figli miei")
dataset["text"] = dataset["text"].str.replace("Ora vi do la mia santa benedizione nel nome del Padre, del Figlio, dello Spirito Santo\. Amen Il segno di oggi :", "Ora vi do la mia santa benedizione nel nome del Padre, del Figlio, dello Spirito Santo. Amen. Il segno di oggi: 'Amore'")
dataset["text"] = dataset["text"].str.replace("Amen Durante", "Amen. Durante")
dataset["text"] = dataset["text"].str.replace("Amen Ecco", "Amen. Ecco")
dataset["text"] = dataset["text"].str.replace("Spirito Santo \.", "Spirito Santo.")
dataset["text"] = dataset["text"].str.replace("Amen ''Popolo Mio'' SEGNI DAL CIELO ''I H S''", "Amen. Sign: 'Popolo Mio'. Segni Dal Cielo: 'I H S'")
dataset["text"] = dataset["text"].str.replace("''IO SONO CON VOI \" ", "'IO SONO CON VOI'")
dataset["text"] = dataset["text"].str.replace("\"", "")
dataset["text"] = dataset["text"].str.replace("AmenLa", "Amen. La")
dataset["text"] = dataset["text"].str.replace("Amen La", "Amen. La")
dataset["text"] = dataset["text"].str.replace("AmenIn", "Amen. In")
dataset["text"] = dataset["text"].str.replace("Santo \. Amen", "Santo, Amen.")
dataset["text"] = dataset["text"].str.replace(" : ", ": ")
dataset["text"] = dataset["text"].str.replace("Spirito santo", "Spirito Santo")
dataset["text"] = dataset["text"].str.replace("Dio Figli", "Dio. Figli")
dataset["text"] = dataset["text"].str.replace("Amen Oggi", "Amen. Oggi")
dataset["text"] = dataset["text"].str.replace("Continua a leggere\. \. \. \»", "")
dataset["text"] = dataset["text"].str.replace("sinistro\.\.", "sinistro.")
dataset["text"] = dataset["text"].str.replace("Amen Il ", "Amen. Il ")
dataset["text"] = dataset["text"].str.replace("Amen \.", "Amen.")
dataset["text"] = dataset["text"].str.replace("Amen ", "Amen.")
dataset["text"] = dataset["text"].str.replace("uno per uno", "uno per uno.")
dataset["text"] = dataset["text"].str.replace("Gesu'", "Gesù")
dataset["text"] = dataset["text"].str.replace("\(13 04", "(13 04)")
dataset["text"] = dataset["text"].str.replace("insultato mortificato", "insultato, mortificato")
dataset["text"] = dataset["text"].str.replace("la Germania \.", "la Germania.")
dataset["text"] = dataset["text"].str.replace("Il Vostro Gesù", "Il Vostro Gesù.")
dataset["text"] = dataset["text"].str.replace("disperazione \.", "disperazione.")
dataset["text"] = dataset["text"].str.replace("voce \. ", "voce. ")
dataset["text"] = dataset["text"].str.replace("Bagnoregio 26 08", "")
dataset["text"] = dataset["text"].str.replace("\.Amen", ". Amen")
dataset["text"] = dataset["text"].str.replace("vostro Si di", "vostro 'Si' di")
dataset["text"] = dataset["text"].str.replace("facendo \.", "facendo .")
dataset["text"] = dataset["text"].str.replace("\"Beati coloro che verranno perseguitati a causa del mio nome\"", "'Beati coloro che verranno perseguitati a causa del mio nome'")
dataset["text"] = dataset["text"].str.replace("\"quando capirete i segni la mia venuta sarà vicina\"", "'quando capirete i segni la mia venuta sarà vicina'")
dataset["text"] = dataset["text"].str.replace("noi \.", "noi.")
dataset["text"] = dataset["text"].str.replace("AmenDopo", "Amen. Dopo")
dataset["text"] = dataset["text"].str.replace("pubblicamente \.", "pubblicamente.")
dataset["text"] = dataset["text"].str.replace("preghiera \.", "preghiera.")
dataset["text"] = dataset["text"].str.replace(" \.", ".")
dataset["text"] = dataset["text"].str.replace("Amen Alle", "Amen. Alle")
dataset["text"] = dataset["text"].str.replace("pregate pregate", "pregate, pregate")
dataset["text"] = dataset["text"].str.replace("Salvatevi\”", "'Salvatevi'")
dataset["text"] = dataset["text"].str.replace("\” Riflessione", "Riflessione")
dataset["text"] = dataset["text"].str.replace("\"sentire \"", "'sentire'")
dataset["text"] = dataset["text"].str.replace("Amen\”\.", "Amen.")
dataset["text"] = dataset["text"].str.replace("SIATE TESTIMONI", "Sign: 'SIATE TESTIMONI'")
dataset["text"] = dataset["text"].str.replace("sacrAmenti", "sacramenti")
dataset["text"] = dataset["text"].str.replace("Spirito Santo Amen", "Spirito Santo, Amen")
dataset["text"] = dataset["text"].str.replace("\. Madonna di", ".")
dataset["text"] = dataset["text"].str.replace("dal cielo \.", "dal cielo.")
dataset["text"] = dataset["text"].str.replace("Figli miei, domani sarò ancora con voi", "Figli miei, domani sarò ancora con voi.")
dataset["text"] = dataset["text"].str.replace("cambiAmenti", "cambi Amenti")


dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 3)), "Dear children, thank you for having responded to my call in your hearts. Dear children, how many sins are accumulated day by day by everyone, Church, Faithful and unfaithful. My children, why do you let yourselves be tempted every day by evil? Why, you still do not understand that these are the times when the truth must be proclaimed, the name of Jesus is the way, the truth and the life, do not waste any more time, you have lost so much, now I invite you to confess all your sins, those that you have not been able to confess until today, be clean and ready because the time is near. Now, I thank you for having welcomed me once again and I bless you with Maternal Love, in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 5)), "Dear children, thank you for being united here in prayer. My dear little ones, pray, pray, the plagues are coming and the epidemics are spreading, everything will begin in Rome, where the sick Church of Peter is. Pray my children continuously, the times I have foretold have begun, but do not fear because I will always be at your side. My loves, the times to come will be harvest times, so sow well and those who have not yet done so, I ask them to convert. Thank you my children, I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 8)), "Dear and beloved brothers, thank you for being gathered here in this blessed home. Dear brothers, proclaim with joy my coming, be joyful in your hearts, for your King is to be in your midst. Do not be afraid of the future, you will have our protection, just as you have welcomed me into your hearts, so will I welcome you into the new Paradise, delicacies are ready for you, with peace, joy and infinite love. Now I will pass by each of you to give you my Holy Blessing, in the name of the Father in my name and of the Holy Spirit, Amen. Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 12)), "Beloved children, thank you for being here in prayer. My beloved children, how important the family is for God, it is the beginning of the little church, so I ask you to have prayer circles inside the homes, teach your children about prayers and the importance of them. You adults, take strength with the Eucharist so that you can better face what will come. I love you, and it is with Maternal Love that I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 15)), "My beloved ones, how many sufferings and how many tribulations you will have to face, but with all the love that presses upon me, I tell you that I am with you and will always be with you. Brothers, I am often with you and with all of humanity, I often speak in hearts, but they do not listen to me, hardly anyone stops to ask me anything seriously, and yet how I long to listen and help everyone. Entrust yourselves to me completely, and I will lead you to peace, I will advise you and give the graces you ask for. I am here, I am asking you and I desire that you recognize Me. Open your hearts and return to me; everything would be simpler. I leave you under the protection of my Blessed Mother, I love you. Your Dear Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 19)), "Beloved children, thank you for having responded to my call in your hearts. My children, how much love I feel in your hearts, be apostles and brothers, witness the faith everywhere. My sweetest children, prayers have mitigated what is to come, but continue to pray, never grow tired, for you will see unimaginable things happen that rationally you will not be able to understand. Children, lead your brothers on the path of love for my Son Jesus. Now, I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen. Beloved daughter, I will remain to pray with you." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 22)), "My beloved ones, thank you for being here in prayer. All this time I have been with you to protect you from demons, pointing you to the right way to my Son Jesus. I have asked you to approach the sacraments, to prepare yourselves for these end times. My children, do not be tempted! How much I suffer when I watch my children get lost, I beg you to continue in unceasing prayer, I am your Mother and I am here with you and for you. Now, I leave you in peace and in my Holy Blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 26)), "My beloved children, thank you for listening to my call in your hearts. Beloved children, I ask you and insist on the conversion of your hearts, love my Son Jesus, strengthen yourselves with the Eucharist. I am sad for the hard times you are heading towards, there is no peace, everyone is against each other because there is no longer God in hearts. Always remain united, take care of the weakest and your rewards will be great. My beloved ones, take my peace into your homes, where I desire there to be circles of prayer. Pray for Russia. Many graces will descend this evening. Now, I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 29)), "My children, thank you for answering My call in your hearts. Why do I not see many of my children? By what are they distracted! My beloved children, you marvel when I say that incomprehensible things will happen, remember that all that I have foretold will happen in this time, therefore, I ask you to prepare yourselves for the events that will come, prepare yourselves with prayer and sacrifices, do not fear, for the angels who are on earth will protect you, they are many sent from heaven. Be witnesses. My children, do not be afraid, pray for the divided and almost disintegrated Church. Always love one another, spread peace and not discord. I invite you again to conversion; I will always protect you as a Mother. Remember, you are in the world, but you are not of the world. Now, I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 2)), "Beloved children, thank you for responding to my call in your hearts. My beloved ones, how much humility and how much love for God, I see in many of these children tonight, but I also see so much confusion in your minds and in our hearts. I ask you not to listen to those who want to change the Word, what has been left to you in writing is not to be interpreted, but only to be put into practice, always be faithful to the Gospel, all truth is written there. I love you children, always be witnesses of the faith. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 3)), "Dear children, thank you for having responded to my call in your hearts. My loves, how much joy I feel in seeing you gathered in prayer in this blessed place, your prayers will be lifted up to heaven, thank you children, my heart is sad for all that will happen and especially for all the souls who flee before God's love. My children, I ask families to teach their children love, peace and mercy, these young people are growing up without God, why don't you decide to let Him enter the families? Everything would always and only be love. This is the time where there will be apostles of God and apostles of Satan, especially within the church there will be Bishops against Bishops, priests against priests, parents against children, husbands against wives and so on, this is the time of persecution, soon everything will be clarified. The warning is upon you, I love you and call upon me, and I will be with you. Now, I give you my blessing in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 12)), "Beloved children, thank you for being gathered here in prayer. When I look at you, as you help each other as brothers, my Immaculate Heart fills with joy. My children, my apparitions are not accepted, neither by a part of the Church, nor by many of my beloved children, who do not seriously believe that the Trinity has given mankind a great opportunity, allowing Me, Co-Redemptrix, to warn His children to return to God. God is good and merciful, but do not waste time, if you ask Jesus for forgiveness from the heart, He will take you by the hand, convert, children, and be ready for the Warning, it will be an important spiritual event for each of you. Seek strength in the Rosary, in the Eucharist and in Confession, be ready and live each day as if it were the last. Now, I bless you, your families and your hearts in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 16)), "Dear children, thank you for listening to my call in your hearts. My beloved ones, what was foretold is coming, the Church is now in the most total division, the followers of Jesus, against the followers of Satan. My children, terrible times are coming, the earth will tremble as never before. Have faith in God, for only in this way will you go where all will be peace and infinite love, while on earth the death of sinners will be infinite. All of you belong to the Lord, do not fear, woe to the proud and arrogant man, for he will feel all the punishment of God. Pray for Italy and for Europe. Now, I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 19)), "Greetings, love and peace in this house. I, God the Father Almighty, creator of heaven and earth, am here among you. I ask you children, why do you not love Me, I am your Father, the only true Father, I love you with an outsized love. My children, how much joy I had in creating everything, why do you avoid Me? To make you understand how great is the love I feel for My children, I sent My only Son for you, to give you the concreteness of My being here with you. To redeem you from your sins He went up on the cross and died for you, as I could have if I had not been a good and merciful Father. Do not be afraid of me. I say to families, teach your children to see me as the good Father who comes down among you to love you. Tell me your confidences, I have never turned anyone away, I am not evil, I am not that old man who is painted, I am not, neither old nor young, I am the Eternal Father, good and merciful. Oh children! What a Grace to be here with you, I wanted to gather you here, in this house that now belongs to Me, as in all houses where prayer prevails. My children, I remind you again, do not be afraid of me. I say to the priests present and not present, I beg you, teach the commandments, teach what I have left you, make people not afraid of me, I am the good, merciful and living Father. The Cross and the Eucharist is what you must see, the Cross is the remission for your sins and is the only thing that brings you together to come to me, the Eucharist, asked for and founded by my Son, is the gift of a wonderful grace, which you can all enjoy. I, Almighty Father Creator of all, ask my creatures to love me, I have never asked for anything, only Love, and where there is Love I am there, you are my family and I want you all together to proclaim in one voice one thing, Love, the Love of God, the Love that comes from me, that passes through my Son, the Love for my chosen Mary Most Holy Immaculate Virgin. Now, I bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 22)), "Beloved children, thank you for having responded to my call in your hearts. My children, thank you for being gathered here in prayer together as true Apostles. Children, I have gathered you here so that you may see and pray for my tears and for my heart torn with sorrow. Soon, punishment will descend on the church, punishment that cannot be postponed, so that sin may be destroyed, too much pride and arrogance have ruined my beloved children. The Lord does not want theologians, but shepherds who receive souls with love and tenderness, loving them and guiding them towards the light and not letting them descend into darkness together with them. Children, pray so much that the punishment may be mitigated. Pray for America. Now, I bless you in the name Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 23)), "Beloved children, thank you for listening to my call in our hearts. My children, always keep the flame of faith burning and I beg you, pray, pray, pray, for the times are ripe. Pray the Rosary in your homes and make praying circles everywhere; only in this way will you be protected from the evil that surrounds you. Be ready, be awake! Do not fall asleep as the apostles did. I am here to guide you. I love you and I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 26)), "Dear children, thank you for having responded to my call in your hearts. Handmaid of the Lord, spread what I tell you: the true Church faithful to Jesus Christ is under the rubble of the Church itself, if my children do not equip themselves with prayer and humility, soon suffering will see many of my beloved children fall. They are changing the Holy Gospel and changing the prayers. this is not love for Jesus, but believing that they can create their own doctrine, putting themselves in the place of God. My dear children, you will have nothing to fear, because before the purification, which is coming on earth, you will be protected and taken to safe places, where the evil one will not be able to touch you. Pray, pray, pray. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 2)), "My dear children, thank you for having responded to my call in your hearts. Beloved children, I am still touching the earth with the hope that there will still be many conversions, listen to my messages that are given only out of love for humanity. The Church is in great danger, I wish to say to my beloved children, have courage, feed on the Holy Gospel, remember that where there is pride there is no God and where there is pride there is no faith, have love for your brothers and always be united in the love of Jesus. Tomorrow, I will be with you again, my Apostles. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Beloved children, thank you for being here in prayer and for answering my call in your hearts. My children, how much comfort I feel to my wounded heart because of the abomination of this world. Sweet creatures, I ask you to let your hearts be handled like this, like a clay pot, so that they may be molded to the great love of Jesus. Dear children, be apostles of light, be serene for those who do not believe in my real presence in this place blessed by the Father, for my presence and my instructions for your salvation will thunder from one end of the world to the other, so that my people may gather to love Jesus and be ready for the coming days. Be My apostles, be solid walls and fortresses for lukewarm souls. Now, I leave you with my Holy Blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 5)), "Dear children, thank you for listening to my call in your heart. Beloved children, so many are asking for the signs of the coming of my son Jesus, you will no longer believe in sin when the Protestantization will take place in the church, those will be the signs that will point you to his coming. My children, this is the time when the demons come to life more than ever before on earth, the devil's plan is at its highest fulfillment, do not be attracted by the glitter of the world, I am here to protect you, I love you with all my heart. Now, I leave you with my motherly blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 12)), "Beloved children, thank you for responding to my call in your hearts. My children, do not be afraid of what will happen, continue in prayer, penance and sacrifices during this Easter season. My beloved ones, the Lord Jesus Christ as my sweet Son, continues to be persecuted, especially by the men of the Church, trouble, 10 times trouble, for those who are at the top of the Church, I am speaking to the Bishops and Cardinals who take advantage of sacrosanct obedience to persecute the holy priests who are faithful to the Gospel and who fight for the Truth and the Word of God, for this, the justice of God will be 10 times worse. What has been written will come true, love each other as brothers. Pray for Russia and for France. Now, I leave you my holy blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 16)), "Beloved children, thank you for having responded to my call in your hearts. My children, how much comfort I feel in my heart to see you here in prayer, this is my Church, I know all your afflictions, but I ask you to entrust yourselves to my Jesus, that He may bestow many graces on all of you, today there will be healings. Dear children, stay close to God with all your heart, the times that will come will be hard. Why do so many of my children decide to be on the side of evil? Those who have faith and watch God's laws have nothing to fear. My treasures, have mercy on those who are erring, love them. Be close to the Gospel and the Word, above all love as God loves you and forgive as He forgives, so that the kingdom of heaven may open to enjoy what is ready for you. Now, I leave you with my motherly blessing, in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 19)), "My children, I the Son of the Father, I ask you in this season of Lent, make sacrifices for me. Oh! how many times have I gone to my consecrated ones to ask, where are the souls that you are bringing to me, and yet there are none, how many chosen children have I passed by to ask the same thing and how many souls have I found that have approached my heart and in that of my Mother. This is why I choose according to open hearts that have the heart of children and souls turned to Heaven and not those who drink the chalice of worldliness and that of earthly pleasures. Brothers, I desire that you be one soul with Mine. My chosen daughter and sister, thank you for your peace, despite everything, I know your suffering, but I know that you are offering me everything, that is why I love you, how much love I feel in your heart for me, but tell me how much do you love me? How much do you want to suffer for me? This is what I want. Your brothers and your beloved spouse are lights and honey to me for my suffering. I love you all and would love to show you how special you are to Heaven. I bless you, your Dear Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 23)), "Dear children, thank you for having responded to my call in your hearts. Dear children, in this Easter season continue with penances and sacrifices. My children, ask to receive the gift of the Holy Spirit together with the seven gifts, invoke Him and He will descend upon you. My children, the times that are coming will be very hard to face, strengthen yourselves in the faith and make an examination of conscience, when you go to Church to attend Holy Mass, you think you have washed your conscience, but this is not the way to be at peace with God, you must live it intensely and not just attend, confession and communion with others is necessary. Make circles of prayer. The earth will shake again, the Vatican will be shaken, pray for America which will be tormented by nature. I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 26)), "Dear blessed children, thank you for being gathered here in prayer, soften the pains of my Son Jesus. My beloved ones, conversion is what I am continually asking for in the places where I have appeared and where I continue to appear, only in this way will you be able to enter the Kingdom of Heaven. My Son wants you all safe, sinners and non-sinners, remember that God loves everyone equally, He waits for His children with love, patience and Mercy. Now, I leave you with my motherly blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 30)), "Dear children, thank you for being gathered here in prayer, responding to my call in your hearts. Beloved children, my little flock, be filled with the Holy Spirit, I pray for each of you before God, that the fire of the Holy Spirit may inflame your soul, your spirit. My beloved ones, I beg you to be strong in the faith and especially in the true and only Christian doctrine, in this period many things will be denied you by my beloved children, but do not prostrate yourselves before the modernist changes and praises, for they do not come from God. Now, I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 2)), "Dear beloved children, thank you for having responded to my call in your hearts. My beloved ones, the war is near, pray a lot with the Holy Rosary in your hands, only with true faith can something change. My children, why do you continue to mortify my Son Jesus, He died to redeem you from your sins, do not be each one God of yourselves, remember that the easy ways come from Satan, but those of God are reached only with suffering. Children, do not be dazzled by false lights, Love my Son and the cross, only in this way can you be worthy of His Love and Peace. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 3)), "Dear children, thank you for being here in prayer and thank you for responding to my call in your hearts. Beloved children, I am here again today to remind you to open your hearts and begin true conversion. Children, give all your tribulations to me and I will lift you up, invoke my Son and he will be close to you to protect you especially in times of tribulation, I ask you to love me and to be united for the days of difficulty that will come, God wants only love, let yourselves be cuddled by him like children. My children, make prayer circles in your homes, especially teach your children love for your Father and the Father's love for them. My beloved ones, do not be afraid, as long as I am with you, you have nothing to fear; strengthen yourselves in the faith, only in this way will you not run into dangers. Now, I leave you with my motherly blessing and bring peace to your homes, in the name of the Father, of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 6)), "My beloved ones, I am the Immaculate Conception, thank you for answering my call in your heart, you are here in prayer in this blessed place, I listen to your pleas and your requests, because I know how contrite your heart is, always pray the Holy Rosary if you want to ward off the war that is increasingly imminent. Your faith will give you peace and joy, pray for the young people who are being dragged by Satan towards darkness. Today I will grant some Graces. Pray, pray, pray with love and I will send light into your hearts opening them to Grace. Now, I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 9)), "Dear children, thank you for having responded to my call in your hearts. My children, be ready because the resounding sign you have been waiting for is about to arrive. Beloved children, be ready for when the fire of the Holy Spirit will invade your hearts, woe to those who are not, for they will be seized with great suffering. Dear children, we are now in the time when the heavens will open and you will hear the trumpets of the angels sounding, the purification will be stronger than before. My beloved children, soon the Eucharist will be removed from the Church. Pray, pray, pray for the rulers of America so that they do not make wrong decisions. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 13)), "Beloved children, thank you for having responded to my call in your hearts. My children, how many sorrows I hear, I am here to lead you towards the light of the Lord. Dear children, I have come to touch the earth, but few listen to my messages, know that soon the earth will tremble, but you are in the joy and love of God, do not get lost, your source must be the Gospel. Beloved children, in this Easter week, love the Cross and thank the Lord, you will not always be able to understand everything that is God's plan and often it is humanly incomprehensible, only Heaven and prayer will be able to answer your questions if you will have opened your heart. Do not change your prayers and do not change anything about the dogmas of the faith because that would be blasphemy, Satan is cunning, he takes souls without you noticing. I love you, I am your Mother, I protect you and I place you all under my mantle. Now, I leave you with my motherly blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 16)), "Brothers, be anointed by my Holy Spirit this Easter, for everything will be forgiven you, even the worst of sinners. I have created this family so that you may be united before my Mystical Body, do not forsake me, look at the signs of the times and do not be afraid, I am with you and I will stand by you. Tell even the blasphemers, the most hardened sinners to ask my forgiveness and forgiveness will be granted. Beloved children, if you only knew how much I love you! As children and as brothers I ask you not to leave me alone in this time of suffering, they have stripped me, mocked me and humiliated me, and so will happen to you in my name, you will be humiliated and stripped, but how great will be the Kingdom of Heaven that I have promised you! I love you brothers and I bless you one by one, your brother Jesus. Thank you for welcoming me into this home once again." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21)), "Beloved children, thank you for having responded to my call in your hearts. Dear children, today is the third year that I am manifesting myself to you with love in this blessed house, where I have been welcomed in the love of the family. Beloved children, today you are celebrating this Easter with great joy, my dead Son has risen for you and is asking to rise with Him in your lives, come out of your tombs, believe and witness in my risen Son. My beloved children, carry and love your Cross and as the Cyrenean accompanied Jesus, so must you help your brothers. My children, the dead will join the living for this great feast and your work from today will be to work on this earth for eternal life. I love you and as Mother I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 28)), "Beloved children, thank you for being here in prayer. Dear children, your prayers console my heart and give relief to the sufferings of Jesus, who is suffering much for all the injustices and ugliness of this world, which now seems to be dominated by Satan. Soon, Jesus will come to free you from all this evil. Still, suffering and destruction will come. Beloved children, justice is upon you, open your eyes and be always with the rosary in your hand. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 30)), "Dear children, thank you for responding to my call in your hearts. Beloved children, times are hard to face and this is not the worst, for the worst is yet to come. Time seems to happen very fast to you, my Jesus is in a hurry, now apostasy is in the church and it is so clear that confusion will continue to blind you, I ask families to form prayer circles in the homes, teach your children to pray the Holy Rosary, mothers sanctify yourselves, imitating me. Now the devil is entering the families, but if you follow my instructions, he will not be able to enter. I leave you with my motherly blessing in the name of the Father of the Son of the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 3)), "Dear children, thank you for responding to my call in your hearts.  Children, what a joy for me to see you united, the people of God gathered as brothers in love and praise for God. Children, by now the times have come, the Church rejects prayers and the true doctrine of the faith, Satan thinks he has reached his goal, destroying, what was created with so much love, but know that soon my Immaculate Heart will triumph, and I want you to be sharers in this Triumph, convert by making a great cleansing with a beautiful confession, be missionaries of peace, serenity and courage in faith. My children, I am still here to love you and I place you all under my blessed mantle. Love Jesus, be faithful to Him and graces will be abundant. Now, I bless you in the name of the Father, of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 4)), "Dear brothers, thank you for being beside me in these times of torture, I am here today to tell you that this is the time of yes - yes, no - no, either with me or against me. I keep asking myself how much faith I will still find on earth, I who have made my beloved children my image, giving them the Holy Spirit to transform the Host into my living body and the wine into my blood and they betray me. No! I do not want to hear any more of this abomination. Beloved brothers and children, prepare yourselves, for soon I will come to take you where everything is ready for your protection. I will embrace you all with immense love. Now I ask you, do not abandon me and do not abandon your faith in me. Now, I will touch you one by one for my holy blessing, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 7)), "Beloved children, thank you for having responded to my call in your hearts. My beloved ones, look around you, the devil wants to take over, so I ask you to pray a lot and intensify the prayer circles. My children, be and live like the apostles in the love of God with courage, take up the weapons without fear which are faith, tolerance, patience, love, brotherhood and be light for all. Dear children, tell the world to convert quickly, for time is passing inexorably. Baptize the children and avoid their damnation, soon all that I have foretold will happen in a very short time, be ready. Fire will come down from heaven . You will be filled with the Holy Spirit. Now, I leave you with the blessing of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 11)), "Beloved children, thank you for having responded to my call in your hearts. My beloved children, thank you for having welcomed me with faith in your heart. My dear children, I am always with you so that you may not go wrong. Your way is marked, but sometimes you are confused and do not go to meet Jesus, but do not let yourselves be confused. I ask you my people, listen to my words, read the Gospel and the Word of God, it is the only way you will have, to embark on the way of holiness. My children, it is to you that I ask to help me save the Church and it is again to you that I ask to be warriors of light, today the Church is sowing confusion and it is all in your hands, go and sow the word of God, the demons are creating so much confusion. Gather in prayer circles in your families. Listen to the winds of war that are not only the atomic bombs, but the war of the world has already begun. Now, I leave you with my motherly blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 14)), "Dear children, thank you for being here in prayer. My daughter, the truth is deviated especially by my consecrated persons, I ask them to make an examination of conscience and to stand in the truth of the Gospel. Recite together with the faithful the Holy Rosary, do not leave the flock alone, but be true shepherds. Cities will be flooded. Live with your gaze turned towards heaven. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 18)), "My children, thank you for responding to My call in your hearts. My beloved ones, soon heaven will open and you will see the kingdom of God with all that has been prepared for you. Be faithful to Jesus, I call you again to urgent conversion. My beloved ones, you have no more time, soon you will see the return of my Son Jesus, His second coming will not wait, but first you will see great signs from Heaven. Behold God's justice is upon you, do not be tied to earthly things, everything will be swept away, ask yourself why these floods, these strong winds, these hurricanes, are to come and happen just to make you understand that God is the only important thing, now and always, He loves you, but many of you have lost faith because of the demons who know how to blow hard in the minds destroying thoughts. There will be a strong earthquake, pray, pray for America, because it will drink the bitter cup because of the great sins. Be strong children, for what awaits you. Now, I leave you and bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 21)), "Dear children, thank you for having responded to my call in your hearts. Beloved children, I urge you to live the messages that I am leaving you and to comment often on the Gospel. Dear children, I urge you once again to urgent conversion, do you not understand that you no longer have time? It is no longer time to waste, for it is finished, look around you, they want to destroy My Church, even from within there will be terrorist attacks from the world. Children, pray that whoever speaks will speak filled with the Holy Spirit. Defend the true Christian Faith and do not distort it. Now, I leave you with my motherly blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 25)), "Dear children, thank you for being here in prayer. How much faith I feel in your hearts! Love and courage for faith, for my Jesus and for my Church that the devil wants to destroy, be true apostles. My children, the devil wants to deceive you and now he will find all the ways to creep in, do not let him do it, pray, he is always lurking, because he knows that his time is over. I weep for everything that will happen, convert and always be faithful to the true Church. Now, I bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 28)), "Dear children, thank you for being here in prayer. My children, dear to my blessed heart, how many times have I told you to pray for these moments, now they have arrived, but how many of you feel ready to face these last times! Beloved children, I am here to protect you, soon you will have nothing left, look at the confusion that reigns on earth and around you, these are signs visible to all, where are you running to, children, what are you looking for if not for God? The devil will touch places and people you would never imagine. Children, pray, pray, pray. Now, I place my blessed mantle over you and bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])

dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 1)), "Dear children, thank you for being here in prayer. My children, what a wonderful Gift you have been given by the Father, both to you and to all those who have come to know my Son Jesus. You as instruments, always be beacons of light, never extinguish your lamps, but bring light to the world, which is love and peace. My dear little ones, how great and humble is your heart! I will protect you from every attack of the evil one, you with your Yes, you have turned on a beacon in the world and I will always be with you together with my Jesus. My children, bear witness and make everyone listen to my messages. The times will be hard, but you will not be alone, my angels will not allow you to be touched by those who are in the grip of evil. Now, I leave you with my holy blessing in the name of the Father, the Son and the Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 3)), "Dear children, thank you for listening to my call in your heart. Dear children, love my Son Jesus, change hatred with love, anger with forgiveness, selfishness with selflessness, pride with humility and have the rationality of the spirit, these are the things I ask of you, you do not have much time to convert. Please children, do not make me weep anymore and do not make the heart of Jesus suffer anymore, for you has He not already suffered enough? Hasn't humanity already done too much harm to God, who loves you, protects you and has been by your side since the first womb? Yet, how have men thanked Jesus? By blaspheming and entering eternal damnation. Why do you love the most comfortable life, claiming the graces? Open your hearts to the joy of Jesus' love and everything will be easier. My children, I am a mother and I do not abandon you. Now, I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen. I will remain with you in prayer." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 8)), "Dear children, thank you for listening to my call in your heart. Beloved children, thank you for your faith. Children, you will be entrusted with the mission of making my Son known wherever you go. Soon, those who have faith will receive the gift of the Holy Spirit and it will happen suddenly, you will feel joyful and ready to take the Word to those who do not know it. My loves, I ask you to be bound to the Gospel and to the True One and Only Doctrine of Faith. My children, I weep because I know what you will be up against, so please be ready always. The Church will undergo a great renewal, taking away what is evil and everything will return to its proper place, this task is now entrusted to you, the laity. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 11)), "My beloved children, thank you for being here in prayer, comfort my heart and that of Jesus with your presence and your prayers. My children, remember that soon God's justice will be more explosive, but do not be afraid, rather fear when you no longer feel God with you, then, yes, you will have to fear. Earthquakes will follow one another, soon the Eucharist will disappear, but be faithful and fight like soldiers, many will be the sufferings, but whoever will have believed will be saved. Now, I leave you my peace and bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 15)), "Dear children, thank you for having responded to my call in your hearts. My beloved children, how many are your sufferings, remember that there is no cross that does not lead to God, love it and carry it with love and with the certainty that Jesus is beside you. My loves, how many words have been said in these years, yet despite the significant signs, still not all hearts are converted. I have cried making you see my pain and you still do not understand, behold, the time of grace is at an end, the time of justice is upon you. I ask only for love, love even for yourselves, instead I continue to see my children going towards the road that leads to hell. Your eternal life is of great value to God, work for eternal life. Pray for the Church, where the earthquake will be strong and have serious consequences. Now, I bless you in the name of the Father, the Son of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 18)), "My dear brothers, thank you for being here in prayer. I, your Jesus, am here with you and I see your hearts. Brothers, how many are your fears, but this is the measure of your Faith. Soon, I will come to embrace you and take you to places of safety. Seeing many of My consecrated children and brothers rejecting My Mother gives Me great pain and this will be one of the main reasons for the strong earthquakes that will occur in the Church. Kneel down and pray to my Blessed Mother, so that she may intercede for your sufferings. Brothers, there will be many more noises that will shake the earth. What I had entrusted to humanity, you have reduced to a putrid world. Repent by a Holy Confession. Now, I bless you in the name of the Holy Trinity, Amen. Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 22)), "Dear children, thank you for having responded to my call in your hearts, some of you will come out of this meeting greatly changed with open hearts. Adored children, why do you still make my Son Jesus suffer? [and there Our Lady showed me a heart that she had in her hands and it was bleeding]. Look! The heart of my Son is bleeding because of the sufferings of every day and despite everything, He continues to send mercy for my beloved children. My children, soon everything will change. The Church, humanity and the world are unfortunately no longer in tune with God the Father. Many will be the events that will bring changes, but you pray, pray so much my children, because everything can be mitigated. Thank you for having welcomed me with love of heart. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 25)), "Dear children, thank you for having responded to my call in your hearts. My children, I am asking you for urgent conversion, there is no more time, after all the signs coming from Heaven why do you still not believe! Ask yourselves questions, convert, because the worst is yet to come and you are not ready. My beloved children, when the Eucharist will no longer be there, the church will no longer be called the house of God, but a simple place of prayer, do not be unfaithful, fight for the Truth. My children, remember that God is Love, Life and Truth and He is your only certainty, do not be tied to material things, for they will soon disappear. You children, understand that the only certainty is in God and not in what you build. The earth will continue to tremble. Pray for the Pope. Now, I leave you with my Holy Blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 29)), "Dear children, thank you for being gathered here in prayer and thank you for all the love I feel in your hearts. My beloved children, do not be afraid, I am here with you and I will always be. Offer to my Son your anguish and he will transform it into joy, your bad thoughts and he will transform them into thoughts of love. My children, soon you will have striking news and a great falsehood coming from the seat of Peter. Pray and forgive. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])

dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 2)), "Beloved children, thank you for being gathered here in prayer and thank you for having responded to my call in your hearts. My children, why do you still not convert completely? Amente! You must tell, especially my beloved sons (priests), to teach the word of God and speak the Gospel, I do not want to see my children fall into the abyss. Now, children, my Jesus is merciful, but wait no longer, the time has come. The earth will continue to shake more and more. Now, I leave you my peace and take it into your homes, I bless you in the name of the Father, the Son and the Holy Spirit, Amen. My children, tomorrow I will still be with you." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "Beloved children, thank you for having responded to my call in your hearts. My children, I ask you for peace, peace among men, peace in families, peace among the nations and the powerful of the world. My children, peace among men, must be beyond every nation, every religion, every race. Peace also means respect for different creeds, but you, love each other as brothers in the love of one God, Jesus made man and died for you on the cross for your salvation and for your sins, Who left His Word which is one, for all and forever. All religions cannot stand in one prayer in the House of God, My Church will be saved by your Faith. Now I bless you, in the name of the Father, the Son and the Holy Spirit, Amen. Today, many will be the graces that will descend upon you." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 9)), "Dear beloved children, thank you for having responded to my call in your hearts. My children, how much abomination there is in this world and all this causes pain to my heart and to that of my Son. My children, pray that my Son Jesus may anticipate the time of His coming. Great things do the Almighty for those who have faith. Pray for the world, especially for America. Now I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 13)), "Dear children, thank you for responding to my call in your hearts. Beloved children, everything that is happening was foretold, many are asking for signs before the coming of Jesus, but after all that is happening, the earthquakes, the waters that come down from the sky with power and enter the cities, you still do not understand, despite everything. My children, do not wait, you have no more time because your sin is too great. Pray, children, do not wait for the cold night, pray for Italy, which refuses grace, and pray for America, which has let Satan into their nation, convert. Now I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 16)), "My beloved children, thank you for having responded to my call, may peace descend in your hearts. My children, pray for the Church, pray for priests, bishops and cardinals so that they may open their hearts to grace without trivializing the sacraments, especially the Eucharist. Children, I beg you, take my hands so that I may lead you to my Son Jesus. Beloved children, I ask you to hold praying circles in homes and families so that you may be more protected; the rosary is the powerful prayer against evil, never forget this. Now, I leave you with my Holy Blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 20)), "Dear brothers, thank you for being gathered here in prayer. My brothers, how many graces you ask for, but have you asked yourselves how great is your faith? I hope to embrace you soon and I will finally be able to nurture you with the delights I have ready for you. Beloved brothers, love God in all His fullness, convert, the time is over, justice is already upon you, you will see balls of fire coming from the sky, the earth will not stop shaking, old and buried diseases will return and new diseases will appear. Pray for my apostles and those who have married God, Peter's Church will soon be inhabited by revolution, pray for the powerful of the world, that peace may reign. My brothers, why do you turn away, pretending that the world has always been like this, you do not want to change your attitude towards the immense love of God, you do not want to understand that everything that is part of this world will soon no longer exist, because it is invaded by Satan, and what do you do? Instead of following the path of the righteous, you take the most comfortable one, with the simplest things which is that of the devil and then die eternally. Fight for eternal life and do not fall into the infernal flames that, like long tongues of fire, seek your souls. Brothers, I do not say all this to frighten you, but only to shake your consciences and make you understand what awaits you, take God's way, yes, perhaps more difficult, but safe and with My help and that of My Mother, you will be safe and everything will be easier. Now I give you, My holy blessing in the name of the Father, in My Name and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 23)), "Beloved children, thank you for having responded to my call in your hearts. My beloved ones, rejoice, for soon my Son Jesus will be among you to renew the earth. The church will be renewed only when, of this old church, along with those who worship Satan, nothing will remain but dust. Pray children, pray that hearts may open to God's love, for why can't you love as He loves you with an immense love? Yet, He created you and pampered you! Pray for the Pope, who will soon be attacked. Dear children, soon the light will come in the sky and you will understand that God is here for you and then you will ask for forgiveness with your heart and He in His infinite Mercy will welcome you, but do not wait until then. Now I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 25)), "Beloved children, thank you for being here in this blessed house, I wanted this Rosary to be here again today so that once again, you may see the miracle of my tears. My children, I feel so much love, but at the same time you have a contrite heart. Dear children, how many illnesses and how many things will happen on this earth, all this has been written and will be so, but do not fear, you will have our protection, do not be afraid. Love my Son Jesus and pray, I beg you to pray a lot for Peace. Now, I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen. Our Lady laid her hands on each of us bestowing her holy blessing." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 27)), "Beloved children, thank you for having responded to my call in your hearts and for being here in prayer. Beloved children, pray, pray for the Church, trust in my Father, do not judge so that the Faith may not be harmed by judgments, but love only God, as you have been taught, follow the commandments and always be attached to the Gospel. My beloved little ones, remember that Peace among mankind and among yourselves is what I ask of you, for only through peace can everything be mitigated and it is only Peace in your lives that leads you to love. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 30)), "Dear children, thank you for being here in prayer. I look and do not see my children, how many times must I tell you to leave the things of the world and think of the spirit! My beloved ones, I who come by the grace of the Father, descend upon you to protect you and instruct you for the good of your soul, but often I am not heard, I have no more tears. Children, you must pray, pray, fast and do penances, especially for the Church, for the bishops and cardinals, you do not know what you are up against, everything is ready for war, pray, pray, pray a lot. Blessed are those who will have Faith. Now, I bless you in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 3)), "Dear beloved children, thank you for having responded to my call in your hearts. My children, how much faith and how many sorrows are in your hearts, but give everything to my Son and He will give light to your darkness. Beloved children, do not be afraid of the messages that have come from Heaven; thus it will be accomplished. I am here to save you all. They killed my Son on the cross, a terrible death for the Son of God, but this allowed a new covenant. I love you, but now heaven has joined the earth and just as the angels descend to protect you, the devil gains strength because of the libertinism of this world. Learn who hates God and who loves Him. Learn the Holy Scriptures and reflect. My loves, convert. It is time. Pray for America for her pain will be great. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 6)), "My children, thank you for being here in prayer. Where are you going! Why, do you not listen to My words of salvation! My beloved children, I have no more tears to shed for these lost children, great will be the punishment for those who have distorted the truth, these beloved children who are clouding the word of God. Children, by now justice has begun its journey, I can no longer hold the hand of justice. Children, always be faithful to God, my Son's heart bleeds because of too many sins. Convert, before your hearts are wounded. Now I leave you with my holy blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 10)), "My dear daughter, look at what is happening in the world, the roar of war is near, the earth will continue to shake as never before, everything is in great movement to arrive at the Triumph of my Immaculate Heart. All this was marked out and God's plan cannot be changed. My daughter, Jesus is ever closer and many will perceive His glorious presence. Do not turn away from the truth, but be ever closer in prayer. My beloved, pray for the ruined church and for France. Daughter, I am beside you, for I know the difficulties of the mission, but together with my Son we will give you the strength to go forward in preaching the word of God and witnessing to His love. I now bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 13)), "My children, thank you for being here in prayer. My children, great is your heart, because your renunciations have given you peace in your hearts, you are worthy of the attention of your Father who is beside you when you invoke Him. I ask all my children, be just, keep and live the Ten Commandments and the Holy Mass, where Jesus is always present. My children, everyone sees the things that are happening in the world, but often many hearts still do not draw close to God, who instead is always closer to the earth. My children, I now leave you with my Holy Motherly Blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 15)), "My beloved children, thank you for your prayers and for those who pray in the blessed places. My children, I am Mother Consoler, Queen of Angels, She who crushes the head of the serpent and this is what I will return to do and finally together with you, My Immaculate Heart will triumph. Adored children, I want saints and I want holy families. Pray the Holy Rosary every day and ask for my protection, I will give it to you. Now I bless you, in the name of the Father, the Son and the Holy Spirit, together with the prayer groups, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 20)), "Beloved children, thank you for listening to my call in your heart. My children, your daily commitment is to follow Jesus, have no remorse for those who do not believe, for those who do not love and for those who do not forgive, God's justice will be felt because He alone is the true judge. My beloved children, turn your gaze towards Heaven because it is from there that all the signs will come. Beware children, the devil is unleashed more than ever, for he knows that his play is at an end. My children, for those who have followed Jesus, for those who have abandoned everything, choosing God and not the things of the world, it is then that the Graces will be multiplied a hundredfold, a beautiful land awaits you, do not back out. My children, pray for the volcanoes that will erupt and cause catastrophes, pray for Russia and pray for the powerful of the world. Now I leave you my blessing, in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 22)), "Beloved children, thank you for being here in prayer. My children, I am happy to hear your hearts open and with great faith, pray, but unfortunately many of my children have given their souls to Satan because of all the demons on earth who are in a hurry. My children dear to my heart, this is the time of choice, choose well by reflecting, because your choice will be the mirror of your future, many are my angels who protect you, I am with you and will remain with you for all your prayer. Recite with me the Lord's Prayer. And now I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 24)), "My children, thank you for having responded to my call in your hearts. My children, beware of lies and falsehoods; know how to recognize the truth through prayer. This world is full of arrogance, wickedness, falsehood and horror, and why are you so surprised? Everything takes a different turn and everything goes wrong; you have attracted evil with your immeasurable sins. My children, I will always protect you until the end, I weep for what is to come and I would like you to be ready, but often, even today, you do not listen to Me, but I want and must save you, for you are My children and what mother likes to watch her children in danger? Now I leave you with my Holy Blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 27)), "My children, thank you for being here in prayer. My beloved ones, sometimes I see fears and torments in your hearts, but I am here near you to encourage you to go forward and to remove these fears, because my plans will come true, as is the will of Heaven, millions will come to glorify the Lord. My children, you are in the midst of the times foretold by Me in so many apparitions and you will be witnesses of the Triumph of My Immaculate Heart. Those who have chosen the King of Hell will suffer terribly, but those who have chosen God will feel peace in their hearts and will know that evil will not be able to touch them. Now I give you my Motherly Blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 31)), "My children, thank you for responding to My call in your hearts. My children, how many hearts are closed! How many believe that they must witness spectacular events, but this could happen only in your hearts, feeling the accelerated pulse, but not all are able to open their hearts to Grace. Beloved children, I beg you to convert, for those who are not ready will suffer greatly during the Warning. My children, make circles of prayer in your homes, transforming them into small churches; recite the rosary every day. Now I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "Dear children, thank you for responding to my call in your hearts. Beloved children, open your hearts to God's love and ask for protection unceasingly because you will need it. Believe in the messages that I bring you as a mother to protect you from the whirlwind in which you will gradually be enveloped. My beloved little ones, how much you speak of discernment. . ! And today I want to tell you, the Church and especially my beloved children what you must do. . Look at the children I am sending among you and see if they radiate light. It is only the light that will make you understand that they are my true messengers. Pray for the powerful of the earth and always look at the signs from Heaven, so you will understand that you are within the last times. Now I leave you with my holy blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 7)), "Beloved children, thank you for responding to my call in your hearts. My beloved ones, be true Christians, it means to entrust everything to Jesus, remove and put aside your humanity and exalt the Spirit, be fighters and courageous to witness the faith. My children, I love you and also tomorrow I will be with you. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 8)), "My dear children, thank you for opening your hearts with such joy. Pray with faith. My children, how I wish to see all my children and especially the priests so composed in the order of love for my Son Jesus. Dear children, thank you for touching Heaven, the Holy Spirit will blow upon you. I bless you in the name of the Father, the Son and the Holy Spirit. Pray to my Immaculate Heart and here where I will be many graces will descend. Amen. Holy Mary came today surrounded by numerous angels singing praises. Our Lady said that if we kneel before her statue and pray to her Immaculate Heart, she will give us many graces." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 10)), "My children, thank you for responding to my call in your hearts. Seek peace, peace in your hearts, you will find it only if you follow my Son Jesus, these are the last hours for your choice. My children, here you can be part of the Triumph of my Immaculate Heart. My loves, be strong in faith because Satan's plan is to take many souls to hell, so strengthen yourselves and open your hearts and above all make them humble. Pray, for the plague and other new diseases are coming. I love you children and do not fear, I will protect you. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 14)), "My dear children, thank you for being here in prayer. My children, these times I have been predicting for a long time and now you are in the midst of the worst period that humanity can experience. I have come to warn and instruct you, but in spite of everything, still humanity is not yet ready to witness all that is to come. I ask you, my children, once again, strengthen yourselves with prayer every day, do not listen to those who say bad things about you, but entrust everything to my Son, do not feel resentment for your brothers, but forgive, demons choose souls weak in faith. My children, pray for this earth and for this humanity that chooses earthly things and not raising the spirit, will die. Look to the heavens, for soon my Jesus will be with you and you will see new heavens is new earth. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 17)), "Beloved children, thank you for responding to my call in your hearts. My children, free yourselves from your sufferings, give everything to my Son Jesus, who in death saved you and embraced His cross with love. My children, prepare safe havens because a time will come when you will not be able to trust even my beloved children. This period of apostasy will lead you to great confusion and tribulation, but you, my children, always be attached to God's word, do not be taken in by modernism! Remember My children, the world belongs to God and He is the only master of the Universe, and not man. Attention children, attention! I bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 21)), "Dear beloved children, thank you for responding to my call in your hearts. How much faith I feel in many of you, but also so many spiritual struggles, with my Son Jesus beside you and the Holy Spirit, you will have a chance to see the Truth. Beloved children, this is the time when whoever takes the narrow way will be persecuted and those closest to you will rise up against you with insults and contempt, but remember, evil will not touch you because I will always protect you. Invoke my Immaculate Heart and I will be there. Now I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 24)), "Dear brothers, thank you for being here in prayer. My beloved ones, soon the Church will undergo a great change. My Father has sent My Blessed Mother to help you understand what prayer is for, to instruct you and to accompany you in these times. Mankind, however, is turning away, not believing and even despising this Grace. Yet it is My Mother and yours, who cares for her children and cries for lost humanity. Do not despise the Grace, stay in silence and prayer. I am with you, love me and I will lead you where all is ready. Now I bless you in the name of the Father, in my Name and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 28)), "My beloved children, thank you for listening to my call in your hearts. Pray, pray, pray for peace and for what awaits you. Pray for China because new diseases will come from there, everything is ready to affect the air by unknown bacteria. Pray for Russia because war is coming. Pray for America, it is now in great decline. Pray for the Church, because the fighters are coming and the attack will be disastrous, do not be plagued by wolves in sheep's clothing, everything, soon will have a great turning point. Look at the sky, you will see the signs of the end times. I will be with you until the end of prayer. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 28) & (dataset["author"] == "Holy Father")), "I, Almighty Father, but you do not see the wars! Why do you not understand? Pray my children, my Son loves you! I have sent Him for your salvation and you are turning away, love my Son He is your only salvation as He was once and will be again today. Oh! My Beloved Mary, born without original sin, put to work for you, and you, oh! you humanity lost to sin. Humanism has entered the Church making people believe that man is master of the world, my world has become the world of Satan, everything is in confusion. What are you doing to your children! What are you leaving to your children, without any respect, without any sacredness, without faith, teach Love and great will be the reward in the Kingdom of Heaven. I love you children, I love you! I will always protect you, be firm in the faith and I will protect you. I, your merciful Father, ask you, have mercy on my Son, do not fall into sin. I love you and bless you all and I will be with you every minute of your life, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 1)), "My dear children, thank you for responding to my call in your hearts. Beloved children, I would like to instruct you what to ask for and how to pray to the Lord Jesus Christ; Children, open your hearts in prayer. Ask God to bathe you in His light, that you may witness with courage and speak of Jesus without fear; ask for the gift of knowledge, humility and brotherhood. When all this happens, your Yes will be sincere: you will have everything you need, graces will descend upon you and you will feel joy and peace in your heart. Go to Mass because He is waiting for you. Shout to the world that my Son will soon be with you. May the blessing of the Father, of the Son and of the Holy Spirit descend upon you and your families, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 3)), "My beloved children, thank you for responding to my call in your hearts. Today, I want to bring peace into your hearts so that they may open to grace. My children, times are very hard, but I am here and I will not leave you alone, but only if you really want it. Children, pray for the Church, the world is lost in Satan's clutches, but our prayer and the Rosary will be a great protection for you and your families. Shepherds, evangelize, bring the word of God into homes, teach young people love, this is the Church, the family, the first small church, do not be afraid of being judged, but go forward with God's blessing. Now I bless you in the name of the Father, the Son of the Holy Spirit, I will be with you until the end of the prayer to bless you and the sacred objects you wear, today children will descend many graces, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 5)), "Beloved children, thank you for being here in prayer and for responding to my call in your hearts. Beloved ones, pray, pray, pray very much, that faith may return to this embittered world. My children, some of the men of the church have lost their faith. Pray much, now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 7)), "My beloved children, thank you for being gathered here in prayer with faith. At this time only prayer is needed, where are my children! Great is my suffering, because my Son Jesus has been put aside, our merciful God is about to be replaced, how many tears I have shed, even of blood, to make you understand my pain and discouragement, because there is little faith on this earth! My children, take my messages to the world, gather souls to bring to Jesus, do not be silent, but warriors of Light, tell the world to convert and to love only our One and Triune God. Now, I leave you with my holy blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 12)), "My beloved children, thank you for responding to my call in your hearts. I see my children united and my heart rejoices. My children, I call you to the love that has always united you and to prayer; do you remember my messages? Have you lived them completely? Do not forget that the devil is very strong in these times, he tempts you and forces you to disunity, he creates doubts about everything, especially by turning the truth upside down. I love you, I am your Mother, come down from Heaven to protect you; live the grace that God has allowed to send you and be courageous witnesses always. Children, I am here, do not be afraid, together with my Son we will always protect you, do not allow the great confusion generated in these times to enter your lives, but be faithful to the Word, the Gospel. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 15)), "Beloved My children, thank you for responding to My call in your hearts. My children, how great is the pain and suffering I feel every time my chosen ones are mocked, judged and looked upon as plague victims, it is all being accomplished. My son is about to be put out of the church, those who do this, continue to make the wounds of Jesus bleed even more and do not believe that soon justice will come upon them. Behold the word of God will be fulfilled. My children, remember that the Word and the Gospel are immutable. After the great sorrow, My Church will rise again with a few faithful, but true ones.  Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 19)), "My brothers, I am here with you, how small you are, you are still children, I want you to be big in faith with your children's hearts. Oh! My brothers, I ask you not to waver with the faith, or you will give space to Satan. Do not change your house and move whatever happens, but be united, my angels will protect you, soon the hand of God will be on the world, how many things are happening on earth, Oh! my church, my church has turned its back on me, but I will be reborn, I will return. My Mother! how great is her pain, but you give her love, only love, what we ask for is only love. God is good and patient, He will forgive you of all your sins, if you sincerely repent. Oh! My children, my brothers, how I love you, my angels protect you from the attacks of the earth, stay calm and trust me, I will never leave you alone, I know your hearts and I know how great is your love for me, for my Mother and my Father. Stay anchored in the faith, it is your only salvation together with prayer. Dear brothers, I love you and I am close to you today and always. Now, I bless you all, in the name of the Father, in my name and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 23)), "My daughter, thank you for your prayers, do not worry about the things of the world, but continue in prayer. Shout out to the world that those who are faithful to God will soon feel joy, lightheartedness and love, but those who turn away and worship other gods will feel their hearts darken and will feel despair, discouragement and sadness. The return of the Son of God is near, rejoice and announce the new Jerusalem. My daughter, how much pain I feel, for not having fulfilled my request for consecration, remind those who do not want to listen to me, that faith is also courage and witness, God throws up the lukewarm. Now I leave you with my motherly blessing, in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 26)), "My beloved children, thank you for having responded to my call in your hearts. My children, how much peace I feel in your hearts despite the sad moments, but I beg you, strengthen your faith and prayer, I ask for prayer circles in your homes. At this time my angels are fighting against the angels of evil, apostasy continues to hover in the Church, but only with prayer can everything return to the way Jesus wanted it. My children, many will be the graces that will descend for those who have faith, my Immaculate Heart will soon triumph. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 30)), "My daughter, thank you for being present in prayer, many will be the sorrows that will come, but do not tire yourself, take refuge in my Immaculate Heart and there you will find comfort. My daughter, the persecution of Christians will soon begin, so be very careful everyone, take my advice as a Mother and do not turn away. Have patience, love and charity for your brothers because dark times will come when you will not be found. America will suffer the greatest pain because of laws against God. Always be faithful to the true Magisterium of the Church, God is the only one you must trust, stay away from false modernist ideologies, otherwise you will be blind leading other blind people. I love you and with Maternal Love I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 31)), "My beloved children, thank you for being here in prayer, oh! how much you lighten my pain and that of my Son! My beloved ones, what is mankind doing? It is accepting, exalting and proclaiming sin as something pleasing to God, but it is not so, for these the gates of hell will open. My children, come often to visit Me in this place blessed by the Father. I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 3)), "Dear children, thank you for having responded to my call in your hearts. My children, how much joy I feel in seeing so many shepherds in this blessed place and how many children I see full of faith praying, staying close to my Son Jesus, who especially in these times, a lance still pierces his heart. Beloved children, St. Joseph is also here, and he is with me to pray over you. My beloved ones, invoke the Holy Spirit so that you may be enlightened in spirit and heart. My children, do not be afraid, I am with you, the devil cannot harm those who are faithful to God. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 5)), "My children, thank you for responding to My call in your heart. My daughter, how great and heavy is the mission entrusted by Heaven, but I will help you and I will always be beside you. The truth is only one, Love for God, who is the center of everything, but not all open their hearts and allow themselves to be invaded by the flame of the Holy Fire. Please, children, do not let the flame go out. How many of my children are harassed by Satan who works in their minds with negative thoughts against their brothers, thoughts of persecution and enmity, but only the light of the Spirit will be able to illuminate you giving you peace. Soon a great light a will appear in the sky and God will thunder in all his glory. Now I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 9)), "Dear children, thank you for having responded to my call in your hearts. My dear children, pray, pray, pray so much for peace, peace among brothers and peace in the world. My beloved ones, in suffering, take refuge in my Immaculate Heart and in that of my Son, cry out the truth and tell that my Son Jesus is love, not pain, He is joy and not sadness, He is union and not disunion, do not fall into the trap of Satan who wants to destroy everything good that has been created. I am with you and I bless you in the name of the Father, the Son and the Holy Spirit, Amen. " , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 12)), "Beloved children, thank you for having responded to my call in your hearts. My children, hard times await you, give your hearts to my Son, He alone is your only salvation. Demons are unleashed in the world taking away so many souls, I beg you my children, feed on the body of my Son Jesus, God looks at this lost humanity with great sorrow. My beloved ones, I am beside you and bless you one by one, so that the Holy Spirit may open your hearts completely. Behold, the whole Church is being destroyed to be reborn stronger than before, pray, pray, pray. The winter that is coming will be hard, all the crops will be burnt by the frost and the calamities will be stronger and stronger, pray so much. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 16)), "Beloved children, thank you for having responded to my call in your hearts. My dear children, open your hearts to my Son Jesus, increase your faith, set fire to the flame of love for God, soon Jesus will be with you, be ready and be filled with His Love. Dear children, pray the Holy Rosary and organize prayer circles in your homes. Pray for Spain, remember that wars, calamities and all that will happen will open the doors to the Antichrist. I love you, children, and I will always be with you; today many graces will descend on the people present. Now I give you my motherly blessing in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 19)), "Beloved children, thank you for having responded to my call in your hearts. My children, many will be the souls that I will take with me, for they are good and with us they will find peace, but I will make unassailable those who are strong in faith and following the Gospel will serve God with their witness and strength in Truth. Beloved children, when Jesus was crucified giving his life for you, the high priests asked for a sign, but he refused and was not believed. After two thousand years, still today some priests ask for signs, but they do not understand that the Lord acts only in open hearts. Pray and Forgive. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 23)), "My brothers, thank you for being here in prayer, I am with you, open your hearts and let my light in, so that you may look at everything differently with the eyes of the spirit and no longer with those of reason. Too much reasoning distances you from me and from each other, brothers. My beloved ones, be faithful to God at all hours of the day, so that when I come you may enter the new land, where joy and love will be the only good that you will find. Brothers, your whole life should be based on Love. I was born for Love and I died for Love, but in this humanity, it seems that Love is no longer part of it, and yet you often say that you love Me! But why, instead, do I see only feelings of pride, envy and jealousy? Remember that God will judge by how much Love you have given. Now I bless you in the name of the Father, in my name and in the name of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 26)), "My dear children, thank you for having responded to my call in your hearts. My beloved ones, because of dullness you do not see what is happening in the world, because you do not believe what you touch with your hands, but I tell you my children, God's anger is already upon you to make you understand that He is also just. Beloved children, come closer to God, begin to love Jesus, do not be afraid, with Him at your side you will be better. These are also times of Grace, pray with a pure heart and you will see wonders. I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 30)), "My children, your Jesus is here with you, feel comforted by My Love, how many of My children will be hated starting from the hierarchies of the Church, they will hate you in My Name, the injustice will be great. My children, how many theologians! Oh! what pain I feel in my heart, it is terrible, theology closes the hearts of all, they have not understood my love for you and they have not understood your love for me. My children, my brothers, you have not yet seen anything of what is to come, love my cross of love, but also the bitter one, I will be beside you, nothing will be greater than me in your lives, I will be with you to protect you, no one will be able to touch you, not even with a finger, and no hair will be removed from these my beloved children. How little faith I see in those who enter the Churches, say they pray, but then, blinded by hatred, pride and selfishness, they rail against my beloved children. Oh! dear children, your sorrow is my sorrow, your weeping is my weeping, but your victory will be my victory with you, now and forever, Amen. Verily I say unto you, Rejoice, for yours shall be the kingdom of heaven. Now I bless you and touch you one by one, in the name of the Father, in My name and of the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 3)), "Dear children, thank you for having responded to my call in your hearts. My beloved children, I beg you, live your Priesthood with me with courage, do not be proud to the point of letting souls go into darkness, confusion and ignorance. Do not change anything of the Gospel, of the Word of God and of the Holy Mass where my Son Jesus is alive, woe to him who will leave souls to perdition because it will be your responsibility. Dear children, when you ask Jesus to come back, know that He is already in you, let Him be born in your heart. Now I bless you in the name of the Father, of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 7)), "My beloved children, thank you for responding to my call in your hearts. My beloved children, soon my Jesus will return, but how much faith will He find! I see, even more today, how many of the Lord's workers are turning away from my Immaculate Heart because of the words of blasphemers, profaners and heretics. My children, pray for America, for because of the change of events, so many nations will weep. The Church will suffer a strong attack. Children, be faithful to the Gospel and to the Word of God. Now, I touch you one by one and bless you in the name of the Father, the Son, and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 8)), "Beloved children, thank you for this feast and thank you for bringing joy to my heart that is tortured for these times. Children, they want to remove me from the throne... I, Mary Immaculate, Co-redemptrix, Queen of the Angels of Heaven and Earth, but Satan will not prevail and your devotion will be ever greater. Continue with the recitation of the Holy Rosary. Tonight, graces will descend for some of you. I now bless you in the name of the Father, the Son and the Holy Spirit. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 14)), "Children, thank you for being here in prayer. Beloved children, let Jesus be born in your hearts; only in this way will you be able to face the darkness that clings to you. Soon, the cross will appear in the sky and thus each one will see his own life and realize how merciful God is, if you repent of your sins. Open your hearts and let us pray even more this Christmas to regain strength in faith. God's wrath is upon you; prepare yourselves for worse times and strengthen yourselves. Children, I love you and as a Mother, I anoint you with Blessings, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 17)), "My beloved children, thank you for being here in prayer. My children, how much suffering I see in your fragile hearts, evil destabilizes you, but I beg you, continue with unceasing prayer, now more than ever. My children, do not be proud and arrogant and look into the depths of your consciences, learn to ask forgiveness if you have sinned in this, otherwise you will not see the Kingdom of God. Children, my immaculate heart is grieving because my children are being lost. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 21)), "Beloved children, thank you for having responded to my call in your hearts. Beloved children, the coming of my Son Jesus is approaching, be ready to welcome Him in your hearts, in your lives and in your homes. My beloved ones, how many lights I see on the Christmas trees and in the streets, but few in your hearts, remember children, be light for your brothers, bright lights and not the deepest darkness that at this time reigns in your lives. Now I leave you and I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 22)), "My dear children, thank you for having responded to my call in your hearts. My beloved little ones, sweeten my sorrow with your prayer, such is the faith I feel in your hearts. My children, I would like you to look at the cave where the Son of God was born, give me your hands and I will lead you to that poor little bed, there you will learn humility, which will make you walk on the way to God. I love you all and with my Jesus in my arms, I will pass by to bless each of you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 25)), "" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 28)), "" , dataset["text_pl"])


dataset["text"] = dataset["text"].str.replace("Amen\"", "Amen.")
dataset["text_en"] = dataset["text_en"].str.replace("Amen\"", "Amen.")



dataset.to_csv("trevignano2019_cleaned.csv", encoding="utf-8", index=False)




















































