# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator



dataset = pd.read_csv("august_cleaned.csv", encoding="utf-8")

dataset["text_pl"] = ""
dataset["text_en"] = ""
dataset["text_it"] = ""
dataset["month_string"] = "August"

dataset["author"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 3)), "Holy Mary", dataset["author"] )
dataset["author"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 7)), "Holy Mary", dataset["author"] )
dataset["author"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 11)), "Holy Mary", dataset["author"] )
dataset["author"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 15)), "Holy Mary", dataset["author"] )
dataset["author"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 17)), "Holy Mary", dataset["author"] )
dataset["author"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 21)), "Holy Mary", dataset["author"] )
dataset["author"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 24)), "Holy Mary", dataset["author"] )
dataset["author"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 28)), "Holy Mary", dataset["author"] )
dataset["author"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 31)), "Holy Mary", dataset["author"] )



# ITALIAN
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 3)), "Cari figli, grazie per essere qui nella preghiera e per aver ascoltato la mia chiamata nel vostro cuore. Amati figli miei, vi chiedo di essere pronti perché l’avvertimento è molto vicino. Molti torneranno a Dio, anche coloro che non credono, in particolare i sacerdoti che non credono a tutto ciò che vivete in questo momento. Alcuni troveranno qualcosa per stravolgere ciò che sarà stato visto (dell’avvertimento) e non vorranno ammettere che Dio può tutto, e in quel momento avranno scelto. Io, Madre di Dio e Madre vostra, voglio custodirvi per i tempi terribili che arriveranno. Voglio indicarvi che presto ci saranno guerriglie nel mondo, ma questo sarà il momemto in cui arriverà l’anticristo e si presenterà come uomo di pace. Attenzione figli, non fatevi fuorviare la mente, ma siate fedeli anche quando il Cattolicesimo diventerà paganesimo e protestantesimo. Voi siate sempre con il Vangelo e con il Rosario in mano e non distraetevi. Figli, voglio salvarvi tutti e vi chiedo di testimoniare.  Ora vi lascio con la mia benedizione materna nel nome della Santissima Trinità. Pregate per l’umanità perduta e Io pregherò insieme a voi. La Madonna dice che oggi scenderanno delle grazie tra di voi.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 7)), "Figli miei, grazie per avere ascoltato la mia chiamata nel vostro cuore e per aver piegato le ginocchia. Figli amati, pregate tanto perché tutto è nel suo compimento, ho bisogno di voi, ho bisogno di uomini di  fede vera, così come Gesù disse ai suoi apostoli. Io dico a voi: alzatevi e andate tra le genti e parlate di Dio, fate uomini santi, non temete nulla perché mio Figlio sarà con voi. Figli miei, la Mia presenza nel mondo è una preparazione per la venuta di Gesù, che è sempre più vicina, non preoccupatevi di lasciare le cose terrene, famiglia, amicizie, ma andate e insegnate con coraggio e se chi vi ascolterà continuerà ad avere il cuore chiuso, pregate solo per loro e andate avanti ad evangelizzare, Io sarò con voi. Prendete le distanze da tutto ciò che non viene da Dio, perché Gesù dice: chi soffrirà con me e per me entrerà nel mio regno, ma chi non vorrà gioire con me attenderà il mio giudizio, raccontate di Dio che è tanto misericordioso, ma è anche giusto ed Io vi sto preparando ad essere come Lui, perdonate e siate giusti. La Cina subirà le sue malefatte, pregate per il luogo dove è nato Gesù perché ci saranno guerriglie. Ora vi benedico nel nome della Santissima Trinità, Padre, Figlio e Spirito Santo.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 11)), "Figli amati, grazie per aver ascoltato la mia chiamata nel vostro cuore. Amati miei bambini, pregate tanto affinché molti dei vostri fratelli abbiano la forza di respingere il male. Guardate il mondo, sta bruciando, i mari e le acque entrano nelle case, siete all’apice del caos. Figli miei, pregate affinché tutti possano riconoscere l’unico Dio. In questi periodi molti si rivolgono alle false dottrine che stanno travolgendo l’unica verità. Figli, la situazione non sta migliorando, ma sta peggiorando sempre di più, facendo crollare l’economia, il comunismo sta prendendo piede e questo è uno dei motivi per cui vi dico che presto sarete costretti a nascondervi per le messe, ricordate anche, che voi siete stati scelti come testimoni di tutto ciò che è stato predetto, quindi siate forti nella fede, i miei angeli ed arcangeli vi proteggeranno, siamo alla battaglia finale, non abbiate mai paura. Pregate per la Turchia. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 15)), "Amati figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, Io Assunta in anima e corpo, così come mio Figlio, per il privilegio concessomi dalla resurrezione di Gesù, sono qui a chiedervi: non mostrate la vostra debolezza   perché il demonio vi attacca per farvi precipitare nel peccato, fate attenzione, la vostra conversione deve essere ora, non domani, ma ora. Vi chiedo di aumentare la vostra spiritualità che può avvenire solo con la preghiera assidua, dovrete essere come coloro che sono già nel regno di Dio, pieni di gioia, di amore, di fratellanza e di Lodi al Signore, solo così potrete essere forti per tutto ciò che accadrà. Figli, ormai è tutto pronto, i nemici avanzano e arriveranno dal mare. Figli miei, tutto ciò che stato predetto lo state vedendo con i vostri occhi, eppure, molti ancora non credono. Io, Madre di tutti voi, vi dico: presto ci sarà lo scisma nella chiesa, tutto precipiterà, il Padre Mio farà tremare le sue fondamenta. Dico ai miei figli prediletti (sacerdoti) che seguono il vero magistero: non abbiate paura perché voi farete rinascere la mia Chiesa più rigogliosa, insieme ai miei fedeli. Figli miei, in questo momento sarete perseguitati dai vostri amici e familiari, ma i miei angeli vi proteggeranno sempre, ricordate che il dolore e la sofferenza offerta in spirito di fede è gradita a Dio, per la vostra purificazione. Ora vi lascio con la mia Santa benedizione nel nome del Padre, del Figlio e dello Spirito Santo, Amen. E’ presente Gesù che mi chiede di recitare insieme a Lui l’Ave Maria e poi dice: nella preghiera dell’Ave Maria ci sono le più belle e gloriose parole degne rivolte alla Mia mamma. Vi benedico!", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 17)), "Figli miei amati, grazie per essere qui nella preghiera e per avere ascoltato la mia chiamata nel vostro cuore. Figli miei, vedo che non siete ancora pronti, ma vi chiedo di non rimandare ciò che potreste fare ora, non avete più tanto tempo, sistemate le cose al più presto, soprattutto ciò che turba il vostro cuore, fate una buona confessione, seguite il vero magistero della Chiesa, convertitevi presto perché non c’è più tempo, pensate di più alla vostra vita spirituale. Figli miei, il fragore delle guerre inizia a farsi sentire, ma non capite che il mondo che conoscete non ci sarà più? Mio Figlio Gesù arriverà nella giustizia, questa umanità non si libera dal peccato e allora vi chiedo: figli,  fate  attenzione, la strada da intraprendere è quella del bene e se vi chiedete quale sia, io vi dico di seguire il vangelo e i 10 comandamenti e chi non avrà paura e rafforzerà la propria fede , avrà grazie in quantità, quindi vi chiedo di stare nell’amore di Dio. Ora vi benedico, nel nome della Santissima Trinità, Padre, Figlio e Spirito Santo. Molte grazie scenderanno su di voi.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 21)), "Figli miei amati, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, questi sono i tempi predetti e voi siete stati scelti come testimoni. Presto, sentirete e vedrete guerriglie ovunque, i terremoti si susseguiranno uno dietro l’altro fino a quando arriverà quello peggiore. Figli miei, abbiate fede, pregate, pregate, pregate molto, solo così riuscirete a proteggervi, ormai ciò chi arriverà non potrà essere mitigato, ma voi non dovete temere nulla, amate Dio, continuate i cenacoli di preghiera affidandovi solo a Lui e alla sua infinita misericordia. Non arretrate mai, ma andate avanti con forza nell’unica verità. Vi chiedo figli: consacratevi a me tutti i giorni, vostra Madre, ed Io metterò il mio manto intorno a voi per proteggervi sempre. Non abbiate mai paura. Pregate per la Chiesa perché la confusione dilaga.  Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 24)), "Figlia mia, grazie per avermi accolta nel tuo cuore. Vengo a te per avvertire, ancora una volta, i tuoi fratelli di stare uniti. I tempi che arriveranno saranno peggiori di questi, le catastrofi alle quali assisterete vi faranno molto male, Io piango perché vedo tutto questo, vedo anche come il peccato dilaga nel mondo, ormai non c’è più coscienza, non c’è più rispetto gli uni con gli altri, siete confusi e spaventati, faticate e vi disperate senza capire che Gesù è l’unica via, verità e vita. Non tutte le cose vi sono state rivelate, piano piano quando sarete forti e in grado di rendervi conto, altre saranno le cose che saprete. Figlia mia, devi dire ai tuoi fratelli di non abbandonare la fede, ma di aggrapparsi ad essa, dovrete perdonarvi l’uno con l’altro, perché quando sarà il momento dovrete essere pronti. Presto i tempi saranno maturi per l’ingresso dell’anticristo, sarà un uomo molto vicino alla chiesa, sarà il mediatore di pace durante la guerra e lì capirete che non dovrete mai guardarlo negli occhi, non fatevi illudere dal suo modo amorevole. Figlia mia, tutto questo durerà poco, quindi siate forti e luci accese per il mondo, la preghiera comunitaria vi aiuterà, non isolatevi, ma siate sempre in comunione con i vostri fratelli.  Pregate molto per la chiesa, per l’Italia perché ci sarà la persecuzione dei cristiani e per l’America che ha voltato le spalle a Dio dilagando e amando il peccato.  Ora ti benedico insieme al tuo sposo nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 28)), "Figli miei amati dal cielo, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, sento la vostra paura e la vostra sofferenza, ma sulle sacre scritture non era stato già predetto tutto? Figli miei, Gesù vi ha preparati da tempo, eppure, voi che non siete stati saldi nella fede adesso avete paura. Ricordate sempre che Io vi ho chiamati uno per uno e sto preparando il mio popolo affinché tanti miei figli, formino delle famiglie con madri, padri e fratelli. La persecuzione sarà grande, soprattutto quando le chiese verranno distrutte da esseri immondi, ma siate uniti, perché Io vi proteggerò. Ormai il peccato è grande, ma così grande che solo la preghiera e l’affidamento potrà salvarvi. Ora vi lascio con la mia benedizione materna, nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 31)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, piango perché so verso quale dolore andate incontro, tutto ciò è stato predetto, ma voi perdete il vostro tempo con le cose del mondo. Non vi ha lasciato detto il mio Gesù, chiedete e vi sarà dato? Figli cari, restate fedeli alla Parola del mio Signore e Lui abbonderà di misericordia e di provvidenza. Figli del mio cuore, non conformatevi a ciò che vi dice il mondo, non correte da chi vi assicura  protezione, perché solo il mio Gesù protegge, assiste, vi aiuta e vi ama. Continuate ad essere nel vero magistero della fede e non lasciatevi ingannare. Ora vi benedico nel nome del Padre del Figlio e dello Spirito Santo, amen.", dataset["text_it"])





# ENGLISH
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 3)), "Dear children, thank you for being here in prayer and for listening to my call in your hearts. My beloved children, I ask you to be ready because the warning is very near. Many will return to God, even those who do not believe, especially the priests who do not believe all that you are experiencing at this time. Some will find something to distort what will have been seen (of the Warning) and will not want to admit that God can do everything, and at that moment they will have chosen. I, Mother of God and your Mother, want to guard you for the terrible times that will come. I want to point out to you that soon there will be war in the world, but this will be the moment when the antichrist will come and present himself as a man of peace. Be careful children, do not let your minds be misled, but be faithful even when Catholicism becomes paganism and Protestantism. Always be with the Gospel and the Rosary in your hands and do not be distracted. My children, I want to save you all and I ask you to have faith.  Now I leave you with my motherly blessing in the name of the Most Holy Trinity. Pray for lost humanity and I will pray with you. Our Lady says that graces will come down among you today.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 7)), "My children, thank you for having listened to my call in your hearts and for having bowed your knees. Beloved children, pray so much because everything is in its fulfillment, I need you, I need men of true faith, just as Jesus said to His apostles. I say to you: rise up and go among the nations and speak of God, make holy men, fear nothing because my Son will be with you. My children, My presence in the world is a preparation for the coming of Jesus, which is ever closer, do not worry about leaving earthly things, family, friendships, but go and teach with courage and if those who listen to you continue to have closed hearts, pray only for them and go ahead to evangelize, I will be with you. Distance yourselves from everything that does not come from God, because Jesus says: whoever suffers with me and for me will enter my kingdom, but whoever does not want to rejoice with me will await my judgment, tell about God who is so merciful, but He is also just and I am preparing you to be like Him, forgive and be just. China will suffer for its wrongdoings, pray for the place where Jesus was born because there will be a war. Now I bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 11)), "Beloved children, thank you for listening to my call in your hearts. My beloved children, pray so much that many of your brothers will have the strength to reject evil. Look at the world, it is burning, the seas and waters are entering homes, you are at the height of chaos. My children, pray that all may recognize the one God. In these times many turn to false doctrines that are overwhelming the one truth. My children, the situation is not getting better, it is getting worse and worse, collapsing the economy, communism is taking hold and this is one of the reasons I tell you that soon you will be forced to hide for the masses, remember also, that you have been chosen to witness all that has been foretold, so be strong in faith, my angels and archangels will protect you, we are at the final battle, never fear. Pray for Turkey. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 15)), "Beloved children, thank you for having responded to my call in your hearts. My children, I, the Assumed One in body and soul, as well as my Son, by the privilege granted me by Jesus' resurrection, am here to ask you: do not show your weakness because the devil attacks you to make you fall into sin, be careful, your conversion must be now, not tomorrow, but now. I ask you to increase your spirituality which can only happen with unceasing prayer, you must be like those who are already in the kingdom of God, full of joy, love, brotherhood and praise to the Lord, only in this way can you be strong for everything that will happen. My children, everything is now ready, the enemies are advancing and will come from the sea. My children, all that has been foretold you are seeing with your own eyes, yet, many still do not believe. I, Mother of you all, tell you: soon there will be schism in the Church, everything will fall apart, My Father will make its foundations tremble. I say to My beloved sons (priests) who follow the true Magisterium: do not be afraid because you will make My Church reborn more abundant, together with my faithful. My children, at this time you will be persecuted by your friends and family, but my angels will always protect you, remember that pain and suffering offered in a spirit of faith is pleasing to God, for your purification. Now I leave you with my Holy Blessing in the name of the Father and the Son and the Holy Spirit, Amen. Jesus is present and asks me to recite the Hail Mary with Him and then says: in the prayer of the Hail Mary there are the most beautiful and glorious worthy words addressed to My Mother. I bless you!", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 17)), "My beloved children, thank you for being here in prayer and for having listened to my call in your hearts. My children, I see that you are not yet ready, but I ask you not to postpone what you could do now, you do not have much time left, settle things as soon as possible, especially that which troubles your heart, make a good confession, follow the true Magisterium of the Church, convert soon because there is no more time, think more about your spiritual life. My children, the noise of the wars is beginning to be heard, but do you not understand that the world you know will no longer exist? My Son Jesus will come in justice, this humanity does not free itself from sin and so I ask you: children, pay attention, the way to take is the way of good and if you wonder which it is, I tell you to follow the gospel and the 10 Commandments and whoever will not be afraid and will strengthen his faith, will have graces in abundance, so I ask you to stay in God's love. Now I bless you, in the name of the Most Holy Trinity, Father, Son and Holy Spirit. Many graces will descend upon you.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 21)), "My beloved children, thank you for responding to my call in your hearts. My children, these are the times foretold and you have been chosen as witnesses. Soon, you will hear and see warfare everywhere, earthquakes will follow one after another until the worst one comes. My children, have faith, pray, pray, pray a lot, only in this way will you be able to protect yourselves, by now that which will come cannot be mitigated, but you must not fear anything, love God, continue the prayer circles entrusting yourselves only to Him and to His infinite mercy. Never turn back, but go forward with strength in the one truth. I ask you, children: consecrate yourselves to me, your Mother, every day and I will put my mantle around you to protect you always. Never be afraid. Pray for the Church because confusion is rampant.  Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 24)), "My daughter, thank you for welcoming me into your heart. I come to you to warn, once again, your brothers to stay united. The times to come will be worse than these, the catastrophes you will witness will hurt you very much, I weep because I see all this, I also see how sin is spreading in the world, by now there is no more conscience, no more respect for one another, you are confused and frightened, you struggle and despair without understanding that Jesus is the only way, truth and life. Not all things have been revealed to you, slowly when you are strong and able to realize, other things will be the things you will know. My daughter, you must tell your brothers not to abandon the faith, but to cling to it, you will have to forgive one another, because when the time comes you must be ready. Soon the time will be ripe for the entrance of the antichrist, he will be a man very close to the church, he will be the mediator of peace during the war and there you will understand that you must never look him in the eyes, do not be deceived by his loving way. My daughter, all this will last for a short time, so be strong and lighted lights for the world, community prayer will help you, do not isolate yourself, but always be in communion with your brothers.  Pray a lot for the church, for Italy because there will be persecution of Christians and for America that has turned its back on God by spreading and loving sin.  Now I bless you together with your spouse in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 28)), "My beloved children from Heaven, thank you for answering my call in your hearts. My children, I feel your fear and suffering, but was not everything already foretold in the Holy Scripture? My children, Jesus has been preparing you for a long time, yet, you who have not been steadfast in faith are now afraid. Always remember that I have called you one by one and am preparing My people so that many of My children will form families with mothers, fathers and brothers. Persecution will be great, especially when the churches are destroyed by unclean beings, but be united, for I will protect you. By now the sin is great, but so great that only prayer and trust can save you. Now I leave you with My motherly blessing, in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 31)), "My children, thank you for having responded to My call in your hearts. My children, I weep because I know what sorrow you are heading for, all this has been foretold, but you waste your time with the things of the world. Has not my Jesus left you saying, ask and it will be given you? Dear children, remain faithful to the Word of my Lord and He will abound in mercy and providence. Children of my heart, do not conform to what the world tells you, do not run to those who assure you of protection, for only my Jesus protects, assists, helps and loves you. Continue to be in the true teaching of the faith and do not be deceived. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])


# POLISH
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie i że słuchacie mojego wołania w waszych sercach. Moje kochane dzieci, proszę was, abyście byli gotowi, ponieważ ostrzeżenie jest bardzo bliskie. Wielu powróci do Boga, nawet ci, którzy nie wierzą, szczególnie księża, którzy nie wierzą we wszystko, co przeżywacie w tym czasie. Niektrórzy znajdą sposób, by zniekształcić to, co zostanie pokazane (z Ostrzeżenia),nie będą chcieli przyznać, że Bóg jest wszechmocny i w tym momencie dokonają wyboru. Ja, Matka Boga i wasza Matka, chcę was strzec w tych nadchodzących strasznych czasach. Chcę wam wskazać, że wkrótce na świecie wybuchnie wojna, będzie to także moment, w którym przyjdzie Antychryst i przedstawi się jako człowiek pokoju. Strzeżcie się dzieci, nie dajcie się zwieść waszym umysłom, lecz bądźcie wierni nawet wtedy, gdy katolicyzm staje się pogaństwem i protestantyzmem. Zawsze bądźcie z Ewangelią i Różańcem w rękach i nie rozpraszajcie się. Dzieci moje, chcę was wszystkich zbawić i proszę was, abyście mieli wiarę.  Teraz zostawiam was z moim matczynym błogosławieństwem w imię Trójcy Przenajświętszej. Módlcie się za zagubioną ludzkość, a ja będę modlić się z wami. Matka Boża mówi, że dziś zstąpią na was łaski.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 7)), "Dzieci moje, dziękuję wam za to, że wsłuchaliście się w moje wołanie w waszych sercach i że uklęknęliście. Umiłowane dzieci, módlcie się mocno, bo wszystko się wypełnia, potrzebuję was, potrzebuję ludzi prawdziwej wiary, tak jak Jezus powiedział do swoich apostołów. Mówię wam: powstańcie i idźcie między narody i mówcie o Bogu, czyńcie świętymi ludzi, nie bójcie się niczego, bo mój Syn będzie z wami. Moje dzieci, moja obecność na świecie jest przygotowaniem na Przyjście Jezusa, które jest coraz bliżej, nie bójcie się zostawić rzeczy ziemskich, rodziny, przyjaźni, ale idźcie i nauczajcie z odwagą, a jeśli ci, którzy was słuchają nadal mają zamknięte serca, módlcie się tylko za nich i idźcie ewangelizować, będę z wami. Oddalcie się od wszystkiego, co nie pochodzi od Boga, bo Jezus mówi: kto ze Mną i dla Mnie cierpi, wejdzie do mojego Królestwa, ale kto nie chce się ze Mną radować, będzie czekał na mój sąd, opowiadajcie o Bogu, który jest tak miłosierny, ale jest też sprawiedliwy i przygotowuję was, abyście byli jak On, przebaczajcie i bądźcie sprawiedliwi. Chiny będą cierpieć za swoje złe uczynki, módlcie się za miejsce, gdzie urodził się Jezus, bo tam będą działania wojenne. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca, Syna i Ducha Świętego.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 11)), "Umiłowane dzieci, dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Moje kochane dzieci, módlcie się mocno, aby wielu waszych braci miało siłę do odrzucenia zła. Spójrzcie na świat, on płonie, morza i wody wdzierają się do domów, żyjecie w szczycie chaosu. Dzieci moje, módlcie się, aby wszyscy mogli rozpoznać jedynego Boga. W tych czasach wielu zwraca się ku fałszywym doktrynom, które przytłaczają jedyną Prawdę. Moje dzieci, sytuacja nie poprawia się, jest coraz gorzej, z powodu załamania załamanie gospodarki, komunizm bierze górę i to jest jeden z powodów, dla których mówię wam, że wkrótce będziecie zmuszeni ukrywać się przed masami, pamiętajcie również, że zostaliście wybrani, aby być świadkami tego wszystkiego, co zostało przepowiedziane, więc bądźcie silni w wierze, moi aniołowie i archaniołowie będą was chronić, jesteśmy w ostatecznej bitwie, nigdy się nie bójcie. Módlcie się za Turcję. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 15)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, ja, Wniebowzięta z ciałem i duszą, a także mój Syn, dzięki przywilejowi, jaki daje mi zmartwychwstanie Jezusa, jesteśmy tutaj, aby was prosić: nie okazujcie swojej słabości, ponieważ diabeł atakuje was, abyście popadli w grzech, bądźcie ostrożni, wasze nawrócenie musi być teraz, nie jutro, ale teraz. Musicie być jak ci, którzy już są w Królestwie Bożym, pełni radości, miłości, braterstwa i uwielbienia dla Pana, tylko w ten sposób możecie być gotowi na wszystko, co się wydarzy. Moje dzieci, wszystko jest już przygotowane wrogowie nadejdą od strony morza. Dzieci moje, wszystko, co zostało przepowiedziane, widzicie na własne oczy, a jednak wielu jeszcze nie wierzy. Ja, Matka was wszystkich, mówię wam: wkrótce nastąpi rozłam w Kościele, wszystko się rozpadnie, Mój Ojciec wstrząśnie jego fundamentami. Mówię do moich umiłowanych synów (kapłanów), którzy podążają za prawdziwym Magisterium: nie lękajcie się, bo razem z moimi wiernymi sprawicie, że mój Kościół odrodzi się bardziej bujny. Moje dzieci, w tym czasie będziecie prześladowani przez waszych przyjaciół i rodzinę, ale moi aniołowie zawsze będą was chronić, pamiętajcie, że ból i cierpienie ofiarowane w duchu wiary jest miłe Bogu, dla waszego oczyszczenia. Teraz zostawiam was z moim Świętym Błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen. Jezus jest obecny i prosi mnie, abym odmówiła z Nim Zdrowaś Maryjo, a następnie mówi: w modlitwie Zdrowaś Maryjo są najpiękniejsze i najchwalebniejsze słowa skierowane do Mojej Matki. Błogosławię cię!", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 17)), "Moje kochane dzieci, dziękuję wam, że jesteście tutaj na modlitwie i że wsłuchaliście się w moje wołanie w waszych sercach. Dzieci moje, widzę, że nie jesteście jeszcze gotowi, ale proszę was, abyście nie odkładali tego, co moglibyście zrobić teraz, nie zostało wam wiele czasu, uporządkujcie sprawy jak najszybciej, zwłaszcza to, co trapi wasze serce, spowiadajcie się dobrze, postępujcie zgodnie z prawdziwym Magisterium Kościoła, nawróćcie się szybko, bo nie ma już czasu, myślcie więcej o waszym życiu duchowym. Moje dzieci, słychać już odgłosy wojen, ale czy nie rozumiecie, że świat, który znacie, nie będzie już istniał? Mój Syn, Jezus przyjdzie w sprawiedliwości, ta ludzkość nie uwalnia się od grzechu i dlatego proszę was: dzieci, uważajcie, drogą do celu jest ścieżka dobra, a jeśli zadajecie sobie pytanie, która to ścieżka, to mówię wam, abyście szli za Ewangelią i 10 przykazaniami, a kto nie będzie się bał i umocni swoją wiarę, będzie miał łaski w obfitości, dlatego proszę was, abyście trwali w miłości Bożej. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego. Wiele łask zstąpi na was.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 21)), "Moje kochane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, to są to przepowiadane czasy, a wy zostaliście wybrani na świadków. Wkrótce zewsząd usłyszycie i zobaczycie działania wojenne, trzęsienia ziemi będą następowały jedno po drugim, aż nadejdzie to najgorsze. Moje dzieci, miejcie wiarę, módlcie się, módlcie się, módlcie się mocno, tylko w ten sposób będziecie chronieni, do tej pory to co nadejdzie nie może być złagodzone, ale nie wolno wam się niczego obawiać, kochajcie Boga, kontynuujcie kręgi modlitewne powierzając się tylko Jemu i Jego nieskończonemu Miłosierdziu. Nigdy nie zawracajcie, ale idźcie naprzód z mocą w jedynej prawdzie. Proszę was, moje dzieci: poświęcajcie się codziennie Mnie, waszej Matce, a Ja otoczę was moim płaszczem, aby was zawsze chronić. Nigdy się nie bójcie. Módlcie się za Kościół, ponieważ szerzy się zamieszanie. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 24)), "Moja córko, dziękuję ci, że przyjęłaś mnie do swojego serca. Przychodzę do was, aby raz jeszcze ostrzec waszych braci, aby pozostali zjednoczeni. Czasy, które nadejdą, będą jeszcze gorsze, katastrofy, których będziecie świadkami, mocno w was uderzą, płaczę, bo widzę to wszystko, widzę też, jak grzech szerzy się na świecie, nie ma już sumienia, nie ma już szacunku dla siebie nawzajem, jesteście zdezorientowani i przerażeni, walczycie i rozpaczacie, nie rozumiejąc, że Jezus jest jedyną drogą, prawdą i życiem. Nie wszystkie rzeczy zostały wam objawione; stopniowo, gdy będziecie silni i zdolni do uświadomienia sobie, inne rzeczy będą wam znane. Moja córko, musisz powiedzieć swoim braciom, aby nie porzucali wiary, ale w niej trwali, abyście przebaczali sobie nawzajem, bo kiedy nadejdzie czas, musicie być gotowi. Wkrótce nadejdzie czas wejścia Antychrysta, będzie to człowiek bardzo bliski Kościołowi, będzie on mediatorem w czasie wojny i wtedy zrozumiecie, że nie wolno wam nigdy patrzeć mu w oczy, nie dajcie się zwieść jego miłemu usposobieniu. Moja córko, to wszystko nie potrwa długo, bądź więc silna i bądź światłem dla świata, modlitwa wspólnotowa ci w tym pomoże, nie izoluj się, ale zawsze bądź w jedności z braćmi.  Módlcie się dużo za Kościół, za Włochy, ponieważ tam będą prześladowania chrześcijan i za Amerykę, która odwróciła się od Boga, szerząc i kochając grzech.  Teraz błogosławię cię razem z twoim małżonkiem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 28)), "Moje ukochane dzieci Nieba, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, czuję wasz strach i cierpienie, ale czyż nie wszystko zostało już przepowiedziane w Piśmie Świętym? Moje dzieci, Jezus przygotowywał was od dawna, a jednak wy, którzy nie byliście mocni w wierze, teraz się boicie. Pamiętajcie zawsze, że powołałam was pojedynczo i przygotowuję mój lud, aby wiele moich dzieci założyło rodziny z matkami, ojcami i braćmi. Prześladowania będą wielkie, zwłaszcza gdy kościoły są niszczone przez nieczyste istoty, ale bądźcie zjednoczeni, bo będę was chronić. Teraz grzech jest tak wielki, że tylko modlitwa i ufność mogą cię uratować. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 31)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, płaczę, bo wiem, do jak wielkiego smutku zmierzacie, wszystko to zostało przepowiedziane, ale wy tracicie czas na sprawy tego świata. Czy mój Jezus nie zostawił ci, mówiąc: 'Proście, a będzie wam dane'? Drogie dzieci, pozostańcie wierne Słowu mojego Pana, a On będzie obdarzał was miłosierdziem i opatrznością. Dzieci mego serca, nie dostosowujcie się do tego, co mówi wam świat, nie uciekajcie do tych, którzy zapewniają was o ochronie, bo tylko mój Jezus was chroni, pomaga, wspiera i kocha. Trwajcie w prawdziwej nauce wiary i nie dajcie się zwieść. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])




translator = google_translator()  

# BROKEN

#dataset["text_es"] = dataset["text_it"].apply(lambda x: translator.translate(x,lang_tgt='es'))
#dataset["text_fr"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='fr'))
#dataset["text_zh"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='zh'))
#dataset["text_de"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='de'))
#dataset["text_pt"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='pt'))



import goslate
gs = goslate.Goslate()

dataset["text_es"] = dataset["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset["text_fr"] = dataset["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset["text_zh"] = dataset["text_en"].apply(lambda x: gs.translate(x,'zh'))
dataset["text_de"] = dataset["text_en"].apply(lambda x: gs.translate(x,'de'))
dataset["text_pt"] = dataset["text_en"].apply(lambda x: gs.translate(x,'pt'))





dataset.to_csv("august_2021.csv", encoding="utf-8", index=False)










