# -*- coding: utf-8 -*-
"""
Created on Fri Jan 1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator

#dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "", dataset["text_it"])



dataset = pd.read_csv("november_cleaned.csv", encoding="utf-8")

dataset["text_pl"] = ""
dataset["text_en"] = ""
dataset["text_it"] = ""
dataset["month_string"] = "November"





# ITALIAN
dataset["text_it"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 3)), "Figli miei, grazie per aver ascoltato la mia chiamata nel vostro cuore. Io sono felice nel vedervi qui in ginocchio nella preghiera. Figli miei, quanto vorrei vedervi così nonostante la pioggia di benedizioni, in particolare in questi tempi molto difficili. Questo fa molto piacere a Gesù, soprattutto vedere una vera fede, una coraggiosa fede, che non ha paura di nulla. Voi, così come figli mi siete stati affidati e io vi amo come Madre di Gesù e Madre vostra. Voglio allontanarvi dal peccato, voglio che siate sempre pronti ad essere con lo sguardo unito a quello di Gesù. Pregate figli per la Chiesa, perché purtroppo le minacce sono dall’interno. Ricordate che sarete perseguitati così come lo è stato mio Figlio. Sarete chiamati pazzi così come è stato detto a mio Figlio; e non verrete accolti per la vostra fede. Le vostre pene saranno mille volte ricompensate. Soprattutto, se continuerete su questa strada, potrete godere un giorno del paradiso. Pregate affinché la guerra non possa iniziare perché tutto è pronto nei paesi. Pregate per la Spagna. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo. Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 6)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli, vi chiedo di avere un cuore puro, togliete l’odio, il rancore e fate una confessione settimanale, tenetevi pronti perché l’avvertimento sta per essere. Io farò un ponte tra il cielo e la terra per tutti i miei figli prediletti. Figli miei, camminate sulla strada della santità, le vostre sofferenze offerte, serviranno per la salvezza di molte anime, soprattutto la sofferenza della mia prediletta. Io sto riunendo i miei figli, affinché insieme possano evangelizzare il più possibile, ormai è urgente. Figlia mia, parla del mio Gesù nel mondo, Io sarò al tuo fianco, il mio amore e la mia consolazione sta attirando molte anime, che altrimenti si sarebbero perdute. Figli miei, pregate per i governanti, perché stanno tramando qualcosa di pericoloso per voi. Pregate per la Chiesa. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 13)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, oggi sono qui come Madre Addolorata, guardo i vostri cuori e non vedo la pace di cui avrete bisogno per affrontare i tempi bui. Figli amati, quante cattiverie ancora ci sono nel mondo, persecuzioni, giudizi contro i vostri fratelli, ricordate che solo Dio è giudice e non voi, affidate a Lui tutte le vostre sofferenze. Figli miei, vedo tante persone che pregano molto, ma senza cuore e amore, quelle non sono preghiere, ma solo parole inutili, metteteci tutto l’amore e con gli occhi e le mani verso il cielo, rivolgetevi a Gesù Cristo, unico e vero Salvatore. Figli cari, pregate per la Chiesa, pregate per l’America dove tutto è pronto per la guerra. Pregate per la Russia, che sembra volere la pace, ma è già pronta al conflitto.  Fate penitenza figli miei. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 16)), "Figlia mia, grazie per aver risposto alla mia chiamata nel tuo cuore.  Sono ancora qui a chiedere la conversione urgente, vi chiedo di non continuate a sfidare Dio. Ancora non comprendete che il demonio, con la sua astuzia, vuole controllarvi totalmente, comprese le vostre menti? Beati coloro, che nonostante le tenebre che attanagliano il mondo, restano fedeli alle parole di Gesù e pregano con la gioia e la pace nei loro cuori.  Figli miei, fidatevi di Gesù Cristo e non dei falsi idoli, che stanno portando i miei figli alla perdizione. Vi ho dato l’arma più potente, il Santo Rosario per combattere il demonio, non abbiate paura e siate fedeli alla Parola di Dio. Tutto è pronto per attaccare la mia Chiesa e molto sangue scorrerà nella grande piazza, pregate, pregate, pregate tanto! Gesù tornerà per fare nuove tutte le cose e non ci sarà più dolore, ne lamento, ma solo pace e amore. Ora ti lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 20)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore, vi ringrazio figli miei per avere piegato le vostre ginocchia. Cari figli, molti di voi pregano per anticipare la venuta di mio Figlio Gesù, vi capisco, ma l’ordine di tutte le cose deve essere rispettato, così come la costruzione di una casa che prima dovrà essere vista sul progetto e poi ammirare la bellezza della casa, ecco così è il progetto di Dio che avrà compimento dopo che alcune cose saranno accadute. Questo è il momento dell’anticristo, che presto apparirà. Adesso l’apostasia della Chiesa ha allontanato tanti miei figli dai sacramenti e per chi ha una fede precaria, cade facilmente nell’errore. Figli miei, non abbiate paura se sarete nella vera fede, affidatevi a mio Figlio Gesù che tutto può con la pace effusa. Ora vi benedico nel nome del Padre e del Figlio e dello Spirito Santo, Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 21)), "Fratelli miei, grazie per avermi consolato anche oggi con la vostra presenza. Fratelli e figli, voi che ogni giorno mi chiedete nel vostro cuore, se fate abbastanza per me, io vi dico in verità: tutte le volte che ascolto le vostre voci cantando lodi e preghiere, i miei angeli si uniscono a voi affinché il cielo e la terra diventino un’unica cosa.  Fratelli miei, fare la mia volontà è amarsi nella verità, siate fratelli e uniti, così come dovrà essere il mio popolo, camminando e seguendo le mie orme sulla via dell’amore reciproco e della verità. Io sarò con voi fino alla fine della santa messa per benedirvi uno ad uno, la pace sia con voi. Il vostro Gesù.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 23)), "Figlia mia, grazie per aver ascoltato la mia chiamata nel tuo cuore. Urla e devi dire con determinazione che il grande diluvio sta per abbattersi su questa umanità, durante il quale una grande Croce sarà vista dal mondo intero, convertitevi con urgenza. Figlia mia, chiedi di aprire i cuori alla mia chiamata e di sentire il forte dolore di mio Figlio Gesù, presto l’eresia della Chiesa sarà più forte, tutti capiranno, almeno coloro che hanno avuto una fede salda, basata sulla parola di Dio. Il demonio vuole arrivare a farvi impiantare il suo marchio, Attenzione!! i progetti sono malvagi, così come la dittatura, il comunismo, la falsità e tutto ciò che servirà per controllarvi, ma non dovete temere, Dio sa distinguere ciò che è per il vostro bene e ciò che non lo è, ricordate queste parole: chi vorrà salvare la propria vita la perderà, ma chi perderà la vita per causa Mia la troverà. Ora ti benedico insieme al tuo sposo ed ai tuoi fratelli, nel nome del Padre e del Figlio e dello Spirito Santo, Amen.", dataset["text_it"])

# ENGLISH
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 3)), "My children, thank you for listening to my call in your hearts. I am happy to see you here on your knees in prayer. My children, how much I would like to see you like this in the shower of blessings, especially in these very difficult times. This pleases Jesus very much, especially to see a true faith, a courageous faith, which is not afraid of anything. You, as children have been entrusted to me and I love you as Mother of Jesus and Mother of you. I want to turn you away from sin, I want you to be always ready to be with your gaze united to that of Jesus. Pray, children, for the Church, because unfortunately the threats are from within. Remember that you will be persecuted just as my Son was persecuted. You will be called insane as it was said to my Son; and you will not be accepted for your faith. Your pains will be a thousandfold rewarded. Above all, if you continue on this path, you will one day enjoy paradise. Pray that the war cannot begin because everything is ready in the countries. Pray for Spain. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 6)), "My children, thank you for answering my call in your heart. My children, I ask you to have a pure heart, remove hatred, resentment and make a weekly confession, be ready because the warning is about to happen. I will make a bridge between heaven and earth for all My beloved children. My children, walk on the way of holiness, your sufferings offered, will serve for the salvation of many souls, especially the suffering of my beloved. I am gathering my children so that together they may evangelize as much as possible, it is now urgent. My daughter, speak of my Jesus in the world, I will be at your side, my love and consolation is attracting many souls, who would otherwise be lost. My children, pray for the rulers, for they are plotting something dangerous for you. Pray for the Church. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 13)), "Dear children, thank you for responding to my call in your hearts. My children, today I am here as a Sorrowful Mother, I look at your hearts and I do not see the peace that you will need to face the dark times. Beloved children, how much wickedness there still is in the world, persecutions, judgments against your brothers, remember that only God is judge and not you, entrust all your sufferings to Him. My children, I see so many people who pray a lot, but without heart and love, those are not prayers, but only useless words, put all your love into them and with your eyes and hands towards heaven, turn to Jesus Christ, the only and true Savior. Beloved children, pray for the Church, pray for America where everything is ready for war. Pray for Russia, which seems to want peace, but is already ready for conflict. Do penance my children. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 16)), "My daughter, thank you for responding to my call in your heart. I am still here asking for urgent conversion; I ask you not to continue to defy God. Do you still not understand that the devil, with his cunning, wants to control you totally, including your minds? Blessed are those who, despite the darkness that grips the world, remain faithful to Jesus' words and pray with joy and peace in their hearts.  My children, trust in Jesus Christ and not in false idols, which are leading my children to perdition. I have given you the most powerful weapon, the Holy Rosary to fight the devil, do not be afraid and be faithful to the Word of God. Everything is ready to attack My Church and much blood will flow in the great square, pray, pray, pray so much! Jesus will return to make all things new and there will be no more pain, no more lament, only peace and love. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 20)), "My children, thank you for responding to my call in your hearts, I thank you my children for bending your knees. Dear children, many of you are praying to advance the Coming of my Son Jesus, I understand you, but the order of all things must be respected, as well as the construction of a house that must first be seen on the plan and then you will admire the beauty of the house, that is how it is God's plan that will have fulfillment after some things have happened. This is the time of the antichrist, who will soon appear. Now the apostasy of the Church has turned many of my children away from the sacraments and for those who have a precarious faith, they easily fall into sin. My children, do not be afraid if you are in the true faith, entrust yourselves to my Son Jesus who can do everything by the peace poured out. Now I bless you in the name of the Father and of the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 21)), "My brothers, thank you for consoling me again today with your presence. Brothers and children, you who ask me every day in your hearts if you do enough for me, I tell you in truth: every time I hear your voices singing praises and prayers, my angels join you so that Heaven and Earth become one. My brothers, to do My Will is to love one another in truth; be brothers and united, as My people must be, walking and following in My footsteps on the way of mutual love and truth. I will be with you until the end of Holy Mass to bless you one by one, peace be upon you. Your Jesus.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 23)), "My daughter, thank you for listening to My call in your heart. Cry out and you must say with determination that the great flood is about to come upon this humanity, during which a great Cross will be seen by the whole world, convert urgently. My daughter, ask to open hearts to my call and feel the strong sorrow of my Son Jesus, soon the heresy of the Church will be stronger, everyone will understand, at least those who had a firm faith, based on the word of God. The devil wants to get to you to implant his mark, Beware! Those schemes are evil, as well as dictatorship, communism, falsehood and all that will serve to control you, but you must not fear, God knows how to distinguish what is for your good and what is not, remember these words: whoever wants to save his life will lose it, but whoever loses his life because of Me will find it. Now I bless you together with your spouse and your brothers, in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])

# POLISH
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 3)), "Dzieci moje, dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Cieszę się, że widzę was tutaj na kolanach w modlitwie. Moje dzieci, jak bardzo chciałabym was widzieć takimi w deszczu błogosławieństw, zwłaszcza w tych bardzo trudnych czasach. To bardzo podoba się Jezusowi, zwłaszcza gdy widzi prawdziwą wiarę, wiarę odważną, która niczego się nie boi. Wy, jako dzieci, zostaliście mi powierzeni i kocham was jako Matka Jezusa i wasza Matka. Chcę was odwrócić od grzechu, chcę, abyście byli zawsze gotowi, aby wasze spojrzenie było zjednoczone ze spojrzeniem Jezusa. Módlcie się, moje dzieci, za Kościół, bo niestety zagrożenia są od wewnątrz. Pamiętajcie, że będziecie prześladowani, jak prześladowany był mój Syn. Zostaniecie nazwani szaleńcami, jak to zarzucono mojemu Synowi; i nie zostaniecie przyjęci z powodu waszej wiary. Wasz trud zostanie wynagrodzony po tysiąckroć. Ponadto, jeśli będziecie podążać tą drogą, pewnego dnia będziecie mogli cieszyć się rajem. Módlcie się, aby wojna się nie rozpoczęła, ponieważ wszystko w krajach jest gotowe. Módlcie się za Hiszpanię. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 6)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, proszę was, abyście mieli czyste serce, usuńcie nienawiść, urazę i spowiadajcie się co tydzień, bądźcie gotowi, bo ostrzeżenie ma nadejść. Uczynię most między niebem a ziemią dla wszystkich moich ukochanych dzieci. Dzieci moje, kroczcie drogą świętości, wasze ofiarowane cierpienia posłużą dla zbawienia wielu dusz, a szczególnie dla cierpienia mojego ukochanego. Gromadzę moje dzieci, aby razem ewangelizowały jak najwięcej, to pilne. Córko moja, mów o moim Jezusie w świecie, ja będę przy tobie, moja miłość i pociecha przyciąga wiele dusz, które w przeciwnym razie byłyby zgubione. Dzieci moje, módlcie się za władców, bo knują coś niebezpiecznego dla was. Módlcie się za Kościół. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 13)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, dziś jestem tu jako Matka Bolesna, patrzę na wasze serca i nie widzę pokoju, którego potrzebujecie, by stawić czoła mrocznym czasom. Umiłowane dzieci, jak wiele zła jest jeszcze na świecie, prześladowania, sądy przeciwko swoim braciom, pamiętajcie, że tylko Bóg jest sędzią, a nie wy, Jemu powierzcie wszystkie wasze cierpienia. Moje dzieci, widzę tak wielu ludzi, którzy dużo się modlą, ale bez serca i miłości, to nie są modlitwy, ale tylko bezużyteczne słowa, włóżcie w nie całą waszą miłość i z oczami i rękami zwróconymi ku niebu, zwróćcie się do Jezusa Chrystusa, jedynego i prawdziwego Zbawiciela. Drogie dzieci, módlcie się za Kościół, módlcie się za Amerykę, gdzie wszystko jest gotowe do wojny. Módlcie się za Rosję, która wydaje się pragnąć pokoju, ale jest już gotowa na konflikt.  Czyńcie pokutę, moje dzieci. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 16)), "Moja córko, dziękuję ci, że odpowiedziałaś na moje wezwanie w swoim sercu. Nadal jestem tutaj, prosząc o pilne nawrócenie; proszę was, abyście przestali sprzeciwiać się Bogu. Czy nadal nie rozumiecie, że diabeł, ze swoją przebiegłością, chce was całkowicie kontrolować, w tym wasze umysły? Błogosławieni są ci, którzy pomimo ciemności ogarniających świat, pozostają wierni słowom Jezusa i modlą się z radością i pokojem w sercu. Moje dzieci, zaufajcie Jezusowi Chrystusowi, a nie fałszywym bożkom, które prowadzą moje dzieci do zguby. Dałam wam najpotężniejszą broń, Różaniec Święty, do walki z diabłem; nie bójcie się i bądźcie wierni Słowu Bożemu. Wszystko jest gotowe do ataku na mój Kościół i wiele krwi popłynie na wielkim placu, módlcie się, módlcie się, módlcie się mocno! Jezus powróci, aby uczynić wszystko nowym i nie będzie więcej bólu, nie będzie więcej lamentu, tylko pokój i miłość. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 20)), "Moje dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach, dziękuję wam, moje dzieci, że uklęknęliście. Drogie dzieci, wielu z was modli się, aby przyspieszyć Przyjście mojego Syna Jezusa, rozumiem was, ale porządek wszystkich rzeczy musi być przestrzegany, tak jak budowa domu musi być najpierw widziana na planie, a następnie można podziwiać piękno domu, tak też Plan Boży wypełni się po tym, jak pewne rzeczy się wydarzą. Jest to czas antychrysta, który wkrótce się pojawi. Obecnie apostazja Kościoła odwróciła wiele moich dzieci od sakramentów, a ci, którzy mają chwiejną wiarę, łatwo popadną w grzech. Dzieci moje, nie bójcie się, jeśli jesteście prawdziwej wiary, powierzcie się mojemu Synowi Jezusowi, który może uczynić wszystko, rozlewając pokój. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 21)), "Moi bracia, dziękuję wam za to, że także dzisiaj pocieszacie mnie swoją obecnością. Bracia i dzieci, wy, którzy codziennie pytacie mnie w swoich sercach, czy robicie dla mnie wystarczająco dużo, zaprawdę powiadam wam: za każdym razem, gdy słyszę wasze głosy śpiewające chwałę i modlitwę, moi aniołowie przyłączają się do was, tak że niebo i ziemia stają się jednym. Bracia moi, wypełniać moją wolę to miłować się wzajemnie w prawdzie, być braćmi i zjednoczonymi, jak powinien być mój lud, idąc i podążając moimi śladami drogą wzajemnej miłości i prawdy. Będę z wami do końca Mszy Świętej, aby was wszystkich błogosławić, pokój wam. Wasz Jezus.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 23)), "Córko Moja, dziękuję ci, że wysłuchałaś Mojego wezwania w twoim sercu. Wołajcie i mówcie z całą stanowczością, że wielka powódź ma spaść na tę ludzkość, podczas której cały świat ujrzy wielki Krzyż, nawracajcie się pilnie. Córko moja, proś o otwarcie serc na moje wezwanie i odczuwanie silnego smutku mojego Syna Jezusa; wkrótce herezja Kościoła będzie silniejsza, wszyscy zrozumieją, przynajmniej ci, którzy mieli mocną wiarę, opartą na słowie Bożym. Diabeł chce wam wszczepić swój znak, uważajcie! To są złe zamysły, tak samo, jak dyktatura, komunizm, fałsz i wszystko, co będzie służyło do kontrolowania was, ale nie wolno wam się bać, Bóg wie jak rozróżnić co jest dla waszego dobra, a co nie, pamiętajcie te słowa: kto chce zachować swoje życie, straci je, ale kto straci swoje życie ze względu na Mnie, znajdzie je. Teraz błogosławię cię wraz z twoim małżonkiem i waszymi braćmi, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])


import goslate
gs = goslate.Goslate()

dataset["text_es"] = dataset["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset["text_fr"] = dataset["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset["text_zh"] = dataset["text_en"].apply(lambda x: gs.translate(x,'zh'))


dataset["text_de"] = dataset["text_en"].apply(lambda x: gs.translate(x,'de'))

dataset["text_pt"] = dataset["text_en"].apply(lambda x: gs.translate(x,'pt'))





dataset.to_csv("november_2021.csv", encoding="utf-8", index=False)







