# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator



dataset = pd.read_csv("march_cleaned.csv", encoding="utf-8")

dataset["text_pl"] = ""
dataset["text_en"] = ""


dataset["text_it"] = dataset["text_it"].str.replace("\"", "")
dataset["text_it"] = dataset["text_it"].str.replace("AmenLa", "Amen. La")
dataset["text_it"] = dataset["text_it"].str.replace("AmenIn", "Amen. In")
dataset["text_it"] = dataset["text_it"].str.replace("Santo \. Amen", "Santo, Amen.")
dataset["text_it"] = dataset["text_it"].str.replace(" : ", ": ")
dataset["text_it"] = dataset["text_it"].str.replace("Spirito santo", "Spirito Santo")
dataset["text_it"] = dataset["text_it"].str.replace("Dio Figli", "Dio. Figli")
dataset["text_it"] = dataset["text_it"].str.replace("Amen Oggi", "Amen. Oggi")
dataset["text_it"] = dataset["text_it"].str.replace("Continua a leggere\. \. \. \»", "")
dataset["text_it"] = dataset["text_it"].str.replace("sinistro\.\.", "sinistro.")
dataset["text_it"] = dataset["text_it"].str.replace("Amen Il ", "Amen. Il ")



dataset["text_it"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 30)), "Amati figli non temete, perché anche Io sono stato perseguitato prima di voi e vi prego non dite che Io ero Figlio di Dio in quanto potevo sopportare tutta la sofferenza, non è così, ho provato nella mia carne come nel mio cuore tutto il dolore e il buio del mondo perché fui incarnato per questo. Affidate tutto a me, unica àncora di salvezza, vi prenderò per mano e allevierò le vostre sofferenze caricandole sulle mie spalle e portandole con me verso il calvario. Vi chiedo con estremo amore di non abbandonare Me e la mia Santa Madre, che con molta umiltà, ancora sta in mezzo a voi, la vostra sofferenza sarà premiata. Vi chiedo di aiutare i vostri fratelli, affinché non cadano nella perdizione, e se solo uno dei vostri fratelli si salverà, sarà festa nei cieli. Io non vi lascio, guardate la croce e tutto quello che ella comporta, abbiate pietà del vostro Gesù che vi capisce e che tanto soffre. L'uomo purtroppo, è attaccato dall'angelo più bello che si è ribellato a Dio, solo chi avrà la forza e la Fede si salverà, questo messaggio è per te Gisella e per tutti i miei fratelli scelti per opera mia, non lasciate che il male possa offuscare le vostre menti. Io sono con voi e vi Benedico nel nome del Padre nel mio nome e dello Spirito Santo, Amen." , dataset["text_it"])




dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Dear children, thank you for having responded to my call in your hearts. Beloved children, I, your Mother, ask you: take my hands and listen to what is coming to you from Heaven, for everything is for your salvation. Take advantage of this time of mercy, for soon justice and God's wrath will make themselves felt; by now the time left is very short, as is the time I will remain with you. My beloved ones, do not fear for the times that will come or that have already come, because with prayer and conversion you will be able to save yourselves, but do not play any longer, but open your hearts and let the Holy Spirit enter that will transform you and unite you in one heart with Jesus. My children, if you only knew how much I love you and how much joy I feel seeing you all together in prayer. My beloved ones, pray for the Church and for the consecrated, for they are in darkness, confusion and gloom, that they may be enlightened by God's love. Now I leave you with my motherly blessing,in the name of the Father and the Son and the Holy Spirit, Amen. Today, so many graces will descend upon you, witness them with humility. Your Mother!" , dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 6)), "Dear children, thank you for responding to my call in your hearts. Beloved children, you ask, why does my Son weep tears of blood? Know that Jesus is sad, grieved for this humanity that is called to salvation, but does not respond to His call. By now, my children, today is the end of the time of Mercy, call on the Lord to have mercy on you, I offer my tears for you. My children, someone will be saved thanks to the suffering offered by this daughter of mine. I ask you: pray, pray very much. My children, technology is about to be attacked by solar eruptions, so be ready. Soon evil will reveal itself before the world, but only those who are faithful to Christ will recognize good from evil, thanks to the infusion of the Holy Spirit. My children, the times that will come will be hard, very hard. As a Mother I ask you to hasten your conversion, do not be lukewarm, only God will be your salvation, entrust your life to Him, everything will be renewed and much will be lost, but I want to save these children of mine. The earth will continue to tremble without ceasing. Now I leave you with My Motherly Blessing in the name of the Father and the Son and the Holy Spirit, Amen." , dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 9)), "Dear children, your prayers dry my tears. My children, the pain offered must bring joy. My children, not everything will be as you expect, the earth you know will no longer exist, you will be transformed into light and taken to a safe place, do not be afraid because everything will be painless for these moments. I only ask you to pray for your transformation. My children, the new earth will be full of joy and peace and there will be no sickness, everything is ready for your arrival. My children, what you will soon see, you will not be able to bear if you are not in faith and prayer, be careful because the devil will do everything to discourage you, so much so that even those who say they have faith could be caught in his web. My children, bring many souls to Jesus, that they may know Him and be faithful to Him always. My children, many have adhered to the evil, blasphemies and corruptions of the world, but they have not yet understood that their yes must be only for God. My children, please open your eyes and look around, do you not understand where you have arrived? Spiritual warfare is going on, watch over your children, pray for your rulers, so that the light may enter their hearts. Now I leave you with My Motherly Blessing in the name of the Father and the Son and the Holy Spirit, Amen." , dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 13)), "My children, thank you for having responded to my call in your hearts. Beloved children, in these years of apparitions, not everything has been taken seriously, but now realize that what I am telling you is not slow in coming, and therefore I ask once again for an urgency to convert, be in grace, do not be afraid and be in the joy of the Lord who will soon come. My children, unfortunately many of my children have adapted to the imposition to which they are subjected, I beg you children, do not fear, for I am and will be with you every time you need help and when confusion takes hold of your soul, chase it away with prayer and look at the face of my Son, so that you may have serenity. My children, be disciples, fight for the truth, do not be subject to the devil who with his wiles involves you in lies, the times will be turbulent both for the Church and for politics, make circles of prayer. Now I leave you with my blessing in the name of the Father and the Son and the Holy Spirit, Amen." , dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 16)), "My children, thank you for being here in prayer. My children, I come again to warn you and to help you not to make mistakes, avoiding what does not come from God, yet you look around confused without realizing the deaths that there are and will be on earth, all because of your obstinacy to listen only to human decisions. Many times I have told my children to be careful with vaccines, yet you do not listen. Beloved children, look at the Cross of Jesus and stand under His Blessed Cross with which He redeemed you. Beloved children, the Wrath of God will not be long in making itself felt, but humanity is so blind that it will not notice anything, giving only scientific explanations. My children, you are my true Church and it is to you that I entrust myself, for thanks to my faithful she will be reborn resplendent and glorious. My children, by now nothing will be the same as before, they have taken everything from you including your freedom, be faithful to the Lord and to the Holy Scriptures, convert, only in this way will you be on the path of light ready for you. My children, the Church, oh! the Church how much pain! My heart bleeds to see brick after brick fall, how much pain!!! My children, you are at war and you must fight, it does not matter if you are mocked, go on without ceasing. Now I leave you with my Motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen." , dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 20)), "Dear children, thank you for being here in prayer and for responding to my call in your hearts. Beloved children, your prayers soothe my sufferings and those of my Son. My children, be ready, the storm is upon you and I ask you to forgive, love and confess so that you are ready for what is coming and for the times that are coming. This is the time to come together and not to be divided, be true men and women of faith, be those who will fight in the front line, this is the time when you will be asked by Heaven to find shelters and refuges where you can hide even to pray, the predicted times have come. My children, I, your Mother, am with you together with my angels to protect you. Now I leave you with my Motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen." , dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 23)), "Beloved daughter, thank you for your 'Yes', together with your spouse and the little remnant you are my consolation. Daughter, you must tell humanity that the trumpets have already sounded, only one remains, that of justice. My children, my chosen people must strengthen their prayer for these times, division and persecution has begun. My children, war is about to begin in the Middle East, pray for Syria, this will be a great war because it will involve Russia and America. How much pain in this land flooded with sin, I had asked through other beloved children to warn the Church and the heads of government so that they would not compromise and instead they chose the way of evil. Now I ask them once again: repent and convert, for you do not realize what you are heading for, only some in the government know what is going to happen, the others are just in great confusion, but remember that my Immaculate Heart will triumph, pray, pray, pray. To My faithful children I say: be in peace because nothing will be lacking, you will be covered and protected by my Mantle. Now I leave you with my blessing, in the name of the Father and the Son and the Holy Spirit, Amen." , dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 28)), "My children, thank you for being here and for bending your knees in prayer. My children, my Jesus fills you with Grace, for this is what you will need, God's justice is upon you, His cry of pain will come with the fire of purification, and all believers and faithful will rejoice, but the wrongdoers and those who deny Him will suffer greatly. Children, the times have hastened also thanks to your prayers, do not be afraid, but rejoice and be glad because the coming of Jesus is near. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen." , dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 30)), "Beloved children, do not fear, for I too have been persecuted before you, and I beg you not to say that because I was the Son of God so that I could bear all the suffering, it is not so; I experienced in my flesh as in my heart all the pain and darkness of the world because I was incarnated for this. Entrust everything to me, the only anchor of salvation, I will take you by the hand and I will ease your suffering by carrying it on my shoulders and carrying it with me towards Calvary. I ask you, with extreme love, not to abandon Me and my Holy Mother, who, with much humility, still stands among you; your suffering will be rewarded. I ask you to help your brothers, so that they do not fall into perdition, and if only one of your brothers is saved, it will be a feast in heaven. I do not leave you, look at the cross and all that it entails, have pity on your Jesus who understands you and who suffers so much. Unfortunately, man is being attacked by the most powerful angel who has rebelled against God, only those who have the strength and faith will be saved, this message is for you Gisella and for all my brothers chosen by me, do not let evil cloud your minds. I am with you and I bless you in the name of the Father, in my Name and the Holy Spirit, Amen." , dataset["text_en"])


dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, Ja, wasza Matka, proszę was: trzymajcie mnie za rękę i słuchajcie tego, co przychodzi do was z Nieba, bo wszystko jest dla waszego zbawienia. Wykorzystajcie ten czas miłosierdzia, ponieważ wkrótce sprawiedliwość i gniew Boży dadzą o sobie znać; czas, który pozostał do dyspozycji, jest już bardzo krótki, podobnie jak czas, w którym pozostanę z wami. Umiłowani moi, nie bójcie się czasów, które nadejdą lub już nadeszły, bo modlitwą i nawróceniem będziecie mogli się uratować, ale nie udawajcie już więcej, ale otwórzcie wasze serca i pozwólcie wejść Duchowi Świętemu, a On was przemieni i zjednoczy w jednym sercu z Jezusem. Moje dzieci, gdybyście tylko wiedzieli, jak bardzo was kocham i jak wielką radość odczuwam, gdy widzę was wszystkich razem na modlitwie. Umiłowani moi, módlcie się za Kościół i za osoby konsekrowane, bo są pogrążone w ciemnościach, zamęcie i mroku, aby oświeciła je miłość Boża. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen. Dziś zstąpi na was wiele łask, bądźcie ich świadkami z pokorą. Wasza Matka!" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 6)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, pytacie się, dlaczego mój Syn płacze krwawymi łzami? Wiedzcie, że Jezus jest smutny, zasmucony z powodu tej ludzkości, która jest powołana do zbawienia, ale nie odpowiada na Jego wezwanie. Już teraz, moje dzieci, dziś skończył się czas Miłosierdzia, wzywajcie Pana, aby się nad wami zmiłował, ja ofiaruję za was moje łzy. Moje dzieci, ktoś zostanie uratowany dzięki cierpieniu ofiarowanemu przez tę moją córkę. Proszę was: módlcie się, módlcie się bardzo mocno. Moje dzieci, technologia zostanie wkrótce zaatakowana przez erupcje słoneczne, więc bądźcie gotowi. Wkrótce zło ujawni się przed światem, ale tylko ci, którzy są wierni Chrystusowi, będą odróżniać dobro od zła, dzięki wylaniu Ducha Świętego. Moje dzieci, czasy, które nadejdą, będą ciężkie, bardzo ciężkie. Jako matka proszę was: przyspieszcie swoje nawrócenie, nie bądźcie letni, tylko Bóg będzie waszym zbawieniem, powierzcie Mu swoje życie, wszystko zostanie odnowione i wiele stracicie, ale ja chcę ocalić te moje dzieci. Ziemia będzie nadal drżeć bez ustanku. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 9)), "Drogie dzieci, wasze modlitwy osuszają moje łzy. Moje dzieci, ofiarowany ból musi przynieść radość. Moje dzieci, nie wszystko będzie tak, jak się spodziewacie, ziemia, którą znacie, nie będzie już istnieć, zostaniecie przemienieni w światło i zabrani w bezpieczne miejsce, nie bójcie się, ponieważ w tych chwilach wszystko będzie bezbolesne. Proszę was tylko o modlitwę w intencji waszej przemiany. Dzieci moje, nowa ziemia będzie pełna radości i pokoju i nie będzie na niej chorób, wszystko jest gotowe na wasze przyjście. Dzieci moje, tego, co wkrótce zobaczycie, nie będziecie mogli znieść, jeśli nie jesteście w wierze i modlitwie, uważajcie, bo diabeł zrobi wszystko, aby was zniechęcić, tak bardzo, że nawet ci, którzy mówią, że mają wiarę, mogą zostać uwięzieni w jego sieci. Dzieci moje, przyprowadźcie wiele dusz do Jezusa, aby Go poznały i były Mu zawsze wierne. Dzieci moje, wielu przylgnęło do zła, bluźnierstw i zepsucia świata, ale nie zrozumieli jeszcze, że ich 'tak' musi być tylko dla Boga. Dzieci moje, błagam was, otwórzcie oczy i rozejrzyjcie się wokół siebie, czy nie rozumiecie, dokąd doszliście? Walka duchowa toczy się, czuwajcie nad swoimi dziećmi, módlcie się za swoich władców, aby światło mogło wejść do ich serc.  Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 13)), "Moje dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, w tych latach objawień nie wszystko było brane na serio, ale teraz uświadomcie sobie, że to, co wam mówię, nie przychodzi powoli i dlatego jeszcze raz proszę o pilne nawrócenie, bądźcie w łasce, nie bójcie się i bądźcie w radości Pana, który wkrótce przyjdzie. Moje dzieci, niestety wiele moich dzieci dostosowało się do narzuconego reżimu, któremu są poddawane, błagam was dzieci, nie lękajcie się, bo jestem i będę z wami za każdym razem, gdy będziecie potrzebować pomocy, a gdy zamęt ogarnie waszą duszę, odganiajcie go modlitwą i wpatrujcie się w oblicze mojego Syna, abyście mieli spokój. Dzieci moje, bądźcie uczniami, walczcie o prawdę, nie ulegajcie diabłu, który swoimi podstępami wciąga was w kłamstwo, czasy będą burzliwe zarówno dla Kościoła, jak i dla polityki, twórzcie koła modlitewne. A teraz zostawiam was z moim błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 16)), "Dzieci moje, dziękuję wam, że jesteście tutaj na modlitwie. Dzieci moje, przychodzę znowu, aby was ostrzec i pomóc wam, abyście nie popełniali błędów, unikając tego, co nie pochodzi od Boga, a jednak rozglądacie się zdezorientowani, nie zdając sobie sprawy ze śmierci, która jest i będzie na ziemi, a wszystko to z powodu waszego uporu, aby słuchać tylko ludzkich decyzji. Wiele razy mówiłam moim dzieciom, żeby uważały na szczepionki, ale wy nie słuchacie. Umiłowane dzieci, spójrzcie na Krzyż Jezusa i stańcie pod Jego Najświętszym Krzyżem, którym was odkupił. Umiłowane dzieci, gniew Boży niebawem da o sobie znać, ale ludzkość jest tak ślepa, że niczego nie zauważy, dając tylko naukowe wyjaśnienia. Dzieci, wy jesteście moim prawdziwym Kościołem i to wam się powierzam, bo dzięki moim wiernym odrodzi się on pełen blasku i chwały. Dzieci moje, już nic nie będzie takie jak dawniej, odebrali wam wszystko, łącznie z waszą wolnością, bądźcie wierni Panu i Pismu Świętemu, nawracajcie się, tylko w ten sposób będziecie na drodze światła, która jest dla was przygotowana. Dzieci moje, Kościół, oh Kościół!, ileż bólu! Serce mi krwawi, gdy widzę, jak cegła za cegłą się przewraca, ileż bólu!!! Dzieci moje, jesteście na wojnie i musicie walczyć, nie ma znaczenia, czy jesteście wyśmiewani, idźcie dalej bez ustanku. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 20)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie i że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, wasze modlitwy łagodzą cierpienia moje i mojego Syna. Dzieci moje, bądźcie gotowi, burza jest nad wami i proszę was o to, byście przebaczali, kochali i spowiadali się, abyście byli gotowi na to, co ma się wydarzyć i na czasy, które nadchodzą. Jest to czas, abyście się zebrali i nie dzielili, bądźcie prawdziwymi mężczyznami i kobietami wiary, bądźcie tymi, którzy będą walczyć na pierwszej linii frontu, jest to czas, w którym zostaniecie poproszeni przez Niebo, abyście znaleźli schrony i schronienia, gdzie możecie się ukryć, choćby po to, aby się modlić, nadeszły przepowiedziane czasy. Dzieci moje, jako matka jestem z wami wraz z moimi aniołami, aby was chronić.  Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 23)), "Umiłowana córko, dziękuję ci za twoje Tak, razem z twoim małżonkiem i małą resztką, jesteś moją pociechą. Córko, musisz powiedzieć ludzkości, że trąby już zabrzmiały, pozostała tylko jedna - trąba sprawiedliwości. Moje dzieci, Mój naród wybrany musi wzmocnić swoją modlitwę na te czasy, rozpoczął się podział i prześladowania. Moje dzieci, na Bliskim Wschodzie ma się rozpocząć wojna, módlcie się za Syrię, to będzie wielka wojna, bo będą w nią zaangażowane Rosja i Ameryka. Ileż bólu na tej ziemi zalanej grzechem, prosiłam przez inne umiłowane dzieci, aby ostrzegły Kościół i szefów rządów, aby nie szli na kompromis, a oni zamiast tego wybrali drogę zła. Teraz jeszcze raz ich proszę: pokutujcie i nawróćcie się, bo nie zdajecie sobie sprawy z tego, do czego zmierzacie, tylko niektórzy z rządu wiedzą, co ma się stać, inni są tylko w wielkim zamieszaniu, ale pamiętajcie, że moje Niepokalane Serce zatriumfuje, módlcie się, módlcie się, módlcie się. Moim wiernym dzieciom mówię: bądźcie w pokoju, bo niczego wam nie zabraknie, będziecie okryci i chronieni przez mój płaszcz. A teraz zostawiam was z moim błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 28)), "Dzieci moje, dziękuję wam, że jesteście tutaj i uklękneliście do modlitwy. Moje dzieci, mój Jezus napełnia was Łaską, bo tego właśnie będziecie potrzebować, sprawiedliwość Boża jest nad wami, Jego krzyk bólu przyjdzie z ogniem oczyszczenia, a wszyscy wierzący i wierni będą się radować, lecz złoczyńcy i ci, którzy się Go zapierają, będą bardzo cierpieć. Dzieci moje, nadejście czasu przyspiesza także dzięki waszym modlitwom, nie bójcie się, ale radujcie się i cieszcie, bo przyjście Jezusa jest bliskie. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 30)), "Umiłowane dzieci, nie bójcie się, bo i Ja byłem prześladowany przed wami i proszę was, nie mówcie, że ponieważ byłem Synem Bożym, to mogłem znieść wszystkie cierpienia; tak nie jest, doświadczyłem w moim ciele i w moim sercu wszystkich bólów i ciemności świata, bo po to zostałem wcielony. Powierzcie wszystko Mnie, jedynej kotwicy zbawienia, wezmę was za rękę i ulżę waszym cierpieniom, kładąc je na moje ramiona i niosąc je ze sobą na Kalwarię. Proszę was z wielką miłością, abyście nie opuszczali Mnie i Mojej Świętej Matki, która z wielką pokorą jest jeszcze wśród was; wasze cierpienia zostaną wynagrodzone. Proszę was, abyście pomogli swoim braciom, aby nie popadli w zatracenie, a jeśli tylko jeden z waszych braci zostanie zbawiony, będzie to uczta w niebie. Nie opuszczę cię, spójrz na krzyż i wszystko, co się z nim wiąże, ulituj się nad swoim Jezusem, który cię rozumie i który tak bardzo cierpi. Niestety, człowiek jest atakowany przez najpotężniejszego anioła, który zbuntował się przeciwko Bogu, tylko ci, którzy mają siłę i wiarę, zostaną uratowani, to przesłanie jest dla ciebie Gisella i dla wszystkich moich braci wybranych przeze mnie. Nie pozwólcie, aby zło zmąciło wasze umysły. Jestem z wami i błogosławię was w imię Ojca, w Imię moje i Ducha Świętego, Amen.", dataset["text_pl"])

translator = google_translator()  

dataset["text_es"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='es'))
dataset["text_fr"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='fr'))
dataset["text_zh"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='zh'))
dataset["text_de"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='de'))
dataset["text_pt"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='pt'))







dataset.to_csv("march_2021.csv", encoding="utf-8", index=False)





