# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator



dataset = pd.read_csv("july_cleaned.csv", encoding="utf-8")

dataset["text_pl"] = ""
dataset["text_en"] = ""
dataset["text_it"] = ""
dataset["month_string"] = "July"

dataset["author"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "Holy Mary", dataset["author"] )



# ITALIAN
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "Figli amati, grazie per essere qui uniti nella preghiera e per avere risposto alla mia chiamata nel vostro cuore. Figli miei, io sono ancora qui per la misericordia di Dio che vi vuole salvi. Vi prego, figli miei, non girate le spalle a Dio, ma pregate, pregate, pregate per questa umanità perduta, pregate per la Chiesa dove l’iniquità vuole fare da padrona. Figli miei, purtroppo pochi hanno la vera fede, ma vi chiedo di guidare i vostri fratelli sulla strada di Dio che è la via, verità e vita. Accadranno cose molto brutte e non vi vedo pronti, preparatevi con degna serietà per poter raggiungere la casa del Padre, dove tutto è pronto. La nuova Gerusalemme è vicina ed Io vi voglio in prima fila con la gioia, l’amore e la serenità. Ora vi lascio con la mia santa benedizione nel nome del Padre, del Figlio e dello Spirito Santo, Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 6)), "Figli amati, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, guardate intorno a voi, non fatevi ingannare dalle false promesse del demonio. Amati figli miei, tutto sta cambiando intorno a voi e in voi, pregate per i tempi che arriveranno, soltanto con la preghiera potrete sconfiggere il male.  Sento tanti farisei parlare, predicano bene, ma al di fuori peccano davanti a Dio, non siate come loro, parlate nella verità, è l’unica cosa che potrà rendervi liberi.  Non Guardate la falsa tranquillità, perché presto si trasformerà in tumulto. Non abbiate paura se siete in Dio, Io non sono qui per spaventarvi, ma per mettervi davanti ad una realtà cruda, ma Vera e ciò che accadrà sarà causato dall’ umanità che crede di poter fare a meno di Dio. Amatevi e cibatevi di mio Figlio. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 10)), "Cari figli, grazie per essere qui nella preghiera e per aver risposto alla mia chiamata nel vostro cuore. Amati figli miei, il principe del male non si ferma, ma avanza con grande forza, guardate cosa sta facendo, purtroppo è entrato nelle menti delle persone affinchè solo i potenti possano manovrarle.  Un giorno l’uomo impazzirà al punto che ogni simile mangerà il suo simile. Figli miei, leggete cos’è l’inferno, il purgatorio e il paradiso, molti dei miei figli non credono soprattutto all’esistenza dell’inferno e alla dannazione eterna, eppure da molti dei miei figli prediletti(mistici) vi è stato raccontato. Figli miei, come esiste il bene, esiste il male e per chi prega tanto per salvare le anime che si sono perdute, sentirà la presenza del Signore, convertitevi urgentemente, non avete ancora molto tempo. Figli, pregate tanto per il Brasile e pregate per l’Italia perché la terra tremerà molto forte. Io, vostra Madre vi proteggerò con i miei Santi Angeli, non abbiate mai paura, andate avanti parlando di mio Figlio nella Santa verità. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 13)), "Cari figli, grazie per essere qui nella preghiera. Figli miei, mettete ordine nelle vostre vite e abbiate una fede forte, vi servirà per adattarvi ai cambiamenti che ci saranno. Non meravigliatevi di ciò che accade intorno a voi, ricordate che più l’iniquità si diffonderà, più l’amore tra voi si raffredderà. L’ira di Dio, che non può essere fermata, si abbatterà su questa umanità, ma i miei figli fedeli saranno protetti. La trasformazione di tutto sarà sotto i vostri occhi. Dio mette sempre alla prova la vostra fede e, se Io sono ancora qui, è per indicarvi la via da seguire per arrivare fedeli a Dio e per darvi grandiose ricompense. Figli miei, diffidate da chi vi chiede di anteporre le cose del mondo a Dio, ascoltate bene quando qualcuno vi parla, ascoltate e capirete se sono parole di Dio oppure no. In questi tempi vedo alcuni dei miei figli tralasciare la recita del Santo Rosario per le frivolezze, ma ancora una volta vi dico: il Santo Rosario è l’arma più forte per combattere il male. Allora vi chiedo figli: da quale parte volete stare? Vi chiedo di fare adorazione perché porterà tanti benefici spirituali e non. Siate come i primi apostoli, pregate con la gioia dello Spirito Santo, siate fedeli alle sacre scritture. Amati figli miei, basta con i rancori, giudizi, ego e invidia, nessuno è migliore di un altro davanti a me, siete tutti miei figli e vorrei condurvi verso la luce. Non addoloratemi, ma siate testimoni del trionfo del mio Cuore Immacolato. Non dovrete mai temere, la mia protezione sarà per tutti voi fedeli e umili. Ora vi lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 15)), "Popolo mio, come fate ad avere dubbi sulla mia presenza in questo pane. Figli e fratelli, non vedete che Io vi proteggo? E’ grande il mio amore per voi e nulla vi mancherà mai, cibatevi del mio corpo finché ne avrete la possibilità, dovrete nascondervi per ricevermi senza recarmi alcuna offesa. Presto avrete bisogno l’uno dell’altro e Io sarò sempre qui accanto a voi e farò scendere tanta misericordia per coloro che resteranno fedeli a me, vi benedico, il vostro Gesù.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 17)), "Cari figli, grazie per essere qui nella preghiera e per aver risposto alla mia chiamata nel vostro cuore. Figli amati, prego insieme a voi e in particolare per i giovani che stanno scambiando la loro anima con la libertà. Figli miei, il demonio vuole portare all’inferno più anime possibili e molti sono caduti nell’inganno più grande dell’umanità. Figli miei, spesso mi chiedete se davvero ci sarà la guerra, ma sappiate che quella spirituale è già dentro in molti di voi. Amati figli miei, ciò che vi è stato predetto accadrà, pregate tanto perché la giustizia di Dio arriverà all’improvviso più forte che mai e potreste non avere il tempo per chiedere perdono. Chiedo ancora una volta la Consacrazione della Russia al mio cuore Immacolato, perché da lì accadranno molte cose. Figli cari, seguite il vero magistero della fede, rimanete vicini ai santi sacerdoti che avranno tanto bisogno di voi. Figli miei, l’unione e l’amore tra di voi commuove il cuore del mio Gesù, siate figli della luce. Ora, vi benedico nel nome del Padre del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 20)), "Figlia e sorella mia, grazie per essere qui nella preghiera, guarda intorno a te quanta abitudine hanno preso con le tue apparizioni, non si accorgono e non si inginocchiano perché non sentono che Io sono qui. Molti non mi riconosceranno neanche quando ritornerò. Figlia mia, non posso più accettare le lacrime di mia Madre che è stata inviata per accompagnarvi e indicarvi la strada della salvezza.  Molti uomini sono presi dalla loro umanità, ed è per questo che lo Spirito Santo che è stato inviato non potrà agire nei loro cuori perchè sono chiusi. Figlia, la preghiera dovrà essere una comunicazione dolce, intima con me e con la mia Santissima Madre, fate in modo che lo Spirito Santo possa trasformare i vostri cuori altrimenti non potrete sopportare ciò che sta per arrivare. Io vi chiedo l’unità, la fratellanza, l’umiltà e l’amore tra voi, senza queste poche cose sarete solo dei ciechi che accompagneranno altri ciechi, non siate ipocriti, ma mettete il cuore nella preghiera e soprattutto affidatevi e fidatevi di Me. L’umanità si è troppo umanizzata e il cuore serve solo per pulsare e andare avanti, ecco perché Io vi dico: non siate sepolcri imbiancati, ma innalzate la vostra spiritualità. Figli miei, pregate per i sacerdoti santi, perché loro vi consoleranno nel momento della necessità, pregate per i bambini affinché possano crescere nella più grande protezione. Ora vi benedico nel nome della Santissima Trinità, Padre, figlio e Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 24)), "Figlia mia, sappi che arriverà ciò che nessuno si aspetta, i tempi si stanno rincorrendo e velocizzando. Cara figlia mia, questo è il tempo peggiore che sta vivendo l’umanità, tante persone stanno soffrendo, ma soprattutto chi non conosce Dio. La guerra spirituale è ancora aperta, ma chi sarà fedele non deve temere nulla. Dico ai miei figli di luce che il male non potrà toccarli, quindi siate gioiosi e tranquilli perché la provvidenza vi arriverà senza esitare. Sappiate che questo è il momento della scelta tra  il bene il male, che la vostra decisione sia per il bene e quindi per la vita eterna. Figli miei, vi dico: tutto questo male terminerà, satana sta approfittando delle anime più deboli e più fragili, ma quando mio Figlio arriverà, tutto sarà nuovo e rinnovato. Testimoniate che la fede è gioia, amore e unità. Ora vi benedico nel nome del Padre e del Figlio e dello Spirito Santo. Io vostra Madre sono con voi.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 27)), "Cari amati figli miei, grazie per essere qui nella preghiera e per aver piegato le ginocchia. Figli miei, tutto è nel suo totale compimento. I padri dovranno benedire i figli, i mariti le mogli e i santi sacerdoti a tutti voi. Vi chiedo di fare le rinunce battesimali. Rinunciate a satana e credete nel Signore salvatore,  rinunciate alle sue astuzie e credete in Dio Salvatore, rinunciate all’odio, all’invidia e  alla gelosia e credete in Dio Salvatore,  rinunciate ai suoi tranelli, alla confusione, ai mali della mente e credete in Dio salvatore.  La chiesa tremera’ dalle sue fondamenta.  Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo , amen", dataset["text_it"])

# ENGLISH
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "Beloved children, thank you for being here united in prayer and for having responded to my call in your hearts. My children, I am still here through the mercy of God who wants you to be saved. I beg you, my children, do not turn your backs on God, but pray, pray, pray for this lost humanity, pray for the Church where iniquity wants to be the master. My children, unfortunately few have the true faith, but I ask you to lead your brothers on the way of God who is the way, the truth and the life. Very bad things will happen and I do not see you ready; prepare yourselves with worthy seriousness to be able to reach the Father's house where everything is ready. The new Jerusalem is near and I want you in the front row with joy, love and serenity. Now I leave you with My holy blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 6)), "Beloved children, thank you for having responded to my call in your hearts. My children, look around you, do not be deceived by the false promises of the devil. My beloved children, everything is changing around you and in you, pray for the times that will come, only with prayer can you defeat evil.  I hear so many Pharisees talking, they preach well, but outside they sin before God, do not be like them, speak in truth, it is the only thing that can make you free.  Do not look at the false tranquility, because soon it will turn into turmoil. Do not be afraid if you are in God, I am not here to frighten you, but to put you in front of a crude but true reality and what will happen will be caused by humanity that believes it can do without God. Love yourselves and feed on my Son. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 10)), "Dear children, thank you for being here in prayer and for having responded to my call in your hearts. My beloved children, the prince of evil does not stop, but advances with great strength, look what he is doing, unfortunately he has entered the minds of people so that the powerful can manipulate them.  One day man will go crazy to the point that every like will eat his like. My children, read what hell, purgatory and heaven are, many of my children do not believe especially in the existence of hell and eternal damnation, yet by many of my beloved children (mystics) you have been told. My children, as there is good, there is evil and for those who pray so much to save souls who are lost, they will feel the presence of the Lord, convert urgently, you do not have much time yet. Children, pray so much for Brazil and pray for Italy because the earth will shake very strongly. I, your Mother will protect you with my Holy Angels, never be afraid, go forth speaking of my Son in the Holy Truth. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 13)), "Dear children, thank you for being here in prayer. My children, put your lives in order and have a strong faith, it will serve you to adapt to the changes that will come. Do not marvel at what is happening around you, remember that the more iniquity spreads, the more love between you will grow cold. The wrath of God, which cannot be stopped, will come upon this humanity, but my faithful children will be protected. The transformation of everything will happen before your eyes. God is always putting your faith to the test and if I am still here, it is to show you the way to be faithful to God and to give you great rewards. My children, be wary of those who ask you to put the things of the world before God; listen well when someone speaks to you, listen and you will understand if they are God's words or not. In these times I see some of my children neglecting the recitation of the Holy Rosary for trivialities, but once again I say to you: the Holy Rosary is the strongest weapon to fight evil. So I ask you children: which side do you want to be on? I ask you to make adoration because it will bring many spiritual and other benefits. Be like the first apostles, pray with the joy of the Holy Spirit, be faithful to the sacred scriptures. My beloved children, enough with grudges, judgments, ego and envy, no one is better than another before me, you are all my children and I would like to lead you to the light. Do not grieve me, but be witnesses of the triumph of my Immaculate Heart. You will never have to fear, my protection will be for all of you who are faithful and humble. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 15)), "My people, how can you doubt My presence in this bread? My children and brothers, do you not see that I protect you? My love for you is great and nothing will ever be lacking; feed on My Body while you have the chance, you will have to hide to receive Me without causing Me any offense. Soon you will need each other and I will always be here beside you and I will send down so much mercy for those who remain faithful to Me, I bless you, your Jesus.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 17)), "Dear children, thank you for being here in prayer and for responding to my call in your hearts. Beloved children, I pray together with you and especially for the young people who are exchanging their souls for freedom. My children, the devil wants to take as many souls as possible to hell and many have fallen into humanity's greatest deception. My children, you often ask me if there really will be a war, but know that the spiritual one is already inside many of you. My beloved children, what has been foretold to you will happen, pray hard because God's justice will suddenly come stronger than ever and you may not have time to ask for forgiveness. Once again I ask for the Consecration of Russia to my Immaculate Heart, because from there many things will happen. Dear children, follow the true teaching of the faith, stay close to the holy priests who will need you so much. My children, the union and love among you moves the heart of my Jesus, be children of light. Now, I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 20)), "My daughter and sister, thank you for being here in prayer, look around you how much did they get used to these apparitions, they do not notice and do not kneel down because they do not feel that I am here. Many will not even recognize Me when I return. My daughter, I can no longer accept the tears of My Mother who was sent to accompany you and show you the way to salvation.  Many men are caught up in their humanity, and this is why the Holy Spirit who was sent cannot act in their hearts because they are closed. Daughter, prayer must be a sweet, intimate communication with me and with my Blessed Mother, so that the Holy Spirit may transform your hearts otherwise you will not be able to bear what is coming. I ask you for unity, brotherhood, humility and love among yourselves, without these few things you will only be blind men who will accompany other blind men, do not be hypocrites, but put your heart into prayer and above all entrust yourselves and trust Me. Humanity has become too humanized and the heart is only needed to pulsate and move forward, that is why I say to you: do not be whitewashed graves, but raise your spirituality. My children, pray for the holy priests, for they will console you in your time of need; pray for the children that they may grow up in the greatest protection. Now I bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 24)), "My daughter, know that what no one expects will come, times are chasing and speeding up. My dear daughter, this is the worst time humanity is living, so many people are suffering, but especially those who do not know God. The spiritual war is still open, but those who will be faithful should fear nothing. I tell my children of light that evil will not be able to touch them, so be joyful and calm because providence will come to you without hesitation. Know that this is the moment of the choice between good and evil, may your decision be for the good and therefore for eternal life. My children, I say to you: all this evil will end, Satan is taking advantage of the weakest and most fragile souls, but when my Son comes, everything will be new and renewed. Witness that faith is joy, love and unity. Now I bless you in the name of the Father and of the Son and of the Holy Spirit. I, your Mother, am with you.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 27)), "My dear beloved children, thank you for being here in prayer and for bending your knees. My children, everything is in its total fulfillment. Fathers are to bless their sons, husbands their wives and holy priests all of you. I ask you to make baptismal renunciations. Renounce Satan and believe in the Lord Saviour, renounce his wiles and believe in God the Saviour, renounce hatred, envy and jealousy and believe in God the Saviour, renounce his snares, confusion and the evils of the mind and believe in God the Saviour.  The church will tremble from its foundations.  Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])

# POLISH
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj zjednoczeni na modlitwie i że odpowiedzieliście w waszych sercach na moje wezwanie. Moje dzieci, wciąż jestem tu dla miłosierdzia Boga, który chce, abyście byli zbawieni. Błagam was, moje dzieci, nie odwracajcie się od Boga, ale módlcie się, módlcie się, módlcie się za tę zagubioną ludzkość, módlcie się za Kościół, w którym nieprawość chce rządzić. Dzieci moje, niestety niewielu ma prawdziwą wiarę, ale proszę was, abyście prowadzili waszych braci drogą Boga, który jest drogą, prawdą i życiem. Będą się działy bardzo złe rzeczy, a ja nie widzę, żebyście byli gotowi; przygotujcie się z godną powagą, abyście mogli wejść do domu Ojca, gdzie wszystko jest gotowe. Nowa Jerozolima jest blisko i chcę, abyście byli w pierwszym rzędzie z radością, miłością i spokojem. Teraz zostawiam was z moim świętym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 6)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, rozejrzyjcie się wokół siebie, nie dajcie się zwieść fałszywym obietnicom diabła. Moje kochane dzieci, wszystko się zmienia wokół was i w was, módlcie się o czasy, które nadejdą, tylko modlitwą można pokonać zło.  Słyszę tak wielu faryzeuszy, którzy wygłaszają piękne kazania, ale na zewnątrz grzeszą przed Bogiem, nie bądźcie tacy jak oni, mówcie o prawdzie, to jedyna rzecz, która może was wyzwolić.  Nie patrz na fałszywy spokój, bo wkrótce zamieni się on w zamieszanie. Nie bójcie się, jeśli jesteście w Bogu. Nie jestem tu po to, by was straszyć, ale by postawić was przed surową, ale prawdziwą rzeczywistością, a to, co się stanie, będzie spowodowane przez ludzkość, która wierzy, że może się obejść bez Boga. Kochajcie się i karmcie się moim Synem. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 10)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie i że odpowiedzieliście na moje wezwanie w waszych sercach. Moje ukochane dzieci, książę zła nie zatrzymuje się, ale posuwa się naprzód z wielką siłą, patrzcie co robi, niestety wszedł w umysły ludzi tak, że potężni mogą nimi manipulować.  Pewnego dnia ludzie oszaleją do tego stopnia, że będą zjadać się nawzajem. Moje dzieci, przeczytajcie czym jest piekło, czyściec i raj, wiele z moich dzieci nie wierzy przede wszystkim w istnienie piekła i wiecznego potępienia, a jednak przez wiele moich ulubionych dzieci (mistyków) zostało wam to powiedziane. Moje dzieci, tak jak istnieje dobro, istnieje też zło i dla tych, którzy tak bardzo modlą się, aby uratować dusze, które są zagubione, poczują obecność Pana, nawróćcie się pilnie, nie macie jeszcze wiele czasu. Moje dzieci, módlcie się bardzo za Brazylię i módlcie się za Włochy, ponieważ ziemia będzie się bardzo mocno trząść. Ja, wasza Matka, będę was chronić z moimi Świętymi Aniołami, nigdy się nie bójcie, idźcie naprzód mówiąc o moim Synu w Świętej Prawdzie. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 13)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie. Dzieci moje, uporządkujcie swoje życie i miejcie silną wiarę, która pomoże wam dostosować się do zmian, które nadejdą. Nie bądźcie zaskoczeni tym, co dzieje się wokół was, pamiętajcie, że im bardziej rozprzestrzenia się nieprawość, tym bardziej oziębnie miłość między wami. Gniew Boży, którego nie można powstrzymać, spadnie na tę ludzkość, ale moje wierne dzieci będą chronione. Przemiana wszystkiego odbędzie się na waszych oczach. Bóg zawsze wystawia waszą wiarę na próbę i jeśli nadal tu jestem, to po to, by pokazać wam drogę, którą należy podążać, aby być wiernym Bogu i aby dać wam wielką nagrodę. Dzieci moje, bądźcie ostrożne wobec tych, którzy proszą was, abyście przedkładali rzeczy tego świata nad Boga; słuchajcie dobrze, gdy ktoś do was mówi, słuchajcie, a zrozumiecie, czy są to słowa Boga, czy nie. W tych czasach widzę, że niektóre z moich dzieci zaniedbują odmawianie Różańca Świętego dla błahostek, ale raz jeszcze mówię wam: Różaniec Święty jest najsilniejszą bronią w walce ze złem. Pytam więc was, moje dzieci: po której stronie chcecie być? Proszę was o adorację, ponieważ przyniesie ona wiele korzyści duchowych i innych. Bądźcie jak pierwsi apostołowie, módlcie się z radością Ducha Świętego, bądźcie wierni Pismu Świętemu. Moje kochane dzieci, dość pretensji, osądów, ego i zazdrości, nikt dla mnie nie jest lepszy od drugiego, wszyscy jesteście moimi dziećmi i chciałbym was poprowadzić ku światłu. Nie zasmucajcie mnie, ale bądźcie świadkami triumfu mego Niepokalanego Serca. Nigdy nie będziecie musieli się bać, moja ochrona będzie dla wszystkich, którzy są wierni i pokorni. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 15)), "Ludu mój, jak możesz wątpić w moją obecność w tym chlebie? Dzieci moje i bracia, czy nie widzicie, że was chronię? Miłość moja do was jest wielka i niczego wam nie zabraknie; karmcie się moim ciałem, póki macie okazję, będziecie musieli się ukryć, aby mnie przyjąć bez obrażania mnie. Wkrótce będziecie potrzebować siebie nawzajem, a ja zawsze będę przy was i ześlę tyle miłosierdzia dla tych, którzy pozostaną mi wierni, błogosławię was, wasz Jezus.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 17)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie i że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, modlę się razem z wami, a w szczególności za młodych ludzi, którzy wymieniają swoje dusze na wolność. Moje dzieci, diabeł chce zabrać jak najwięcej dusz do piekła i wiele z nich wpadło w największe oszustwo ludzkości. Moje dzieci, często pytacie mnie, czy naprawdę będzie wojna, lecz wiedzcie, że duchowa wojna jest już w wielu z was. Moje kochane dzieci, to, co zostało wam przepowiedziane, stanie się, módlcie się dużo, ponieważ sprawiedliwość Boża przyjdzie nagle silniejsza niż kiedykolwiek i możecie nie mieć czasu, aby prosić o przebaczenie. Jeszcze raz proszę o poświęcenie Rosji mojemu Niepokalanemu Sercu, bo stamtąd nadejdzie wiele rzeczy. Drogie dzieci, podążajcie za prawdziwym Magisterium wiary, bądźcie blisko świętych kapłanów, którzy będą was tak bardzo potrzebować. Moje dzieci, zjednoczenie i miłość między wami porusza serce mojego Jezusa, bądźcie dziećmi światłości. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 20)), "Moja córko i siostro, dziękuję ci, że jesteś tu na modlitwie; spójrz wokół siebie, jak bardzo przyzwyczaili się do tych objawień; nie zauważają i nie klękają, bo nie czują, że tu jestem. Wielu nawet mnie nie rozpozna, kiedy wrócę. Moja córko, nie mogę już dłużej przyjmować łez mojej Matki, która została posłana, aby ci towarzyszyć i wskazać ci drogę do zbawienia.  Wielu ludzi jest uwikłanych w ich człowieczeństwo, i dlatego Duch Święty, który został wysłany, nie może działać w ich sercach, ponieważ są one zamknięte. Córko, modlitwa musi być delikatną, osobistą komunikacją ze Mną i z moją Najświętszą Matką; sprawcie, aby Duch Święty mógł przemieniać wasze serca, bo inaczej nie będziecie w stanie znieść tego, co nadchodzi. Proszę was o jedność, braterstwo, pokorę i miłość między wami, bez tych kilku rzeczy będziecie tylko ślepcami, którzy będą towarzyszyć innym ślepcom, nie bądźcie hipokrytami, ale wkładajcie serce w modlitwę, a przede wszystkim powierzajcie się i ufajcie Mi. Ludzkość stała się zbyt uczłowieczona, a serce służy tylko do pulsowania i podążania naprzód; dlatego mówię do was: nie bądźcie pobielonymi grobami, ale podnieście swoją duchowość. Dzieci moje, módlcie się za świętych kapłanów, bo oni was pocieszą w potrzebie; módlcie się za dzieci, aby wzrastały w największej ochronie. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 24)), "Moja córko, wiedz, że nadejdzie to, czego nikt się nie spodziewa, wydarzenia przyspieszają. Moja droga córko, to jest najgorszy czas, w którym żyje ludzkość, wielu ludzi cierpi, ale szczególnie ci, którzy nie znają Boga. Duchowa wojna jest nadal otwarta, ale ci, którzy są wierni, nie mają się czego obawiać. Mówię do moich dzieci światłości, że zło nie będzie w stanie ich dotknąć, więc bądźcie radośni i spokojni, bo opatrzność przyjdzie do was bez wahania. Wiedzcie, że jest to chwila wyboru między dobrem a złem, aby wasza decyzja była dla dobra, a więc dla życia wiecznego. Dzieci moje, mówię wam: całe to zło się skończy, szatan wykorzystuje najsłabsze i najbardziej wrażliwe dusze, ale kiedy przyjdzie mój Syn, wszystko będzie nowe i odnowione. Bądźcie świadkami, że wiara jest radością, miłością i jednością. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Ja, twoja Matka, jestem z tobą.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 27)), "Moje kochane dzieci, dziękuję wam, że jesteście tutaj i uklękneliście do modlitwy. Moje dzieci, wszystko jest w swoim całkowitym spełnieniu. Ojcowie mają błogosławić swoich synów, mężowie swoje żony, a święci kapłani was wszystkich. Proszę was o dokonanie wyrzeczeń chrzcielnych. Wyrzeknijcie się szatana i wierzcie w Pana Zbawiciela, wyrzeknijcie się jego podstępów i wierzcie w Boga Zbawiciela, wyrzeknijcie się nienawiści, zazdrości i zawiści i wierzcie w Boga Zbawiciela, wyrzeknijcie się jego sideł, zamieszania i zła umysłu i wierzcie w Boga Zbawiciela.  Fundamenty Kościoła będą drżeć.  Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])



translator = google_translator()  

# BROKEN

#dataset["text_es"] = dataset["text_it"].apply(lambda x: translator.translate(x,lang_tgt='es'))
#dataset["text_fr"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='fr'))
#dataset["text_zh"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='zh'))
#dataset["text_de"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='de'))
#dataset["text_pt"] = dataset["text_en"].apply(lambda x: translator.translate(x,lang_tgt='pt'))



import goslate
gs = goslate.Goslate()

dataset["text_es"] = dataset["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset["text_fr"] = dataset["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset["text_zh"] = dataset["text_en"].apply(lambda x: gs.translate(x,'zh'))
dataset["text_de"] = dataset["text_en"].apply(lambda x: gs.translate(x,'de'))
dataset["text_pt"] = dataset["text_en"].apply(lambda x: gs.translate(x,'pt'))





dataset.to_csv("july_2021.csv", encoding="utf-8", index=False)
















