# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator

#dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "", dataset["text_it"])



dataset = pd.read_csv("september_cleaned.csv", encoding="utf-8")

dataset["text_pl"] = ""
dataset["text_en"] = ""
dataset["text_it"] = ""
dataset["month_string"] = "September"

dataset["author"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "Holy Mary", dataset["author"] )




# ITALIAN
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "Cari figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei adorati, oggi mio Figlio è con voi, agonizzante, ma pieno d’amore per tutti. Figli miei, molti chiedono i segni, ma quali segni volete quando dalla bocca di alcuni esce fumo e non la parola di Dio, inoltre chiedete e chiedete senza ringraziare mai per tutto ciò che avete. Pregate per la Chiesa che sta assaporando il suo martirio, pregate figli miei, perché il mondo è avvolto dalle tenebre e voi dovete farvi riconoscere come luci splendenti, andando avanti nella verità della parola di Dio. Figli miei,  non siete nel tempo dove vi è permesso di perdervi nelle frivolezze, perché il Figlio dell’uomo è per essere con voi. Vi chiedo di portare la vostra croce con amore per la purificazione sulla terra, se la porterete con gioia avrete grandi ricompense, ma se la porterete con disperazione non potrete provare la gioia promessa. Pregate per  i vulcani .Ora vi lascio con la mia benedizione materna nel nome del Padre e del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 4)), "Figli miei,  siate luce per il mondo, i più bei fiori del mio giardino,  i migliori frutti di questa vigna. Io sono con voi e vi benedico nel nome del Padre e del Figlio e  dello Spirito santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 7)), "Figli miei, grazie per avere risposto alla mia chiamata nel vostro cuore sofferente. Io, vostra Madre consolerò il vostro cuore addolorato. Figli miei, guardate la croce e consolatevi. Date a Gesù tutti i vostri dolori, offrite le offese che vi verranno fatte perché Lui le trasformerà in grazia. Figli miei, la persecuzione di cui vi ho sempre parlato sarà soprattutto spirituale, quindi siate pronti, perché i dolori saranno grandi, più grandi di quanto voi possiate immaginare, ma Io non vi abbandonerò mai, e insieme ai miei angeli vi proteggeremo da tanto dolore. Vi chiedo ancora una volta, convertitevi e decidete per Dio, perché il tempo è finito. Ora vi benedico nel nome del Padre e del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 8)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, non abbiate paura dell’acqua che oggi scende dal cielo, anche nel giorno della mia nascita un fulmine squarciò il cielo e scese tanta acqua. Figli miei, Io tocco la terra per portare la pace nei vostri cuori e nelle vostre case. Figli cari, amate il mio Gesù che tanto vi darà se da parte vostra ci sarà un affidamento completo a Lui, che per amore è morto sulla croce. Oggi farò scendere il mio manto su di voi. Figli miei, vi amo e pregate, pregate tanto, soprattutto per l’Italia. Vi benedico nel nome del Padre e del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 11)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli diletti, quante sono le mie lacrime che scendono su questa umanità che si è data al peccato. Pregate per la mia Chiesa che ormai e nel buio delle tenebre, le stesse che scenderanno su di voi, ma chi avrà fede non dovrà temere. Io, vostra Madre, sto mettendo ognuno di voi nel posto giusto, dovete combattere come veri soldati, la vostra arma principale è la preghiera e il Santo Rosario, arma più forte contro satana, che adesso è molto più infuriato perché sa che il suo tempo svolge alla fine. Figli cari, siate sempre vicini alla preghiera, non allontanatevi mai da essa perché sarà l’unica cosa che avrete nei tempi che stanno arrivando. Figli miei, fate scorte di cibo perché la carestia è alle porte. Siate uniti come fratelli e andate avanti senza alcuna paura, chi è vicino al Signore non può farsi scalfire il cuore da tutto quello che sta per arrivare, perché Lui provvederà ai vostri bisogni, qualunque essi siano. Ora vi benedico nel nome della Santissima Trinità, Padre e Figlio e Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 14)), "Figli miei, grazie per essere qui presenti nel giorno dell’esaltazione della mia croce. Non fissate lo sguardo solo sulla mia sofferenza e guardando la mia croce come qualcosa di triste, ma guardatela piuttosto come Redenzione per ognuno di voi. Fratelli miei, la mia Chiesa è ormai alla deriva a causa del peccato e dell’amore verso altri idoli. Ecco, in questo luogo benedetto dal Padre mio potrete risollevare la vostra anima. Fratelli miei, la vostra fede e il vostro cuore fa di voi dei figli prediletti ai miei occhi e questo luogo sarà uno dei tanti dove fonderò la mia Chiesa. L’apostasia all’interno della mia Chiesa vi ha fatto allontanare da essa a causa dell’ipocrisia e del peccato, venite qui a refrigerarvi con l’amore di Dio che salva, rinfranca e consola. Figli miei, non abbiate mai paura perché Io sono qui. Lottate per la verità e unitevi, solo così sarete vincitori nell’amore e nel vero magistero della fede. Passerò tra di voi per benedirvi uno per uno, nel nome del Padre, nel mio nome e dello Spirito Santo, amen. Il vostro Gesù.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 16)), "Figli miei, grazie per aver ascoltato la mia chiamata nel vostro cuore. Figli miei prediletti, (sacerdoti) pregate affinché i doni che vi sono stati affidati non vadano perduti per non aver obbedito alle leggi di Dio. Figli miei, le prove che arriveranno saranno grazie per voi e per la vostra  purificazione. I politici saranno uno contro l’altro, così come fratello contro il fratello. Pregate per la Chiesa. Ora vi benedico nel nome del Padre e del Figlio e dello Spirito Santo, amen. Il Signore vi accompagnerà verso la luce, uno per uno.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 21)), "Figlia mia, grazie per aver piegato le tue ginocchia. Chiedo ai miei figli prediletti, ai miei apostoli di pregare per la Chiesa perché il demonio sta tessendo una tela molto forte, dove, a causa di sacerdoti, vescovi e cardinali che non hanno più timore di Dio esaltano ciò che non viene dal cielo, mentre coloro che sono obbedienti alla Parola vengono allontanati dalla mia casa. Pregate per l’Italia, la povera Italia dove il peccato e il transumanesimo ha preso piede. Figli cari, guardate i tempi predetti, sono su di voi, ma per coloro che saranno fedeli, scenderà lo Spirito Santo affinchè siano protetti e al riparo, siate uniti nella pace. Ora avete la mia benedizione nel nome del Padre del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 25)), "Fratelli miei, Io sono qui con voi, anche se non mi vedete, sentirete il mio Spirito. Fratelli carissimi, siete in pochi e con il cuore puro, ma pensate alle grazie che vi vengono fatte tutti i giorni?  Il Padre mio, vi riempie di Spirito Santo, ma voi alcune volte siete ciechi e sordi.  Aiutate tutte le persone e questa mia figlia prediletta che è nel mio cuore: Aiutami figlia mia!  Non posso, non posso più tenere il braccio di mio Padre, tutto è su di voi e sarà un continuo di persecuzioni, malattie e ipocrisie.  Figli miei, quanti danni avete fatto, quanto male è stato procurato per causa dei peccati. Ecco, l’America, parte dell’America sparirà e poi dalle ceneri rinascerà a vita nuova, pregate, pregate Dio e la Sua misericordia.  Voi che avete la grazia di ascoltare mia Madre, non fate finta che non accade nulla, è tutto in corso, la terra sta per trasformarsi e arriverà tutto, quando meno ve lo aspettiate, siate pronti, pregate con il cuore. Oh! Figli miei, questo luogo è il mio santuario offerto per voi in gloria del Padre mio, non abbiate mai paura, vi ho mai promesso delle cose che non ho mantenuto? Vi avevo detto che nulla vi sarebbe mancato, ecco, nulla vi è mancato fino ad oggi, allora, perché non credete?  Credete solo a ciò che vi fa comodo per la vostra vita umana, ma non sempre credete   alle parole di mia Madre. Non ragionate figli, non ragionate su quando e come tutto accadrà.  Molti moriranno e molti saranno presi nella Mia Casa, non abbiate paura delle sofferenze, perché voi dovete purificarvi sulla terra per arrivare al cielo nella casa del Padre Vostro e come   pensate di   arrivarci, con le mani luride e le vesti sporche?  No figli, no, siate gloriosi un giorno, solo così potrete arrivare alla gloria di Mio Padre.  State facendo un buon lavoro tutti, continuate non fermatevi a qualunque costo, Io sono qui per voi e non vi lascerò mai soli.  Ora vi dò la mia Santa benedizione, nel nome del Padre, nel mio nome e dello Spirito Santo, amen.  Vi amo figli, vi amo, pregate per Roma, la città a me tanto cara e che mi ha tradito, pregate, perchè presto il sangue scorrerà nelle piazze, pregate, pregate tanto. Il vostro Gesù.", dataset["text_it"])


# ENGLISH

dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "My dear children, thank you for responding to my call in your hearts. My beloved children, today my Son is with you, agonizing, but full of love for all. My children, many ask for signs, but what signs do you want when from the mouths of some comes smoke and not the word of God, moreover you ask and ask without ever giving thanks for all that you have. Pray for the Church that is experiencing its martyrdom, pray my children, because the world is surrounded by darkness and you must make yourselves known as shining lights, going forward in the truth of God's Word. My children, you are not in the time where you are allowed to lose yourselves in frivolities, for the Son of Man is to be with you. I ask you to carry your cross with love for purification on earth, if you carry it with joy you will have great rewards, but if you carry it with despair you will not experience the promised joy. Pray for the volcanoes. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 4)), "My children, be light for the world, the most beautiful flowers in my garden, the best fruits of this vineyard. I am with you and I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 7)), "My children, thank you for having responded to my call in your suffering hearts. I, your Mother, will console your sorrowful heart. My children, look at the cross and console yourselves. Give to Jesus all your sorrows, offer up the offenses that are done to you so that He may transform them into grace. My children, the persecution of which I have always spoken to you will be above all spiritual, so be ready, for the sufferings will be great, greater than you can imagine, but I will never abandon you, and together with my angels we will protect you from so much pain. I ask you once again, convert and choose God, for the time is over. Now I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 8)), "My children, thank you for responding to my call in your hearts. My children, do not be afraid of the water that is coming down from the sky today, even on the day of my birth, lightning ripped through the sky and so much water came down. My children, I am touching the earth to bring peace to your hearts and homes. Dear children, love my Jesus who will give you so much if you entrust yourselves completely to Him, who died on the cross out of love. Today I will make my mantle descend upon you. My children, I love you and pray, pray so much, especially for Italy. I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 11)), "Dear children, thank you for having responded to my call in your hearts. Beloved children, how many tears of mine are falling on this humanity which has given itself over to sin. Pray for my Church which is now in the darkness of darkness, the same darkness that will descend upon you, but whoever has faith should not fear. I, your Mother, am putting each one of you in the right place, you must fight like true soldiers, your main weapon is prayer and the Holy Rosary, the strongest weapon against Satan, who is now much more furious because he knows that his time is coming to an end. Beloved children, always be close to prayer, never stray from it because it will be the only thing you will have in the times that are coming. My children, stock up on food because the famine is coming. Be united as brothers and go forward without any fear, those who are close to the Lord cannot have their hearts shaken by all that is coming, because He will provide for your needs, whatever they may be. Now I bless you in the name of the Holy Trinity, Father and Son and Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 14)), "My children, thank you for being here on the day of the exaltation of my cross. Do not fix your gaze only on My suffering and look at My Cross as something sad, but rather look at it as Redemption for each one of you. My brothers, my Church is now adrift because of sin and love for other idols. Behold, in this place blessed by My Father you will be able to raise your souls. My brothers, your faith and your heart make you beloved children in My eyes and this place will be one of the many where I will establish My Church. The apostasy within My Church has made you turn away from it because of hypocrisy and sin; come here to be refreshed by the love of God who saves, refreshes and consoles. My children, never fear, for I am here. Only in this way will you be victorious in love and in the true teaching of the faith. I will pass among you to bless you one by one, in the name of the Father, in My Name and in the Holy Spirit, Amen. Your Jesus.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 16)), "My children, thank you for listening to my call in your hearts. My beloved children, (priests) pray that the gifts entrusted to you may not be lost for not obeying God's laws. My children, the trials that will come will be graces for you and for your purification. Politicians will be one against another, as well as brother against brother. Pray for the Church. Now I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen. The Lord will accompany each of you into the light.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 21)), "My daughter, thank you for kneeling down. I ask my beloved children, my apostles to pray for the Church because the devil is weaving a very strong web, where, priests, bishops and cardinals who no longer fear God will exalt what is not from Heaven, while those who are obedient to the Word are being driven away from My house. Pray for Italy, poor Italy where sin and transhumanism has taken hold. Beloved children, look at the times foretold, they are upon you, but for those who are faithful, the Holy Spirit will descend so that they may be protected and sheltered, be united in peace. Now you have my blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 25)), "My brothers, I am here with you, even if you do not see me, you will feel My Spirit. My dearest brothers, you are few in number and with a pure heart, but do you think of the graces given to you every day? My Father fills you with the Holy Spirit, but you are sometimes blind and deaf. Help all people and this beloved daughter of mine who is in my heart: Help me daughter! I cannot, I cannot hold My Father's arm anymore, everything is on you and it will be a continuum of persecutions, sickness and hypocrisies. My children, how much damage you have done, how much evil has been procured because of sins. Behold, America, part of America will disappear and then from the ashes it will be reborn to new life, pray, pray to God and His mercy. You who have the grace to listen to my Mother, do not pretend that nothing is happening, everything is in progress, the earth is about to transform and everything will come when you least expect it, be ready, pray with your heart. Oh! My children, this place is My sanctuary offered for you in glory to My Father, never be afraid, have I ever promised you things that I have not kept? I told you that nothing would be lacking, behold, nothing has been lacking until today, so why do you not believe? You believe only what suits you for your human life, but you do not always believe the words of My Mother. Do not reason children, do not reason about when and how everything will happen. Many will die and many will be taken into My House, do not be afraid of suffering, for you must purify yourselves on earth to reach Heaven in Your Father's house and how do you expect to get there, with filthy hands and dirty clothes? No children, no, be glorious one day, only in this way will you be able to arrive at My Father's glory. You are all doing a good job, continue, do not stop at any cost, I am here for you and I will never leave you alone.  Now I give you My Holy Blessing, in the name of the Father, in My Name and the Holy Spirit, Amen.  I love you children, I love you, pray for Rome, the city that is so dear to me and that has betrayed me, pray, because soon the blood will flow in the squares, pray, pray so much. Your Jesus.", dataset["text_en"])


# POLISH

dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "Moje drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje kochane dzieci, dzisiaj mój Syn jest z wami, umierający, ale pełen miłości do wszystkich. Dzieci moje, wielu prosi o znaki, ale jakich znaków chcecie, skoro z ust niektórych wychodzi tylko dym, a nie Słowo Boże, co więcej, prosicie i prosicie, nie dziękując nigdy za wszystko, co macie. Módlcie się za Kościół, który przeżywa swoje męczeństwo; módlcie się, moje dzieci, ponieważ świat jest spowity w ciemnościach, a wy musicie dać się poznać jako jaśniejące światła, idące naprzód w prawdzie słowa Bożego. Dzieci moje, nie jesteście w czasie, w którym wolno wam zatracić się we frywolności, bo Syn Człowieczy ma być z wami. Proszę was, abyście nieśli swój krzyż z miłością dla oczyszczenia na ziemi, jeśli będziecie go nieść z radością, otrzymacie wielkie nagrody, lecz jeśli będziecie go nieść z rozpaczą, nie doświadczycie obiecanej radości. A teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 4)), "Dzieci moje, bądźcie światłem dla świata, najpiękniejszymi kwiatami w moim ogrodzie, najlepszymi owocami tej winnicy. Jestem z wami i błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 7)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych cierpiących sercach. Ja, twoja Matka, pocieszę twoje smutne serce. Dzieci moje, spójrzcie na krzyż i pocieszcie się. Oddajcie Jezusowi wszystkie wasze boleści, ofiarujcie przewinienia, które wam wyrządzono, aby On mógł je przemienić w łaskę. Dzieci moje, prześladowanie, o którym zawsze wam mówiłem, będzie przede wszystkim duchowe, więc bądźcie gotowi, bo bóle będą wielkie, większe niż możecie sobie wyobrazić, ale ja was nigdy nie opuszczę i razem z moimi aniołami ochronimy was przed tak wielkim bólem. Proszę was jeszcze raz, nawróćcie się i wybierzcie Boga, bo czas się skończył. A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 8)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, nie bójcie się wody, która dziś spływa z nieba; także w dniu moich narodzin piorun rozdarł niebo i spadło dużo wody. Dzieci moje, dotykam ziemi, aby przynieść pokój do waszych serc i domów. Drogie dzieci, kochajcie mojego Jezusa, który da wam tak wiele, jeśli całkowicie powierzycie się Mu, który umarł na krzyżu z miłości. Dziś pozwalam, aby mój płaszcz zstąpił na was. Moje dzieci, kocham was, módlcie się, módlcie się mocno, szczególnie za Włochy. Błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 11)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, jakże wiele moich łez spływa na tę ludzkość, która oddała się grzechowi. Módlcie się za mój Kościół, który jest teraz w wielkich ciemnościach, tych samych ciemnościach, które spadną na was, ale kto ma wiarę, niech się nie lęka. Ja, wasza Matka, stawiam każdego z was na właściwym miejscu, musicie walczyć jak prawdziwi żołnierze, waszą główną bronią jest modlitwa i Różaniec święty, najsilniejsza broń przeciwko szatanowi, który jest teraz o wiele bardziej wściekły, ponieważ wie, że jego czas dobiega końca. Drogie dzieci, bądźcie zawsze blisko modlitwy, nigdy nie oddalajcie się od niej, ponieważ będzie ona jedyną rzeczą, jaką będziecie mieli w nadchodzących czasach. Dzieci moje, zaopatrzcie się w żywność, bo głód nadchodzi. Bądźcie zjednoczeni jako bracia i idźcie naprzód bez lęku, ci, którzy są blisko Pana, nie mogą mieć serc swoich wstrząśniętych tym wszystkim, co nadchodzi, ponieważ On zaspokoi wasze potrzeby, jakiekolwiek by one nie były. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 14)), "Dzieci moje, dziękuję wam, że jesteście tutaj w dniu wywyższenia mojego krzyża. Nie patrzcie tylko na moje cierpienie i nie patrzcie na mój krzyż jako na coś smutnego, ale patrzcie na niego raczej jako na Odkupienie dla każdego z was. Moi bracia, mój Kościół jest teraz rozproszony z powodu grzechu i miłości do innych bożków. Oto w tym miejscu, błogosławionym przez mojego Ojca, będziecie mogli podnosić wasze dusze. Bracia moi, wasza wiara i wasze serce czynią was umiłowanymi dziećmi w Moich oczach, a to miejsce będzie jednym z wielu, gdzie założę Mój Kościół. Apostazja w moim Kościele spowodowała, że odwróciliście się od niego z powodu hipokryzji i grzechu; przyjdźcie tutaj, aby odnowić się Bożą miłością, która zbawia, pokrzepia i pociesza. Dzieci moje, nie lękajcie się, bo ja tu jestem. Walczcie o prawdę i jednoczcie się, tylko w ten sposób zwyciężycie w miłości i w prawdziwej nauce wiary. Będę przechodził między wami, aby po kolei was błogosławić, w imię Ojca, w imię Moje i w imię Ducha Świętego, Amen. Twój Jezus.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 16)), "Dzieci moje, dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Moje kochane dzieci, (kapłani) módlcie się, aby powierzone wam dary nie zostały utracone za nieprzestrzeganie praw Bożych. Dzieci moje, próby, które przyjdą, będą dla was łaskami i oczyszczeniem. Politycy będą jedni przeciwko drugim jak brat przeciwko bratu. Módlcie się za Kościół. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen. Pan będzie każdemu z was towarzyszył w drodze ku światłu.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 21)), "Moja córko, dziękuję ci, że uklęknęłaś. Proszę moje ukochane dzieci, moich apostołów, aby modlili się za Kościół, ponieważ diabeł tka bardzo mocną sieć, w której z powodu niebojących się już Boga księży, biskupów i kardynałów, wywyższają to, co nie pochodzi z Nieba, podczas gdy ci, którzy są posłuszni Słowu, są wypędzani z mojego domu. Módlcie się za Włochy, biedne Włochy, gdzie zapanował grzech i transhumanizm. Drogie dzieci, spójrzcie na przepowiedziane czasy, są one nad waszymi głowami, ale dla tych, którzy są wierni, Duch Święty zstąpi, aby mogli być chronieni, zabezpieczeni i zjednoczeni w pokoju. Teraz masz moje błogosławieństwo w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 25)), "Bracia moi, jestem tu z wami; nawet jeśli mnie nie widzicie, to poczujecie mojego Ducha. Moi drodzy bracia, jest was niewielu i macie czyste serca, ale czy myślicie o łaskach, które są wam udzielane każdego dnia? Mój Ojciec napełnia was Duchem Świętym, ale wy jesteście czasem ślepi i głusi. Pomóżcie wszystkim ludziom i tej mojej ulubionej córce, która jest w moim sercu: Pomóż mi, moja córko!  Nie mogę, nie mogę już dłużej trzymać ramienia mojego Ojca, wszystko ciąży na was i będzie to ciągłe prześladowanie, choroby i zakłamywanie. Dzieci moje, jak wiele szkód wyrządziliście, jak wiele zła dokonało się z powodu grzechów. Oto Ameryka, część Ameryki zniknie, a potem z popiołów odrodzi się do nowego życia, módlcie się, módlcie się do Boga i Jego Miłosierdzia.  Wy, którzy macie łaskę słuchać mojej Matki, nie udawajcie, że nic się nie dzieje, wszystko jest w drodze, ziemia ma się przekształcić i wszystko przyjdzie, kiedy najmniej się tego spodziewacie, bądźcie gotowi, módlcie się sercem. Dzieci moje, to miejsce jest moim sanktuarium ofiarowanym dla was w chwale mojemu Ojcu, nigdy się nie bójcie, czy kiedykolwiek obiecałem wam rzeczy, których nie spełniłem? Powiedziałem wam, że niczego wam nie zabraknie, oto do dziś niczego wam nie brakuje, dlaczego więc nie wierzycie? Wierzycie tylko w to, co wam odpowiada w waszym ludzkim życiu, ale nie zawsze wierzycie słowom mojej Matki. Nie zastanawiajcie się, dzieci, nie zastanawiajcie się, kiedy i jak wszystko się wydarzy. Wielu umrze i wielu zostanie zabranych do Mojego Domu, nie bójcie się cierpienia, bo musicie się oczyścić na ziemi, aby wejść do Nieba,  do domu Ojca waszego, a jak myślicie, jak się tam dostaniecie z brudnymi rękami i brudnym ubraniem? Nie dzieci, nie, stańcie się pełnymi chwały, tylko w ten sposób będziecie mogli wejść do Chwały Mojego Ojca.  Wszyscy wykonujecie wspaniałą pracę, kontynuujcie ją, nie zatrzymujcie się za wszelką cenę, jestem tu dla Was i nigdy nie zostawię Was samych.  Teraz daję wam moje Święte Błogosławieństwo, w imię Ojca, w Imię moje i Ducha Świętego, Amen. Kocham was, moje dzieci, kocham was, módlcie się za Rzym, miasto, które jest mi tak drogie, a które mnie zdradziło, módlcie się, bo wkrótce krew popłynie na placach, módlcie się, módlcie się tak bardzo. Wasz Jezus.", dataset["text_pl"])




import goslate
gs = goslate.Goslate()

dataset["text_es"] = dataset["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset["text_fr"] = dataset["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset["text_zh"] = dataset["text_en"].apply(lambda x: gs.translate(x,'zh'))


dataset["text_de"] = dataset["text_en"].apply(lambda x: gs.translate(x,'de'))

dataset["text_pt"] = dataset["text_en"].apply(lambda x: gs.translate(x,'pt'))





dataset.to_csv("september_2021.csv", encoding="utf-8", index=False)







