# -*- coding: utf-8 -*-
"""
Created on Fri Jan 1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator

#dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "", dataset["text_it"])



dataset = pd.read_csv("october_cleaned.csv", encoding="utf-8")

dataset["text_pl"] = ""
dataset["text_en"] = ""
dataset["text_it"] = ""
dataset["month_string"] = "October"






# ITALIAN
dataset["text_it"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 3)), "Figli miei, grazie per aver ascoltato la mia chiamata nel vostro cuore. Figli, piccoli bambini miei, tanti saranno coloro che si allontaneranno, ma tanti altri si stanno avvicinando alla fede perché hanno compreso che è l’unica salvezza. Ritornate a formare piccole comunità, seguite il Vangelo e la vera dottrina della fede. Figli miei, camminate verso tempi difficili, ma non dovete temere quando il vostro cuore è per Gesù, evangelizzate e soprattutto testimoniate. Figli miei, le vostre preghiere mi rendono felice e soprattutto consolano il cuore del mio Gesù, approfittate di questi tempi perché presto l’Eucarestia sparirà. Siate apostoli del mio cuore e preparatevi, perché tutto è pronto, affinché le scritture abbiano compimento. Pregate per la Chiesa. Oggi, tante saranno le grazie che scenderanno su di voi. Ora vi lascio con la mia benedizione materna nel nome del Padre e del Figlio dello Spirito Santo, amen.", dataset["text_it"] )
dataset["text_it"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 6)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, pregate, pregate, pregate molto per Gerusalemme perché sarà nella tribolazione. Voi siete stati scelti come soldati di luce per abbattere le tenebre che vi circondano. Io già vi dissi che tutto sarebbe precipitato presto, e ancora vi dico: quando sentirete e vedrete fratelli contro fratelli, guerriglie per le strade, altre pandemie in arrivo a causa di virus e quando la falsa democrazia diventerà dittatura, ecco, allora il tempo dell’arrivo di Gesù è vicino. Figli miei, vivete questi messaggi che arrivano per grazia, siate uniti e ricordate che la parola di Dio è Una e per sempre, guai a coloro che proveranno a cambiare ciò che Gesù ha lasciato detto, perché presto Lui vi renderà ciò che vi spetta, sia nel bene che nel male. Fate scorte di acqua, cibo e medicine. Oggi, in questo luogo, scenderanno molte grazie, piegate le vostre ginocchia nella preghiera. Ora vi benedico nel nome del Padre e del Figlio e dello Spirito Santo. Pregate per le vittime che ci saranno a causa di un disastro aereo.", dataset["text_it"] )
dataset["text_it"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 9)), "Figli miei, grazie per essere qui nella preghiera e per aver risposto alla mia chiamata nel vostro cuore. Figli miei, approfittate di questo momento di grazia per convertirvi in modo urgente, ma ancora non avete capito che non c’è più tempo? Guardate mio Figlio, Lui è morto per voi, Lui e solo Lui potrà darvi tutto ciò di cui avrete bisogno, Lui è pace e amore e nonostante abbia dimostrato in mille modi che vi sta vicino, voi siete presi dalle cose del mondo e non avete tempo da dedicargli, non comprendete che solo il cielo potrà avere cura di voi? Figli miei, non affannatevi, non siate dubbiosi e spaventati, perché chi è con Cristo non dovrà temere, affidatevi completamente a Lui e obbedite alle sue leggi, siate sempre pronti perché tutto accadrà in un’ora. Vi benedico nel nome del Padre e del Figlio e dello Spirito Santo, amen.", dataset["text_it"] )
dataset["text_it"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 12)), "Figli miei, grazie per essere qui nella preghiera e aver risposto la mia chiamata nel vostro cuore. Figli miei, non abbiate paura, se solo affidaste tutto al mio Gesù! Lui dottore dell’anima, Lui Unico Salvatore. Figli miei, la purificazione è necessaria per la vostra anima, vedrete guerriglie nel mondo, vedrete virus anche mortali dove non arriverà la scienza e la medicina, vedrete uragani, terremoti e distruzioni ovunque, tutto questo arriverà a causa dell’umanità che vuole cambiare tutto con l’umanesimo. La Chiesa di Roma: sarà grande la sua purificazione. Rifugiatevi nel mio cuore Immacolato. Figli, bambini miei, ascoltate le mie parole, non per impaurirvi, ma per prepararvi ed essere consolati, non siete soli, Dio vi benedice. Io Madre Misericordiosa sono con voi tutti i giorni, prendete le mie mani ed Io vi porterò sul sentiero perfetto che porta alla luce. Io manderò i miei angeli per assistervi, abbiate la fede viva e coraggiosa, vi amo. Ora vi benedico nel nome del Santissima Trinità, Padre, Figlio e Spirito Santo, amen.", dataset["text_it"] )
dataset["text_it"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 16)), "Figli amati, grazie per essere qui nella preghiera e per aver risposto alla mia chiamata nel vostro cuore. Figli miei, piango perché vedo quanto dolore state incontrando sulla via, ma ancora una volta, vi chiedo di convertirvi perché nonostante Io venga fra voi, molti ancora non credono. Figli miei, nonostante la vostra fede sarete toccati spiritualmente anche dal demonio, fate attenzione, abbiate ben presente il discernimento che potrà aiutarvi. Figli miei, tutto è in gran lunga velocizzato perché non c’è più tempo, unitevi tra fratelli e non rimanete soli perché questo è il momento in cui avrete bisogno l’uno dell’altro. Pregate tanto perché le guerriglie aumenteranno. Pregate per la Chiesa. I maremoti saranno in aumento causando grandi catastrofi. Ora vi lascio con la mia benedizione materna nel nome del Padre e del Figlio dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 19)), "Sorella mia benedetta, Io, il tuo Gesù ti chiedo di parlare ai tuoi fratelli. Desidero che ognuno di voi, lasci le cose della terra, siate leggeri dalle cose materiali perché porterete solo il vostro cuore al mio cospetto. Figli miei, vedete i segni del mio ritorno e come ho già detto ai miei apostoli, non vengo per unire, ma per dividere il bene dal male. In questo tempo di satana, che ormai è alla conclusione, molti dei miei figli prediletti (sacerdoti) che si sono dati ai piaceri del mondo, chiedo di tornare a me con lo stesso amore con cui sono stati chiamati, prima che per loro si aprano le porte dell’inferno. Figli e fratelli amati, preparatevi con coraggio come veri soldati per combattere la più grande apostasia mai vissuta. Vi chiedo ancora di prepararvi bene per l’avvertimento, non tutti crederanno, neanche molti dei miei consacrati. Io ho sempre chiesto di offrire a me le vostre sofferenze, eppure ciò nonostante sono stato rifiutato. Fratelli, Io Gesù Cristo, non ho mai abbandonato nessuno, Io, come un mendicante ho cercato amore e spesso sono in un angolo della vostra casa, del vostro lavoro, del vostro cuore e vi guardo in attesa di un vostro sguardo e invece siete attratti dalla falsa luce che non è la mia. Vivete di più i luoghi dove appare la mia Santissima Madre, perché è lì che dovrete andare quando vi sarà chiesto, affinché non possa mancarvi nulla, protezione e tanta provvidenza. Vi chiedo di rivolgere a Me e a mia Madre, la vostra preghiera ed Io sarò felice di aiutarvi, ho detto anche ai miei apostoli e lo ripeto oggi, sarò con voi fino alla fine dei tempi. Fratelli, sarete come i primi cristiani, insieme e uniti faremo meraviglie per il Padre mio e gli angeli esulteranno e canteranno la gloria di Dio. Vi benedico nel nome della Santissima Trinità. Il vostro caro Gesù.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 23)), "Figlia mia, grazie per aver risposto alla mia chiamata. Diletta, sento quanta amarezza e solitudine c’è nel tuo cuore per questo mondo e per tutto ciò che va alla rovescia. Figli miei, sappiate che questa stagione sarà difficile, la pandemia è stata la scusa per abituarvi a ciò che arriverà e se non sarete forti nella fede non riuscirete a sopravvivere, tanto sarà il dolore che si vedrà anche intorno a voi, solo chi avrà una fede viva e salda sarà protetto dei miei angeli. Vi chiedo di portare le anime a Dio, parlate di Lui a chi non lo conosce. Vedrete presto scendere il fuoco dal cielo, sarà il battesimo dello Spirito Santo e alcuni malati guariranno. L’Avvertimento è prossimo, siate pronti, ma per coloro che non piegheranno le ginocchia riconoscendo Dio, avranno la dannazione eterna. Pregate per la Siria, perché da lì, avrà inizio la guerra, pregate per la Chiesa, dove presto annunceranno l’unica religione e l’appoggio al transumanesimo, crocifiggendo ancora una volta Gesù Cristo. Ora vi lascio con la mia benedizione materna, nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 26)), "Cara figlia, grazie per aver risposto alla mia chiamata nel tuo cuore. Figli miei, vi chiedo di ascoltare i veri profeti di questi ultimi tempi, perché loro sono i miei messaggeri e come tali saranno la vostra guida. Io, voglio salvare tutti i miei figli ed è per questo che ancora tocco la terra, non c’è più cieco di chi non vuole vedere e nonostante i segni dei tempi predetti, anche chi ha fede si rifiuta di guardare ciò che accade.  Figli miei, i tempi sono duri, tutta la terra continua ad essere coperta dalle tenebre, vi chiedo di pregare tanto ed è urgente la conversione. Vi chiedo ancora: per la festa di satana rimanete a casa nella preghiera e accendete una candela benedetta, purtroppo le sette sataniche faranno riti mostruosi, ma non abbiate paura i miei angeli sono con voi e saranno più numerosi con il passare del tempo, tutto è stabilito per la lotta finale. Ora vi benedico nel nome del Padre del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 30)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli cari, non abbiate paura per ciò che arriverà, vedrete cose mai viste, ma se siete in Cristo il male non vi toccherà. Figli, seguite i miei consigli, pregate per la Chiesa e per i consacrati, Io li guardo e vedo con quanta indifferenza cambiano la verità della Parola di Dio. Siate dei chicchi nascosti e germoglierete come grandi frutti, andate avanti con forza e unitevi nell’amore di Dio e seguite il vero magistero della fede. Ora, vi lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])


# ENGLISH
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 3)), "My children, thank you for listening to my call in your hearts. My little children, many will be those who go astray, but many others are coming closer to the faith because they have understood that it is the only salvation. Return to form small communities, follow the Gospel and the true doctrine of the faith. My children, walk towards difficult times, but you must not fear when your heart is for Jesus, evangelize and above all witness. My children, your prayers make me happy and above all they console the heart of my Jesus, take advantage of these times because soon the Eucharist will disappear. Be apostles of My Heart and prepare yourselves, for everything is ready, so that the scriptures may be fulfilled. Pray for the Church. Today, many will be the graces that will descend upon you. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"] )
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 6)), "My children, thank you for responding to My call in your hearts. My children, pray, pray, pray very much for Jerusalem for it will be in tribulation. You have been chosen as soldiers of light to bring down the darkness that surrounds you. I have already told you that everything would soon fall apart, and again I say to you: when you hear and see brothers against brothers, warfare in the streets, more pandemics coming because of viruses and when false democracy becomes dictatorship, behold, then the time of Jesus' arrival is near. My children, live these messages that are coming by grace, be united and remember that the word of God is One and forever, woe to those who will try to change what Jesus has left said, for soon He will return to you what you deserve, both good and bad. Stock up on water, food and medicine. Many graces will descend here today, bend your knees in prayer. I bless you now in the name of the Father and the Son and the Holy Spirit. Pray for the victims that will be there because of an air disaster.", dataset["text_en"] )
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 9)), "My children, thank you for being here in prayer and for responding to my call in your hearts. My children, take advantage of this moment of grace to convert urgently, but have you still not understood that there is no more time? Look at my Son, He died for you, He and only He can give you everything you need, He is peace and love and although He has shown in a thousand ways that He is close to you, you are taken by the things of the world and have no time to dedicate to Him, do you not understand that only Heaven can take care of you? My children, do not be anxious, do not be doubtful and afraid, because whoever is with Christ will not have to fear, entrust yourselves completely to Him and obey His laws, always be ready because everything will happen in an hour. I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"] )
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 12)), "My children, thank you for being here in prayer and answering my call in your hearts. My children, do not be afraid, if you would only entrust everything to My Jesus! He is the Doctor of the soul, He is the only Savior. My children, purification is necessary for your souls, you will see wars in the world, you will see viruses even deadly ones where science and medicine will not arrive, you will see hurricanes, earthquakes and destruction everywhere, all this will come because of humanity that wants to change everything with humanism. The Church of Rome: her purification will be great. Take refuge in my Immaculate Heart. My children, my children, listen to my words, not to frighten you, but to prepare yourselves and be consoled, you are not alone, God blesses you. I, the Merciful Mother, am with you every day, take my hands and I will lead you on the perfect path that leads to the light. I will send My angels to assist you, have living and courageous faith, I love you. Now I bless you in the name of the Holy Trinity, Father and the Son and the Holy Spirit, Amen.", dataset["text_en"] )
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 16)), "Beloved children, thank you for being here in prayer and for responding to my call in your hearts. My children, I weep because I see how much pain you are encountering on the way, but once again, I ask you to convert because although I am coming among you, many still do not believe. My children, in spite of your faith you will also be touched spiritually by the devil, be careful, be aware of the discernment that can help you. My children, everything is greatly accelerated because there is no more time, unite among brothers and do not remain alone because this is the time when you will need each other. Pray a lot because the wars will increase. Pray for the Church. Tidal waves will be on the rise causing great catastrophes. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 19)), "My blessed sister, I, your Jesus, ask you to speak to your brothers. I desire that each one of you, leave the things of the earth, be light of material things for you will bring only your heart before Me. My children, see the signs of my return and as I have already told my apostles, I am not coming to unite, but to divide the good from the evil. In this time of Satan, which is now at its conclusion, many of my beloved sons (priests) who have given themselves to the pleasures of the world, I ask them to return to me with the same love with which they were called, before the gates of hell open for them. Beloved sons and brothers, prepare yourselves with courage as true soldiers to fight the greatest apostasy ever experienced. I ask you again to prepare yourselves well for the warning; not everyone will believe, not even many of my consecrated people. I have always asked you to offer your sufferings to Me, and yet I have been refused. Brothers, I, Jesus Christ, have never abandoned anyone, I, like a beggar have sought love and I am often in a corner of your home, your work, your heart and I look at you waiting for your gaze and instead you are attracted by the false light that is not mine. Live more in the places where my Most Holy Mother appears, for that is where you must go when you are asked, so that you may lack nothing, protection and much providence. I ask you to address your prayers to Me and to My Mother and I will be happy to help you, as I also told My apostles and repeat today, I will be with you until the end of time. Brothers, you will be like the first Christians, together and united we will work wonders for My Father and the angels will exult and sing the glory of God. I bless you in the name of the Most Holy Trinity. Your dear Jesus.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 23)), "My daughter, thank you for responding to my call. Beloved, I feel how much bitterness and loneliness there is in your heart for this world and all that is going upside down. My children, know that this season will be difficult, the pandemic was the excuse to get used to what will come and if you are not strong in faith you will not be able to survive, so much will be the pain that will also be seen around you, only those who will have a living and firm faith will be protected by my angels. I ask you to bring souls to God, speak of Him to those who do not know Him. You will soon see fire coming down from heaven, it will be the baptism of the Holy Spirit and some sick people will be healed. The Warning is near, be ready, but for those who will not bend their knees acknowledging God, they will have eternal damnation. Pray for Syria, for from there, the war will begin, pray for the Church, where they will soon announce the one religion and support for transhumanism, crucifying Jesus Christ once again. Now I leave you with my motherly blessing, in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 26)), "Dear daughter, thank you for responding to My call in your heart. My children, I ask you to listen to the true prophets of these last times, for they are my messengers and as such they will be your guide. I, want to save all my children and that is why I still touch the earth, there is no one more blind than he who does not want to see and despite the signs of the times foretold, even those who have faith refuse to look at what is happening. My children, times are hard, the whole earth continues to be covered by darkness, I ask you to pray a lot and conversion is urgent. I ask you again: for the feast of Satan stay at home in prayer and light a blessed candle, unfortunately the satanic sects will perform monstrous rites, but do not be afraid, my angels are with you and will be more numerous as time goes by, everything is set for the final battle. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 30)), "My children, thank you for having responded to my call in your hearts. Dear children, do not be afraid of what is to come, you will see things you have never seen, but if you are in Christ, evil will not touch you. My children, follow my advice, pray for the Church and for the consecrated, I watch them and I see with how much indifference they change the truth of God's Word. Be hidden grains and you will sprout as great fruits, go forth with strength and unite in the love of God and follow the true magisterium of faith. Now, I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])


# POLISH
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 3)), "Dzieci moje, dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Moje małe dzieci, wielu będzie takich, którzy zbłądzą, ale wielu innych zbliża się do wiary, ponieważ zrozumieli, że jest ona jedynym ratunkiem. Powróćcie do tworzenia małych wspólnot, podążajcie za Ewangelią i prawdziwą doktryną wiary. Dzieci moje, idziecie ku trudnym czasom, ale nie wolno wam się lękać, jeśli wasze serce jest dla Jezusa, ewangelizujcie, a przede wszystkim dawajcie świadectwo. Moje dzieci, wasze modlitwy sprawiają mi radość, a przede wszystkim pocieszają serce mojego Jezusa, wykorzystajcie ten czas, bo wkrótce Eucharystia zniknie. Bądźcie apostołami mojego serca i przygotujcie się, bo wszystko jest gotowe, aby się wypełniło Pismo Święte. Módlcie się za Kościół. Dziś wiele będzie łask, które zstąpią na was. A teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"] )
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 6)), "Moje dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, módlcie się, módlcie się, módlcie się mocno za Jerozolimę, ponieważ będzie ona w ucisku. Zostaliście wybrani jako żołnierze światła, aby pokonać ciemność, która was otacza. Już wam mówiłam, że wszystko wkrótce upadnie, i powtarzam wam: gdy usłyszycie i zobaczycie braci przeciwko braciom, wojny na ulicach, więcej pandemii nadchodzących z powodu wirusów i gdy fałszywa demokracja stanie się dyktaturą, oto czas przyjścia Jezusa jest bliski. Dzieci moje, żyjcie tymi orędziami, które przychodzą przez łaskę, bądźcie zjednoczeni i pamiętajcie, że słowo Boże jest Jedno i na zawsze, biada tym, którzy próbują zmienić to, co Jezus zostawił do powiedzenia, bo wkrótce zwróci wam to, co wam się należy, zarówno dobre, jak i złe. Zaopatrz się w wodę, żywność i lekarstwa. Wiele łask zstąpi tu dzisiaj, zegnijcie kolana w modlitwie. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Módlcie się za ofiary katastrofy lotniczej.", dataset["text_pl"] )
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 9)), "Dzieci moje, dziękuję wam za to, że jesteście tutaj na modlitwie i że odpowiadacie na moje wezwanie w waszych sercach. Dzieci moje, skorzystajcie z tej chwili łaski, aby pilnie się nawrócić, ale czy jeszcze nie zrozumieliście, że nie ma już czasu? Spójrzcie na mojego Syna, On umarł za was, On i tylko On może dać wam wszystko, czego potrzebujecie, On jest pokojem i miłością i chociaż na tysiące sposobów pokazał, że jest blisko was, wy jesteście zajęci sprawami świata i nie macie czasu, aby poświęcić się Jemu, czy nie rozumiecie, że tylko Niebo może się wami zaopiekować? Dzieci moje, nie bądźcie niespokojne, nie wątpcie i nie bójcie się, bo kto jest z Chrystusem, nie będzie musiał się lękać, powierzcie się Mu całkowicie i bądźcie posłuszni Jego prawom, bądźcie zawsze gotowi, bo wszystko stanie się w godzinę. Błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"] )
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 12)), "Dzieci moje, dziękuję wam, że jesteście tutaj na modlitwie i że odpowiedzieliście w waszych sercach na moje wezwanie. Moje dzieci, nie bójcie się, jeśli tylko powierzycie wszystko mojemu Jezusowi! On jest lekarzem duszy, On jest jedynym Zbawicielem. Dzieci moje, konieczne jest oczyszczenie waszych dusz, zobaczycie wojny na świecie, zobaczycie wirusy, nawet te śmiertelne, gdzie nauka i medycyna nie dotrą, zobaczycie huragany, trzęsienia ziemi i zniszczenia wszędzie, wszystko to przyjdzie z powodu ludzkości, która chce zmienić wszystko humanizmem. Kościół Rzymski: jego oczyszczenie będzie wielkie. Schroncie się w moim Niepokalanym Sercu. Moje dzieci, wsłuchajcie się w moje słowa, nie po to, aby się przestraszyć, ale po to, aby się przygotować i pocieszyć; nie jesteście sami, Bóg wam błogosławi. Ja, Matka Miłosierna, jestem z wami każdego dnia; weźcie mnie za ręce, a poprowadzę was doskonałą drogą, która prowadzi do światła. Wyślę moje anioły, aby wam pomagały, miejcie żywą i odważną wiarę, kocham was. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"] )
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 16)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj na modlitwie i że odpowiadacie na moje wezwanie w waszych sercach. Dzieci moje, płaczę, bo widzę, jak wiele bólu napotykacie na drodze, ale jeszcze raz proszę was o nawrócenie, bo choć przychodzę do was, wielu jeszcze nie wierzy. Moje dzieci, pomimo waszej wiary, będziecie również dotykani duchowo przez diabła; bądźcie ostrożni, bądźcie świadomi rozeznania, które może wam pomóc. Moje dzieci, wszystko przyspieszyło, bo nie ma już czasu, jednoczcie się między braćmi i nie pozostawajcie sami, bo to jest moment, kiedy będziecie potrzebować siebie nawzajem. Módlcie się mocno, bo wojny będą się nasilać. Módlcie się za Kościół. Fale przypływów będą rosły, powodując wielkie katastrofy. A teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 19)), "Moja błogosławiona siostro, Ja, twój Jezus, proszę cię, abyś przemówiła do swoich braci. Pragnę, aby każdy z was zostawił rzeczy ziemskie, był lekki w rzeczach materialnych, ponieważ przyniesiecie tylko swoje serca przede mnie. Dzieci moje, patrzcie na znaki mojego powrotu i jak już powiedziałem moim apostołom, nie przychodzę, aby jednoczyć, ale aby oddzielać dobrych od złych. W tym czasie szatana, który dobiega końca, wielu z moich umiłowanych synów (kapłanów), którzy oddali się przyjemnościom tego świata, proszę, aby powrócili do mnie z tą samą miłością, z jaką zostali powołani, zanim otworzą się przed nimi bramy piekieł. Umiłowani synowie i bracia, przygotujcie się z odwagą jak prawdziwi żołnierze do walki z największą apostazją, jaka kiedykolwiek miała miejsce. Jeszcze raz proszę was, abyście się dobrze przygotowali na ostrzeżenie; nie wszyscy uwierzą, nawet wielu z moich konsekrowanych. Zawsze prosiłem was, abyście ofiarowali mi swoje cierpienia, a jednak spotykałem się z odmową. Bracia, Ja, Jezus Chrystus, nigdy nikogo nie opuściłem, Ja, jak żebrak, szukałem miłości i często jestem w kącie waszego domu, waszej pracy, waszego serca i patrzę na was, czekając na wasze spojrzenie, a zamiast tego przyciąga was fałszywe światło, które nie jest moje. Żyjcie więcej w miejscach, gdzie pojawia się moja Najświętsza Matka, bo tam właśnie musicie się udać, gdy zostaniecie poproszeni, aby nie zabrakło wam niczego, ochrony i wiele opatrzności. Proszę was, kierujcie wasze modlitwy do Mnie i do Mojej Matki, a Ja wam chętnie pomogę; powiedziałem też Moim apostołom i powtarzam to dzisiaj: będę z wami aż do końca czasów. Bracia, będziecie jak pierwsi chrześcijanie, razem i zjednoczeni będziemy czynić cuda dla mojego Ojca, a aniołowie będą się radować i śpiewać na chwałę Boga. Błogosławię cię w imię Trójcy Przenajświętszej. Wasz drogi Jezu.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 23)), "Moja córko, dziękuję ci, że odpowiedziałaś na moje wezwanie. Umiłowani, czuję, jak wiele goryczy i samotności jest w waszym sercu wobec tego świata i wobec wszystkiego, co się przewraca do góry nogami. Moje dzieci, wiedzcie, że ten okres będzie trudny, pandemia była pretekstem do przyzwyczajenia się do tego, co nadejdzie i jeśli nie jesteście silni w wierze, nie będziecie w stanie przetrwać, tak wielki będzie ból, który będzie widoczny wokół was, tylko ci, którzy będą mieli żywą i mocną wiarę, będą chronieni przez moich aniołów. Proszę was, abyście przyprowadzali dusze do Boga, mówili o Nim tym, którzy Go nie znają. Wkrótce zobaczysz ogień zstępujący z nieba, będzie to chrzest Duchem Świętym, a niektórzy chorzy ludzie zostaną uzdrowieni. Ostrzeżenie jest blisko, bądźcie gotowi, ale dla tych, którzy nie klękają w uznaniu Boga, będzie wieczne potępienie. Módlcie się za Syrię, bo tam zacznie się wojna, módlcie się za Kościół, gdzie niedługo ogłoszą jedną religię i poparcie dla transhumanizmu, krzyżując po raz kolejny Jezusa Chrystusa. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 26)), "Droga córko, dziękuję ci, że odpowiedziałaś na moje wezwanie w twoim sercu. Dzieci moje, proszę was, abyście słuchali prawdziwych proroków tych ostatnich czasów, ponieważ są oni moimi posłańcami i jako tacy będą waszymi przewodnikami. Chcę uratować wszystkie moje dzieci i dlatego wciąż stąpam po ziemi, nie ma bardziej ślepego niż ten, kto nie chce widzieć i mimo przepowiedzianych znaków czasu, nawet ci, którzy mają wiarę, nie chcą patrzeć na to, co się dzieje. Dzieci moje, czasy są ciężkie, całą ziemię nadal spowijają ciemności, proszę was o wiele modlitwy, nawrócenie jest pilne. Proszę was jeszcze raz: na święto szatana pozostańcie w domu na modlitwie i zapalcie błogosławioną świecę, niestety sekty satanistyczne będą odprawiać potworne rytuały, ale nie bójcie się, moi aniołowie są z wami i w miarę upływu czasu będą coraz liczniejsi, wszystko zostało ustalone do ostatecznej bitwy. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 30)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, nie bójcie się tego, co nadejdzie, zobaczycie rzeczy, których nigdy nie widzieliście, ale jeśli jesteście w Chrystusie, zło was nie dotknie. Moje dzieci, słuchajcie moich rad, módlcie się za Kościół i za osoby konsekrowane, patrzę na nich i widzę, z jaką obojętnością zmieniają prawdę Słowa Bożego. Bądźcie ukrytymi ziarnami, a wykiełkujecie jako wielkie owoce, wyjdźcie z mocą i zjednoczcie się w miłości Boga i podążajcie za prawdziwym Magisterium wiary. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])


import goslate
gs = goslate.Goslate()

dataset["text_es"] = dataset["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset["text_fr"] = dataset["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset["text_zh"] = dataset["text_en"].apply(lambda x: gs.translate(x,'zh'))


dataset["text_de"] = dataset["text_en"].apply(lambda x: gs.translate(x,'de'))

dataset["text_pt"] = dataset["text_en"].apply(lambda x: gs.translate(x,'pt'))





dataset.to_csv("october_2021.csv", encoding="utf-8", index=False)







