# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator


dataset_2017 = pd.read_json("trevignano2017.js")



missing_2017 = pd.read_csv("missing_2017.csv")


#Italian
missing_2017["text_it"] = np.where(((missing_2017["month"] == 4) & (missing_2017["day"] == 16)), "Amati fratelli, eccomi io sono qui nella mia resurrezione e anche nella vostra. Prendete la strada della salvezza e della santificazione, sono qui per tendervi la mia mano. Vi amo e annunciate a tutti la mia resurrezione. Vi benedico nel nome del Padre del figlio e dello Spirito Santo. Amen. Il vostro Gesù.", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 4) & (missing_2017["day"] == 30)), "Cari Figli,grazie per avermi accolta , grazie per la grande fede che c’è nel vostro cuore. Amati Figli , siate i miei apostoli, siate i miei piccoli e non lasciate mai la mano che Gesù stende con tutta la sua misericordia, cercate solo in lui la salvezza, la verità e la via. Pregate per la Francia e per il Cile. Vi amo e vi benedico nel nome Padre del Figlio e dello Spirito Santo. Amen.", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 5) & (missing_2017["day"] == 7)), "Amati figli,  oggi mi avete resa felice per aver ascoltato la mia richiesta di consacrazione al mio cuore Immacolato e a mio Figlio Gesù. Adesso sarete più riconosciuti agli occhi del Padre. Oggi ci saranno molte grazie. Con tutto il mio amore materno vi benedico nel nome del Padre e del Figlio e dello Spirito Santo. Amen.", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 7) & (missing_2017["day"] == 15)), "Amati figli miei, Gesù vi ha dato il dono del discernmento e voi dovete usarlo. In questo momento tutti voi,  vi sentite nervosi , tristi, inquietati e questi sono tutti sentimenti che il demonio vi dà per farvi cadere nella tentazione,  questo è il momento della Scelta. Cari figli , ci sarà padre contro figlio , sorella contro sorella , marito contro moglie e tutto ciò cadrà nella disperazione. Vi prego fate la giusta scelta e amatevi tanto. Io sono con voi per confortarvi. Ora vi do’ la mia benedizione nel nome del Padre del Figlio e dello Spirito Santo. Amen.", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 7) & (missing_2017["day"] == 18)), "Amata figlia di luce, grazie per essere qui per aver portato le pecorelle del gregge che si erano smarrite, grazie per aver accolto e portato avanti la missione che ti ho affidato. Io, come regina di luce Vi illumino di Spirito Santo insieme a mio Figlio Gesù che è qui tra voi. State vicino a Lui perché soffre tanto, Vi amo e vi benedico nel nome del Padre del Figlio e dello spirito santo. Amen.", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 7) & (missing_2017["day"] == 19)), "Amati miei , aprite i vostri cuori ,pregate, pregate , pregate. Ricordate sempre che Gesù è morto per la vostra salvezza. Credete sempre al vero magistero della chiesa. Gesù è l unica verità, finché io tocchero’ la terra , il braccio della giustizia sarà fermo. Voglio salvarvi e rendervi puri come agnelli. Ora vi benedico nel nome del Padre del Figlio e dello Spirito Santo. Amen.", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 9) & (missing_2017["day"] == 2)), "Amati figli miei , grazie per essere qui riuniti nella preghiera, ma quanta distrazione sento nelle vostre menti! Prendete la croce con tutte le sue sofferenze e le sue amarezze, cosi come ha fatto Gesù e andate avanti. Poveri coloro che non  ascoltano i miei insegnamenti. Ora vi dò la mia benedizione nel nome del Padre del Figlio e dello Spirito Santo. Amen.", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 9) & (missing_2017["day"] == 3)), "Figli miei grazie,  mi consola oggi vedervi in tanti riuniti qui in questo posto benedetto. Amati miei, quando vi deridono , quando vi danno dei bugiardi, degli stolti, ricordate che non lo dicono a voi ,ma a mio Figlio, è Lui che rinnegano e offendono tutte le volte. Amati miei, io sono qui per darvi il coraggio della fede, non tornate mai indietro quando avete intrapreso la strada della verità. Siate coraggiosi, e vi invito a testimoniare. (Oggi la Madonna , ha detto che molte persone avrebbero ricevuto tante grazie). Guardate intorno a voi la giustizia e la purificazione farsi strada.Pregate figli miei, pregate. Io sarò con voi, pregate per l’Italia e soprattutto per Roma. Pregate per la Spagna. Ora vi benedico nel nome del Padre del Figlio e dello Spirito Santo. Amen", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 3)), "Figli amati, gioielli miei, grazie perché avete ascoltato e risposto alla mia chiamata nel vostro cuore. Piccoli miei, quante sofferenze sento nei vostri cuori, ma vi prego abbiate Fede e aprite i vostri cuori affinchè i miei raggi d’amore possono entrare in voi. Amati miei, ciò che avevo predetto si sta verificando, guardate con i vostri occhi, il giorno della grande apostasia nella chiesa, è oggi, presto toglieranno l’Eucarestia e i crocifissi dalle chiese per dare posto al modernismo e all’eresia. Vi prego, tenete tra le mani il santo rosario e recitatelo tutti giorni, pregate per i sacerdoti e per l’umanità, affinchè possano scegliere la via della verità, che è mio Figlio Gesù. La Falsa chiesa insieme ai demoni, stanno prendendo il posto del vostro Gesù. Questo è il giorno delle tribolazioni, uscite ed annunciate il ritorno mio Figlio. Siate miei apostoli, Vi amo e Vi benedico nel nome della Santissima Trinità, Padre, Figlio e Spirito Santo. Amen", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 17)), "Amati figli, grazie per aver risposto alla mia chiamata, oggi siete qui in preghiera e desidero che continuate su questa strada. Amati miei, presto una notizia eclatante sarà data dal vaticano. Pregate per Papa Benedetto. Pregate per la Russia. Ora vi benedico nel nome del Padre del Figlio e dello Spirito Santo. Amen.", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 22)), "Perle del mio cuore , grazie per essere qui nella preghiera, state vivendo momenti di grande confusione, mio Figlio vi sta sempre accanto prendendovi per mano, basterebbe che voi lo seguiste. Amori miei questi sono tempi duri e io piango perché so a cosa andrete in contro. Tempo fa, mio Figlio vi chiese di essere suoi soldati , oggi io vi chiedo di combattere e di stare uniti,  come in unica anima e continuare a restare fermi nella vera fede e nella vera vera chiesa, oggi ho bisogno di voi sulla terra,  più che mai. Pregate per l’America. Ora vi benedico nel nome del Padre del Figlio e dello Spirito Santo. Amen", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 31)), "Figli miei, non disperatevi! Amati miei , stasera i demoni danzeranno e festeggeranno il nemico di Dio . Figli miei, Gesù aveva previsto per Roma la nuova Gerusalemme, così fece edificare la Sua Chiesa, ma all’interno cosa hanno fatto? Hanno continuato a tramare contro di Lui,  e ancora oggi lo crocifiggono e continuano a dire che la misericordia è grande,  ma presto sarà la giustizia a trionfare perché la Chiesa di Dio trionferà. Voi siete le mie fiammelle accese, andate avanti e intensificate la preghiera, perché accadranno cose terribili. Vi proteggerò ora e sempre , il Padre vi attende fra le Sue braccia. Ora vi benedico nel nome del Padre del Figlio e dello Spirito Santo. Amen", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 12) & (missing_2017["day"] == 14)), "Amata figlia, guarda il mondo in subbuglio, neanche la nascita di mio Figlio viene rispettata,  il mondo è ormai senza la presenza di Dio. Io sono una madre addolorata che guarda questo mondo caduto nella confusione causata da satana. Figlia mia,  ormai le mie fiamme più accese all’ interno delle chiese  hanno una luce fioca,  solo il mio popolo che cammina nella verità e nella speranza, riesce ad illuminare le mie Chiese con la fiamma dell’amore per Dio. Grazie e andate avanti con coraggio. Ora ti benedico nel nome del Padre del Figlio e dello Spirito Santo. Amen", missing_2017["text_it"])
missing_2017["text_it"] = np.where(((missing_2017["month"] == 12) & (missing_2017["day"] == 16)), "Figlia mia, io sono una madre addolorata, oggi come ieri busso alle porte, ma nessuno apre, quando stava per nascere il figlio di Dio nessuno ha creduto. Questo Natale, non  pensate ai festeggiamenti ipocriti con doni, ma aprite le porte, affinchè mio Figlio abbia un posto dove nascere, un luogo che sia pieno di amore di pace e speranza. Vi amo figli, seguite la strada della fede e   preparatevi al Suo arrivo. Io sono qui per avvertirvi e proteggervi e chiedervi di amare mio Figlio . Ora vi benedico nel nome del Padre del Figlio e dello Spirito Santo. Amen", missing_2017["text_it"])



#English
missing_2017["text_en"] = np.where(((missing_2017["month"] == 4) & (missing_2017["day"] == 16)), "Beloved brothers, here I am in my resurrection and also in yours. Take the way of salvation and sanctification, I am here to extend my hand to you. I love you and announce my resurrection to all. I bless you in the name of the Father and the Son and of the Holy Spirit. Amen. Your Jesus.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 4) & (missing_2017["day"] == 30)), "Dear children, thank you for having welcomed me and thank you for the great faith that is in your heart. Beloved children, be my apostles, be my little ones and never let go of the hand that Jesus extends with all His mercy; seek salvation, truth and the way in Him alone. Pray for France and Chile. I love you and I bless you in the name of the Father and the Son and the Holy Spirit. Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 5) & (missing_2017["day"] == 7)), "Beloved children, today you have made me happy by listening to my request for consecration to my Immaculate Heart and to my Son Jesus. Now you will be more recognized in the eyes of the Father. Today there will be many graces. With all my motherly love, I bless you in the name of the Father and of the Son and of the Holy Spirit. Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 7) & (missing_2017["day"] == 15)), "My beloved children, Jesus has given you the gift of discernment and you must use it. At this time all of you, you feel nervous, sad, restless and these are all feelings that the devil gives you to make you fall into temptation, this is the time of the Choice. Dear children, there will be father against son, sister against sister, husband against wife and all of this will fall into despair. Please, make the right choice and love each other very much. I am with you to comfort you. Now I give you my blessing in the name of the Father and the Son and the Holy Spirit. Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 7) & (missing_2017["day"] == 18)), "Beloved daughter of light, thank you for being here to carry the sheep of the flock that had gone astray, thank you for accepting and carrying out the mission I have entrusted to you. I, as Queen of Light, enlighten you with the Holy Spirit together with my Son Jesus who is here among you. I love you and bless you in the name of the Father and the Son and the Holy Spirit. Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 7) & (missing_2017["day"] == 19)), "My beloved ones, open your hearts, pray, pray, pray. Always remember that Jesus died for your salvation. Always believe in the true Magisterium of the Church. Jesus is the only truth, as long as I touch the earth, the arm of justice will be still. I want to save you and make you pure as lambs. Now I bless you in the name of the Father and of the Son and of the Holy Spirit. Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 9) & (missing_2017["day"] == 2)), "My beloved children, thank you for being gathered here in prayer, but how much distraction I hear in your minds! Take up the cross with all its sufferings and bitterness, just as Jesus did, and move on. Poor those who do not listen to my teachings. Now I give you my blessing in the name of the Father and the Son and the Holy Spirit. Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 9) & (missing_2017["day"] == 3)), "My children, thank you, it consoles me today to see so many of you gathered here in this blessed place. My beloved ones, when they mock you, when they call you liars, fools, remember that they are not saying this to you, but to my Son, it is He whom they deny and offend every time. My beloved ones, I am here to give you the courage of faith, never turn back when you have embarked on the path of truth. Be courageous, and I encourage you to witness. (Today Our Lady , said that many people would receive many graces). Look around you at the justice and purification taking place. Pray, my children, pray. I will be with you, pray for Italy and especially for Rome. Pray for Spain. I now bless you in the name of the Father, the Son and the Holy Spirit. Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 3)), "Beloved children, my jewels, thank you for having listened and responded to my call in your hearts. My little ones, how much suffering I feel in your hearts, but I ask you to have faith and open your hearts so that my rays of love may enter you. My beloved ones, what I predicted is happening, look with your eyes, the day of the great apostasy in the Church is today, soon they will remove the Eucharist and the crucifixes from the churches to give place to modernism and heresy. Please hold the Holy Rosary in your hands and recite it every day, pray for the priests and for humanity, so that they may choose the way of truth, which is my Son Jesus. The false church together with the demons are taking the place of your Jesus. This is the day of tribulation, come out and announce my Son's return. Be my apostles, I love you and I bless you in the name of the Most Holy Trinity, Father and the Son and the Holy Spirit, Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 17)), "Beloved children, thank you for having responded to my call, today you are here in prayer and I desire that you continue on this way. Beloved ones, soon a striking news will be given from the Vatican. Pray for Pope Benedict. Pray for Russia. I now bless you in the name of the Father and the Son and the Holy Spirit. Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 22)), "Pearls of my heart, thank you for being here in prayer, you are living in a time of great confusion, my Son is always beside you taking you by the hand, it would be enough for you to follow Him. My loves, these are hard times and I weep because I know what you will be up against. Some time ago, my Son asked you to be His soldiers, today I ask you to fight and to stay united, as one soul and continue to remain firm in the true faith and in the true church, today I need you on earth, more than ever. Pray for America. I now bless you in the name of the Father and the Son and the Holy Spirit. Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 31)), "My children, do not despair! My beloved ones , tonight the demons will dance and celebrate the enemy of God . My children, Jesus had foreseen for Rome the new Jerusalem, so He had His Church built, but inside what have they done? They continued to plot against Him, and even today they crucify Him and continue to say that mercy is great, but soon justice will triumph because the Church of God will triumph. You are my burning flames, go ahead and intensify your prayer, for terrible things will happen. I will protect you now and always, the Father is waiting for you in His arms. Now I bless you in the name of the Father and the Son and the Holy Spirit. Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 12) & (missing_2017["day"] == 14)), "Beloved daughter, look at the world in turmoil, not even the birth of my Son is respected, the world is now without the presence of God. I am a grieving mother looking at this world fallen into confusion caused by Satan. My daughter, by now my brightest flames in the churches have a dim light, only my people who walk in truth and hope are able to illuminate my churches with the flame of love for God. Thank you and go forward with courage. I now bless you in the name of the Father and the Son and the Holy Spirit. Amen.", missing_2017["text_en"])
missing_2017["text_en"] = np.where(((missing_2017["month"] == 12) & (missing_2017["day"] == 16)), "My daughter, I am a grieving mother, today as yesterday I knock on the doors, but no one opens, when the Son of God was about to be born no one believed. This Christmas, do not think of hypocritical celebrations with gifts, but open the doors, so that my Son may have a place to be born, a place that is full of love, peace and hope. I love you children, follow the way of faith and prepare for His coming. I am here to warn you and protect you and ask you to love my Son. Now I bless you in the name of the Father and the Son and the Holy Spirit. Amen.", missing_2017["text_en"])

#Polish
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 4) & (missing_2017["day"] == 16)), "Umiłowani bracia, oto ja w moim, a także w waszym zmartwychwstaniu. Podejmijcie drogę zbawienia i uświęcenia, jestem tutaj, aby wyciągnąć rękę do Was. Kocham was i ogłaszam wszystkim moje zmartwychwstanie. Błogosławię Was w imię Ojca i Syna i Ducha Świętego. Amen. Wasz Jezus.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 4) & (missing_2017["day"] == 30)), "Drogie dzieci, dziękuję wam za to, że mnie przyjęliście, dziękuję za wielką wiarę, która jest w waszych sercach. Umiłowane dzieci, bądźcie moimi apostołami, bądźcie moimi maluczkimi i nigdy nie puszczajcie ręki, którą Jezus wyciąga z całym swoim miłosierdziem; szukajcie zbawienia, prawdy i drogi tylko w Nim. Módlcie się za Francję i za Chile. Kocham was i błogosławię w imię Ojca i Syna i Ducha Świętego. Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 5) & (missing_2017["day"] == 7)), "Umiłowane dzieci, dzisiaj sprawiłyście mi radość, wysłuchując mojej prośby o poświęcenie się mojemu Niepokalanemu Sercu i mojemu Synowi Jezusowi. Teraz będziecie mieć większe uznanie w oczach Ojca. Dzisiaj spł┘ynie wiele łask. Z całą moją matczyną miłością błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 7) & (missing_2017["day"] == 15)), "Moje kochane dzieci, Jezus dał wam dar rozeznawania i musicie go używać. W tym czasie wszyscy czujecie się zdenerwowani, smutni, niespokojni i są to uczucia, które diabeł daje wam, abyście ulegli pokusie; jest to czas Wyboru. Drogie dzieci, będzie ojciec przeciwko synowi, siostra przeciwko siostrze, mąż przeciwko żonie, wszyscy oni popadną w rozpacz. Błagam was, dokonajcie właściwego wyboru i kochajcie się bardzo mocno. Jestem z tobą, aby cię pocieszyć. Teraz daję wam moje błogosławieństwo w imię Ojca i Syna i Ducha Świętego, Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 7) & (missing_2017["day"] == 18)), "Umiłowana córko światłości, dziękuję ci, że jesteś tutaj, aby prowadzić owce stada, które zbłądziły, dziękuję ci, że przyjęłaś i wypełniłaś misję, którą ci powierzyłem. Ja, jako Królowa Światłości, oświecam was Duchem Świętym wraz z moim Synem Jezusem, który jest tutaj wśród was. Bądźcie blisko Niego, bo On tak bardzo cierpi. Kocham Was i błogosławię w imię Ojca i Syna i Ducha Świętego. Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 7) & (missing_2017["day"] == 19)), "Moi ukochani, otwórzcie swoje serca, módlcie się, módlcie się, módlcie się. Zawsze pamiętaj, że Jezus umarł dla twojego zbawienia. Zawsze wierzcie w prawdziwe Magisterium Kościoła. Jezus jest jedyną prawdą. Tak długo, jak dotykam ziemi, ramię sprawiedliwości będzie nieruchome. Chcę was zbawić i uczynić was czystymi jak baranki. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 9) & (missing_2017["day"] == 2)), "Moje kochane dzieci, dziękuję wam za to, że jesteście tu zgromadzeni na modlitwie, ale jakże wielkie rozproszenie słyszę w waszych umysłach! Weźcie krzyż ze wszystkimi jego cierpieniami i goryczą, jak to uczynił Jezus, i idźcie naprzód. Biedni są ci, którzy nie słuchają moich słów. Teraz daję wam moje błogosławieństwo w imię Ojca i Syna i Ducha Świętego. Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 9) & (missing_2017["day"] == 3)), "Dzieci moje, dziękuję wam; pociesza mnie dzisiaj widok tak wielu z was zgromadzonych w tym błogosławionym miejscu. Umiłowani moi, kiedy z was szydzą, kiedy nazywają was kłamcami, głupcami, pamiętajcie, że nie mówią tego do was, ale do mojego Syna, to On jest tym, któremu za każdym razem zaprzeczają i którego obrażają. Umiłowani moi, jestem tutaj, aby dać wam odwagę wiary, nigdy nie zawracajcie z drogi prawdy. Bądźcie odważni i zachęcam was do dawania świadectwa. (Dzisiaj Matka Boża powiedziała, że wielu ludzi otrzyma wiele łask). Obserwuj, jak wokół ciebie dokonuje się sprawiedliwość i oczyszczenie. Módlcie się, moje dzieci, módlcie się. Będę z wami; módlcie się za Włochy, a szczególnie za Rzym. Módlcie się za Hiszpanię. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego. Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 3)), "Umiłowane dzieci, moje klejnoty, dziękuję wam za to, że wysłuchaliście i odpowiedzieliście na moje wezwanie w waszych sercach. Moi mali, jak wiele cierpienia odczuwam w waszych sercach, ale błagam was o wiarę i otwarcie waszych serca, aby moje promienie miłości mogły wejść do was. Umiłowani moi, to, co przepowiedziałam, dzieje się, spójrzcie waszymi oczami, dzień wielkiej apostazji w Kościele jest dzisiaj, wkrótce usuną z kościołów Eucharystię i krucyfiksy, aby dać miejsce modernizmowi i herezji. Błagam was, trzymajcie w rękach różaniec święty i odmawiajcie go codziennie, módlcie się za kapłanów i za ludzkość, aby wybrali drogę prawdy, którą jest mój Syn Jezus. Fałszywy kościół wraz z demonami zajmują miejsce waszego Jezusa. To jest dzień ucisku, wyjdźcie i ogłoście powrót mojego Syna. Bądźcie moimi apostołami, kocham was i błogosławię wam w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego. Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 17)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie, dzisiaj jesteście tutaj na modlitwie i pragnę, abyście nadal podążali tą drogą. Umiłowani moi, wkrótce Watykan przekaże uderzającą wiadomość. Módlcie się za papieża Benedykta. Módlcie się za Rosję. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 22)), "Perły mego serca, dziękuję wam, że jesteście tutaj na modlitwie, przeżywacie chwile wielkiego zamętu, mój Syn jest zawsze obok was, biorąc was za rękę, wystarczy, że pójdziecie za Nim. Moi kochani, to są ciężkie czasy i płaczę, bo wiem, z czym będziecie musieli się zmierzyć. Jakiś czas temu mój Syn poprosił was, abyście byli Jego żołnierzami, dziś proszę was, abyście walczyli i pozostali zjednoczeni, jak w jednej duszy i trwali mocno w prawdziwej wierze i w prawdziwym Kościele, dziś potrzebuję was na ziemi, bardziej niż kiedykolwiek. Módlcie się za Amerykę. Teraz błogosławię was w imię Ojca i Syna, i Ducha Świętego. Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 10) & (missing_2017["day"] == 31)), "Dzieci moje, nie rozpaczajcie! Moi umiłowani, dziś wieczorem demony będą tańczyć i sławić wroga Boga. Dzieci moje, Jezus przewidział dla Rzymu nową Jerozolimę, dlatego kazał zbudować swój Kościół, ale co oni zrobili w środku? Oni nadal spiskowali przeciwko Niemu, a nawet dzisiaj Go krzyżują i nadal mówią, że miłosierdzie jest wielkie, ale wkrótce sprawiedliwość zatriumfuje, ponieważ Kościół Boży zatriumfuje. Jesteście moimi ognistymi płomieniami, idźcie dalej i zintensyfikujcie swoją modlitwę, ponieważ wydarzą się straszne rzeczy. Będę was chronić teraz i zawsze, Ojciec czeka na was w swoich ramionach. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 12) & (missing_2017["day"] == 14)), "Umiłowana córko, spójrz na świat pogrążony w chaosie, nawet narodziny mojego Syna nie są szanowane, świat jest teraz bez obecności Boga. Jestem zrozpaczoną matką, która patrzy na ten świat pogrążony w zamęcie spowodowanym przez szatana. Moja córko, już teraz moje najjaśniejsze płomienie w kościołach mają przygaszone światło, tylko moi ludzie, którzy chodzą w prawdzie i nadziei, są w stanie oświetlić moje kościoły płomieniem miłości do Boga. Dziękuję wam, idźcie naprzód z odwagą. Błogosławię was teraz w imię Ojca i Syna i Ducha Świętego. Amen.", missing_2017["text_pl"])
missing_2017["text_pl"] = np.where(((missing_2017["month"] == 12) & (missing_2017["day"] == 16)), "Moja córko, jestem zasmuconą matką, dziś, tak jak wczoraj, pukam do drzwi, ale nikt nie otwiera, kiedy Syn Boży miał się narodzić, nikt nie uwierzył. W te święta nie myślcie o obłudnych obchodach z prezentami, ale otwórzcie drzwi, aby mój Syn miał gdzie się narodzić, miejsce pełne miłości, pokoju i nadziei. Kocham was, małe dzieci, idźcie drogą wiary i przygotujcie się na Jego przyjście. Jestem tu, aby was ostrzec, chronić i prosić, abyście kochali mojego Syna. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen.", missing_2017["text_pl"])


translator = google_translator()  


missing_2017["text_es"] = missing_2017["text_en"].apply(lambda x: translator.translate(x,lang_tgt='es'))
missing_2017["text_fr"] = missing_2017["text_en"].apply(lambda x: translator.translate(x,lang_tgt='fr'))
missing_2017["text_zh"] = missing_2017["text_en"].apply(lambda x: translator.translate(x,lang_tgt='zh'))
missing_2017["text_de"] = missing_2017["text_en"].apply(lambda x: translator.translate(x,lang_tgt='de'))
missing_2017["text_pt"] = missing_2017["text_en"].apply(lambda x: translator.translate(x,lang_tgt='pt'))

import goslate
gs = goslate.Goslate()

missing_2017["text_es"] = missing_2017["text_it"].apply(lambda x: gs.translate(x,'es'))
missing_2017["text_fr"] = missing_2017["text_en"].apply(lambda x: gs.translate(x,'fr'))
missing_2017["text_zh"] = missing_2017["text_en"].apply(lambda x: gs.translate(x,'zh'))

#missing_2017.to_csv("missing_2017.csv", index=False)



missing_2017["text_de"] = missing_2017["text_en"].apply(lambda x: gs.translate(x,'de'))
missing_2017["text_pt"] = missing_2017["text_en"].apply(lambda x: gs.translate(x,'pt'))



dataset_merged = pd.concat([dataset_2017, missing_2017])


dataset_merged["month_string"] = np.where(dataset_merged["month"] == 4, "April", dataset_merged["month_string"]) 
dataset_merged["month_string"] = np.where(dataset_merged["month"] == 5, "May", dataset_merged["month_string"]) 
dataset_merged["month_string"] = np.where(dataset_merged["month"] == 7, "July", dataset_merged["month_string"]) 
dataset_merged["month_string"] = np.where(dataset_merged["month"] == 9, "August", dataset_merged["month_string"]) 
dataset_merged["month_string"] = np.where(dataset_merged["month"] == 10, "October", dataset_merged["month_string"]) 
dataset_merged["month_string"] = np.where(dataset_merged["month"] == 12, "December", dataset_merged["month_string"]) 



dataset_merged = dataset_merged.sort_values(by=["month", "day"])




dataset_merged.to_json("trevignano2017.js",orient="records")







