# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np




dataset = pd.read_csv("trevignano2018.csv", encoding="utf-8")

dataset["text"] = dataset["text"].str.replace(" amen", " Amen")
dataset["text"] = dataset["text"].str.replace("\"ma io prego!\"", "'ma io prego!'")
dataset["text"] = dataset["text"].str.replace("Amen\. \"", "Amen.")
dataset["text"] = dataset["text"].str.replace("Amen\. \”", "Amen.")
dataset["text"] = dataset["text"].str.replace("Amen\"", "Amen.")
dataset["text_en"] = dataset["text_en"].str.replace("Amen\"", "Amen.")
dataset["text"] = dataset["text"].str.replace("Tu sei il nostro Re!!\”", "'Tu sei il nostro Re!!'")
dataset["text"] = dataset["text"].str.replace("miei figli\”", "miei figli")
dataset["text"] = dataset["text"].str.replace("Amore e Vita\”", "Amore e Vita")
dataset["text"] = dataset["text"].str.replace("Amen Figli miei", "Amen. Figli miei")
dataset["text"] = dataset["text"].str.replace("Ora vi do la mia santa benedizione nel nome del Padre, del Figlio, dello Spirito Santo\. Amen Il segno di oggi :", "Ora vi do la mia santa benedizione nel nome del Padre, del Figlio, dello Spirito Santo. Amen. Il segno di oggi: 'Amore'")
dataset["text"] = dataset["text"].str.replace("Amen Durante", "Amen. Durante")
dataset["text"] = dataset["text"].str.replace("Amen Ecco", "Amen. Ecco")
dataset["text"] = dataset["text"].str.replace("Spirito Santo \.", "Spirito Santo.")
dataset["text"] = dataset["text"].str.replace("Amen ''Popolo Mio'' SEGNI DAL CIELO ''I H S''", "Amen. Sign: 'Popolo Mio'. Segni Dal Cielo: 'I H S'")
dataset["text"] = dataset["text"].str.replace("''IO SONO CON VOI \" ", "'IO SONO CON VOI'")
dataset["text"] = dataset["text"].str.replace("\"", "")
dataset["text"] = dataset["text"].str.replace("AmenLa", "Amen. La")
dataset["text"] = dataset["text"].str.replace("Amen La", "Amen. La")
dataset["text"] = dataset["text"].str.replace("AmenIn", "Amen. In")
dataset["text"] = dataset["text"].str.replace("Santo \. Amen", "Santo, Amen.")
dataset["text"] = dataset["text"].str.replace(" : ", ": ")
dataset["text"] = dataset["text"].str.replace("Spirito santo", "Spirito Santo")
dataset["text"] = dataset["text"].str.replace("Dio Figli", "Dio. Figli")
dataset["text"] = dataset["text"].str.replace("Amen Oggi", "Amen. Oggi")
dataset["text"] = dataset["text"].str.replace("Continua a leggere\. \. \. \»", "")
dataset["text"] = dataset["text"].str.replace("sinistro\.\.", "sinistro.")
dataset["text"] = dataset["text"].str.replace("Amen Il ", "Amen. Il ")
dataset["text"] = dataset["text"].str.replace("Amen \.", "Amen.")
dataset["text"] = dataset["text"].str.replace("Amen ", "Amen.")
dataset["text"] = dataset["text"].str.replace("uno per uno", "uno per uno.")
dataset["text"] = dataset["text"].str.replace("Gesu'", "Gesù")
dataset["text"] = dataset["text"].str.replace("\(13 04", "(13 04)")
dataset["text"] = dataset["text"].str.replace("insultato mortificato", "insultato, mortificato")
dataset["text"] = dataset["text"].str.replace("la Germania \.", "la Germania.")
dataset["text"] = dataset["text"].str.replace("Il Vostro Gesù", "Il Vostro Gesù.")
dataset["text"] = dataset["text"].str.replace("disperazione \.", "disperazione.")
dataset["text"] = dataset["text"].str.replace("voce \. ", "voce. ")
dataset["text"] = dataset["text"].str.replace("Bagnoregio 26 08", "")
dataset["text"] = dataset["text"].str.replace("\.Amen", ". Amen")
dataset["text"] = dataset["text"].str.replace("vostro Si di", "vostro 'Si' di")
dataset["text"] = dataset["text"].str.replace("facendo \.", "facendo .")
dataset["text"] = dataset["text"].str.replace("\"Beati coloro che verranno perseguitati a causa del mio nome\"", "'Beati coloro che verranno perseguitati a causa del mio nome'")
dataset["text"] = dataset["text"].str.replace("\"quando capirete i segni la mia venuta sarà vicina\"", "'quando capirete i segni la mia venuta sarà vicina'")
dataset["text"] = dataset["text"].str.replace("noi \.", "noi.")
dataset["text"] = dataset["text"].str.replace("AmenDopo", "Amen. Dopo")
dataset["text"] = dataset["text"].str.replace("pubblicamente \.", "pubblicamente.")
dataset["text"] = dataset["text"].str.replace("preghiera \.", "preghiera.")
dataset["text"] = dataset["text"].str.replace(" \.", ".")
dataset["text"] = dataset["text"].str.replace("Amen Alle", "Amen. Alle")
dataset["text"] = dataset["text"].str.replace("pregate pregate", "pregate, pregate")
dataset["text"] = dataset["text"].str.replace("Salvatevi\”", "'Salvatevi'")
dataset["text"] = dataset["text"].str.replace("\” Riflessione", "Riflessione")
dataset["text"] = dataset["text"].str.replace("\"sentire \"", "'sentire'")
dataset["text"] = dataset["text"].str.replace("Amen\”\.", "Amen.")
dataset["text"] = dataset["text"].str.replace("SIATE TESTIMONI", "Sign: 'SIATE TESTIMONI'")




dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 2)), "Beloved children, thank you for being gathered here for the prayer of the Holy Rosary. Beloved children, love is God, but how little love and faith I sometimes see in the hearts of men; pray for conversion; the time is ripe for everything to be fulfilled. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 3)), "Beloved children, today how many blessings will descend upon you for being here in prayer. Children, please listen to the cry of love of my Son who does not give up and does not want to lose His children. I am a mother who can no longer look on with sorrow, those who surrender to Satan. Soon, I will come together with my Son Jesus into the world and I will take you in my arms. Beloved children, continue to be always on the way of faith and continue to be my soldiers and true apostles. This will be a year of changes. Now I bless you leaving peace in your hearts, in the name of the Most Holy Trinity, Father Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 4)), "Beloved children, I am approaching, I am ready, grace is with you. My daughter, you must tell everyone as soon as possible that they must pray for my coming. You will be glorified by my love, you have enormous grace and you do not understand it. Children, give yourselves peace among yourselves, you must be together and ready, soon you will be able to enjoy the things My Father has prepared for you, love one another, love all of you. Have faith, have faith all of you. Love yourselves more than your own children, the devil will not win, but you with your faith will have won all eternity for life. Do not be angry, do not be nervous, I leave you Peace, all the rest comes from Satan, who tries to insinuate himself into your lives, do not allow him to do so, your salvation will soon arrive together with me glorious, smile and rejoice. Do not reason too much, reasoning comes from satan, do not reason for the things of your life, entrust everything to me who am your Savior Jesus Christ. My Father sends me for the salvation of men, please do not reason too much, you will never understand my Father's plans. Thank you for accepting me. Your Jesus. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 6)), "Dear children, thank you for listening to my call in your hearts. May peace be with you. Beloved children, always remember the Word, always remember the Mass and the Eucharist, these are the principles of faith. Do not listen to the false peace that is seen in the world. The powerful have already put into action the project of the antichrist. Soon you will see signs from heaven. Jerusalem will be destroyed again, as it was two thousand years ago. Those who do not believe these messages, must remember what happened in the time of Noah, with the universal flood, now history will repeat itself in a greater way. Always be ready. I am near to protect you. Now I bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 13)), "Brothers, I am beside you ... My priests have bowed their heads to Satan and this is what they are doing to me (Jesus shows a torn chest), embrace and love my cross. thank you for consoling me. I bless you all in my name, in the name of my Father and the Holy Spirit, Amen. At 10:00 p.m. 2nd message of Jesus: Brothers, you will hear my strong powerful call, always be united, fight against Satan, I am here with you, I am in your midst, have pity on my cross, do not abandon one another, always be united in my name, my mother will come with me to welcome you into the new paradise, from tonight everything will begin, I only want to love you, my cry of love will not stop here, I will go further in love, love one another as I love you. My brothers I am always here, next to you, I will follow your minds, your hearts, I just want you to allow it. I love you, I bless all of you present, on your families will descend blessings every day, let me into your hearts. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 16)), "Dear children, thank you for listening to my call in your hearts. My beloved ones, pray, pray, always be ready in spirit, the warning is getting closer and closer. I, your Mother, am present on earth to implore you to redeem yourselves urgently, the sacraments, the Holy Mass and the Most Holy Trinity must be your greatest loves. I weep for what awaits you and feel great sorrow when I listen to the hearts of my children who do not feel love either for my Son or for their brother. Great is the love of the Father for His children, accept this love and rejoice. Now, together with the Most Holy Trinity, I bless you in the name of the Father and of the Son and of the Holy Spirit. Our Lady blessed all the sacred objects including those worn." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 18)), "Beloved children, thank you for being here, behold, my stirring of love has been accepted in your hearts. This is what I desire now, you have understood that you must stay united in prayer groups, intensify the rosary, this year will be really in need of prayer, given what I see. You must tell the priests to continue with the sacraments, many of them will no longer obey what is not from God, be on the alert and use discernment from what is from heaven and not. You have comforted me and made my heart rejoice. Thank you my jewels. I now bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 20)), "Beloved children, thank you for being gathered here in prayer. My little ones, remember that our Lord is Love, whoever sows evil does not come from God. God is love towards His brother, love towards the weakest, love is the only way that leads to the light, do not behave like the Pharisees. Dear beloved children, my messengers, thank you for sacrificing your life for me, for being willing every day to criticize, know that you will be the first to be elevated and embraced by me and my Son Jesus. Pray for Europe. I now bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 23)), "Beloved children, thank you for listening to my call in your hearts. My beloved ones, the Antichrist who will be presented will take the world into his hands and will be supported by the powerful, he will make his way into the Church and into people's lives. Be careful My loves, acclaim only your Jesus, who is Love and Life. I bless you one by one, that you may bring Peace into your homes. I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 25)), "Beloved children, thank you for having listened to the call in your hearts. Dear children, the devil wants to take your hearts, always stay close to the Eucharist and to confession, know how to recognize good from evil. I will support you in all the trials you will have to endure in this year. I will be close to you, because humanity is facing the abyss. This evening graces will descend upon you. I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 27)), "Beloved children, thank you for being gathered here, pray children, pray so much, as I predicted, now in some churches my Son has disappeared, the Eucharist no longer has any value, this modernity is spreading, do not follow these false extravagances, they do not come from God. The arrival of Jesus is imminent, just as imminent will be signs from Heaven. Love one another and always be in Grace. I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 28)), "Brothers, be careful because iniquity is going through the world. They will make you believe what does not exist so that I am no longer present in this world. I do not force you to love Me, I do not force you to trust Me ... but why do you not trust Me with everything! When you are in Me, you must rest assured, do not believe unrighteous men. My Father, soon He will eliminate His enemies, the many enemies of God. The cold war has begun and before it is too late repent while there is still time. The devil is attacking you, he is attacking you every day, but I will be here with you. Stay in grace, I will never leave you alone, entrust everything to me. I bless you in the name of the Most Holy Trinity, in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 30)), "Dear children, thank you for being gathered here. Where are my beloved children? My beloved ones, you must be united in prayer, the war is at its next step and America has lost all closeness to God and will suffer much because of this. Europe will also be attacked in every sense. My invitation is to watch the signs that will come from heaven, through which you will understand many things! Everything that belongs to the devil will be destroyed. You must tell priests to stay connected to the true Magisterium of the Church because the devil will try to brainwash them by making them approach rituals that are exclusively satanic. My little ones pray, pray, pray, I will be beside you every time you invoke my name. I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 1)), "Beloved children, thank you for listening to my call in your hearts. Dear children, this is the time of your courage, entrust everything to my Jesus. It will be a difficult journey, where you will be mocked and many will turn away, the angels of hell are on earth to catch you with cunning, be careful. This is the time when the Lord will give you many gifts, especially that of discernment, be calm, I will be with you, I will take you by the hand, be united to the Holy Rosary every day, so that the demons may be weakened. I bless you in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 3)), "Dear children, thank you for having responded to my call in your hearts. My beloved children, how difficult is the way that leads to light and sanctification, but I give you the strength to go forward. Do not stop before the obstacles that there will be on this path that leads to Jesus. I tell priests to follow their hearts and to beware of the pitfalls wherever they come. My dear children, soon the cross will appear in the sky and it will be before the warning. Have peace in your hearts and take it into your homes. I now bless you in the name of the Father of the Son and of the Most Holy Trinity. Amen Our Lady then said: Today, many graces will descend on my children. During the apparition, I saw the blue cross turn red-hot." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 3) & (dataset["author"] == "Jesus Christ")), "My brothers, pray, pray so much, I am on my way to you, have mercy on me, my body is desecrated by those who say they love me and do not listen to their voices, it is a continuous uproar inside the churches. Those who say they love me and speak in my name and profane the Eucharist will burn in the fire of hell. Beware My children, beware!!! The new church will rise, you are part of my people, I love you, be united always in prayer. Now I bless you in the name of My Father, in My Name and in the Holy Spirit. Be patient with everyone, it will be the great virtue. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 13)), "My beloved children, thank you for listening to my call in your heart. Today, I am among you once again to shout my love for you and to ask you to follow my Son Jesus, please do not forget the reason for His death, all His sufferings, for your salvation and for the redemption of mankind. The evil one is unleashed in your families, but take the rosary in hand, it is the only anchor of salvation you have. This call of mine is urgent, soon you will hear the sound of the last trumpet before the coming of Jesus, remember children, that He does not come to unite but to separate. My beloved ones, pray for this sinful Italy and for Japan, where the earth will soon tremble. I now bless you in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 17)), "Beloved children, thank you for listening to my call in your heart. Blessed children, a part of humanity has a petrified heart because it does not have true faith, it does not listen to the word and does not pray with the heart, but only out of hypocrisy. In this beginning of Lent, remember why Jesus died, contemplate His cross, thinking of forgiveness, this must be your Easter. Listen to my appeals, convert, love Him who died for your salvation. The worst times will come and when the most terrible earthquakes will break out, remember it will be a sign that Jesus is coming, this event will be anticipated by the three days of darkness. Now I bless you in the name of the Father, the Son and the Holy Spirit. (During Our Lady's apparition I saw Jesus blessing all those present )." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 27)), "Dear brothers, how much joy your prayers give me, they succeed in soothing my wounds that still today burn and bleed. Open your hearts, pray a lot, and I will accompany you hand in hand and all your obstacles I will help you to overcome. I love you and I beg you do not lose faith and do not get confused, soon, everything will be clearer in your eyes and finally the happiness you will feel will be unimaginable. I now bless you in the name of the Holy Trinity." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Beloved children, thank you for being gathered here again today. How much faith I feel in your hearts and in your prayers. Never be afraid, go to prayer meetings, witness your faith everywhere, evangelize the world, beginning with your families. My little flowers, thank you for always being attentive to my requests and suggestions, today Jesus is here with me and in spite of His sufferings He loves you and is ready to forgive all your sins because He is merciful, but I beg you my children, sincerely confess especially your mortal sins, do not wait any longer. Beloved children, you are now passing through the narrowest path that will lead you to glory. Pray for Japan. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8)), "Beloved children, lighted torches, thank you for being gathered here in this domestic church. My beloved ones, at last I feel your hearts beating for the great Faith. The hard times are before your eyes, please continue to pray so much. I desire that these prayer circles be held more often in your homes where I am and will always be present. My loves, make yourselves ready and purified to welcome us. Go out into the world to evangelize, do not stand idly by, there is no more time. The grace and blessings of my Son will descend upon you today. Pray for Italy, Spain, France and England. I leave you now in peace. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8) & (dataset["author"] == "Jesus Christ")), "Brethren, thank you for being gathered here in this blessed home, I am here among you to leave you peace. Today I am very sad, so sad, I am praying to My Father that His justice will not be worse than the flood or worse than what happened in the days of Noah. My Father does not want to listen to me anymore, you have done too much harm. Brothers, how I love you! I want your salvation, that is why I will give you my love, love me as I love you, you did not welcome me the first time when I was born and you do not want to welcome me today for my second coming. Oh! Children, stay with me, do not be afraid, spread my word, stay close to the Gospel and the Eucharist. Stay united, please stay united. In the name of the Most Holy Trinity, I bless you in my name, in my Father and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 10)), "Beloved children, thank you for listening to my call in your hearts. Dear children, I have come here not to put fear in you, but to assist you and your soul. After so many years of apparitions, you still do not believe my messages; not everyone realizes the great Grace that my Father has given you. My beloved ones, the demons are all on earth and you will never imagine how much place has been made in hell for all the souls who will fall into sin, there is an immense chasm. Please, open your eyes and do not listen to the false peace, for the powerful are planning a great war. Pray, pray, pray. Now I give you my motherly blessing in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 13)), "Beloved children, thank you for having responded to my call in your hearts. Dear children, remember that my Son, when He gathered His apostles, did not call the doctors of the Church, but simple and righteous people of heart. Enough with the pretense of putting doubts in the heads of the brothers, the devil is playing with your minds and hearts. Remember children, you will all stand before God's justice. Pray, pray, pray much, listen to the winds of war. Now I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 24)), "Dear children, thank you for listening to my call in your hearts. Dear children, as I feel the great faith in your hearts, so also do I feel the great frost of hearts that do not flinch before me. Arrogance and pride do not come from God. This period you will feel the quiet, but soon everything will precipitate. This Easter, there will be many signs that will anticipate the end of time. I would like to raise you up to me and for this I ask you to pray a lot. I am your Mother, now I bless you in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 27)), "My children, do not be cruel to Me, I love you, stay united in peace, in the Word and in the Gospel. Enough, continue to love Me, surrender to your King, I am everything, love, the beginning and the end. Why do you want to abandon Me, love My wounds, My Cross. Now I bless you in the name of the Father of the Son and of the Holy Spirit, thank you for accepting Me, thank you My children." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 31)), "My beloved, children of my heart, time is drawing to a close. I turn to the priests, be solicitous to receive as many souls as possible, so that they may take the way of holiness. This is a period of purification, so that you may be ready for the coming of Jesus. My children, do not be afraid to fight heresy; Satan, believing he has won, is celebrating for all the souls he has managed to attract to himself. Pray, pray, pray for peace. I bless you in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 3)), "My beloved, children of my heart, time is drawing to a close. I turn to the priests, be solicitous to receive as many souls as possible, so that they may take the way of holiness. This is a period of purification, so that you may be ready for the coming of Jesus. My children, do not be afraid to fight heresy; Satan, believing he has won, is celebrating for all the souls he has managed to attract to himself. Pray, pray, pray for peace. I bless you in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 7)), "Beloved children, thank you for being here united in prayer. Dear children, how much suffering there is in your heart, but this is the way to reach Jesus. He always takes you by the hand, especially when He looks at your suffering. My Son and I suffer and feel your pain, do not fear my children, you are not alone, I only ask you to entrust yourselves completely to us, remember that you are in the world, but you are not of the world. I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 14)), "Beloved children, thank you for listening to my call in your hearts. Beloved children, what sorrow causes me so much suffering, especially that of your families. Now, the war that has just begun, will have consequences all over the world, but why does man persist in indifference and not yet understand that the only salvation is that of prayer! My little ones, always be ready at night, what has been foretold is coming, the rapture will happen soon. Now, we need the best souls, so that they can join the army of salvation. I love you my children, I leave you now with my motherly blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 17)), "Beloved children, thank you for being gathered here in prayer. Your souls sweeten my sufferings and your faith eases the pains of my Son. Beloved children, the church will remain as it has always been, the devil who thinks he can be the master will be cast out, only because souls have allowed themselves to be taken by pride and arrogance. Nothing can be changed, because the truth is one, before, now and always. Be strong in faith and attached to the only truth that my Son has left you. Whoever thinks to change everything blasphemes against God. Now, I bless you and all sacred objects, in the name of the Father of the Son of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21)), "Beloved children, thank you for being here in this blessed home. Today is the anniversary of my arrival to my beloved daughter, so that my messages may be heard by as many people as possible. I already knew, that the heart of this daughter and her sweet husband would break down all barriers by spreading my messages of love and peace, because in their hearts there is love and hope. Continue to pray for all those who do not believe and who are far from God, that they may be protected, and I intercede with my Son Jesus and they will be saved. I love you with a love so great that you could not imagine. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21) & (dataset["author"] == "Jesus Christ")), "My brothers, I will always be with you, my grace will descend upon you, have faith and never abandon me. Love me, as I love you; pray, that I may anticipate my return. Please, children, stay united, now I give you my blessing in the name of the Father, in my name and in the name of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 24)), "Dear children, thank you for listening to the call in your hearts. My children, change your lives and convert, not only when you feel pain, but truly open your hearts to God's love. Dear children, the righteous will be persecuted and provoked continually, but I know their hearts and therefore they will be protected from all evil. I will give you all strength, but you approach the Eucharist often, be faithful to the laws of the Lord. Pray for the Vatican, something very serious will happen soon. My blessings will descend upon you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 1)), "Beloved children, thank you for being here in prayer. My little ones, the Church will always remain intact, even if there are blind people leading other blind people, no one will ever be able to touch it, because it will be sustained by the Holy Spirit. Never as today, graces will descend upon you, so that all may look with children's eyes at how good and merciful God is. Dear children, always invoke mercy. Now I give you my holy blessing, in the name of the Father, the Son and the Holy Spirit, Amen. " , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 3)), "Beloved children of my heart, thank you for listening to my call in your hearts. Dear children, begin this month to consecrate yourselves in my immaculate heart, here you will find peace and my protection. My beloved ones, follow my Son Jesus, for He is love, pure love, He does not come only to judge you, but to make new heavens and a new earth, this earth which is now invaded by the sin of war and by the 'I' who is not God. Children, I am still here to follow you and to protect you, recite the rosary, the weapon that stops evil, the one that is spreading in the world. Satan will not win, and I will triumph with my angels. My beloved ones, be faithful to God's laws and always be consistent. Speak to God, as to a father or best friend, do not be afraid, He hears all who call upon Him. Pray for Rome, terrorism will not be long in coming. Now, I give you my Holy Blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 5)), "Beloved children, thank you for your prayers for you and for all those who will make prayer circles and for the rosaries prayed in families, I will be there and I will bless one by one and intercede through my Son for all the graces that you will ask of me at that moment. Dear children, always prepare yourselves, before taking the Eucharist, only after having forgiven everything in your heart. Pray for Chile. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 8)), "Beloved children of my immaculate heart, thank you for listening to my call in your hearts. My daughter, I desire, that you tell the priests not to be afraid, the hours of persecution have come, but you cling to my Son Jesus and continue to evangelize always the truth. Dear children, heaven and earth will soon unite and the pain will disappear, for you will taste Paradise. I love you, for you are my beloved children and my lighted lamps, go forth and witness your faith always. Remember, where there is God, there is love and where there is love, there is mercy. Now, I bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit, may the fire of the Holy Spirit descend upon you. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 12)), "My dear children, thank you for being gathered here in prayer. My beloved ones, how much confusion is in your heads and in your hearts, this is what the devil wants to sow, destruction and confusion, I, on the other hand, desire that you can cling only to the recitation of the Holy Rosary, approach prayer, the Eucharist and confession with love towards my Son Jesus. I am beside you and will always accompany you and take you by the hand. Let me accompany you! Soon, everything will change and you will be able to be in the light and see the true Paradise. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 19)), "Beloved children, thank you for listening to my call in our hearts. How much sadness I see in your hearts, but for so long I have been reminding you that this is a time of purification, surely many will be your sorrows, but do you wonder how much Jesus has suffered for you? My little ones, do not be anxious, soon you will be able to taste the new Paradise, what is written must happen before the return of Jesus. Now I leave you with my motherly blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 22)), "My beloved children, thank you for being gathered here in prayer. I know how much sadness there is in your hearts, I know you one by one and I know your anxieties and weaknesses. Behold, I am here to console you, to guide you and to love you with a motherly love so great that I would like only to see you smile, having my Son Jesus in your hearts. My beloved ones, the return of Jesus is soon, welcome Him, be ready and be found on the way of holiness. The devil is creating the greatest schism the Church has ever felt, but do not lose hope, I will be with you, do not turn back in faith, but continue on your way, today stronger than before. I love you and bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 26)), "Beloved children, thank you for listening to my call in your heart. Beloved daughter, sometimes silence and meditation are needed, I am always with you. My daughter, a day will come when any human being will love my Son, shouting, 'You are our King!!!', but if this does not happen soon, nothing will be granted, because the false penitents will feel only Divine justice. Open your hearts to the love of my Son, for everything is speeding up, be ready. Dear children, soon you will be taken away, protected by my blessed mantle, which is already on earth. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 29)), "My brothers, thank you for listening to the call to prayer of the Holy Rosary. I invite you to reflect. When My Mother asks you to be ready for My Second Coming, you often think, 'But I pray!' Make an examination of conscience. How often do you bring me your joys and sorrows, how often do you thank me for the beautiful things I give you? Do you wonder if you have judged your brothers and sisters unfairly? How many good works have you done in your lives and how many works of mercy? How many souls have you brought to me by snatching them away from the devil? Brothers and sisters, these are the reasons why you will be judged; know that those who blaspheme will never see my face. Be united and pray for Italy, for great will be its suffering, even nature will rebel against man. Now I bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 2)), "Beloved children, thank you for being here, gathered in prayer. Dear children, I, your mother, ask you not to be confused, the Holy Spirit will descend upon you to have discernment, especially in the Church. Ah!! my beloved children, how much persecution and how much pain they create in my heart. Beware children, they will also use my image, raising me up before the faithful to make them believe that everything continues, but sometimes they deceive you, because their behavior outside the Church is far from the Word of God. My beloved ones, I weep for what awaits you, my Son, if He returned in the flesh He would be crucified once again, but only a few will see His Holy Face. Now, I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 3)), "Beloved children, thank you for having responded to my call in your hearts. Some of you needed time, but now you are here under my blessed mantle. Dear beloved children, today is a very special day and I ask you to stay before my Son and His Body, approach the Eucharist often, you will see the Graces descending on you, He will speak to your heart following you, day by day, so that you cannot do without Him, listening to the peace He will leave in your hearts. My beloved children, do not despair, the angels are united with the saints and with those who have ascended to Heaven in holiness to fight this war against the devil. My children, there is no more time, convert and open your hearts to love. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 5)), "Dear daughter, thank you, my motherly heart desires my children to light up the spirit instead of the mind, unite in the name of Jesus and make circles of prayers, I love you all, because you are all my children. My little one, do not be afraid of the purification, for it serves to bring you where there is only peace and harmony, always be faithful to the Gospel and love each other as brothers. Now, I give you my motherly blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 9)), "Dear children, thank you for listening to the call in your hearts. My beloved ones, now the heavens are opening to unite with the earth. Short are the times of waiting and soon you will all see the glory of God. This is why I beg you to implore God's forgiveness. If your yes is sincere, you will surely be forgiven and all God's mercy will descend upon you. Forgive and you will be forgiven. Be ready to look at the signs of heaven, do not be blind and do not stand with your arms crossed doing nothing. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 12)), "Dear children, thank you for being gathered here in prayer. My beloved ones, the devil is very cunning, he binds you to earthly things, to pleasures of every kind. My children, be careful, especially of jealousies and envies, for he tempts your reactions to set you against each other and cause division. My little ones, beware of false peace, earthquakes will follow and nature, especially the sea will rebel. Pray for Russia. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 16)), "Dear children, thank you for being gathered here in prayer. Little children of my heart, pray for conversions, especially of my consecrated children, from the first to the last. Dear children, soon it will be the time of warning; unfortunately, they always look for scientific explanations for the signs of Heaven, but whoever opens his heart with the eyes of the spirit will understand. I, your Mother, am still here, because the Father who is in Heaven wants everyone saved and loves all believers and non-believers, even if there is not much love for Him. Now, I bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 19)), "Dear children, thank you for your prayers and for your faith. My beloved ones, do not be angry, do not be disappointed when they speak ill of you, when you are ridiculed, all this in the name of Jesus. I am not here to put fear in my children, but to warn them of the dangers that lie ahead. Faith and prayers mitigate and slow down events, gather as many souls as you can and lead them to conversion. Pray for Spain and for all those who do not believe. Now, I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 23)), "Chapel of the Sacred Heart My brothers, thank you for your prayers and the recitation of the Holy Rosary, a weapon that drives away evil. My dear brothers, in spite of the continuous presence of my Blessed Mother, in spite of the signs I give you, the graces you receive and in spite of everything, why do many still not open their hearts to my love, my Grace and my Mercy? I want to take everyone to My Paradise, therefore, I am now asking you to confess every sin, especially the serious ones, without ever repeating them, so that I can forgive you. I, your Jesus, give you all My Mercy, be alive in faith and bear witness. Love My Cross, repent and come to Me, I am only waiting for your YES and I will always be beside you in your life. Be ready for the new Pentecost. Now, I bless you in the name of the Father, in my name and in the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 26)), "Beloved children, thank you for responding to my call in your hearts. Dear daughter, unfortunately the time of tribulation and true persecution for you and your brothers has not yet truly arrived. Everything you value is being taken away from you, but you must rejoice, do not be gripped by pain. Soon your Savior will come among you to save you from Satan's cunning. My little ones, look at the signs, soon even the moon will no longer give its light. Pray, pray, pray, do not be afraid, invoke me and I will always protect you. Read the Gospel and announce the arrival of Jesus. Now, I give you my motherly blessing, in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 30)), "Dear brothers, thank you for being gathered in prayer. I am here, here I am among you, I ask you, take my hand and follow me without asking much, without asking questions, remember that this is the true faith. I am the truth, the way and the life. Love me as I love you. Believers and non-believers, I am here for a call for salvation, 'Save yourselves', come back in time, the day will come when you will be together with Me, and I am waiting for your heart, open it, how much love I would like to give you! Always remember to follow the Gospel, be strong in My words and above all, shout the truth without fear, I will always be with you. Now, I bless you, in the name of the Father, in my name and in the name of the Holy Spirit, Amen." , dataset["text_pl"])

dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "My beloved children, thank you for listening to my call in your hearts. My beloved children, thank you for being the Church, I know how much you pray and I know how much you give up for the Lord, but sometimes all this is not enough. Make fasts, feed on the body of my Son, come closer to Confession. All this will be for the salvation of your souls. Dear children, Jesus still suffers because evil is rampant in the world, but His mercy is great, it is immense, but your conversion and that of the world is urgent. The Church of Christ will triumph. Now, I bless you, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 7)), "My beloved children, thank you for listening to my call in your hearts. I know your names one by one, I know your requests and your pains, pray to my Son Jesus and He will intervene for your needs. I am here to give you peace, to give you clarity and to love you. Beloved consecrated children, I know your confusion, but do not flee before the difficulties that Satan puts before you, but go ahead, remember your Bride and remember to always be shepherds who gather the lost sheep, put order in your heart and do not get confused. Call upon me and the name of my Son and we will be there to protect you. Pray for America, that, she may return to love Jesus. Now, I give you my Holy Blessing, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 10)), "Dear daughter, thank you for still being here waiting for my message of salvation, thank you to those who have answered my call in their hearts. My beloved ones, soon you will see darkness descend upon you, do not fear, but pray and light the Blessed candles. The Holy Spirit will descend upon you and you will speak through His mouth. Remember that the Crosses and suffering will serve to save souls. Free yourselves from the ego that holds you captive, but be humble and listen to the words of My Apostles. No one has the right to judge and condemn, but only God is allowed everything. Pray for Russia and for Italy, where soon a strong earthquake will shake the earth. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 14)), "Dear children, thank you for having responded to my call in your heart. My beloved ones, every time your heart has an accelerated beat and you feel my fragrance, at that instant, you will understand that I am in your midst. My beloved ones, how much you are loved by My Father! He wants you all to be saved, even the non-believers, when they meet Me, will understand what their place will be. My children, the devil is strong, but you have a great strength which is faith, prayer and the holy rosary. Pray, pray, pray! Now, I give you my Holy motherly blessing in the name of the Father, the Son and the Holy Spirit, Amen. Reflection: Our sweetest Mother exhorts us once again to have faith and to pray. Not a childish, emotional and occasional faith, but an adult and conscious faith. She unceasingly asks for trusting, loving prayer and abandonment to a loving Father who considers us as precious as the apple of His eye and keeps us in His love. Let us pray for the conversion of hearts because He wants His children saved! Mary warns us about the powerful action of the evil one and gives us the key to understand the strength we have that knocks down the enemy: faith and prayer, if we have both, She will make us 'feel' tangibly! Alleluia!" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 17)), "Dear children, thank you for being here in prayer. My beloved little ones, how much love I feel in your hearts! Always be pure like children, but with a strong soldier-like faith. Persecution will be in this world, be strong and do not be afraid. My dear children, soon your consciences will come to light and those who have believed will rejoice, but those who have rejected God's love in their hearts will feel great pain. I love you, pray, pray, pray, for the time is ripe and soon all will be accomplished. Now I bless you in the name of the Father of the Son and of the Holy Spirit, Amen. Reflection Our sweetest Mother rejoices in the love she feels in the hearts of her children and prepares us to have strength and courage for the trials and struggles that God's children must face. Soon everything will be manifested, everything will come to the surface and to the light: our faith and our consciences, but also persecution will become increasingly clear. We are beloved children, but there are those who reject this loving Father and these children will live in their hearts all the pain of the rejection of this infinite Love! Mary invokes our prayers for the time that is now near, but she reassures and strengthens us with Her motherly love and blessing.  Alleluia!" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 21)), "Beloved children, thank you for listening to my call in your hearts. Dear children, you are my burning flames, never extinguish the fire of faith because I need you, I need soldiers on earth, adults who still wonder like children when they feel my presence and that of my Son. How many times do I hear you ask, how much more time do we have? Children, I ask you, be ready, as Jesus said, I will come like a thief in the night, so always be ready, the moments that are approaching are short and they are accelerating. Pray for the Church and for Japan. Now, I bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 24)), "Dear children, thank you for responding to my call in your hearts, do not abandon prayer, always be faithful to Jesus. How much pain I feel in your hearts, offer everything and put your problems at the feet of the cross. My treasures, the battle between good and evil is going on, the devil is cunning, strong and will rejoice for every soul he manages to snatch from God. I beg you my children, do not lay down your weapons of prayer and love out of weariness, you will have the greatest reward, eternal life, do not be afraid the warning is imminent upon you and it will be terrible for those who have rejected God and joyful for those who have recognized Him. I, your mother, love you, I take you by the hand, let me accompany you. Now, I bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 28)), "Dear children, thank you for having responded to my call in your hearts. Beloved children, so sad is my heart for what is to come. How many times have I asked you to look at the signs in the sky, everything that is admired by the world is a great sign. The red of the moon is the blood that Jesus shed for you. Behold children, this is the time of strong earthquakes, the sea and the earth will rebel. Children, free yourselves from the 'I' and come to me, only with Jesus will it be the right and true way. Pray for Italy because the earth will shake very strongly. My beloved ones, I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 31)), "My daughter, all this is only a very small part of what will happen, be soldiers of light, pray for the bishops the consecrated priests and especially for the theologians who are changing the word, giving a different explanation from what Jesus left said. Take the Eucharist while there is still time, everything will be thwarted. How much blood will have to flow in the world, Jesus will come into the world carrying his cross of salvation for humanity. My children, he will protect you with his Precious Blood. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 3)), "My children, thank you for listening to my call in your hearts. My beloved ones, how much pain I hear in your prayers, your hearts are contrite and afflicted by all the evil that is spreading in the world. My loves, they want you to believe that hell does not exist, but it is not so, there would be no forgiveness if there were no sin. So, please, my children, read the Gospel and stand firm in the word. Peace and Peace be still in your hearts, invoke my Son in difficult times, He will hear you and protect you, entrust your sorrows and disappointments to Him, He will turn your life into wonder. Now, I bless you in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 4)), "Beloved brothers, thank you for being here in prayer, I ask you not to let yourselves be led by evil, He is taking advantage of your moments of weakness to take you where the flames burn. I ask you for love and peace with your brothers, forgive and you will be forgiven, I will judge who is with me and who is against me. Beware of the signs from Heaven, I alone am the Way, the Truth and the Life, my Father will soon destroy all wickedness, be ready to be attacked, mocked and persecuted in my name, I will always protect you together with my beloved Mother. Always believe in the One and Triune God. Now, in the name of the Most Holy Trinity, I give you my holy blessing, in the name of the Father, in my name and in the name of the Holy Spirit, Amen. Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 7)), "Dear children, thank you for being here in prayer. My children, heaven rejoices, you do too, now, little is the time that separates us, always keep the blessed lamp lit and the rosary in your hands. Soon, very soon, my Son will be among you, He will come with all His glory. My jewels, do you not see the signs of heaven? The suffocating heat and all that will happen will be for your purification and will be necessary so that you can kneel down when Jesus comes and all will recognize Him as the King of Heaven and Earth. Do not think of earthly things, but enrich yourselves in the spirit, the rest is no longer needed. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 11)), "Beloved children, thank you for having responded to my call in your hearts. My children, I will wipe away your tears and you, with your Holy Rosary, will wipe away part of mine, that is why I continue to ask you for circles of prayer in so many places. My beloved ones, the justice of my Son is already upon you; observe what is happening in the world and in my Church. All the wars, the violence, the earthquakes, should make you understand that God's justice has begun. My beloved ones, continue to feed on the body of my Son, because everything is falling together with the Tabernacle. I am still here and will be for a short time more, to teach you the way that leads to Jesus. Listen to my messages and do not turn your back on those who speak by my mouth. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 15)), "Beloved children, thank you for listening to my call in your hearts. Adored children, come to me so that I may bring you to my Son Jesus. I would like to see you all saved and that is why every time I am here and every time you call upon me, I am beside you. All that is happening is for the great purification of the earth and afterwards you will be reborn to new life with me and with my Jesus. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 18)), "Dear children, thank you for responding to my call in your heart. Jesus is already on His way for His second coming, how much suffering He still feels, they are crucifying Him as they once did. Enough! Too many sins, too many blasphemies, how many mistakes! All that is happening is a very small part of what will happen, I say these words to you so that there may be true conversion in your hearts and I say it especially to my consecrated children, stop crucifying Jesus, justice will be great upon you. My beloved ones, come to me, the seventh seal will soon be opened and you will hear the trumpets of the Angels sounding, be ready in prayer, especially in the recitation of the Holy Rosary and with fasting. Once again, I urge you to love my Son Jesus, so that peace and transformation of your hearts may be immediate. Now, I leave you with my motherly blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 21)), "My children, thank you for your prayers, thank you for being faithful to the Gospel and following my instructions. What disciples do is to carry their cross, Jesus said: whoever does not carry my cross cannot be my disciple. Everything that will happen will be in front of everyone's eyes and everyone will recognize the truthfulness of these messages. You, faithful children, will drink the bitter chalice and your sufferings will be great, but think of the reward together with me and my Jesus. Pray for Italy, for a strong earthquake will shake it. Be humble in suffering, but be strong in faith. This is the time when the trials will be many, even those of ending your mission. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 25)), "Dear children, thank you for listening to my call in your hearts. Pray, pray, pray so much, by now the document regarding the Eucharist has been signed. No longer will people believe in transfiguration, but everything will be accepted as a memorial. Beloved children, everything has changed and will still change in an accelerated way, be ready, only in the Eucharist and in the Word will you find the strength to meet these changes. The See of Peter will soon be destroyed. Pray for the Church, where darkness has taken the place of light, entrust yourselves to my Son Jesus who is love. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 28)), "Oh! Brothers, thank you for being here in prayer, I am here in your midst, but not everyone recognizes My presence. How much I have prayed for you to My Father, but mankind no longer has anything to do with the Faith, I can no longer stop this purification that is now underway, be in Me and My beloved Mother and we will protect you. How much pain in my Church, many are my executioners, the doctors of the church did it once and today they still do it with force, but remember brothers, my Church will never be beaten by evil, but will be reborn victorious. Immerse yourselves in my love, the countdown has begun. Now I give you my blessing, in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 1)), "Dear children, thank you for having responded to my call in your hearts. My beloved ones, always be united in the love of Jesus to defend souls from the devil and lead them towards the light. Beloved children, kneel before the Crucifix with great humility and ask forgiveness for your sins. Return to God, no more lightness of heart, but strengthen yourselves in faith. This is the moment when you will see all that I had revealed. Pray so much for beloved Italy, now she needs many prayers to avoid the worst, unfortunately she has turned away from God. Now, I give you my blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "Beloved children, what joy to my heart to see you here responding to my call in your hearts. Beloved children, tell my consecrated men and women not to walk on the roads of the world, but on the road that leads to my Son Jesus, helping the souls who are getting lost tempted by Satan. My loves pray, as I pray to my Father, that I may still be here with you so that I can guide you to the end. Listen to my messages and my indications for eternal life. By now Satan's hours are numbered but he is much more aggressive because he knows that the second coming of Jesus is imminent. Pray, my Children, so that the purification of the world may serve to regain paradise. Now I place you all under my mantle of grace and I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 8)), "My beloved ones, thank you for being here in prayer. My little children, you give me your hands and I will give you many blessings. I will lead you where everything will be full of love, no wickedness, no injustice, I am your Mother, that is why I have been asking you for the same things for years, I want you all safe and today you will see a sign that will remove all doubt of my presence. I bless you my children, in the name of the Father, the Son and the Holy Spirit, Amen. The sun revolved on itself and became visible to the naked eye with a thousand wonderful colors. Thank you Holy Mary for this gift of yours!" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 11)), "Dear children, thank you for having responded to my call in your hearts. Beloved children, for the hard times that will come, I ask you not to be discouraged, entrust yourselves to Jesus, He will protect you and I together with the angels will never allow evil to touch you. Courageously defend faith and truth, clothe yourselves with God's love and fight. Pray for America because she has turned away from God and the punishment will be harsh. Children return to God and open your hearts. Now, I give you my motherly blessing of the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 15)), "Dear beloved children, thank you for having responded to my call in your hearts. Beloved children, how much pain in my heart for all that is happening in the house of God, but Satan will not win because, little will be the time at his disposal and the Church will be reborn Holy. I ask you, my loves, stay united, be filled with the Holy Spirit and ask for the gift of discernment. Beware of deceptions, this is the time when many wolves disguised as lambs will sneak into the prayer groups to destroy them. Do not listen to the words of those who change the Mass and the misinterpretations they will give to what is written in the Gospel, remember children, the word of Jesus was and will always be one and only one. Children, fight for the truth and I will always be by your side together with my Angels and Archangels. Love the Most Holy Trinity. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 18)), "Beloved children, thank you for responding to my call in your hearts. Dear children, my little ones, everything is changing and everything is being transformed, especially in your consciences. Always ask for help from the Holy Spirit, who, when invoked, will invade you with His peace and only the words of Jesus will come out of your mouth. My children, open your hearts, for soon will be the return of my Son and when He comes, how much faith will He find? Ask yourselves, how courageous and determined are you to speak in the name of Jesus and at what cost do you defend the truth? Do not hide and do not be lukewarm Catholics, but true Christians. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 22)), "Dear brothers, how much joy there is in my heart to see you united in prayer. Brothers, friends, children, look well into your hearts, it is the only thing I need to enter, so open them wide so that my great love can enter. Brothers, I understand temptations, I too have been tempted by Satan, I understand your weaknesses because I too have been a man, I have been rejected, mistreated, mortified and finally Crucified, I fully understand your humanity, but you must be strong. Drive away the devil with the prayer of the Holy Rosary and take the Eucharist often. Love your brothers and especially those who persecute you because of my name; I have forgiven those who crucified me. I have forgiven those who crucified Me. Always be ready, I am coming, remember that I am watching you every day in your prayers and works. I love you all and I bless you in the name of the Most Holy Trinity. I leave you peace! Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 25)), "Dear children, thank you for responding to my call in your hearts. Beloved children, soon you will see great signs from heaven. What are you still waiting for? Is everything that happens not enough for God to call you back to Himself? Surely all that will come will frighten you, but before it is too late, I would like to accompany you on that way that leads to the Light. At this moment on earth there is only aridity, as well as in the hearts of humanity. The earth will rebel more and more strongly, look at these events with your heart and everything will become clearer to you. The devil is creeping in strongly as never before. Jesus is still anticipating the timing of his coming. Pray for America. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 29)), "Beloved children, thank you for being here and for listening to my call in your hearts. Dear children, you see my tears of blood and then continue with indifference in your lives, but do you not understand how great is my pain as I watch many of my children being lost, especially the youth, families and my Church? Instead of reflecting, you turn your backs without any true conversion or sorrow. My children, those who have already ascended into Heaven are preparing to fight the great final battle, while I am preparing My army on earth. Be strong, do not be deceived or put down, for you will have to fight for the truth. Now, I bless you in the name of the Father, and of the Son, and of the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 3)), "Dear children, thank you for having responded to my call in your hearts. Beloved daughter from Heaven, now you must say perfectly what I say to you: Cardinals and Bishops, stop walking with your heads held high, while the Church is in ruins, theologians dear to me, do not venture to change what Jesus left written, His words will live forever because He is the way, the truth and the life, shepherds do not remain anchored in obedience, but fight those who want to add love for Satan, do not intrigue with Freemasonry, but be at the service of the souls of the faithful. My beloved ones, soon my Son will return once again, to free you from your sins. What are you still waiting for to convert, do you still want signs? Instead, I ask you for conversion and prayer, before the fire descends from heaven. Pray for Italy, for America and for Sicily. I love you because you are My children. Today, Graces and Blessings will descend upon you.  Now, I bless you in the name of the Father, and of the Son, and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 6)), "Beloved children, thank you for having responded to my call in your hearts, what a joy to see you here, in so many, gathered in prayer! I am happy because those who have opened their hearts to my Son have seen the wonders of God. Beloved children, never fear, the children of God are already marked and no one will be touched in this time of persecution. Announce the good news, for this world will soon return to peace thanks to the Love that only Jesus the Savior can bring. Be serene, I will always protect you, but be ready with your lamps lit, for everything is falling. Convert, beloved children, the time is over. Now take my blessing and peace into your homes, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 9)), "Beloved children, thank you for being here in prayer and for listening to my call in your hearts. Dear children, always ask, never cease for a moment to ask for the gift of true faith, always invoke the Holy Spirit, that He may mold you, as Jesus wants. Witness your Faith, be courageous. This is a time of Graces that will be bestowed with love and that only a mother can do. You are My warriors of Light on Earth, the terrible things that await you must never frighten you, for we will always be at your side. I bless you now in the name of the Father, the Son and the Holy Spirit, Amen. Sign: 'BE WITNESSES' " , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 13)), "Dear brothers, thank you for being here in prayer. You are My blessed people, I remind you, that in this period you must help My persecuted children, persecution is today more than yesterday. My dear brothers, never be afraid to divulge the messages given by Heaven, they serve to prepare you for all that will happen soon. I will no longer be present in the Church, get ready to gather in your homes to pray, as my mother predicted. Protestantism has begun and my Mother is no longer welcome among the people of the Church, but you brothers who love her and who collect her tears and believe in her great sorrow, let yourselves be taken by the hand to be accompanied towards Holiness. Always love the Most Holy Trinity and I bless you all one by one in the name of the Father in my name and the Holy Spirit, Amen. Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 16)), "My children, thank you for your prayers. I ask my beloved children not to be afraid for the days to come. My beloved ones, the heavens have opened, I desire that all my children remain calm, because my Church will never die. Now, everything will be desecrated, but you follow my true Church, I will always be close to you. My children, do not be afraid, I, your Mother, love you. Now, I give you my holy blessing in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 23)), "Beloved children, thank you for listening to my call in your hearts. My beloved ones, I desire that you always be united because soon there will be a time when you will need each other. My children, soon what I have always said will happen, watch the signs in the sky, the earth will move more and more strongly, the seas will stir more and more and the volcanoes are ready for heavier eruptions. When you are caught, all the demons will be on earth, but do not be afraid, love each other as brothers, the icy night is coming. Children, I ask you for peace, peace is what will make you more and more unique. I love you so much, the world and the church will undergo a great trial, but evil will not prevail. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 27)), "Dear children, thank you for having responded to my call in your hearts. My children, I ask you to always discern, in order to understand those who claim to speak in My Name, there are many who will come forward claiming to be sent by the Father, but they will not be beings of light, but beings of darkness. My children, pray for My Holy Church, for soon you will hear, precisely from those who have denied it until now, that the Apostasy is taking place. My children, pray, pray, pray that you will not suffer during the Warning. Peace My children, peace will descend upon you and your families, Graces will descend today. And now, I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 30)), "Dear beloved children, thank you for having responded to my call in your hearts. My children, I beg you to open your hearts, convert quickly, there is no more time. Pray for the Bishops, Cardinals and Priests, some of them have said yes to darkness and because of this, they will endanger children and young people. I beg you, children, be ready with lighted lamps, never be afraid. I ask you to consecrate yourselves and your families to my Immaculate Heart and to the Heart of Jesus, this will be your protection and let yourselves be anointed with His Precious Blood. Now, I give you my motherly blessing, in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 3)), "My beloved children, thank you for having listened to my call in your hearts. Beloved children, I urge you to live in the Church, always be close to the Tabernacle where Jesus is alive and present, feed often on the Eucharist, live my messages and the Holy Rosary every day. The times to come will be very sad, but I ask you never to fear. The salvation of your souls is only love for God and His commandments, listen to the word of God every day and remember my children that all religions together do not lead to any salvation, but only to great confusion and heresy, the word of God is One and will be so forever. Now, I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 6)), "Dear daughter, you must tell everyone to look at what is happening in the world, everything is now in ruins, floods, landslides, torrential rains, hailstorms, what I said is happening. My beloved, when I ask for a quick conversion, I mean NOW, humanity cannot afford to waste any more time on futile things while true purification is taking place, even the economy of the various countries will be heavily destroyed. My little one, be strong, do not be afraid to speak the truth, only in this way will many understand. The time that separates you from the Savior is short, by now heaven and earth have united, only by returning to God can there be salvation. My blessing descends upon you and upon your house, in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 10)), "Beloved children, thank you for having responded to my call in your hearts. My children, you often wonder what will happen during the Warning, now I will tell you what will happen; everything will stop and you will all be put in a state of ecstasy, during all this you will see the sins committed in life pass away, this will serve to make you aware of the suffering and you will seek and find God. My beloved ones, pray for America because soon something great will hit this nation dear to me and will involve the whole world, so I ask you not to waste time, conversion is important to prepare yourselves for the encounter with Jesus, do it now because you have only known God's love and Mercy, but you hope never to see His justice. Dear children, do not be afraid, whatever happens, remember that I will always be close to you. Now I give you my motherly blessing in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 13)), "Beloved children, thank you for responding to my call in your hearts. My beloved ones, in this period, many will make an examination of conscience because the Holy Spirit will enter into many of my children. What you will feel will be great strength, peace, union among brothers and courage. My little ones, I am close to you and I will always be, you will look for me as a mother, just as children who need their mother, you will feel the desire to be followed by me. Never turn away from the love of God and His word, open your hearts and He will enter like a storm of love and you will understand that nothing is without God, you will have to do everything to bring your brothers to Him and have the certainty of eternal life. Now I bless you, the sick present and the sacred objects you wear, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 17)), "Dear children, thank you for responding to my call in your hearts. My children, pray for my Holy Church, they want to modernize what God has left written. My children, the will of men at this time is not the will of God. My dear little ones, you are My army, be a light for all brothers, that they may open their hearts. Now, I ask you to kneel in prayer so that you may praise God and enjoy His glory. Love the Most Holy Trinity. Soon, a strong earthquake will hit Italy, natural disasters will follow, the stubbornness of the powerful of the world are causing so many innocent deaths. Pray, pray, pray, I ask you to light the blessed candles soon, pray for Russia and America. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 22)), "My dear children, thank you for being here in prayer, this is what I would like to see in families, how much joy you give to my heart! My beloved ones, always be united, you will need each other, confess if you have negative feelings towards other brothers, purify yourselves because the time is near and so you will be ready. The Church will be attacked, solar storms are increasing, threatening technology, so, pray, pray, always be in the presence of my Son. Blessings descend upon you, in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 24)), "Beloved children, thank you for having listened to my call from your heart. My children, I know your difficulties, your anxieties and your life, accept the graces that will fall on you at this time. My children, feed yourselves on the Word of my Son, be good and honest with your neighbor. My dear children, as a mother, I suffer from seeing how many pray and then behave with pride and arrogance, learn from what Jesus said. My children, my Son needs your prayers, but you will need Him more and more. Now, I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 27)), "My beloved children, thank you for being here on your knees in prayer. Beloved children, everyone often asks what will be the day of my Son's arrival, but why do you ask if you do not even recognize the signs of the times? My children, when you pray the Rosary always meditate on it, the prayer of the Rosary without meditations and in haste is not valid. My children, how my immaculate heart bleeds when I see the pastors of the Church in sin! Pray for my priests. Pray for Russia. Now, I give you my motherly blessing, in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 1)), "Dear children, thank you for having responded to my call in your hearts. Pray, pray, pray very much, unfortunately inexplicable things will happen especially in Italy, stop and continue to bring souls to my Son Jesus, He is Love, Way, Truth and Life, why do not you understand! The time has come, convert, do not wait for the last moments, believe what this daughter says because everything is Truth, do not look indifferent to everything that happens around you. Pray for Naples. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 3)), "Dear children, thank you for being here and responding to my call in your heart. My dear children, always nourish yourselves with the Word and with what Jesus left, whoever has the pretension to change it, offends God, His Word is immutable and will be forever. My children, I speak to my priests, I desire that they understand and realize what God has done for them, making them similar to Jesus, giving them the possibility to forgive sins in His Name, to take bread and wine in their hands and at the moment of consecration, transform them into the true body and true blood of my Son, so my children, do not soil your hands with sins, avoid pride and arrogance, but be humble. I ask you to pray for that church which is in the greatest of sins. Pray for central Italy. Now I leave you with my motherly blessing, in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 9)), "Beloved brethren, you, by your prayers, have anticipated My arrival, My return is about to take place, watch the changes in the world around you, the change of your Spirit. Those who draw near will be forever, but those who turn away will have no escape from the justice of My Father. Beloved My brothers, remain united in My love and in that of God and My Most Holy Mother. Do not look at your brothers with impure eyes, but have wisdom. Turn away what seems evil to you and I will give you all my Spirit of discernment. May My Father's blessing always descend upon you and your families. Dear friends, how I love you! Your brother Jesus. I am always here with you, I bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 11)), "My beloved little ones, thank you for having responded to my call in your hearts, but where are the rest of my children! This is the period in which you await the birth of my Son, I ask you not to live this wait like the pagans, with gifts and colored trees and a closed heart, but welcome Him in serenity and peace and above all in your heart. Pray for Italy, so that it may return to God, otherwise the suffering will be great, pray for Russia, pray for my Church, where in a part of it, my Son Jesus is no longer prayed to, they are trying to abolish the dogmas that belong to me, the Apostasy is upon you. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 14)), "Dear blessed children, my little flock, thank you for being here in prayer, your intentions will be heard today. My children, do not be afraid for what is to come, for protection over you is assured, light the blessed candles. During the bad times do not be afraid, because, whoever has had faith, will overcome everything with so much peace in his heart. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 18)), "Dear children, thank you for having responded to my call in your hearts. My children, do not wait any longer, witness the truth and your faith, this is a time of Grace. I desire that my children understand how great is my love for them, therefore, I need your testimonies so that the hearts of the most distant may open and be enlightened. My beloved ones, very bad times will come, especially this new year that is coming. Wait with love, peace, humility, for the Creator. Now, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 25)), "Dear brothers, welcome me into your hearts, soon I will come among you, no one knows the day or the hour. Beware, today, of the many false seers who surround you. I desire that you listen only to the words of My true messengers. The great thunder is coming among you and I will descend, as I have ascended into Heaven, to divide the wicked from the righteous. This will be a special year, where you will all have your blessed signs. Open your hearts and help My brothers to bring the truth. My brothers, always remain united in Peace and Love, for I love you. Now, I give you the Holy Blessing in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 29)), "Dear children, thank you for responding to my call in your hearts. My children, I ask you to pray a lot in this time of struggle between good and evil. My beloved children, I urge you to pray for the whole world, how many catastrophes there will be, the seas will rage devastating the cities, volcanoes will continue to erupt in a catastrophic way. My children, why is it that in spite of all the warnings, many do not listen, believing that they can imitate God in their lives, mistakenly! I am here to ask you again: Return to the Father! Children, how many conversions there have been! But how many still have to return to God! Help your brothers with your testimonies, do not be afraid. My children, through faith, the road you will travel will be the one I will show you to reach the light and only in this way will you be able to have peace and feel love. Now, I give you my Holy Blessing in the name of the Father, of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 31)), "I, your Father, ask you to read the book of John, it says everything that is going to happen, do not pretend you do not know how to read, keep everything aside. Revelation is the book you must read for these new times that will come. Do not be afraid, you are My People, always listen to your Beloved Mother who comes to teach you, catechize you and protect you. Do not be afraid, be ready for battle, My soldiers. The heavens will always protect you. I bless you my children, in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 31)), "" , dataset["text_pl"])
dataset["text"] = dataset["text"].str.replace("Amen\"", "Amen.")
dataset["text_en"] = dataset["text_en"].str.replace("Amen\"", "Amen.")



dataset.to_csv("trevignano2018_cleaned.csv", encoding="utf-8", index=False)




















































