# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np




dataset = pd.read_csv("trevignano2016.csv", encoding="utf-8")


dataset["text"] = dataset["text"].str.replace("Amen\"", "Amen.")
dataset["text_en"] = dataset["text_en"].str.replace("Amen\"", "Amen.")


dataset["text"] = dataset["text"].str.replace("\"", "")
dataset["text"] = dataset["text"].str.replace("AmenLa", "Amen. La")
dataset["text"] = dataset["text"].str.replace("AmenIn", "Amen. In")
dataset["text"] = dataset["text"].str.replace("Santo \. Amen", "Santo, Amen.")
dataset["text"] = dataset["text"].str.replace(" : ", ": ")
dataset["text"] = dataset["text"].str.replace("Spirito santo", "Spirito Santo")
dataset["text"] = dataset["text"].str.replace("Dio Figli", "Dio. Figli")
dataset["text"] = dataset["text"].str.replace("Amen Oggi", "Amen. Oggi")
dataset["text"] = dataset["text"].str.replace("Continua a leggere\. \. \. \»", "")
dataset["text"] = dataset["text"].str.replace("sinistro\.\.", "sinistro.")
dataset["text"] = dataset["text"].str.replace("Amen Il ", "Amen. Il ")





dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21)), "While I was with my husband lying in bed watching TV, I heard a voice calling me. I asked my husband to turn down the volume on the TV and as I turned to the little statue on the dresser, I saw the Madonna wrapped in a white veil and a blue/celeste cloak. In tears I said to my husband: The Madonna! The Madonna! and instinctively we both knelt at the foot of the bed. She smiled and said to me: My daughter, I am the Holy Virgin, don't be afraid, I have chosen you because you are full of love and hope and life must be founded on this. I will send you many people who need to be converted, do not close the doors but open them so that all may see and learn to love my Son Jesus. I will return soon and they too (referring to my family members) will feel my presence with a sign from me. I bless you in the name of the Father, the Son and the Holy Spirit, Amen. At the end of the apparition all my family members in the house heard a ringing of bells. " , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 28)), "My daughter, my heart suffers from injustice, from lack of trust in the signs that God sends you from heaven. Faith is also shown by accepting the Lord with humility and trust. Listen to what God is saying to you and do not resist his call. Meditate! This mother wants to pour out her love for you to prepare your hearts for her Son. Accept my blessing and my protection. I bless you in the name of the Father, the Son and the Holy Spirit, Amen" , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 30)), "My daughter, do not despair, I will follow you. Help others to pray, to come closer to God the Creator. My heart is bleeding because we are close and the Church is very confused and clouded. Remember, that only with prayer will you have eternity. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 2)), "My child, the three days of darkness are coming. It will be a very cold night. Do not be afraid, for whoever believes in my Son will be saved. I insist on asking you to pray the rosary and whoever teaches it to others will have his head girded with pearls of mercy and glory for all the souls he will have saved. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 14)), "My daughter, tell the Bishop not to stop fighting. He must pray for the world, because Satan will not stop taking all the souls that are close to him. Rest assured, your family has my blessing, but you too will have to fight for the prayers that I ask of you and especially for conversions, I will always be beside you. I weep for the wrong decisions that the rulers are making and for the Church, which is in great difficulty; especially the Pope, pray for them so that the choices they make will only be decided by the heart. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 25)), "Dear Children, I recognise your sorrows, pray and I will be close to you. Pray to Jesus and you will be victorious. Pray for those who do not believe. Do not stop, there are many people who need to be redeemed and all your sufferings will not be lost. Do not cease to pray. I bless you in the name of the Father, the Son and the Holy Spirit, Amen. Madonna on this occasion prayed in Aramaic over all those present during the recitation of the Holy Rosary." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 29)), "Dear Children, I thank you and I am very happy because you are gathered here today also. You are my apostles. Do not be tempted by Satan because he is strong, but with prayer you will overcome him. Jesus gives you His blessing, together with me, Your Mother. I bless you in the name of the Father, the Son and the Holy Spirit. During the recitation of the Holy Rosary, Our Lady held the little Jesus in her arms, then at the end, opening her arms, she wrapped us all in her heavenly mantle and gave her blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 1)), "My daughter, I am happy to be here. Conversion is needed because God is in a hurry. Your names are engraved in my Immaculate Heart and each one will have his own reward for having favoured my plans. Do not be afraid. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 11)), "My children, thank you for being here in ever greater numbers. I will touch you one by one, so that you can bring my blessing to the needy and to your families. Love my Son because it is He who sends me to touch the earth. Kneel down and be humble. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 14)), "My children, thank you once again for being here with me. Thank you for having sought me out. Thank you for having welcomed me here in your heart. Love my Son because He is the only truth. You are on the right path; I will give you many graces to give you a sign of my presence. Thank you, my apostles. With your mother's heart you will receive my blessing in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 18)), "Dear Children, I am very happy still today because you have responded in your hearts to my call. I beg you there is no more time, convert and recite the Rosary. Do not resist my call, pray for the priests who are being lost, who are blind and deaf. Tell them to go into homes and onto the streets for the salvation of as many souls as possible. I love you and if only everyone knew how great is my love for you! Jesus forgives you for your sins and I, still with my Son, bless you in the name of the Father, the Son and the Holy Spirit, Amen. Then she added: After France it will be the turn of Rome where there will be a great earthquake. The Vatican will suffer a great pain. Within it at this moment there are Cardinals and Bishops who will be forced to choose the way of evil, turning away from the only truth that leads to the Father. Listen to the winds of war. Russia is preparing. Pestilence, misery and smallpox will fall on Rome, bringing death and despair. At the end of this message, Our Lady points to the sun, and I notice that it has turned on itself several times.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 21)), "Dear children, thank you for being here and thank you to those who have accepted my call today. Remember that only the truth will make you free. Recite the Our Father with me three times. Pray for the priests, for the Pope, for the bishops and cardinals, that my light may touch their hearts. I will give signs of my presence to those who do not believe. Thank you my apostles, I bless you in the name of the Father, the Son and the Holy Spirit, Amen. On this occasion Our Lady added: ...pray for the Pope, for his pontificate will be brief. During the three days of darkness take blessed candles; those who keep them lit will not be touched by demons. My daughter, help me for the conversion of my children; I know that you and your husband are the ones I want by my side for my requests and I know that you will accomplish the task I have entrusted to you. Thank you, my children, your Mother.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 25)), "My children, thank you for being here still today. Allow the luminous rays of my Son to enter your hearts. I say and I keep repeating: be humble, not only during prayer, but every day. When you pray, there is no need to name one by one the people you have at heart, because I know your needs, one by one and the names of the people dear to you. I thank you and together with Jesus, I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 28)), "Dear children, dear children...thank you for still being here, so many also today...I am very happy. Some people ask why my apparitions take place during the Rosary. The answer is simple, because I am the Queen of the Rosary. My daughter, you and your husband must be the example for all couples, that is why I have chosen you, for the great Love and the great Peace that you have in your hearts; because unfortunately the devil has crept into families and destroyed them. The strength of the Rosary is the winning and powerful weapon. My Children, pray for the Pope, for he is forced to make decisions which do not come from his heart. Please, intensify the Rosaries because times are very tight. There is no more time. Thank you my apostles. I bless you in the name of the Father, the Son and the Holy Spirit, Amen. On this occasion the picture of the Divine Mercy oozed abundantly in front of all those present, arousing amazement and devotion. A very strong testimony to the attention of all present.", dataset["text_en"])



dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 2)), "Dear Children, thank you for having responded to your Mother's call. I am here because Jesus sent me. Do not be afraid; my messages are not defeatist. I want you to believe in the one God and to embrace the cross of my Son. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 5)), "Thank you, my children, for having responded to my call in your hearts. Today there are many new people. I will dry your tears and will not allow Satan to attack you. Pray the Holy Rosary. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 9)), "Thank you my children, today young people are here in this blessed house. I love you all. I bless you in the name of the Father, the Son and the Holy Spirit, Amen. On this occasion, during the apparition, Our Lady asked Gisella to give her caress to all those present.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 12)), "Dear children, I am very happy because there are so many of you also today...but today I am also a little sad, because some of you have a hard heart, I have given you many graces but you continue not to comprehend my presence. I take you by the hand, but you continue to err, do not let yourselves be touched by the snares. Take the Eucharist because my Son is there. Then, praying over all those present, she said: Take my blessing to your families, I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 16)), "Dear Children, thank you for having responded to my call in your hearts. Today I ask you for peace and love for your brothers and for those in need. I ask you to love yourselves, as my Son did with His brothers. My Son is very near and you will see Him descend from a great white cloud. I beg you, my children, hold on to the Rosary which is the only weapon to defend oneself from evil. For every Hail Mary said with the heart, I will give a Grace! I bless you in the name of the Father, the Son and the Holy Spirit, Amen. On this occasion the Queen of the Rosary asked for the messages received so far to be spread so that all people can meditate on them.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 23)), "Dear children, I thank you again for the new people, for the call that you have heard in your hearts. The Lord gives you grace, the gift of wisdom, of hope, of knowledge, but you must listen to the message of Jesus, you must open your hearts. I weep for the hard times that are waiting for you, have courage, I am close to you and I will always be to protect you from all evil. Do not be far from me, for I love you and I desire so much that the greatest desire is to bring you into my Kingdom, into my new world on this earth. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 26)), "Dear Children, I thank you for having once again accepted my call in your hearts...it is addressed above all to the new people who have made a great effort to come to Gisella's house; some did not even want to be there, but She once again insisted by blowing into their hearts. Our Lady asked us to cling once again to the Holy Rosary and to prayer, because it is the only powerful and strong weapon to defeat Satan who is always on the hunt for souls, and she added: Jesus is praying to His Father, that He may free us as soon as possible and that nothing may happen, and that the Earth may be purified only through prayer and love. But even this becomes difficult because God is tired...God is tired! Our Lady also added that a great World War is being prepared and that we must remain calm and must pray a lot because She is here to protect us and not to frighten us. Those who love her Son and who pray the Rosary will be saved. She asked us never to stop, and finally she blessed all the Rosaries of those present. She blessed all of us, in the name of the Father, the Son and the Holy Spirit.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 30)), "Dear Children, thank you for having responded to my call in your hearts and for being gathered here in this blessed house. Open your hearts so that the Holy Spirit may infuse Peace upon you. Pray always so that with your prayers, you may alleviate your sorrows and those of the other faithful for the days of tribulation that await you. The Earth is about to tremble, Brazil will soon drink from the bitter chalice. I will be at your side and I will take you by the hand one by one, continue to recite the Rosary because it is the strongest and most powerful weapon. In this apparition, under Our Lady's feet, one could see the world, enveloped in blood and so many people crying out to the Lord for help; but the Queen of the Rosary says: ...for those who have not had faith it will be useless, at the last moment, to invoke the Lord, because they will not be saved! At the end of this apparition, the rays of light around the figure of Mary touched all the sick people present and She blessed everyone in the name of the Father of the Son of the Holy Spirit.", dataset["text_en"])



dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 2)), "Dear Children, thank you for being here, thank you for responding to my call in your heart. The angels are waiting for my command to come down and pick you up without your realizing it, you will find yourselves on a new earth and you will see great wonders. I insist on asking you to pray the Rosary; I myself will come down with the angels to hold your hands. The Blessed Virgin was filled with rays of light, she showered the Blessing on all those present like a shower of bright and colourful confetti, then she blessed everyone in the name of the Father in the Son and the Holy Spirit. Today Our Lady was also very happy for the presence of the Bishop and for the new young people who came for the first time, and she said: the paths that I trace out for you cannot be diverted. I have breathed into the hearts of many people and I thank you for having listened to my call in your hearts. I ask you to pray for Chile and America. Today at last I have my Son among us. Scientists are gagged by the powerful . She asks us to go forward and to pray the Holy Rosary. Then she prayed a Hail Mary with us and blessed us in the Name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 13)), "Today Our Lady was dressed in white with a crown of stars and said: My dear Apostles, thank you for being gathered here and for having heard my call in your hearts. Many of you come to seek faith, but open your hearts and there you will find the answers. Today my Son is in your midst, then He opened His arms and spread His mantle as if to protect us and blessed all those present in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 15)), "My family and I were invited to a friend's house. We had arrived at dinnertime to celebrate the Feast of the Assumption, and as we were talking at the table, I felt the presence of the Blessed Mother, and as I raised my eyes to heaven, she appeared dressed in white with a luminous crown and blue mantle with a red heart in her hand. She radiated a great light. Our Lady said: Dear children, I pray for the reconciliation of your families and I pray for graces before the Most Holy Trinity. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 16)), "Dear Children, I am very happy because you are numerous and because you have responded to the call in your heart. Shortly my Son will reveal the third seal (in the vision that Our Lady gave me I saw a knight dressed in black with a sword and a black horse sowing famine, death and despair). The only weapon you will have will be prayer and the Holy Rosary, stock up on canned food and drinking water because the demons will try to take everything away from you. My Son is marking His disciples so that no one can be approached by demons. Trust in him; I will always protect you. I bless you in the name of the Father, the Son and the Holy Spirit. During the apparition Our Lady caressed each one of those present.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 23)), "Also today Our Lady is in our midst and she said : I know that your brothers are here to ask for graces and to ask for conversions, I hope that the fire of the Holy Spirit can invade your body and your heart, I love you like a mother, I love you like your mother, because I am your mother, therefore I beg you to love my Son as He loves you, He asks for forgiveness, He asks you to forgive and to know how to ask forgiveness of others just as God has forgiven so many of you. Our Lady then says: Pray for France because it will face yet another great sorrow, pray for Italy especially for Rome because the forecasts are not good, pray for Chile, the earth will tremble again and volcanoes will begin to erupt one after the other in all parts of the world. I insist on asking you to pray, to convert before it is too late. I thank the Anointed One to GOD who finally opened his heart, and that was what I wanted. Unfortunately, there is not much time for any of us and therefore I truly ask you to open your hearts towards Jesus, come closer to my Son, love Him and give Him all your sufferings, embrace your cross and He will change it into joy, do not wait until the last moment to do so. Be my Apostles, do not go in search of signs but of prayers with an open heart and I will listen to you, just as I also intercede every day before my Son. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 30)), "Dear Children Thank you for being gathered here in the Father's house, you are about to experience something very great, the end of time has begun. Listen to the earthquakes in the world, this is the shaking of your consciences. My Son is asking for your sincere yes, do not be hypocrites, I am here once again to ask you to come closer to Him. Whoever believes in the one God will be sanctified, but whoever turns away will be accursed. Thank you, my beloved children, I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])




dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "Dear daughter, this is the hour of your tribulation and every time I appear I will give great graces. Let the Holy Spirit of my Son infuse you so that hatred, anguish and fear do not touch you when Satan gives you pain just because you all pray to my Son. I love you and He is giving you a beautiful Grace, do not be blind. I beg you, my children, let Him mark you so that we may all be together in the new land that He has prepared for you. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 6)), "Dear Children, thank you for having heard my call in your hearts. Thank you for being gathered here and how much faith I feel in my children today. Today I am leaving you with a mission, pray for the souls who must convert so that they may be worthy of the New Land of my Son. My daughter, recite a Hail Mary and also today many graces will descend. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 10)), "Dear children! Thank you for having accepted my call in your hearts, bend your knees in prayer and be humble. You are my little children and I love you, remember that I am the Queen of the Church, of that Church which is being lost, pray for the priests so that they do not lose themselves in the hypocrisy of prayer. My children, open your hearts and convert; I will always be at your side, protecting you. I bless you in the name of the Father, the Son and the Holy Spirit.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 16)), "Dear Children, thank you for always being gathered here with me; the secrets of Fatima are on everyone's lips, yet there is total indifference towards my messages. Help people to convert, there is not much time, and yet the wars that are in the world should make everyone understand everything and instead many believe that everything will work out and go on as if nothing were happening. Listen to the rain of the Father's wrath that is approaching. Do not think that the Vatican is doing good things for humanity, it is all false. Many men of the Church are false, the few holy priests will be persecuted as well as the people of God. My daughter, do not trust and follow in detail only what I ask of you. Thank you, my children, for your daily yes; I will be beside you to console and protect you. I love you because you are My children and that is why I chose you, your mission must not be hindered, I will be with you in struggle and tribulation. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 17)), "Dear children, thank you for being gathered here in this blessed house. My daughter, why are you turning away from me because you are not renewing your yes to the Lord, do not let yourself be tempted, faith is courage and only with serenity will you be able to cleanse your spirit and not turn Jesus and me away from your life, you have my protection and you have a mission that you must carry out with love. Thank you, my daughter. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 19)), "Dear children, thank you for having responded to my call in your hearts, I am very happy to see you gathered, you are my little ones and I love you all, I bless this small part of the Church. My children, embrace Jesus in your heart together with His cross, if you only knew how great is my love for you. Pray for conversions there is no more time, the solar storms have begun and an asteroid is fast approaching the earth for a great impact, but do not be afraid you will be infused with the Holy Spirit and so will God's people. Pray for Japan and Chile where the earth will soon tremble. Take my blessing to your families and I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 22)), "Dear children, thank you for coming here to this blessed house.You are a small part of the church, My children we are here, the days of warning have come, soon you will see my son coming from heaven on a cloud and a loud roar will shake the earth.  He will come to gather all of God's children together and forgive you of all your sins. A great sign will be a cross visible all over the world, do not be afraid, I will be with you and I will take you by the hand but you must embrace the Heart of Jesus and His Cross. Our Lady asks us to recite the Our Father together with her. Our Lady adds: do not cover the signs that Jesus leaves you, let everyone see the love of my Son's passion Dear children, whoever will speak in my name and in the name of Jesus will have my blessing. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 26)), "Dear children, thank you for having accepted my call in your hearts, I am happy to see you gathered here. I protect you and I take you by the hand, remember that envy, jealousy and pride are feelings that belong to evil, love one another and unite in prayer and be compassionate towards one another. My children, pray for Mexico where the volcano has awakened, pray for Italy because the earth will tremble and pray because a world war is imminent. Dear Children, I give you my blessing and take it also to your families in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 27)), "Dear children, how much hypocrisy and coldness I feel in prayer, this is the hour when the evil one is taking possession of my Son's Church. I command you, my daughter, to help me spread prayer and save as many souls as possible. The moment of the choice that will change the world has arrived; there is no more time. Say a prayer for the priests who are being lost and for those who are far from God. Thank you, my beloved daughter. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 29)), "Dear Children, thank you for being gathered here and thank you for responding to my call. Pray for the priests who are in great confusion and this will lead them to perdition. The new earth is ready, full of lilies and flowers and is waiting for you. Stay close to my Son and love him, he alone is truth, love and salvation. Beloved children, the Church will soon make great news, pray for Italy where there will be a strong earthquake, pray for Colombia where the forces of evil are awakening. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])


dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 1)), "Dear Children, what happiness in my heart to see all of you gathered here in prayer. Thank you for your testimonies of faith, go forward with courage, I am and will always be with you, prepare your hearts for my Son Jesus. Then she added: due to strong eruptions of a volcano, the earth will tremble again.Beware of the agreements that will be signed by the Church, they do not come from God. Beloved children I bless you in the name of the Father, the Son and the Holy Spirit, Amen. Take my blessing to your families.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 4)), "Dear Children, thank you for being gathered here in prayer. Many ask how all this is possible and I answer you that if you reasoned with the mind of the spirit and not with the mind of the head, you would be able to see beyond and you would realize that even the inexplicable would be possible. My children, open your hearts and let yourselves be carried away by the love of my Son. May my blessing descend upon you and your families. Pray for Canada where the forces of evil are preparing and pray for Central America where there will be a strong earthquake.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 8)), "Dear Children, thank you for having listened to my call, especially the new people who have come here. My children, look at the fire of the Holy Spirit appearing before your eyes, pray, pray, pray. The evil one is about to take the throne in the church instead of my Son and soon the Eucharist will disappear. Jesus will return and all will see Him. Pray for Chile where the earth will tremble with vigour and pray for Japan and America where the scourge will continue for purification. My Children, I bless you in the name of the Father, the Son and the Holy Spirit.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 10)), "Dear Children, thank you for having listened to my call in your hearts, I am very happy that new people have joined here to pray my Holy Rosary. My children, do not be tempted by Satan, he is always lurking, especially if you are weak, so pray, pray, pray always and be ready when my Son calls you one by one. Open your hearts to his infinite love, nourish yourselves with the body of my Son. Pray so that a disease for which there is no cure may be eradicated. In the name of the Most Holy Trinity, my children, I bless you in the name of the Father, the Son and the Holy Spirit. ", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 11)), "Today only Jesus appeared, dressed in a white tunic and a burgundy-coloured cloak. In a warm and gentle voice he turned to my husband and me and said: Dear sister and brother, you know that I am the only Truth, I trust you. I ask you for obedience only to me and to my Father. I am sending you my mother to comfort you, to give you strength and courage to go on...listen to her messages. Then he turned to all those present and said: My brothers, I will pass among you and I will touch you one by one. The Holy Spirit and my holy blessing will come upon you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 15)), "Beloved children, the evil of Jesus' enemy is devouring all those who have turned away; convert, we are at the end. My children, I will protect you and hold you close to my immaculate heart; you will be put to sleep and will be transported to true life where you will find true love. The cross that you choose will be blessed from heaven; I will appear every 3rd of the month at 3 p.m. so that the crowds of pilgrims may convert. Pray for Japan and Italy where there will be a strong earthquake. I love you, my children, and I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 25)), "Dear children, thank you for being gathered here; man, who has sin within, is afraid to recite the rosary and flees before its power. My children, be humble and live these times with the spirit, do not be attached to material things, feed on the Eucharist and mercy. My daughter, I will send you righteous priests who will know how to read the events and my messages, do not worry I will follow you. Pray for Mexico and Chile where the earth, the sea and the volcanoes will shake. I bless you in the name of the Father, the Son and the Holy Spirit, Amen. Today 7 crosses appeared on my left arm.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 29)), "Dear beloved children, thank you for having responded to my call, tonight there will be many conversions, thanks to the infusion of the Holy Spirit of my Son. Trust in Him and He will transform your sufferings into joy; entrust yourselves to His immense love and do not despair in difficulties. Dear children, soon Rome will collapse, there will be a strong earthquake and the altar of the homeland will be the first to be destroyed, unite in prayer for the church because it is in the hands of the devil. I protect you and I embrace you, do not be afraid, I am with you with all my motherly love, pray for Australia. I bless you in the name of the Father, the Son and the Holy Spirit, Amen. Today at 6:30 p.m. before the recitation of the Holy Rosary an inscription appeared on my left arm: I AM WHO I AM.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 30)), "Dear children, the angel of love looks at you with tenderness, you are much loved by heaven, do not be tied to the ego and to material things, the most important thing at this time is the spirit and it is the only thing that interests you. Jesus appeared together with our Mother saying: Dear brothers, I am with you in you and for you I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])


dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 1)), "Dear children, the tribulations and obstacles due to the approach of the first public apparition are making themselves felt, but I am with you, so go forward with courage and with my protection. Dear children, bear witness to the faith, bear witness with courage, thank you. May my blessing descend upon you in the name of the Father, the Son and the Holy Spirit, Amen. Today at 5:30 p.m. the letter 'M' appeared on the wrist of my left arm. Our Mother's presence is constant, she never abandons us, we are all called in this mission and we will be Victorious.", dataset["text_en"])

dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 3)), "Dear children, thank you for having responded to my call in your hearts, today I am leaving you a message of warning addressed to my consecrated children and apostles, God will raise his just arm for those who lightly condone abortion, a practice which underlines a mortal sin equal to one who kills his brother. Pray with me an Our Father so that God may enter your hearts. Love my Son and repent with the heart He still anticipates His coming, remember that God is merciful, but also just. Pray for the Church, soon its announcement will be resounding and against the divine laws. I am here not to announce catastrophes, but to protect you from the evil that has taken hold on the earth. Another war is being prepared. But you be faithful to my Son to the 10 commandments and recite the Rosary fervently. Pray for Peru because there will be a strong earthquake. Beloved children, I love you all and I give you my blessing in the name of the Father, the Son and the Holy Spirit, Amen. ", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 6)), "Beloved brothers, today I am in your midst to pour the Holy Spirit into you, so that you may have the strength and courage to go forward. My sister, take the hands of your spouse for a special blessing. I understand your weariness caused by all the attacks from those who do not believe in me, from those who are afraid of the messages that my beloved Mother leaves and from those who do not believe in prophecies. But I am with you in love and in suffering, to help you and to show you the way. Many would like to block the way that leads to me, but be strong and determined, my love will protect you. Whenever you speak of me, it is not you who will speak, but it is my Spirit who will speak in you. I bless you all in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 8)), "Dear Children, thank you for being here with me. Thank you also to those who arrived in disbelief, but my call to your heart was stronger. Beloved apostles, everything is ready! I cannot wait to come to you to take you with me and hold you to my immaculate heart. Continue to feed on the body of my Son. Thanks to your prayers, I am stopping the long hand of the Father. I bless you all in the name of the Father, the Son and the Holy Spirit, Amen. Today's sign at 2:30 p.m: Most Pure Mary in my left arm.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 10)), "Dear children, I weep for those who are lost and for those who will be lost. This is the time of tribulation in families. Cling to me and you will be saved. Beloved children of faith, do not retreat. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 17)), "Dear children, thank you for being gathered here to pray the Holy Rosary, the earth will continue to tremble ever more strongly, come back and immerse yourselves in God's love before it is too late, listen to my messages and meditate with the heart. Beloved children, pray for Sicily, the most dangerous of volcanoes has already awakened; now I give you my blessing in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 20)), "Beloved children, thank you for being gathered here. Once again I invite you to confess all your sins with true repentance. Beloved children, a great light will soon be visible over the entire earth, which will lay bare your consciences, your errors and your goodness. Some will not bear the terrible vision, so much so that it will lead them to death. But God's people will be ready to follow my Son Jesus on the new earth which is ready for you, where brothers will help one another, where peace, love and joy will reign. My children, Satan is stirring up envy and jealousy among men; do not be tempted. Pray for Europe and in particular for Italy, where terrorism has already taken hold and will not stop. I bless you in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 24)), "Dear brothers, I, your Jesus, am here this evening to give you joy, peace and serenity in your hearts. Always be joyful, love one another as brothers and forgive. I embrace you and give you my blessing in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 27)), "Dear children, thank you for being here in this blessed house. At last I find you gathered here in peace with God, with the bliss and sweetness that you have in your hearts. I urge unbaptized adults and unbaptized children to do so now, so that when the great light arrives, they do not feel great suffering. Pray for Italy, for Rome, where the institution of the Vatican will be attacked. Pray for the Church, so that it does not collapse before your eyes. Pray for this Europe, that it may be united again. Continue always to have the peace of my Son in your hearts. I bless you and your families in the name of the Father, the Son and the Holy Spirit.  Amen.", dataset["text_en"])



dataset["text"] = dataset["text"].str.replace("Amen\"", "Amen.")
dataset["text_en"] = dataset["text_en"].str.replace("Amen\"", "Amen.")



dataset.to_csv("trevignano2016_cleaned.csv", encoding="utf-8", index=False)





