# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np




dataset = pd.read_csv("trevignano2017.csv", encoding="utf-8")


dataset["text"] = dataset["text"].str.replace("Amen\"", "Amen.")
dataset["text_en"] = dataset["text_en"].str.replace("Amen\"", "Amen.")


dataset["text"] = dataset["text"].str.replace("Amen Figli miei", "Amen. Figli miei")
dataset["text"] = dataset["text"].str.replace("Ora vi do la mia santa benedizione nel nome del Padre, del Figlio, dello Spirito Santo\. Amen Il segno di oggi :", "Ora vi do la mia santa benedizione nel nome del Padre, del Figlio, dello Spirito Santo. Amen. Il segno di oggi: 'Amore'")
dataset["text"] = dataset["text"].str.replace("Amen Durante", "Amen. Durante")
dataset["text"] = dataset["text"].str.replace("Amen Ecco", "Amen. Ecco")
dataset["text"] = dataset["text"].str.replace("Spirito Santo \.", "Spirito Santo.")
dataset["text"] = dataset["text"].str.replace("Amen ''Popolo Mio'' SEGNI DAL CIELO ''I H S''", "Amen. Sign: 'Popolo Mio'. Segni Dal Cielo: 'I H S'")
dataset["text"] = dataset["text"].str.replace("''IO SONO CON VOI \" ", "'IO SONO CON VOI'")
dataset["text"] = dataset["text"].str.replace("\"", "")
dataset["text"] = dataset["text"].str.replace("AmenLa", "Amen. La")
dataset["text"] = dataset["text"].str.replace("Amen La", "Amen. La")
dataset["text"] = dataset["text"].str.replace("AmenIn", "Amen. In")
dataset["text"] = dataset["text"].str.replace("Santo \. Amen", "Santo, Amen.")
dataset["text"] = dataset["text"].str.replace(" : ", ": ")
dataset["text"] = dataset["text"].str.replace("Spirito santo", "Spirito Santo")
dataset["text"] = dataset["text"].str.replace("Dio Figli", "Dio. Figli")
dataset["text"] = dataset["text"].str.replace("Amen Oggi", "Amen. Oggi")
dataset["text"] = dataset["text"].str.replace("Continua a leggere\. \. \. \»", "")
dataset["text"] = dataset["text"].str.replace("sinistro\.\.", "sinistro.")
dataset["text"] = dataset["text"].str.replace("Amen Il ", "Amen. Il ")
dataset["text"] = dataset["text"].str.replace("Amen \.", "Amen.")
dataset["text"] = dataset["text"].str.replace("Amen ", "Amen.")
dataset["text"] = dataset["text"].str.replace("uno per uno", "uno per uno.")
dataset["text"] = dataset["text"].str.replace("Gesu'", "Gesù")
dataset["text"] = dataset["text"].str.replace("\(13 04", "(13 04)")
dataset["text"] = dataset["text"].str.replace("insultato mortificato", "insultato, mortificato")
dataset["text"] = dataset["text"].str.replace("la Germania \.", "la Germania.")
dataset["text"] = dataset["text"].str.replace("Il Vostro Gesù", "Il Vostro Gesù.")
dataset["text"] = dataset["text"].str.replace("disperazione \.", "disperazione.")
dataset["text"] = dataset["text"].str.replace("voce \. ", "voce. ")
dataset["text"] = dataset["text"].str.replace("Bagnoregio 26 08", "")
dataset["text"] = dataset["text"].str.replace("\.Amen", ". Amen")
dataset["text"] = dataset["text"].str.replace("vostro Si di", "vostro 'Si' di")
dataset["text"] = dataset["text"].str.replace("facendo \.", "facendo .")
dataset["text"] = dataset["text"].str.replace("\"Beati coloro che verranno perseguitati a causa del mio nome\"", "'Beati coloro che verranno perseguitati a causa del mio nome'")
dataset["text"] = dataset["text"].str.replace("\"quando capirete i segni la mia venuta sarà vicina\"", "'quando capirete i segni la mia venuta sarà vicina'")
dataset["text"] = dataset["text"].str.replace("noi \.", "noi.")
dataset["text"] = dataset["text"].str.replace("AmenDopo", "Amen. Dopo")
dataset["text"] = dataset["text"].str.replace("pubblicamente \.", "pubblicamente.")
dataset["text"] = dataset["text"].str.replace("preghiera \.", "preghiera.")
dataset["text"] = dataset["text"].str.replace(" \.", ".")







dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 3)), "Dear children, thank you for having responded to my call in your hearts. My children, I am very sorry for your pains and tribulations, but ask yourselves, what did my Son do that was so bad? I know that you too will be persecuted in the name of my Son, but you have me, your mother, who will be with you every day, awaiting the coming of my Son, to finally bring you Peace and Love in this earth that is now torn apart by evil. Many holy priests, I will send to this place and I bless you and them, in the name of the Father, the Son and the Holy Spirit, Amen. Today's sign: 'I AM WITH YOU'." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 7)), "Dear children, thank you for being gathered here, do not be far from prayer and do not be overcome with weariness because of those who follow the ephemeral and are far from God, kneel down. My children, accept the mercy of my Son and keep your pride far away. Beloved children, pray for southern Italy which will be torn by pain, pray for the earth which will tremble incessantly. Pray for France and Spain where terrorism will give no respite. My children, I love you and I protect you; open your hearts and you will discover wonders. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 10)), "Dear Children, thank you for being here and for responding to my call in your hearts. My children, your prayers have saved many souls, so continue constantly with prayer and the recitation of the Holy Rosary. Do not give Satan the possibility to enter your mind and heart, follow my Son who is the only truth. Dear daughter, it makes me happy to know that many consecrated persons are here, you must tell them to take my embrace to their sisters and brothers, I pray in particular to the Most Holy Trinity for their conversion, for they are for me, beloved children! Now I give you my Blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 14)), "Dear Children, thank you for having heard my call in your hearts and thank you for the new people who have come to faith. The time of my Son's coming is imminent. Today I am blessing you in a very special way (He anointed us one by one) so that you may feel in your hearts that I am here, that I am present and that I will never abandon you. Beloved children, unfortunately the time of tribulations has already begun, but I will never abandon you! Open your hearts and pray, pray, pray. I beg you, do not think only of your career or of being someone in life, because you are already very important for God and this is the only thing that really counts. Remember my little ones, each of you is unique and special for God so do not push him away but say your YES every day and above all read the sacred scriptures. Pray for Italy, for Europe and for the world; they will face many tribulations. Be ready for the great light. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 17)), "Beloved children, thank you for being gathered here tonight also. Pray much for the Church and for the consecrated children. Soon Peter's Church will be destroyed by those who are approaching. Beloved daughter, I desire that you speak to the holy priests, asking them to teach children the true catechism, to teach that the devil exists and to explain who this cunning angel of hell really is. By now Protestantism is creeping into the Church and many no longer believe that in the Eucharist is my living Son. Soon they will not even acknowledge me as the Immaculate Virgin conceived without sin. Beloved daughter, how many will suffer for these sins. How many prelates, cardinals and bishops are taking the way of perdition! Help them to understand that my Son and the Gospel are the only truth and life. Soon you will be forced to return to prayer in your homes. Cling to the daily recitation of the Holy Rosary, which is the only shield that will protect you from evil. I will always be beside you whenever you invoke my name. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 21)), "Dear children, thank you for having heard my call in your hearts. My little ones, I weep for you and for all that you will see; do not weep for the dead, they already see the great light. You are living the times of purification. Beloved children, pray for the Church. Pray for Italy, where there will still be strong earthquakes and also the seas will be agitated, but do not be afraid; follow the Holy Gospel and pray the Holy Rosary in communion. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 24)), "Beloved children, thank you for having responded to my call in your hearts, especially the new people who are gathered here in prayer. Pray, my children, pray because Satan will not give you a break by dividing you and the Church, but you people of faith do not fall into this trap, be just and witness with courage. Love each other as God loves you. Dear children, look at what is happening around you, earthquakes, tidal waves and avalanches, we are at the end of time, so do not waste time, convert. I love you, do not be afraid, I will always protect you. Pray for the peace of the world, a war is being prepared where Russia, China and the United States will be involved. Now, I bless you in the Name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 26)), "Dear children, thank you for being here, finally united in prayer, with joy and purity in your hearts. Beloved children, you are always my little ones! This is how I see you, especially tonight. You will soon see my Son, to gather you all together in the one love which God knows. Unfortunately, you will be persecuted and then glorified, but I am with you as a mother and as the Queen of Heaven. Do not worry if you see signs in the sky, it is only my Son who is preparing His coming! Pride and arrogance are the things that are ruining the world. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen. Our Lady blessed those present, one by one." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 28)), "Beloved daughter, your tribulation will continue, my Son was accused of being a heretic but he continued to preach without stopping. You must go forward without fear, you must always give your testimony with strength and courage, I will protect you. Receive the lukewarm souls and help them to love my Son and to approach prayer. My children, by now the time is near, soon my Son Jesus will be with you to embrace you lovingly and to judge you one by one. Now I give you my blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])





dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 3)), "Beloved children, thank you for having listened to my call. Thank you for coming here to this blessed place with such faith. Leave your sufferings and tears under this cross and you will have wonders. My children, this is the time of apostasy. My Son continues to be scourged as then. Beloved little ones, convert because my Son's return is imminent and I desire that all of you be ready for that moment. Have faith, it will save you. I love you always and I bless you in the name of the Father, the Son and the Holy Spirit, Amen. The Holy Virgin also asks you to pray for the Pope and for all priests." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 4)), "Beloved children, thank you for having responded to my call. Pray for the Church, for the devil has already taken hold, but I will protect her with my mantle, so that my beloved children may be saved. Convert, pray the rosary and forgive your enemies. My dear children, do not be afraid of my messages, I was sent by God to save you and to warn you about what will happen, but I also give you instructions not to fall into temptations, above all, be careful of worldliness, be humble and simple and be merciful. Soon the sun will give great signs. Now I give you my blessing in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 7)), "Dear brothers, today I am here among you to give you my peace. Accept my mercy and never have doubts, because those come from Satan, who tries to manipulate your minds. Know that your prayers are needed by many souls and many souls will be saved thanks to you. Now I pass among you to give you my blessing. Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 11)), "Dear daughter, I know that the tribulations are not few, but remember that I am here with you. The beloved children (priests) say that praying to me obscures Jesus, so little by little they want to erase me from the hearts of my children. The Church, today more than ever, needs humble and courageous priests; my great sorrow is to see them on Satan's side with pride and power. Unfortunately, this will be the cause of the perdition of many souls. The war with chemical weapons is making its way, the earthquakes will continue without respite, but do not fear beloved children, I will always protect you. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 14)), "Beloved children, thank you for being gathered here in prayer. I am very saddened because I know what awaits you. Pray, pray, pray especially for the Church, which will be involved in one of the greatest battles between good and evil that has ever been seen. Soon, from the sky, you will see the sun emanating balls of fire, the fire of purification. Dear children, bear witness to your faith with courage and never flinch. Devoted daughter, offer your suffering for this sick humanity, offer your yes for all sinners. Now may my holy blessing descend upon you and upon the sacred objects in the name of the Father, the Son and the Holy Spirit." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 18)), "Dear children, in spite of a sad heart, it makes me happy tonight to see you gathered here in prayer, thank you for having responded to my call in your hearts. My beloved ones, my sadness is caused by the sinful expression of the Church, that great torment that you feel, I feel it, the split is greater and greater. I desire to see priests bishops and cardinals united in the one truth, the teachings of my Son Jesus and be shepherds of this flock that is being lost and do not think of a career because it will not help when you stand before God. My children, you will be persecuted but cling to my rosary and you will be saved. Pray for Spain, she will have great sorrows. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 21)), "Beloved daughter, accept your sufferings with joy because God's love is a great witness for the unbelieving and the doubters. Beloved daughter, embrace the Holy Church which leads to light, while the false church will lead to darkness, be prudent. May my Holy Blessing descend upon you, your family and friends in the Name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 25)), "Dear children, thank you for being gathered here and for having listened to my call in your heart. I ask you once again to change your life, be humble and courageous, do not be unprepared when my Son comes because He will not come only to free you from evil and to embrace you but also to judge you one by one. I, your mother, am coming and I will dry all your tears because you are my children and I want to see you joyful, pray, pray, pray and be filled with grace. The Antichrist has already made his entrance into the great palace. Pray for Europe and for the United States because the nuclear weapons are ready for the great war. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 28)), "Beloved and devoted children, everything is ready for the arrival of my Son and I desire that all be equally ready to receive Him. Open your hearts to mercy and approach the Holy Eucharist often, because only in this way can you feel that fire of love with which my Son envelops you. Always keep the Holy Rosary in your hands as a strong weapon to ward off evil. The false church will not stop, it will give clamorous news, touching the peak of spiritual confusion. The Holy Spirit will teach you to discern between evil and good, between right and wrong. Be cautious, just and courageous. Beloved children, pray for Russia and France where the earth will tremble, pray for the United States. I am saddened by the failure to consecrate Russia to my immaculate heart, as I requested at Fatima, and this will cause grave tribulations. Beloved children, I love you with all my heart, may the Holy Blessing descend upon you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "My beloved children, you who are gathered here, cannot imagine how happy you make me. Your prayers comfort my heart. Thank you for having responded to my call. Beloved children, always be united in prayer also in your families, always have the courage to witness faith and the graces which come to you from heaven. This is a time of tribulation where evil thinks it has won, but my immaculate heart will triumph very soon. Pray for the Church of my Son. Soon a man sent by the Father will come to free you from this abomination. You continue to pray for all the children chosen by the Holy Spirit. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 4)), "Beloved children, I thank you for being gathered here. Do not worry and do not be anxious during the great changes. Rejoice, you will soon embrace my Son. I bless you in the Name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 7)), "Beloved children, my sadness is caused by what they are doing to my Son. They continue to scourge Him, to humiliate Him and especially the consecrated ones chosen one by one by Jesus, have decided to replace everything that is divine law. Dear children, pray, pray, pray! Soon the heavens will thunder with the arrival of my Son. The angels will sound the last trumpets and everything will be ready. Be found in peace and love, I am here to save you. My messages will continue to be the instructions for your salvation, do not be afraid of what I tell you. For too long I have been asking you for true conversion, but sometimes you turn away, not believing in my words. My beloved children, strengthen your prayer group. Jesus sends you His blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 11)), "Beloved daughter, how many sufferings because of those who are far from God and profess to be prophets, unfortunately satan puts doubts, jealousies and the worst evils so that we turn away from God, you continue on your path that leads to truth and peace, I will accompany you on this path. . . entrusted to you. Beloved children, cover your ears when you listen to Christian theologians who interpret the sacred scriptures in their own way; always be in communion with Him who is the way, the truth and the life. Love one another and be charitable to your brothers and sisters. Pray for Spain and for Poland, I now bless you in the name of the Father of the Son and of the Holy Spirit. On this occasion, Our Lady asks us to pray the Holy Rosary at the place chosen by Her on Holy Thursday (13 April)." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 14)), "Beloved children, thank you for being gathered here, I feel with such sadness in my heart with how much falsehood and hypocrisy the Holy Rosary is prayed. Prayer is not a distracted chant, but a sweet music that is born from the heart. Dear children, stop and reflect on what is happening in the world, for you persist in not believing the messages I leave you, yet the warning is before your eyes. Soon, you will see a great cross that will be visible throughout the world and this will be the last chance you will have to choose, convert you have no more time. Now, I give you my blessing in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 18)), "My beloved children, thank you for being here in communion with me and I thank the newcomers who have responded to my call. I desire that you continuously nourish yourselves with the body of my Son, immersing yourselves in His cup. Join in prayer, follow my messages, God allows me to still be here with you to give you His peace and love. My apostles, trust Jesus, give yourselves completely to God. He is the light, the hope and the love. Ask God and He will answer you, talk to Jesus, carry His cross with love. Soon, very soon the earth will be purified, but my beloved ones will not have to fear. Trust and you will be saved. Prepare the blessed candles and keep them ready. Dear children, know that God's love for you is immense! But how limited is your love for Him! When He knocks on your hearts, what do you do? Do not be blind and do not be deaf. Reflect, follow the Gospel and always keep the rosary in your hands. Pray, pray, pray! I will do so many graces for you, accept them and witness them with faith. Know that I love you. May my holy blessing descend upon you and in particular upon the children present, in the Name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 21)), "Beloved children, pray so much to support my Son's cross which is very heavy. Still today He suffers much for the errors of humanity. Forgive and do not be taken by discouragement, do not get angry because you will become weaker and in weakness Satan will creep into you. Do not back down, be faithful to my Son and His cross, walk in truth and peace. My dear children, remember that God is love; He chose the narrow way and allowed Himself to be crucified for love of you; you, on the other hand, always seek the wider way because you do not always trust in Him. Pray for Japan and Syria, the earth everywhere will tremble ever more strongly. I leave you with all my motherly love and I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 25)), "My beloved, my love for you is great and that is why I ask you to share my pain. I thank all those for the work they are doing in My vineyard, especially your spouse. I thank you in seeing you gathered with fervor in prayer, but be careful, do not be tempted by my greatest enemy who is Satan. Today this modernist Church continues to make me suffer, I desire that priests continue to wear the cassock, that they do not deliver my body into desecrated hands and that they continue to follow the true Magisterium of the Church. Beware of consecrated Judas and Judas Catholics, for they accompany souls to hell. When you hear the heavens thunder and the earth tremble, I will come to embrace all my disciples to take them to new lands and new heavens, I am still anticipating my coming because this earth is too contaminated. Dear brothers I wipe away your tears and give you my holy blessing in the name of the Father of the Son and of the Holy Spirit, Amen. Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 28)), "Beloved children, thank you for responding to my call in your hearts. What is written will happen, the earth will be purified. Earthquakes and floods will be before everyone's eyes, many will flee but those who are faithful to my Son will not have to fear. My children, pray, pray, pray, the day of my Son's coming is already fixed, we are at the end of time and the angels are ready for this battle against evil. Heaven loves you and I love you. These are times where the tribulations will be stronger and stronger but you will have my protection. Now I give you my blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 1)), "Beloved children, thank you for responding to my call in your hearts. My children, continue to kneel in prayer and I beg you not to weaken. Satan is taking so many of my children. When you are in suffering, do not think that you will solve everything on your own, it is a great mistake! Remember, when you are in trial and fall, get back up, showing the trust you have in Jesus. In this period of Lent be in peace, do not have a lukewarm faith and do not pray out of inertia. Be careful with science, be careful with vaccines, they will try to manipulate everyone from birth. Beware of fake democracies because soon you will find yourselves immersed in dictatorship. My dear children, how much I love you and how much I want to protect you. Listen to my messages! I would like so much to take you all safe into the arms of my Son. Soon a meteorite will come to earth. Look often at the sky and its signs. Now I give you my holy blessing in the Name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 3)), "Beloved children, thank you for having responded to my call. It makes me happy to see in this blessed place so many of my beloved children and especially so many people of faith who listen to my messages and follow my advice. Beloved children, open your hearts to my Son, love as He loves you, love is the greatest weapon to fight evil. Never be downcast before your cross, as I have embraced that of my Son who died for love and defeated death. Let us pray together for the Church and for the priests who follow the Gospel and the Holy Scriptures and who sometimes need to be in recollection to hear what Jesus wants from them. Unfortunately, many of them are confused, but I ask them to go forward with courage. I love you my children, If you only knew how great is the love for you! Let your tears be dried by your heavenly mother. Pray for Russia. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen. Our Lady opened her arms as if to embrace us and protect us under her mantle." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 4)), "Beloved children, the heavens and the earth will tremble, but you will be saved by your faith. I insist on asking for the conversion of many; convert and love! This is the time of reconciliation and love. Forgive your brothers, do not live like the Pharisees, Jesus will judge you for how much love you have given. Pray for Chile where suffering will abound. Now I give you my holy blessing in the name of the Father, the Son and the Holy Spirit." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 8)), "Dear children, thank you for having responded to my call in your hearts. I, your mother, am here tonight to call you one by one as apostles and to gather all my people to tell you that everything is being fulfilled. Look around you, you will be taken in the arms of my Son during your sleep and brought to the new earth where you can be satisfied with the wonders I have prepared for you. Announce to everyone His arrival, be pure and joyful. Confess and feed as much as you can on the body of my Son. Do not delay in converting, there is no more time. Pray for Spain, the earth will shake strongly. Pray for Rome. My beloved ones, I leave you with the blessing of the Most Holy Trinity, in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 11)), "Beloved children, I weep for a Son who even today as before continues to be insulted, mortified and crucified.  Be faithful to Him and remember that He died for the great love of humanity, but at His return those who will have believed in Him will have eternal life. I weep for what awaits you. Prayer, Eucharist and fasting will have to be your food in these days. Pray, pray, pray, vibrate in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 13)), "Dear children, you gladden my heart by seeing you gathered here as I have requested. Beloved children, rejoice this Easter because Jesus my Son died for the remission of the sins of mankind past and present, thus giving you eternal life, which is not only of the spirit, but also of the soul and the physical. Dear children, my Son after the crucifixion spent five hours on the cross before He expired. He did the Father's will for all of you, even though they spit on Him and insulted Him, but this was the greatest act of love He could do for us. So please, since His greatest gift is being alive in the Eucharist, feed on Him always, repent and be ready. His coming is near! I now bless you in the name of the Father, the Son and the Holy One. Our Lady was dressed in white and next to her was Jesus. Our Lady embraced us all. This Rosary recited on the mount on Holy Thursday, was expressly requested by Our Lady, to celebrate the institution of the Eucharist and the Priesthood." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 18)), "Beloved children, thank you for having responded to my call, tonight I ask you to rejoice because my Son is risen and so, I would like you to rise with him. Come out of your tombs, the tombs of selfishness, slander, wickedness, blasphemy, pain caused by yourselves, rise from all this and you will be saved. My little ones, always remember to love each other as brothers and always preach love and peace. In these times you will have to pray so much for all that you are facing. Make circles of prayer, I will always be with you to protect you. Pray for France. Now, I give you my blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21)), "Oh, my beloved children, thank you for being here, in this blessed house, thank you for being so many to open your hearts to my Son and there are still so many of you in the world, do not be afraid of what is happening around you, I am and will always be beside you. My great joy is to see one of my beloved children whom I always call in humility united with you. Obey the Church as long as everything is in the Gospel and the Holy Scriptures. Preach love and pray for Rome. I love you and with motherly love I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 22)), "Beloved children, thank you for those who have listened to my call. Dear children, time has come to an end, sometimes you are so accustomed to evil that you do not see the demons that surround you, you cannot see the antichrist who is already in your midst. Remember that good produces good and evil produces evil. Embrace your cross and carry it with joy and love and you will be victorious, just as Jesus conquered death. My beloved ones, be my apostles and always courageously witness your faith so that many souls may be saved. Pray for Russia and for the Pope, much depends on him. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 25)), "Beloved daughter, nature is rebelling, men are moving towards self-destruction. Beloved daughter, spread this message to priests, bishops and cardinals. I ask you to confess the sins of heresy and carnal sins because they are very serious! Confess before it is too late, entrust yourselves to the mercy of Jesus. Beloved children, I intercede for you, but you live my messages and always be humble, as I have taught you. Pray for the United States. I love you and bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 29)), "My beloved children, thank you for having listened to my call in your hearts, I know how much you are suffering for everything that surrounds you, for the wars that are beginning, for all the victims and for so much suffering in the world. I also suffer with you, but if they had listened to my words all this would have been avoided, I had asked to consecrate some nations to my immaculate heart, but they did not listen to me. My beloved ones, you who are experiencing my grace, my great love and the immense mercy of Jesus, witness fearlessly and courageously and above all continue to live my messages, my presence among you serves to save souls and to intercede always for you. I love you immensely, woe to those who by their pride lead souls towards perdition and confusion, for they will suffer God's justice. Now I bless you and the sacred objects you carry, in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 2)), "My beloved children, now the time to return to prayer in the homes is about to begin. My heart is saddened when I see the powerful of the world, the consecrated and many of my children in the hands of Satan, but soon you will be in the time of warning and choice. I ask you to choose love for my Son, save yourselves and convert, I will always be at your side with all motherly love. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 3)), "Beloved children, thank you for listening to my call in your hearts. I know your sufferings and tribulations, but I am here to wipe away your tears and to be with you always. Unfortunately, at this time Satan is taking as many souls as he can. If man had listened more to my words and the Fatima messages, you would not be at this point. I pray for all of you to live humility and silence, this is my legacy. I love you my apostles. Always kneel in prayer. I now bless you in the name of the Father, the Son and the Holy Spirit. Our Lady today was dressed in white and had a heavenly mantle. She spread her arms wide as a sign of protection for all those present and for all those for whom we prayed. She is thinking of everyone." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 6)), "Beloved children, I thank you for being here. What more must I do to make my Son Jesus love me? Ask for graces, but do not pray with an open heart. Love each other as brothers. Beware of the consecrated persons who do not follow the Gospel, whose guidance leads to the abyss; whoever follows them will go to meet the darkness. I love you so much my children and I warn you for your salvation. Now I bless you in the name of the Father and of the Son and of the Holy Spirit." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 13)), "Dear children, thank you for all those who heard my call in their hearts for this special apparition. Today is 100 years of my apparitions and announcements. My beloved ones, consecration to my immaculate heart is an immense protection against the diseases that will soon come and against the attacks of demons. After so many apparitions, still many do not believe in my messages, but these are the times when everything will be seen with your eyes. Love and defend the Most Holy Trinity, proclaim love in the world and you will see graces and wonders descend upon you. Thank you my little ones, I love you, now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 16)), "Dear daughter, my heart aches for the blasphemous and false men who preach love but do not put it into action, because of their pride and haughtiness. Beloved from Heaven, keep my people united and soon you will enjoy the wonders ready for you. You are blessed by the Most Holy Trinity in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 20)), "Beloved children, thank you for being gathered here in this blessed place. People of God loved by me and by the Most Holy Trinity, to gather you is what I wish for all humanity. I have chosen you to be an example today and always, just as I have gathered you today, I will gather you again to save you and all the souls who still do not find peace, truth and the way. Love each other as brothers. Upon you will descend the graces you have asked for and my blessing, in the name of the Father, the Son and the Holy Spirit, Amen. Mark: 'My People'. Signs from Heaven 'I H S'." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 23)), "Dear children, the arm of God can no longer be stopped. The fire of purification will soon come upon the earth contaminated by evil. The time has come. The corruption of men has run out of time. My beloved ones, convert and pray, pray so much, soon the church will no longer be the home of my Son. Today most of my consecrated children no longer behave like pastors and this is my greatest sorrow. I ask you to love my Jesus and to keep the Holy Scriptures. Now I bless you in the Name of the Father, the Son and the Holy Spirit. May my holy blessing descend upon your families and upon the sacred objects you carry with you. Pray for France From the moment the Eucharist is removed from the Church, Sacramental Jesus will no longer dwell in it." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 27)), "Dear brothers, I am coming closer and closer to you in this time of grace, every day you will see and feel my presence to give you a taste of my love for you. I love you so much that I died for your salvation. My beloved ones, soon you will enjoy the delights I have prepared for you. Listen to what my beloved Mother is telling you. Thank you, brothers, for being gathered here. I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 29)), "Beloved children, thank you for being gathered here. I ask you to decorate a small altar in your homes, I ask you to pray the Holy Rosary every day by lighting a blessed candle. Prepare yourselves, for these are the times. My beloved and precious children, how much grace will descend on your hearts! Always love my Son, as I love you. All that has been foretold will happen, even if it is mitigated through prayer. I am here with you. I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 30)), "My lovely jewels, thank you for accepting my call, do not be upset by what is happening around you, soon believers and non-believers alike will see the great miracle, a great light will appear over all the earth, the heavens will thunder, no one will be able to say anything except to hail God for His power and greatness. Now I bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 3)), "Beloved children, thank you for listening to my call in your hearts. I am here among you because I feel strongly the grace of your prayer. My children, your Jesus will soon be among you, He is already on your heads to instill in you the Holy Spirit, peace in your hearts and union among you brothers. Always love My Son. Unfortunately, Satan works in your minds putting doubts and fears. Pray for the priests, bishops and cardinals who at this time are against each other and are not always guided by the Holy Spirit. Pray for the Church, soon it will be freed from this confusion. I love you and protect you always, call me and I will always be there with you. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 8)), "Beloved daughter, Satan is putting his tentacles in the prayer groups and in all that is Sacred to create misunderstandings, discord, false doctrines, doubts and bitterness. It helps to understand how great is the merciful and just love of Jesus. Charity, love and union make the people of God. My daughter, worse times will come but be jealously bound to the truth and sacred scriptures of the past. Listen and spread this call, I will stand by each of you so that you may be worthy of the new earth. I bless you with motherly love in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 10)), "Dearest and beloved daughter of the Most Holy Trinity, do not burden your heart with the things of the world, for you are in the world but you are not of the world. Love everyone as I love you. Soon a great light will appear in the sky, so that believers and non-believers alike will have the last chance to choose between surrendering to my love and being enveloped by me and believing in my return, or darkness. My beloved Mother touches the earth not to frighten you, but for your deep conversion. Beloved ones, convert, repent and pray for the world because it is in great danger. I give you my Holy Blessing in the name of the Father, the Son and the Holy Spirit, Amen. Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 13)), "My most precious children, thank you for listening to my call in your heart. Beloved children, I ask you to give precedence to love, it is the only feeling that should move the world, love with all of yourselves, because God is love and it is the only thing that really counts. Always follow and spread my messages and never stray from what Jesus asks of you, peace, love and mercy. Pay attention to false doctrines, the Holy Spirit will descend upon you to make you open your eyes and understand which is the holy way and which is the way of darkness. Dear children, repent and convert in these last moments, before Jesus comes to take you to hold you tightly in His arms. With motherly love, I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 17)), "Dear beloved children, thank you for responding to my call. Come closer to my Son more and more, the warning is near, so finally everyone: believers, atheists, other religious and unrepentant sinners, will be before their consciences and all will truly feel the weight of their sins. I am coming to save you and to prepare you for the second coming of my Son Jesus. My beloved and delightful children, always feed on the Eucharist as long as you have time, for because of the Body of my Son they are preparing to disown the living Jesus. You will have much to fight for especially the persecution of my children will be terrible, even my consecrated will be excommunicated if they do not follow the faith of men. Take strength from Jesus, I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 20)), "Dear children, thank you for being gathered here in prayer. Woe to those who mock my children, especially those who carry my word into the world. You are my children and I am your mother and I want to protect you. I desire that the walls of pride and discord be torn down, that you be in peace in love and truth Unite yourselves in prayer to my Son, that all may believe in what He has left you, His living body in the Eucharist. Modernism is driving many away from this truth and faith. You will be persecuted, but I will give you the strength and courage not to be tempted by evil. Pray for Argentina. I bless you one by one and bring peace to your homes in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 24)), "My beloved ones, thank you for responding to my call in your hearts. Beloved children I weep for you and for the times to come, they will be very hard, but those who have faith will endure the dark times. The devil has diverted the powerful of the world to send you into ruin, I beg you children, pray, pray so much, the earth is beginning its transformation. Today, humanity has surpassed Sodom and Gomorrah, many no longer love life, because the devil has bound them to his chains. My beloved ones, I will be there, where I will be invoked to help and protect you, always be burning flames of God's love. Pray for Russia, because of terrorism. An asteroid is getting closer and closer to the earth. I bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 27)), "Beloved children, thank you for gathering in this blessed place. Thank you, for your prayer with the heart. My children, lift up your eyes to Heaven and praise your Jesus. Even the angels will sing with you. Jesus loves you and leaves you his peace, my blessing and that of the Father, descend upon you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])



dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 1)), "My loves, thank you for being here, this prayer of yours consoles my heart and that of Jesus. My beloved ones, pray for this modernist church, it seems that everything is the same, but everything is being transformed. Slowly they will remove my son from the altar, they will make you believe that this new religion will be what the world needs, so that the brothers will unite in one God, this will be false and it will be satan's deception. Jesus will give you gifts, especially the gift of discernment, so that the true people of God may recognize and unite, do not be afraid and witness with courage. I love you and always pray to the Most Holy Trinity. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "Beloved children, I am here because the Father is allowing me to touch the earth again. My Son wants your salvation as much as I do. Today I come with all motherly love to send you towards the true faith. The sacred scriptures are important and still will be your anchor. You are My wonderful children. Gisella, today you will have a great sign, but be serene because I will be with you. Beloved children, listen to and follow my messages because man does not live by bread alone, but also by holy words; always do the will of God now and always. May my blessing, on the sick and on those present and in particular on those who are in this holy place, remain with you now and always. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3) & (dataset["author"] == "Holy Father")), "Beloved children, I am your Father! Be always in My mercy. It is I who allow Jesus to touch the earth. For the consecrated: open your heart and I will enter with My Love into you with a great light that will allow you to be My children and My friends. Unite yourselves with the love of Mary and Jesus so that you, through free will, may be mine! I bless you in my name, in the name of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 8)), "My dear children, I know your sufferings and your anguish, but I am here, I am beside you, every day, to give you strength, entrust everything to me, I beg you do not let your difficulties become sadness that does not come from God, but my Son will transform them into joy and have faith, have faith, have faith. Pray for Germany. Now I bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 11)), "Brothers, I am here with you to fill you with so much grace. My beloved people, I am and will always be with you so that we may win together, soon the heavens will open and I will come to embrace you again. May my Holy Blessing descend upon you in the name of the Father, the Son and the Holy Spirit, Amen. Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 15)), "My beloved children, Jesus has given you the gift of discernment and you must use it. At this moment all of you are feeling nervous, sad, restless and these are all feelings that the devil gives you to make you fall into temptation, this is the moment of Choice. Dear children, there will be father against son, sister against sister, husband against wife and all this will fall into despair. Please make the right choice and love each other very much. I am with you to comfort you. Now I give you my blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 22)), "Beloved blessed children, thank you for gathering here and for responding to my call in your hearts. Dear children, I am here to comfort you, soon there will be the presentation of the antichrist, pay attention, stick only to the Gospel and the Holy Scriptures. Soon the Holy Mass will be changed. The time is ripe for everything to be fulfilled, the fire of purification will come from heaven, but the angelic hosts will come to protect you. Pray for Russia and for the United States. Now I give you my motherly blessing in the name of the Father, the Son and the Holy Spirit, Amen. " , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 25)), "Beloved children, thank you for being gathered here today also. My treasures, life on this earth is a great trial, do not think that what you have built materially is the highest aspiration, rather think of the spirit, especially in these times when everything will change without your realizing it. Be ready by purifying yourselves and feeding on the Eucharist. Dear children, I predicted that the great confusion would be the sign that precedes the last times, now everything is in the moment, I beg you to open your hearts and think of the place that awaits you full of joy and peace. Pray for Iceland. Now I give you my blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 27)), "Beloved children, blessed by me and by the Most Holy Trinity, today I wanted you in this blessed house, because I would like to speak to you and to your hearts, you are my flames of love and my jewels on this earth, I ask you to stay united, comfort each other, do not be tempted by the deceiver who can do anything when doubts and uncertainties give him space. Love my Son who is the only truth. I am here among you to leave you peace, glory and joy. I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])

dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 1)), "My people, I am here among you, now my arrival is only a breath away, be ready, work for me, announce it to the world. My mother has been touching the earth for so many years asking for conversion and love, now it is no longer time to convince anyone of the truthfulness of the messages. You have been marked by me, but this is also the time of Satan who will do anything to have as many souls as possible. Brothers, this is the time of tribulation and persecution because of my name, but you shut your mouths and be deaf, go forward with love and prayer, do not listen to those who tell you that everything is fine, be sensitive to what is happening around you including the sun, I love you and I bless you in the name of the Most Holy Trinity. Amen Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 3)), "Pearls of my heart, thank you for gathering here. My children, listen and watch for the signs. After so many instructions, I am still asking you today urgently for conversion and love. Please, dear children, soon there will be a warning, the stars will merge to form a great red cross that will be visible all over the world and then your consciences will be infused with a great light and that will be the last chance for salvation. Do not be afraid, I am and will be with you but be ready! Pray that Russia will not enter the war. With motherly love I give you my peace and blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 5)), "Beloved children, thank you for responding to my call in your hearts. Dear children, open your hearts and keep your faith firm. My Son continues to be crucified and His hands continue to bleed from the nails driven in. My children, look at the signs that surround you, like the warmth of the sun, remember what Jesus said 'when you understand the signs my coming will be near', once again He anticipates His arrival so please do not sleep, but be awake in love in faith in forgiveness and sacrifices. Now, I bless you with motherly love in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 8)), "Beloved children, thank you for being gathered here in prayer. Dear children, your mission has been attacked, be ready for Satan's abomination and cunning. This is the sign of my presence in that blessed place, where with so much love and dedication you have taken care of everything for the reception of pilgrims, but do not be sad, I will protect you and be beside you in the time of struggle. Pray for the prophets and for those who are my voice and my word. My children, be mute and deaf especially when you are challenged. Now I bless you in the name of the Father and of the Son and of the Holy Spirit, Amen. Behold, I pour peace into your hearts." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 12)), "Beloved children, thank you for being here for the recitation of the Holy Rosary, I beg you to be strong in faith and in my Son Jesus, He is the only way, truth and life. My beloved little ones, always be pure in heart, blessed are the pure because they will be exalted in the eyes of the Father. Justice will be great for those who are persecuted and offended, because they are bearers of my word, in my name and in the name of my Son. Each one of you will have the cross you can bear, but I will protect you. Jesus will give you the strength to continue on this road that leads to the light, I know that it is the narrowest road in this time of great trial and choice, but do not forget that I will be with you. Now I bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 15)), "My children, thank you for being gathered here on this very special day for me. Beloved children, I feel your hearts beating fast and in every beat there is my presence. Dear children, every time you recite the rosary with all your heart, many souls will be saved and many graces will come down. My children, God gives you the possibility to feel His love and I ask you to pursue the way that leads to holiness, God loves you immensely. Thank you, beloved children, because with your prayers you comfort my heart. Now I give you my motherly blessing in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 19)), "Beloved children, thank you for listening to my call in your hearts. Thank you, My disciples, today apostasy is now within My Church. The antichrist wants to destroy her together with my consecrated children, creating great confusion and setting them against each other. Be ready for the time of warning because it is very near. Everything is falling apart, go ahead with prayer. People of God and my people, be united in one voice . I now bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 22)), "Beloved children, do not fear, I am with you to protect you, evil is spreading in every corner of the earth, justice and punishment are approaching. My dear children, I am your mother and I will never allow Satan to approach your families. Pray, pray, pray. Have faith in my Son Jesus who is with you and in you. Selfishness and envy lead astray, peace love and charity are the three things that lead to God. Pray for France and Italy because they will feel so much pain. I am with you and will not leave you. I now bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 25)), "My beloved ones, thank you for being gathered here, you with your love and your prayers comfort my heart. My beloved ones, I am here present with you together with my Son. I weep for what they are still doing to my Son Jesus, look at the signs of purification, it has already begun and still many do not realize it. I desire that my messages be spread as soon as possible so that some souls may take the road of conversion. Be my soldiers and protect my children. Pray for Brazil and Spain. I love you and in the name of the Holy Trinity I bless you. Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 26)), "Dear children, you console my heart and are in each of the wounds of my Son, entrust your sufferings to Him. I am here with you, every day, together with Jesus. Dear daughters, soon the heavens will open and you will be in the arms of my Son. My angels will protect you. Now I bless you in the name of the Father, the Son and the Holy Spirit." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 29)), "Beloved brothers, my heart rejoices to see you gathered in prayer. I ask for the conversion of everyone quickly, because there is no more time, do not take lightly the messages of my beloved Mother, follow her suggestions and desires, because Satan will always be stronger, because he knows that soon he will be chained in hell. My heart bleeds for the blasphemies and all that they continue to do to me. The nations are one against the other, the earth will continue to tremble and the seas will churn. Believe in me, trust me and I will protect you together with my Mother, I will take you and you will be full of light like bright stars. You are loved by the Most Holy Trinity. I bless you one by one in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])

dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 5)), "My beloved ones, precious jewels of my heart, thank you for being in prayer. I am always beside you when you invoke me. I know your sufferings and I weep for what awaits you; I desire your yes, sincere and with love. Beloved children, forgive and do not be proud, always give precedence to love. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 9)), "My beloved children, thank you for your prayers, for your complete trust and for your daily 'Yes'. My treasures, pray, pray so much, they are tending to take away from you the bread of life, the precious food for your spirit and therefore the Eucharist. Soon, Korea will be attacked, pray for the United States, there will be much suffering. Now I leave you peace in your hearts and give you my motherly blessing in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 12)), "My beloved children, thank you for consoling my heart. I desire prayers and rosaries for this humanity that is in disarray; even my consecrated children no longer know what is right or what is wrong, but if they would listen to my messages they would come out of this confusion. I am here to show you the way to go, but you persist in not wanting to believe in my apparitions and in not believing that I have been sent by My Father to advise and instruct you. I am your Mother and I weep for everything that is happening, I beg you children, come back to the light, the time is over, convert, confess the most serious of your sins and do not be found unprepared and give true importance to the Eucharist. Pray for Colombia, she will soon drink the bitter cup. I now bless you in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 16)), "Beloved brothers and sisters, how much suffering in your hearts, but never forget that I know you and am within each one of you, especially when you take the Eucharist. My brothers, I weep for all the evil, I suffer and feel more and more pain for what they are still doing to me today. Look at the world, it is true, there are floods and earthquakes everywhere, but are you able to overcome all this? Listen, only those who will have Me in their hearts and in their lives will be able to navigate through these turbid waters. My Father has already established the day and the hour of the Warning that only I know, so do not listen to those who give you dates and months. Now I bless you in the name of the Holy Trinity and may peace enter you and your homes. Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 19)), "My beloved children, thank you for your sufferings offered for the cross of my Son.Remember what my Son said: 'Blessed are those who will be persecuted for my name's sake'. By now there is no more time to look at the things of the world, listen in silence to your hearts, exalt your spirit and save your soul. I bless you and I am with you every day to love and console you. Now I give you my Blessing in the name of the Father and of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 23)), "My beloved children, thank you for being gathered in prayer, because by following my instructions you have strengthened it. My dear children, I ask you never to extinguish that burning flame of faith; I know how many difficulties and how many snares there are in your homes, but the Holy Spirit, if invoked, will enter within you to lead you on the right way. Remember that God alone is the life, the truth and the way. I ask you to offer sacrifices and fasts in this time of great tribulation. Beloved sweethearts, do not be afraid, I am with you, prepare yourselves for the second coming of my Son. Pray for Mexico and the United States. Now, I bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 26)), "My beloved children, thank you for listening to my call in your hearts. Beloved children, remember that God is love, but do not forget that God is also just, I would like you to firmly believe that evil exists, that deception exists, that sin exists and that Satan exists, there is Heaven, but also Hell, never forget it! Do not let your minds be misled by those who belong to the false church, so that you do not believe in the king of hell. Confess, my children, believe in the Eucharist, where my Son is alive, convert and open your hearts, so that Jesus may be one with you, to be able to love and comfort you. My children, the times have come to an end, but I will always protect you because I love you and I will be present whenever you ask for my help. Now, I bless you, in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 28)), "Beloved children, thank you for being gathered here in this blessed home, how much joy you give me in seeing you here in prayer!!! O you, who if you remained in silence, would feel the angels enveloping you to protect you, I send them because in these times you will need comfort and I would like so much that you perceive these angelic presences so that you will not feel alone. Now I give you my motherly blessing in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 30)), "Beloved children, thank you for being here in the prayer of the Holy Rosary. My beloved ones, how many sorrows you have in your hearts, in your families and in your homes, often, you are very attentive to the evils that are around you, but you do not pay attention to the graces that come. My Son allows all this, especially for the beloved children, so that you may be put to the test, how little faith I feel in my little ones. I desire that you entrust yourselves more, open your hearts, when you go to Church on Sundays, do not do it out of habit, but with faith, otherwise you offend my Son. Pray for Italy and be ready for the embrace of my Son Jesus. I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])

dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 3)), "Beloved children, my jewels, thank you for having listened and responded to my call in your hearts. My little ones, how much suffering I feel in your hearts, but I beg you to have faith and open your hearts so that my rays of love may enter you. My beloved ones, what I predicted is happening, look with your eyes, the day of the great apostasy in the Church is today, soon they will remove the Eucharist and the crucifixes from the churches to give place to modernism and heresy. Please hold the Holy Rosary in your hands and recite it every day, pray for the priests and for humanity, so that they may choose the way of truth, which is my Son Jesus. The false church together with the demons are taking the place of your Jesus. This is the day of tribulation, come out and announce my Son's return. Be my apostles, I love you and I bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 7)), "My brothers, I am here with you today and I will stay for all the prayer, thank you for being gathered here. I am preparing you as my soldiers of light, because the war with the angels of darkness is getting stronger every day, that is why I am constantly asking you through my Mother to pray hard and always. Never, in the world, has there been a battle so important and so great for humanity, what is happening around you is the evil caused by man, who offends my Father. All of you are waiting for My Return. Do not wait for the signs to come to convert, but do it now. I am with you and will remain with you until the end, when I will finally be able to embrace you and make you enjoy the most beautiful delights prepared for you. I bless you in the name of the Most Holy Trinity, Father Son and Holy Spirit. At the end of the message, Jesus stretched out his arms praying over all of us." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 10)), "My beloved children, flames of love burning on this earth, children of my heart, thank you, thank you for being here in prayer. My beloved ones, the time of warning is very near, do not waste time on the things of the world, but think of those of Heaven. My loves, they are betraying my Son, especially my beloved ones, soon everything will be clearer in your eyes. In Italy, soon there will be a great event, but despite everything, many will not believe. Pray for Japan. Now I bless you in the name of the Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 13)), "My beloved children, I thank you for listening to my call. I have come today on this special day and I have called you here to gather in prayer and to tell you that everything that is happening to humanity is also caused by the failure to consecrate Russia, which I asked for at Fatima, so that the wars that are now imminent do not begin. My beloved little ones, remember well this word 'commemoration', soon it will be the word that will be present in the Churches instead of the Eucharist. 'Commemoration' . I have prayed so much to My Jesus that you have so many graces, and here, upon you they have descended in abundance. What are you waiting for to love my Son with all your heart. Now I bless you with motherly love, in the name of the Father, the Son and the Holy Spirit, Amen. After Our Lady's apparition, Gisella went into ecstasy and Jesus through his voice said: My children listen to my mother, I am with you in these dark and hard times, love me as I love you. I bless you! Our Lady today was dressed in white and had a rosary on her left hand that was transparent as if it were crystal, she was accompanied by many angels and emanated a wonderful light." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 24)), "Dear children, thank you for listening to my call in your heart. I am your mother and I am beside you, taking you by the hand. My beloved ones, do not be afraid, offer your sufferings, your tribulations and your wounds to my Son, but do it with faith and complete trust, and He will transform your life. You are, and will be put before trials, sometimes terrible ones, but I am here to console and support you, I will never leave you alone. Jesus in these times is doing many graces to show His presence, speeding up all things. I ask you for your conversion and be the true portion of the Church. Now I bless you with motherly love in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 28)), "Dear children, thank you for listening to my call in your heart. I suffer for the times that await you, I have already foretold you of earthquakes, floods and apostasy, all this has passed before your eyes, now is the time of the imminent war that is being prepared in the world. I beg you children, do not abandon Jesus, He alone is your salvation. I am here to instruct you in this time, do not be distracted, listen to my words so that you may be saved. My beloved ones, listen to the silence, pray the Holy Rosary, and forgive your brothers, purify yourselves and feed on my Son, not only through the Eucharist, but also through the Word. By now everything is transforming, there is no more time. Darkness will be defeated by light and peace, joy and love will finally reign. I love you and will always protect you. I now bless you in the name of the Most Holy Trinity. Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 3)), "Beloved children, thank you for being gathered here in this blessed place. My heart beats with joy to see you gathered here in prayer, that prayer which comes not from words, but from the depths of your heart. I know how much you grieve, especially for the Church, that Church which must never be left alone. Be serene because my Son will protect her until the end, raising her, as he did, from the dead. I ask, and I desire, that priests do not let themselves be deceived by false ideologies and that they continue with the Gospel in hand to profess the word of Jesus. Beloved children, everything will be fulfilled, but Jesus will be at your side to follow you, therefore, do not afflict your hearts, for after the sufferings he will open the doors of love in your hearts and peace will return. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen. During the apparition, Gisella saw the heavenly Mother open her arms and with her blue mantle, she covered all those present as a sign of protection." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 4)), "Dear children, thank you for listening to my call in your hearts. You are my pupils, the eyes of purity and faith. Often you wonder what is true and what is false, but you have Jesus who will guide you by making you understand, but you always be on guard because now the demons are all over the earth, endangering your faith and especially prayer groups. Soon, the antichrist will be shown publicly. Always kneel in prayer, even the shepherds knelt before Jesus, why do you not do it? I continue to pray to my Son so that everything may be mitigated. Now I embrace you with motherly love and bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 7)), "Dear brothers, thank you for your prayers because they ease the pain of my wounds. My beloved, how many times in prayer you have asked me if all this evil I can stop it, but I cannot, because remember, all the demons are on earth and all this evil can be annihilated only with the purification of fire and water. Because you are constantly asking me when my return will be, I tell you, soon it will be my descent on earth, but besides the embraces there will also be much pain. Brothers, you must believe only in Me, and in My Name, and the angels of peace will protect you. Pray to the Most Holy Trinity. Convert while there is still time, now all is soon over. Now I bless you in the name of the Father, in My name and in the name of the Holy Spirit, Amen. Your Jesus." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 11)), "Beloved children, thank you for having responded to my call in your hearts. My children, continue without stopping in prayer, in the recitation of the Holy Rosary. My little ones, pray with your hearts for your souls, for the days to come, but do not be afraid in spite of everything. I, your Mother, will never abandon you. Soon, the earth will tremble, announcing the return of Christ and the echo of His powerful voice, like a trumpet, will be heard all over the world. I now bless you in the name of the Most Holy Trinity, Father, Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 14)), "Beloved children, thank you for listening to my call in your hearts. I am your sorrowful Mother who weeps for the children who walk in darkness and not in grace. Pray, pray, pray, from heaven it will rain water and fire and the great volcano is ready for its awakening. Adored children, I love you, open your hearts and convert. Woe to those who will not believe my messages, for they will not be ready. Pray for Japan. Now I bless you in the name Father of the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 18)), "Dear children, thank you because you are going ahead with the mission that I have entrusted to you. My beloved ones, have the courage of faith, go forward with your heads held high without turning back, very hard times await you, pray, pray a lot and above all, pray to my Son. I will be close to you. Pray for the Pope who despite all the difficulties keeps the true faith united. Pray for the Vatican because soon there will be an earthquake at its doors. I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 21)), "Beloved children, thank you for accepting my call in your hearts. Beloved children, treasures of my heart, I as mother and co-redemptrix continue to be here for your salvation. My Son Jesus is suffering more than His crucifixion, because humanity has exchanged truth for lies, love for hatred, humility for pride, faith for heresy. Soon my Son will come, just as He left, and I beg you to gather as many souls as possible and bring them to conversion. My Son is blowing into your hearts, bringing the Holy Spirit, accept Him and let yourselves be transformed. I am here with you, now I give you my motherly blessing and bring peace to your families in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 25)), "Beloved children, thank you for listening to my call in your hearts, thank you also to those who, curious and in search of the truth, approach prayer. Beloved daughter, to those who ask why God punishes, answer, because many freely follow Satan, who has inserted himself into the Church of God so that everything may be destroyed. (Our Lady, as Church also means the family, therefore the domestic Church). I ask you to be constant in prayer and in the sacraments; be ready. Satan, underhandedly, is settling in the minds of many people creating doubts about the apparitions and my messages. A sudden flood will come soon. Pray for Portugal. I am close to you, especially in your tribulations, in particular I remain close to the true shepherds who will be guided by my Son Jesus. Now I bless you in the name of the Most Holy Trinity, Father Son and Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 28)), "Beloved children, I have no more tears, these from today are the only ones left. I weep for all that will happen in the world, wars, earthquakes, floods and because the wicked are preparing to enter the Church of God. My children, today I ask you to pray, pray without ceasing and in spite of these times you go forward following the 10 commandments with the joy of having Jesus in your heart and strive for eternal life. Love each other and stay united. My Son will destroy the evil on earth by bringing back peace, joy and love, but you must choose now which side to be on. The devil is destroying everything, pray especially for the priests, many of them have chosen the way of evil, be vigilant children! As Mother, I will protect you with my mantle, entrust yourselves and together we will witness the triumph of my Immaculate Heart. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])


dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 3)), "Beloved children, thank you for having responded to my call in your hearts. Beloved children, in the world there are many hard hearts that are unable to see and understand the signs and graces that I send them. My children, you will be judged not by how many prayers you recite, but by how much love and mercy you are able to give. Think of how much love God feels for you and how much He asks for Him and for all creatures who are far from the sacraments and who do not follow the Gospel. Accept this immense love and infuse it into your brothers. Jewels of my heart, I protect you and I am always beside you, so that evil may not undermine you, I love you and you pray to my Son Jesus. Now I give you my holy blessing in the name of the Father, the Son and the Holy Spirit. Amen Today's sign: 'Love'." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 5)), "Beloved children, thank you for being gathered here in prayer, I know all your sufferings, but this is the moment of great Grace. My little ones, soon you will see the great sign appear in the sky, it will be a red cross, red like the blood shed by Jesus for you, know that on the left hand of God there is the warning and on the right hand the miracle. The earth will continue to tremble, soon everything will be fulfilled. Remember that God is good and grants forgiveness to all those who will sincerely repent with humiliation. Pray for France and Russia. I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 8)), "My beloved little ones, thank you for having responded to My call in your hearts. My little ones, this is the time of the Word, listen and read little pearls of the Gospel every day so that you may hear what Jesus has left for you to say. My little pearls, I ask you today to pray a lot more for the world and its Church, for they are desecrating My image and that of Jesus. Jesus will come soon together with Me and all the angels. Dear children, in moments of difficulty, recite a Creed and a Salve Regina. He will come for the judgment so that those who do not see may see and those who see may become blind. (John 9:39). Repent and repent by walking the path of holiness. Pray for France. Now I bless you in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 9)), "Beloved children, thank you for being here and listening to my call in your heart. You are close to a great war, the whole world is at war, pray for the world and for the conversion of their rulers. All that has been foretold will be fulfilled. My children, all that awaits you will be heavy, but do not forget the immense protection you will have from Heaven if you are faithful to My Jesus. Be upright and united in joy, love and charity, remember that you will need each other. Now I bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 23)), "My sweet children, of my heart, only your prayers alleviate my pain and the agony of my Son. Beloved children, pray, pray, pray so that priests may make priests live this Christmas with expectation and humility and not that of the pomp of gifts, you still have not learned to live the Mass, but you attend without understanding the true meaning. The war has already begun, often even in families, at least you have the peace that my Son gives with His birth. My loves, when Jesus came into the world He left His commandments to be followed, do not lose yourselves in hearing speakers without faith. Pray for Italy, France and Russia, they will be involved in a great war. Live in joy and expectation. I bless you in the name of the Father of the Son and of the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 24)), "I was born in a humble family full of love, behold, to redeem all, the children of man. I wish, that also in all families there is love and unity, just like my family, they were humble, there was so much love. Love each other, be united, I ask this of all families, everything starts from the family, the first church, be united my brothers, I see the evil that exists in the homes and I am coming. Be united in the families, let me be born where there is love, true love. I bless you all in the name of the Holy Trinity and in the name of my Father, in my name and in the name of the Holy Spirit, Amen. My children, thank you for accepting me." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 26)), "My beloved children, thank you for having responded to my call in your hearts and thank you for being gathered here, you comfort my heart with your prayers. Dear children, when my Son Jesus was born, we were forced to flee, because no one believed and those who knew us avoided us, today as then those who are faithful to Jesus will be shunned and slandered, because in their homes and in their hearts there is no love. At this time Satan is taking possession of my best children, especially in the Church founded on Peter. Please witness your faith with courage, remember that repentance and confession are urgent. I love you, my children. Pray for Italy and especially for Rome, where the pain will always be stronger and more acute. I now bless you in the name of the Father, the Son and the Holy Spirit, Amen." , dataset["text_pl"])
dataset["text_en"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 30)), "My brothers and my people, I ask you, but how great is your love for me and how great is your faith that should not be conditioned by the graces received. Your love, I desire it unconditional and absolute. I hear very often ''Lord, if you love me, why do you take away from me the things that I love the most'' Then I look at you with compassion and in truth I tell you that this is a time of love and great trials and your love should not increase or decrease based on what you have or do not have. Soon you will be judged for love and faith. Pray on your knees and with humility. I now bless you in the name of the Holy Trinity. Amen." , dataset["text_pl"])


dataset["text"] = dataset["text"].str.replace("Amen\"", "Amen.")
dataset["text_en"] = dataset["text_en"].str.replace("Amen\"", "Amen.")



dataset.to_csv("trevignano2017_cleaned.csv", encoding="utf-8", index=False)





