# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np




dataset = pd.read_csv("trevignano_2018.csv", encoding="utf-8")



dataset["author"] = np.where(dataset["text"].str.contains("Il vostro Gesù"), "Jesus Christ", dataset["author"])
dataset["author"] = np.where(dataset["text"].str.contains(" Il Vostro Gesù"), "Jesus Christ", dataset["author"])


dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 3) & (dataset["author"] == "Jesus Christ")), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje kochane dzieci, jakże trudna jest droga, która prowadzi do światła i uświęcenia, ale Ja daję wam siłę, abyście szli naprzód. Nie zatrzymujcie się przed przeszkodami, które będą na tej drodze, która prowadzi do Jezusa. Mówię kapłanom, aby szli za głosem serca i byli uważni na sidła, gdziekolwiek się pojawią. Moje drogie dzieci, wkrótce krzyż pojawi się na niebie i będzie to przed ostrzeżeniem. Miejcie pokój w waszych sercach i zabierzcie go do waszych domów. Teraz błogosławię was w imię Ojca i Syna, i Trójcy Przenajświętszej. Amen Matka Boża powiedziała wtedy: Dzisiaj wiele łask zstąpi na moje dzieci. Podczas objawienia zobaczyłam, że niebieski krzyż stał się czerwony i żarzący.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 13)), "Moje kochane dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Dziś znów jestem wśród was, aby wykrzyczeć moją miłość do was i prosić was, abyście naśladowali mojego Syna Jezusa; błagam was, abyście nie zapomnieli powodu Jego śmierci, wszystkich Jego cierpień, dla waszego zbawienia i dla odkupienia ludzkości. Zły rozpętał się w waszych rodzinach, ale weźcie do rąk różaniec, to jedyna kotwica zbawienia, jaką macie. To moje wezwanie jest pilne, wkrótce usłyszycie dźwięk ostatniej trąby przed przyjściem Jezusa, pamiętajcie dzieci, że On nie przychodzi, aby łączyć, ale aby rozdzielać. Umiłowani moi, módlcie się za te grzeszne Włochy i za Japonię, gdzie wkrótce zadrży ziemia. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 17)), "Umiłowane dzieci, dziękuję wam, że wsłuchujecie się w moje wołanie w waszych sercach. Błogosławione dzieci, część ludzkości ma skamieniałe serce, ponieważ nie ma prawdziwej wiary, nie słucha słowa i nie modli się sercem, lecz tylko z obłudy. W tym początku Wielkiego Postu, pamiętaj dlaczego Jezus umarł, kontempluj Jego krzyż, myśl o przebaczeniu, to musi być twoja Wielkanoc. Słuchajcie moich wezwań, nawracajcie się, kochajcie Tego, który umarł dla waszego zbawienia. Nadejdą najgorsze czasy i kiedy rozpętają się najstraszniejsze trzęsienia ziemi, pamiętajcie, że będzie to znak, że Jezus nadchodzi, wydarzenie to będzie antycypowane przez trzy dni ciemności. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego. (Podczas objawienia Matki Bożej widziałam Jezusa błogosławiącego wszystkich obecnych.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 27)), "Drodzy bracia, jak wielką radość sprawiają mi wasze modlitwy. Udaje im się łagodzić moje rany, które jeszcze dziś palą i krwawią. Otwórzcie wasze serca, módlcie się dużo, a ja będę wam towarzyszył ramię w ramię i pomogę wam pokonać wszystkie przeszkody. Kocham Cię i błagam Cię, nie trać wiary i nie dezorientuj się, wkrótce wszystko stanie się jaśniejsze w Twoich oczach i w końcu szczęście, które poczujesz będzie niewyobrażalne. Teraz błogosławię was w imię Trójcy Przenajświętszej.", dataset["text_pl"])

dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Umiłowane dzieci, dziękuję wam za to, że jesteście tu dziś zgromadzeni. Jak wielką wiarę czuję w waszych sercach i w waszych modlitwach. Nigdy się nie bójcie, chodźcie na spotkania modlitewne, dawajcie świadectwo waszej wiary wszędzie, ewangelizujcie świat, zaczynając od waszych rodzin. Moje małe kwiatuszki, dziękuję wam za to, że zawsze byliście uważni na moje prośby i sugestie, dzisiaj Jezus jest tutaj ze mną i pomimo swoich cierpień kocha was i jest gotowy przebaczyć wam wszystkie grzechy, ponieważ jest miłosierny, ale błagam was, moje dzieci, szczerze wyznajcie grzechy, zwłaszcza śmiertelne, nie czekajcie dłużej. Umiłowane dzieci, przechodzicie teraz przez najwęższą drogę, która doprowadzi was do chwały. Módlcie się za Japonię. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8) & (dataset["author"] == "Holy Mary")), "Umiłowane dzieci, zapalone pochodnie, dziękuję wam, że jesteście zgromadzeni tutaj, w tym domowym kościele. Moi umiłowani, słyszę wreszcie, jak wasze serca biją dla wielkiej Wiary. Ciężkie czasy są przed waszymi oczami, błagam was, abyście nadal tak bardzo się modlili. Pragnę, aby te kręgi modlitewne odbywały się częściej w waszych domach, gdzie jestem i będę zawsze obecna. Moi kochani, przygotujcie się i oczyśćcie na przyjęcie nas. Wyjdźcie do świata, aby ewangelizować, nie stójcie bezczynnie, nie ma już czasu. Łaska i błogosławieństwo mojego Syna zstąpi dziś na was. Módlcie się za Włochy, Hiszpanię, Francję i Anglię. Zostawiam was teraz w pokoju. Błogosławię Cię w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8) & (dataset["author"] == "Jesus Christ")), "Bracia, dziękuję wam, że zgromadziliście się w tym błogosławionym domu, jestem tu wśród was, aby zostawić wam pokój. Dziś jestem bardzo smutny, bardzo smutny, modlę się do mojego Ojca, aby sprawiedliwość Jego nie była gorsza od potopu, od tego, co się stało za dni Noego. Mój Ojciec nie chce mnie już słuchać, wyrządziliście zbyt wiele krzywdy. Bracia, jak ja was kocham! Nie przyjęliście mnie za pierwszym razem, kiedy się urodziłem i nie chcecie mnie przyjąć nawet dzisiaj, kiedy przyjdę po raz drugi. O dzieci, pozostańcie ze mną, nie bójcie się, głoście moje słowo, bądźcie blisko Ewangelii i Eucharystii. Pozostańcie zjednoczeni, błagam was, pozostańcie zjednoczeni. W imię Trójcy Przenajświętszej błogosławię was w imię moje, Ojca mego i Ducha Świętego. Amen", dataset["text_pl"])

dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 10)), "Umiłowane dzieci, dziękuję wam, że wsłuchujecie się w moje wołanie w waszych sercach. Drogie dzieci, przyszłam tutaj nie po to, żeby was straszyć, lecz żeby pomóc wam i waszej duszy. Po tylu latach objawień nadal nie wierzycie w moje orędzia, nie wszyscy zdają sobie sprawę z wielkiej łaski, jaką obdarzył was mój Ojciec. Ukochani moi, wszystkie demony są na ziemi i nie wyobrażacie sobie, ile miejsca w piekle zrobiono dla wszystkich dusz, które popadną w grzech, jest tam ogromna przepaść. Proszę, otwórzcie oczy i nie słuchajcie fałszywego pokoju, bo potężni planują wielką wojnę. Módlcie się, módlcie się, módlcie się. Teraz daję wam moje matczyne błogosławieństwo w imię Ojca i Syna, i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 13)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Drogie dzieci, pamiętajcie, że mój Syn, kiedy zgromadził swoich apostołów, nie powołał doktorów Kościoła, ale ludzi prostych i prawego serca. Dosyć już tego udawania, że w głowach braci są wątpliwości, diabeł bawi się waszymi umysłami i sercami. Pamiętajcie dzieci, wszyscy staniecie przed Bożą sprawiedliwością. Módlcie się, módlcie się, módlcie się dużo, wsłuchujcie się w wiatry wojny. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 24)), "Drogie dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Drogie dzieci, tak jak odczuwam wielką wiarę w waszych sercach, tak też odczuwam wielki chłód serc, które nie wzdragają się przede mną. Arogancja i duma nie pochodzą od Boga. W tym okresie odczujesz ciszę, ale wkrótce wszystko się wyciszy. W tą Wielkanoc będzie wiele znaków, które będą poprzedzać koniec czasu. Chciałbym was zabrać do siebie i w tym celu proszę was o wiele modlitw. Jestem waszą Matką, błogosławię was teraz w imię Ojca i Syna, i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 27)), "Dzieci moje, nie bądźcie dla mnie okrutne, kocham was, pozostańcie zjednoczeni w pokoju, w Słowie i w Ewangelii. Wystarczy, kochajcie Mnie dalej, poddajcie się waszemu Królowi, Ja jestem wszystkim, miłością, początkiem i końcem. Dlaczego chcesz Mnie porzucić, kochaj Moje Rany, Mój Krzyż. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego, dziękuję wam, że mnie przyjęliście, dziękuję wam, moje dzieci. ", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 31)), "Moi ukochani, dzieci mojego serca, czas się kończy. Zwracam się do kapłanów; bądźcie uważni, aby przyjąć jak najwięcej dusz, aby mogły one wejść na drogę świętości. Jest to czas oczyszczenia, by być gotowym na przyjście Jezusa. Dzieci moje, nie bójcie się walczyć z herezją. Szatan, sądząc, że zwyciężył, świętuje z powodu wszystkich dusz, które udało mu się przyciągnąć do siebie. Módlcie się, módlcie się, módlcie się o pokój. Błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])




dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 3)), "Umiłowane dzieci, dziękuję wam za wysłuchanie mojego wezwania w waszych sercach, niech zstąpi na was pokój. Moje dzieci, to jest czas, kiedy zaczyna się prześladowanie, tak jak zdradzili Jezusa, nie rozpoznali i prześladowali Go, tak teraz w czasie Jego powtórnego przyjścia wszystko się powtarza. W Kościele moje dzieci, także te umiłowane, pochylają głowy przed szatanem, błagam was, moje dzieci, módlcie się tak bardzo, aby święci kapłani i prawdziwi pasterze przynieśli słowo, słowo Ewangelii, która jest jedyną prawdą niezmienną przez wieki. Umiłowani moi, ofiarujcie swoje cierpienia, otwórzcie się na Bożą miłość. Ufajcie w Jego miłość i w Jego łaski. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 7)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj zjednoczeni w modlitwie. Drogie dzieci, jak wiele cierpienia jest w waszych sercach, ale to jest droga, aby przyjść do Jezusa. On zawsze trzyma cię za rękę, zwłaszcza gdy patrzy na twoje cierpienie. Mój Syn i ja cierpimy i odczuwamy wasz ból, nie bójcie się moje dzieci, nie jesteście sami, proszę was tylko, abyście się nam całkowicie powierzyli, pamiętajcie, że jesteście na świecie, ale nie jesteście ze świata. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 14)), "Umiłowane dzieci, dziękuję wam, że wsłuchujecie się w moje wołanie w waszych sercach. Umiłowane dzieci, jaki ból mi to sprawia, a szczególnie waszym rodzinom. Teraz, wojna, która właśnie się rozpoczęła, będzie miała konsekwencje na całym świecie, ale dlaczego człowiek trwa w obojętności i nie rozumie jeszcze, że jedynym ratunkiem jest modlitwa! Moi mali, bądźcie zawsze gotowi w nocy, to, co zostało przepowiedziane, ma nadejść, wkrótce nastąpi wniebowzięcie. Teraz potrzebujemy najlepszych dusz, aby mogły one dołączyć do armii zbawienia. Kocham was, moje dzieci, a teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna, i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 17)), "Umiłowane dzieci, dziękuję wam, że jesteście tu zgromadzeni na modlitwie. Wasze dusze łagodzą moje cierpienia, a wasza wiara łagodzi bóle mojego Syna. Umiłowane dzieci, Kościół pozostanie taki, jaki był zawsze, diabeł, który myśli, że może być panem, zostanie wypędzony, tylko dlatego, że dusze dały się porwać pysze i arogancji. Nic nie może być zmienione, ponieważ prawda jest jedna, przedtem, teraz i zawsze. Bądźcie mocni w wierze i przywiązani do jedynej prawdy, którą zostawił wam mój Syn. Kto myśli, że może zmienić wszystko, bluźni przeciwko Bogu. Teraz błogosławię was i wszystkie święte przedmioty w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21) & (dataset["author"] == "Holy Mary")), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj, w tym błogosławionym domu. Dzisiaj jest rocznica mojego przyjścia do mojej ukochanej córki, aby moje przesłania usłyszało jak najwięcej ludzi. Wiedziałam już, że serce tej córki i jej słodkiego męża przełamie wszelkie bariery, szerząc moje przesłanie miłości i pokoju, ponieważ w ich sercach jest miłość i nadzieja. Nadal módlcie się za wszystkich tych, którzy nie wierzą i którzy są daleko od Boga, aby mogli oni być chronieni, a ja wstawiam się przed moim Synem Jezusem, by byli zbawieni. Kocham Cię miłością tak wielką, że nie możesz sobie wyobrazić. Błogosławię Cię w imię Ojca, Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21) & (dataset["author"] == "Jesus Christ")), "Bracia moi, zawsze będę z wami, zstąpi na was moja łaska, miejcie wiarę i nigdy mnie nie opuszczajcie. Kochaj mnie, jak cię kocham. Módl się, abym mógł oczekiwać mojego powrotu. Proszę, małe dzieci, pozostańcie zjednoczeni, teraz daję wam moje błogosławieństwo w imię Ojca, w moje imię i w imię Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 24)), "Drogie dzieci, dziękuję wam za to, że słuchacie wezwania, które jest w waszych sercach. Dzieci moje, zmieńcie swoje życie i nawróćcie się, nie tylko wtedy, gdy odczuwacie ból, ale naprawdę otwórzcie swoje serca na Bożą miłość. Drogie dzieci, sprawiedliwi będą prześladowani i prowokowani nieustannie, ale Ja znam ich serca i dlatego będą chronieni od wszelkiego zła. Dam ci wszystkie siły, ale musisz często przystępować do Eucharystii, być wiernym prawom Pana. Módlcie się za Watykan, wkrótce wydarzy się coś bardzo poważnego. Moje błogosławieństwa zstąpią na was w imię Ojca, Syna i Ducha Świętego, Amen.", dataset["text_pl"])




dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 3)), "Umiłowane dzieci mego serca, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Drogie dzieci, zacznijcie w tym miesiącu poświęcać się mojemu niepokalanemu sercu, tu znajdziecie pokój i moją opiekę. Moi umiłowani, idźcie za moim Synem Jezusem, ponieważ On jest miłością, czystą miłością, On nie przychodzi tylko po to, aby was osądzić, ale aby uczynić nowe niebo i nową ziemię, tę ziemię, która jest teraz najeżona grzechem wojny i 'ja', które nie jest Bogiem. Dzieci, nadal jestem tutaj, aby iść za wami i chronić was; odmawiajcie różaniec, broń, która powstrzymuje zło, to, co rozprzestrzenia się w świecie. Szatan nie zwycięży, a ja zatriumfuję z moimi aniołami. Umiłowani moi, bądźcie wierni prawom Bożym i zawsze bądźcie konsekwentni. Mówcie do Boga, jak do ojca lub najlepszego przyjaciela, nie bójcie się, On słyszy wszystkich, którzy Go wzywają. Módlcie się za Rzym, terroryzm nie będzie długo nadchodził. Teraz udzielam wam mojego Świętego Błogosławieństwa, w imię Ojca, Syna i Ducha Świętego. Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 5)), "Umiłowane dzieci, dziękuję wam za to, że jesteście tutaj na modlitwie. Moi mali, Kościół zawsze pozostanie nienaruszony, nawet jeśli ślepcy będą prowadzić innych ślepców, nikt nigdy nie będzie mógł go tknąć, ponieważ będzie podtrzymywany przez Ducha Świętego. Nigdy tak jak dziś, nie zstąpią na was łaski, aby wszyscy mogli patrzeć oczami dzieci na to, jak dobry i miłosierny jest Bóg. Drogie dzieci, zawsze wzywajcie miłosierdzia. Teraz daję wam moje święte błogosławieństwo, w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 1)), "Umiłowane dzieci, dziękuję wam za wasze modlitwy za was i za wszystkich, którzy będą tworzyć wieczerniki modlitewne i za różańce odmawiane w rodzinach, będę tam i będę błogosławić wszystkich i wstawiać się przez mojego Syna o wszystkie łaski, o które będziecie mnie prosić w tym czasie. Drogie dzieci, zawsze przygotowujcie się, zanim przyjmiecie Eucharystię, tylko po przebaczeniu wszystkiego w waszym sercu. Módlcie się za Chile. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego. Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 8)), "Umiłowane dzieci mojego niepokalanego serca, dziękuję wam, że wsłuchujecie się w moje wołanie w waszych sercach. Moja córko, pragnę, abyś powiedziała kapłanom, aby się nie bali, nadeszły godziny prześladowań, ale wy przylgnijcie do mojego Syna Jezusa i kontynuujcie ewangelizację zawsze w prawdzie. Drogie dzieci, niebo i ziemia wkrótce się połączą i ból zniknie, bo zasmakujecie raju. Kocham was, ponieważ jesteście moimi drogimi dziećmi i moimi zapalonymi lampami, idźcie naprzód i zawsze bądźcie świadkami waszej wiary. Pamiętajmy, że tam gdzie jest Bóg, tam jest miłość, a tam gdzie jest miłość, tam jest i miłosierdzie. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca, Syna i Ducha Świętego, niech zstąpi na was ogień Ducha Świętego. Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 12)), "Moje drogie dzieci, dziękuję wam za to, że jesteście tutaj zgromadzeni na modlitwie. Umiłowani moi, jak wielki zamęt panuje w waszych głowach i sercach, to jest to, co diabeł chce siać, zniszczenie i zamęt, ja natomiast pragnę, abyście trzymali się tylko odmawiania Różańca Świętego, abyście z miłością podchodzili do modlitwy, Eucharystii i spowiedzi do mojego Syna Jezusa. Jestem przy tobie i zawsze będę ci towarzyszyła i trzymała cię za rękę. Pozwól mi towarzyszyć ci! Wkrótce wszystko się zmieni i będziecie mogli być w świetle i zobaczyć prawdziwy Raj. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 19)), "Umiłowane dzieci, dziękuję wam, że wsłuchujecie się w moje wołanie w naszych sercach. Jak wielki smutek widzę w waszych sercach, ale już od dawna przypominam wam, że jest to czas oczyszczenia. Z pewnością wiele będzie waszych cierpień, ale czy zadajecie sobie pytanie, ile Jezus wycierpiał za was? Moi mali, nie bądźcie niespokojni, wkrótce będziecie mogli zakosztować nowego Raju, to co jest napisane musi się wydarzyć przed powrotem Jezusa. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 22)), "Moje kochane dzieci, dziękuję wam, że jesteście tu zgromadzeni na modlitwie. Wiem, jak wiele smutku jest w waszych sercach, znam was wszystkich i znam wasze troski i słabości. Oto jestem tu, aby was pocieszać, prowadzić was i kochać was tak wielką matczyną miłością, że chciałabym tylko widzieć was uśmiechniętych, mających w swoich sercach mojego Syna Jezusa. Moi ukochani, powrót Jezusa jest bliski, przyjmijcie go, bądźcie gotowi i odnajdźcie się na drodze świętości. Diabeł tworzy największy rozłam, jaki kiedykolwiek odczuwał Kościół, ale nie traćcie nadziei, będę z wami, nie zawracajcie w wierze, ale kontynuujcie waszą drogę, dziś silniejsi niż przedtem. Kocham Cię i błogosławię Cię, w imię Ojca, Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 26)), "Umiłowane dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Ukochana córko, czasami potrzebna jest cisza i medytacja, Ja jestem zawsze z tobą. Moja córko, nadejdzie dzień, kiedy każdy człowiek będzie kochał mojego Syna, krzycząc: 'Ty jesteś naszym Królem!', ale jeśli to się nie stanie wkrótce, nic nie zostanie przyznane, ponieważ fałszywi pokutnicy odczują tylko Boską sprawiedliwość. Otwórzcie wasze serca na miłość mojego Syna, bo wszystko przyspiesza, bądźcie gotowi. Drogie dzieci, wkrótce zostaniecie zabrani i osłonięci przez mój błogosławiony płaszcz, który już jest na ziemi. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 29)), "Moi bracia, dziękuję wam za wysłuchanie wezwania do odmawiania Różańca Świętego. Zapraszam do refleksji. Kiedy Moja Matka prosi was, abyście byli gotowi na Moje Powtórne Przyjście, często myślicie: 'Ale ja się modlę!' Zróbcie rachunek sumienia. Jak często przynosisz mi swoje radości i smutki, jak często dziękujesz mi za piękne rzeczy, które ci daję? Czy zastanawiasz się, czy osądziłeś swoich braci niesprawiedliwie? Ile dobrych uczynków dokonaliście w swoim życiu i ile uczynków miłosierdzia? Ile dusz przyprowadziłeś do mnie, wyrywając je od diabła? Bracia i siostry, to są powody, dla których będziecie sądzeni; wiedzcie, że ci, którzy bluźnią, nigdy nie ujrzą mojego oblicza. Bądźcie zjednoczeni i módlcie się za Włochy, bo ich cierpienia będą wielkie, nawet natura zbuntuje się przeciwko człowiekowi. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])




dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 2)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj, zgromadzeni na modlitwie. Drogie dzieci, ja, wasza matka, proszę was, abyście nie byli zdezorientowani; Duch Święty zstąpi na was, abyście mieli rozeznanie, szczególnie w Kościele. Ach, moje kochane dzieci, ileż prześladowań i ileż bólu wywołują one w moim sercu. Strzeżcie się, Moje dzieci, oni również będą posługiwać się Moim wizerunkiem, podnosząc Mnie przed wiernymi, aby uwierzyli, że wszystko trwa nadal, ale czasami zwodzą was, ponieważ ich zachowanie poza Kościołem jest dalekie od Słowa Bożego. Umiłowani moi, płaczę z powodu tego, co was czeka, mój Syn, gdyby powrócił w ciele, zostałby ponownie ukrzyżowany, ale tylko nieliczni ujrzą Jego Święte Oblicze. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 3)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Niektórzy z was potrzebowali czasu, ale teraz jesteście tutaj pod moim błogosławionym płaszczem. Drogie kochane dzieci, dziś jest bardzo szczególny dzień i proszę was, abyście trwali przy moim Synu i Jego Ciele, często przystępujcie do Eucharystii, a zobaczycie, jak zstąpią na was łaski, On będzie mówił do waszego serca, podążając za wami dzień po dniu, tak że nie będziecie już mogli się bez Niego obejść, słuchając pokoju, który pozostawi w waszych sercach. Moje kochane dzieci, nie rozpaczajcie, aniołowie są zjednoczeni ze świętymi i z tymi, którzy wstąpili do Nieba w świętości, aby walczyć w tej wojnie przeciwko diabłu. Moje dzieci, nie ma już czasu, nawróćcie się i otwórzcie wasze serca na miłość. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 5)), "Droga córko, dziękuję ci, moje matczyne serce pragnie, aby moje dzieci rozpalały ducha, a nie umysł, jednoczyły się w imię Jezusa i tworzyły wieczerniki modlitwy, kocham was wszystkich, ponieważ wszyscy jesteście moimi dziećmi. Mój mały, nie bój się oczyszczeń, bo one służą temu, by doprowadzić cię tam, gdzie jest tylko pokój i zgoda, bądźcie zawsze wierni Ewangelii i miłòujcie się jak bracia. Teraz daję wam moje matczyne błogosławieństwo, w imię Ojca, Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 9)), "Drogie dzieci, dziękuję wam za to, że słuchacie wezwania, które jest w waszych sercach. Umiłowani moi, teraz otwierają się niebiosa, aby zjednoczyć się z ziemią. Krótkie są czasy oczekiwania i wkrótce wszyscy ujrzycie Bożą chwałę. Dlatego błagam was, proście o Boże przebaczenie. Jeśli twoje 'tak' jest szczere, na pewno zostanie ci wybaczone i zstąpi na ciebie całe Boże miłosierdzie. Przebacz, a będzie ci przebaczone. Bądźcie gotowi patrzeć na znaki nieba, nie bądźcie ślepi i nie stójcie ze skrzyżowanymi rękami nic nie robiąc. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 12)), "Drogie dzieci, dziękuję wam, że jesteście tutaj zgromadzeni na modlitwie. Umiłowani moi, diabeł jest bardzo przebiegły, przywiązuje was do rzeczy ziemskich, do wszelkiego rodzaju przyjemności. Dzieci moje, bądźcie czujne, zwłaszcza na zazdrość i zawiść, bo on prowokuje wasze reakcje, aby nastawić was przeciwko sobie i spowodować podział. Moi mali, strzeżcie się fałszywego pokoju, trzęsienia ziemi będą następowały jedno po drugim, a przyroda, zwłaszcza morze, będzie się buntować. Módlcie się za Rosję. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen. ", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 16)), "Drogie dzieci, dziękuję wam, że jesteście tutaj zgromadzeni na modlitwie. Dzieci mojego serca, módlcie się o nawrócenia, zwłaszcza moich dzieci konsekrowanych, od pierwszego do ostatniego. Niestety, zawsze szukają naukowych wyjaśnień dla znaków nieba, ale kto otworzy swoje serce oczami ducha, ten zrozumie. Ja, wasza Matka, wciąż tu jestem, ponieważ Ojciec, który jest w Niebie, chce, aby wszyscy zostali zbawieni i kocha wszystkich wierzących i niewierzących, nawet jeśli nie ma zbyt wiele miłości do Niego. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego. Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 19)), "Drogie dzieci, dziękuję wam za wasze modlitwy i za waszą wiarę. Umiłowani moi, nie gniewajcie się, nie bądźcie zawiedzeni, kiedy mówią o was źle, kiedy jesteście wyśmiewani, a wszystko to w imię Jezusa. Ja nie jestem tu po to, aby wzbudzać strach w moich dzieciach, ale aby ostrzec je przed niebezpieczeństwami, które na nie czyhają. Wiara i modlitwa łagodzą i spowalniają wydarzenia, gromadzą jak najwięcej dusz i prowadzą je do nawrócenia. Módlcie się za Hiszpanię i za tych wszystkich, którzy nie wierzą. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 23)), "Moi bracia, dziękuję wam za modlitwy i odmawianie Różańca Świętego, który jest bronią odpierającą zło. Moi drodzy bracia, pomimo ciągłej obecności mojej Najświętszej Matki, pomimo znaków, które wam daję, łask, które otrzymujecie i pomimo wszystkiego, dlaczego wielu wciąż nie otwiera swoich serc na moją miłość, na moją łaskę i na moje miłosierdzie? Chcę wszystkich zabrać do Mojego Raju, dlatego proszę was teraz, abyście wyznali każdy grzech, zwłaszcza ciężki, nie powtarzając go nigdy, abym mógł wam przebaczyć. Ja, wasz Jezus, daję wam całe Moje Miłosierdzie. Bądźcie żywi w wierze i dawajcie świadectwo. Kochajcie mój krzyż, nawróćcie się i przyjdźcie do mnie, ja tylko czekam na wasze TAK i zawsze będę obok was w waszym życiu. Bądźcie gotowi na nowe Zesłanie Ducha Świętego. Teraz błogosławię was w imię Ojca, w imię moje i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 26)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Droga córko, niestety czas ucisku i prawdziwego prześladowania dla ciebie i twoich braci jeszcze naprawdę nie nadszedł. Odbierane jest wam wszystko, co cenicie, ale musicie się cieszyć, nie pozwólcie, by ogarnął was ból. Wkrótce wasz Zbawiciel przyjdzie między was, aby uratować was od przebiegłości szatana. Moi mali, patrzcie na znaki, wkrótce nawet księżyc nie będzie już dawał swego światła. Módlcie się, módlcie się, módlcie się, nie bójcie się, wzywajcie mnie, a ja zawsze będę was chronił. Czytajcie Ewangelię i zapowiadajcie przyjście Jezusa. Teraz daję wam moje matczyne błogosławieństwo, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 30)), "Drodzy bracia, dziękuję wam za to, że zgromadziliście się na modlitwie. Jestem tutaj, jestem wśród was, proszę was, weźcie mnie za rękę i idźcie za mną, nie pytając wiele, nie zadając pytań, pamiętajcie, że to jest prawdziwa wiara. Ja jestem prawdą, drogą i życiem. Kochaj mnie tak, jak ja kocham ciebie. Wierzący i niewierzący, jestem tu z wezwaniem do zbawienia, 'Ratujcie się', wróćcie na czas, nadejdzie dzień, kiedy będziecie razem ze Mną, a Ja czekam na wasze serce, otwórzcie je, ileż miłości pragnę dać! Pamiętajcie zawsze, aby postępować zgodnie z Ewangelią, bądźcie mocni w Moich słowach, a przede wszystkim głoście prawdę bez lęku, Ja zawsze będę z wami. A teraz błogosławię was w imię Ojca, w imię moje i Ducha Świętego, Amen.", dataset["text_pl"])



dataset["text_pl"] = np.where(dataset["text_pl"] == "x", "", dataset["text_en"])








# SPELLING FIX
dataset["text_pl"] = dataset["text_pl"].str.replace("aa", "a")
dataset["text_pl"] = dataset["text_pl"].str.replace("Ojca Syna i Ducha Świętego", "Ojca i Syna i Ducha Świętego")
dataset["text_pl"] = dataset["text_pl"].str.replace("niebawem przybędę, jestem gotowa", "niebawem przybędę, jestem gotowy")
dataset["text_pl"] = dataset["text_pl"].str.replace("przygotował dla was mój Ojciec, kochać się, kochać", "przygotował dla was, kocham was, kocham was wszystkich")
dataset["text_pl"] = dataset["text_pl"].str.replace("Kochajcie się bardziej niż własne dzieci", "Kochajcie siebie nawzajem bardziej niż własne dzieci")
dataset["text_pl"] = dataset["text_pl"].str.replace("ale wy z wiarą wygracie całą wieczność na całe życie", "ale wy przez swoją wiarę zdobędziecie życie wieczne")
dataset["text_pl"] = dataset["text_pl"].str.replace("zostawiam ci spokój", "zostawiam ci pokój")
dataset["text_pl"] = dataset["text_pl"].str.replace("twoje zbawienie wkrótce nadejdzie ze mną chwalebne, uśmiechnij się i raduj", "twoje zbawienie wkrótce będzie ze mną w chwale, uśmiechnij się i raduj")
dataset["text_pl"] = dataset["text_pl"].str.replace("Mój Ojciec posyła mnie po zbawienie ludzi, proszę, nie myśl za dużo, nigdy nie zrozumiecie planów mego Ojca", "Mój Ojciec posyła mnie dla zbawienia ludzkości, proszę nie rozumujcie za bardzo, nigdy nie zrozumiecie planów mojego Ojca")
dataset["text_pl"] = dataset["text_pl"].str.replace("Dzięki za powitanie mnie", "Dziękuję, że mnie przyjęliście")
dataset["text_pl"] = dataset["text_pl"].str.replace("I Eucharystii", "i Eucharystii")
dataset["text_pl"] = dataset["text_pl"].str.replace("a co nie\.\.", "a co nie.")
dataset["text_pl"] = dataset["text_pl"].str.replace("teraz w niektórych kościołach mój Syn zniknął", "teraz mój Syn zniknął w niektórych kościołach")
dataset["text_pl"] = dataset["text_pl"].str.replace("znaki z nieba", "znaki z Nieba")
dataset["text_pl"] = dataset["text_pl"].str.replace("ale dlaczego nie powierzysz mi wszystkiego", "ale dlaczego nie ufasz mi we wszystkim")
dataset["text_pl"] = dataset["text_pl"].str.replace("Boga\.Zaczęła", "Boga. Rozpoczęła")
dataset["text_pl"] = dataset["text_pl"].str.replace("Drogie dzieci, dziękujemy, że jesteście tu zgromadzeni", "Drogie dzieci, dziękuję, że tu jesteście")
dataset["text_pl"] = dataset["text_pl"].str.replace("Zapraszam do spojrzenia na znaki, które przyjdą z nieba, dzięki którym zrozumiecie wiele rzeczy", "Zachęcam was, abyście patrzyli na znaki, które przyjdą z nieba, dzięki którym zrozumiecie wiele rzeczy")
dataset["text_pl"] = dataset["text_pl"].str.replace("mego wezwania", "mojego wezwania")
dataset["text_pl"] = dataset["text_pl"].str.replace("trudna droga, na której będziecie się śmiać i wielu odejdzie", "trudna droga, na której zostaniecie wyśmiani i wielu odejdzie")
dataset["text_pl"] = dataset["text_pl"].str.replace("aniołowie podziemia są na ziemi, by was przebiegłością zabrać, bądźcie ostrożni", "anioły podziemia są na ziemi, aby cię porwać podstępem, strzeżcie się")
dataset["text_pl"] = dataset["text_pl"].str.replace("każdego dnia łączę się z różańcem świętym, aby demony mogły zostać osłabione", "zjednoczcie się z Różańcem Świętym każdego dnia, aby osłabić demony")
dataset["text_pl"] = dataset["text_pl"].str.replace("ale daję wam siłę, by iść naprzód", "ale ja daję wam siłę, by iść naprzód")
dataset["text_pl"] = dataset["text_pl"].str.replace(" jakie napotkają na tej drodze", " jakie napotkają was na tej drodze")
dataset["text_pl"] = dataset["text_pl"].str.replace("wkrótce krzyż pojawi się w niebie i będzie przed ostrzeżeniem", "wkrótce krzyż pojawi się na niebie i będzie przed Ostrzeżeniem")
dataset["text_pl"] = dataset["text_pl"].str.replace("Miej pokój w swoich sercach i przynieś go do swoich domów", "Miejcie pokój w waszych sercach i przynieście go do swoich domów")
dataset["text_pl"] = dataset["text_pl"].str.replace("Ojca Syna", "Ojca i Syna")
dataset["text_pl"] = dataset["text_pl"].str.replace("Amen Wtedy", "Amen. Wtedy")
dataset["text_pl"] = dataset["text_pl"].str.replace("dzieci \”\. ", "dzieci. ")
dataset["text_pl"] = dataset["text_pl"].str.replace("Podczas objawienia zobaczyłam, jak niebieski krzyż świeci na czerwono", "Podczas objawienia zobaczyłam, że niebieski krzyż stał się czerwony i żarzący")







dataset.to_csv("trevignano2018.csv", index=False, encoding="utf-8")
dataset.to_json("trevignano2018.json",orient="records")






















