# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np




dataset = pd.read_csv("trevignano_2018.csv", encoding="utf-8")



dataset["author"] = np.where(dataset["text"].str.contains("Il vostro Gesù"), "Jesus Christ", dataset["author"])
dataset["author"] = np.where(dataset["text"].str.contains(" Il Vostro Gesù"), "Jesus Christ", dataset["author"])


dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 3) & (dataset["author"] == "Jesus Christ")), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje kochane dzieci, jakże trudna jest droga, która prowadzi do światła i uświęcenia, ale Ja daję wam siłę, abyście szli naprzód. Nie zatrzymujcie się przed przeszkodami, które będą na tej drodze, która prowadzi do Jezusa. Mówię kapłanom, aby szli za głosem serca i byli uważni na sidła, gdziekolwiek się pojawią. Moje drogie dzieci, wkrótce krzyż pojawi się na niebie i będzie to przed ostrzeżeniem. Miejcie pokój w waszych sercach i zabierzcie go do waszych domów. Teraz błogosławię was w imię Ojca i Syna, i Trójcy Przenajświętszej. Amen Matka Boża powiedziała wtedy: Dzisiaj wiele łask zstąpi na moje dzieci. Podczas objawienia zobaczyłam, że niebieski krzyż stał się czerwony i żarzący.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 13)), "Moje kochane dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Dziś znów jestem wśród was, aby wykrzyczeć moją miłość do was i prosić was, abyście naśladowali mojego Syna Jezusa; błagam was, abyście nie zapomnieli powodu Jego śmierci, wszystkich Jego cierpień, dla waszego zbawienia i dla odkupienia ludzkości. Zły rozpętał się w waszych rodzinach, ale weźcie do rąk różaniec, to jedyna kotwica zbawienia, jaką macie. To moje wezwanie jest pilne, wkrótce usłyszycie dźwięk ostatniej trąby przed przyjściem Jezusa, pamiętajcie dzieci, że On nie przychodzi, aby łączyć, ale aby rozdzielać. Umiłowani moi, módlcie się za te grzeszne Włochy i za Japonię, gdzie wkrótce zadrży ziemia. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 17)), "Umiłowane dzieci, dziękuję wam, że wsłuchujecie się w moje wołanie w waszych sercach. Błogosławione dzieci, część ludzkości ma skamieniałe serce, ponieważ nie ma prawdziwej wiary, nie słucha słowa i nie modli się sercem, lecz tylko z obłudy. W tym początku Wielkiego Postu, pamiętaj dlaczego Jezus umarł, kontempluj Jego krzyż, myśl o przebaczeniu, to musi być twoja Wielkanoc. Słuchajcie moich wezwań, nawracajcie się, kochajcie Tego, który umarł dla waszego zbawienia. Nadejdą najgorsze czasy i kiedy rozpętają się najstraszniejsze trzęsienia ziemi, pamiętajcie, że będzie to znak, że Jezus nadchodzi, wydarzenie to będzie antycypowane przez trzy dni ciemności. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego. (Podczas objawienia Matki Bożej widziałam Jezusa błogosławiącego wszystkich obecnych.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 27)), "Drodzy bracia, jak wielką radość sprawiają mi wasze modlitwy. Udaje im się łagodzić moje rany, które jeszcze dziś palą i krwawią. Otwórzcie wasze serca, módlcie się dużo, a ja będę wam towarzyszył ramię w ramię i pomogę wam pokonać wszystkie przeszkody. Kocham Cię i błagam Cię, nie trać wiary i nie dezorientuj się, wkrótce wszystko stanie się jaśniejsze w Twoich oczach i w końcu szczęście, które poczujesz będzie niewyobrażalne. Teraz błogosławię was w imię Trójcy Przenajświętszej.", dataset["text_pl"])

dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Umiłowane dzieci, dziękuję wam za to, że jesteście tu dziś zgromadzeni. Jak wielką wiarę czuję w waszych sercach i w waszych modlitwach. Nigdy się nie bójcie, chodźcie na spotkania modlitewne, dawajcie świadectwo waszej wiary wszędzie, ewangelizujcie świat, zaczynając od waszych rodzin. Moje małe kwiatuszki, dziękuję wam za to, że zawsze byliście uważni na moje prośby i sugestie, dzisiaj Jezus jest tutaj ze mną i pomimo swoich cierpień kocha was i jest gotowy przebaczyć wam wszystkie grzechy, ponieważ jest miłosierny, ale błagam was, moje dzieci, szczerze wyznajcie grzechy, zwłaszcza śmiertelne, nie czekajcie dłużej. Umiłowane dzieci, przechodzicie teraz przez najwęższą drogę, która doprowadzi was do chwały. Módlcie się za Japonię. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8) & (dataset["author"] == "Holy Mary")), "Umiłowane dzieci, zapalone pochodnie, dziękuję wam, że jesteście zgromadzeni tutaj, w tym domowym kościele. Moi umiłowani, słyszę wreszcie, jak wasze serca biją dla wielkiej Wiary. Ciężkie czasy są przed waszymi oczami, błagam was, abyście nadal tak bardzo się modlili. Pragnę, aby te kręgi modlitewne odbywały się częściej w waszych domach, gdzie jestem i będę zawsze obecna. Moi kochani, przygotujcie się i oczyśćcie na przyjęcie nas. Wyjdźcie do świata, aby ewangelizować, nie stójcie bezczynnie, nie ma już czasu. Łaska i błogosławieństwo mojego Syna zstąpi dziś na was. Módlcie się za Włochy, Hiszpanię, Francję i Anglię. Zostawiam was teraz w pokoju. Błogosławię Cię w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8) & (dataset["author"] == "Jesus Christ")), "Bracia, dziękuję wam, że zgromadziliście się w tym błogosławionym domu, jestem tu wśród was, aby zostawić wam pokój. Dziś jestem bardzo smutny, bardzo smutny, modlę się do mojego Ojca, aby sprawiedliwość Jego nie była gorsza od potopu, od tego, co się stało za dni Noego. Mój Ojciec nie chce mnie już słuchać, wyrządziliście zbyt wiele krzywdy. Bracia, jak ja was kocham! Nie przyjęliście mnie za pierwszym razem, kiedy się urodziłem i nie chcecie mnie przyjąć nawet dzisiaj, kiedy przyjdę po raz drugi. O dzieci, pozostańcie ze mną, nie bójcie się, głoście moje słowo, bądźcie blisko Ewangelii i Eucharystii. Pozostańcie zjednoczeni, błagam was, pozostańcie zjednoczeni. W imię Trójcy Przenajświętszej błogosławię was w imię moje, Ojca mego i Ducha Świętego. Amen", dataset["text_pl"])

dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 10)), "Umiłowane dzieci, dziękuję wam, że wsłuchujecie się w moje wołanie w waszych sercach. Drogie dzieci, przyszłam tutaj nie po to, żeby was straszyć, lecz żeby pomóc wam i waszej duszy. Po tylu latach objawień nadal nie wierzycie w moje orędzia, nie wszyscy zdają sobie sprawę z wielkiej łaski, jaką obdarzył was mój Ojciec. Ukochani moi, wszystkie demony są na ziemi i nie wyobrażacie sobie, ile miejsca w piekle zrobiono dla wszystkich dusz, które popadną w grzech, jest tam ogromna przepaść. Proszę, otwórzcie oczy i nie słuchajcie fałszywego pokoju, bo potężni planują wielką wojnę. Módlcie się, módlcie się, módlcie się. Teraz daję wam moje matczyne błogosławieństwo w imię Ojca i Syna, i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 13)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Drogie dzieci, pamiętajcie, że mój Syn, kiedy zgromadził swoich apostołów, nie powołał doktorów Kościoła, ale ludzi prostych i prawego serca. Dosyć już tego udawania, że w głowach braci są wątpliwości, diabeł bawi się waszymi umysłami i sercami. Pamiętajcie dzieci, wszyscy staniecie przed Bożą sprawiedliwością. Módlcie się, módlcie się, módlcie się dużo, wsłuchujcie się w wiatry wojny. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 24)), "Drogie dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Drogie dzieci, tak jak odczuwam wielką wiarę w waszych sercach, tak też odczuwam wielki chłód serc, które nie wzdragają się przede mną. Arogancja i duma nie pochodzą od Boga. W tym okresie odczujesz ciszę, ale wkrótce wszystko się wyciszy. W tą Wielkanoc będzie wiele znaków, które będą poprzedzać koniec czasu. Chciałbym was zabrać do siebie i w tym celu proszę was o wiele modlitw. Jestem waszą Matką, błogosławię was teraz w imię Ojca i Syna, i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 27)), "Dzieci moje, nie bądźcie dla mnie okrutne, kocham was, pozostańcie zjednoczeni w pokoju, w Słowie i w Ewangelii. Wystarczy, kochajcie Mnie dalej, poddajcie się waszemu Królowi, Ja jestem wszystkim, miłością, początkiem i końcem. Dlaczego chcesz Mnie porzucić, kochaj Moje Rany, Mój Krzyż. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego, dziękuję wam, że mnie przyjęliście, dziękuję wam, moje dzieci. ", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 31)), "Moi ukochani, dzieci mojego serca, czas się kończy. Zwracam się do kapłanów; bądźcie uważni, aby przyjąć jak najwięcej dusz, aby mogły one wejść na drogę świętości. Jest to czas oczyszczenia, by być gotowym na przyjście Jezusa. Dzieci moje, nie bójcie się walczyć z herezją. Szatan, sądząc, że zwyciężył, świętuje z powodu wszystkich dusz, które udało mu się przyciągnąć do siebie. Módlcie się, módlcie się, módlcie się o pokój. Błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])




dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 3)), "Umiłowane dzieci, dziękuję wam za wysłuchanie mojego wezwania w waszych sercach, niech zstąpi na was pokój. Moje dzieci, to jest czas, kiedy zaczyna się prześladowanie, tak jak zdradzili Jezusa, nie rozpoznali i prześladowali Go, tak teraz w czasie Jego powtórnego przyjścia wszystko się powtarza. W Kościele moje dzieci, także te umiłowane, pochylają głowy przed szatanem, błagam was, moje dzieci, módlcie się tak bardzo, aby święci kapłani i prawdziwi pasterze przynieśli słowo, słowo Ewangelii, która jest jedyną prawdą niezmienną przez wieki. Umiłowani moi, ofiarujcie swoje cierpienia, otwórzcie się na Bożą miłość. Ufajcie w Jego miłość i w Jego łaski. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 7)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj zjednoczeni w modlitwie. Drogie dzieci, jak wiele cierpienia jest w waszych sercach, ale to jest droga, aby przyjść do Jezusa. On zawsze trzyma cię za rękę, zwłaszcza gdy patrzy na twoje cierpienie. Mój Syn i ja cierpimy i odczuwamy wasz ból, nie bójcie się moje dzieci, nie jesteście sami, proszę was tylko, abyście się nam całkowicie powierzyli, pamiętajcie, że jesteście na świecie, ale nie jesteście ze świata. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 14)), "Umiłowane dzieci, dziękuję wam, że wsłuchujecie się w moje wołanie w waszych sercach. Umiłowane dzieci, jaki ból mi to sprawia, a szczególnie waszym rodzinom. Teraz, wojna, która właśnie się rozpoczęła, będzie miała konsekwencje na całym świecie, ale dlaczego człowiek trwa w obojętności i nie rozumie jeszcze, że jedynym ratunkiem jest modlitwa! Moi mali, bądźcie zawsze gotowi w nocy, to, co zostało przepowiedziane, ma nadejść, wkrótce nastąpi wniebowzięcie. Teraz potrzebujemy najlepszych dusz, aby mogły one dołączyć do armii zbawienia. Kocham was, moje dzieci, a teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna, i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 17)), "Umiłowane dzieci, dziękuję wam, że jesteście tu zgromadzeni na modlitwie. Wasze dusze łagodzą moje cierpienia, a wasza wiara łagodzi bóle mojego Syna. Umiłowane dzieci, Kościół pozostanie taki, jaki był zawsze, diabeł, który myśli, że może być panem, zostanie wypędzony, tylko dlatego, że dusze dały się porwać pysze i arogancji. Nic nie może być zmienione, ponieważ prawda jest jedna, przedtem, teraz i zawsze. Bądźcie mocni w wierze i przywiązani do jedynej prawdy, którą zostawił wam mój Syn. Kto myśli, że może zmienić wszystko, bluźni przeciwko Bogu. Teraz błogosławię was i wszystkie święte przedmioty w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21) & (dataset["author"] == "Holy Mary")), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj, w tym błogosławionym domu. Dzisiaj jest rocznica mojego przyjścia do mojej ukochanej córki, aby moje przesłania usłyszało jak najwięcej ludzi. Wiedziałam już, że serce tej córki i jej słodkiego męża przełamie wszelkie bariery, szerząc moje przesłanie miłości i pokoju, ponieważ w ich sercach jest miłość i nadzieja. Nadal módlcie się za wszystkich tych, którzy nie wierzą i którzy są daleko od Boga, aby mogli oni być chronieni, a ja wstawiam się przed moim Synem Jezusem, by byli zbawieni. Kocham Cię miłością tak wielką, że nie możesz sobie wyobrazić. Błogosławię Cię w imię Ojca, Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21) & (dataset["author"] == "Jesus Christ")), "Bracia moi, zawsze będę z wami, zstąpi na was moja łaska, miejcie wiarę i nigdy mnie nie opuszczajcie. Kochaj mnie, jak cię kocham. Módl się, abym mógł oczekiwać mojego powrotu. Proszę, małe dzieci, pozostańcie zjednoczeni, teraz daję wam moje błogosławieństwo w imię Ojca, w moje imię i w imię Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 24)), "Drogie dzieci, dziękuję wam za to, że słuchacie wezwania, które jest w waszych sercach. Dzieci moje, zmieńcie swoje życie i nawróćcie się, nie tylko wtedy, gdy odczuwacie ból, ale naprawdę otwórzcie swoje serca na Bożą miłość. Drogie dzieci, sprawiedliwi będą prześladowani i prowokowani nieustannie, ale Ja znam ich serca i dlatego będą chronieni od wszelkiego zła. Dam ci wszystkie siły, ale musisz często przystępować do Eucharystii, być wiernym prawom Pana. Módlcie się za Watykan, wkrótce wydarzy się coś bardzo poważnego. Moje błogosławieństwa zstąpią na was w imię Ojca, Syna i Ducha Świętego, Amen.", dataset["text_pl"])




dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 3)), "Umiłowane dzieci mego serca, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Drogie dzieci, zacznijcie w tym miesiącu poświęcać się mojemu niepokalanemu sercu, tu znajdziecie pokój i moją opiekę. Moi umiłowani, idźcie za moim Synem Jezusem, ponieważ On jest miłością, czystą miłością, On nie przychodzi tylko po to, aby was osądzić, ale aby uczynić nowe niebo i nową ziemię, tę ziemię, która jest teraz najeżona grzechem wojny i 'ja', które nie jest Bogiem. Dzieci, nadal jestem tutaj, aby iść za wami i chronić was; odmawiajcie różaniec, broń, która powstrzymuje zło, to, co rozprzestrzenia się w świecie. Szatan nie zwycięży, a ja zatriumfuję z moimi aniołami. Umiłowani moi, bądźcie wierni prawom Bożym i zawsze bądźcie konsekwentni. Mówcie do Boga, jak do ojca lub najlepszego przyjaciela, nie bójcie się, On słyszy wszystkich, którzy Go wzywają. Módlcie się za Rzym, terroryzm nie będzie długo nadchodził. Teraz udzielam wam mojego Świętego Błogosławieństwa, w imię Ojca, Syna i Ducha Świętego. Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 5)), "Umiłowane dzieci, dziękuję wam za to, że jesteście tutaj na modlitwie. Moi mali, Kościół zawsze pozostanie nienaruszony, nawet jeśli ślepcy będą prowadzić innych ślepców, nikt nigdy nie będzie mógł go tknąć, ponieważ będzie podtrzymywany przez Ducha Świętego. Nigdy tak jak dziś, nie zstąpią na was łaski, aby wszyscy mogli patrzeć oczami dzieci na to, jak dobry i miłosierny jest Bóg. Drogie dzieci, zawsze wzywajcie miłosierdzia. Teraz daję wam moje święte błogosławieństwo, w imię Ojca i Syna i Ducha Świętego. Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 1)), "Umiłowane dzieci, dziękuję wam za wasze modlitwy za was i za wszystkich, którzy będą tworzyć wieczerniki modlitewne i za różańce odmawiane w rodzinach, będę tam i będę błogosławić wszystkich i wstawiać się przez mojego Syna o wszystkie łaski, o które będziecie mnie prosić w tym czasie. Drogie dzieci, zawsze przygotowujcie się, zanim przyjmiecie Eucharystię, tylko po przebaczeniu wszystkiego w waszym sercu. Módlcie się za Chile. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego. Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 8)), "Umiłowane dzieci mojego niepokalanego serca, dziękuję wam, że wsłuchujecie się w moje wołanie w waszych sercach. Moja córko, pragnę, abyś powiedziała kapłanom, aby się nie bali, nadeszły godziny prześladowań, ale wy przylgnijcie do mojego Syna Jezusa i kontynuujcie ewangelizację zawsze w prawdzie. Drogie dzieci, niebo i ziemia wkrótce się połączą i ból zniknie, bo zasmakujecie raju. Kocham was, ponieważ jesteście moimi drogimi dziećmi i moimi zapalonymi lampami, idźcie naprzód i zawsze bądźcie świadkami waszej wiary. Pamiętajmy, że tam gdzie jest Bóg, tam jest miłość, a tam gdzie jest miłość, tam jest i miłosierdzie. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca, Syna i Ducha Świętego, niech zstąpi na was ogień Ducha Świętego. Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 12)), "Moje drogie dzieci, dziękuję wam za to, że jesteście tutaj zgromadzeni na modlitwie. Umiłowani moi, jak wielki zamęt panuje w waszych głowach i sercach, to jest to, co diabeł chce siać, zniszczenie i zamęt, ja natomiast pragnę, abyście trzymali się tylko odmawiania Różańca Świętego, abyście z miłością podchodzili do modlitwy, Eucharystii i spowiedzi do mojego Syna Jezusa. Jestem przy tobie i zawsze będę ci towarzyszyła i trzymała cię za rękę. Pozwól mi towarzyszyć ci! Wkrótce wszystko się zmieni i będziecie mogli być w świetle i zobaczyć prawdziwy Raj. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 19)), "Umiłowane dzieci, dziękuję wam, że wsłuchujecie się w moje wołanie w naszych sercach. Jak wielki smutek widzę w waszych sercach, ale już od dawna przypominam wam, że jest to czas oczyszczenia. Z pewnością wiele będzie waszych cierpień, ale czy zadajecie sobie pytanie, ile Jezus wycierpiał za was? Moi mali, nie bądźcie niespokojni, wkrótce będziecie mogli zakosztować nowego Raju, to co jest napisane musi się wydarzyć przed powrotem Jezusa. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 22)), "Moje kochane dzieci, dziękuję wam, że jesteście tu zgromadzeni na modlitwie. Wiem, jak wiele smutku jest w waszych sercach, znam was wszystkich i znam wasze troski i słabości. Oto jestem tu, aby was pocieszać, prowadzić was i kochać was tak wielką matczyną miłością, że chciałabym tylko widzieć was uśmiechniętych, mających w swoich sercach mojego Syna Jezusa. Moi ukochani, powrót Jezusa jest bliski, przyjmijcie go, bądźcie gotowi i odnajdźcie się na drodze świętości. Diabeł tworzy największy rozłam, jaki kiedykolwiek odczuwał Kościół, ale nie traćcie nadziei, będę z wami, nie zawracajcie w wierze, ale kontynuujcie waszą drogę, dziś silniejsi niż przedtem. Kocham Cię i błogosławię Cię, w imię Ojca, Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 26)), "Umiłowane dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Ukochana córko, czasami potrzebna jest cisza i medytacja, Ja jestem zawsze z tobą. Moja córko, nadejdzie dzień, kiedy każdy człowiek będzie kochał mojego Syna, krzycząc: 'Ty jesteś naszym Królem!', ale jeśli to się nie stanie wkrótce, nic nie zostanie przyznane, ponieważ fałszywi pokutnicy odczują tylko Boską sprawiedliwość. Otwórzcie wasze serca na miłość mojego Syna, bo wszystko przyspiesza, bądźcie gotowi. Drogie dzieci, wkrótce zostaniecie zabrani i osłonięci przez mój błogosławiony płaszcz, który już jest na ziemi. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 29)), "Moi bracia, dziękuję wam za wysłuchanie wezwania do odmawiania Różańca Świętego. Zapraszam do refleksji. Kiedy Moja Matka prosi was, abyście byli gotowi na Moje Powtórne Przyjście, często myślicie: 'Ale ja się modlę!' Zróbcie rachunek sumienia. Jak często przynosisz mi swoje radości i smutki, jak często dziękujesz mi za piękne rzeczy, które ci daję? Czy zastanawiasz się, czy osądziłeś swoich braci niesprawiedliwie? Ile dobrych uczynków dokonaliście w swoim życiu i ile uczynków miłosierdzia? Ile dusz przyprowadziłeś do mnie, wyrywając je od diabła? Bracia i siostry, to są powody, dla których będziecie sądzeni; wiedzcie, że ci, którzy bluźnią, nigdy nie ujrzą mojego oblicza. Bądźcie zjednoczeni i módlcie się za Włochy, bo ich cierpienia będą wielkie, nawet natura zbuntuje się przeciwko człowiekowi. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])




dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 2)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj, zgromadzeni na modlitwie. Drogie dzieci, ja, wasza matka, proszę was, abyście nie byli zdezorientowani; Duch Święty zstąpi na was, abyście mieli rozeznanie, szczególnie w Kościele. Ach, moje kochane dzieci, ileż prześladowań i ileż bólu wywołują one w moim sercu. Strzeżcie się, Moje dzieci, oni również będą posługiwać się Moim wizerunkiem, podnosząc Mnie przed wiernymi, aby uwierzyli, że wszystko trwa nadal, ale czasami zwodzą was, ponieważ ich zachowanie poza Kościołem jest dalekie od Słowa Bożego. Umiłowani moi, płaczę z powodu tego, co was czeka, mój Syn, gdyby powrócił w ciele, zostałby ponownie ukrzyżowany, ale tylko nieliczni ujrzą Jego Święte Oblicze. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 3)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Niektórzy z was potrzebowali czasu, ale teraz jesteście tutaj pod moim błogosławionym płaszczem. Drogie kochane dzieci, dziś jest bardzo szczególny dzień i proszę was, abyście trwali przy moim Synu i Jego Ciele, często przystępujcie do Eucharystii, a zobaczycie, jak zstąpią na was łaski, On będzie mówił do waszego serca, podążając za wami dzień po dniu, tak że nie będziecie już mogli się bez Niego obejść, słuchając pokoju, który pozostawi w waszych sercach. Moje kochane dzieci, nie rozpaczajcie, aniołowie są zjednoczeni ze świętymi i z tymi, którzy wstąpili do Nieba w świętości, aby walczyć w tej wojnie przeciwko diabłu. Moje dzieci, nie ma już czasu, nawróćcie się i otwórzcie wasze serca na miłość. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 5)), "Droga córko, dziękuję ci, moje matczyne serce pragnie, aby moje dzieci rozpalały ducha, a nie umysł, jednoczyły się w imię Jezusa i tworzyły wieczerniki modlitwy, kocham was wszystkich, ponieważ wszyscy jesteście moimi dziećmi. Mój mały, nie bój się oczyszczeń, bo one służą temu, by doprowadzić cię tam, gdzie jest tylko pokój i zgoda, bądźcie zawsze wierni Ewangelii i miłòujcie się jak bracia. Teraz daję wam moje matczyne błogosławieństwo, w imię Ojca, Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 9)), "Drogie dzieci, dziękuję wam za to, że słuchacie wezwania, które jest w waszych sercach. Umiłowani moi, teraz otwierają się niebiosa, aby zjednoczyć się z ziemią. Krótkie są czasy oczekiwania i wkrótce wszyscy ujrzycie Bożą chwałę. Dlatego błagam was, proście o Boże przebaczenie. Jeśli twoje 'tak' jest szczere, na pewno zostanie ci wybaczone i zstąpi na ciebie całe Boże miłosierdzie. Przebacz, a będzie ci przebaczone. Bądźcie gotowi patrzeć na znaki nieba, nie bądźcie ślepi i nie stójcie ze skrzyżowanymi rękami nic nie robiąc. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 12)), "Drogie dzieci, dziękuję wam, że jesteście tutaj zgromadzeni na modlitwie. Umiłowani moi, diabeł jest bardzo przebiegły, przywiązuje was do rzeczy ziemskich, do wszelkiego rodzaju przyjemności. Dzieci moje, bądźcie czujne, zwłaszcza na zazdrość i zawiść, bo on prowokuje wasze reakcje, aby nastawić was przeciwko sobie i spowodować podział. Moi mali, strzeżcie się fałszywego pokoju, trzęsienia ziemi będą następowały jedno po drugim, a przyroda, zwłaszcza morze, będzie się buntować. Módlcie się za Rosję. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen. ", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 16)), "Drogie dzieci, dziękuję wam, że jesteście tutaj zgromadzeni na modlitwie. Dzieci mojego serca, módlcie się o nawrócenia, zwłaszcza moich dzieci konsekrowanych, od pierwszego do ostatniego. Niestety, zawsze szukają naukowych wyjaśnień dla znaków nieba, ale kto otworzy swoje serce oczami ducha, ten zrozumie. Ja, wasza Matka, wciąż tu jestem, ponieważ Ojciec, który jest w Niebie, chce, aby wszyscy zostali zbawieni i kocha wszystkich wierzących i niewierzących, nawet jeśli nie ma zbyt wiele miłości do Niego. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego. Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 19)), "Drogie dzieci, dziękuję wam za wasze modlitwy i za waszą wiarę. Umiłowani moi, nie gniewajcie się, nie bądźcie zawiedzeni, kiedy mówią o was źle, kiedy jesteście wyśmiewani, a wszystko to w imię Jezusa. Ja nie jestem tu po to, aby wzbudzać strach w moich dzieciach, ale aby ostrzec je przed niebezpieczeństwami, które na nie czyhają. Wiara i modlitwa łagodzą i spowalniają wydarzenia, gromadzą jak najwięcej dusz i prowadzą je do nawrócenia. Módlcie się za Hiszpanię i za tych wszystkich, którzy nie wierzą. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 23)), "Moi bracia, dziękuję wam za modlitwy i odmawianie Różańca Świętego, który jest bronią odpierającą zło. Moi drodzy bracia, pomimo ciągłej obecności mojej Najświętszej Matki, pomimo znaków, które wam daję, łask, które otrzymujecie i pomimo wszystkiego, dlaczego wielu wciąż nie otwiera swoich serc na moją miłość, na moją łaskę i na moje miłosierdzie? Chcę wszystkich zabrać do Mojego Raju, dlatego proszę was teraz, abyście wyznali każdy grzech, zwłaszcza ciężki, nie powtarzając go nigdy, abym mógł wam przebaczyć. Ja, wasz Jezus, daję wam całe Moje Miłosierdzie. Bądźcie żywi w wierze i dawajcie świadectwo. Kochajcie mój krzyż, nawróćcie się i przyjdźcie do mnie, ja tylko czekam na wasze TAK i zawsze będę obok was w waszym życiu. Bądźcie gotowi na nowe Zesłanie Ducha Świętego. Teraz błogosławię was w imię Ojca, w imię moje i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 26)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Droga córko, niestety czas ucisku i prawdziwego prześladowania dla ciebie i twoich braci jeszcze naprawdę nie nadszedł. Odbierane jest wam wszystko, co cenicie, ale musicie się cieszyć, nie pozwólcie, by ogarnął was ból. Wkrótce wasz Zbawiciel przyjdzie między was, aby uratować was od przebiegłości szatana. Moi mali, patrzcie na znaki, wkrótce nawet księżyc nie będzie już dawał swego światła. Módlcie się, módlcie się, módlcie się, nie bójcie się, wzywajcie mnie, a ja zawsze będę was chronił. Czytajcie Ewangelię i zapowiadajcie przyjście Jezusa. Teraz daję wam moje matczyne błogosławieństwo, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 30)), "Drodzy bracia, dziękuję wam za to, że zgromadziliście się na modlitwie. Jestem tutaj, jestem wśród was, proszę was, weźcie mnie za rękę i idźcie za mną, nie pytając wiele, nie zadając pytań, pamiętajcie, że to jest prawdziwa wiara. Ja jestem prawdą, drogą i życiem. Kochaj mnie tak, jak ja kocham ciebie. Wierzący i niewierzący, jestem tu z wezwaniem do zbawienia, 'Ratujcie się', wróćcie na czas, nadejdzie dzień, kiedy będziecie razem ze Mną, a Ja czekam na wasze serce, otwórzcie je, ileż miłości pragnę dać! Pamiętajcie zawsze, aby postępować zgodnie z Ewangelią, bądźcie mocni w Moich słowach, a przede wszystkim głoście prawdę bez lęku, Ja zawsze będę z wami. A teraz błogosławię was w imię Ojca, w imię moje i Ducha Świętego, Amen.", dataset["text_pl"])





dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "Moje kochane dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Moje kochane dzieci, dziękuję wam za to, że jesteście Kościołem, wiem, jak bardzo się modlicie i wiem, jak wiele wyrzekacie się dla Pana, ale czasami to wszystko nie wystarcza. Czyńcie posty, karmcie się Ciałem mojego Syna, spowiadajcie się. Wszystko to będzie dla zbawienia waszych dusz. Drogie dzieci, Jezus nadal cierpi, ponieważ zło szerzy się na świecie, Jego miłosierdzie jest wielkie, jest ogromne, ale wasze nawrócenie i nawrócenie świata jest pilne. Kościół Chrystusa zatriumfuje. A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 7)), "Moje kochane dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Znam wasze imiona jedno po drugim, znam wasze prośby i wasze smutki, módlcie się do mojego Syna Jezusa, a On będzie interweniował w waszych potrzebach. Jestem tutaj, aby dać wam pokój, wyjaśniać i kochać was. Umiłowane poświęcone dzieci, znam wasze zakłopotanie, ale nie uciekajcie przed trudnościami, które szatan przed wami stawia, ale idźcie naprzód, pamiętajcie o waszej Oblubienicy i pamiętajcie, abyście zawsze byli pasterzami, którzy gromadzą zagubione owce, zaprowadzajcie porządek w waszych sercach i nie dajcie się zmylić. Wzywajcie mnie i imienia mojego Syna, a będziemy tam, aby was chronić. Módlcie się za Amerykę, aby na nowo pokochała Jezusa. Teraz udzielam wam mojego Świętego Błogosławieństwa, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 10)), "Droga córko, dziękuję ci, że wciąż jesteś tutaj, czekając na moje orędzie zbawienia, dziękuję tym, którzy odpowiedzieli na moje wezwanie w swoich sercach. Moi kochani, wkrótce zobaczycie, że zstąpi na was ciemność, nie lękajcie się, ale módlcie się i zapalajcie błogosławione świece. Duch Święty zstąpi na ciebie i będzię przemawiać przez twoje usta. Pamiętaj, że krzyże i cierpienia będą służyć zbawieniu dusz. Uwolnijcie się od ego, które trzyma was w niewoli, bądźcie pokorni i słuchajcie słów Moich Apostołów. Nikt nie ma prawa sądzić i potępiać, tylko Bóg może wszystko. Módlcie się za Rosję i za Włochy, gdzie wkrótce silne trzęsienie wstrząśnie ziemią. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 14)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowani moi, za każdym razem, kiedy wasze serce bije szybciej i czujecie mój zapach, w tym momencie zrozumiecie, że jestem pośród was. Umiłowani moi, jak bardzo kocha was mój Ojciec! On chce, abyście wszyscy byli zbawieni; nawet niewierzący, gdy mnie spotkają, zrozumieją swoje miejsce. Dzieci moje, diabeł jest silny, ale wy macie wielką siłę, którą jest wiara, modlitwa i różaniec święty. Módlcie się, módlcie się, módlcie się! Teraz daję wam moje święte matczyne błogosławieństwo w imię Ojca, Syna i Ducha Świętego, Amen. 'Refleksja: Nasza najsłodsza Matka wzywa nas raz jeszcze do wiary i modlitwy. Nie wiary infantylnej, sentymentalnej i okazjonalnej, ale wiary dorosłej i świadomej. Nieustannie prosi o ufną, pełną miłości modlitwę i oddanie się kochającemu Ojcu, który uważa nas za cennych jak źrenica Jego oka i który zachowuje nas w swojej miłości. Módlmy się o nawrócenie serc, bo On chce, aby Jego dzieci zostały zbawione! Maryja ostrzega nas przed potężnym działaniem Złego i daje nam klucz do zrozumienia siły, jaką mamy, która pokonuje wroga: wiarę i modlitwę, a jeśli mamy jedno i drugie, Ona sprawi, że 'poczujemy' to namacalnie! Alleluja!", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 17)), "Drogie dzieci, dziękuję wam za waszą obecność na modlitwie. Moje kochane maleństwa, jak wielką miłość czuję w waszych sercach! Bądźcie zawsze czyści jak dzieci, ale z silną żołnierską wiarą. Prześladowania będą na tym świecie; bądźcie silni i nie bójcie się. Moje drogie dzieci, wkrótce wasze sumienia wyjdą na jaw i ci, którzy uwierzyli, będą się radować, ale ci, którzy odrzucili miłość Bożą w swoich sercach, odczują wielki ból. Kocham was, módlcie się, módlcie się, módlcie się, bo czas już dojrzał i wkrótce wszystko się spełni. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen. Refleksja Nasza najsłodsza Matka raduje się miłością, którą czuje w sercach swoich dzieci i przygotowuje nas, abyśmy mieli siłę i odwagę na próby i zmagania, którym dzieci Boże muszą stawić czoła. Wkrótce wszystko się objawi, wszystko wyjdzie na powierzchnię i na światło: nasza wiara i nasze sumienia, ale także prześladowania będą coraz bardziej widoczne. Jesteśmy umiłowanymi dziećmi, ale są tacy, którzy odrzucają tego kochającego Ojca, i te dzieci doświadczą w swoich sercach całego bólu związanego z odrzuceniem tej nieskończonej Miłości! Maryja wzywa nas do modlitwy o czas, który jest już bliski, ale uspokaja i umacnia nas swoją matczyną miłością i swoim błogosławieństwem. Alleluja!", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 21)), "Umiłowane dzieci, dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Drogie dzieci, jesteście moimi zapalonymi płomieniami, nigdy nie gaście ognia wiary, ponieważ potrzebuję was, potrzebuję żołnierzy na ziemi, dorosłych, którzy nadal zastanawiają się jak dzieci, kiedy czują moją obecność i obecność mojego Syna. Ile razy słyszę wasze pytanie: ile mamy jeszcze czasu? Dzieci, proszę was, bądźcie gotowi, jak powiedział Jezus, przyjdę jak złodziej w nocy, więc zawsze bądźcie gotowi, chwile, które się zbliżają są krótkie i przyspieszają. Módlcie się za Kościół i za Japonię. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 24)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach, nie opuszczajcie modlitwy, bądźcie zawsze wierni Jezusowi. Jak wiele bólu czuję w waszych sercach, ofiarujcie wszystko i złóżcie swoje problemy u stóp krzyża. Moje skarby, trwa walka między dobrem a złem, diabeł jest przebiegły, silny i będzie się cieszył z każdej duszy, którą uda mu się wyrwać Bogu. Proszę, moje dzieci, nie odkładajcie waszej broni modlitwy i miłości z powodu zmęczenia, będziecie mieli największą nagrodę, życie wieczne, nie bójcie się, ostrzeżenie jest bliskie i będzie straszne dla tych, którzy odrzucili Boga i radosne dla tych, którzy Go rozpoznali. Ja wasza matka kocham was, biorę was za rękę, pozwólcie mi towarzyszyć wam.  Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 28)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, tak bardzo smutne jest moje serce z powodu tego, co ma nadejść. Ileż to razy prosiłam, aby spojrzeć na znaki na niebie, wszystko, co jest podziwiane przez świat, jest wielkim znakiem. Czerwień księżyca to krew, którą Jezus przelał za ciebie. Oto dzieci, jest to czas wielkich trzęsień ziemi, zbuntuje się morze i ziemia. Dzieci moje, uwolnijcie się od 'ja' i przyjdźcie do mnie; tylko z Jezusem droga będzie właściwa i prawdziwa. Módlcie się za Włochy, ponieważ ziemia będzie się bardzo mocno trząść. Umiłowani moi, błogosławię was teraz w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 31)), "Moja córko, to wszystko jest tylko bardzo małą częścią tego, co się wydarzy, bądźcie żołnierzami światła, módlcie się za biskupów, konsekrowanych kapłanów, a szczególnie za teologów, którzy zmieniają słowo, dając inne wyjaśnienie niż to, które pozostawił Jezus. Przyjmijcie Eucharystię, póki jest jeszcze czas, wszystko zostanie przekreślone. Jak wiele krwi będzie musiało popłynąć na świecie, Jezus przyjdzie na świat niosąc swój krzyż zbawienia dla ludzkości. Dzieci moje, On was ochroni swoją Krwią Chrystusa. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])




dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 3)), "Moje dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Umiłowani moi, jak wielki ból słyszę w waszych modlitwach, wasze serca są skruszone i strapione całym złem, które szerzy się na świecie. Moi kochani, oni chcą, abyście wierzyli, że piekło nie istnieje, ale tak nie jest, nie byłoby przebaczenia, gdyby nie było grzechu. Proszę więc, moje dzieci, czytajcie Ewangelię i trwajcie mocno w tym słowie. Pokój i spokój niech będzie w waszych sercach, w trudnych chwilach przyzywajcie mojego Syna, On was wysłucha i ochroni, powierzcie Mu swoje smutki i rozczarowania, On przemieni wasze życie w cud. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 4)), "Umiłowani bracia, dziękuję wam, że jesteście tu na modlitwie, proszę was, nie dajcie się prowadzić złu, ono wykorzystuje wasze chwile słabości, by zaprowadzić was tam, gdzie płoną płomienie. Proszę was o miłość i pokój z waszymi braćmi, przebaczcie, a będzie wam przebaczone, Ja osądzę, kto jest ze mną, a kto przeciwko mnie. Wypatrujcie znaków z nieba, tylko ja jestem Drogą, Prawdą i Życiem, mój Ojciec wkrótce zniszczy wszelką niegodziwość, bądźcie gotowi na ataki, szyderstwa i prześladowania w moje imię, zawsze będę was chronił wraz z moją ukochaną Matką. Zawsze wierzcie w Boga Jedynego i Trójjedynego. Teraz, w imię Trójcy Przenajświętszej, daję wam moje święte błogosławieństwo, w imię Ojca, w imię moje i w imię Ducha Świętego, Amen. Twój Jezus.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 7)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie. Dzieci moje, niebo się raduje, wy też możecie to uczynić teraz, niewiele czasu nas dzieli, zawsze miejcie zapaloną błogosławioną lampę i różaniec w swoich rękach. Już wkrótce, mój Syn będzie wśród was, przyjdzie z całą swoją chwałą. Moje klejnoty, czy nie widzicie znaków nieba? Duszący upał i wszystko, co się wydarzy, będzie dla waszego oczyszczenia i będzie konieczne, abyście mogli uklęknąć, gdy przyjdzie Jezus i wszyscy uznają Go za Króla nieba i ziemi. Nie myślcie o rzeczach ziemskich, ale wzbogacajcie się w duchu, reszta nie jest już potrzebna. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 11)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, Ja otrę wasze łzy, a wy swoim Różańcem Świętym otrzyjcie część moich, dlatego wciąż proszę was o wieczerniki modlitwy w tak wielu miejscach. Dlatego nie przestaję was prosić, abyście w tak wielu miejscach organizowali kręgi modlitewne. Moi umiłowani, sprawiedliwość mojego Syna jest już nad wami, patrzcie, co się dzieje na świecie i w moim Kościele. Wszystkie wojny, przemoc i trzęsienia ziemi powinny dać ci do zrozumienia, że Boża sprawiedliwość już się rozpoczęła. Umiłowani moi, karmcie się nadal Ciałem mojego Syna, bo wszystko się wali razem z Tabernakulum. Nadal tu jestem i będę przez krótki czas, aby uczyć was drogi, która prowadzi do Jezusa. Słuchajcie moich orędzi i nie odwracajcie się od tych, którzy mówią przez moje usta. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 15)), "Umiłowane dzieci, dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Umiłowane dzieci, przyjdźcie do mnie, abym mogła was przyprowadzić do mojego Syna Jezusa. Pragnę zobaczyć was wszystkich zbawionych i dlatego za każdym razem, gdy tu jestem i gdy mnie wzywacie, jestem obok was. Wszystko to, co się dzieje, jest dla wielkiego oczyszczenia ziemi i po tym będziecie odrodzeni do nowego życia ze mną i z moim Jezusem. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 18)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Jezus jest już w drodze na swoje powtórne przyjście, ileż cierpienia jeszcze odczuwa, krzyżują Go jak za dawnych lat. Wystarczy! Zbyt wiele grzechów, zbyt wiele bluźnierstw, jak wiele błędów! Wszystko to, co się dzieje, jest bardzo małą częścią tego, co się stanie, mówię wam te słowa, aby w waszych sercach nastąpiło prawdziwe nawrócenie, a przede wszystkim mówię to do moich konsekrowanych dzieci, przestańcie krzyżować Jezusa, sprawiedliwość będzie na was wielka. Umiłowani moi, przyjdźcie do mnie, wkrótce zostanie otwarta siódma pieczęć i usłyszycie trąby anielskie, bądźcie gotowi w modlitwie, zwłaszcza w odmawianiu Różańca świętego i w poście. Jeszcze raz wzywam was do miłości mojego Syna Jezusa, aby pokój i przemiana waszych serc były natychmiastowe. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca, Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 21)), "Dzieci moje, dziękuję wam za wasze modlitwy, dziękuję za wierność Ewangelii i podążanie za moimi wskazaniami. To, co robią uczniowie, to niesienie swojego krzyża, Jezus powiedział: kto nie niesie mojego krzyża, nie może być moim uczniem. Wszystko, co się wydarzy, będzie na oczach wszystkich i każdy uzna prawdziwość tych wiadomości. Wy, wierne dzieci, będziecie pić gorzki kielich i wasze cierpienia będą wielkie, ale pomyślcie o nagrodzie razem ze mną i moim Jezusem. Módlcie się za Włochy, bo silne trzęsienie ziemi zachwieje nimi. Bądźcie pokorni w cierpieniu, ale mocni w wierze. Jest to czas, kiedy próby będą liczne, nawet te, które mają na celu zakończenie waszej misji. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 25)), "Drogie dzieci, dziękuję wam, że usłyszeliście moje wołanie w waszych sercach. Módlcie się, módlcie się, módlcie się dużo, do tej pory dokument dotyczący Eucharystii został już podpisany. Ludzie nie będą już wierzyć w przeistoczenie, ale wszystko zostanie przyjęte jako pamiątka. Umiłowane dzieci, wszystko się zmieniło i nadal będzie się zmieniać w przyspieszonym tempie, bądźcie gotowi, tylko w Eucharystii i w Słowie znajdziecie siłę, by sprostać tym zmianom. Stolica Piotrowa wkrótce zostanie zniszczona. Módlcie się za Kościół, gdzie ciemność zajęła miejsce światła, powierzcie się mojemu Synowi Jezusowi, który jest miłością. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 28)), "Bracia, dziękuję wam, że jesteście tu na modlitwie, jestem pośród was, ale nie wszyscy rozpoznają moją obecność. Jak bardzo modliłem się za ciebie mój Ojcze, lecz ludzkość nie ma już nic wspólnego z Wiarą, nie mogę już zatrzymać tego oczyszczenia, które teraz się dokonuje, bądź we mnie i w mojej ukochanej Matce, a my będziemy cię chronić. Ileż bólu w moim Kościele, wielu jest moich katów, lekarze kościoła robili to kiedyś i dziś jeszcze robią to z mocą, ale pamiętajcie bracia, mój Kościół nigdy nie zostanie pokonany przez zło, ale odrodzi się zwycięsko. Zanurzcie się w mojej miłości, odliczanie się rozpoczęło. Teraz daję wam moje błogosławieństwo, w imię Trójcy Świętej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])


dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 1)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moi umiłowani, bądźcie zawsze zjednoczeni w miłości Jezusa, aby bronić dusze przed diabłem i prowadzić je ku światłu. Umiłowane dzieci, uklęknijcie przed Krucyfiksem z wielką pokorą i proście o przebaczenie za wasze grzechy. Powróćcie do Boga, nie z lekkością serca, ale umacnieni w wierze. To jest moment, w którym zobaczycie wszystko, co ujawniłem. Módlcie się dużo za ukochane Włochy, teraz one potrzebują wielu modlitw, aby uniknąć najgorszego, niestety odwróciły się od Boga. Teraz daję wam moje błogosławieństwo w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "Umiłowane dzieci, jaka radość ogarnia moje serce, gdy widzę was tutaj odpowiadających na moje wezwanie w waszych sercach. Umiłowane dzieci, powiedz moim konsekrowanym mężczyznom i kobietom, aby nie chodzili drogami świata, ale drogą, która prowadzi do mojego Syna Jezusa, pomagając duszom zagubionym, kuszonym przez szatana. Moi kochani, módlcie się, tak jak ja modlę się do mojego Ojca, abym nadal była tu z wami, abym mogła was prowadzić do końca. Słuchajcie moich przesłań i moich wskazań do życia wiecznego. Teraz godziny szatana są już policzone, ale jest on o wiele bardziej agresywny, ponieważ wie, że drugie przyjście Jezusa jest bliskie. Módlcie się, moje dzieci, aby oczyszczenie świata posłużyło do odzyskania raju. Teraz umieszczam was wszystkich pod moim płaszczem łaski i błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 8)), "Moi kochani, dziękuję wam, że jesteście tutaj na modlitwie. Moje małe dzieci, podajcie mi swoje ręce, a Ja wam dam wiele błogosławieństw. Zaprowadzę was tam, gdzie wszystko będzie pełne miłości, nie będzie niegodziwości, nie będzie niesprawiedliwości, jestem waszą Matką, dlatego od lat proszę was o to samo, chcę, abyście wszyscy byli zbawieni i dzisiaj zobaczycie znak, który usunie wszelkie wątpliwości co do mojej obecności. Błogosławię was, moje dzieci, w imię Ojca, Syna i Ducha Świętego, Amen. Słońce zaczęło się obracać i było widoczne gołym okiem w tysiącu cudownych kolorów. Dziękujemy Ci Święta Maryjo za ten dar!", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 11)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, na trudne czasy, które nadejdą, proszę was, nie zniechęcajcie się, powierzcie się Jezusowi, On was ochroni, a ja wraz z aniołami nigdy nie pozwolę, aby zło was dotknęło. Odważnie brońcie wiary i prawdy, przyobleczcie się w Bożą miłość i walczcie. Módlcie się za Amerykę, ponieważ odwróciła się ona od Boga i kara będzie surowa. Dzieci, powróćcie do Boga i otwórzcie swoje serca. Teraz daję wam moje matczyne błogosławieństwo w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 15)), "Drogie kochane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, ileż bólu w moim sercu z powodu tego wszystkiego, co dzieje się w domu Bożym, ale szatan nie zwycięży, bo niewiele czasu będzie do jego dyspozycji, a Kościół odrodzi się święty. Proszę was, moi kochani, abyście trwali w jedności, byli pełni Ducha Świętego i prosili o dar rozeznania. Strzeżcie się oszustwa. Jest to czas, kiedy wiele wilków w owczej skórze zakradnie się do grup modlitewnych, aby je zniszczyć. Nie słuchajcie słów tych, którzy zmieniają Mszę św. i błędnych interpretacji, jakie nadadzą temu, co jest napisane w Ewangelii, pamiętajcie dzieci, słowo Jezusa było i będzie zawsze jedno i jedyne. Moje dzieci, walczcie o prawdę, a ja zawsze będę przy was razem z moimi Aniołami i Archaniołami. Kochaj Trójcę Przenajświętszą. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 18)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Drogie dzieci, maluczcy, wszystko się zmienia i wszystko jest przekształcane, szczególnie w waszych sumieniach. Zawsze proście Ducha Świętego o pomoc. Gdy zostaniecie wezwani, On napełni was swoim pokojem i tylko słowa Jezusa wyjdą z waszych ust. Dzieci moje, otwórzcie wasze serca, bo wkrótce mój Syn powróci, a kiedy przyjdzie, ile wiary znajdzie? Zadajcie sobie pytanie, jak odważni i zdeterminowani jesteście, aby mówić w imię Jezusa i za jaką cenę bronicie prawdy? Nie ukrywajcie się i nie bądźcie letnimi katolikami, ale prawdziwymi chrześcijanami. A teraz błogosławię was w imię Ojca i Syna, i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 22)), "Drodzy bracia, jak wielka jest radość w moim sercu, gdy widzę was zjednoczonych w modlitwie. Bracia, przyjaciele, dzieci, spójrzcie dobrze w swoje serca, tylko tam muszę wejść, więc otwórzcie je szeroko, aby moja wielka miłość mogła wejść. Bracia, rozumiem pokusy, ja też byłem kuszony przez szatana, rozumiem wasze słabości, bo ja też byłem człowiekiem, byłem odrzucony, maltretowany, umartwiany i w końcu ukrzyżowany, doskonale rozumiem wasze człowieczeństwo, ale musicie być silni. Odpędzajcie diabła modlitwą Różańca Świętego i często bierzcie Eucharystię. Miłujcie braci waszych, a zwłaszcza tych, którzy was prześladują z powodu mego imienia. Ja przebaczyłem tym, którzy mnie ukrzyżowali. Pamiętajcie, że czuwam nad wami każdego dnia w waszych modlitwach i pracach. Kocham was wszystkich i błogosławię was w imię Trójcy Przenajświętszej. Zostawiam wam pokój! Twój Jezus.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 25)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, wkrótce ujrzycie wielkie znaki z Nieba. Na co jeszcze czekasz? Czy wszystko, co się dzieje, nie jest wystarczające, aby Bóg wezwał cię do siebie? Z pewnością wszystko, co nadejdzie, przerazi was, ale zanim będzie za późno, chciałabym wam towarzyszyć na tej drodze, która prowadzi do Światła. W tej chwili na ziemi jest tylko jałowość, tak jak i w sercach ludzkości. Ziemia będzie buntować się coraz mocniej, patrzcie na te wydarzenia sercem, a wszystko stanie się dla was jaśniejsze. Diabeł wkrada się z taką siłą, jak nigdy wcześniej. Jezus wciąż oczekuje czasu swojego przyjścia. Módlcie się za Amerykę. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 29)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj i że słuchacie mojego wołania w waszych sercach. Drogie dzieci, widzicie moje łzy krwi, a potem z obojętnością kontynuujecie swoje życie, ale czy nie rozumiecie, jak wielki jest mój ból, gdy patrzę, jak ginie wiele moich dzieci, zwłaszcza młodzież, rodziny i mój Kościół? Zamiast się zastanowić, odwracacie się plecami, bez prawdziwego nawrócenia i smutku. Moje dzieci, ci, którzy już wstąpili do nieba, przygotowują się do stoczenia wielkiej ostatecznej bitwy, podczas gdy ja przygotowuję moją armię na ziemi. Bądźcie silni, nie dajcie się zwieść ani zniechęcić, bo będziecie musieli walczyć o prawdę. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])



dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowana córko Nieba, teraz musisz dokładnie powiedzieć to, co ci przekazuję: kardynałowie i biskupi, przestańcie chodzić z podniesionymi głowami, podczas gdy Kościół jest w ruinie, drodzy mi teologowie, nie ważcie się zmieniać tego, co Jezus pozostawił napisane, Jego słowa będą żyły wiecznie, ponieważ On jest drogą, prawdą i życiem, proboszczowie nie pozostawajcie zakotwiczeni w posłuszeństwie, ale walczcie z tymi, którzy chcą dodać miłości szatanowi, nie intrygujcie z masonerią, ale bądźcie w służbie dusz wiernych. Umiłowani moi, wkrótce mój Syn powróci ponownie, aby uwolnić was od waszych grzechów. Na co jeszcze czekasz, żeby się nawrócić, czy nadal chcesz mieć znaki? Zamiast tego proszę was o nawrócenie i modlitwę, zanim ogień zstąpi z nieba. Módlcie się za Włochy, za Amerykę i za Sycylię. Kocham was, bo jesteście moimi dziećmi. Dziś zstąpią na was łaski i błogosławieństwa. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 6)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach; jaka to radość widzieć was tutaj tak wielu zgromadzonych na modlitwie! Jestem szczęśliwa, ponieważ ci, którzy otworzyli swoje serca na mojego Syna, zobaczyli cuda Boga. Umiłowane dzieci, nie bójcie się, dzieci Boże są już naznaczone i nikt nie zostanie dotknięty w tym czasie prześladowań. Ogłaszajcie dobrą nowinę, bo ten świat wkrótce powróci do pokoju dzięki Miłości, którą może przynieść tylko Jezus Zbawiciel. Bądźcie spokojni, zawsze będę was chronić, ale bądźcie gotowi z zapalonymi lampami, bo wszystko się wali. Nawróćcie się, ukochane dzieci, czas się skończył. Teraz przyjmijcie moje błogosławieństwo i pokój do waszych domów, błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 9)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj na modlitwie i że słuchacie mojego wołania w waszych sercach. Drogie dzieci, zawsze proście, nigdy nie przestawajcie prosić o dar prawdziwej wiary, zawsze wzywajcie Ducha Świętego, aby On was kształtował, tak jak chce tego Jezus. Dawajcie świadectwo swojej wiary, bądźcie odważni. Jest to czas łask, które będą udzielane z miłością i które może uczynić tylko matka. Jesteście Moimi wojownikami Światła na ziemi. Straszne rzeczy, które was czekają, nie mogą was nigdy przerazić, bo my zawsze będziemy u waszego boku. Teraz błogosławię was w imię Ojca i Syna, i Ducha Świętego, Amen. BĄDŹCIE ŚWIADKAMI", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 13)), "Drodzy bracia, dziękuję wam za waszą obecność na modlitwie. Jesteście moim błogosławionym ludem, przypominam wam, że w tym czasie musicie pomóc moim prześladowanym dzieciom, prześladowanie jest dziś większe niż wcześniej. Moi drodzy bracia, nigdy nie bójcie się ujawniać orędzi danych przez Niebo, one służą przygotowaniu was na wszystko, co się wkrótce wydarzy. Nie będę już obecny w Kościele, przygotujcie się, aby zgromadzić się w waszych domach na modlitwie, jak przepowiedziała moja matka. Rozpoczęła się protestantyzacja i moja Matka nie jest już mile widziana wśród ludzi Kościoła, ale wy, bracia, którzy Ją kochacie, którzy zbieracie Jej łzy i wierzycie w Jej wielki smutek, pozwólcie się wziąć za rękę, by towarzyszyć Jej ku świętości. Zawsze kochajcie Trójcę Przenajświętszą. Błogosławię was wszystkich w imię Ojca w imię moje i Ducha Świętego, Amen. Twój Jezus", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 16)), "Moje dzieci, dziękuję wam za wasze modlitwy. Proszę moje ukochane dzieci, abyście się nie bały o nadchodzące dni. Moje kochane dzieci, otworzyły się niebiosa, pragnę, aby wszystkie moje dzieci zachowały spokój, ponieważ mój Kościół nigdy nie zginie. Teraz wszystko zostanie zbezczeszczone, ale wy podążacie za moim prawdziwym Kościołem, ja zawsze będę blisko was. Moje dzieci, nie bójcie się, ja, wasza matka, kocham was. Teraz daję wam moje święte błogosławieństwo w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 23)), "Umiłowane dzieci, dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Umiłowani moi, pragnę, abyście zawsze byli zjednoczeni, ponieważ wkrótce nadejdzie czas, kiedy będziecie potrzebowali siebie nawzajem. Dzieci moje, wkrótce stanie się to, o czym zawsze mówiłam, obserwujcie znaki na niebie, ziemia będzie się poruszać coraz mocniej, morza będą coraz bardziej wzburzone, a wulkany są gotowe do większych erupcji. Kiedy zostaniecie pochwyceni, wszystkie demony będą na ziemi, ale nie bójcie się, miłujcie się jak bracia, nadchodzi zimna noc. Dzieci, proszę was o pokój, pokój jest tym, co sprawi, że będziecie coraz bardziej wyjątkowi. Tak bardzo was kocham, świat i Kościół przejdą wielką próbę, ale zło nie zwycięży. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 27)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, proszę was, abyście zawsze rozeznawali, aby zrozumieć tych, którzy przemawiają w moim imieniu. Jest wielu, którzy wystąpią, mówiąc, że są posłani przez Ojca, ale nie będą to istoty światła, lecz istoty ciemności. Moje dzieci, módlcie się za Mój Święty Kościół, bo wkrótce usłyszycie, właśnie od tych, którzy do tej pory temu zaprzeczali, że ma miejsce apostazja. Moje dzieci, módlcie się, módlcie się, módlcie się, módlcie się, abyście nie cierpieli podczas Ostrzeżenia. Pokój Dzieci moje, pokój zstąpi na was i na wasze rodziny, łaski zstąpią dzisiaj. A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 30)), "Drogie kochane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, błagam was, otwórzcie wasze serca, nawróćcie się szybko, nie ma już czasu. Módlcie się za biskupów, kardynałów i księży, niektórzy z nich powiedzieli 'tak' ciemności i z tego powodu będą narażać na niebezpieczeństwo dzieci i młodzież. Błagam was, dzieci, bądźcie gotowi z zapalonymi lampami; nigdy się nie bójcie. Proszę was, poświęćcie siebie i wasze rodziny mojemu Niepokalanemu Sercu i Sercu Jezusa, to będzie waszą ochroną i pozwólcie się naznaczyć Jego Krwią. Teraz daję wam moje matczyne błogosławieństwo w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])



dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 3)), "Moje kochane dzieci, dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Umiłowane dzieci, zachęcam was, abyście żyli w Kościele, zawsze byli blisko Tabernakulum, gdzie Jezus jest żywy i obecny, karmili się często Eucharystią, żyli moimi orędziami i codziennie odmawiali Różaniec Święty. Czasy, które nadejdą, będą bardzo smutne, ale proszę was, nie bójcie się. Zbawieniem waszych dusz jest tylko miłość do Boga i Jego przykazań, słuchajcie codziennie słowa Bożego i pamiętajcie, moje dzieci, że wszystkie religie razem wzięte nie prowadzą do żadnego zbawienia, a jedynie do wielkiego zamętu i herezji, słowo Boże jest Jedno i będzie takie na wieki. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 6)), "Droga córko, musisz powiedzieć wszystkim, aby spojrzeli na to, co się dzieje na świecie, wszystko jest teraz w ruinie, powodzie, osunięcia ziemi, ulewne deszcze, gradobicia, to, co powiedziałem, dzieje się. Moi ukochani, kiedy proszę o szybkie nawrócenie, mam na myśli TERAZ, ludzkość nie może sobie pozwolić na marnowanie czasu na daremne rzeczy, podczas gdy odbywa się prawdziwe oczyszczenie, nawet gospodarki różnych krajów zostaną mocno zniszczone. Moja mała, bądź silna, nie bój się mówić prawdy, tylko w ten sposób wielu zrozumie. Czas, który dzieli cię od Zbawiciela jest krótki, do tej pory niebo i ziemia zjednoczyły się, tylko przez powrót do Boga może być zbawienie. Błogosławieństwo moje zstępuje na ciebie i na twój dom, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 10)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, często zastanawiacie się co się stanie podczas Ostrzeżenia, teraz powiem wam co się stanie, wszystko się zatrzyma i wszyscy zostaniecie wprowadzeni w stan ekstazy, podczas tego wszystkiego zobaczycie jak grzechy popełnione w życiu przemijają, to posłuży wam do uświadomienia sobie cierpienia i będziecie szukać i odnajdywać Boga. Umiłowani moi, módlcie się za Amerykę, bo wkrótce coś wielkiego stanie się z tym drogim mi narodem i obejmie cały świat, dlatego proszę was, nie traćcie czasu, nawrócenie jest ważne, abyście przygotowali się na spotkanie z Jezusem, zróbcie to teraz, bo znacie tylko miłość i miłosierdzie Boga, ale macie nadzieję, że nigdy nie zobaczycie Jego sprawiedliwości. Drogie dzieci, nie bójcie się, cokolwiek się wydarzy, pamiętajcie, że zawsze będę blisko was. Teraz daję wam moje matczyne błogosławieństwo w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 13)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowani moi, w tym okresie wielu zrobi rachunek sumienia, ponieważ Duch Święty wejdzie w wiele moich dzieci. To co poczujecie to wielka siła, pokój, zjednoczenie między braćmi i odwaga. Moje maleństwa, jestem blisko was i zawsze będę, będziecie mnie szukać jako matki, tak jak dzieci, które potrzebują matki, będziecie odczuwać pragnienie bycia naśladowanymi przeze mnie. Nigdy nie odwracajcie się od miłości Boga i Jego słowa, otwórzcie wasze serca, a On wejdzie jak burza miłości i zrozumiecie, że nic nie jest bez Boga, będziecie musieli zrobić wszystko, aby przyprowadzić waszych braci do Niego i mieć pewność życia wiecznego. Teraz błogosławię was, obecnych chorych i święte przedmioty, które nosicie, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 17)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, módlcie się za mój Kościół święty, chcą unowocześnić to, co Bóg zostawił napisane. Moje dzieci, wola ludzka w tym czasie nie jest wolą Bożą. Moje drogie maleństwa, wy jesteście Moją armią, bądźcie światłem dla wszystkich braci, aby otworzyli swoje serca. Teraz proszę was, abyście uklękli w modlitwie, abyście mogli chwalić Boga i cieszyć się Jego chwałą. Kochaj Trójcę Przenajświętszą. Wkrótce silne trzęsienie ziemi nawiedzi Włochy, nastąpią katastrofy naturalne, upór możnych tego świata powoduje tak wiele niewinnych śmierci. Módlcie się, módlcie się, módlcie się, proszę was, abyście wkrótce zapalili błogosławione świece, módlcie się za Rosję i za Amerykę. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 22)), "Moje drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie, to jest to, co chciałbym widzieć w rodzinach, ile radości dajecie mojemu sercu! Umiłowani moi, zawsze bądźcie zjednoczeni, będziecie potrzebowali siebie nawzajem, spowiadajcie się, jeśli macie negatywne uczucia do innych braci, oczyśćcie się, ponieważ czas jest bliski i będziecie gotowi. Kościół będzie atakowany, burze słoneczne nasilają się, zagrażając technologii, więc módlcie się, módlcie się, módlcie się, bądźcie zawsze w obecności mojego Syna. Błogosławieństwo zstępuje na was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 24)), "Umiłowane dzieci, dziękuję wam, że wysłuchaliście mojego wołania z waszego serca. Moje dzieci, znam wasze trudności, wasze troski i wasze życie, przyjmijcie łaski, które spadną na was w tym czasie. Dzieci moje, karmcie się Słowem mojego Syna, bądźcie dobrzy i uczciwi wobec bliźniego. Moje drogie dzieci, jako matka, cierpię widząc, jak wielu modli się, a potem zachowuje się z pychą i arogancją, uczcie się z tego, co powiedział Jezus. Moje dzieci, mój Syn potrzebuje waszych modlitw, ale wy będziecie Go potrzebować coraz bardziej. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 11) & (dataset["day"] == 27)), "Moje kochane dzieci, dziękuję wam, że jesteście tutaj na kolanach na modlitwie. Umiłowane dzieci, wszyscy często pytają, jaki będzie dzień przyjścia mojego Syna, ale dlaczego pytacie, jeśli nawet nie rozpoznajecie znaków czasu? Dzieci moje, kiedy odmawiacie Różaniec, zawsze go rozważajcie, modlitwa różańcowa bez rozważania i w pośpiechu jest nieważna. Moje dzieci, jakże krwawi moje niepokalane serce, gdy widzę pasterzy Kościoła w grzechu! Módlcie się za moich kapłanów. Módlcie się za Rosję. Teraz daję wam moje matczyne błogosławieństwo, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])

dataset["text_pl"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 1)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Módlcie się, módlcie się, módlcie się bardzo dużo, niestety niewytłumaczalne rzeczy będą się działy szczególnie we Włoszech, zatrzymajcie się i kontynuujcie przyprowadzanie dusz do mojego Syna Jezusa, On jest Miłością, Drogą, Prawdą i Życiem, dlaczego nie rozumiecie! Nadszedł czas, nawracajcie się, nie czekajcie na ostatnie chwile, wierzcie w to, co mówi ta córka, bo wszystko jest Prawdą, nie patrzcie obojętnie na wszystko, co dzieje się wokół Was. Módlcie się za Neapol. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że jesteście tutaj i odpowiadacie na moje wezwanie w waszych sercach. Moje drogie dzieci, zawsze karmcie się Słowem i tym, co pozostawił Jezus, ktokolwiek ma pretensje do zmieniania tego, obraża Boga, Jego Słowo jest niezmienne i będzie na zawsze. Moje dzieci, mówię do moich kapłanów, pragnę, aby zrozumieli i uświadomili sobie, co Bóg dla nich uczynił, upodabniając ich do Jezusa, dając im możliwość odpuszczania grzechów w Jego Imię, brania chleba i wina do rąk i w momencie konsekracji przemieniania ich w prawdziwe Ciało i Krew mojego Syna, dlatego moje dzieci, nie brudzcie swoich rąk grzechami, unikajcie pychy i arogancji, ale bądźcie pokorni. Proszę was o modlitwę za ten kościół, który jest w największym grzechu. Módlcie się za środkowe Włochy. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 9)), "Umiłowani bracia, wy przez wasze modlitwy oczekiwaliście Mojego przyjścia, Mój powrót jest bliski, obserwujcie zmiany w otaczającym was świecie, przemianę waszego Ducha. Ci, którzy się zbliżają, będą na zawsze, lecz ci, którzy się odwracają, nie będą mieli ucieczki przed sprawiedliwością Ojca mojego. Moi umiłowani bracia, pozostańcie zjednoczeni w mojej miłości, w miłości Boga i mojej Najświętszej Matki. Nie patrzcie na swoich braci nieczystymi oczami, ale miejcie mądrość. Odwróćcie to, co wam się wydaje złe, a Ja wam wszystkim dam mojego Ducha rozeznania. Niech błogosławieństwo mojego Ojca zawsze zstępuje na was i wasze rodziny. Drodzy przyjaciele, jak ja was kocham! Twój brat Jezus. Jestem zawsze z wami, błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 11)), "Moje kochane maleństwa, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach, ale gdzie jest reszta moich dzieci! To jest czas, w którym oczekujemy narodzin mojego Syna, proszę was, abyście nie przeżywali tego oczekiwania jak poganie, z prezentami i kolorowymi drzewami i zamkniętym sercem, ale przyjęli Go w spokoju i pokoju, a przede wszystkim w swoim sercu. Módlcie się za Włochy, aby powróciły do Boga, w przeciwnym razie cierpienie będzie wielkie, módlcie się za Rosję, módlcie się za mój Kościół, gdzie w jego części nie modlą się już do mojego Syna Jezusa, próbują obalić dogmaty, które należą do mnie, apostazja już jest. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 14)), "Drogie błogosławione dzieci, moja mała trzódko, dziękuję wam, że jesteście tutaj na modlitwie, wasze intencje zostaną dzisiaj wysłuchane. Dzieci moje, nie bójcie się tego, co nadejdzie, bo ochrona jest wam zapewniona, zapalcie błogosławione świece. W złych czasach nie bójcie się, bo kto ma wiarę, przezwycięży wszystko z wielkim pokojem w sercu. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 18)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, nie czekajcie dłużej, dajcie świadectwo prawdzie i waszej wierze, to jest czas Łaski. Pragnę, aby moje dzieci zrozumiały, jak wielka jest moja miłość do nich, dlatego potrzebuję waszych świadectw, aby serca najbardziej oddalonych mogły się otworzyć i zostać oświecone. Umiłowani moi, nadejdą bardzo złe czasy, szczególnie w tym nowym roku, który nadchodzi. Czekajcie na Stwórcę z miłością, pokojem, pokorą. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 25)), "Drodzy bracia, przyjmijcie mnie do waszych serc. Wkrótce przyjdę do was, nikt nie zna dnia ani godziny. Strzeżcie się dzisiaj wielu fałszywych proroków, którzy was otaczają. Pragnę żebyście słuchali tylko słów moich prawdziwych posłańców. Nadejdzie wielki grom i zstąpię, jak wstąpiłem do nieba, aby oddzielić złych od sprawiedliwych. Będzie to szczególny rok, w którym wszyscy będziecie mieli swoje błogosławione znaki. Otwórzcie wasze serca i pomóżcie moim braciom w niesieniu prawdy. Bracia moi, pozostańcie zawsze zjednoczeni w Pokoju i Miłości, bo Ja was kocham. Teraz udzielam wam Świętego Błogosławieństwa w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 29)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, proszę was o wiele modlitw w tym czasie walki między dobrem a złem. Moje kochane dzieci, wzywam was do modlitwy za cały świat, jak wiele będzie katastrof, wzburzone morza będą niszczyć miasta, wulkany będą nadal wybuchać w sposób katastrofalny. Dzieci moje, dlaczego pomimo wszystkich ostrzeżeń, wielu nie słucha, wierząc, że mogą naśladować Boga w swoim życiu, a są w błędzie! Jestem tu, aby prosić was ponownie: Wróćcie do Ojca! Dzieci moje, jak wiele było nawróceń! Ale jak wielu musi jeszcze powrócić do Boga! Pomóżcie swoim braciom waszymi świadectwami, nie bójcie się. Moje dzieci, dzięki wierze, droga, którą będziecie podróżować, będzie tą, którą wam wskażę, abyście dotarli do światła i tylko w ten sposób będziecie mogli mieć pokój i odczuwać miłość. A teraz udzielam wam mojego Świętego Błogosławieństwa w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 12) & (dataset["day"] == 31)), "Ja, wasz Ojciec, proszę was, abyście przeczytali księgę Jana, tam jest napisane wszystko, co się wydarzy, nie udawajcie, że nie umiecie czytać, odłóżcie wszystko na bok. Apokalipsa jest księgą, którą musisz przeczytać dla tych nowych czasów, które nadchodzą. Nie bójcie się, jesteście Moim ludem, zawsze słuchajcie waszej Umiłowanej Matki, która przychodzi, aby was uczyć, katechizować i chronić. Nie bójcie się, bądźcie gotowi do walki, moi żołnierze. Niebiosa zawsze będą cię chronić. Błogosławię was, moje dzieci, w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])










# SPELLING FIX
dataset["text_pl"] = dataset["text_pl"].str.replace("aa", "a")
dataset["text_pl"] = dataset["text_pl"].str.replace("Ojca Syna i Ducha Świętego", "Ojca i Syna i Ducha Świętego")
dataset["text_pl"] = dataset["text_pl"].str.replace("niebawem przybędę, jestem gotowa", "niebawem przybędę, jestem gotowy")
dataset["text_pl"] = dataset["text_pl"].str.replace("przygotował dla was mój Ojciec, kochać się, kochać", "przygotował dla was, kocham was, kocham was wszystkich")
dataset["text_pl"] = dataset["text_pl"].str.replace("Kochajcie się bardziej niż własne dzieci", "Kochajcie siebie nawzajem bardziej niż własne dzieci")
dataset["text_pl"] = dataset["text_pl"].str.replace("ale wy z wiarą wygracie całą wieczność na całe życie", "ale wy przez swoją wiarę zdobędziecie życie wieczne")
dataset["text_pl"] = dataset["text_pl"].str.replace("zostawiam ci spokój", "zostawiam ci pokój")
dataset["text_pl"] = dataset["text_pl"].str.replace("twoje zbawienie wkrótce nadejdzie ze mną chwalebne, uśmiechnij się i raduj", "twoje zbawienie wkrótce będzie ze mną w chwale, uśmiechnij się i raduj")
dataset["text_pl"] = dataset["text_pl"].str.replace("Mój Ojciec posyła mnie po zbawienie ludzi, proszę, nie myśl za dużo, nigdy nie zrozumiecie planów mego Ojca", "Mój Ojciec posyła mnie dla zbawienia ludzkości, proszę nie rozumujcie za bardzo, nigdy nie zrozumiecie planów mojego Ojca")
dataset["text_pl"] = dataset["text_pl"].str.replace("Dzięki za powitanie mnie", "Dziękuję, że mnie przyjęliście")
dataset["text_pl"] = dataset["text_pl"].str.replace("I Eucharystii", "i Eucharystii")
dataset["text_pl"] = dataset["text_pl"].str.replace("a co nie\.\.", "a co nie.")
dataset["text_pl"] = dataset["text_pl"].str.replace("teraz w niektórych kościołach mój Syn zniknął", "teraz mój Syn zniknął w niektórych kościołach")
dataset["text_pl"] = dataset["text_pl"].str.replace("znaki z nieba", "znaki z Nieba")
dataset["text_pl"] = dataset["text_pl"].str.replace("ale dlaczego nie powierzysz mi wszystkiego", "ale dlaczego nie ufasz mi we wszystkim")
dataset["text_pl"] = dataset["text_pl"].str.replace("Boga\.Zaczęła", "Boga. Rozpoczęła")
dataset["text_pl"] = dataset["text_pl"].str.replace("Drogie dzieci, dziękujemy, że jesteście tu zgromadzeni", "Drogie dzieci, dziękuję, że tu jesteście")
dataset["text_pl"] = dataset["text_pl"].str.replace("Zapraszam do spojrzenia na znaki, które przyjdą z nieba, dzięki którym zrozumiecie wiele rzeczy", "Zachęcam was, abyście patrzyli na znaki, które przyjdą z nieba, dzięki którym zrozumiecie wiele rzeczy")
dataset["text_pl"] = dataset["text_pl"].str.replace("mego wezwania", "mojego wezwania")
dataset["text_pl"] = dataset["text_pl"].str.replace("trudna droga, na której będziecie się śmiać i wielu odejdzie", "trudna droga, na której zostaniecie wyśmiani i wielu odejdzie")
dataset["text_pl"] = dataset["text_pl"].str.replace("aniołowie podziemia są na ziemi, by was przebiegłością zabrać, bądźcie ostrożni", "anioły podziemia są na ziemi, aby cię porwać podstępem, strzeżcie się")
dataset["text_pl"] = dataset["text_pl"].str.replace("każdego dnia łączę się z różańcem świętym, aby demony mogły zostać osłabione", "zjednoczcie się z Różańcem Świętym każdego dnia, aby osłabić demony")
dataset["text_pl"] = dataset["text_pl"].str.replace("ale daję wam siłę, by iść naprzód", "ale ja daję wam siłę, by iść naprzód")
dataset["text_pl"] = dataset["text_pl"].str.replace(" jakie napotkają na tej drodze", " jakie napotkają was na tej drodze")
dataset["text_pl"] = dataset["text_pl"].str.replace("wkrótce krzyż pojawi się w niebie i będzie przed ostrzeżeniem", "wkrótce krzyż pojawi się na niebie i będzie przed Ostrzeżeniem")
dataset["text_pl"] = dataset["text_pl"].str.replace("Miej pokój w swoich sercach i przynieś go do swoich domów", "Miejcie pokój w waszych sercach i przynieście go do swoich domów")
dataset["text_pl"] = dataset["text_pl"].str.replace("Ojca Syna", "Ojca i Syna")
dataset["text_pl"] = dataset["text_pl"].str.replace("Amen Wtedy", "Amen. Wtedy")
dataset["text_pl"] = dataset["text_pl"].str.replace("dzieci \”\. ", "dzieci. ")
dataset["text_pl"] = dataset["text_pl"].str.replace("Podczas objawienia zobaczyłam, jak niebieski krzyż świeci na czerwono", "Podczas objawienia zobaczyłam, że niebieski krzyż stał się czerwony i żarzący")







dataset.to_csv("trevignano2018.csv", index=False, encoding="utf-8")
dataset.to_json("trevignano2018.json",orient="records")






















