# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np




dataset = pd.read_csv("trevignano_2019.csv", encoding="utf-8")



dataset["author"] = np.where(dataset["text"].str.contains("Il vostro Gesù"), "Jesus Christ", dataset["author"])
dataset["author"] = np.where(dataset["text"].str.contains(" Il Vostro Gesù"), "Jesus Christ", dataset["author"])




dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Drogie dzieci, jak wiele grzechów gromadzą dzień po dniu wszyscy, Kościół, wierni i innowiercy. Dzieci moje, dlaczego pozwalacie się kusić codziennie przez zło? Dlaczego, wciąż nie rozumiecie, że są to czasy, w których prawda musi być głoszona, imię Jezusa jest drogą, prawdą i życiem, nie traćcie więcej czasu, straciliście tak wiele, teraz zapraszam was do wyznania wszystkich waszych grzechów, tych, których nie byliście w stanie wyznać aż do dzisiaj, bądźcie czyści i gotowi, bo czas jest bliski. Teraz dziękuję wam za ponowne przyjęcie mnie i błogosławię was z Matczyną Miłością, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 5)), "Drogie dzieci, dziękuję wam, że jesteście tutaj zjednoczeni w modlitwie. Moje drogie maleństwa, módlcie się, módlcie się, plagi nadchodzą i epidemie się rozprzestrzeniają, wszystko zacznie się w Rzymie, gdzie jest chory Kościół Piotra. Módlcie się moje dzieci nieustannie, czasy, które przepowiedziałem, już się rozpoczęły, ale nie lękajcie się, bo zawsze będę przy was. Moi kochani, czasy, które mają nadejść, będą czasami żniw, więc siejcie dobrze, a kto jeszcze tego nie uczynił, proszę go o nawrócenie. Dziękuję wam moje dzieci, teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 8)), "Drodzy i umiłowani bracia, dziękuję wam, że zgromadziliście się w tym błogosławionym domu. Drodzy bracia, zwiastujcie moje przyjście z radością, bądźcie radośni w waszych sercach, bo wasz Król ma być pośród was. Nie lękajcie się przyszłości, będziecie mieli naszą ochronę, tak jak przyjęliście mnie do swoich serc, tak ja powitam was w nowym Raju, pyszności są dla was gotowe, z pokojem, radością i nieskończoną miłością. Teraz przejdę obok każdego z was, aby udzielić wam mojego Świętego Błogosławieństwa, w imię Ojca, w imię moje i Ducha Świętego, Amen. Twój Jezus" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 12)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie. Moje kochane dzieci, jak ważna dla Boga jest rodzina, jest ona początkiem małego Kościoła, dlatego proszę was, abyście mieli w domach kręgi modlitewne, uczcie wasze dzieci o modlitwie i jej znaczeniu. Wy, dorośli, nabierzcie sił w Eucharystii, abyście mogli lepiej stawić czoła temu, co nadejdzie. Kocham was i z macierzyńską miłością błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 15)), "Umiłowani moi, ileż cierpień i ileż ucisków będziecie musieli znosić, ale z całą miłością, jaką mam dla was, mówię wam, że jestem z wami i zawsze będę z wami. Bracia, często jestem z wami i z całą ludzkością, często mówię w sercach, ale mnie nie słuchają, mało kto zatrzymuje się, by zapytać mnie o coś poważnego, a przecież jakże pragnę słuchać i pomagać wszystkim. Powierzcie mi się całkowicie, a ja was poprowadzę ku pokojowi, będę wam doradzał i udzielę łask, o które prosicie. Jestem tutaj, proszę was i pragnę, abyście mnie rozpoznali. Otwórzcie swoje serca i wróćcie do mnie, wszystko będzie prostsze. Zostawiam was pod opieką mojej Najświętszej Matki, kocham was. Twój drogi Jezu" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 19)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, jak wielką miłość czuję w waszych sercach, bądźcie apostołami i braćmi, bądźcie wszędzie świadkami wiary. Moje najsłodsze dzieci, modlitwy złagodziły to, co nadejdzie, ale módlcie się dalej, nigdy nie bądźcie zmęczeni, ponieważ zobaczycie, że wydarzą się niewyobrażalne rzeczy, których racjonalnie nie będziecie w stanie zrozumieć. Dzieci, wprowadźcie waszych braci na drogę miłości do mojego Syna Jezusa. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen. Moja ukochana córko, pozostanę, aby się z tobą modlić. " , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 22)), "Moi kochani, dziękuję wam, że jesteście tutaj na modlitwie. Przez cały ten czas byłam z wami, aby chronić was przed demonami, pokazując wam właściwą drogę, abyście przyszli do mojego Syna Jezusa. Prosiłam was, abyście podeszli do sakramentów, abyście przygotowali się na te czasy ostateczne. Dzieci moje, nie dajcie się skusić! Jak bardzo cierpię, gdy patrzę, jak moje dzieci się zatracają, błagam was, trwajcie w nieustannej modlitwie, jestem waszą Matką i jestem tu z wami i dla was. Teraz zostawiam was w pokoju i w moim Świętym Błogosławieństwie w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 26)), "Moje kochane dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Umiłowane dzieci, proszę i nalegam na was o nawrócenie waszych serc, kochajcie mojego Syna Jezusa, umacniajcie się Eucharystią. Smutno mi z powodu trudnych czasów, do których zmierzacie, nie ma pokoju, wszyscy są przeciwko sobie, bo nie ma już Boga w sercach. Zawsze pozostańcie zjednoczeni, dbajcie o najsłabszych, a wasze nagrody będą wielkie. Umiłowani moi, zanieście mój pokój do waszych domów, gdzie pragnę, aby były wieczerniki modlitwy. Módlcie się za Rosję. Wiele łask zstąpi na nas tego wieczoru. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 29)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na Moje wezwanie w waszych sercach. Dlaczego nie widzę wielu Moich dzieci? Przez co oni są rozproszeni! Moje kochane dzieci, dziwicie się, gdy mówię, że wydarzą się rzeczy niepojęte, pamiętajcie, że wszystko, co przepowiedziałam, wydarzy się w tym czasie, dlatego proszę was, abyście przygotowali się na wydarzenia, które nadejdą, przygotujcie się modlitwą i ofiarami, nie bójcie się, bo aniołowie, którzy są na ziemi, będą was chronić, jest ich wielu posłanych z Nieba. Bądźcie świadkami. Moje dzieci, nie bójcie się, módlcie się za Kościół, który jest podzielony i prawie rozpadł się. Zawsze miłujcie się wzajemnie, szerzcie pokój zamiast niezgody. Wzywam cię ponownie do nawrócenia, zawsze będę cię chronić jako matka. Pamiętajcie, że jesteście na świecie, ale nie jesteście ze świata.  Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])


dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 2)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moi kochani, ileż pokory i ileż miłości do Boga widzę dziś wieczorem u wielu z was, ale widzę też tyle zamętu w waszych umysłach i w waszych sercach. Proszę was, abyście nie słuchali tych, którzy chcą zmienić Słowo, to co zostało wam pozostawione nie jest do interpretacji, ale tylko do wprowadzenia w życie, bądźcie zawsze wierni Ewangelii, tam jest zapisana cała prawda. Kocham was dzieci, bądźcie zawsze świadkami wiary. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moi kochani, jak wielką radość odczuwam widząc was zgromadzonych na modlitwie w tym błogosławionym miejscu, wasze modlitwy będą wzniesione do Nieba, dziękuję wam dzieci. Moje serce jest smutne z powodu wszystkiego, co się wydarzy, a szczególnie z powodu wszystkich dusz, które uciekają przed Bożą miłością. Moje dzieci, proszę rodziny, aby uczyły swoje dzieci miłości, pokoju i miłosierdzia, ci młodzi ludzie dorastają bez Boga, dlaczego nie zdecydujecie się pozwolić Mu wejść do rodzin? Wszystko byłoby zawsze i tylko miłością. Jest to czas, w którym będą apostołowie Boga i apostołowie szatana, szczególnie w kościele będą biskupi przeciwko biskupom, księża przeciwko księżom, rodzice przeciwko dzieciom, mężowie przeciwko żonom i tak dalej, jest to czas prześladowań, wkrótce wszystko zostanie wyjaśnione. Ostrzeżenie jest na ciebie, kocham cię i wezwij mnie, a ja będę z tobą. Teraz udzielam wam mojego błogosławieństwa w imię Ojca i Syna i Ducha Świętego Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 12)), "Umiłowane dzieci, dziękuję wam, że jesteście tu zgromadzeni na modlitwie. Kiedy patrzę na was, jak pomagacie sobie nawzajem jako bracia, moje Niepokalane Serce napełnia się radością. Moje dzieci, moje objawienia nie są akceptowane ani przez część Kościoła, ani przez wiele moich ukochanych dzieci, które nie wierzą poważnie, że Trójca Święta dała ludzkości wielką szansę, pozwalając mi, Współodkupicielce, ostrzec Jej dzieci, aby powróciły do Boga. Bóg jest dobry i miłosierny, ale nie trać czasu. Jeśli prosisz Jezusa o przebaczenie z sercem, On weźmie cię za rękę. Nawróćcie się, dzieci, i bądźcie gotowi na Ostrzeżenie. Będzie to ważne wydarzenie duchowe dla każdego z was. Szukajcie siły w Różańcu, w Eucharystii i w spowiedzi, bądźcie gotowi i przeżywajcie każdy dzień tak, jakby miał być ostatnim. Teraz błogosławię was, wasze rodziny i wasze serca w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 16)), "Drogie dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Umiłowani moi, nadchodzi to, co zostało przepowiedziane, Kościół znajduje się obecnie w najbardziej całkowitym podziale, naśladowcy Jezusa przeciwko naśladowcom szatana. Moje dzieci, nadchodzą straszne czasy, ziemia zadrży jak nigdy dotąd. Miejcie wiarę w Boga, bo tylko w ten sposób pójdziecie tam, gdzie będzie pokój i nieskończona miłość, podczas gdy na ziemi śmierć grzeszników będzie nieskończona. Wy wszyscy należycie do Pana, nie lękajcie się; biada człowiekowi dumnemu i aroganckiemu, bo on odczuje całą karę Bożą. Módlcie się za Włochy i za Europę. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 19)), "Cześć, miłość i pokój w tym domu. Ja, Bóg Ojciec Wszechmogący, stwórca nieba i ziemi, jestem tu wśród was. Pytam was, dzieci, dlaczego Mnie nie kochacie, Ja jestem waszym Ojcem, jedynym prawdziwym Ojcem, kocham was miłością nieskończoną. Moje dzieci, ile radości sprawiło mi stworzenie wszystkiego, dlaczego mnie unikacie? Abyście zrozumieli, jak wielką miłością darzę moje dzieci, posłałem za was mojego jedynego Syna, aby dać wam potwierdzenie mojej obecności tutaj z wami. Aby odkupić cię od twoich grzechów, poszedł na krzyż i umarł za ciebie, jak mógłbym na to pozwolić, gdybym nie był dobrym i miłosiernym ojcem. Nie bójcie się mnie. Mówię do rodzin, nauczcie wasze dzieci widzieć we mnie dobrego Ojca, który zstępuje między was, aby was kochać. Zwierzajcie się mi, nigdy nikogo nie odtrąciłem, nie jestem zły, nie jestem tym starcem, który jest malowany, nie jestem stary ani młody, jestem Ojcem Przedwiecznym, dobrym i miłosiernym. O dzieci! Jakaż to łaska być tu z wami, chciałem was tu zgromadzić, w tym domu, który teraz należy do Mnie, jak we wszystkich domach, gdzie panuje modlitwa. Dzieci moje, przypominam wam raz jeszcze, nie bójcie się mnie. Mówię do kapłanów obecnych i nieobecnych, błagam was, uczcie przykazań, uczcie tego, co wam zostawiłem, sprawcie, aby ludzie się mnie nie bali, jestem dobrym, miłosiernym i żywym Ojcem. Krzyż i Eucharystia są tym, co musicie zobaczyć, Krzyż jest odpuszczeniem waszych grzechów i jest jedyną rzeczą, która was gromadzi, abyście przyszli do mnie, Eucharystia, o którą prosił i którą ufundował mój Syn, jest darem cudownej łaski, z której wszyscy możecie korzystać. Ja, Ojciec Wszechmogący Stwórca wszystkiego, proszę moje stworzenia, aby mnie kochały, nigdy o nic nie prosiłem, tylko o Miłość, a gdzie jest Miłość tam jestem, jesteście moją rodziną i chcę, abyście wszyscy razem jednym głosem głosili jedno, Miłość, Miłość Boga, Miłość, która pochodzi ode mnie, która przechodzi przez mojego Syna, Miłość do mojej wybranki Maryi Najświętszej Niepokalanej Dziewicy. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 22)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, dziękuję wam za to, że jako prawdziwi apostołowie jesteście tu zgromadzeni na wspólnej modlitwie. Dzieci, zgromadziłam was tutaj, abyście mogli zobaczyć i modlić się za moje łzy i za moje serce rozdarte smutkiem. Wkrótce kara zstąpi na Kościół, kara, której nie można odłożyć, aby grzech został zniszczony, zbyt wiele pychy i arogancji zrujnowało moje ukochane dzieci. Pan nie chce teologów, ale pasterzy, którzy przyjmują dusze z miłością i czułością, kochając je i prowadząc ku światłu, nie pozwalając im zejść do ciemności razem z nimi. Moje dzieci, módlcie się tak bardzo, aby kara mogła być złagodzona. Módlcie się za Amerykę. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 23)), "Umiłowane dzieci, dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Moje dzieci, zawsze podtrzymujcie płomień wiary i błagam was, módlcie się, módlcie się, módlcie się, bo czas już nadszedł. Odmawiajcie Różaniec w waszych domach i wszędzie zakładajcie wieczerniki, tylko w ten sposób będziecie chronieni przed złem, które was otacza. Bądźcie gotowi, bądźcie przebudzeni! Nie zasypiajcie tak, jak to czynili apostołowie. Jestem tu, aby cię poprowadzić. Kocham Cię i błogosławię Cię w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 26)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Służebnico Pańska, rozgłaszaj to, co ci mówię: prawdziwy Kościół wierny Jezusowi Chrystusowi znajduje się pod gruzami samego Kościoła, jeśli moje dzieci nie wyposażą się w modlitwę i pokorę, wkrótce cierpienie będzie świadkiem upadku wielu moich ukochanych dzieci. To nie jest miłość do Jezusa, ale wiara, że mogą stworzyć własną doktrynę, stawiając siebie na miejscu Boga. Moje drogie dzieci, nie będziecie mieli się czego obawiać, ponieważ przed oczyszczeniem, które ma nadejść na ziemi, będziecie chronieni i zabrani do bezpiecznych miejsc, gdzie zły nie będzie mógł was dotknąć. Módlcie się, módlcie się, módlcie się. A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])


dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 2)), "Moje drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Ukochane dzieci, wciąż dotykam ziemi z nadzieją, że wciąż będzie wiele nawróceń, słuchajcie moich przesłań, które są dane tylko z miłości do ludzkości. Kościół jest w wielkim niebezpieczeństwie, pragnę powiedzieć moim ukochanym dzieciom: miejcie odwagę, karmcie się świętą Ewangelią, pamiętajcie, że gdzie jest pycha, tam nie ma Boga, gdzie jest pycha, tam nie ma wiary, miejcie miłość do braci i bądźcie zawsze zjednoczeni w miłości Jezusa. Jutro znów będę z wami, moi Apostołowie.  A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj na modlitwie i że odpowiadacie na moje wezwanie w waszych sercach. Dzieci moje, jakże wielką pociechę odczuwam w moim zranionym sercu z powodu obrzydliwości tego świata. Słodkie stworzenia, proszę was, pozwólcie, aby wasze serce było tak traktowane, jak gliniane naczynie, aby mogło być uformowane do wielkiej miłości Jezusa. Drogie dzieci, bądźcie apostołami światła, bądźcie spokojni dla tych, którzy nie wierzą w moją rzeczywistą obecność w tym miejscu pobłogosławionym przez Ojca, ponieważ moja obecność i moje instrukcje dla waszego zbawienia będą grzmiały z jednego końca świata na drugi, aby mój lud mógł się zgromadzić, aby kochać Jezusa i być gotowym na nadchodzące dni. Bądźcie Moimi apostołami, bądźcie solidnymi murami i twierdzami dla dusz letnich. Teraz zostawiam was z moim Świętym Błogosławieństwem, w Imię Ojca, Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 5)), "Drogie dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Umiłowane dzieci, tak wielu prosi o znaki przyjścia mojego syna Jezusa, nie będziecie już wierzyć w grzech, gdy w kościele nastąpi protestantyzacja, to będą znaki, które wskażą wam jego przyjście. Dzieci moje, jest to czas, kiedy demony ożywają bardziej niż kiedykolwiek na ziemi, plan diabła jest w najwyższym stopniu wypełniony, nie dajcie się zwabić blaskowi świata, jestem tu, aby was chronić, kocham was z całego serca. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 12)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, nie bójcie się tego, co się wydarzy, trwajcie w modlitwie, pokucie i wyrzeczeniach w tym okresie wielkanocnym. Umiłowani moi, Pan Jezus Chrystus jako mój słodki Syn jest nadal prześladowany, szczególnie przez ludzi Kościoła, biada, 10 razy biada tym, którzy są na szczytach Kościoła, mówię o biskupach i kardynałach, którzy wykorzystują święte posłuszeństwo, aby prześladować świętych kapłanów, którzy są wierni Ewangelii i walczą o Prawdę i Słowo Boże, za to sprawiedliwość Boża będzie 10 razy gorsza. To, co zostało napisane, spełni się, kochajcie się jak bracia. Módlcie się za Rosję i za Francję. Teraz zostawiam wam moje święte błogosławieństwo, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 16)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, jakże wielką pociechę czuję w sercu widząc was tutaj na modlitwie, to jest mój Kościół, znam wszystkie wasze utrapienia, ale proszę was, powierzcie się mojemu Jezusowi, aby dał wiele łask dla was wszystkich, dzisiaj będą uzdrowienia. Drogie dzieci, bądźcie blisko Boga z całego serca, bo czasy, które nadejdą, będą trudne. Dlaczego tak wiele z moich dzieci decyduje się stanąć po stronie zła? Ten, kto ma wiarę i obserwuje prawa Boże, nie powinien się niczego obawiać. Skarby moje, zmiłujcie się nad tymi, którzy błądzą, kochajcie ich. Bądźcie blisko Ewangelii i Słowa, przede wszystkim kochajcie tak, jak Bóg was kocha i przebaczajcie tak, jak On przebacza, aby otworzyło się Królestwo Niebieskie, abyście mogli cieszyć się tym, co jest dla was przygotowane. A teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 19)), "Dzieci moje, ja Syn Ojca, proszę was w tym okresie Wielkiego Postu, poświęćcie się dla mnie. O! ileż to razy szedłem do moich konsekrowanych, aby zapytać, gdzie są dusze, które mi przyprowadzacie, a jednak ich nie ma, ileż to wybranych dzieci mijałem, aby zapytać o to samo i ileż to dusz znalazłem, które zbliżyły się do mojego serca i do serca mojej Matki. Dlatego wybieram według otwartych serc, które mają serca dzieci i dusze zwrócone ku Niebu, a nie tych, którzy piją kielich światowości i ziemskich przyjemności. Bracia, pragnę, abyście byli jedną duszą z Moją. Moja wybrana córko i siostro, dziękuję ci za twój pokój, mimo wszystko, znam twoje cierpienie, ale wiem, że ofiarowujesz mi wszystko, dlatego cię kocham, jak wielką miłość czuję w twoim sercu do mnie, ale powiedz mi, jak bardzo mnie kochasz? Jak bardzo chcesz dla mnie cierpieć? To jest to, czego chcę. Twoi bracia i Twój umiłowany małżonek są dla mnie światłem i miodem na moje cierpienia. Kocham was wszystkich i chciałabym wam pokazać, jak bardzo jesteście wyjątkowi dla Nieba. Błogosławię Cię, Twój drogi Jezu" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 23)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Drogie dzieci, w tym czasie wielkanocnym kontynuujcie pokutę i wyrzeczenia. Dzieci moje, proście o dar Ducha Świętego wraz z siedmioma darami, wzywajcie Go, a On zstąpi na was. Dzieci moje, czasy, które nadchodzą będą bardzo trudne, umacniajcie się w wierze i badajcie swoje sumienia, kiedy idziecie do kościoła na Mszę Świętą, myślicie, że obmyliście swoje sumienia, ale to nie jest droga do pokoju z Bogiem, musicie żyć nią intensywnie, a nie tylko uczestniczyć, konieczna jest spowiedź i komunia z innymi. Twórzcie wieczerniki modlitwy. Ziemia zadrży ponownie, Watykan zostanie wstrząśnięty, módlcie się za Amerykę, która będzie dręczona przez naturę. Błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 26)), "Drogie błogosławione dzieci, dziękuję wam, że jesteście tu zgromadzeni na modlitwie, łagodząc bóle mojego Syna Jezusa. Moi umiłowani, nawrócenie jest tym, o co nieustannie proszę w miejscach, gdzie się pojawiałam i gdzie nadal się pojawiam, tylko w ten sposób będziecie mogli wejść do Królestwa Niebieskiego. Mój Syn chce, abyście wszyscy zostali zbawieni, grzesznicy i nie-grzesznicy, pamiętajcie, że Bóg kocha wszystkich jednakowo, czeka na swoje dzieci z miłością, cierpliwością i Miłosierdziem. A teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 30)), "Drogie dzieci, dziękuję wam, że jesteście tutaj zgromadzeni na modlitwie, odpowiadając na moje wezwanie w waszych sercach. Umiłowane dzieci, moja mała trzódko, bądźcie napełnieni Duchem Świętym, modlę się za każdego z was przed Bogiem, aby ogień Ducha Świętego rozpalił waszą duszę, waszego ducha. Umiłowani moi, błagam was, bądźcie mocni w wierze, a szczególnie w prawdziwej i jedynej nauce chrześcijańskiej, w tym czasie wiele rzeczy będzie wam odmawianych przez moje umiłowane dzieci, ale nie płaszczcie się przed modernistycznymi zmianami i pochwałami, ponieważ nie pochodzą one od Boga. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])

dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 2)), "Drogie uwielbione dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moi kochani, wojna jest blisko, módlcie się dużo z różańcem świętym w rękach, tylko z prawdziwą wiarą można coś zmienić. Dzieci moje, dlaczego nadal umartwiacie mojego Syna Jezusa, On umarł, aby was odkupić od waszych grzechów, nie bądźcie bogiem dla samych siebie, pamiętajcie, że łatwe drogi pochodzą od szatana, ale do tych Bożych dochodzi się tylko przez cierpienie. Moje dzieci, nie dajcie się oślepić fałszywym światłom, kochajcie mojego Syna i krzyż, tylko w ten sposób możecie być godni Jego Miłości i Pokoju. A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję, że jesteście tutaj na modlitwie i dziękuję, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, jestem tu dzisiaj ponownie, aby przypomnieć wam, abyście otworzyli wasze serca i rozpoczęli prawdziwe nawrócenie. Dzieci, oddajcie mi wszystkie wasze utrapienia, a ja was podniosę, wzywajcie mojego Syna, a będzie blisko was, aby was chronić, szczególnie w chwilach utrapienia, proszę was, abyście mnie kochali i byli zjednoczeni w dniach trudności, które nadejdą, Bóg pragnie tylko miłości, pozwólcie się przytulić do Niego jak dzieci. Dzieci moje, twórzcie kręgi modlitewne w waszych domach, a szczególnie uczcie wasze dzieci miłości do Ojca i miłości Ojca do nich. Umiłowani moi, nie bójcie się, dopóki Ja jestem z wami, nie macie się czego bać, umacniajcie się w wierze, tylko w ten sposób będziecie bezpieczni. Teraz zostawiam was z moim matczynym błogosławieństwem, przyjmijcie pokój do waszych domów, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 6)), "Umiłowani moi, jestem Niepokalane Poczęcie, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszym sercu, jesteście tutaj na modlitwie w tym błogosławionym miejscu, słucham waszych błagań i próśb, bo wiem, jak skruszone jest wasze serce, odmawiajcie zawsze Różaniec święty, jeśli chcecie oddalić wojnę, która jest coraz bardziej nieuchronna. Wasza wiara da wam pokój i radość; módlcie się za młodych ludzi, których szatan ciągnie w stronę ciemności. Dziś udzielę kilku łask. Módlcie się, módlcie się, módlcie się z miłością, a ja wyślę światło do waszych serc, otwierając je na Łaskę. A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 9)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, bądźcie gotowi, bo znak uderzający, na który czekaliście, już wkrótce nadejdzie. Umiłowane dzieci, bądźcie gotowi na to, że gdy ogień Ducha Świętego wtargnie do waszych serc. Biada tym, którzy nie będą, bo zostaną ogarnięci wielkim cierpieniem. Drogie dzieci, znajdujemy się teraz w czasie, gdy Niebiosa się otworzą i usłyszycie trąby anielskie, a oczyszczenie będzie silniejsze niż wcześniej. Moje kochane dzieci, wkrótce Eucharystia zostanie usunięta z Kościoła. Módlcie się, módlcie się, módlcie się za władców Ameryki, aby nie podejmowali złych decyzji. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 13)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, jak wiele smutków słyszę, jestem tu, aby was prowadzić ku światłu Pana. Drogie dzieci, przyszedłem dotknąć ziemi, ale niewielu słucha moich orędzi, wiedzcie, że wkrótce ziemia zadrży, ale wy jesteście w radości i miłości Boga, nie zgubcie się, waszym źródłem musi być Ewangelia. Umiłowane dzieci, w tym tygodniu wielkanocnym, kochajcie Krzyż i dziękujcie Panu, nie zawsze będziecie mogli zrozumieć wszystko, co jest Bożym planem i często jest to po ludzku niezrozumiałe, tylko niebo i modlitwa będą w stanie odpowiedzieć na wasze pytania, jeśli otworzycie wasze serca. Nie zmieniajcie waszych modlitw i nie zmieniajcie niczego z dogmatów wiary, bo to byłoby bluźnierstwo, szatan jest przebiegły, zabiera dusze, a wy tego nie zauważacie. Kocham was, jestem waszą Matką, chronię was i umieszczam was wszystkich pod moim płaszczem. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 16)), "Bracia, bądźcie namaszczeni przez mojego Ducha Świętego w tę Wielkanoc, bo wszystko będzie wam odpuszczone, nawet najgorszym grzesznikom. Stworzyłem tę rodzinę, abyście mogli zjednoczyć się przed moim Mistycznym Ciałem. Nie opuszczajcie mnie, patrzcie na znaki czasu i nie bójcie się, jestem z wami i będę z wami. Powiedz nawet bluźniercom, nawet najbardziej zatwardziałym grzesznikom, aby prosili mnie o przebaczenie, a przebaczenie zostanie im udzielone. Umiłowane dzieci, gdybyście tylko wiedzieli, jak bardzo was kocham! Jako dzieci i bracia, proszę was, nie zostawiajcie mnie samego w tym czasie cierpienia; oni mnie obdzierali, wyśmiewali i poniżali, i tak samo stanie się z wami w moje imię; będziecie poniżeni i obdzierani, ale jakże wielkie będzie Królestwo Niebieskie, które wam obiecałem! Kocham was bracia i błogosławię was wszystkich, wasz brat Jezus. Dziękuję za ponowne przyjęcie mnie do tego domu." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Drogie dzieci, dziś mija trzeci rok, jak objawiam się wam z miłością w tym błogosławionym domu, gdzie zostałam przyjęta w miłości rodziny. Umiłowane dzieci, dziś z wielką radością obchodzicie Wielkanoc, mój Syn, który umarł, zmartwychwstał dla was i prosi, abyście razem z Nim zmartwychwstali w waszym życiu, wyjdźcie z waszych grobów, uwierzcie i dajcie świadectwo mojemu zmartwychwstałemu Synowi. Moje kochane dzieci, noście i kochajcie wasz krzyż i jak Cyrenejczyk towarzyszył Jezusowi, tak wy musicie pomagać waszym braciom. Moje dzieci, umarli dołączą do żywych na tej wielkiej uczcie, a waszą pracą od dzisiaj będzie praca na tej ziemi dla życia wiecznego. Kocham was i jako Matka błogosławię was w imię Ojca, Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 28)), "Umiłowane dzieci, dziękuję wam za to, że jesteście tutaj na modlitwie. Drogie dzieci, wasze modlitwy pocieszają moje serce i przynoszą ulgę w cierpieniach Jezusa, który bardzo cierpi z powodu wszystkich niesprawiedliwości i brzydoty tego świata, który teraz wydaje się być zdominowany przez szatana. Wkrótce Jezus przyjdzie, aby uwolnić cię od tego całego zła. Będzie więcej cierpienia i zniszczenia. Umiłowane dzieci, sprawiedliwość jest na was. Otwórzcie oczy i bądźcie zawsze z różańcem w ręku. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 30)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, czasy są ciężkie, a to nie jest najgorsze, bo najgorsze dopiero nadejdzie. Czas wydaje się wam płynąć bardzo szybko, mój Jezus się spieszy, apostazja jest już w kościele i jest tak oczywista, że zamieszanie będzie nadal was zaślepiać, proszę rodziny, aby tworzyły w domach wieczerniki modlitewne, uczcie wasze dzieci odmawiać Różaniec Święty, matki uświęcajcie się, naśladując mnie. Teraz diabeł wchodzi do rodzin, ale jeśli będziecie postępować zgodnie z moimi instrukcjami, nie będzie mógł wejść. Zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])

dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, jaka to dla mnie radość widzieć was zjednoczonych, lud Boży zgromadzony jako bracia w miłości i uwielbieniu Boga. Moje dzieci, nadszedł już czas, Kościół odrzuca modlitwę i prawdziwą naukę wiary, szatan myśli, że osiągnął swój cel, niszcząc to, co zostało stworzone z tak wielką miłością, ale wiedzcie, że wkrótce moje Niepokalane Serce zatriumfuje i chcę, abyście byli uczestnikami tego Triumfu, nawrócili się dokonując wielkiego oczyszczenia z piękną spowiedzią,abyście byli misjonarzami pokoju, pogody ducha i odwagi w wierze. Moje dzieci, nadal jestem tutaj, aby was kochać i umieszczam was wszystkich pod moim błogosławionym płaszczem. Kochaj Jezusa, bądź Mu wierny, a łaski będą obfite. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 4)), "Drodzy bracia, dziękuję wam, że jesteście przy mnie w tych czasach męki, jestem tu dzisiaj, aby wam powiedzieć, że jest to czas "tak - tak", "nie - nie", albo ze mną, albo przeciwko mnie. Ciągle zadaję sobie pytanie, ile wiary znajdę jeszcze na ziemi, ja, który uczyniłem moje ukochane dzieci moim obrazem, dając im Ducha Świętego, aby przemieniły Hostię w moje żywe ciało, a wino w moją krew, a one mnie zdradzają. Nie! Nie chcę więcej słyszeć o tym obrzydlistwie. Umiłowani bracia i dzieci, przygotujcie się, bo wkrótce przyjdę zabrać was tam, gdzie wszystko jest przygotowane dla waszej ochrony. Obejmę was wszystkich z ogromną miłością. Teraz proszę was, nie opuszczajcie mnie i nie porzucajcie waszej wiary we mnie. Teraz dotknę was po kolei przez moje święte błogosławieństwo, Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 7)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moi kochani, rozejrzyjcie się wokół siebie, diabeł chce przejąć władzę, dlatego proszę was, abyście dużo się modlili i zintensyfikowali kręgi modlitewne. Dzieci moje, miejcie odwagę i żyjcie z odwagą jak apostołowie w miłości Bożej, chwyćcie bez lęku za broń, którą jest wiara, tolerancja, cierpliwość, miłość, braterstwo i bądźcie światłem dla wszystkich. Drogie Dzieci, powiedzcie światu, żeby się szybko nawrócił, bo czas płynie nieubłaganie. Ochrzcijcie dzieci i uniknijcie ich potępienia, wkrótce wszystko, co przepowiedziałam, wydarzy się w bardzo krótkim czasie, bądźcie gotowi. Ogień zstąpi z nieba. Zostaniecie napełnieni Duchem Świętym. Teraz zostawiam was z błogosławieństwem Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 11)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje kochane dzieci, dziękuję wam, że przyjęliście mnie z wiarą w waszych sercach. Moje drogie dzieci, jestem zawsze z wami, abyście nie zbłądzili. Wasza droga jest wyznaczona, ale czasami jesteście zdezorientowani i nie idziecie w kierunku Jezusa. Nie dajcie się zdezorientować. Proszę was, mój ludu, abyście słuchali moich słów, abyście czytali Ewangelię i Słowo Boże. Tylko w ten sposób będziecie mogli podjąć drogę świętości. Moje dzieci, to was proszę o pomoc w ratowaniu Kościoła i to was nadal proszę, abyście byli wojownikami światła, dzisiaj Kościół sieje zamęt i wszystko jest w waszych rękach, idźcie i siejcie słowo Boże, demony wprowadzają tyle zamętu. Zbierzcie się w kręgach modlitewnych w waszych rodzinach. Słuchajcie wiatrów wojny, nie tylko są bomby atomowe. Wojna światowa już się rozpoczęła. A teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 14)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie. Moja córko, prawda jest wypaczana zwłaszcza przez moje osoby konsekrowane, proszę je o zrobienie rachunku sumienia i stanięcie w prawdzie Ewangelii. Odmawiajcie razem z wiernymi Różaniec Święty, nie zostawiajcie trzody samej, ale bądźcie prawdziwymi pasterzami. Miasta zostaną zalane. Żyj ze wzrokiem zwróconym ku niebu. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 18)), "Moje dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowani moi, wkrótce niebo się otworzy i ujrzycie królestwo Boże ze wszystkim, co zostało dla was przygotowane. Bądźcie wierni Jezusowi, ponownie wzywam was do pilnego nawrócenia. Umiłowani moi, nie macie więcej czasu, wkrótce zobaczycie powrót mojego Syna Jezusa, Jego powtórne przyjście będzie niedługo, ale najpierw zobaczycie wielkie znaki z Nieba. Oto sprawiedliwość Boża jest nad wami, nie bądźcie związani z ziemskimi rzeczami, wszystko zostanie zmiecione, zadajcie sobie pytanie, dlaczego te powodzie, te silne wiatry, te huragany. One mają przyjść i dzieją się tylko po to, abyście zrozumieli, że Bóg jest jedyną ważną rzeczą, teraz i zawsze, On was kocha, ale wielu z was straciło wiarę z powodu demonów, które wiedzą jak mocno dmuchać w umysły niszcząc myśli. Będzie silne trzęsienie ziemi, módlcie się, módlcie się za Amerykę, bo będzie piła gorzki kielich z powodu wielkich grzechów. Bądźcie silni, dzieci, na to, co was czeka. Teraz zostawiam was i błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 21)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, zachęcam was do życia orędziami, które wam zostawiam i do częstego komentowania Ewangelii. Drogie dzieci, jeszcze raz wzywam was do pilnego nawrócenia; czy nie rozumiecie, że nie macie już czasu? Nie ma już czasu do stracenia, bo to jest skończone, rozejrzyjcie się wokół siebie, chcą zniszczyć mój Kościół, także od wewnątrz. Będą ataki terrorystyczne na świecie. Dzieci, módlcie się, aby przemawiał przez was Ducha Świętego. Brońcie prawdziwej wiary chrześcijańskiej i nie zniekształcajcie jej. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 25)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie. Jak wielką wiarę czuję w waszych sercach! Miłość i odwaga dla wiary, dla mojego Jezusa i dla mojego Kościoła, który diabeł chce zniszczyć; bądźcie prawdziwymi apostołami. Dzieci moje, diabeł chce was zwieść i teraz znajdzie wszystkie sposoby, by się w was wkraść, nie pozwólcie mu na to, módlcie się, on zawsze się czai, bo wie, że jego czas się skończył. Płaczę z powodu wszystkiego, co się wydarzy, nawracajcie się i bądźcie zawsze wierni prawdziwemu Kościołowi.  Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 28)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie. Moje dzieci, drogie memu błogosławionemu sercu, ileż to razy mówiłem wam, abyście modlili się o te chwile, teraz one nadeszły, ale ilu z was czuje się gotowymi do stawienia czoła tym ostatnim chwilom! Umiłowane dzieci, jestem tutaj, aby was chronić, wkrótce nie będziecie mieli nic, spójrzcie na zamęt, który panuje na ziemi i wokół was, to są znaki widoczne dla wszystkich, dokąd uciekacie, dzieci, czego szukacie, jeśli nie Boga? Diabeł dotknie miejsc i ludzi, których nigdy byście sobie nie wyobrazili. Dzieci, módlcie się, módlcie się, módlcie się. Teraz nakładam na was mój błogosławiony płaszcz i błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])

dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 1)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie. Dzieci moje, jakże wspaniałym Darem obdarzył was Ojciec, zarówno was, jak i wszystkich tych, którzy poznali mojego Syna Jezusa. Wy, jako narzędzia, zawsze bądźcie latarniami światła, nigdy nie gaście swoich lamp, ale nieście światu światło, którym jest miłość i pokój. Drogie dzieci, jakże wielkie i pokorne są wasze serca! Będę was chroniła przed każdym atakiem złego. Swoim tak, zapaliliście latarnię na świecie i zawsze będę z wami razem z moim Jezusem. Dzieci moje, dajcie świadectwo i sprawcie, aby wszyscy słuchali moich orędzi. Czasy będą ciężkie, ale nie będziecie sami, moi aniołowie nie pozwolą, aby dotknęli was ci, którzy są w szponach zła. Teraz zostawiam was z moim świętym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Drogie dzieci, kochajcie mojego Syna Jezusa, zamieńcie nienawiść na miłość, gniew na przebaczenie, egoizm na bezinteresowność, pychę na pokorę i miejcie rozsądek ducha, to są rzeczy, o które was proszę, nie macie wiele czasu na nawrócenie. Proszę, moje dzieci, nie każcie mi więcej płakać i nie każcie więcej cierpieć sercu Jezusa, czyż nie wycierpiał On już wystarczająco dużo dla was? Czy ludzkość nie zrobiła już zbyt wiele krzywdy Bogu, który cię kocha, chroni i jest przy tobie od pierwszego krzyku? Jednak, jak ludzie podziękowali Jezusowi? Przez bluźnierstwo i wejście w wieczne potępienie. Dlaczego kochasz najwygodniejsze życie, domagając się łask? Otwórzcie wasze serca na radość miłości Jezusa, a wszystko będzie łatwiejsze. Dzieci moje, jestem matką i nie opuszczam was. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen. Pozostanę z wami w modlitwie." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 8)), "Drogie dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach.Umiłowane dzieci, dziękuję wam za waszą wiarę. Dzieci moje, zostanie wam powierzona misja rozsławiania mojego Syna, gdziekolwiek pójdziecie. Wkrótce ci, którzy mają wiarę, otrzymają dar Ducha Świętego i stanie się to nagle, poczujecie się radośni i gotowi do niesienia Słowa tym, którzy go nie znają. Moi kochani, proszę was, abyście byli przywiązani do Ewangelii i do prawdziwej, jedynej nauki wiary. Dzieci moje, płaczę, bo wiem, co was spotka, więc proszę, bądźcie zawsze gotowi. Kościół przejdzie wielką odnowę, usuwając to, co złe i wszystko wróci na swoje miejsce, to zadanie jest teraz powierzone wam, świeckim. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 11)), "Moje kochane dzieci, dziękuję wam za to, że jesteście tutaj na modlitwie, pocieszając moje serce i serce Jezusa waszą obecnością i waszymi modlitwami. Moje dzieci, pamiętajcie, że wkrótce Boża sprawiedliwość będzie bardziej przytłaczająca, ale nie bójcie się, raczej bójcie się, gdy nie będziecie już czuli Boga przy sobie, wtedy będziecie musieli się bać. Trzęsienia ziemi będą następowały jedno po drugim, wkrótce zniknie Eucharystia, ale bądźcie wierni i walczcie jak żołnierze, wiele będzie cierpień, ale kto uwierzy, będzie zbawiony. Teraz zostawiam wam mój pokój i błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 15)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje kochane dzieci, jak wiele jest waszych cierpień, pamiętajcie, że nie ma krzyża, który nie prowadziłby do Boga, kochajcie go i noście go z miłością i pewnością, że Jezus jest obok was. Moi kochani, ileż to słów zostało wypowiedzianych w tych latach, a jednak pomimo znaczących znaków, wciąż nie wszystkie serca się nawróciły. Wołałem do was, pokazując wam mój ból, a wy nadal nie rozumiecie, oto czas łaski się skończył, czas sprawiedliwości nad wami. Proszę tylko o miłość, miłość nawet do was samych, zamiast tego nadal widzę, jak moje dzieci podążają drogą, która prowadzi do piekła. Twoje życie wieczne ma wielką wartość dla Boga, pracuj dla życia wiecznego. Módlcie się za Kościół, gdzie trzęsienie ziemi będzie silne i będzie miało poważne konsekwencje. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 18)), "Moi drodzy bracia, dziękuję wam, że jesteście tutaj na modlitwie. Ja, wasz Jezus, jestem tu z wami i widzę wasze serca. Bracia, jakże liczne są wasze obawy, ale to jest miara waszej wiary. Wkrótce przyjdę, aby was objąć i zabrać do miejsc bezpiecznych. Widok wielu moich konsekrowanych dzieci i braci, którzy odrzucają moją Matkę, sprawia mi wielki ból i będzie to jedną z głównych przyczyn silnych trzęsień ziemi, które nastąpią w Kościele. Uklęknijcie i módlcie się do mojej Najświętszej Matki, aby wstawiała się za waszymi cierpieniami. Bracia, będzie jeszcze wiele innych sygnałów, które wprawią ziemię w drżenie. To, co powierzyłem ludzkości, zredukowaliście do gnijącego świata. Nawróćcie się przez świętą spowiedź. Teraz błogosławię was w imię Trójcy Świętej, Amen. Twój Jezus" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 22)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach, niektórzy z was wyjdą z tego spotkania bardzo odmienieni z otwartymi sercami. Uwielbiane dzieci, dlaczego wciąż każecie cierpieć mojemu Synowi Jezusowi? [i tam Matka Boża pokazała mi serce, które trzymała w rękach i które krwawiło]. Patrzcie! Serce mojego Syna krwawi z powodu cierpień każdego dnia i pomimo wszystko, On nadal zsyła miłosierdzie dla moich ukochanych dzieci. Moje dzieci, wkrótce wszystko się zmieni. Kościół, ludzkość i świat nie są już niestety w zgodzie z Bogiem Ojcem. Wiele będzie wydarzeń, które przyniosą zmiany, ale wy módlcie się, módlcie się tak bardzo moje dzieci, ponieważ wszystko można złagodzić. Dziękuję, że przyjęliście mnie z miłością serca. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 25)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, proszę was o pilne nawrócenie; nie ma już czasu, po wszystkich znakach, które przychodzą z nieba, dlaczego jeszcze nie wierzycie! Zadawajcie sobie pytania, nawracajcie się, ponieważ najgorsze dopiero przed wami, a wy nie jesteście gotowi. Moje kochane dzieci, kiedy nie będzie już Eucharystii, kiedy kościół nie będzie już nazywany domem Bożym, ale po prostu miejscem modlitwy, nie stańcie się niewiernymi, walczcie o Prawdę. Dzieci moje, pamiętajcie, że Bóg jest Miłością, Życiem i Prawdą i On jest waszą jedyną pewnością, nie przywiązujcie się do rzeczy materialnych, bo one wkrótce znikną. Wy, dzieci, zrozumcie, że jedyna pewność jest w Bogu, a nie w tym, co budujecie. Ziemia będzie nadal drżeć. Módlcie się za papieża. Teraz zostawiam was z moim Świętym Błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 29)), "Drogie dzieci, dziękuję wam, że jesteście tutaj zgromadzeni na modlitwie i dziękuję za całą miłość, którą czuję w waszych sercach. Moje kochane dzieci, nie bójcie się, jestem tu z wami i zawsze będę. Ofiarujcie mojemu Synowi wasze udręki, a On przemieni je w radość, wasze złe myśli, a On przemieni je w myśli miłości. Moje dzieci, wkrótce będziecie mieli uderzające wieści i wielki fałsz pochodzący z Siedziby Piotra. Módlcie się i przebaczajcie. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])


dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 2)), "Umiłowane dzieci, dziękuję wam, że jesteście tu zgromadzeni na modlitwie i dziękuję, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, dlaczego jeszcze nie nawróciliście się całkowicie! Musicie powiedzieć, zwłaszcza moim umiłowanym synom (kapłanom), aby nauczali słowa Bożego i mówili o Ewangelii, bo nie chcę widzieć, jak moje dzieci wpadają w otchłań. Teraz, dzieci, mój Jezus jest miłosierny, ale nie czekajcie dłużej, nadszedł czas. Ziemia będzie nadal drżeć coraz bardziej. Teraz zostawiam wam mój pokój, zabierzcie go do waszych domów, błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen. Dzieci moje, jutro znów będę z wami." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, proszę was o pokój, pokój między ludźmi, pokój w rodzinach, pokój między narodami i mocarzami tego świata. Dzieci moje, pokój między ludźmi musi być ponad wszelkim narodem, ponad wszelką religią, ponad wszelką rasą. Pokój oznacza również szacunek dla różnych wyznań, ale wy, miłujcie się wzajemnie jak bracia w miłości jednego Boga, który Jezusa uczynił człowiekiem i umarł za was na krzyżu dla waszego zbawienia i za wasze grzechy, który zostawił swoje Słowo, które jest jedno, dla wszystkich i na wieki. Wszystkie religie nie mogą trwać w jednej modlitwie w Domu Bożym, mój Kościół będzie zbawiony przez waszą Wiarę. A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen. Dziś wiele będzie łask, które zstąpią na was." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 9)), "Drogie kochane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, jak wiele brzydoty jest na tym świecie i wszystko to sprawia ból mojemu sercu i sercu mojego Syna. Dzieci moje, módlcie się, aby mój Syn Jezus mógł uprzedzić o czasie swego przyjścia. Wielkie rzeczy czyni Wszechmogący dla tych, którzy mają wiarę. Módlcie się za świat, a szczególnie za Amerykę. A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 13)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, wszystko, co się dzieje, zostało przepowiedziane, wielu prosi o znaki przed przyjściem Jezusa, ale po tym wszystkim, co się dzieje, trzęsieniach ziemi, wodach, które zstępują z nieba z mocą i wkraczają do miast, wy nadal nie rozumiecie, mimo wszystko. Dzieci moje, nie czekajcie, nie macie już czasu, bo wasz grzech jest zbyt wielki. Módlcie się dzieci, nie czekajcie na zimną noc, módlcie się za Włochy, które odmawiają łaski i módlcie się za Amerykę, która wpuściła szatana do swojego narodu, nawróćcie się.  A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 16)), "Moje kochane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie, niech pokój zstąpi do waszych serc. Dzieci moje, módlcie się za Kościół, módlcie się za kapłanów, biskupów i kardynałów, aby otworzyli swoje serca na łaskę, nie lekceważąc sakramentów, zwłaszcza Eucharystii. Moje dzieci, błagam was, weźcie mnie za ręce, abym mogła was zaprowadzić do mojego Syna Jezusa. Umiłowane dzieci, proszę was, abyście organizowali wieczerniki w domach i rodzinach, abyście byli lepiej chronieni. Różaniec jest potężną modlitwą przeciwko złu, nigdy o tym nie zapominajcie. Teraz zostawiam was z moim świętym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 20)), "Drodzy bracia, dziękuję wam, że zgromadziliście się tutaj na modlitwie. Bracia moi, o ileż to łask prosicie, ale czy zadaliście sobie pytanie, jak wielka jest wasza wiara? Mam nadzieję, że już niedługo będę mógł Was objąć i wreszcie będę mógł Was zadowolić wspaniałościami, które dla Was przygotowałem. Umiłowani bracia, miłujcie Boga w całej Jego pełni, nawróćcie się, czas się skończył, sprawiedliwość już na was czeka, zobaczycie kule ognia spadające z nieba, ziemia nie przestanie się trząść, powrócą stare i pogrzebane choroby i pojawią się nowe. Módlcie się za moich apostołów i za tych, którzy poślubili Boga, Kościół Piotra będzie wkrótce zamieszkany przez rewolucję, módlcie się za możnych tego świata, aby zapanował pokój. Bracia moi, dlaczego odwracacie się, udając, że świat zawsze taki był, nie chcecie zmienić swojej postawy wobec ogromnej miłości Boga, nie chcecie zrozumieć, że wszystko, co jest częścią tego świata, wkrótce już nie będzie istniało, ponieważ zostało opanowane przez szatana, i co robicie? Zamiast podążać drogą sprawiedliwych, obieracie najwygodniejszą, z najprostszymi rzeczami, która jest drogą diabła, a potem umieracie wiecznie. Walczcie o życie wieczne i nie wpadajcie w płomienie piekielne, które jak długie języki ognia szukają waszych dusz. Bracia, nie mówię tego wszystkiego, aby was przestraszyć, ale tylko po to, aby wstrząsnąć waszymi sumieniami i abyście zrozumieli, co was czeka, obierzcie drogę Bożą, owszem, może trudniejszą, ale bezpieczną i z pomocą Moją i Mojej Matki będziecie bezpieczni i wszystko będzie łatwiejsze. A teraz udzielam wam Mojego świętego błogosławieństwa w imię Ojca, w Imię Moje i Ducha Świętego, Amen" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 23)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowani moi, radujcie się, bo wkrótce mój Syn Jezus będzie wśród was, aby odnowić ziemię. Kościół zostanie odnowiony dopiero wtedy, gdy z tego starego kościoła, wraz z tymi, którzy czczą szatana, nie pozostanie nic oprócz prochu. Módlcie się dzieci, módlcie się, aby serca otworzyły się na Bożą miłość, bo dlaczego nie możecie kochać tak, jak On was kocha z ogromną miłością? On cię stworzył i troszczył się o ciebie! Módlcie się za papieża, który wkrótce zostanie zaatakowany. Drogie dzieci, wkrótce na niebie pojawi się światło i zrozumiecie, że Bóg jest tutaj dla was i wtedy poprosicie sercem o przebaczenie, a On w swoim nieskończonym Miłosierdziu przyjmie was, lecz nie czekajcie do tego czasu. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 25)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj, w tym błogosławionym domu. Chciałam, aby ten Różaniec był tu dzisiaj ponownie, abyście jeszcze raz mogli zobaczyć cud moich łez. Moje dzieci, czuję tak wielką miłość, ale jednocześnie macie skruszone serce. Drogie dzieci, ileż chorób i ileż rzeczy wydarzy się na tej ziemi, wszystko to zostało napisane i tak będzie, ale nie bójcie się, będziecie mieli naszą ochronę, nie bójcie się. Kochajcie mojego Syna Jezusa i módlcie się, błagam was, módlcie się dużo o pokój. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen. Matka Boża położyła ręce na każdego z nas i udzieliła swojego świętego błogosławieństwa." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 27)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach i że jesteście tutaj na modlitwie. Umiłowane dzieci, módlcie się, módlcie się, módlcie się za Kościół, ufajcie mojemu Ojcu, nie osądzajcie, aby wiara nie doznała uszczerbku przez osądy, ale kochajcie tylko Boga, jak was nauczono, przestrzegajcie przykazań i bądźcie zawsze przywiązani do Ewangelii. Moje umiłowane maleństwa, pamiętajcie, że Pokój między ludźmi i między wami jest tym, o co was proszę, ponieważ tylko poprzez pokój wszystko może być złagodzone i tylko Pokój w waszym życiu prowadzi was do miłości. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 30)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie. Patrzę i nie widzę moich dzieci, ile razy mam wam powtarzać, abyście zostawili rzeczy tego świata i myśleli o duchu! Umiłowani moi, ja, który przybywam z łaski Ojca, zstępuję na was, aby was chronić i pouczać dla dobra waszej duszy, ale często nie jestem wysłuchiwana, nie mam już łez. Moje dzieci, musicie się modlić, modlić, pościć i czynić pokuty, szczególnie za Kościół, za biskupów i kardynałów, nie wiecie, co was czeka, wszystko jest przygotowane do wojny, módlcie się, módlcie się, módlcie się, módlcie się tak bardzo. Błogosławieni, którzy będą mieli Wiarę. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])

dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 22)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 26)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 29)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 22)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 26)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 29)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 22)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 26)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 29)), "" , dataset["text_pl"])


dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 22)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 26)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 29)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 22)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 26)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 29)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 22)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 26)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 29)), "" , dataset["text_pl"])



dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 22)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 26)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 29)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 22)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 26)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 29)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 22)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 26)), "" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 10) & (dataset["day"] == 29)), "" , dataset["text_pl"])



























dataset.to_csv("trevignano2019.csv", index=False, encoding="utf-8")
dataset.to_json("trevignano2019.json",orient="records")