# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np




dataset = pd.read_csv("trevignano_2020.csv", encoding="utf-8")



dataset["author"] = np.where(dataset["text"].str.contains("Il vostro Gesù"), "Jesus Christ", dataset["author"])
dataset["author"] = np.where(dataset["text"].str.contains(" Il Vostro Gesù"), "Jesus Christ", dataset["author"])



dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 3)), "Moje kochane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Kochane dzieci, w tym czasie, świat jest w wielkim zamieszaniu, jako wasza matka proszę was, nawróćcie się, nie zostało wam wiele czasu. Drogie dzieci, dlaczego wierzycie w Boga stworzonego przez was samych! Chrystus przyszedł dla ciebie i umarł za ciebie. Moje dzieci, módlcie się o pokój na świecie i wśród waszych braci, módlcie się za Kościół, który zmierza do całkowitego upadku. Bądźcie odważnymi wojownikami i chrońcie tę Wiarę w Jedynego i Trójjedynego Boga. A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 4)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Wczoraj byłam bardzo szczęśliwa widząc was zgromadzonych na uroczystej modlitwie i słysząc wasze pochwały i pieśni, byliście wielkim przykładem dla wielu. Umiłowane dzieci, słowa, które wypowiada ta moja córka, są słowami Jezusa Chrystusa, to mój Syn wkłada w jej usta swoje słowa, nie dziwcie się, bo jej miłość do mojego Syna jest bezgraniczna i odważna. Znaki, były naszą czystą radością. Wiele łask zstąpi dziś na was. Módlcie się za kapłanów. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 7)), "Moi umiłowani bracia, dziękuję wam, że jesteście tutaj na modlitwie. Bracia moi, wy, z waszymi cierpieniami, nadal wspinajcie się po drabinie duchowości, oddajcie mi wasze ciężary i wasze bóle, tylko w ten sposób możecie mieć radość i spokój w waszych sercach, to Ja i tylko Ja przemienię bóle w radość. Bracia, myślcie tylko o życiu wiecznym, oddajcie mi się całkowicie, mój powrót jest bliski. A teraz błogosławię was w imię Ojca, w imię Moje i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 11)), "Drogie dzieci, dziękuję wam za to, że przyjęliście moje wezwanie i odpowiedzieliście na nie w waszych sercach. Dzieci moje, sytuacja ludzkości jest trudna, proszę was, podajcie mi swoje ręce, a ja was przyprowadzę do Jezusa, bądźcie zawsze zjednoczeni, kochajcie się wzajemnie jak bracia, aby była to nowa Pięćdziesiątnica. Moje serce nadal krwawi z powodu niesprawiedliwości, ziemia będzie mocno drżeć, Watykan będzie mocno atakowany, módlcie się za światowe mocarstwa, Chiny, Amerykę, Rosję, módlcie się, módlcie się, módlcie się bardzo mocno. Dzieci, moje dzisiejsze łzy mają wyjaśnienie dla tych, którzy nigdy nie chcieli zrozumieć. Teraz zostawiam was i błogosławię was w imię Ojca i Syna, i Ducha Świętego, Amen.  Dziś wieczorem zstąpi na was wiele łask." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 14)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Drodzy mali, jak bardzo potrzebujecie być prowadzeni i jak wiele zamieszania jest zasiane! Aby mieć pewne prowadzenie, bądźcie zawsze wierni Ewangelii i Słowu Bożemu. Serca można przemienić modlitwą. Nie bądźcie grobami pobielanymi. Umiłowane dzieci, zawsze będę blisko was, razem z moim Synem Jezusem. Módlcie się za papieża. Teraz zostawiam was z moim Świętym Błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 15)), "Córko moja, bądź potulna, ale jasna, każde słowo czy pismo nowej doktryny będzie musiało wzbudzić w tobie wątpliwości, prawda jest jasna, krystaliczna i jest tylko jedna i na zawsze, to wszystko, co zostało objawione w Fatimie, nabiera teraz kształtów na niedowierzających oczach wszystkich, ale wielu będzie przenikniętych poczuciem normalności i nowoczesności, tu córko moja, to wszystko musi być wyjaśnione dla dobra ludzkości, która się gubi. Będę wam towarzyszyła w modlitwie razem z waszymi braćmi i błogosławię was, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 18)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Niebo jest radosne z powodu waszych modlitw. Moje ukochane dzieci, wiecie, że wszystko, co przepowiedziałam, stanie się, wojny, trzęsienia ziemi i inne straszne rzeczy przyjdą na tę ziemię, aby mogła zostać oczyszczona. Dzieci moje, nigdy nie wolno wam się bać, bo Pan i ja będziemy z wami, aby was chronić. Moje dzieci, te orędzia muszą być rozpowszechniane na całym świecie, aby wielu mogło powrócić do Boga i nawrócić się. Umiłowani moi, módlcie się za Kościół i za kapłanów. Panuje zamęt, płaczę nad ludzkością. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 19)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj na modlitwie. Moi umiłowani, bądźcie blisko Serca Jezusowego, aby nawet w ostatniej chwili mój Syn mógł wejść do waszych serc. Ziemia ma zostać oczyszczona z brudu, który stworzył człowiek, dzieci, nawróćcie się, nadszedł czas. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 25)), "Drogie dzieci, dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Ukochane dzieci, ileż nieszczęść na tej ziemi pełnej grzechów, Wiara to coś wspaniałego, to zbliżanie się coraz bardziej do Boga, nawracajcie się moje dzieci, Wiara to nie ekologia, ale to przestrzeganie Przykazań, Ewangelii Świętej, Sakramentów. To nie ziemię należy adorować, ale Syna Bożego. Wszystko, co dzieje się dzisiaj na Ziemi, nie zależy od Boga, ale od samego człowieka, który swoją ręką zrujnował raj, jaki Bóg pozostawił. Módlcie się za Włochy, które wpadły w wir pogaństwa, módlcie się, módlcie się tak bardzo, aby światło Boże dotarło do zatwardziałych serc wielu księży, miłość, miłosierdzie i przebaczenie to fundamenty chrześcijaństwa. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 28)), "Moje kochane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Drogie dzieci, wszystko, co się dzieje, powoduje smutek w waszych sercach, lecz dzieci, konieczne jest oczyszczenie. Dzieci moje, módlcie się tak bardzo za Niemcy i Francję. Watykan dzieli się na dwie części. Dzieci moje, oto wielka próba wiary, mówię jako Matka do moich synów kapłanów, bądźcie zawsze posłuszni Kościołowi, ale bądźcie ostrożni, bo kiedy zniknie konsekracja Eucharystii, zniknie również mój Syn, Pan Jezus. Wiedzcie, że wasza prawdziwa wiara zostanie nagrodzona, bo ja was ochronię. Oto przepowiedziane czasy są nad waszymi głowami, przyjdą nowe choroby, na które trudno będzie znaleźć lekarstwo. Ziemia będzie nadal drżeć coraz mocniej, pokutujcie i nawróćcie się. Będę z tobą tak często, jak będziesz mnie wzywał. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 31)), "Umiłowane dzieci, dziękuję wam, że jesteście zgromadzeni w tym błogosławionym miejscu, pragnę, aby te kręgi modlitewne odbywały się dwa razy w tygodniu. Zbierajcie się w imię Pana, bo wasze pokorne modlitwy o Niebo są złotymi iskrami. Umiłowane dzieci, kochajcie Kościół i Eucharystię, bądźcie zawsze wierne Ewangelii i Słowu Bożemu. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])





dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 1)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moja córko, również dzisiaj, który jest dla ciebie szczególnym dniem, mówiłaś o moim Synu i błogosławię cię dzisiaj i zawsze razem z twoim małżonkiem. Umiłowani moi, w tym czasie brzydoty i pokus, wiele serc się otworzy i wielu się nawróci, tylko modlitwa będzie jedyną obroną, jaką macie. Módlcie się o pokój, aby potężni nie realizowali diabolicznego planu, módlcie się, a znajdziecie lekarstwo i zbawienie.  Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowani moi, módlcie się, módlcie się bardzo mocno! Dziś ludzkość jest zagubiona. Rozejrzyj się wokół siebie, co się dzieje. Spójrzcie na zniszczone rodziny, na młodych ludzi, którzy nie mają już żadnych wskazówek. Dzieci moje, czy nie widzicie, że diabeł chce was skusić, aby zabrać jak najwięcej dusz? Umiłowane dzieci, małe aniołki na tej ziemi, odwróćcie wzrok od ziemi i rzeczy ziemskich, ale spójrzcie na niebo z jego znakami, które was prowadzą i wskazują drogę do świętości. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 8)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, wiem o waszych cierpieniach spowodowanych atakami diabła, ale powierzcie się Bożej sprawiedliwości, a my przemienimy wasze cierpienia w radość i łaskę. Umiłowane dzieci, módlcie się za Kościół, który znajduje się na ogromnym rozdrożu. To wszystko nie wydarzyłoby się, gdyby posłuchano tego, o co prosiłam w Fatimie. Moje dzieci, im bardziej zbliża się czas triumfu mojego Niepokalanego Serca, tym bardziej szatan będzie was atakował, ale nie bójcie się, ja zawsze będę z wami razem z Jezusem. Dzieci moje, zostawiam was teraz z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen. P.S: Dziś wieczorem Matka Boża płakała, a w rękach trzymała krwawiące serce Jezusa." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 11)), "Kochani moi, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Drogie dzieci, dziękuję wam, że jesteście tutaj, w tym błogosławionym miejscu. Moje dzieci, pocieszacie moje serce, proszę was, bądźcie zawsze światłami na tym świecie, moi aniołowie was rozpoznają, a mój Pan przyjdzie wcześniej niż myślicie, proszę was, świeccy i wy, konsekrowani, abyście nadal byli solą dla tej ziemi grzechu, bądźcie blisko waszych braci, wszystko przyjdzie nagle, więc bądźcie gotowi. Moje dzieci, módlcie się, módlcie się, módlcie się dużo i pamiętajcie, że Kościół będzie się chwiać, ale nie upadnie, tak długo, jak długo wy również będziecie słyszeć wasze wołanie miłości, jesteście błogosławieni przez Niebo i wiele łask zstąpi na was tego wieczoru. Teraz zostawiam was z moim matczynym błogosławieństwem, błogosławię wszystkich obecnych, jednego po drugim, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 15)), "Moja ukochana córko, ból, który odczuwam, jest silny, siostro, moje serce krwawi z powodu cierpienia, które odczuwam, patrząc, jak ludzkość odwraca się ode mnie. Módlcie się za świętych kapłanów, aby was pocieszali w czasie cierpienia i ucisku. Stopniowo zniknie ofiara Mszy świętej i co wy, bracia, zrobicie, dokąd pójdziecie, jeśli nie z sercem zwróconym ku mnie. Niech twój wzrok i twoja modlitwa będą zwrócone do Boga, bo On może cię pocieszyć. Przywódcy i możni chcą jednej religii, chcą sprotestantyzować Mój Kościół, ale bądźcie wojownikami Światła, a Ja będę liczył na was i na Moją małą wierną resztkę, bardziej niż na niektóre rozproszone i modernistyczne osoby konsekrowane. Bracia, ten czas jest coraz bliższy, Bóg jest zmęczony, wszystko zostanie przebaczone za każde prawdziwe i szczere nawrócenie. Wiele będzie nawróceń dla tych, którzy otworzą szczelinę w swoim sercu. Będę mógł wejść i działać w nich. Zostawiam was teraz z Moim Świętym Błogosławieństwem w Imię Ojca, w Moje Imię i w Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 18)), "Moje drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, spójrzcie na to wszystko, co dzieje się wokół was, Kościół upada, wraz z wieloma moimi pomazańcami, trzęsienia ziemi są wszędzie, wirusy obrały swoją drogę, gospodarka upada, a jednak wasza wiara nadal jest słaba, ale czy naprawdę nie zdajecie sobie z tego sprawy? Jesteście w samym środku burzy i walki i gdybyście tylko zdali sobie z tego sprawę, zwiększylibyście swoją wiarę, zgięlibyście kolana w modlitwie. Nawróćcie się, dzieci, Ja będę z wami za każdym razem, gdy będziecie Mnie wzywać. Teraz zostawiam was z moim świętym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 22)), "Drogie dzieci, dziękuję wam za waszą obecność na modlitwie. Moja córko, moje spojrzenie skierowane jest na tę ludzkość, która jest zdenerwowana i zdezorientowana, ponieważ patrzy na rzeczy tego świata i nie ufa moim słowom i słowom Jezusa. Wielokrotnie ostrzegałem was o tym, co przeżywacie. Proszę moje dzieci świata, moich wybranych, aby dużo się modlili, abym mógł być blisko was. Umiłowane dzieci, nie bądźcie w zamieszaniu, ale ofiarujcie Msze św. i karmcie się Eucharystią, powtarzam jeszcze raz, NAWRÓĆCIE SIĘ. Oczekuję na ostatni dogmat, o Współodkupicielce, dla zbawienia ludzkości. Teraz zostawiam was z moim Świętym Błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 23)), "Córko moja, to są ciemne czasy, które przepowiedziałam, kiedy wszyscy się z ciebie śmiali, dzisiaj się boją, nie bójcie się dzieci, Ja Współodkupicielka świata poślę moje ukochane dzieci, aby wam pomogły, pocieszyły was i niczego wam nie zabraknie, także Jezusa żywego w ciele, krwi i boskości. Znam wasze trudności związane z Eucharystią i aby mój Syn Jezus nie był oburzony, dla tych, którzy nie będą mieli możliwości przyjęcia Komunii do ust, zaopatrzcie się w lnianą chusteczkę i tą samą ręką przyłóżcie ją do ust, nie dotykając jej rękami, chusteczkę starannie przechowujcie i zawsze używajcie tej samej. Kocham was dzieci, będę blisko was i błogosławię was każdego dnia, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 2) & (dataset["day"] == 29)), "Moje dzieci, dziękuję wam, że słuchacie mojego wołania w waszych sercach. Dzieci moje, dlaczego czekacie na straszne rzeczy, aby przybliżyć się do Boga, a kiedy wszystko idzie dobrze, nie znacie swojego Zbawiciela? Moje dzieci, to nie będzie ostatni wirus, który przyjdzie z ziemi, ale czekajcie na więcej, trzęsienia ziemi i zarazy, świat jest ich pełen, a wielu, mimo wszystko, już oddało swoje dusze diabłu. Moje dzieci, to jest czas, nawróćcie się, módlcie się i wierzcie w Ewangelię, obiecuję wam ochronę. Umiłowane dzieci, wielu z was prosi mojego Syna o rychły powrót i On przyjdzie, ale dopiero wtedy, gdy zobaczy, że ohyda, grzech i bluźnierstwo jeszcze bardziej się rozprzestrzeniają i zło nie da wam już siły do powrotu do Boga, wtedy Jego przyjście będzie ostatnim aktem miłosierdzia. Moje kochane dzieci, módlcie się, módlcie się tak bardzo, Ja, jako Matka was wszystkich, będę was chronić i będę przy was. Teraz zostawiam was z moim Świętym Błogosławieństwem, w imię Ojca, Syna i Ducha Świętego, Amen." , dataset["text_pl"])




dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Drogie kochane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowani moi, jak wiele bólu trwa w waszym życiu! Moje dzieci, w tym czasie Wielkiego Postu, ofiarujcie wszystkie wasze smutki Sercu Jezusa, które bardzo cierpi z wami, za Kościół, za osoby konsekrowane i za was, dzieci, które jesteście wierne Ewangelii i Słowu Bożemu. Zły zabiera wiele dusz, wykorzystując ten moment zamętu, lecz Ja, jako Współodkupicielka ludzkości, przyprowadziłam was do stóp Krzyża i proszę o pomoc moje ukochane dzieci: pomóżcie mi przyprowadzić wiele dusz do Boga, abyście i wy mogli być Współodkupicielami razem ze Mną i ostatecznie zwyciężyć ze Mną. Moi mali, nigdy nie bójcie się prawdy. Pan Jezus, pamiętajmy, jest Życiem, Prawdą i Drogą. Dziś zstąpi na was wiele łask. Teraz daję wam moje matczyne błogosławieństwo w imię Ojca i Syna i Ducha Świętego. Amen. Następnie Matka Boża dodała: żyj ze mną i z Jezusem Jego Męką. Dzisiaj Matka Boża była trochę smutna; miała na sobie piękną długą białą suknię, a w lewej ręce trzymała kryształowy różaniec; Jej stopy spoczywały na świecie i zapraszała mnie do oglądania obrazów wojen i śmierci. Matka Boża zaprasza nas do nieustannej modlitwy." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 6)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie w tym domowym kościele, to jest moje pragnienie, aby modlić się razem w pokoju z sercem zwróconym ku Jezusowi. Dzieci, bądźcie pokorni i proszę was, abyście wybrali wąską drogę do waszej świętości, a nie tę bez trudności, która prowadzi do zguby, pomyślcie o swojej duszy. Módlcie się za Niemcy. Nie osądzaj księży, dla wielu, będzie sądzony ciężko przez Boga. Jestem tu z wami, aby was pocieszyć, i błogosławię was w imię Ojca i Syna, i Ducha Świętego, Amen. Już niebawem, siostro moja, nadejdzie moment, w którym oddzielę światłość od ciemności." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 7)), "Dzieci moje, dziękuję wam, że jesteście tutaj na modlitwie, proszę was, abyście się wyspowiadali i oczyścili swoją duszę, idźcie w prawdzie w tym czasie oczyszczenia. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8)), "Drodzy bracia i moje dzieci, dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Dziękuję wam za waszą miłość, Ja, wasz Król, wkrótce będę z wami, aby odebrać to, co należy do Boga. Moje dzieci, co one mi robią! Serce moje i Mojej Najświętszej Matki płacze, już wam mówiłem, że wkrótce nie będzie Mnie już w Moim domu, teraz nadeszła chwila Mojego ukrzyżowania. Po raz kolejny jest to silniejsze niż poprzednio, nigdy nie przeżyłem tak złych czasów dla mnie, wszystko zawsze decyzją ludzi, jakże głupia jest ta ludzkość! Zapomnieli, że umarłem za nich. Błogosławię was w imię Ojca, w imię Moje i w imię Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 10)), "Dzieci moje, dziękuję wam, że jesteście tutaj na modlitwie. Drogie dzieci, nie bójcie się wirusów, ale raczej tego, że pozostaniecie bez chleba życia wiecznego. Moi umiłowani, bądźcie zjednoczeni, abyście zawsze byli światłem świata. Nigdy nie gaście tego światła. Dzieci moje, każdy sposób wspólnej modlitwy jest pożyteczny. Moje dzieci, módlcie się za Rzym, ponieważ będzie on pił gorzki kielich. Módlcie się za Rosję. O, ukochane dzieci, gdybyście mnie posłuchały! Teraz zostawiam was w pokoju i błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 11)), "Umiłowani moi, serce mi krwawi, gdy widzę was tak bezradnych i gdy widzę, że zamiast modlić się do Ojca mego, zamykacie się w domach. To, czego nie widać, jest przerażające! Dlaczego nie kochasz mnie, który jest blisko ciebie! Moja Matka, która z wielkim smutkiem mówi wam, co macie czynić, nie jest wysłuchiwana, tylko modlitwa może was uratować i nie trwajcie w pragnieniu zrozumienia, bo dopóki nie uwierzycie, umysł tego, który doprowadzi was do zbawienia, nie może być oświecony. Mała trzódko, możecie zrobić tak wiele, modląc się do mojego Ojca z otwartym sercem, powróćcie, aby odkryć na nowo wiarę, miłość do waszego brata i odbudować pokój między wami. Umiłowani moi, jak bardzo boli mnie widok was tak bezradnych i poranionych, módlcie się z Moją Matką, a Ona będzie z wami w modlitwie, aby wznieść wasze wołanie do Mojego Ojca, który choć tak bardzo was kocha, nie może już patrzeć na swoje ukochane dzieci, które się zagubiły i nie mają odwagi przynieść Świętej Eucharystii nawet tym, którzy cierpią, ta próba jest silna. Życzę, aby każdy z Was przyjął swój krzyż z miłością. Błogosławię was w imię Ojca, w moim imieniu i w imię Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 14)), "Moje drogie dzieci, dziękuję wam za wasze modlitwy, pamiętajcie, aby nie opuszczać krzyża, bądźcie zawsze ze wzrokiem zwróconym ku niebu, nie bójcie się, bo mój Jezus jest blisko was, razem z aniołami i archaniołami, miejcie pokój i radość w waszych sercach. Moje dzieci, kochajcie mojego Syna Jezusa, weźcie mnie za ręce, a niczego wam nie zabraknie, opatrzności nie zabraknie tym, którzy są mocni w wierze. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 17)), "Dzieci moje, dziękuję wam, że jesteście tutaj na modlitwie. Dzieci moje, wiem jak wiele cierpienia spadło na ludzkość, ale będę przy was i proszę was w tych trudnych chwilach, zastanówcie się i pomyślcie, że tylko Bóg może być waszą pomocą i pociechą, trwa czas walki dobra ze złem. Zbliżcie się do modlitwy, tylko w ten sposób możecie pokonać zło, które do was przylgnęło. Przygotujcie się dzieci, nadejdą ciężkie czasy z powodu nowych pandemii, trzęsień ziemi i wojennych wiatrów. Mimo wszystko, wielu z was będzie odczuwać wielki pokój w sercu, wiedzcie, że jest to łaska Nieba, nie bójcie się, będę z wami.  Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 21)), "Umiłowane dzieci, dziękuję wam za to, że jesteście tutaj na modlitwie. Moje kochane dzieci, jakże jesteście przerażeni tym wszystkim, co się dzieje, lecz Ja dotknęłam ziemi, aby was ostrzec i przygotować was na to wszystko, co się wydarzy, a wielu, pomimo moich ciągłych wezwań, nie słucha. Umiłowane dzieci, podajcie mi swoje ręce, a ja przeprowadzę was przez wszystko, co będzie musiało się wydarzyć z wielką ochroną, bądźcie blisko mnie i mojego Jezusa, a nic nie będzie mogło wam się stać.  Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 24)), "Bracia moi, jesteście tu wszyscy zgromadzeni w tej wielkiej rodzinie, co za radość w moim sercu, wszyscy na modlitwie, jak dawniej. Umiłowane dzieci, wy, którzy staliście się teraz częścią mojej małej trzódki, idźcie w ślady za moją Matką, będę wam towarzyszyć wśród lwów i żmij, nikt nie może was dotknąć, nikt nie może was skrzywdzić. Drodzy bracia, jak wielka jest moja miłość do was, pozostańcie zjednoczeni, bo dziś jest czas, kiedy każdy potrzebuje drugiego, nie zostawiajcie braci samych, ale miejcie litość i miłosierdzie, bo Ja będę miał je dla was, niczego wam nie zabraknie. Moc Boża jest tak wielka, że mój płaszcz jest płaszczem mojej Matki; okryje was i uczyni niewidzialnymi dla zła. Bracia moi, elita świata chce was sobie podporządkować, staliście się jak poddani, ale Ja przyjdę i wyzwolę was od całego tego zła. Bracia moi, będę przechodził obok was wszystkich, będę was przytulał i błogosławił, jako brat, jako przyjaciel, jako ojciec, w imię Ojca, w Imię Moje i Ducha Świętego, Amen. Moja córko, nie bój się, schowaj swoją dłoń w Mojej, a Ja będę przy tobie, nigdy cię nie opuszczę, będą z tobą na czas tej misji, bądź spokojna." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 28)), "Umiłowane dzieci, moje serce bije miłością do was, którzy jesteście zjednoczeni w modlitwie i odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowani moi, słuchajcie sercem i patrzcie oczami na wezwania nieba, wykorzystajcie te dni, aby powrócić do Boga, to jest ostatnie wezwanie, bo wkrótce nadejdzie Ostrzeżenie, bądźcie przygotowani. Dzieci moje, wykorzystajcie te okresy Męki Pańskiej na post i pokutę. Dzieci moje, módlcie się za możnych tego świata, którzy to wszystko zaplanowali. Diabeł nie chce puścić swojej ofiary, ale wy, dzieci, módlcie się, módlcie się, módlcie się tak bardzo, by wszystko, co przyjdzie, mogło być tak mało bolesne, jak to możliwe. Módlcie się za Kościół, w którym mój Syn nie jest już obecny razem z moimi umiłowanymi dziećmi, które miały odwagę ponownie zdradzić Jezusa i nadal Go krzyżują. Módlcie się za Kościół, poniesie on wielką stratę. Módlcie się za Japonię i za ujarzmione Włochy. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 31)), "Moja córko, dziękuję ci, że jesteś zjednoczona w modlitwie. Umiłowane dzieci, w tym czasie zastanówcie się nad tym, co mieliście i co macie teraz, wszystko może się zmienić, kiedy jesteście tego mniej świadomi i co wam pozostanie, jeśli nie wiara i miłość do Boga, waszego jedynego ratunku? Moje dzieci, nawróćcie się sercem, w tym czasie wasza dusza jest obnażona przed waszą małością. Dzieci moje, módlcie się za Kościół, bo ból będzie wielki; módlcie się za osoby konsekrowane, bo wiele z nich utraciło swoją duchowość i oddało się wszystkiemu, co ziemskie, rozpraszając trzodę. Moja córko, umieszczam was wszystkich pod moim błogosławionym płaszczem, aby was chronić, bo wiem, co was spotka. Umiłowani moi, poczujecie, jak Duch Święty zstępuje na was i wasze serca wypełnia radość. Kochajcie się jak bracia i pomagajcie sobie nawzajem, bo najgorszy czas dopiero nadejdzie i będziecie zmuszeni modlić się w ukryciu, to jest czas, który nadejdzie, bądźcie zawsze silni i wierni. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 31) & (dataset["author"] == "Jesus Christ")), "Dzieci moje i bracia, wprowadźcie do waszych serc pokój, miłość i radość. Jeśli to uczynicie, nie nawiedzi was żaden cień, bo idzie za wami moja ręka. Podaj mi swoją dłoń, a ja zaprowadzę Cię wśród czystych wód, błękitnego nieba i bezkresnych łąk. Będziesz upojony miłością. Wasze życie zmieni się na zawsze i nie możecie sobie wyobrazić, ile szczęścia istnieje razem z waszym Bogiem. Rozumiem, co przeżywacie, bo ja też byłem człowiekiem i jako człowiek byłem prześladowany i ukrzyżowany, ale przy moim zmartwychwstaniu ujrzeliście światło życia wiecznego. Idź moją ścieżką, a już cię nie opuszczę; wybierz szczęście wieczne. Twój Jezus." , dataset["text_pl"])




dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie. Umiłowani moi, wasze związki modlitewne wznoszą się do nieba jak pieśni aniołów. Umiłowane dzieci, ileż łez wylałam za tę ludzkość, pamiętajcie, że w tym czasie mój Syn, zanim został ukrzyżowany, był poniżany, traktowany jako heretyk i oczerniany, podobnie prorocy, którzy byli prześladowani w imię Jezusa i z miłości do Jezusa, więc nie dziwcie się, jeśli to wszystko dzieje się również dzisiaj z moimi dziećmi, to ta sama historia. Zawsze będę was chroniła, ale pamiętajcie, że wszystko, co nadejdzie, będzie złagodzone waszymi modlitwami, ale nie może być odwołane, ponieważ to, co jest napisane, musi się wypełnić. Moi umiłowani, Ja, wasza Matka, modlę się, aby moi synowie, powołani do kapłaństwa, powrócili do prawdziwej Wiary i do prawdziwego Magisterium Kościoła, w którym dokonuje się oczyszczenie. Moje dzieci, pomóżcie mi w tym krzyku bólu, módlcie się za Włochy, gdzie ziemia mocno się trzęsie. Módlcie się za Indie. Błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 8)), "Dziś, w Wielką Środę, był dzień, w którym zostałem zdradzony przez Judasza pocałunkiem. Gdy szedłem przez miasto, faryzeusze patrzyli na mnie z góry, z arogancją, tak też i dzisiaj mój Kościół zdradza mnie, patrząc na mnie powierzchownie; nawet wielcy teologowie zagradzają kościoły, rozpraszając moją trzodę. Moja córko, to jest historia Wielkiej Środy i tych czasów; wkrótce Ostrzeżenie będzie nad tobą, dając ci wybór: Kochaj Mnie lub szatana. Po tym, kule ognia zstąpią na ziemię i to będzie najgorszy okres dla was, bo przyjdą katastrofy wszelkiego rodzaju. Moja Matka będzie was chronić, oddając was pod swój błogosławiony płaszcz, nie bójcie się. Błogosławię was wszystkich w imię Ojca, w imię moje i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 11)), "Umiłowane dzieci, drogie sercu mojej Matki, dziękuję wam za to, że jesteście tu zgromadzeni na modlitwie i że w waszych sercach słuchacie mojego wołania. Umiłowani moi, proszę was, abyście pokochali i przyjęli krzyż, jak uczynił to mój Syn. Moi mali, daję wam dobrą nowinę o Jego zmartwychwstaniu, wielu z was zostanie wskrzeszonych ze śmierci na tej ziemi, wkrótce otworzą się Niebiosa i Syn Boży, mój Pan, przyjdzie i uczyni nowe niebo i nową ziemię. Otwórzcie swoje serca dla Tego, który umarł dla zbawienia ludzkości, a mój Syn przebaczy wam wszystko, jeśli poprosicie Go z sercem wypełnionym miłością. Moje dzieci, wiele łask zstąpi dziś na was i zostaniecie napełnieni Duchem Świętym. Módlcie się dzieci, módlcie się, aby modlitwy dotarły do nieba, już wiele wydarzeń zostało złagodzonych. Teraz błogosławię was jako Matka was wszystkich, w imię Ojca, Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 14)), "Moje kochane dzieci, dziękuję wam za to, że jesteście zjednoczeni w modlitwie i że wsłuchujecie się w moje wołanie w waszych sercach. Umiłowane dzieci, proszę was, abyście byli zjednoczeni, nawet jeśli tylko duchem w tym szczególnym czasie, wkrótce będziecie potrzebować siebie nawzajem. Proszę tych, którzy mają skruszone serce, aby przebaczyli i pojednali się, w przeciwnym razie diabeł nabierze sił i nie zostawi was w pokoju. Drogi dzieci, moje małe dzieci, szatan wypędził was z kościołów i zabronił wam przyjmować Komunię, dlatego myśli, że już wygrał, ale wiedzcie, że nie wygra, Pan da wam miłość w sercu, abyście, moje dzieci, nie przegrali siebie. A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 18)), "Umiłowane dzieci, dziękuję wam za trwanie na modlitwie i za słuchanie mojego wołania w waszych sercach. Drogie dzieci, walczcie o swoją wolność, wkrótce zostaniecie zniewoleni przez złych dyktatorów. Strzeżcie się szczepionek i wszelkich zobowiązań, ponieważ nie będą one pochodzić od Boga, ale od szatana, który chce rządzić waszym życiem i umysłami. Umiłowani moi, trzęsienia ziemi będą słyszalne w każdej części świata, dotknęłam ziemi, aby ostrzec moje dzieci, aby były gotowe na straszne czasy, które nadejdą. Dzieci moje, używajcie rozeznania, gdyż jest to czas, kiedy wielu będzie fałszywych proroków. Módlcie się dużo i nieustannie, miejcie tylko wiarę w Boga i kontynuujcie czytanie Pisma Świętego. Umiłowane dzieci, tylko wiara może was uratować, nigdy o tym nie zapominajcie. Moi Aniołowie i Archaniołowie zawsze będą przy was, nie bądźcie letni. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21)), "Umiłowane dzieci, dziękuję wam, że jesteście tutaj na modlitwie i że słuchacie mojego wołania w waszych sercach. Moja córko, tak jak pierwszego dnia, proszę cię jeszcze raz, abyś otworzyła swoje drzwi i ramiona, dała miłość, pewność i siłę dzieciom, które ci przyślę. Przygotujcie bezpieczne schronienia na czasy, które nadejdą, prześladowania mają miejsce, zawsze bądźcie ostrożni. Dzieci moje, proszę was o siłę i odwagę, módlcie się za tych, którzy już umarli i za tych, którzy dopiero umrą. Epidemie będą trwały, dopóki moje dzieci nie zobaczą światła Bożego w swoich sercach. Wkrótce krzyż rozświetli niebo i będzie to ostatni akt miłosierdzia. Wkrótce, wszystko wydarzy się tak szybko, że będziecie myśleć, że nie możecie już znieść tego bólu, ale powierzcie wszystko waszemu Zbawicielowi, bo On jest już gotowy, aby wszystko odnowić i wasze życie stanie się naczyniem radości i miłości, nie bójcie się, bo ja będę przy was i wkrótce moje Niepokalane Serce zatriumfuje z wami. Całe twoje życie zostanie przemienione. Oto Duch Święty nadal działa. Nie lękajcie się, siły i odwagi, moje dzieci. Teraz zostawiam was z moim Świętym Błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen. Komentarz: W dzisiejszym orędziu Matka Boża prosi nas, abyśmy przygotowali bezpieczne schronienia, które są miejscami, gdzie panuje modlitwa, a więc tam, gdzie odbywają się wieczerniki, ponieważ tam, gdzie jest prawdziwa modlitwa, odczuwana sercem, zło nie będzie mogło wejść. Największymi schronieniami są Niepokalane Serca Maryi i Jezusa, dlatego, aby stać się ich częścią, potrzebne jest prawdziwe nawrócenie." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 25)), "Moja córko i siostro, dziękuję wam za to, że jesteście tutaj w modlitwie. Bracia moi, ukojcie moje zbolałe i krwawiące serce, módlcie się dużo, bo to, co ma nadejść, będzie bardzo bolesne dla świata, ale wy nie jesteście światem, jesteście moimi umiłowanymi, którzy jak dzieci przychodzą do mnie ze szczerymi oczami i proszą o pomoc i miłosierdzie. Bracia moi, będę śledził wasze umysły i sam poprowadzę was na właściwe drogi, tylko dajcie mi wasze ręce. Bracia, przebaczcie i zacznijcie głosić światu, aby wszyscy mnie poznali. Otwórzcie wasze serca, a będę miłosierny, lecz kto mimo upływu czasu będzie nadal bluźnił, nie będę miał litości. Bracia, strzeżcie się dyktatur i tego, co chcą na was wymusić, bo nie pochodzą one od Ojca Mojego. Oto wojna już się rozpoczęła. Bracia, nigdy nie wątpcie w Moją pomoc, w Moją bliskość i w Moją miłość. Módlcie się za kapłanów. Błogosławię was wszystkich w Imię Ojca, w Moje Imię i w Ducha Świętego, Amen. Twój Drogi Jezus" , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 28)), "Drogie dzieci, dziękuję wam, że jesteście zjednoczeni w modlitwie i że przyjęliście moje wezwanie w waszych sercach. Umiłowane dzieci, potężni zaplanowali wszystko, nie biorąc pod uwagę Boga. Nie ma sensu planować swojej ucieczki przed tym, co się wydarzy, ponieważ moimi bezpiecznymi schronieniami będą modlitwa, ofiary, pokuta i to, co Bóg już dla was przygotował. Radujcie się, dzieci, bo zobaczycie Jezusa, który zejdzie tak, jak odszedł. Umiłowane dzieci, mój Pan tak bardzo cierpi, ponieważ umarł za was i za wasze grzechy, ale świat nadal działa na pustkowiu. Duszpasterze nie troszczą się o wiernych, kościoły są zamykane, a wkrótce nawet Eucharystia zostanie wam ponownie odebrana. To, co nadejdzie, spowoduje śmierć. Ale ty nadal nie rozumiesz! Zostałem wysłany, aby was ostrzec, ale wielu nawet nie docenia mojej obecności. Módlcie się, moje dzieci! Módlcie się pod Krzyżem mojego Syna, bo ziemia jest pełna demonów. Człowiek rzuci się na człowieka i od tego momentu rozpocznie się wojna. Umiłowani moi, powierzcie wszystko mojemu Panu. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen." , dataset["text_pl"])




dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że jesteście zjednoczeni w modlitwie i że słuchacie mojego wołania w waszych sercach. Dzieci moje, nie traćcie odwagi, módlcie się, bo tylko w modlitwie znajdziecie pocieszenie i nieskończoną radość w waszym sercu, bo będziecie mieli pewność, że wasze serce jest w ramionach Jezusa, gdzie tylko wy będziecie bezpieczni. Umiłowani moi, tak wielkie będzie wasze wzruszenie i tak wiele łez popłynie z waszych oczu z powodu wielkiej radości, jaką odczujecie, gdy zobaczycie, co Jezus dla was przygotował. Tylko w ten sposób będziecie mogli żyć w radości i prawdziwej miłości. Mówię do moich kapłanów: nie porzucajcie Ewangelii i Słowa; pamiętajcie, że wasze przyrzeczenia są święte; nawróćcie się, zanim nadejdzie koniec czasów, błagam was, pomóżcie mi zatroszczyć się o dusze. Dzieci moje, módlcie się, módlcie się tak bardzo za trzęsienia ziemi, które będą miały miejsce, szczególnie w środkowych Włoszech. Bądźcie jednak spokojni, bo ja nigdy was nie opuszczę. Dziś zstąpi wiele łask dla moich dzieci. A teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego. Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 5)), "Dzieci moje, dziękuję wam za to, że zgromadziliście się na modlitwie i że wsłuchaliście się w moje wołanie w waszych sercach. Pamiętajcie, dzieci, ceńcie swoje modlitwy, bo to ja was wzywam; ceńcie swoją wiarę i mojego Pana, który modli się do Ojca za was. Umiłowane dzieci, nie zasypiajcie, ale czuwajcie i czekajcie w gotowości, bo nikt nie będzie znał ani godziny, ani dnia. Umiłowani moi, módlcie się za osoby konsekrowane, aby powróciły do Boga. Ta obecna sytuacja wystawiła na wielkie próby, a kiedy mój Syn powróci, będzie to podział, a nie zjednoczenie, ponieważ wybór został już dokonany; pamiętajcie o słowach Ewangelii: jeden zostanie zabrany, a drugi pozostawiony. Moi umiłowani, apostazja wkroczyła do Kościoła jak nigdy dotąd. Módlcie się za potężnych ziemi, ponieważ podejmują oni decyzje, od których nigdy nie będą w stanie zawrócić. Jestem waszą Matką i płaczę z powodu czasów, w których przyjdzie wam żyć. Nawracajcie się. Teraz błogosławię was w imię Ojca, Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 9)), "Drogie dzieci, dziękuję wam, że jesteście zjednoczeni w modlitwie i że słuchacie mojego wołania w waszych sercach. Dzieci moje, jeszcze raz was proszę: nie zdradzajcie mojego Jezusa, który was kocha bezgranicznie; słuchajcie Jego głosu w waszym sercu, bo On nadal wzywa was po imieniu. Moi kochani, wszystko spełni się w krótkim czasie. Czy nie zdajesz sobie sprawy, czym stał się świat? Garść gruzu z powodu diabła. Moje dzieci, wkrótce nastąpi wielka zmiana. Oczekujcie silnego deszczu oczyszczającego i silnego trzęsienia ziemi, które poprzedzą przyjście mojego Syna, aby zapanował pokój. Jezus nigdy cię nie opuści, On cię kocha, tak jak ja cię kocham. Wam, którzy powiedzieliście swoje szczere 'tak' na zawsze, niczego nie będzie brakować i wielka ochrona zstąpi na was. A teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 12)), "Drogie dzieci, dziękuję wam, że jesteście zjednoczeni w modlitwie i że słuchacie mojego wołania w waszych sercach. Moje kochane dzieci, nie bójcie się, nie myślcie głową, ale sercem. Powierz mi wszystkie swoje lęki, a ja zawsze będę z tobą. Wkrótce mój Syn Jezus przyjdzie, aby zniszczyć ogród, który szatan stworzył dla siebie: nie wierzcie w jego kłamstwa i iluzje. Jak wielu niestety jest częścią tego parszywego ogrodu! Tylko Pan przyniesie radość, pokój, radość i miłość. Mój Syn jest naprawdę przerażony bezczeszczeniem Jego ciała, które ma miejsce. Moje dzieci, dość z milczeniem ze strachu, świadczcie śpiewając hymny do Pana, milczenie ze strachu nie przyniesie pokoju, ale będzie uległością wobec kuszenia diabła. Teraz odchodzę od ciebie, ale wiedz, że jestem z tobą. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego. Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 16)), "Drogie dzieci, dziękuję wam, że jesteście zjednoczeni w modlitwie i że słuchacie mojego wołania w waszych sercach. Moi kochani, nieporządek, który was otacza, czasami przeraża niektórych z was, lecz bądźcie cierpliwi trochę dłużej, a porządek powróci na tę ziemię. Cena będzie wysoka, bo ludzkość będzie piła gorzki kielich cierpienia, ale ci, którzy powierzą wszystko mnie i mojemu Jezusowi, nie muszą się obawiać. Drogie dzieci, zło weszło do Kościoła, ale wy w międzyczasie trwajcie w modlitwie, w prawdzie i w prawach Bożych, a nic wam się nie stanie. Proszę was, moi mali, nie pozwólcie zbezcześcić ciała mojego Syna; błagam was, nie podążajcie za modernizmem, który sprawia, że trzoda już się załamuje i nie wie, co jest dobre, a co złe, ale podążajcie za Ewangelią, a nie będziecie mogli zbłądzić. Teraz przytulam was po kolei, bądźcie nadal światłem dla świata. Błogosławię Was w imię Ojca i Syna i Ducha Świętego. Amen. Wasza Matka." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 19)), "Dzieci moje, dziękuję wam za to, że jesteście zjednoczeni w modlitwie i że przyjęliście Moje wezwanie do waszych serc. Umiłowani moi, ewangelizujcie i krzyczcie, że Jezus przychodzi, aby was zbawić. Jestem smutna, bo nie słuchacie moich słów i za ból, który sprawiacie mojemu Synowi Jezusowi. Umiłowane dzieci, nie męczcie się, ponieważ teraz jest czas, aby rozejrzeć się wokół siebie i zobaczyć, kto jest w Chrystusie, a kto nie, to jest czas, aby wasza mowa była: tak-tak lub nie-nie! Bądź światłem świata, twoje światło musi być tak silne, aby wszyscy cię rozpoznali. Przygotujcie bezpieczne schronienia, przygotujcie wasze domy jako małe Kościoły, a ja będę tam z wami. Bunt jest gotowy, zarówno wewnątrz, jak i na zewnątrz Kościoła. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 23)), "Umiłowane dzieci, dziękuję wam za to, że zgromadziliście się na modlitwie i że wsłuchujecie się w moje wołanie w waszych sercach. Moje dzieci, rozejrzyjcie się wokół siebie, moje ukochane dzieci są jedne przeciwko drugim. Prosiłem was o modlitwę i nadal proszę o modlitwę, ponieważ teraz księża są przeciwko swoim braciom, biskupi przeciwko biskupom, a to wszystko powoduje tylko wielkie zamieszanie w stadzie. Moje dzieci, wróćcie do Boga, bo w ten sposób nigdzie nie dojdziecie, a tylko do całkowitego zatracenia. Nic nie wróci do poprzedniego stanu i nie dajcie się zwieść szatanowi, bo on jest ojcem kłamstwa. Opróżnijcie się z waszego ego i wypełnijcie się Bogiem, który jest jedyną prawdziwą radością. Bądź w harmonii z Niebiosami, abyś mógł ze spokojem stawić czoła Ostrzeżeniu, które jest coraz bliżej. Teraz zostawiam was z moim matczynym błogosławieństwem, Ojca i Syna i Ducha Świętego. Amen. Będę z wami przez cały czas trwania modlitwy." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 26)), "Moi umiłowani, dziękuję wam za to, że jesteście zjednoczeni w modlitwie i że słuchacie Mojego wołania w waszych sercach. Wkrótce, bardzo wkrótce, przyjdzie oświecenie [Ostrzeżenie] i wprowadzi was w stan ekstazy, który będzie trwał około 15 minut; oto niebo stanie się ogniście czerwone; wtedy usłyszycie bardzo głośny ryk, ale nie bójcie się, ponieważ będzie to zapowiedź, że Syn Boży ma przyjść. Moje ukochane dzieci, to są czasy, w których Antychryst ma dokonać swego wejścia. Dalej podam ci więcej instrukcji. Umiłowane dzieci, nie módlcie się tylko po to, aby prosić, ale także, aby podziękować mojemu Synowi Jezusowi za wasz pokój i wasze życie. Kocham was, małe dzieci, zawsze będę blisko was. Pamiętaj, że po ciszy nadejdzie burza. Módlcie się za potężnych, by Bóg mógł mieć litość nad nimi. Módlcie się za Kościół i za kapłanów. Błogosławię was teraz w imię Ojca i Syna i Ducha Świętego. Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 30)), "Dzieci moje, dziękuję wam, że jesteście zjednoczeni w modlitwie i że słuchacie mojego wołania w waszych sercach. Moi żołnierze światłości, bądźcie zawsze gotowi w swoim sercu do walki za mojego Syna Jezusa i bądźcie gotowi, by być jednym głosem z moimi aniołami. Dzieci moje, nie traćcie z oczu modlitwy, bo to, co przeżywacie, jest tylko złudzeniem spokoju, wszystko to nagle runie. Przypomnijcie wszystkim braciom, że do Nieba prowadzi tylko modlitwa różańcowa. Pamiętajcie o tym zawsze, moje dzieci! Módlcie się za Kościół i za osoby konsekrowane dręczone przez szatana, które są zmuszane do podejmowania bardzo bolesnych decyzji. Módlcie się za Amerykę, gdyż panuje tam zamieszanie. Teraz błogosławię was wszystkich, jednego po drugim, w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego. Amen." , dataset["text_pl"])





dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 3)), "Umiłowani moi, dziękuję wam, że zgromadziliście się w tym błogosławionym miejscu i dziękuję, że usłyszeliście moje wezwanie w waszych sercach. Umiłowane dzieci, wykorzystajcie ten czas, aby zbliżyć się do Boga, nie tylko poprzez modlitwę, ale przede wszystkim poprzez otwarcie waszych serc. Nadal jestem tutaj, aby pouczyć was o tym, co was spotka, o wszystkim, co jest przygotowane dla tej ludzkości i dla spotkania z Antychrystem, który wkrótce objawi się jako zbawiciel. Moje dzieci, wszystko się wali, bóle będą wielkie. Jeśli nie pozwolicie Jezusowi wejść do waszych serc, nie będziecie w stanie mieć pokoju, miłości i radości i stawić czoła trudnym czasom. Moje dzieci, być może jeszcze nie zrozumieliście, że jesteście na początku Apokalipsy! Módlcie się za Kościół, który jest mi tak drogi, aby wkrótce odrodził się w zjednoczeniu i miłości do Boga. Módlcie się za Japonię. Dzisiaj zstąpi na was wiele łask i będzie to znak Mojej obecności. Zostawiam was teraz z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego. Amen. Matka Boża miała na sobie płaszcz w kolorze cukierkowego różu i biały welon na głowie; w lewej ręce trzymała trzy różańce." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 9)), "Drogie dzieci, dziękuję wam, że zgromadziliście się tutaj na modlitwie i że wsłuchujecie się w moje wołanie w waszych sercach. Drogie dzieci, zawsze pamiętajcie o słowach mojego Syna Jezusa: kto jest prześladowany w imię moje, wejdzie do Królestwa Niebieskiego. Moje małe dzieci, czego się boicie? Wiedzcie, że zawsze będę przy was. Jakiegokolwiek wyboru dokonasz, zostaniesz osądzony. Nie bądźcie bierni, wołajcie o miłość jedynego Boga, który stworzył niebo i ziemię, i który wkrótce odnowi ziemię i niebo, tak że zło powróci stamtąd, skąd przyszło, z głębi piekła. Dzieci moje, spójrzcie na to, co się dzieje na świecie: morza wdzierające się do miast, trzęsienia ziemi, które będą coraz silniejsze i bardziej nieustanne. Moje dzieci, nawróćcie się pilnie, abyście podczas Ostrzeżenia nie odczuwali bólu, lecz miłość i pokój. Kościół zostanie odnowiony z małą trzódką, która pozostanie wierna mojemu Jezusowi i słowu mojego Ojca. Módlcie się za Amerykę i za Meksyk. Módlcie się za wszystkich prześladowanych i wiernych świętych kapłanów. Zostawiam was teraz z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego. Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 13)), "Dzieci moje, dziękuję wam, że zgromadziliście się w tym Świętym Domu (Kościele) na modlitwie i że wsłuchaliście się w moje wołanie w waszych sercach. Dziękuję wam, dzieci, że pocieszacie moje serce i Najświętsze Serce Jezusa. Dzieci moje, zawsze bądźcie gotowi, oto niebo i ziemia prawie się zjednoczyły. Dzieci moje, proszę was: karmcie się moim Synem Jezusem, który jest Boskością, Ciałem i Krwią. Mało tego, ci, którzy mną gardzą i bluźnią, będą mieli tylko gniew i gorycz, a ci, którzy uwierzyli, zachowają radość, pokój i miłość. Moje dzieci, prawda będzie musiała być wykrzyczana bez strachu i kiedy wykrzykujecie imię Jezusa prawdziwego Boga, demony będą drżeć, ale nie bójcie się, bo wielka ochrona zstąpi na was. Bądźcie gotowi. Nie zniechęcajcie się, jeśli was znieważają i prześladują, tak zostało napisane, albowiem wasze będzie Królestwo Niebieskie. Wiatry wojny będą wiać. Módlcie się za Włochy i za kapłanów, którzy w tym czasie są zdezorientowani. Poświęcajcie się codziennie mojemu Niepokalanemu Sercu i Najświętszemu Sercu Jezusa; tylko w ten sposób będziecie mogli złagodzić cierpienia w czasach, które nadejdą.  Zostawiam was teraz z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego. Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 16)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie i że słuchacie mojego wołania w waszych sercach. Moje dzieci, Jezus wkrótce będzie z wami; niech znajdzie wasze serca z zapalonymi lampami, a wasze oczy zobaczą cud nowego życia. Moje dzieci, bądźcie jeszcze trochę cierpliwi, zło ma zostać pokonane z tej ziemi. Wszystko, co zostało zniszczone na tej ziemi, zostanie odnowione, także Kościół i wiara. Ileż radości poczujecie w swoich sercach! Moje dzieci, módlcie się, módlcie się, módlcie się bardzo mocno, a ja zawsze będę blisko was. Spójrzcie na bunty, które będą miały miejsce na świecie i spójrzcie na niebo, które nie będzie już takie samo. A teraz zostawiam was z moim świętym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego. Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 20)), "Dzieci moje, dziękuję wam za to, że zgromadziliście się tutaj na modlitwie i że wsłuchujecie się w moje wołanie w waszych sercach. Umiłowane dzieci, dlaczego odrzucacie miłość i miłosierdzie mojego Syna Jezusa, przyjmujecie wszystko, co oferuje wam Niebo, dlaczego chcecie pozostać ze złamanym sercem i bez pokoju? Moje dzieci, módlcie się, módlcie się, módlcie się tak bardzo, prosiłam tak wiele razy i proszę ponownie, naprawdę nawróćcie się, to jest teraz pilne, czy nie rozumiecie, że te czasy się skończyły i kiedy Jezus przyjdzie, co zastanie na tej ziemi? Będziesz musiał być gotowy na to, co nadchodzi, prześladowania przyjdą i będziesz zmuszony modlić się w ukryciu. Proszę, moje dzieci, jestem waszą Matką i pragnę, abyście wszyscy byli zbawieni. Ogłaszając, że Chrystus przychodzi, Ojciec mój ma oczyścić ziemię z niegodziwości, która zawładnęła duszami. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 23)), "Dzieci moje, dziękuję wam za to, że zgromadziliście się na modlitwie i że wsłuchaliście się w moje wołanie w waszych sercach. Dzieci moje, dzisiaj przedstawiam się jako Matka Bolesna dla mojego Kościoła, ponieważ przeżywa on swoją mękę i tak jak mój Syn Jezus został pozostawiony sam sobie i ubiczowany. Moja mała resztka będzie prześladowana, płaczę nad młodymi ludźmi, którzy są daleko od Boga, płaczę nad rozbitymi rodzinami, płaczę nad nieochrzczonymi dziećmi i nad tymi, którzy dorastają w szponach zła, płaczę nad pasterzami, którzy zostawili moją trzodę samą, płaczę nad ludzkością, która zmierza do samozniszczenia. Błagam was moje dzieci, módlcie się i pocieszajcie moje niepokalane serce i Najświętsze Serce mojego Syna, zmieńcie swoje drogi, jeśli chcecie zbawienia powierzcie wszystko Bogu. A teraz zostawiam was z moim świętym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 27)), "Drogie dzieci, dziękuję wam, że jesteście zgromadzeni na modlitwie w tym miejscu pobłogosławionym przez mojego Ojca i dziękuję wam, że wsłuchaliście się w moje wołanie w waszych sercach. Dzieci moje, jesteście tutaj i patrzę na was po kolei, badam wasze serca i przynoszę wasze intencje do Pana, jak wiele miłości macie w sobie i dlatego nazywam was Dziećmi Światła, ponieważ z waszą wiarą napędzacie, przekształcacie serca z kamienia. Dzieci, zawsze miejcie mocną wiarę i pamiętajcie, że gdzie jest wiara, tam jest miłość, a gdzie jest miłość, tam jest Bóg, który jest drogą, prawdą i życiem. Kocham Cię z całą miłością Matki i błogosławię Cię w imię Trójcy Przenajświętszej, Amen." , dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 30)), "Bracia moi, dziękuję wam, że trwacie na modlitwie w Moim Domu i że słuchacie Mojego wołania. Moi bracia i dzieci, ten czas musi być czasem wielkiej refleksji, ponieważ wielu nadal nie słucha orędzi, które przychodzą z Nieba przeze mnie i Moją Najświętszą Matkę. Od jesieni pojawią się inne wirusy. Popatrz, co się dzieje w Moim Kościele, zachowanie Moich kapłanów jest pod obojętnym spojrzeniem tych, którzy mówią, że mają wiarę, popatrz, jak Mnie traktują, nie dbając o Moją Boskość i Łaskę, ale jak oni traktują Mnie, tak Ja będę traktował ich. Bracia moi, przyjdźcie do mnie, podajcie mi swoje ręce, a ja wam wskażę właściwą drogę. Bracia moi, nawróćcie się, czas już się skończył, bo inaczej, gdy wrócę, nie poznacie mnie i nie pójdziecie za mną. Moje dzieci, tylko ja mogę was poprowadzić drogą, która prowadzi do mojego Ojca. Módlcie się, bo ziemia zadrży ponad miarę. Módlcie się za Ojca Świętego. Teraz błogosławię was w imię Ojca, w imię moje i w imię Ducha Świętego, Amen." , dataset["text_pl"])


















dataset.to_csv("trevignano2020.csv", index=False, encoding="utf-8")
dataset.to_json("trevignano2020.json",orient="records")







