# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator

#dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "", dataset["text_it"])



dataset = pd.read_csv("january_cleaned.csv", encoding="utf-8")

dataset["text_pl"] = ""
dataset["text_en"] = ""
dataset["text_it"] = ""
dataset["month_string"] = "January"




# ITALIAN
dataset["text_it"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 1)), "Figlia e sorella mia, grazie per avermi accolto nel tuo cuore. Figlia mia, in questi tempi avete visto intorno a voi disperazione, morte e maldicenza, forse avete pensato di essere stati abbandonati da me? Siete continuamente pronti a lamentarvi, eppure Io molte volte vi ho consolato e di questo non vi siete mai accorti e non solo vi ho dato degli insegnamenti importanti, ma anche su questo non avete fatto caso. Figli e fratelli, Dio vi aspetta nell’amore e nella gioia, vi ho divisi per aiutarvi a riflettere, vi ho messi alla prova ogni Santo giorno e non sempre avete riflettuto. Quanta pace e gioia vorrei dare a questi cuori spesso induriti.  Vorrei che voi riflettiate, ma quante volte ho chiesto le vostre mani per condurvi verso le acque chete e invece avete preferito la tempesta credendo di essere capaci di risolvere tutto senza il mio aiuto, ma ricordate che solo Io sono la Via, la Verità e la Vita e solo Io posso aiutarvi, se solo vi affidaste davvero a me. Sono solo Io che posso stringere le vostre mani, quando mi chiedete aiuto con tutto il cuore e sono ancora Io che posso darvi la consolazione che meritate quando vi sentite soli. Figli miei, il mio tempo è vicino, entrate nell’Arca dell’alleanza, della pace, dell’amore e della fratellanza, solo così potrete superare la tempesta che è in arrivo. Vi ho insegnato tante cose in questo periodo e forse rileggendo con calma le mie parole riuscirete a comprendere la mia volontà, Io voglio vedervi entrare tutti nel mio Regno. Ora vi benedico nel nome della Santissima Trinità, siate sempre pronti alla lotta insieme a Me, ai miei Angeli, i miei Arcangeli e la mia Santissima Madre e riusciremo a sconfiggere il male assoluto, ed aprire le porte al bene infinito. Il vostro caro Gesù.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 3)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli, è una gioia vedervi uniti in un’unica voce, in un unico  cuore, siate sempre una famiglia unita, siate madri, padri e fratelli, l’uno con l’altro. Figli miei, quanto sarà costoso ciò che vedrete in questi tempi che arriveranno, ma affidate tutto a Gesù, Lui non vi abbandonerà e continuerà a consolare il vostro cuore e la vostra anima. Figli, se sapeste quanta bellezza c’è nel Regno di Dio, già pronto per voi, guardate al futuro con gioia perché dopo la purificazione della terra non ci sarà altro che amore, pace e gioia. Molti, in questo anno verranno guariti anche da mali orribili, quindi abbiate fiducia e offrite tutte le vostre sofferenze. Attenzione all’anticristo che sta già lavorando nel silenzio, ecco perché vi chiedo di aumentare la vostra fede, altrimenti non sarete neanche in grado di superare l’avvertimento che è prossimo. Figli, oggi molte grazie scenderanno su di voi, testimoniate e abbiate il coraggio della vera fede. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, Amen. Oggi i miei angeli sono tra voi e pregano con voi.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 8)), "Cari figli miei, grazie per avere ascoltato e risposto alla mia chiamata nel vostro cuore. Figli, bambini miei, vi chiedo l’urgente conversione, non vi accorgete che anche le giornate si sono velocizzate? Ma grazie alle vostre preghiere tutto volge in grande velocità, so che vorreste che tutto finisse presto, ma tutto ciò che è nella scrittura dovrà avere compimento. Figli, in questa battaglia spirituale dovrete essere pronti e in prima linea nel combattimento, voi che siete soldati di luce. Figli miei, presto un’ altro virus letale si affaccerà, siate pronti a lottare per le richieste di Gesù, ci saranno continue catastrofi naturali. Figli, la guerra è pronta, quando vi chiedo di fare scorte, non sarà solo per voi, ma anche per aiutare i vostri fratelli, perché tutto sta per crollare, compresa l’economia che porterà la carestia in tempi brevi. Figli miei. ascoltate le mie parole e fatene tesoro. Ora vi lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, sono con voi, vi amo e non vi abbandonerò mai. Vostra Madre.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 15)), "Cari figli, grazie per avere ascoltato e risposto alla mia chiamata nel vostro cuore.  Figli miei, pregate per i sacerdoti che si sono perduti e per la mia Chiesa dove il demonio serpeggia. Figli cari, pregate per i governanti affinché non portino avanti il loro progetto.  Figli miei, l’umanità è ormai senza ritorno verso il baratro, pregate e mettete tutto nelle piaghe di mio Figlio Gesù. Figli, vedrete tante cose che i vostri occhi non hanno mai visto, cantate Lodi al Signore, unica vostra salvezza. Mi rattrista molto vedere il sudiciume su questa terra, che il Padre mio ha benedetto con tanto amore, eppure adesso non credete più in Dio, ognuno ha creato i propri idoli, basta figli miei con la cattiveria, confessatevi e siate pronti ogni giorno. Presto scenderanno i miei angeli per confortare i miei poveri figli afflitti, rafforzate la vostra fede e aprite i cuori alla grazia per potervi trasformare, questo è il tempo.  Ora vi benedico nel nome del Padre del Figlio e dello Spirito Santo, Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 18)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore.  Figlia cara, devi dire a tutti che non devono temere nulla se sono nel Signore. Chiedo che ci sia l’unione nella preghiera, non fatevi tentare dalla paura, ma unitevi, sapete bene quanto è forte la preghiera comunitaria! Siate vigili e non fate come le vergini stolte, ma riempite d’olio le vostre lampade.  Figli miei, Gesù prende con sé molte anime, ricordate: uno sarà preso e uno verrà lasciato. Quando si vuole raggiungere Dio e si è pronti, il Signore sarà felice di accogliere queste anime in paradiso, molti invece dovranno purificarsi e altri resteranno sulla terra per continuare la propria missione, quindi come potrete comprendere, non siate legati alle cose del mondo, ma pregate per le vostre anime.  Andate alla messa e partecipate al sacrificio, cibatevi del corpo di mio Figlio, finché siete in tempo. La persecuzione sarà grande, quando decideranno di unificare le religioni. Ora vi lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 22)), "Cari e amorevoli figli, grazie per aver risposto alla mia chiamata nel vostro cuore e grazie per aver piegato le vostre ginocchia. Figli miei, guardate intorno a voi, niente è più come prima, ma voi cercate l’amore, siate amore per i vostri fratelli, siate amore per coloro che soffrono, i miei veri figli di luce esprimono amore ed è quasi tangibile. Figli miei, vi dico ancora una volta, non abbiate paura, non siate nell’angoscia perché questi sentimenti non vengono da Dio, siate luce per i vostri fratelli e consigliate loro di rifugiarsi nel mio cuore immacolato e in quello di mio Figlio Gesù, dove troveranno gioia e consolazione. Pregate per l’America perché verrà calpestata. Io vi sono accanto, non abbiate paura di tutto ciò che vedrete perché tutto sarà rinnovato, non provate sentimenti di rabbia, ma di gioia pura. Ora vi benedico nel nome del Padre del Figlio e dello Spirito Santo, Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 25)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, questi sono tempi duri e arriveranno momenti in cui la confusione sarà ancora più grande. Figli, pregate tanto, affinché la guerra che arriverà possa essere mitigata, la potenza della preghiera è grande. Pregate per la Chiesa, perché la fame di potere ha superato ogni limite e non ha più a che vedere con Dio. Pregate per i santi sacerdoti, affinché la luce possa sempre accompagnarli nel loro cammino di veri pastori. Quando pregate e sentite la pace nel vostro cuore, Io sono lì con voi per proteggervi. Figli miei, l’avvertimento è molto, ma molto vicino, tanti si inginocchieranno riconoscendo la potenza di Dio chiedendo perdono e tanti non crederanno perché presi dal potere di satana e moriranno senza pentimento. Siate pronti figli, Io vi avverto perché voglio che tutti i miei figli si salvino. Ora vi benedico nel nome del Padre del Figlio e dello Spirito Santo, Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 29)), "Figli miei, grazie per essere qui e per aver risposto alla mia chiamata nel vostro cuore. Figli, piegate sempre le vostre ginocchia, le preghiere recitate con fede e con il cuore mi confortano. Il mio cuore e quello di mio Figlio Gesù sanguinano, guardo questa umanità, che con tanta facilità cade nelle grinfie di satana, tutto questo per una falsa libertà. Ricordate figli miei, che solo la preghiera vi renderà liberi. Perdonate coloro che vi giudicano senza capire. Figlia mia, prima di te, Gesù è stato accusato di essere indemoniato e pazzo; eppure, era il Figlio di Dio. Figlia mia, offri la tua umiliazione e il tuo dolore, un giorno capiranno che le tue sono parole venute dal cielo. Figli miei, seguite le mie indicazioni, vivete i messaggi e pregate tanto, solo così potrete entrare nel Regno di Dio, tante saranno le tentazioni, ma voi, figli del mio cuore, siate fedeli e aprite i vostri cuori alla grazia e imparate ad offrire e ringraziare. Non abbiate mai paura, con Dio vicino, non ci sarà nulla da temere. Ora vi lascio la mia benedizione materna nel nome del Padre del Figlio dello Spirito Santo, Amen.", dataset["text_it"])



# ENGLISH
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 1)), "My daughter and sister, thank you for welcoming me into your heart. My daughter, in these times you have seen despair, death and backbiting all around you, perhaps you thought you had been abandoned by Me? You are constantly ready to complain, yet I have consoled you many times and you have never noticed this and not only have I given you important teachings, but you have not paid attention to this either. My children and brothers, God is waiting for you in love and joy, I have divided you to help you reflect, I have tested you every holy day and you have not always reflected. How much peace and joy I would like to give to these often hardened hearts.  I would like you to reflect, but how many times have I asked for your hands to lead you towards calm waters and instead you have preferred the storm believing that you are capable of solving everything without My help, but remember that I alone am the Way, the Truth and the Life and I alone can help you, if only you would really entrust yourselves to Me. It is only I who can hold your hands when you ask Me for help with all your heart and it is still I who can give you the consolation you deserve when you feel alone. My children, My time is near, enter the Ark of the Covenant, of peace, of love and brotherhood, only in this way will you be able to overcome the storm that is coming. I have taught you many things in this period and perhaps by calmly rereading my words you will be able to understand My Will, I want to see you all enter My Kingdom. I want to see you all enter into My Kingdom. Now I bless you in the name of the Most Holy Trinity, always be ready to fight together with Me, My Angels, My Archangels and My Blessed Mother and we will succeed in defeating absolute evil and opening the doors to the infinite good. Your dear Jesus.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 3)), "My children, thank you for having responded to my call in your hearts. My children, it is a joy to see you united in one voice, in one heart, always be a united family, be mothers, fathers and brothers, with each other. My children, how costly will be what you will see in these times to come, but entrust everything to Jesus, He will not abandon you and will continue to console your heart and soul. Children, if you knew how much beauty there is in the Kingdom of God, already ready for you, look to the future with joy because after the purification of the earth there will be nothing but love, peace and joy. Many, in this year will be healed even from horrible evils, so trust and offer all your sufferings. Beware of the antichrist who is already working in silence, that is why I ask you to increase your faith, otherwise you will not even be able to overcome the Warning that is near. Children, today many graces will descend upon you, witness and have the courage of true faith. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen. Today my angels are among you and are praying with you.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 8)), "My dear children, thank you for having listened and responded to my call in your hearts. My children, my children, I ask you for urgent conversion, do you not notice that even the days have quickened? I know that you would like everything to end soon, but everything that is in writing must be fulfilled. My children, in this spiritual battle you must be ready and in the forefront of the fight, you who are soldiers of light. My children, soon another lethal virus will appear, be ready to fight for the demands of Jesus, there will be continuous natural catastrophes. My children, the war is ready, when I ask you to stock up, it will not be only for you, but also to help your brothers, because everything is about to collapse, including the economy that will bring famine in a short time. My children. listen to my words and treasure them. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, I am with you, I love you and I will never abandon you. Your Mother.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 15)), "Dear children, thank you for having listened and responded to my call in your hearts.  My children, pray for the priests who are lost and for my Church where the devil is wandering. Dear children, pray for the rulers so that they do not carry out their project.  My children, humanity is now without return towards the abyss, pray and put everything into the wounds of my Son Jesus. My children, you will see many things that your eyes have never seen, sing praises to the Lord, your only salvation. It saddens me very much to see the filth on this earth, which my Father has blessed with so much love, yet now you no longer believe in God, everyone has created their own idols, enough my children with wickedness, confess and be ready every day. Soon my angels will come down to comfort my poor afflicted children, strengthen your faith and open your hearts to grace in order to be transformed, this is the time.  Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 18)), "Dear children, thank you for responding to my call in your hearts. Beloved daughter, you must tell everyone that they need not fear anything if they are in the Lord. I ask that there be union in prayer, do not be tempted by fear, but unite, you know well how strong community prayer is! Be vigilant and do not be like the foolish virgins, but fill your lamps with oil. My children, Jesus takes many souls with Him, remember: one will be taken and one will be left. When you want to reach God and you are ready, the Lord will be happy to welcome these souls into paradise, many instead will have to purify themselves and others will remain on earth to continue their mission, so as you can understand, do not be tied to the things of the world, but pray for your souls.  Go to Mass and participate in the sacrifice, feed on the body of my Son, while there is still time. Persecution will be great when they decide to unify religions. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 22)), "Dear and loving children, thank you for responding to my call in your heart and thank you for kneeling down. My children, look around you, nothing is the same as before, but you seek love, be love for your brothers, be love for those who suffer, my true children of light express love and it is almost tangible. My children, I tell you once again, do not be afraid, do not be in anguish because these feelings do not come from God, be light for your brothers and advise them to take refuge in my Immaculate Heart and in that of my Son Jesus, where they will find joy and consolation. Pray for America because she will be trampled underfoot. I am beside you, do not be afraid of everything you see because everything will be renewed, do not feel feelings of anger, but of pure joy. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 25)), "Dear children, thank you for having responded to my call in your hearts. My children, these are hard times and there will come times when the confusion will be even greater. My children, pray so much so that the war that will come may be mitigated, the power of prayer is great. Pray for the Church, for the hunger for power has exceeded all limits and no longer has anything to do with God. Pray for the holy priests, that light may always accompany them on their journey as true shepherds. When you pray and feel peace in your heart, I am there with you to protect you. My children, the Warning is very, very near, many will kneel down and acknowledge the power of God asking for forgiveness and many will not believe because they are taken by the power of Satan and will die without repentance. Be ready children, I warn you because I want all my children to be saved. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 29)), "My children, thank you for being here and for responding to my call in your hearts. My children, always kneel down, prayers recited with faith and heart comfort me. My heart and that of my Son Jesus bleed, I look at this humanity, which so easily falls into the clutches of Satan, all this for a false freedom. Remember, my children, that only prayer will make you free. Forgive those who judge you without understanding. My daughter, before you, Jesus was accused of being unholy and insane; yet, He was the Son of God. My daughter, offer your humiliation and your pain, one day they will understand that yours are words from heaven. My children, follow my directions, live the messages and pray a lot, only in this way will you be able to enter the Kingdom of God, many will be the temptations, but you, children of my heart, be faithful and open your hearts to grace and learn to offer and give thanks. Never be afraid, with God near, there will be nothing to fear. Now I leave you my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])



# POLISH
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 1)), "Moja córko i siostro, dziękuję ci, że przyjęłaś mnie do swojego serca. Córko Moja, w tych czasach widziałaś wokół siebie rozpacz, śmierć i oszczerstwa; może myślałaś, że zostałaś opuszczona przeze Mnie? Ciągle jesteście gotowi narzekać, a ja wielokrotnie was pocieszałem, jednak wy nigdy tego nie zauważyliście. Udzielałem wam ważnych nauk, lecz wy również nie zwracaliście na to uwagi. Moje dzieci i bracia, Bóg czeka na was z miłością i radością, podzieliłem was, aby pomóc wam w refleksji, wystawiłem was na próbę w każdy dzień święty, a wy nie zawsze to rozważaliście. Ileż pokoju i radości chciałabym dać tym często zatwardziałym sercom. Chciałbym, abyście się zastanowili, ile razy prosiłem wasze ręce, aby poprowadziły was ku spokojnym wodom, a wy zamiast tego woleliście burzę, wierząc, że jesteście w stanie rozwiązać wszystko bez mojej pomocy, lecz pamiętajcie, że tylko Ja jestem Drogą, Prawdą i Życiem i tylko Ja mogę wam pomóc, jeśli tylko prawdziwie powierzycie się Mnie. Tylko ja mogę trzymać was za ręce, gdy z całego serca prosicie mnie o pomoc i tylko ja mogę dać wam pocieszenie, na które zasługujecie, gdy czujecie się samotni. Moje dzieci, mój czas jest bliski, wejdźcie do Arki Przymierza, pokoju, miłości i braterstwa, tylko w ten sposób będziecie mogli pokonać burzę, która nadchodzi. Nauczyłem was wielu rzeczy w tym czasie i być może poprzez spokojne ponowne przeczytanie moich słów będziecie mogli zrozumieć moją wolę, chcę zobaczyć was wszystkich wchodzących do mojego Królestwa. Błogosławię was w imię Trójcy Przenajświętszej, bądźcie zawsze gotowi walczyć razem ze Mną, Moimi Aniołami, Moimi Archaniołami i Moją Przenajświętszą Matką, a uda nam się pokonać zło absolutne i otworzyć drzwi do nieskończonego dobra. Wasz kochany Jezus.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 3)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, to radość widzieć was zjednoczonych w jednym głosie, w jednym sercu, bądźcie zawsze zjednoczoną rodziną, bądźcie matkami, ojcami i braćmi, jedni dla drugich. Moje dzieci, ileż kosztować was będzie to, co zobaczycie w tych czasach, które mają nadejść, ale powierzcie wszystko Jezusowi, On was nie opuści i nadal będzie pocieszał wasze serce i duszę. Moje dzieci, gdybyście wiedzieli, ile piękna jest w Królestwie Bożym, które jest już dla was gotowe, patrzcie w przyszłość z radością, bo po oczyszczeniu ziemi będzie tylko miłość, pokój i radość. Wielu w tym roku zostanie uzdrowionych nawet z okropnych złych rzeczy, więc miejcie wiarę i ofiarujcie wszystkie swoje cierpienia. Strzeżcie się antychrysta, który już działa w ciszy, dlatego proszę was, abyście zwiększyli swoją wiarę, w przeciwnym razie nie będziecie w stanie nawet sprostać Ostrzeżeniu, które jest blisko. Dzieci moje, dzisiaj zstąpi na was wiele łask, dajcie świadectwo i miejcie odwagę prawdziwej wiary. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen. Dziś moi aniołowie są wśród was i modlą się z wami.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 8)), "Moje drogie dzieci, dziękuję wam za to, że wysłuchaliście i odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, moje dzieci, proszę was o pilne nawrócenie, czy nie zauważyliście, że nawet dni przyspieszyły? Wiem, że chciałabyś, aby wszystko szybko się skończyło, ale wszystko, co jest napisane, musi się wypełnić. Dzieci moje, w tym duchowym boju musicie być gotowi i stać w pierwszej linii walki, wy, którzy jesteście żołnierzami światłości. Moje dzieci, wkrótce pojawi się kolejny śmiertelny wirus, bądźcie gotowi do walki o spełnienie wymagań Jezusa, będą ciągłe katastrofy naturalne. Moje dzieci, wojna jest gotowa, kiedy poproszę was o zapasy, nie będzie to tylko dla was, ale także, aby pomóc waszym braciom, ponieważ wszystko ma się zawalić, w tym gospodarka, która przyniesie głód w krótkim czasie. Moje dzieci, słuchajcie moich słów i cencie je. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego; jestem z wami, kocham was i nigdy was nie opuszczę. Wasza Mama.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 15)), "Drogie dzieci, dziękuję wam za to, że usłyszeliście i odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, módlcie się za kapłanów, którzy się zagubili i za mój Kościół, w którym grasuje diabeł. Drogie dzieci, módlcie się za władców, aby nie realizowali swojego projektu. Dzieci moje, ludzkość jest już bez powrotu w przepaść, módlcie się i włóżcie wszystko w rany mojego Syna Jezusa. Dzieci moje, ujrzycie wiele rzeczy, których wasze oczy nigdy nie widziały; śpiewajcie chwałę Panu, waszemu jedynemu zbawieniu. Bardzo mnie smuci, gdy widzę brud na tej ziemi, którą mój Ojciec pobłogosławił z tak wielką miłością, a jednak teraz już nie wierzycie w Boga, każdy stworzył swoje własne bożki, dość moje dzieci z niegodziwością, wyznajcie i bądźcie gotowi każdego dnia. Wkrótce moi aniołowie zstąpią, aby pocieszyć moje biedne, strapione dzieci, wzmocnić waszą wiarę i otworzyć wasze serca na łaskę, abyście mogli zostać przemienieni, to jest ten czas. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 18)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowana córko, musisz powiedzieć wszystkim, że nie mają się czego obawiać, jeśli są w Panu. Proszę o zjednoczenie w modlitwie, nie dajcie się skusić lękowi, ale zjednoczcie się, dobrze wiecie, jak silna jest modlitwa wspólnotowa! Bądźcie czujni i nie bądźcie jak głupie panny, lecz napełnijcie wasze lampy oliwą. Moje dzieci, Jezus zabiera ze sobą wiele dusz, pamiętajcie: jedna będzie wzięta, a druga zostawiona. Gdy będziecie chcieli dotrzeć do Boga i będziecie gotowi, Pan z radością przyjmie te dusze do raju, lecz wiele z nich będzie musiało się oczyścić, a inne pozostaną na ziemi, by kontynuować swoją misję, więc jak rozumiecie, nie przywiązujcie się do rzeczy tego świata, lecz módlcie się za swoje dusze. Chodźcie na Mszę św. i uczestniczcie w ofierze, karmcie się Ciałem mojego Syna, póki jeszcze jest czas. Prześladowania będą wielkie, gdy zdecydują się na ujednolicenie religii. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 22)), "Drogie i kochające dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach i dziękuję, że uklękneliście. Dzieci moje, rozejrzyjcie się wokół siebie, nic nie jest takie samo jak dawniej, lecz wy szukacie miłości, bądźcie miłością dla waszych braci, bądźcie miłością dla tych, którzy cierpią, moje prawdziwe dzieci światła wyrażają miłość i jest ona prawie namacalna. Dzieci moje, jeszcze raz wam mówię: nie bójcie się, nie dręczcie się, bo te uczucia nie pochodzą od Boga, bądźcie światłem dla waszych braci i poradźcie im, by schronili się w moim Niepokalanym Sercu i w Sercu mojego Syna Jezusa, gdzie znajdą radość i pocieszenie. Módlcie się za Amerykę, ponieważ zostanie ona zdeptana. Jestem blisko was, nie bójcie się tego wszystkiego, co zobaczycie, bo wszystko będzie odnowione, nie odczuwajcie uczuć gniewu, ale czystą radość. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 25)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, to są ciężkie czasy i nadejdą takie, w których zamieszanie będzie jeszcze większe. Dzieci moje, módlcie się nieustannie, aby wojna, która nadejdzie, została złagodzona, moc modlitwy jest wielka. Módlcie się za Kościół, ponieważ głód władzy przekroczył wszelkie granice i nie ma już nic wspólnego z Bogiem. Módlcie się za świętych kapłanów, aby światło zawsze towarzyszyło im na ich drodze jako prawdziwym pasterzom. Kiedy modlisz się i czujesz pokój w swoim sercu, jestem tam z tobą, aby cię chronić. Moje dzieci, Ostrzeżenie jest bardzo, bardzo bliskie, wielu uklęknie w uznaniu Bożej mocy i będzie prosić o przebaczenie, a wielu nie uwierzy, ponieważ zostali porwani przez moc szatana i umrą bez pokuty. Bądźcie gotowe dzieci, ostrzegam was, bo chcę, aby wszystkie moje dzieci były zbawione. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 1) & (dataset["day"] == 29)), "Dzieci moje, dziękuję wam, że jesteście tutaj i że odpowiadacie na moje wezwanie w waszych sercach. Dzieci moje, zawsze klękajcie, modlitwy odmawiane z wiarą i sercem pocieszają mnie. Serce moje i mojego Syna Jezusa krwawi, gdy patrzę na tę ludzkość, która tak łatwo wpada w szpony szatana, a wszystko to dla fałszywej wolności. Pamiętajcie, moje dzieci, że tylko modlitwa uczyni was wolnymi. Wybaczcie tym, którzy osądzają was bez zrozumienia. Moja córko, przed tobą Jezus został oskarżony o opętanie i szaleństwo, a przecież był Synem Bożym. Moja córko, ofiaruj swoje upokorzenie i swój ból; pewnego dnia zrozumieją, że twoje słowa pochodzą z Nieba. Moje dzieci, podążajcie za moimi wskazaniami, żyjcie orędziami i módlcie się nieustannie, tylko w ten sposób będziecie mogli wejść do Królestwa Bożego, wiele będzie pokus, ale wy, dzieci mojego serca, bądźcie wierne i otwórzcie wasze serca na łaskę i nauczcie się ofiarowywać i dziękować. Nigdy się nie lękajcie, z Bogiem przy sobie, nie będzie się czego bać. Teraz zostawiam wam moje matczyne błogosławieństwo w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])






import goslate
gs = goslate.Goslate()

dataset["text_es"] = dataset["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset["text_fr"] = dataset["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset["text_zh"] = dataset["text_en"].apply(lambda x: gs.translate(x,'zh'))


dataset["text_de"] = dataset["text_en"].apply(lambda x: gs.translate(x,'de'))

dataset["text_pt"] = dataset["text_en"].apply(lambda x: gs.translate(x,'pt'))





dataset.to_csv("january_2022.csv", encoding="utf-8", index=False)





