# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator
import goslate
gs = goslate.Goslate()

#dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "", dataset["text_it"])



dataset = pd.read_csv("march_2022.csv", encoding="utf-8")






# ITALIAN
dataset["text_it"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 1)), "Amati figli, grazie per aver piegato le vostre ginocchia nella preghiera e per aver risposto alla mia chiamata nel vostro cuore. Figli miei, pregate per la pace nel mondo, perché questa guerra andrà avanti a causa di leader mondiali che continuano a pensare solo al potere e alle cose del mondo. Figli miei, la purificazione metterà tutti alla prova, siate dalla parte di Dio. Pregate per un leader politico che subirà un attentato.  Pregate per la chiesa e per tutti gli innocenti, che con il loro sangue laveranno i peccati dell’umanità. Pregate per il governo italiano, perché all’interno di esso vi è un guerrafondaio. Pregate per la Francia. Pregate, perché l’umanità perversa è causa di tutto questo. Ora vi benedico, nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Amati figli, grazie per aver risposto alla mia chiamata nel vostro cuore e per aver piegato le vostre ginocchia nella preghiera. Figli miei, nonostante tutto ciò che vedete intorno a voi, spesso non vi rendete conto e pensate che la guerra non vi appartiene perché non è a casa vostra, ma purtroppo non sarà così, questo è il motivo del mio continuo appello alla conversione. Figli, vi prego, accogliete tutti i miei messaggi con amore, Io vi guiderò per non farvi perdere la strada, ma voi invece di avvicinarvi a Dio vi allontanate. Figli miei, la via da voi intrapresa non è giusta, altro arriverà, eppure continuate a vivere la vostra piccola vita senza pensare che intorno a voi, il demonio sta distruggendo tutto e non avete cura delle vostre anime. Credete che la vita sia tutta questa? Ma non credete che esiste la dannazione eterna, se vi farete guidare dal demonio? Figli miei, pregate per il Medio Oriente, l’Avvertimento è qui. Fatevi trovare pronti, figli, Io vi prego. Non fatevi mancare la confessione e l’Eucarestia, perché dovete compensare quando non potrete più usufruirne. Datemi le vostre mani e Io vi condurrò dove c’è la gioia e l’amore puro. Vi lascio la pace e portatela alle vostre famiglie. Vi benedico nel nome del Padre, del Figlio e dello Spirito Santo. Amen. La Madonna dice che farà scendere anche delle grazie sui presenti, in particolare su una ragazza giovane che ha un tumore, qualcuno di voi, oggi ha pregato per questa intenzione.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8)), "Cara figlia mia, grazie per aver accolto la mia chiamata nel tuo cuore. Figlia, ti prego di chiedere a tutti i miei figli di togliere la superbia che ancora imperversa nei loro cuori. Basta con la zizzania che allontana i fratelli e basta con l’arroganza, ma piegate le vostre ginocchia al Signore. Pentitevi figli miei, non è troppo tardi, pentitevi fino alla fine e non fatevi tentare dal demonio perché la sua astuzia è pungente. Pregate per il mondo, perché non ci sarà più pace, fate penitenza figli cari, non è più tempo di vivere per le cose del mondo, ma alzate lo sguardo verso il cielo e siate più spirituali, la vostra elevazione vi porterà solo benefici. La terra ormai è costituita da un’umanità perversa e sorda ai miei richiami di Madre.  Ora vi lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 10)), "Io, vostro Padre sono qui per ricordarvi che vi amo tutti. Non abbiate paura, mio Figlio fu il primo uomo preso e chiamato eretico dai padri della Chiesa. E allora di cosa temete? Non abbiate paura. Lui ha vinto la morte e Io sarò con voi sempre. Perché non capite? Perché l’umanità non capisce che Io vi amo tutti e come Padre, sento il dovere di starvi accanto, proteggendovi. Come Padre, vi proteggerò davanti a tutti coloro che vi chiameranno eretici. Non preoccupatevi. Guardate adesso come tutto precipiterà. Anche il vostro rifugio sarà pronto per quel periodo. Io sto sollecitando tutto, in modo che quando Maria Santissima, vi dirà che sarà ora di andare, voi dovrete recarvi alla croce blu (collina benedetta  di trevignano romano ) e lì non sarete mai toccati, perché Io personalmente ho santificato quel posto. Non preoccupatevi, lasciate andare le cose umane e abbiate Fede, tutto si realizzerà come da mio progetto. Gli angeli, nel luogo da me benedetto, vi proteggeranno e vi metteranno al sicuro, vi renderanno invisibili ed Io non vi farò mancare nulla. Io sono un Padre buono, ma sono un Padre giusto. Vi amo figli miei, vi amo tanto, non abbiate paura, non temete, tutto ciò che avrete sarà solo per grazia mia. Ora vi lascio. Vostro Padre, Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 12)), "Figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, i cieli sono invasi dalle tenebre, che prenderanno molte anime comprese quelle della Chiesa. Accogliete i vostri fratelli senza aver paura, perché potrebbe accadere anche a voi.  Figli miei, per darvi consolazione vi dico, che dopo le macerie sulla terra, vedrete scendere la nuova Gerusalemme e sarà simile al paradiso. Il mondo rinascerà e si inchinerà davanti a Dio, ci sarà la conversione mondiale compresa la Cina, avrete tanti anni di pace, armonia e tanto amore tra fratelli, non abbiate paura, perché questa purificazione sarà necessaria per rinascere tutto nuovo. La mano e la protezione su questa collina Benedetta (collina di Trevignano Romano) ci sarà sempre e servirà a convertire molte persone. Un giorno vedrete gli angeli qui presenti, manifestarsi con la corona del Salvatore sulle mani e con il suono delle cetre, canteranno Lodi e Inni al Signore. Ora vi lascio con la mia benedizione materna nel nome del Padre del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 15)), "Figli miei cari, grazie per aver risposto alla mia chiamata nel vostro cuore e per aver piegato le ginocchia nella preghiera. Figli amati, quanto dolore sento nel mio cuore, vi guardo, state camminando su un terreno minato non solo da bombe, ma dal male.  Nonostante i miei innumerevoli appelli ancora dubitate, eppure Io vostra Madre, ho sempre avvertito di ciò che sarebbe arrivato se in voi, non ci fosse stata, la vera conversione, ascoltatemi!  Figli miei, vi chiedo ancora una volta: affidate la vostra vita e le vostre giornate a Dio, abbiate fede in Lui, il Giusto che tutto può. Gli uomini non sono pronti a ciò che arriverà improvvisamente, credono solo alle voci del mondo e non alle parole Sante di una Madre che piange e si addolora per tutti. Voglio salvarvi, capite questo monito? La carestia avanzerà senza pietà, aiutatevi tra fratelli. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 19)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore e per aver piegato le ginocchia nella preghiera. Bambini miei cari, siate sempre pronti per ciò che accadrà all’improvviso, l’Europa sarà invasa, pregate per l’Occidente, pregate per il Papa, perché questa è l’ora del suo grande dolore e preoccupazione. Figli miei, ricordate che la preghiera è l’unica medicina per la vostra anima e per il vostro corpo, aprite i vostri cuori alla Grazia, perché solo così riuscirete ad avere pace nei vostri cuori, nonostante i tempi bui. Figli cari, non abbiate paura, ma prendete le mie mani e vi porterò a mio Figlio Gesù. Figli, la persecuzione sarà grande, quindi siate sempre nella fede anche quando tutto sembrerà perduto, affidatevi a Dio, Lui sarà vicino a voi tutti i giorni, fino alla fine. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 24)), "Cara figlia, grazie per aver ascoltato la mia chiamata nel tuo cuore. Gli uomini ancora non capiscono il perché della mia venuta, Io voglio salvare questa umanità, alla quale dico: smettete di innalzare la curiosità nel leggere i miei messaggi, ma viveteli. Vedo i miei figli perdersi e vorrei mostrare loro la strada. Vengo come Madre amorevole per far vedere la luce in mezzo alle tenebre. Con le vostre preghiere e con Vera Fede potrete evitare la terza guerra mondiale, ma ancora siete chiusi nei vostri gusci e non vedete oltre, le catastrofi stanno arrivando, ma voi non abbandonate i sacramenti.  Nonostante le mie lacrime, i vostri cuori sono duri e non fate entrare la luce, chiedo che la vostra Fede non sia solo di parole, ma di fatti, avete l’arma più potente, la preghiera del Santo Rosario, pregate. Con l’avanzare del tempo, la Fede Cristiana non sarà più professata e sarete costretti a nascondervi, siate preparati anche a questo, il comunismo avanza con celerità. Tutto quanto avverrà e sarà la punizione per le eresie, le bestemmie e le blasfemie che fino ad oggi sono perpetrate. Ora, figlia mia, ti lascio con la mia benedizione Materna, nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 25)), "Figlia mia, grazie per aver accolto la mia chiamata nel tuo cuore. Figlia, quel giorno mentre canticchiavo Lodi a Dio e chiedevo la pace per la terra tutta, ecco che arrivò un angelo meraviglioso che illuminò la stanza e la sua voce dolce mi annunciò che avrei avuto un figlio per opera dello Spirito Santo, nonostante la mia verginità e mi parlò della grandezza di Gesù. Pregai per tutta la mia vita per la pace, così come oggi, eppure gli uomini non mi hanno ascoltato e anche adesso non ascoltano. Figlia mia, oggi, molti credono che questa consacrazione possa avere validità, ma la guerra ha avuto inizio, mio Figlio è adirato, perché se fosse stata pronunciata in tempo, la pace sarebbe scesa su questa umanità, ma non sarà così, perché nessuno può offendere Dio. Figlia mia, tutto verrà lievemente mitigato dalle preghiere recitate con vera fede. Presto vivrete tempi bui per i motivi che ti ho appena narrato, vi prego tornate a Dio. Ti benedico nel nome della Santissima Trinità.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 26)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore e per aver piegato le ginocchia nella preghiera. Figli miei, Io ho già parlato, vi chiedo: aprite i vostri cuori alla grazia per essere degni di tutto ciò che Dio ha in serbo per voi. Figli, pregate per la pace, ma prima di tutto per la pace interiore, non perdetevi in cose effimere, ma pensate più alla vostra anima. Ancora vi chiedo: convertitevi, guardate i tempi bui, non attendete il giudizio finale di Dio, ma siate consapevoli di tutto ciò che arriverà, se non sarete pronti non potrete affrontare l’avvertimento. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])

# ENGLISH
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 1)), "Beloved children, thank you for bending your knees in prayer and answering my call in your heart. My children, pray for peace in the world, for this war will go on because of world leaders who continue to think only of power and the things of the world. My children, purification will test everyone, be on God's side. Pray for a political leader who will suffer an attack. Pray for the church and for all the innocents, who will wash the sins of humanity with their blood. Pray for the Italian government, because there is a warmonger within it. Pray for France. Pray, because perverse humanity is the cause of all this. Now I bless you, in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Beloved children, thank you for responding to my call in your hearts and for bending your knees in prayer. My children, in spite of all that you see around you, you often do not realize and think that the war does not belong to you because it is not at home, but unfortunately this will not be the case, this is the reason for my continuous call to conversion. My children, I beg you, accept all my messages with love, I will guide you so that you do not lose your way, but instead of coming closer to God, you are moving away. My children, the way you have taken is not right, more will come, yet you continue to live your little life without thinking that around you, the devil is destroying everything and you have no care for your souls. Do you believe that this is what life is all about? But do you not believe that there is eternal damnation if you let the devil lead you? My children, pray for the Middle East, the Warning is here. Be ready, children, I beg you. Do not miss confession and the Eucharist, for you must make up for it when you can no longer use them. Give me your hands and I will lead you where there is joy and pure love. I leave you peace and take it to your families. I bless you in the name of the Father and the Son and the Holy Spirit, Amen. Our Lady says that she will also bring down graces on those present, especially on a young girl who has a tumor, some of you, today prayed for this intention.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8)), "Dear daughter, thank you for accepting my call in your heart. Daughter, I beg you to ask all My children to remove the pride that still rages in their hearts. Enough with the discord that drives away the brothers and enough with arrogance, but bend your knees to the Lord. Repent my children, it is not too late, repent to the end and do not be tempted by the devil because his cunning is sharp. Pray for the world, for there will be no more peace, do penance dear children, it is no longer time to live for the things of the world, but raise your eyes to heaven and be more spiritual, your elevation will bring you only benefits. The earth is now made up of a perverse humanity deaf to my calls as a Mother. Now I leave you with my motherly blessing in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 10)), "I, your Father am here to remind you that I love you all. Do not be afraid, My Son was the first man taken and called a heretic by the fathers of the Church. So what are you afraid of? Do not be afraid. He has conquered death and I will be with you always. Why do you not understand? Because mankind does not understand that I love you all and as Father, I feel the duty to be by your side, protecting you. As Father, I will protect you before all those who will call you heretics. Do not worry. Watch now how everything will fall apart. Even your shelter will be ready for that time. I am urging everything, so that when Mary Most Holy tells you that it is time to go, you will have to go to the Blue Cross (blessed hill of Trevignano Romano) and there you will never be touched, because I personally have sanctified that place. Do not worry, let go of human things and have Faith, everything will come true as per My plan. The angels, in the place blessed by Me, will protect you and make you safe, they will make you invisible and I will not make you lack anything. I am a good Father, but I am a just Father. I love you My children, I love you so much, do not be afraid, do not fear, all that you will have will be by My grace alone. I leave you now. Your Father, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 12)), "My children, thank you for having responded to My call in your hearts. My children, the heavens are invaded by darkness, which will take many souls including those of the Church. Receive your brothers without fear, for it could also happen to you. My children, to give you consolation, I tell you that after the ruins on earth, you will see the new Jerusalem descend and it will be similar to paradise. The world will be reborn and will bow down before God, there will be worldwide conversion including China, you will have many years of peace, harmony and much love among brothers, do not be afraid, because this purification will be necessary to be reborn all over again. The hand and the protection on this blessed hill (hill of Trevignano Romano) will always be there and will serve to convert many people. One day you will see the angels here, manifest themselves with the crown of the Savior on their hands and with the sound of lyres, they will sing Praises and Hymns to the Lord. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 15)), "My beloved children, thank you for responding to my call in your hearts and for bending your knees in prayer. Beloved children, how much pain I feel in my heart, I look at you, you are walking on ground undermined not only by bombs, but by evil. In spite of my innumerable appeals, you still doubt, yet I, your Mother, have always warned of what would come if there were no true conversion in you; listen to me! My children, I ask you once again: entrust your life and your days to God, have faith in Him, the Just One who can do everything. Men are not ready for what will suddenly come, they believe only the voices of the world and not the Holy words of a Mother who cries and grieves for all. I want to save you, do you understand this warning? The famine will advance without mercy, help each other among brothers. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 19)), "My children, thank you for answering my call in your hearts and for bending your knees in prayer. My dear children, always be ready for what will happen suddenly, Europe will be invaded, pray for the West, pray for the Pope, for this is the hour of his great sorrow and concern. My children, remember that prayer is the only medicine for your soul and your body, open your hearts to Grace, because only in this way will you be able to have peace in your hearts, despite the dark times. Dear children, do not be afraid, but take my hands and I will bring you to my Son Jesus. My children, persecution will be great, so always be in faith even when all seems lost, trust in God, He will be close to you every day, until the end.  Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 24)), "Dear daughter, thank you for listening to My call in your heart. Men still do not understand the reason for my coming, I want to save this humanity, to which I say: stop raising your curiosity in reading my messages, but live them. I see my children getting lost and I want to show them the way. I am coming as a loving Mother to show the light in the midst of darkness. With your prayers and True Faith you can avoid the third world war, but still you are closed in your shells and do not see beyond, catastrophes are coming, but you do not abandon the sacraments. Despite my tears, your hearts are hard and you do not let the light in, I ask that your Faith be not only of words, but of deeds, you have the most powerful weapon, the prayer of the Holy Rosary, pray. As time goes by, the Christian Faith will no longer be professed and you will be forced to hide, be prepared for this as well, communism advances with rapidity. All of this will take place and will be the punishment for the heresies and blasphemies that have been perpetrated until now. Now, my daughter, I leave you with my Motherly blessing, in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 25)), "My daughter, thank you for accepting my call into your heart. Daughter, that day while I was humming Praises to God and asking for peace for the whole earth, behold a wonderful angel came and lit up the room and his sweet voice announced to me that I would have a son by the Holy Spirit, despite my virginity and spoke to me of the greatness of Jesus. I prayed all my life for peace, just as I do today, yet men did not listen to me and even now they do not listen. My daughter, today, many believe that this consecration can have validity, but the war has begun, my Son is angry, because if it had been pronounced in time, peace would have descended on this humanity, but it will not be so, because no one can offend God. My daughter, everything will be slightly mitigated by prayers recited with true faith. Soon you will experience dark times for the reasons I have just told you, please return to God. I bless you in the name of the Most Holy Trinity.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 26)), "My children, thank you for responding to My call in your hearts and for bending your knees in prayer. My children, I have already spoken, I ask you: open your hearts to grace to be worthy of all that God has in store for you. My children, pray for peace, but first of all for inner peace; do not lose yourselves in ephemeral things, but think more of your soul. Again I ask you: convert, look at the dark times, do not wait for God's Final Judgment, but be aware of all that will come, if you are not ready you will not be able to face the warning. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])

# POLISH
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 1)), "Umiłowane dzieci, dziękuję wam, że uklęknęliście do modlitwy i odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, módlcie się o pokój na świecie, ponieważ ta wojna będzie trwała z powodu przywódców światowych, którzy nadal myślą tylko o władzy i o sprawach tego świata. Dzieci moje, oczyszczenie będzie próbą dla wszystkich, bądźcie po stronie Boga. Módl się za przywódcę politycznego, który ucierpi w wyniku zamachu. Módlcie się za Kościół i za wszystkich niewinnych, którzy swoją krwią zmyją grzechy ludzkości. Módlcie się za rząd włoski, ponieważ jest w nim podżegacz wojenny. Módlcie się za Francję. Módlcie się, bo przyczyną tego wszystkiego jest przewrotna ludzkość. Teraz ja was błogosławię w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 3)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach i że uklęknęliście do modlitwy. Moje dzieci, pomimo tego wszystkiego, co widzicie wokół siebie, często nie przyjmujecie tego do wiadomości i myślicie, że wojna nie jest wasza, bo nie ma jej w domu, ale niestety tak nie będzie, to jest powód mojego ciągłego wzywania do nawrócenia. Dzieci moje, błagam was, przyjmijcie z miłością wszystkie moje orędzia. Będę was prowadziła, abyście zbliżali się do Boga, zamiast się gubić i błądzić. Dzieci moje, droga, którą obraliście, nie jest właściwa, nadejdzie coś jeszcze, a jednak nadal żyjecie swoim małym życiem, nie myśląc o tym, że wokół was diabeł niszczy wszystko, a wy nie dbacie o swoje dusze. Czy wierzysz, że o to właśnie chodzi w życiu? Czy nie wierzysz, że wieczne potępienie istnieje, jeśli pozwolisz, by prowadził cię diabeł? Dzieci moje, módlcie się za Bliski Wschód, nadeszło Ostrzeżenie. Bądźcie gotowi, dzieci, błagam was. Nie opuszczajcie spowiedzi i Eucharystii, bo musicie wynagrodzić za to, że nie będziecie już mogli z nich korzystać. Podajcie mi wasze ręce, a ja was poprowadzę tam, gdzie jest radość i czysta miłość. Pozostawiam wam pokój, zabierzcie go do waszych rodzin. Błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen. Matka Boża mówi, że obdarzy łaskami także obecnych, a w szczególności młodą dziewczynę, która ma nowotwór; niektórzy modlili się dziś w tej intencji.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 8)), "Droga córko, dziękuję ci, że przyjęłaś w swoim sercu moje wezwanie. Córko, błagam cię, abyś poprosiła wszystkie moje dzieci o usunięcie pychy, która nadal szaleje w ich sercach. Dosyć już ciemnoty, która odpędza braci, dosyć już arogancji, uklęknijcie przed Panem. Nawracajcie się, moje dzieci, jeszcze nie jest za późno, nawracajcie się do końca i nie dajcie się kusić diabłu, bo jego przebiegłość jest przenikliwa. Módlcie się za świat, bo nie będzie już pokoju, czyńcie pokutę, drogie dzieci, nie czas już żyć dla rzeczy tego świata, ale podnieście oczy ku niebu i bądźcie bardziej duchowi, wasze wywyższenie przyniesie wam same korzyści. Ziemia składa się obecnie z przewrotnej ludzkości, która jest głucha na moje wezwania jako Matki. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 10)), "Ja, wasz Ojciec, jestem tutaj, aby przypomnieć wam, że kocham was wszystkich. Nie bójcie się, mój Syn był pierwszym człowiekiem, którego ojcowie Kościoła schwytali i nazwali heretykiem. Czego więc się obawiacie? Nie bójcie się. On zwyciężył śmierć i zawsze będzie z wami. Dlaczego nie potraficie tego zrozumieć? Ponieważ ludzkość nie rozumie, że kocham was wszystkich i jako Ojciec czuję się w obowiązku być u waszego boku, chronić was. Jako Ojciec będę was bronił przed wszystkimi, którzy będą was nazywać heretykami. Nie martwcie się. Zobaczcie teraz, jak wszystko się rozpadnie. Nawet Twój schron będzie gotowy na ten czas. Przynaglam was do wszystkiego, abyście, gdy Najświętsza Maryja Panna powie wam, że nadszedł czas odejścia, udali się pod Błękitny Krzyż (błogosławione wzgórze Trevignano Romano) i tam nigdy nie zostaniecie dotknięci, ponieważ sam uświęciłem to miejsce. Nie martwcie się, porzućcie ludzkie sprawy i miejcie wiarę, wszystko spełni się zgodnie z moim planem. Aniołowie, w miejscu pobłogosławionym przeze mnie, będą was chronić i uczynią was bezpiecznymi, sprawią, że będziecie niewidzialni, a ja sprawię, że niczego wam nie zabraknie. Jestem dobrym Ojcem, ale jestem też Ojcem sprawiedliwym. Kocham was, moje dzieci, tak bardzo was kocham, nie bójcie się, nie lękajcie się, wszystko, co będziecie mieli, będzie tylko dzięki mojej łasce. Opuszczam was teraz. Wasz Ojciec, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 12)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, niebo ogarnęła ciemność, która pochłonie wiele dusz, także tych należących do Kościoła. Przyjmujcie swoich braci bez lęku, bo i was może to spotkać.  Dzieci moje, aby was pocieszyć, zapowiadam wam, że po zrujnowanej ziemi ujrzycie zstępujące nowe Jeruzalem i będzie ono jak raj. Świat się odrodzi i pokłoni się przed Bogiem, nastąpi nawrócenie na całym świecie, w tym w Chinach, będziecie mieli wiele lat pokoju, harmonii i wielkiej miłości między braćmi, nie bójcie się, ponieważ to oczyszczenie będzie konieczne, aby odrodzić się na nowo. Ręka i ochrona na tym błogosławionym wzgórzu (wzgórze Trevignano Romano) będą zawsze obecne i posłużą do nawrócenia wielu ludzi. Pewnego dnia ujrzycie tu aniołów, objawiających się z koroną Zbawiciela na rękach i przy dźwięku lir, śpiewających Panu pieśni pochwalne i hymny. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 15)), "Moje drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach i że uklęknęliście do modlitwy. Umiłowane dzieci, jakże wielki ból czuję w sercu, gdy patrzę na was, chodzicie po ziemi podkopanej nie tylko przez bomby, ale także przez zło. Mimo moich niezliczonych wezwań wciąż wątpicie, a przecież Ja, wasza Matka, zawsze ostrzegałam, co będzie, jeśli nie nastąpi w was prawdziwe nawrócenie; posłuchajcie mnie! Dzieci moje, jeszcze raz proszę was: powierzcie Bogu wasze życie i wasze dni, miejcie wiarę w Niego, Sprawiedliwego, który wszystko może. Ludzie nie są gotowi na to, co przyjdzie nagle, wierzą tylko głosom świata, a nie świętym słowom Matki, która płacze i boleje nad wszystkimi. Chcę was ocalić, czy rozumiecie to ostrzeżenie? Głód będzie postępował bez litości, pomagajcie sobie nawzajem wśród braci. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 19)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach i zgięliście kolana w modlitwie. Moje drogie dzieci, bądźcie zawsze gotowi na to, co się nagle wydarzy, Europa zostanie najechana, módlcie się za Zachód, módlcie się za Papieża, bo to jest godzina jego wielkiego smutku i troski. Dzieci moje, pamiętajcie, że modlitwa jest jedynym lekarstwem dla waszej duszy i waszego ciała, otwórzcie wasze serca na Łaskę, bo tylko w ten sposób będziecie mogli mieć pokój w waszych sercach, pomimo mrocznych czasów. Drogie dzieci, nie bójcie się, ale weźcie mnie za rękę, a ja zaprowadzę was do mojego Syna Jezusa. Moje dzieci, prześladowania będą wielkie, dlatego zawsze bądźcie pełni wiary, nawet gdy wszystko wydaje się stracone, powierzcie się Bogu, On będzie blisko was każdego dnia, aż do końca. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 24)), "Droga córko, dziękuję ci, że wysłuchałaś w swoim sercu mojego wołania. Ludzie nadal nie rozumieją powodu mojego przyjścia, chcę ocalić tę ludzkość, której mówię: przestańcie rozbudzać swoją ciekawość, czytając moje orędzia, ale żyjcie nimi. Widzę, że moje dzieci się gubią i chcę im wskazać drogę. Przychodzę jako kochająca Matka, aby ukazać światło pośród ciemności. Dzięki waszym modlitwom i prawdziwej wierze możecie uniknąć trzeciej wojny światowej, ale nadal jesteście zamknięci w swoich skorupach i nie widzicie dalej. Nadchodzą katastrofy, lecz nie porzucajcie sakramentów. Pomimo moich łez, wasze serca są twarde i nie wpuszczacie światła, proszę, aby wasza wiara była nie tylko słowami, ale i czynami, macie najpotężniejszą broń, modlitwę Różańca Świętego, módlcie się. Z czasem wiara chrześcijańska przestanie być wyznawana i będziecie zmuszeni do ukrywania się, bądźcie na to przygotowani, komunizm rozwija się bardzo szybko. Wszystko to się spełni i będzie karą za herezje i bluźnierstwa, które do tej pory były popełniane. Teraz, moja córko, zostawiam cię z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 25)), "Moja córko, dziękuję ci, że przyjęłaś w swoim sercu moje wezwanie. Córko, tego dnia, kiedy nuciłam pieśni pochwalne dla Boga i prosiłam o pokój dla całego świata, przyszedł cudowny anioł i rozświetlił pomieszczenie, a jego słodki głos oznajmił mi, że będę miała syna za sprawą Ducha Świętego, pomimo mojego dziewictwa, i opowiedział mi o wielkości Jezusa. Całe życie modliłam się o pokój, tak jak i dzisiaj, ale ludzie mnie nie słuchali i nie słuchają nawet teraz. Moja córko, dzisiaj wielu wierzy, że ta konsekracja może być ważna, ale rozpoczęła się wojna, mój Syn jest zagniewany, bo gdyby została wypowiedziana na czas, pokój zstąpiłby na tę ludzkość, ale tak się nie stanie, bo nikt nie może obrażać Boga. Moja córko, wszystko zostanie nieco złagodzone przez modlitwy odmawiane z prawdziwą wiarą. Wkrótce przeżyjecie mroczne chwile z powodów, o których właśnie wam powiedziałem, proszę, powróćcie do Boga. Błogosławię was w imię Trójcy Przenajświętszej.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 3) & (dataset["day"] == 26)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach i że uklękneliście do modlitwy. Dzieci moje, już o tym mówiłam, proszę was: otwórzcie wasze serca na łaskę, abyście byli godni tego wszystkiego, co Bóg ma dla was w zanadrzu. Dzieci moje, módlcie się o pokój, ale przede wszystkim o pokój wewnętrzny; nie zatracajcie się w rzeczach ulotnych, ale myślcie bardziej o swojej duszy. Ponownie proszę was: nawracajcie się, patrzcie na ciemne czasy, nie czekajcie na Ostateczny Sąd Boży, ale bądźcie świadomi wszystkiego, co nadejdzie, jeśli nie jesteście gotowi, nie będziecie w stanie stawić czoła ostrzeżeniu. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])


dataset = dataset[['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en']]

dataset_ready = pd.read_csv("march_2022.csv")


dataset = dataset.merge(dataset_ready, how="left", on=['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en'])

dataset_ok = dataset[~dataset["text_pt"].isnull()]
dataset_translate = dataset[dataset["text_pt"].isnull()]



dataset_translate["text_es"] = dataset_translate["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset_translate["text_fr"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset_translate["text_zh"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'zh'))
dataset_translate["text_de"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'de'))
dataset_translate["text_pt"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'pt'))


dataset = pd.concat([dataset_ok, dataset_translate])

dataset = dataset.sort_values(by="day")
dataset = dataset[:10]


dataset.to_csv("march_2022.csv", encoding="utf-8", index=False)









