# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator
import goslate
gs = goslate.Goslate()

#dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "", dataset["text_it"])



dataset = pd.read_csv("april_cleaned.csv", encoding="utf-8")




# ITALIAN
dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 3)), "Figli amati, grazie per aver risposto alla mia chiamata nel vostro cuore.  Figli miei, grazie per aver piegato le vostre ginocchia nella preghiera. Figlia, guarda il mio cuore sanguinate, attorniato da una corona di spine. Il mio cuore sanguina perché non avete ancora compreso cosa sarà la giustizia di Dio, sarà peggio del giorno del diluvio universale. Pregate figli, convertite il vostro cuore, cambiate le vostre vite per non farvi trovare impreparati. Figli miei, a breve un forte terremoto sarà su tutta la terra per risvegliare le vostre coscienze, non siate addormentati ma vegliate. Figli miei, tutto è malato, la Chiesa verrà giudicata perché è diventata solamente un’istituzione politica e non è più affidata a Dio. Pregate per i pastori che si sono perduti e pregate per la Francia. Figlia mia, devi dire di fare scorte di cibo e di acqua per sopperire ai momenti bui. Figli miei, ora vi benedico nel nome della Santissima Trinità, Padre, Figlio e Spirito Santo, amen. La Madonna oggi era gioiosa perché ha visto così tante persone unite nella preghiera, ma era anche triste e teneva tra le sue mani un cuore sanguinante con intorno una corona di spine.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 5)), "Figlia mia, grazie per aver risposto alla mia chiamata nel tuo cuore. Figlia, questa umanità, invece di pregare e affidarsi a Dio, cerca i posti dove rifugiarsi per salvare la propria vita, ma ancora vi dico: non ci sarà un posto, anche se il più nascosto dinanzi al giudizio di Dio. Pregate il mio Cuore Immacolato e quello di mio Figlio Gesù, saranno i rifugi più sicuri, abbiate fede in Dio e pensate di più alla salvezza della vostra anima. Ascoltatemi con amore e camminate sul percorso che Io vi ho indicato nel vostro cuore, allora garantirete la realizzazione del Trionfo del mio Cuore immacolato e voi ne sarete testimoni. Consacratevi a me, ed Io vi proteggerò sotto il mio Manto Benedetto. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 8)), "Fratelli miei, grazie per essere qui sotto la mia croce. Fratelli, oggi vi ho fatto la grazia della pace nel cuore e nell’anima, ma solo una persona tra di voi testimonierà la mia presenza viva in questo luogo. Fratelli miei, mettete tutto nelle mie piaghe, soprattutto le vostre sofferenze, affinché Io possa darvi la mia grazia e misericordia. Fratelli, pregate per la guerra e per l’umanità che sta subendo tante atrocità. Fratelli miei, riconoscetemi come vostro Re, presto sarò con voi con tutto il mio amore. Ora vi benedico, passandovi accanto, nel nome del Padre, nel mio Nome e dello Spirito Santo.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 12)), "Io sono la Vergine Immacolata, la sposa dello Spirito Santo, l’umile serva di Dio, la Madre di Gesù, il quale fu tradito, deriso e umiliato. Ancora oggi quella spada trafigge il mio cuore. Figli, siete davanti ad un bivio, fate la scelta giusta, mio Figlio vi aspetta. Io proteggerò i miei figli fedeli e umili, che si sono contraddistinti per il coraggio e l’amore. Figli miei, pentitevi, riconoscete il vostro Dio come unico Dio e Salvatore e Lui per la Sua grande misericordia vi perdonerà. Ora ti benedico figlia mia prediletta e grazie per avermi accolta nel tuo cuore, Padre, Figlio e Spirito Santo.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 16)), "Cara figlia, grazie per aver ascoltato la mia chiamata nel tuo cuore. Io sono la Madre Addolorata per la morte di mio Figlio, il quale ancora oggi viene crocifisso dagli uomini e dai falsi pastori, Consolate il mio cuore di Madre, ho visto il mio unico Figlio morire crocifisso, ed Io con Lui, e ancora un secondo dolore quando fu deposto nel sepolcro, chiuso con un sasso e mi sentii sola, eppure ricordo ancora quando sulla croce disse: “Donna, ecco tuo Figlio” e lì divenni Madre di tutti voi, ho serbato il dolore nel mio cuore e nel silenzio. Ora figli miei, consolatemi con le preghiere, così come Io consolo voi quando mi invocate. Ora vi lascio la mia Materna benedizione nel nome del Padre del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 19)), "Figlia mia, grazie per aver risposto alla mia chiamata e per aver piegato le ginocchia nella preghiera. Figlia, la Resurrezione del mio Gesù dovrà essere la Resurrezione di tutti voi, cambiate le vostre vite, cercate le cose del cielo, tenetevi pronti perché ai miei figli più fedeli tanti saranno i doni che riceveranno. Io vedo la rinascita di alcuni di voi e questo mi conforta. Mio Figlio sarà visto da tutti, credenti e non credenti, coloro che avranno creduto avranno grandi ricompense. Figlia mia, i malvagi sono già pronti, attendono un comando, Roma sarà colpita, i miei fedeli saranno perseguitati, ma Io vi dico: non abbiate paura, il demonio ha uno scopo preciso distruggere tutto ciò che rappresenta la casa di Dio, ma gli inferi non prevarranno. Continuate nella preghiera assidua! Figli, le vostre preghiere fatte con il cuore sono arrivate e molto verrà mitigato ma ciò che è scritto avverrà, non dimenticate le profezie, la pestilenza e la guerra raggiungerà l’Europa. La terra è pronta per il grande terremoto, ma ricordate che io vi amo e vi proteggerò insieme ai miei angeli. Ora vi lascio con la mia benedizione materna nome del Padre e del Figlio e dello Spirito Santo. Amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, oggi è l’anniversario del mio incontro con la mia prescelta ed Io ringrazio lei e il suo sposo di aver donato sempre tempo prezioso, al fine di portare avanti questa grande opera di Grazia. Figli miei, ringrazio anche voi, che avete supportato tutto questo con la vostra fede, credendo nella mia presenza e accogliendo i segni inviati dal cielo e per coloro che hanno aperto il cuore, nulla mancherà, le grazie saranno tante, anche le più piccole, di cui a volte non vi accorgete. Figli, bambini miei, Io vi ho chiamati uno per uno, per essere testimoni coraggiosi e sono qui, ancora per chiedervi di aiutarmi a portare anime a Dio. La preghiera per l’evento di oggi, libererà tante anime. Arriverà la pestilenza, pregate per la terra di mio Figlio. Ora vi benedico nel nome della Santissima Trinità, Padre, Figlio e Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 23)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli, quanto amore sento per voi!  Figli amati, domani è la giornata della Divina Misericordia, presto vedrete Gesù con i suoi raggi illuminare il mondo, accoglietelo in tutta la sua grazia e inginocchiatevi. Figli, Io, vostra madre chiedo solo una cosa, convertitevi, urlatelo al mondo prima che sia troppo tardi. Figli, non ridicolizzate le profezie respingendole, ma accoglietele, serviranno a mettervi in guardia su ciò che potrà accadere, per questo vi chiedo di pregare tanto. Figli miei, Dio purificherà questa terra dai nemici e dal fetore e raccoglierà tutti i frutti migliori, proteggendo coloro che provano grande amore per Lui. Ora vi lascio, con la mia benedizione materna, nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 26)), "Figli miei, perché non avete molta cura della Mia Opera? Io ho dato un luogo per essere seguiti e benedetti, vi ho detto che un giorno quel luogo sarà come l’Eden e voi guardate e vi occupate solo del vostro orticello. Fratelli, agite come i miei Apostoli, quando avevo chiesto di vegliare, si sono addormentati, non siate incuranti per le opere di Dio e rispettate con Amore il luogo benedetto dal Padre mio, dove Io poso i miei piedi e dove la mia Santissima Madre, vi istruisce per i tempi che arriveranno. Un giorno sarà il vostro rifugio, non dimenticatelo. Pregate per il Papa e per la mia Chiesa, perché stanno vacillando, la terra continuerà a tremare. Ora vi lascio con la mia benedizione nel nome del Padre, del mio Santissimo nome e dello Spirito Santo.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 30)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli cari, conosco i vostri cuori e vi dico: venite qui, in questo luogo Benedetto, dove Io vi prenderò le mani per rialzarvi quando cadrete, asciugherò le vostre lacrime quando sarete afflitti e vi consolerò quando sarete disperati. Io sono qui, vostra tenerissima Madre per aiutarvi e sono ancora qui come maestra per il vostro cammino. Seguite i comandamenti che vi sono stati lasciati e cibatevi dei sacramenti. Figli miei, la guerra avanzerà. Pregate perché la siccità sarà grande a causa dell’acqua che mancherà. Pregate per i sacerdoti e per le anime che si stanno perdendo, perché purtroppo il male è entrato nella casa di Dio. Ora vi lascio con la mia benedizione Materna nel nome del Padre, del figlio e dello Spirito Santo, amen.", dataset["text_it"])
#dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 1)), "", dataset["text_it"])
#dataset["text_it"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 1)), "", dataset["text_it"])

# ENGLISH
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 3)), "Beloved children, thank you for responding to My call in your hearts. My children, thank you for kneeling in prayer. Daughter, look at my bleeding heart, surrounded by a crown of thorns. My heart bleeds because you have not yet understood what God's Justice will be, it will be worse than the day of the Great Flood. Pray children, convert your hearts, change your lives so that you are not found unprepared. My children, in a short time a strong earthquake will be on the whole earth to awaken your consciences, do not be asleep but keep watch. My children, everything is sick, the Church will be judged because it has become only a political institution and is no longer entrusted to God. Pray for the pastors who are lost and pray for France. My daughter, you must say to stock up on food and water to make up for the dark times. My children, I now bless you in the name of the Most Holy Trinity, Father and the Son and the Holy Spirit, Amen. Our Lady was joyful today because she saw so many people united in prayer, but she was also sad and held in her hands a bleeding heart with a crown of thorns around it.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 5)), "My daughter, thank you for having responded to My call in your heart. Daughter, this humanity, instead of praying and entrusting itself to God, seeks places of refuge to save its life, but still I tell you: there will be no place, even the most hidden before God's Judgment. Pray to my Immaculate Heart and that of my Son Jesus, they will be the safest shelters, have faith in God and think more about the salvation of your soul. Listen to me with love and walk on the path that I have indicated to you in your heart, then you will guarantee the realization of the Triumph of my Immaculate Heart and you will be its witnesses. Consecrate yourselves to Me, and I will protect you under My Blessed Mantle. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 8)), "My brothers, thank you for being here under my Cross. My brothers, today I have given you the grace of peace in hearts and souls, but only one person among you will witness my living presence in this place. My brothers, put everything in my wounds, especially your sufferings, so that I may give you my grace and mercy. My brothers, pray for the war and for humanity which is suffering so many atrocities. My brothers, recognize Me as your King, soon I will be with you with all My love. Now I bless you, passing by your side, in the name of the Father, in my Name and in the name of the Holy Spirit.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 12)), "I am the Immaculate Virgin, the spouse of the Holy Spirit, the humble servant of God, the Mother of Jesus, who was betrayed, mocked and humiliated. Even today that sword pierces my heart. Children, you are at a crossroads, make the right choice, my Son is waiting for you. I will protect my faithful and humble children, who have distinguished themselves by their courage and love. My children, repent, acknowledge your God as the only God and Savior and He by His great Mercy will forgive you. Now I bless you my beloved daughter and thank you for welcoming me into your heart, in the name of the Father and the Son and the Holy Spirit.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 16)), "Dear daughter, thank you for listening to my call in your heart. I am the Mother of Sorrows over the death of my Son, who is still being crucified today by men and false shepherds, Console my Mother's heart, I saw my only Son die crucified, and I with Him, and again a second sorrow when He was laid in the tomb, closed with a stone and I felt lonely, yet I still remember when on the cross He said: 'Woman, here is your Son' and there I became the Mother of all of you, I kept the sorrow in my heart and in silence. Now my children, console me with your prayers, just as I console you when you invoke me. Now I leave you my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 19)), "My daughter, thank you for responding to my call and for bending your knees in prayer. Daughter, the Resurrection of my Jesus must be the Resurrection of all of you, change your lives, seek the things of Heaven, be ready because my most faithful children will receive many gifts. I see the rebirth of some of you and this comforts me. My Son will be seen by all, believers and non-believers, those who have believed will have great rewards. My daughter, the wicked are ready, they are waiting for a command, Rome will be struck, my faithful will be persecuted, but I say to you: do not be afraid, the devil has a precise aim to destroy everything that represents the house of God, but the underworld will not prevail. Continue in constant prayer! Children, your prayers made with the heart have come and much will be mitigated but what is written will come to pass, do not forget the prophecies, pestilence and war will reach Europe. The earth is ready for the great earthquake, but remember that I love you and will protect you together with my angels. Now I leave you with my motherly blessing in the name of the Father and of the Son and of the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21)), "My children, thank you for having responded to my call in your hearts. My children, today is the anniversary of my meeting with my chosen one and I thank her and her spouse for having always given precious time in order to carry out this great work of Grace. My children, I also thank you, who have supported all this with your faith, believing in my presence and accepting the signs sent from Heaven and for those who have opened their hearts, nothing will be lacking, the graces will be many, even the smallest, which sometimes you do not realize. My children, my children, I have called you one by one to be courageous witnesses and I am here again to ask you to help me bring souls to God. Prayer for today's event will free many souls. The plague will come, pray for the land of my Son. I now bless you in the name of the Holy Trinity, Father and the Son and Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 23)), "Dear children, thank you for having responded to my call in your hearts. My children, how much love I feel for you! Beloved children, tomorrow is the day of Divine Mercy, soon you will see Jesus with His rays illuminating the world, welcome Him in all His grace and kneel down. Children, I, your mother, ask only one thing, convert, cry out to the world before it is too late. My children, do not ridicule prophecies by rejecting them, but welcome them, they will serve to warn you of what may happen, for this I ask you to pray hard. My children, God will purify this land of enemies and stench and will reap all the best fruits, protecting those who have great love for Him. Now I leave you, with my motherly blessing, in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 26)), "My children, why do you not take great care of My Work? I have given you a place to be followed and blessed, I have told you that one day that place will be like Eden and you only watch and take care of your little garden. Brothers, you act as My Apostles did, when I asked them to keep watch, they fell asleep, do not be careless about the works of God and respect with Love the place blessed by My Father, where I lay My feet and where My Most Holy Mother instructs you for the times to come. One day it will be your refuge, do not forget it. Pray for the Pope and for my Church, for they are faltering, the earth will continue to shake. Now I leave you with my blessing in the name of the Father, my Most Holy Name and the Holy Spirit.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 30)), "My children, thank you for having responded to My call in your hearts. Dear children, I know your hearts and I say to you: come here, to this blessed place, where I will take your hands to lift you up when you fall, I will dry your tears when you are afflicted and I will console you when you are in despair. I am here, your most tender Mother to help you and I am still here as your teacher on your path. Follow the commandments left to you and feed on the sacraments. My children, the war will advance. Pray because the drought will be great because of the lack of water. Pray for the priests and for the souls that are being lost, because unfortunately evil has entered the house of God. Now I leave you with my Motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
#dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 1)), "", dataset["text_en"])
#dataset["text_en"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 1)), "", dataset["text_en"])

# POLISH
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 3)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, dziękuję wam, że uklęknęliście do modlitwy. Córko, spójrz na moje krwawiące serce, otoczone koroną cierniową. Moje serce krwawi, ponieważ nie zrozumieliście jeszcze, jaka będzie Sprawiedliwość Boża, będzie ona gorsza niż dzień Wielkiego Potopu. Módlcie się dzieci, nawróćcie wasze serca, zmieńcie wasze życie, abyście nie zostali uznani za nieprzygotowanych. Dzieci moje, wkrótce na całej ziemi będzie odczuwalne silne trzęsienie ziemi, które obudzi wasze sumienia; nie zasypiajcie, lecz czuwajcie. Dzieci moje, wszystko jest chore, Kościół zostanie osądzony, ponieważ stał się jedynie instytucją polityczną i nie jest już powierzony Bogu. Módlcie się za zagubionych pasterzy i za Francję. Moja córko, musisz im powiedzieć, żeby zrobili zapasy żywności i wody, aby zabezpieczyć się na czarną godzinę. Dzieci moje, błogosławię was teraz w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen. Matka Boża była dziś radosna, bo widziała tak wielu ludzi zjednoczonych na modlitwie, ale była też smutna i trzymała w rękach krwawiące serce, wokół którego była korona cierniowa.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 5)), "Moja córko, dziękuję ci, że odpowiedziałaś na moje wezwanie w swoim sercu. Córko, ta ludzkość, zamiast modlić się i powierzać się Bogu, szuka miejsc schronienia, aby ocalić swoje życie, ale mimo to mówię wam: przed Sądem Bożym nie będzie schronienia, nawet najbardziej ukrytego. Módlcie się do mojego Niepokalanego Serca i do Serca mojego Syna Jezusa, one będą najbezpieczniejszym schronieniem, miejcie wiarę w Boga i myślcie raczej o zbawieniu waszej duszy. Słuchajcie mnie z miłością i idźcie drogą, którą wam wskazałam w waszym sercu, a wtedy zagwarantujecie realizację Tryumfu mojego Niepokalanego Serca i będziecie jego świadkami. Poświęćcie się Mi, a Ja będę was chroniła pod Moim Najświętszym Płaszczem. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 8)), "Bracia moi, dziękuję wam, że jesteście tutaj pod moim Krzyżem. Bracia, dzisiaj dałem wam łaskę pokoju w sercach i duszach, ale tylko jedna osoba spośród was będzie świadkiem mojej żywej obecności w tym miejscu. Bracia moi, włóżcie wszystko w moje rany, a zwłaszcza w wasze cierpienia, abym mógł was obdarzyć moją łaską i miłosierdziem. Bracia moi, módlcie się za wojnę i za ludzkość, która doświadcza tak wielu okrucieństw. Bracia moi, uznajcie mnie za waszego Króla; wkrótce będę z wami z całą moją miłością. Teraz błogosławię was, przechodząc obok was, w imię Ojca, w moje Imię i w imię Ducha Świętego.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 12)), "Jestem Niepokalaną Dziewicą, oblubienicą Ducha Świętego, pokorną służebnicą Bożą, Matką Jezusa, który został zdradzony, wyszydzony i upokorzony. Jeszcze dziś ten miecz przeszywa moje serce. Moje dzieci, jesteście na rozdrożu, dokonajcie właściwego wyboru, mój Syn czeka na was. Będę strzegła moje wierne i pokorne dzieci, które odznaczyły się odwagą i miłością. Dzieci moje, nawróćcie się, uznajcie waszego Boga za jedynego Boga i Zbawiciela, a On przez swoje wielkie Miłosierdzie przebaczy wam. Teraz błogosławię cię, moja umiłowana córko, i dziękuję ci, że przyjąłeś mnie do swojego serca, w imię Ojca i Syna i Ducha Świętego.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 16)), "Droga córko, dziękuję ci, że wsłuchałaś się w moje wołanie w twoim sercu. Jestem Matką Bolesną z powodu śmierci mojego Syna, który jeszcze dzisiaj jest krzyżowany przez ludzi i fałszywych pasterzy. Pocieszając moje matczyne serce, widziałam, jak mój jedyny Syn umiera na krzyżu, a ja razem z Nim, i poczułam drugi smutek, kiedy został złożony w grobie, zamkniętym kamieniem, i poczułam się samotna, ale wciąż pamiętam, jak na krzyżu powiedział: 'Niewiasto, oto syn Twój' i tam stałam się Matką was wszystkich, zachowałam smutek w moim sercu i w ciszy. A teraz, moje dzieci, pocieszajcie mnie waszymi modlitwami, tak jak Ja was pocieszam, gdy mnie wzywacie. Teraz zostawiam wam moje matczyne błogosławieństwo w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 19)), "Córko moja, dziękuję ci, że odpowiedziałaś na moje wezwanie i że uklęknęłaś do modlitwy. Córko, Zmartwychwstanie mojego Jezusa musi być Zmartwychwstaniem was wszystkich, zmieńcie swoje życie, szukajcie tego, co niebieskie, bądźcie gotowi, bo moje najwierniejsze dzieci otrzymają wiele darów. Widzę odrodzenie niektórych z was i to mnie pociesza. Mój Syn będzie widziany przez wszystkich, wierzących i niewierzących; ci, którzy uwierzyli, otrzymają wielką nagrodę. Moja córko, niegodziwi są już gotowi, czekają na rozkaz, Rzym zostanie uderzony, moi wierni będą prześladowani, ale Ja wam mówię: nie bójcie się, diabeł ma ściśle określony cel, aby zniszczyć wszystko, co stanowi Dom Boży, ale otchłań nie zwycięży. Trwajcie na wytrwałej modlitwie! Moje dzieci, wasze modlitwy zanoszone z serca dotarły i dużo zostanie złagodzone, ale to, co jest napisane, spełni się, nie zapominajcie o proroctwach, zaraza i wojna dotrą do Europy. Ziemia jest gotowa na wielkie trzęsienie ziemi, ale pamiętajcie, że was kocham i będę was chronić wraz z moimi aniołami. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 21)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, dziś jest rocznica mojego spotkania z moją wybraną i dziękuję jej i jej małżonkowi za to, że zawsze poświęcali swój cenny czas, aby realizować to wielkie dzieło Łaski. Dzieci moje, dziękuję również wam, którzy wspieraliście to wszystko swoją wiarą, wierząc w moją obecność i przyjmując znaki wysyłane z nieba, a tym, którzy otworzyli swoje serca, niczego nie zabraknie; będzie wiele łask, nawet tych najmniejszych, z których czasem nie zdajecie sobie sprawy. Moje dzieci, moje dzieci, wzywałem was wszystkich, abyście byli odważnymi świadkami, i jestem tu ponownie, aby prosić was o pomoc w przyprowadzeniu dusz do Boga. Modlitwa w intencji dzisiejszego wydarzenia uwolni wiele dusz. Nadejdzie zaraza, módlcie się za ziemię mojego Syna. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 23)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, jak wielką miłość czuję do was!  Umiłowane dzieci, jutro jest dzień Miłosierdzia Bożego, wkrótce ujrzycie Jezusa z Jego promieniami rozświetlającymi świat, przyjmijcie Go w całej Jego łasce i uklęknijcie. Dzieci, ja, wasza matka, proszę tylko o jedno, nawróćcie się, wołajcie do świata, zanim będzie za późno. Dzieci moje, nie wyśmiewajcie się z proroctw, odrzucając je, ale je przyjmijcie, one posłużą wam do ostrzeżenia przed tym, co może się wydarzyć, dlatego tak bardzo proszę was o modlitwę. Moje dzieci, Bóg oczyści tę ziemię z wrogów i smrodu i zbierze wszystkie najlepsze owoce, chroniąc tych, którzy mają wielką miłość do Niego. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 26)), "Dzieci moje, dlaczego nie troszczycie się o moje dzieło? Dałem wam miejsce, w którym będziecie czcić i błogosławić, powiedziałem wam, że pewnego dnia to miejsce będzie jak Eden, a wy tylko patrzycie na swój mały ogródek i dbacie o niego. Bracia, postępujcie tak, jak czynili to Moi Apostołowie, kiedy prosiłem ich, aby czuwali, a oni zasnęli, nie bądźcie obojętni na dzieła Boże i z miłością szanujcie miejsce pobłogosławione przez Mojego Ojca, gdzie kładę Moje stopy i gdzie Moja Najświętsza Matka poucza was na nadchodzące czasy. Pewnego dnia będzie to twoje schronienie, nie zapominaj o tym. Módlcie się za papieża i za mój Kościół, bo oni słabną, a ziemia nadal będzie drżeć. Teraz zostawiam was z moim błogosławieństwem w imię Ojca, Mojego Najświętszego Imienia i Ducha Świętego.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 30)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Drogie dzieci, znam wasze serca i mówię wam: przyjdźcie tutaj, do tego błogosławionego miejsca, gdzie wezmę wasze ręce, aby was podnieść, gdy upadniecie, osuszę wasze łzy, gdy będziecie utrudzeni, i pocieszę was, gdy będziecie zrozpaczeni. Jestem tutaj, wasza najczulsza Matka, aby wam pomóc i nadal jestem tutaj jako wasz nauczyciel na waszej drodze. Postępujcie zgodnie z przykazaniami, które zostały wam pozostawione, i karmcie się sakramentami. Moje dzieci, wojna będzie postępować. Módlcie się, ponieważ susza będzie wielka z powodu braku wody. Módlcie się za kapłanów i za dusze, które są gubione, bo niestety zło weszło do domu Bożego. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
#dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 1)), "", dataset["text_pl"])
#dataset["text_pl"] = np.where(((dataset["month"] == 4) & (dataset["day"] == 1)), "", dataset["text_pl"])

dataset = dataset[['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en']]

dataset_ready = pd.read_csv("april_2022.csv")


dataset = dataset.merge(dataset_ready, how="left", on=['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en'])

dataset_ok = dataset[~dataset["text_pt"].isnull()]
dataset_translate = dataset[dataset["text_pt"].isnull()]



dataset_translate["text_es"] = dataset_translate["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset_translate["text_fr"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset_translate["text_zh"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'zh'))
dataset_translate["text_de"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'de'))
dataset_translate["text_pt"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'pt'))


dataset = pd.concat([dataset_ok, dataset_translate])

dataset = dataset.sort_values(by="day")


dataset.to_csv("april_2022.csv", encoding="utf-8", index=False)









