# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator
import goslate
gs = goslate.Goslate()

#dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "", dataset["text_it"])



dataset = pd.read_csv("may_cleaned.csv", encoding="utf-8")




# ITALIAN
dataset["text_it"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 3)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli amati, quanta tenerezza sente il mio cuore di Madre, quando vedo i miei bambini che piegano le ginocchia con grande fede. Figli, presto assisterete all’avvertimento, all’incontro con il mio Gesù che tanto vi ama, attendete questo gesto di misericordia, ma non con paura, ma con gioia. Figli amati, confessatevi per trovarvi pronti per quando Lui verrà, vegliate sempre figli, Io vi amo e voglio guidarvi come una Madre, grande sarà la sofferenza per coloro che non vogliono riconoscere Dio. Figli miei, pregate per la Chiesa e soprattutto per i vescovi, cardinali e sacerdoti, affinché abbandonino ogni orgoglio e inizino a proclamare la parola di Dio, affinché non si occupino più di politica, ma come Pietro, siano pescatori di anime. Ora vi do la mia benedizione Materna nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"]) 
dataset["text_it"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 6)),  "Cara figlia, grazie per avermi accolta nel tuo cuore. Non devi mai temere, perché quando tu proclami la Santa Parola, Io sarò con te. La Chiesa, oggi, ha alzato muri tra mio Figlio e la vera dottrina e nonostante la sofferenza che sta causando al Benedetto e Sacratissimo cuore di Gesù, Lui è lì a proteggerla. La Chiesa, invece di cibare i miei figli, del corpo e sangue di Gesù, ha alienato la sua presenza e nonostante questo, Lui è sempre pronto ad offrire il Suo aiuto. Pentitevi! Figlia mia, la massoneria e la loro stravagante forza malvagia, hanno allontanato i rappresentanti della Chiesa dalla vera fede cristiana, insultando il corpo di Gesù, offrendolo in maniera errata e costringendo i miei figli a non inginocchiarsi ed a riceverlo sulle mani, proclamando una grande menzogna. Vi chiedo: tornate alla vera fede e permettetemi di aiutarvi nei momenti tenebrosi che arriveranno. Vi dico: la vera Chiesa rinascerà e sarà più grande e rigogliosa. Ora, vi consiglio di pregare, perché il tempo a disposizione giunge alla fine. Vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen", dataset["text_it"]) 
dataset["text_it"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 10)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Vedo molti di voi preoccupati per i tempi che arriveranno, ma Io sono qui per confortarvi, pensate che tutto il male sarà sconfitto e voi miei soldati combattenti, avrete grazie e misericordia, vedrete con i vostri occhi, toccherete con le vostre mani tutte le grazie che scenderanno. Figli cari, pregate tanto e così insieme a me sarete testimoni della vittoria del mio Cuore Immacolato. Pregate per la Chiesa, pregate per il Giappone e la Cina affinché possano alleviarsi i dolori che causeranno. Figli, guardate il cielo, lì vedrete i segni dei tempi. Ora vi lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 13)), "Cari figli, grazie per essere qui e per aver risposto alla mia chiamata nel vostro cuore. Figli miei, pregate, pregate, pregate, oggi come allora, (apparizione a Fatima) continuo a chiedere preghiere e conversione. Se tutto fosse stato fatto come da me richiesto, avreste vissuto la pace e invece sono state aperte le porte degli inferi e voi piccoli miei, se non vi rafforzate nella fede, camminerete sulla strada della perdizione. Io sono qui, con il cuore infranto, per tutto ciò che state permettendo. Figli miei, guardate la Chiesa, non vuole riconoscermi come Corredentrice, Io sono la Regina del cielo e della terra, Colei che vi porta a mio Figlio Gesù, Io sono Madre Sua e di tutti voi, accettate questa verità. Figli, pregate per i miei figli ucraini, i quali sono stati buttati in due fosse ancora vivi. Figli miei, la terra tremerà sempre più forte, ma voi non temete, perché Io sono qui per proteggervi, non c’è più tempo, siate sempre più spirituali e guardate i segni del cielo e della terra. Ora vi lascio, con la mia benedizione materna, nel nome del Padre, del Figlio e dello Spirito Santo, amen", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 17)), "Figli miei, grazie per essere qui nella preghiera. Figli amati, anche oggi vi ringrazio per aver risposto alla mia chiamata. Il mio cuore è affranto per tutto ciò che accadrà. Vedo molti cuori chiusi, molti dei miei figli che si perdono e non ascoltano la mia amorevole chiamata. Figli miei, vi chiedo di essere testimoni coraggiosi, non c’è più tempo, ascoltate le parole di vostra Madre, fate scorte di acqua, cibo e medicine, tutto sta per finire. Vi prego figli, aiutatemi. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 21)), "Figli miei, grazie per essere qui nella preghiera e per aver risposto alla mia chiamata nel vostro cuore. Figli, state vivendo tempi bui e andando avanti diventeranno tenebre, ma voi guardate sempre la luce. Quante volte Gesù vi ha promesso protezione, vi ha mai deluso? Quante volte siete stati nella difficoltà, eppure non vi ha mai abbandonato.  Figli, bambini miei, non temete mai, qualunque cosa accadrà, pregate, pregate, pregate tanto, coprite la terra con le vostre preghiere, pregate per i sacerdoti che stanno sfidando Dio, pregate per i potenti perché stanno complottando. Figli miei, vogliono togliervi la libertà, ma voi abbiate fede e siate nella verità, solo essa vi renderà liberi. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 24)), "Cari figli miei, grazie per aver risposto alla mia  chiamata nel vostro cuore. Figli, anche quando pensate di essere soli, Io, vostra Madre sono qui. Figli, la guerra e la carestia si faranno sentire sempre più forte, ma la fede in Dio vi proteggerà, non abbiate paura. In questo periodo siate uniti e non siate mezzi di discordia. Figli, pregate per i vescovi ipocriti e perversi, pregate per la Chiesa, che sta sanguinando, così come mio Figlio. Pregate per il Papa. Ora vi lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 28)), "Figli amati, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, solo la preghiera intensa e incessante conforterà il mio benedetto e dolorante cuore e quello di mio Figlio. Figli miei, pregate perché non sapete cosa sta arrivando, la notte buia è molto vicina, accendete nelle vostre case le candele benedette. Figli miei, gli angeli combattono con le spade, ma voi, con il Santo Rosario tra le mani, continuate questa preghiera a me tanto cara. Figli miei, aprite i vostri cuori affinché possa entrare la gioia e la speranza perché Io vengo a prepararvi, non abbiate paura di ciò che vedrete, perché il mio Manto benedetto è su di voi. Innalzate le vostre braccia e Lodate il Signore. Figli amati, ricordatevi sempre il mio infinito amore di Madre per voi. Ora vi benedico nel nome della Santissima Trinità, Padre, Figlio e Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 31)), "Figli e fratelli miei, grazie per aver piegato le ginocchia, sotto la mia croce. Fratelli, cibatevi di ciò che vi ho lasciato, la mia presenza viva, nel corpo e nel sangue. Adorate il Santissimo Sacramento e tante saranno le grazie che riceverete. Figli, approfittate di questi tempi in cui potrete avere il mio corpo liberamente, presto vi inganneranno, dicendo che è solo un ricordo. Io, in persona, vi do questo avvertimento, leggete spesso il Santo Vangelo, tutto questo verrà cancellato e dovrete farlo di nascosto. Io lo dico, questa è verità sacrosanta. Fratelli miei, chiedetemi la consolazione e l’unione tra fratelli, aprite il vostro cuore alla potenza dello Spirito Santo, che farà di voi uomini nuovi. Siate al servizio dei più deboli, siate umili e abbandonate l’orgoglio e la superbia, soprattutto, coloro che leggendo i messaggi miei e di mia Madre, ridicolizzano tutto, ma se solo leggessero, meditando e pregando, Io stesso risponderei nei loro cuori. Ora vi benedico nel nome del Padre, nel Mio Nome e dello Spirito Santo, amen.", dataset["text_it"])
#dataset["text_it"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 1)), "", dataset["text_it"])
#dataset["text_it"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 1)), "", dataset["text_it"])
# ENGLISH
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 3)), "Dear children, thank you for having responded to my call in your hearts. Beloved children, how much tenderness my Mother's heart feels when I see my children kneeling with great faith. My children, soon you will witness the Warning, the meeting with my Jesus who loves you so much; await this gesture of mercy, but not with fear, but with joy. Beloved children, go to confession so that you will be ready for when He comes; always be vigilant, my children, I love you and I want to guide you like a mother. My children, pray for the Church and especially for the bishops, cardinals and priests, so that they may abandon all pride and begin to proclaim the word of God, so that they may no longer deal with politics, but like Peter, be fishers of souls. Now I give you my Motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"]) 
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 6)), "Dear daughter, thank you for welcoming Me into your heart. You need never fear, for when you proclaim the Holy Word, I will be with you. The Church, today, has put up walls between my Son and true doctrine and despite the suffering it is causing to the Blessed and Most Sacred Heart of Jesus, He is there to protect it. The Church, instead of feeding my children, with the body and blood of Jesus, has alienated His presence and despite this, He is always ready to offer His help. Repent! My daughter, Freemasonry and their extravagant evil force, have alienated the representatives of the Church from the true Christian faith, insulting the body of Jesus, offering it in a wrong way and forcing my children not to kneel and receive it on their hands, proclaiming a great lie. I ask you: return to the true faith and allow me to help you in the dark moments that will come. I tell you: the true Church will be reborn and will be greater and more luxuriant. Now, I advise you to pray, for your time is coming to an end. I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"]) 
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 10)), "Dear children, thank you for responding to My call in your hearts. I see many of you worried about the times that will come, but I am here to comfort you, think that all evil will be defeated and you my fighting soldiers, you will have graces and mercy, you will see with your eyes, you will touch with your hands all the graces that will descend. Beloved children, pray much and thus together with me you will witness the victory of my Immaculate Heart. Pray for the Church, pray for Japan and China that they may be relieved of the pains they will cause. My children, look to the heavens, there you will see the signs of the times. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 13)), "Dear children, thank you for being here and for responding to my call in your hearts. My children, pray, pray, pray, today as then, (Fatima apparition) I continue to ask for prayers and conversion. If everything had been done as I requested, you would have experienced peace but instead the gates of hell have been opened and you My little ones, if you do not strengthen yourselves in faith, you will walk on the road to perdition. I am here, with a broken heart, for all that you are allowing. My children, look at the Church, she does not want to recognize Me as Coredemptrix, I am the Queen of Heaven and Earth, She who leads you to My Son Jesus, I am His Mother and of all of you, accept this truth. My children, pray for my Ukrainian children, who were thrown into two pits still alive. My children, the earth will tremble more and more, but you do not fear, for I am here to protect you, there is no more time, be more and more spiritual and watch the signs of heaven and earth. Now I leave you, with my motherly blessing, in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 17)), "My children, thank you for being here in prayer. Beloved children, also today I thank you for responding to my call. My heart is distressed for all that will happen. I see many closed hearts, many of my children being lost and not listening to my loving call. My children, I ask you to be courageous witnesses, there is no more time, listen to your Mother's words, stock up on water, food and medicine, everything is about to end. Please children, help me. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 21)), "My children, thank you for being here in prayer and for answering my call in your hearts. My children, you are experiencing dark times and going forward they will become darkness, but you always look to the light. How many times has Jesus promised you protection, has He ever failed you? How many times have you been in difficulty, yet He has never abandoned you. My children, my children, never be afraid, no matter what happens, pray, pray, pray a lot, cover the earth with your prayers, pray for the priests who are defying God, pray for the powerful because they are plotting. My children, they want to take away your freedom, but you have faith and be in the truth, only it will make you free. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 24)), "My dear children, thank you for responding to My call in your hearts. Children, even when you think you are alone, I, your Mother am here. Children, war and famine will be felt more and more strongly, but faith in God will protect you; do not be afraid. In this time be united and do not be means of discord. Children, pray for the hypocritical and perverse bishops, pray for the Church, which is bleeding, as is my Son. Pray for the Pope. Now I leave you with my motherly blessing in the name of the Father, the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 28)), "Beloved children, thank you for responding to my call in your hearts. My children, only intense and unceasing prayer will comfort my blessed and aching heart and that of my Son. My children, pray because you do not know what is coming, the dark night is very near, light the blessed candles in your homes. My children, the angels fight with swords, but you, with the Holy Rosary in your hands, continue this prayer that is so dear to me. My children, open your hearts so that joy and hope may enter because I am coming to prepare you, do not be afraid of what you will see, for My blessed Mantle is upon you. Lift up your arms and praise the Lord. Beloved children, always remember my infinite Motherly love for you. Now I bless you in the name of the Most Holy Trinity, Father and Son and Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 31)), "My children and brothers, thank you for bending your knees, under my Cross. Brothers, feed on what I have left you, my living presence, in body and blood. Adore the Blessed Sacrament and many will be the graces you will receive. My children, take advantage of these times when you can have my body freely, soon they will deceive you, saying it is only a remembrance. I, myself, give you this warning, read the Holy Gospel often, all this will be erased and you will have to do it secretly. I say this, this is sacred truth. My brothers, ask me for consolation and union among brothers, open your hearts to the power of the Holy Spirit, who will make new men of you. Be at the service of the weakest, be humble and abandon pride and haughtiness, especially, those who, reading my and my Mother's messages, ridicule everything, but if they would only read, meditate and pray, I myself would respond in their hearts. Now I bless you in the name of the Father, in My Name and the Holy Spirit, Amen.", dataset["text_en"])
#dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 1)), "", dataset["text_en"])
#dataset["text_en"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 1)), "", dataset["text_en"])
# POLISH
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, ileż czułości czuje moje matczyne serce, gdy widzę, jak moje dzieci klękają z wielką wiarą. Dzieci moje, wkrótce będziecie świadkami Ostrzeżenia - spotkania z moim Jezusem, który tak bardzo was kocha; oczekujcie na ten gest miłosierdzia, ale nie z lękiem, lecz z radością. Umiłowane dzieci, idźcie do spowiedzi, abyście byli gotowi na Jego przyjście; bądźcie zawsze czujni, moje dzieci, kocham was i chcę was prowadzić jak matka; wielkie będzie cierpienie tych, którzy nie chcą uznać Boga. Dzieci moje, módlcie się za Kościół, a szczególnie za biskupów, kardynałów i kapłanów, aby porzucili wszelką pychę i zaczęli głosić słowo Boże, aby nie zajmowali się już polityką, ale jak Piotr byli rybakami dusz. Teraz udzielam wam mojego matczynego błogosławieństwa w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"]) 
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 6)), "Droga córko, dziękuję ci, że przyjęłaś mnie do swojego serca. Nie musicie się lękać, bo gdy będziecie głosić Słowo Boże, Ja będę z wami. Dzisiejszy Kościół postawił mury między moim Synem a prawdziwą nauką i pomimo cierpienia, jakie sprawia Najświętszemu Sercu Jezusa, On jest tam, aby go chronić. Kościół, zamiast karmić moje dzieci Ciałem i Krwią Jezusa, odsunął od siebie Jego obecność, a mimo to jest On zawsze gotowy, by ofiarować swoją pomoc. Nawróćcie się! Moja córko, masoneria i jej pozaziemskie siły zła oderwały przedstawicieli Kościoła od prawdziwej wiary chrześcijańskiej, znieważając Ciało Jezusa, ofiarowując je w niewłaściwy sposób i zmuszając moje dzieci, aby nie klękały i przyjmowały go na dłoń, głosząc wielkie kłamstwo. Proszę was: powróćcie do prawdziwej wiary i pozwólcie mi pomóc wam w mrocznych chwilach, które nadejdą. Mówię wam: prawdziwy Kościół odrodzi się i będzie większy i wspanialszy. Teraz zalecam wam modlitwę, bo czas się kończy. Błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"]) 
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 10)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Widzę, że wielu z was martwi się o czasy, które nadejdą, ale jestem tu, aby was pocieszyć, pomyślcie, że wszelkie zło zostanie pokonane, a wy, moi walczący żołnierze, dostąpicie łask i miłosierdzia, zobaczycie oczami, dotkniecie rękami wszystkich łask, które zstąpią. Drogie dzieci, módlcie się mocno, a w ten sposób, razem ze mną, będziecie świadkami zwycięstwa mojego Niepokalanego Serca. Módlcie się za Kościół, módlcie się za Japonię i Chiny, aby zostały uwolnione od bólu, który spowodują. Dzieci moje, spójrzcie w niebo, tam zobaczycie znaki czasu. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 13)), "Drogie dzieci, dziękuję wam, że jesteście tutaj i że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, módlcie się, módlcie się, dziś tak jak wtedy (objawienie w Fatimie) nadal proszę o modlitwę i nawrócenie. Gdyby wszystko odbyło się zgodnie z moją prośbą, zaznalibyście pokoju; tymczasem bramy piekielne zostały otwarte, a wy, moje maleństwa, jeśli nie umocnicie się w wierze, będziecie kroczyć drogą zatracenia. Jestem tu, ze złamanym sercem, z powodu wszystkiego, na co pozwalasz. Dzieci moje, spójrzcie na Kościół, nie chce uznać mnie za Współodkupicielkę, jestem Królową Nieba i Ziemi, Tą, która prowadzi was do mojego Syna Jezusa, jestem Jego Matką i was wszystkich, przyjmijcie tę prawdę. Moje dzieci, módlcie się za moje ukraińskie dzieci, które jeszcze żywe zostały wrzucone do dwóch grobów. Dzieci moje, ziemia będzie drżeć coraz bardziej, ale nie lękajcie się, bo Ja jestem tu, aby was chronić, nie ma już czasu, bądźcie coraz bardziej duchowi i patrzcie na znaki nieba i ziemi. Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 17)), "Moje dzieci, dziękuję wam, że jesteście tutaj na modlitwie. Umiłowane dzieci, również dzisiaj dziękuję wam, że odpowiedzieliście na moje wezwanie. Moje serce jest zasmucone tym wszystkim, co się wydarzy. Widzę wiele zamkniętych serc, wiele moich dzieci, które są zagubione i nie słuchają mojego miłosnego wołania. Dzieci moje, proszę was, bądźcie odważnymi świadkami, nie ma już czasu, słuchajcie słów waszej Matki, zróbcie zapasy wody, żywności i lekarstw, wszystko się kończy. Proszę, moje dzieci, pomóżcie mi. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 21)), "Dzieci moje, dziękuję wam za obecność na modlitwie i za odpowiedź na moje wezwanie w waszych sercach. Dzieci moje, przeżywacie mroczne czasy i w przyszłości staną się one ciemnością, ale wy zawsze patrzycie w stronę światła. Ile razy Jezus obiecał ci ochronę i czy kiedykolwiek cię rozczarował? Ile razy byłeś w trudnej sytuacji, ale On nigdy cię nie opuścił. Dzieci moje, dzieci moje, nie lękajcie się, cokolwiek się stanie, módlcie się, módlcie się gorliwie, pokryjcie ziemię waszymi modlitwami, módlcie się za kapłanów, którzy sprzeciwiają się Bogu, módlcie się za możnych, bo knują. Dzieci moje, chcą wam odebrać wolność, ale wy miejcie wiarę i postępujcie w prawdzie, tylko ona uczyni was wolnymi. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 24)), "Moje drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, nawet gdy myślicie, że jesteście sami, Ja, wasza Matka, jestem tutaj. Dzieci moje, wojna i głód będą coraz bardziej odczuwalne, ale wiara w Boga będzie was chronić, nie bójcie się. W tym czasie bądźcie zjednoczeni i nie bądźcie powodem rozłamu. Dzieci, módlcie się za biskupów obłudnych i przewrotnych, módlcie się za Kościół, który krwawi tak jak mój Syn. Módlcie się za papieża. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 28)), "Umiłowane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, tylko intensywna i nieustanna modlitwa może pocieszyć moje błogosławione i bolesne serce i serce mojego Syna. Dzieci moje, módlcie się, ponieważ nie wiecie, co nadchodzi, ciemna noc jest bardzo bliska, zapalcie w waszych domach pobłogosławione świece. Dzieci moje, aniołowie walczą mieczami, ale wy, z różańcem świętym w rękach, kontynuujcie tę modlitwę, która jest mi tak droga. Dzieci moje, otwórzcie wasze serca, aby zagościła w nich radość i nadzieja, bo przychodzę, aby was przygotować, nie bójcie się tego, co zobaczycie, bo mój błogosławiony płaszcz jest nad wami. Podnieście ręce i chwalcie Pana. Umiłowane dzieci, pamiętajcie zawsze o mojej nieskończonej matczynej miłości do was. Teraz błogosławię was w imię Trójcy Przenajświętszej, Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 31)), "Synowie moi i bracia, dziękuję wam, że uklęknęliście pod moim Krzyżem. Bracia, karmcie się tym, co wam zostawiłem, moją żywą obecnością w Ciele i Krwi. Adorujcie Najświętszy Sakrament, a wiele łask otrzymacie. Dzieci moje, korzystajcie z tych chwil, kiedy możecie swobodnie dysponować moim ciałem, bo wkrótce zwiodą was, mówiąc, że to tylko pamiątka. Sam daję wam to ostrzeżenie, czytajcie często Ewangelię, to wszystko zostanie usunięte i będziecie musieli robić to w tajemnicy. Ja to mówię, to jest święta prawda. Bracia moi, proście o pociechę i jedność między braćmi, otwórzcie wasze serca na moc Ducha Świętego, który uczyni z was nowych ludzi. Służcie najsłabszym, bądźcie pokorni, porzućcie pychę i arogancję, zwłaszcza ci, którzy czytając orędzia moje i mojej Matki, wszystko wyśmiewają, lecz gdyby tylko czytali, rozważali i modlili się, Ja sam odpowiedziałbym w ich sercach. Teraz błogosławię was w imię Ojca, w Imię Moje i Ducha Świętego, Amen.", dataset["text_pl"])
#dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 1)), "", dataset["text_pl"])
#dataset["text_pl"] = np.where(((dataset["month"] == 5) & (dataset["day"] == 1)), "", dataset["text_pl"])
dataset = dataset[['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en']]

dataset_ready = pd.read_csv("may_2022.csv")


dataset = dataset.merge(dataset_ready, how="left", on=['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en'])

dataset_ok = dataset[~dataset["text_pt"].isnull()]
dataset_translate = dataset[dataset["text_pt"].isnull()]



dataset_translate["text_es"] = dataset_translate["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset_translate["text_fr"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset_translate["text_zh"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'zh'))
dataset_translate["text_de"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'de'))
dataset_translate["text_pt"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'pt'))


dataset = pd.concat([dataset_ok, dataset_translate])

dataset = dataset.sort_values(by="day")


dataset.to_csv("may_2022.csv", encoding="utf-8", index=False)









