# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator
import goslate
gs = goslate.Goslate()

#dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "", dataset["text_it"])



dataset = pd.read_csv("june_cleaned.csv", encoding="utf-8")




# ITALIAN
dataset["text_it"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 3)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, grazie per aver piegato le ginocchia durante la preghiera. Figli, attendete l’Avvertimento ,che è più vicino di quanto voi pensiate, ma attendetelo con grande gioia, l’amore di Dio vi farà vedere cose meravigliose, chi avrà paura è perché non si è ancora liberato dal peccato, nonostante il mio continuo richiamo. Figli miei, questo è il momento della vostra purificazione e dovete viverla con accettazione piena. Figli, vi prego, Io tocco ancora la terra perché vi voglio salvi. voi vivete i miei messaggi con umiltà, preghiera e fratellanza, sarete come il piccolo resto, che rimase vicino al mio Gesù, siate apostoli e abbiate il coraggio della fede. Ora vi lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, amen. Sarò con voi fino alla fine della preghiera.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 4)), "Figlia mia, nonostante le mie lacrime, continuate a vivere nell’indifferenza, anche i miei figli prediletti non hanno l’umiltà del silenzio e della contemplazione. Figli, piango perché Io so cosa arriverà a breve e voi continuate a vivere come se non conosceste la verità. Figli miei, nella Chiesa, sarà versato sangue. Pregate per i potenti perché vogliono portarvi alla morte. Il substrato della terra si riscalderà così tanto, che anche molti pesci del mare moriranno. Figli miei, tornate a Dio, vostra unica salvezza e convertitevi. Ora vi benedico, nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 7)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, la Chiesa Di Pietro sarà molto attaccata anche dall’interno, quanti sono i traditori! anche tra coloro che sono stati chiamati alla vocazione, ma che adesso tradiscono mio Figlio. Figli, la guerra continuerà e prenderà molti paesi, pregate per la Francia e per l’Italia, saranno coloro che subiranno molte perdite.  Pregate per l’America, perché sarà cancellata una buona parte di essa. Figli, vi chiedo di guardare sempre la luce di Dio, anche quando tutto sarà più difficile, non perdete mai la speranza. Pregate per coloro che hanno i cuori chiusi, affinché possano essere salvati durante l’Avvertimento, i tempi sono sempre più vicini. Pregate, perché anche i peggiori dei peccatori potrebbero salvarsi davanti al Re dei Re. Figli, fate attenzione, la carestia si diffonderà velocemente, così come altre malattie in arrivo. Figli, non barattate mai la vostra anima per un pezzo di pane, ascoltate le mie parole. Figli miei, tutto questo dolore smetterà, ma adesso abbiamo bisogno del vostro coraggio di soldati di luce che urlano la verità, non abbiate mai paura, Io sono qui per proteggervi. Guardate le variazioni climatiche, dal forte caldo ci sarà un forte freddo, dai tornadi si passerà alla forte grandine, abituatevi ai cambiamenti, perché saranno molteplici. Ora vi lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, amen", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 11) & (dataset["author"] == "Holy Mary")), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli amati, pregate per la Chiesa, perché molti vescovi sono uno contro l’altro a causa del potere. Il comunismo sta avanzando, entrerà anche nella Chiesa e voi ancora non capite.  Molti dei miei figli arriveranno da ogni luogo, perché la carestia avanza. L’America farà parlare di sé. Figli miei, voi avete il libero arbitrio, ma lo state usando molto male e non significa far tutto ciò che si vuole anche peccando, cibatevi del Santo Vangelo e dell’Eucaristia. Figli, ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 11) & (dataset["author"] == "Jesus Christ")), "Figli miei, sono così stanco, ma così stanco, troppa cattiveria. Ecco questo è il momento dell’anticristo, vi stuzzicherà sempre. Figli miei, non siate ipocriti, amatemi, amatevi per davvero e perdonate. La notte buia sta arrivando, chi sarà con me lo sarà per sempre. Io vi metto ai vostri posti e inizia ora la mia conta; voi non siete pronti ancora ma, se non avrete abbandonato tutto ciò che è del mondo, non potrete mai entrare nel mio Regno. Pregate figli, pregate tanto. I miei traditori, nella mia Chiesa, continuano ad infliggermi, continuano a farmi del male, stanno lottando per il potere, non hanno capito che Io sono l’unico che può decidere di tutte le azioni. Ah! questa libera scelta come se la stanno giocando. Oh! Figlia mia, devi essere più tenace, sii più dura, spiega loro che i tempi sono finiti, ma non rattristarti perché Io sono con te. Non credono alle mie profezie e a quelle di mia Madre, non credono, ma come faranno quando arriverà la notte buia e tutto sarà compiuto, a chi chiederanno aiuto? Tanti si convertiranno, ma tanti moriranno, avranno paura, non hanno capito che Io sono il vostro tutto, il vostro Dio. Io sono qui e vi guardo, vi ascolto e scruto i vostri cuori. Figli miei, siate come fratelli, siate uniti, date conforto a chi ha bisogno, confortatevi a vicenda, stringetevi come un’unica famiglia nel mio nome, ma dovete stare uniti, presto arriverà il peggio, ma non capite che senza di me sarà tutto perduto? Vi benedico, pensate, riflettete e meditate le mie parole! Vi benedico figli, siate guerrieri, non abbattetevi mai, il mio Spirito Santo entrerà in ognuno di voi per essere più forti, per darvi la forza e la pace. Vi amo tutti, uno per uno. Vi benedico, sempre, nel nome del Padre, nel mio Santissimo Nome e dello Spirito Santo. Figli miei, vi do una carezza passando, uno per uno, sentirete il soffio dello Spirito e capirete che Io sono qui.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 14)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore.  Figli, come siete belli quando vi inginocchiate nella preghiera. Ascoltate ciò che ho da dirvi, non distraetevi dai miei messaggi, ricordate che sono per la salvezza dell’umanità. Avete occhi per guardare, ma non vedete, orecchie per ascoltare e non udite. Figli miei, pregate per la Francia, patirà molto. Convertitevi!!  Ora vi lascio con la mia benedizione materna, nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 21)), "Cari figli, grazie per essere qui nella preghiera e per aver piegato le vostre ginocchia.  Figlia, devi dire ai sacerdoti che la loro confusione è tra il cuore e la bocca, così stanno portando la confusione tra i miei figli e ancora non capiscono che la transustanziazione del pane e del vino, avviene con la Consacrazione e la discesa dello Spirito Santo che trasforma in corpo e sangue e divinità. Figli miei, pregate tanto, perché la terra è un deserto immenso e dove ci sarà l’acqua, questa causerà molti danni. Figli, i miei angeli cantano il loro lamento perché mio Figlio Gesù è straziato dal dolore, pregate e amate il mio Gesù e ricordate che è morto per voi e per liberarvi dal peccato. Il Vescovo di Roma sarà attaccato proprio da coloro che lo sostengono. Ora vi benedico, nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 25)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli amati, in questi tempi particolari non abbandonate mai la preghiera e accorgetevi delle grazie che scendono su di voi e ringraziate sempre. Figli miei, voi siete prediletti ai miei occhi e davanti al Padre Nostro. Questo è il motivo delle apparizioni in tutto il mondo affinché siate avvertiti dei pericoli che correte se abbandonate Dio. Figli, ringraziate e abbiate rispetto per i profeti che sono stati chiamati alla missione, essi guidano la Chiesa, cioè voi tutti.  La Chiesa non è solo fatta da templi, Gesù stesso a volte, ha abbattuto le mura. Figli miei, questi sono anche i tempi di grazia e tante ne vedrete scendere, serviranno per far aprire gli occhi a chi non crede, che il cielo è unito alla terra e Gesù è vicino a ognuno di voi.  Pregate per la Spagna. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 28)), "Cari figli, Io vostro Padre, desidero che ognuno di voi si ricordi che Io spesso sono dove siete voi. Io conosco tutti i vostri bisogni e tutto ciò che voi desiderate, quanto vorrei vedervi venire a me con fiducia e amore!  Non fatevi allettare dai vizi che conducono alla rovina totale. Figli, l’amore per voi è così grande che Io non provo una gioia pari a quella di essere tra gli uomini. Ecco, Io dico a coloro che sono in stato di peccato: non ignorate questa chiamata d’amore, altrimenti non potrò entrare in voi, vorrei che voi vi guardaste dal peccato. Vi guardo, eppure ignorate che Io sono qui e vi chiamo con la mia grande gioia, vorrei sempre stare accanto a voi con la speranza che un giorno tornerete dal Padre Vostro, sarebbe un bellissimo atto di amore. Io sono la sorgente viva, vorrei essere per voi la gioia senza fine, Mio Figlio Gesù è in me e Io sono in Lui e il nostro amore che è lo Spirito Santo ci tiene uniti. Venite e abbeveratevi in questa sorgente e la vostra gioia sarà così grande fino all’eternità. Non siate indifferenti a questo amore, solo così sarete benedetti, credete a questa verità. Approfittate di questi duri tempi, seguite le Scritture e soprattutto i dieci comandamenti. Figli, chiamatemi con il nome 'Padre' anche una sola volta e avrete la certezza della vita eterna. Dico a voi figli, che state lavorando per la mia Gloria e vi impegnate a farmi conoscere e ad amare, che la vostra ricompensa sarà grande e avrete molto di più nell’eternità. A voi miei figli sacerdoti, Io vi esorto a far conoscere questo amore Paterno che nutro per tutti voi in particolare, dovete lavorare affinché la mia volontà si realizzi, non perdete tempo con le cose del mondo e non siate inattivi, ma fate conoscere la mia potenza, Io desidero solo essere amato, e a voi che in questo momento non state facendo la mia volontà, dico: Guai!  Mi rivolgo ai miei bambini, parlate di me, non respingetemi, Io non voglio sacrifici, voglio amore e rispetto. Guardate il crocifisso, il Santissimo Sacramento, le sacre scritture, affinché possiate capire fino a che punto vi ho amati e se le famiglie mi amassero di più, mi conoscessero di più, mi invocassero di più, Io donerei loro la mia pace, la mia Misericordia ed Io sarò il vostro tutto che vi basterà per tutto, non rifiutate questa gioia vorrei farvi godere di questa luce che illuminerà la vostra vita. Ora vi benedico figli nel nome della Santissima Trinità.", dataset["text_it"])
#dataset["text_it"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 1)), "", dataset["text_it"])
#dataset["text_it"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 1)), "", dataset["text_it"])

# ENGLISH
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 3)), "Dear children, thank you for responding to my call in your hearts. My children, thank you for kneeling in prayer. My children, await the Warning ,which is closer than you think, but await it with great joy, God's love will show you wonderful things, those who will be afraid is because they have not yet freed themselves from sin, despite my continuous call. My children, this is the time of your purification and you must live it with full acceptance. Children, please, I still touch the earth because I want you to be saved. you live my messages with humility, prayer and brotherhood, you will be like the little remnant, who stayed close to my Jesus, be apostles and have the courage of faith. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen. I will be with you until the end of prayer.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 4)), "My child, despite My tears, you continue to live in indifference, even My beloved children do not have the humility of silence and contemplation. My children, I weep because I know what is coming soon and you continue to live as if you do not know the truth. My children, in the Church, blood will be shed. Pray for the powerful because they want to bring you to death. The subterranean earth will heat up so much that even many fish in the sea will die. My children, return to God, your only salvation, and be converted. Now I bless you, in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 7)), "My children, thank you for responding to my call in your hearts. My children, the Church of Peter will also be much attacked from within, how many are the traitors! even among those who were called to vocational ministry but are now betraying my Son. My children, the war will continue and will take many countries, pray for France and Italy, they will be the ones who will suffer many losses.  Pray for America, for a good part of it will be wiped out. Children, I ask you to always look at God's light, even when everything will be more difficult, never lose hope. Pray for those whose hearts are closed, that they may be saved during the Warning, the times are getting closer. Pray, for even the worst of sinners may be saved before the King of kings. Children, be careful, famine will spread quickly, as will other coming diseases. Children, never barter your souls for a piece of bread, listen to my words. My children, all this pain will stop, but now we need your courage as soldiers of light shouting the truth, never be afraid, I am here to protect you. Watch the weather changes, from strong heat there will be strong cold, from tornadoes there will be strong hail, get used to the changes, for they will be manifold. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 11) & (dataset["author"] == "Holy Mary")), "Dear children, thank you for responding to my call in your hearts. Beloved children, pray for the Church, for many bishops are against each other because of power. Communism is advancing, it will also enter the Church and you still do not understand.  Many of my children will come from everywhere, because the famine is advancing. America will make the news. My children, you have free will, but you are using it very badly and it does not mean doing whatever you want even sinning, feed yourselves on the Holy Gospel and the Eucharist. My children, I now bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 11) & (dataset["author"] == "Jesus Christ")), "My children, I am so tired, but so tired, too much wickedness. Here is the time of the antichrist, he will always tease you. My children, do not be hypocrites, love me, really love each other and forgive. The dark night is coming, those who will be with me will be with me forever. I put you in your places and my counting begins now; you are not ready yet but unless you have abandoned all that is of the world, you will never be able to enter my Kingdom. Pray children, pray much. My traitors, in My Church, continue to inflict Me, continue to harm Me, they are fighting for power, they have not understood that I am the only One who can decide all actions. Ah! this free choice how they are playing it. Oh! My daughter, you must be more tenacious, be tougher, explain to them that the times are over, but do not grieve because I am with you. They do not believe My prophecies and My Mother's prophecies, they do not believe, but how will they do when the dark night comes and all is fulfilled, whom will they ask for help? So many will convert, but so many will die, they will be afraid, they have not understood that I am your everything, your God. I am here and I am watching you, listening to you and scanning your hearts. My children, be like brothers, be united, give comfort to those in need, comfort each other, huddle together as one family in my name, but you must stand together, soon the worst will come, but do you not understand that without me all will be lost? I bless you, think, reflect and meditate on my words! I bless you children, be warriors, never get down, my Holy Spirit will enter each of you to be stronger, to give you strength and peace. I love you all, one by one. I bless you, always, in the name of the Father, in my Most Holy Name and the Holy Spirit. My children, I give you a caress as you pass, one by one, you will feel the breath of the Spirit and understand that I am here.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 14)), "Dear children, thank you for responding to my call in your hearts.  My children, how beautiful you are when you kneel in prayer. Listen to what I have to say, do not be distracted by my messages, remember that they are for the salvation of mankind. You have eyes to look but do not see, ears to listen and do not hear. My children, pray for France, she will suffer much. Convert!!!  Now I leave you with my motherly blessing, in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 21)), "Dear children, thank you for being here in prayer and for bending your knees. Daughter, you have to tell the priests that their confusion is between the heart and the mouth, so they are bringing confusion among My children and they still do not understand that the Transubstantiation of the bread and wine, happens with the Consecration and the descent of the Holy Spirit who transforms into Body and Blood and Divinity. My children, pray much, for the earth is a vast desert and where there will be water, it will cause much damage. Children, my angels sing their lament because my Son Jesus is torn with pain, pray and love my Jesus and remember that he died for you and to free you from sin. The Bishop of Rome will be attacked by the very people who support him. Now I bless you, in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 25)), "My children, thank you for responding to my call in your hearts. Beloved children, in these special times never abandon prayer and become aware of the graces that descend upon you and always be grateful. My children, you are beloved in my eyes and before Our Father. This is the reason for the apparitions throughout the world so that you may be warned of the dangers you run if you abandon God. My children, be grateful and have respect for the prophets who have been called to the mission, they lead the Church, that is you all.  The Church is not only made up of temples, Jesus Himself at times, tore down the walls. My children, these are also times of grace and many you will see coming down, they will serve to open the eyes of those who do not believe, that heaven is united to earth and Jesus is close to each of you. Pray for Spain. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 28)), "Dear children, I your Father, desire that each of you remember that I am often where you are. I know all your needs and all that you desire, how I wish to see you come to Me with trust and love! Do not be enticed by vices that lead to total ruin. My children, love for you is so great that I do not feel a joy equal to that of being among men. Behold, I say to those who are in a state of sin: do not ignore this call of love, otherwise I will not be able to enter you; I would like you to beware of sin. I look at you, yet you ignore that I am here and call you with My great joy, I would always like to be beside you with the hope that one day you will return to Your Father, it would be a beautiful act of love. I am the living spring, I would like to be for you the joy without end, My Son Jesus is in Me and I am in Him and our Love which is the Holy Spirit holds us together. Come and drink in this spring and your joy will be so great until eternity. Do not be indifferent to this love, only then will you be blessed, believe this truth. Take advantage of these hard times, follow the Scriptures and especially the Ten Commandments. Children, call me by the name 'Father' even once and you will have the assurance of eternal life. I say to you sons, who are working for My Glory and striving to make Me known and loved, that your reward will be great and you will have much more in eternity. To you my priest sons, I urge you to make known this Fatherly love that I have for all of you in particular, you must work so that my will may be done, do not waste your time with the things of the world and do not be inactive, but make known my power, I only desire to be loved, and to you who are not doing my will at this time, I say, Woe! I address My children, speak of Me, do not reject Me, I do not want sacrifices, I want love and respect. Look at the Crucifix, the Blessed Sacrament, the Sacred Scriptures, so that you may understand to what extent I have loved you and if families would love me more, know me more, invoke me more, I will give them my peace, my Mercy and I will be your all that will suffice for everything, do not reject this joy I would like you to enjoy this light that will illuminate your life. Now I bless you children in the name of the Most Holy Trinity.", dataset["text_en"])
#dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 1)), "", dataset["text_en"])
#dataset["text_en"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 1)), "", dataset["text_en"])

# POLISH
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, dziękuję wam, że uklękliście do modlitwy. Dzieci moje, oczekujcie Ostrzeżenia, które jest bliżej, niż myślicie, oczekujcie go z wielką radością, miłość Boża sprawi, że zobaczycie cudowne rzeczy, bać będą się ci, którzy jeszcze nie uwolnili się od grzechu, mimo moich nieustannych wezwań. Moje dzieci, to jest czas waszego oczyszczenia i musicie go przeżyć z pełną akceptacją. Dzieci moje, błagam was, wciąż przebywam na ziemi, bo chcę, abyście byli zbawieni. Żyjąc moimi orędziami w pokorze, modlitwie i braterstwie, będziecie jak ta mała resztka, która pozostała blisko mojego Jezusa, będziecie apostołami i będziecie mieli odwagę wiary. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen. Będę z wami aż do końca modlitwy.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 4)), "Moje dziecko, mimo moich łez nadal żyjesz w obojętności, nawet moje ukochane dzieci nie mają pokory milczenia i kontemplacji. Dzieci moje, płaczę, bo wiem, co wkrótce nadejdzie, a wy nadal żyjecie tak, jakbyście nie znali prawdy. Dzieci moje, w Kościele poleje się krew. Módlcie się za władców, bo oni chcą was doprowadzić do śmierci. Wnętrze Ziemi rozgrzeje się tak bardzo, że zginie nawet wiele ryb w morzu. Moje dzieci, powróćcie do Boga, waszego jedynego ratunku, i nawróćcie się. Teraz ja was błogosławię w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 7)), "Dzieci moje, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, Kościół Piotrowy będzie również mocno atakowany od wewnątrz, jak wielu jest zdrajców, nawet wśród tych, którzy zostali powołani, a teraz zdradzają mojego Syna. Dzieci moje, wojna będzie trwała i zajmie wiele krajów, módlcie się za Francję i Włochy, to one poniosą wiele strat. Módlcie się za Amerykę, bo zostanie zmieciona z powierzchni ziemi. Dzieci moje, proszę was, abyście zawsze patrzyli na Boże Światło, nawet gdy wszystko będzie trudniejsze, nigdy nie traćcie nadziei. Módlcie się za tych, których serca są zamknięte, aby zostali zbawieni w czasie Ostrzeżenia, bo czasy się zbliżają. Módlcie się, aby nawet najgorsi grzesznicy mogli zostać zbawieni przed Królem królów. Dzieci, strzeżcie się, głód będzie się szybko rozprzestrzeniał, podobnie jak inne nadchodzące choroby. Moje dzieci, nie przehandlujcie waszych dusz za kawałek chleba, słuchajcie moich słów. Moje dzieci, cały ten ból się skończy, ale teraz potrzebujemy waszej odwagi jako żołnierzy światła, którzy wykrzykują prawdę, nigdy się nie bójcie, jestem tu, aby was chronić. Obserwuj zmiany klimatyczne: od silnych upałów do silnego zimna, od tornad do silnego gradu, przyzwyczajaj się do zmian, bo będzie ich wiele. Teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 11) & (dataset["author"] == "Holy Mary")), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, módlcie się za Kościół, ponieważ wielu biskupów z żądzy władzy występuje przeciwko sobie. Komunizm postępuje, wkroczy także do Kościoła, a wy nadal tego nie rozumiecie. Wiele z moich dzieci przybędzie ze wszystkich stron, ponieważ głód jest coraz większy. Ameryka da o sobie znać. Dzieci moje, macie wolną wolę, ale bardzo źle z niej korzystacie - nie polega ona na postępowaniu według własnego uznania, często prowadzącego do grzechu, lecz na karmieniu się świętą Ewangelią i Eucharystią. Dzieci moje, błogosławię was teraz w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 11) & (dataset["author"] == "Jesus Christ")), "Moje dzieci, jestem tak zmęczony, tak zmęczony, zbyt wiele niegodziwości. To jest czas antychrysta, on zawsze będzie wam przeszkadzał. Moje dzieci, nie bądźcie hipokrytami, kochajcie mnie, kochajcie siebie naprawdę i przebaczajcie. Nadchodzi noc ciemna, ci, którzy będą ze Mną, będą ze Mną na zawsze. Umieściłem was na waszych miejscach i teraz zaczyna się moje odliczanie; nie jesteście jeszcze gotowi, ale jeśli nie porzuciliście wszystkiego, co jest ze świata, nigdy nie będziecie mogli wejść do mojego Królestwa. Módlcie się, moje dzieci, módlcie się mocno. Zdrajcy, w moim Kościele, nadal mnie atakują, nadal mnie krzywdzą, walczą o władzę, nie zrozumieli, że tylko ja mogę decydować o wszystkich działaniach. Ach! Ten wolny wybór, jak oni to rozgrywają. Córko moja, musisz być wytrwalsza, mocniejsza, wytłumacz im, że te czasy się skończyły, ale nie smuć się, bo Ja jestem z tobą. Nie wierzą w moje proroctwa i proroctwa mojej Matki, nie wierzą, ale jak postąpią, gdy nadejdzie ciemna noc i wszystko się spełni, do kogo zwrócą się o pomoc? Wielu się nawróci, ale wielu umrze, będą się bać, nie zrozumieli, że Ja jestem waszym Wszystkim, waszym Bogiem. Jestem tu i patrzę na was, słucham was i badam wasze serca. Dzieci moje, bądźcie jak bracia, bądźcie zjednoczeni, dawajcie pociechę potrzebującym, pocieszajcie się nawzajem, tulcie się do siebie jak jedna rodzina w moje imię, ale musicie być zjednoczeni, wkrótce nadejdzie najgorsze, ale czy nie rozumiecie, że beze mnie wszystko będzie stracone? Błogosławię was, myślcie, rozważajcie i medytujcie nad moimi słowami! Błogosławię was, moje dzieci, bądźcie wojownikami, nigdy nie dajcie się pokonać, mój Duch Święty wejdzie w każdego z was, abyście byli silniejsi, aby dać wam siłę i pokój. Kocham was wszystkich. Błogosławię was zawsze w imię Ojca, w moje Najświętsze Imię i Ducha Świętego. Moje dzieci, gdy będziecie przechodzić, przytulę każdego z was, poczujecie tchnienie Ducha i zrozumiecie, że jestem tutaj.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 14)), "Drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Dzieci moje, jakże jesteście piękne, gdy klękacie do modlitwy. Słuchajcie tego, co mam wam do powiedzenia, nie roztrząsajcie moich orędzi, pamiętajcie, że są one dla zbawienia ludzkości. Macie oczy do patrzenia, ale nie widzicie, uszy do słuchania, a nie słyszycie. Dzieci moje, módlcie się za Francję, bo ona będzie wiele cierpieć. Nawróć się! Teraz zostawiam was z moim matczynym błogosławieństwem, w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 21)), "Drogie dzieci, dziękuję wam, że jesteście tutaj na modlitwie i że uklęknęliście. Córko, musisz powiedzieć księżom, że ich zamęt jest między sercem a ustami, dlatego wprowadzają zamęt wśród moich dzieci i nadal nie rozumieją, że Przeistoczenie chleba i wina dokonuje się podczas konsekracji i zstąpienia Ducha Świętego, który przemienia je w Ciało i Krew i Bóstwo. Dzieci moje, módlcie się mocno, bo ziemia jest ogromną pustynią i tam, gdzie jest woda, wyrządzi ona wiele szkód. Moje dzieci, moi aniołowie śpiewają swój lament, ponieważ mój Syn Jezus jest rozdarty bólem, módlcie się i kochajcie mojego Jezusa i pamiętajcie, że umarł za was, aby uwolnić was od grzechu. Biskup Rzymu będzie atakowany właśnie przez tych, którzy go popierają. Teraz ja was błogosławię w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 25)), "Moje dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Umiłowane dzieci, w tych szczególnych czasach nigdy nie rezygnujcie z modlitwy i bądźcie świadomi łask, które na was zstępują i zawsze bądźcie wdzięczni. Moje dzieci, jesteście uprzywilejowani w moich oczach i przed Naszym Ojcem. Objawienia na całym świecie odbywają się po to, by was ostrzec przed niebezpieczeństwami, na które narażacie się, jeśli porzucacie Boga. Moje dzieci, dziękujcie i miejcie szacunek dla proroków, którzy zostali powołani do misji, prowadzą Kościół, czyli was wszystkich. Kościół to nie tylko świątynie, sam Jezus niekiedy burzył mury. Moje dzieci, to jest również czas łaski i zobaczycie, jak wiele ich spłynie, posłużą one do otwarcia oczu tym, którzy nie wierzą, że Niebo jest zjednoczone z ziemią, a Jezus jest blisko każdego z was. Módlcie się za Hiszpanię. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 28)), "Drogie dzieci, Ja, wasz Ojciec, pragnę, aby każdy z was pamiętał, że jestem tam, gdzie wy. Znam wszystkie wasze potrzeby i pragnienia, jakże chciałbym, abyście przyszli do mnie z ufnością i miłością! Nie daj się omamić pokusom, które prowadzą do całkowitej ruiny. Moje dzieci, moja miłość do was jest tak wielka, że nie odczuwam radości równej tej, jaką daje przebywanie wśród ludzi. Oto mówię do tych, którzy są w stanie grzechu: nie ignorujcie tego wezwania miłości, inaczej nie będę mógł przyjść do was; chciałbym, abyście strzegli się grzechu. Patrzę na ciebie, a jednak ignorujesz, że jestem tu i wołam cię z moją wielką radością, chciałbym zawsze być blisko ciebie z nadzieją, że kiedyś wrócisz do Ojca, to byłby piękny akt miłości. Jestem żywym źródłem, pragnę być dla was radością bez końca, Mój Syn Jezus jest we mnie, a ja w Nim, a nasza miłość, którą jest Duch Święty, utrzymuje nas w jedności. Przyjdź i pij z tego źródła, a twoja radość będzie tak wielka aż do wieczności. Nie bądź obojętny na tę miłość, tylko wtedy będziesz błogosławionym, uwierz w tę prawdę. Wykorzystaj te trudne czasy, kieruj się Pismem Świętym, a zwłaszcza dziesięcioma przykazaniami. Moje dzieci, nazwijcie mnie choć raz imieniem 'Ojciec', a będziecie mieli pewność życia wiecznego. Mówię wam synowie, którzy pracujecie dla mojej Chwały i dążycie do tego, abym był znany i kochany, że wasza nagroda będzie wielka i będziecie mieli o wiele więcej w wieczności. Was, moi synowie kapłani, wzywam, abyście ujawnili tę ojcowską miłość, którą darzę was wszystkich. W szczególności musicie pracować, aby spełniła się moja wola, nie traćcie czasu na sprawy tego świata i nie bądźcie bezczynni, ale ujawnijcie moją moc, pragnę tylko być kochanym, a wam, którzy w tym czasie nie wypełniacie mojej woli, mówię: Biada! Zwracam się do moich dzieci, mówcie o mnie, nie odrzucajcie mnie, nie chcę ofiar, chcę miłości i szacunku. Patrzcie na krucyfiks, na Najświętszy Sakrament, w Pismo Święte, abyście zrozumieli, do jakiego stopnia was umiłowałem i jeśli rodziny będą Mnie bardziej kochać, bardziej poznawać, bardziej powoływać się na Mnie, to Ja dam im mój Pokój, moje Miłosierdzie i będę waszym wszystkim, co wystarczy na wszystko, nie odrzucajcie tej radości, chciałbym, abyście cieszyli się tym światłem, które rozświetli wasze życie. Teraz błogosławię was dzieci w imię Trójcy Przenajświętszej.", dataset["text_pl"])
#dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 1)), "", dataset["text_pl"])
#dataset["text_pl"] = np.where(((dataset["month"] == 6) & (dataset["day"] == 1)), "", dataset["text_pl"])

dataset = dataset[['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en']]

dataset_ready = pd.read_csv("june_2022.csv")


dataset = dataset.merge(dataset_ready, how="left", on=['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en'])

dataset_ok = dataset[~dataset["text_pt"].isnull()]
dataset_translate = dataset[dataset["text_pt"].isnull()]



dataset_translate["text_es"] = dataset_translate["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset_translate["text_fr"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset_translate["text_zh"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'zh'))
dataset_translate["text_de"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'de'))
dataset_translate["text_pt"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'pt'))


dataset = pd.concat([dataset_ok, dataset_translate])

dataset = dataset.sort_values(by="day")


dataset.to_csv("june_2022.csv", encoding="utf-8", index=False)









