# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator
import goslate
gs = goslate.Goslate()




dataset = pd.read_csv("july_cleaned.csv", encoding="utf-8")




# ITALIAN
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "Cari figli preziosi al mio cuore e a quello di Gesù, grazie per essere qui nella preghiera e per aver piegato le vostre ginocchia. Guardo questi piccoli in preghiera e come vorrei che anche voi foste così come loro con i cuori puri! Ricordate cosa ha detto Gesù: i piccoli entreranno nel mio Regno. Figli miei, vi supplico, sarà peggio del diluvio universale se voi non vi convertite, non voglio mettervi paura ma avvertirvi, tornate a Dio con le mani giunte, piegando le ginocchia e con il cuore e l’anima rivolti all’unico Salvatore, per poi vivere nell’eternità in paradiso. Figli, ci saranno terremoti, siccità e nubifragi, nella Chiesa, è entrato il male e il maligno ed è senza più mio Figlio. Guardatevi intorno, perché non riconoscerete più i vostri fratelli. Vi chiedo preghiere, digiuno e amore fraterno. Ora vi benedico, nel nome del Padre, del Figlio e dello Spirito Santo amen. Oggi scenderanno molte grazie su di voi, testimoniate!", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 5)), "Figli amati, grazie per essere qui nella preghiera e per aver risposto alla mia chiamata nel vostro cuore. Figli miei, siate sempre uniti, riparate per tutti gli orrori che ci sono su tutta la terra, recitando la corona del preziosissimo sangue di Gesù. Figli miei, guardate i cambiamenti che sono sulla terra, ma anche quelli spirituali saranno grandi, abituatevi a questi cambiamenti, perché niente tornerà come prima. Figli, pregate, perché il capo di Stato dell’America sarà fortemente attaccato. Io vengo ancora per darvi una carezza, vorrei confortarvi in questo mondo malsano e perverso. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 9)), "Cari figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, abbiate il coraggio di fare la vostra scelta ora, perché da ciò dipenderà la vostra vita, più vi avvicinerete alla luce è più sarete illuminati, più vi avvicinerete al male e più il demonio vi fagociterà facilmente. Figli miei, scegliete Dio per sempre, vi prego bambini miei, continuate a fare cenacoli di preghiera, aprite i vostri cuori e le vostre case ed Io vi benedirò e sarò sempre con voi per guidarvi. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen. ", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 15)), "Amata mia, figlia e sorella, scrivi al mondo. Oggi, peggiore del virus che avete tanto temuto, è la lussuria, la cattiveria, la confusione e l’egoismo che stanno dilagando nel cuore e nella mente di questa umanità. L ‘apostasia regna perché i miei consacrati non credono all’esistenza di satana e alle sue astuzie, non parlano del peccato che dilania, facendo passare il peccato, come ordinaria amministrazione. Io verrò a dividere il bene dal male, tornate a Me, prima che sia troppo tardi, voi non seguite più i miei insegnamenti, tollerate il male e chinate il capo ad esso. Coloro che approveranno le leggi contro quelle del Padre mio, saranno vomitati e sentiranno il bruciore del fuoco eterno. I castighi saranno per la purificazione di questa umanità perversa. Fate la vostra scelta, vi dico ciò, affinché siate consapevoli. Svegliatevi, perché il tempo è finito, molti rifiutano la mia Misericordia, eppure, ho mostrato loro i miracoli, ma sono ciechi e sordi. Io dico ai politici: in nome di Dio, fermatevi ora! Distruggerò i vostri piani, solo Io, posso decidere la fine dell’uomo, i vostri progetti satanici saranno spazzati via, insieme a voi, la giustizia del Padre mio tuonerà così forte che l’universo tutto tremerà. Coloro che seguono le leggi di Dio non dovranno temere, ma esultare, perché il regno di Dio è vicino. La pace sia con voi, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 16)), "Cari figli, grazie per essere qui nella preghiera e per aver piegato le vostre ginocchia. Figli miei, l’Italia pagherà a caro prezzo le decisioni dei politici. I vulcani erutteranno, guardate gli eventi che accadranno sulla terra, affinché possiate credere e tornare a Dio. Figli amati, presto la catena di satana sarà più forte, non accettate ciò che di più pericoloso vi proporranno, vogliono prendere le vostre menti e manipolarvi, attenzione!! Figli, abbiate sempre lo sguardo fisso verso la luce, quella luce che vedrete e che vi darà pace e amore, la luce che vi trasformerà per vivere solo per il bene. Vi amo figli e vi benedico nel nome della Santissima Trinità, amen", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 19)), "Figli miei, grazie per essere qui nella preghiera e per aver piegato le vostre ginocchia. Figli, Io, vostra Madre sarò il vostro conforto insieme a mio Figlio Gesù. Figli, perché vi meravigliate, anche mio Figlio è stato perseguitato, lo sarete anche voi. Figli miei, sarete molto attaccati dal male, ma ascoltate le mie parole, siate forti nella preghiera, siate soldati di luce, togliete la paura dal vostro cuore e dalle vostre menti e credete in Gesù che salverà tutti i suoi fratelli fedeli, siate luce per questo mondo di tenebre e quando sarete nello sconforto invocatemi ed Io sarò con voi. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 23)), "Figli miei, grazie per essere qui nella preghiera e per aver risposto alla mia chiamata nel vostro cuore. Figli, questo è il tempo dell’ingiustizia, siate umili e fate penitenza. Figli, il Vescovato di Roma è in seria difficoltà, pregate per i sacerdoti, la Chiesa è e sarà sempre una e santa, ma alcune anime che abitano in essa verranno prese dal male.  Venite qui, in questo luogo benedetto dal Padre e abbeveratevi nella fonte di mio Figlio Gesù.  Figli miei, gli uragani aumenteranno, presto ci sarà un attentato per opera del male, vi prego, credete alle mie parole. Figli miei, mio Figlio dividerà il male dal bene, voi continuate nella preghiera, i tempi saranno sempre più duri, nuovi virus si affacceranno, la vostra libertà è in bilico. Siate Guerrieri di luce. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 24)), "Figli, grazie per essere qui nella preghiera, Io benedico questa casa, perché come i primi cristiani vi è la preghiera e la condivisione. Preparate i vostri rifugi, perché la persecuzione dei cristiani ha avuto inizio, ma voi non dovete temere. (Galati 6 -7/9)  'Non vi fate illusioni; non ci si può prendere gioco di Dio. Ciascuno raccoglierà quello che avrà seminato. Chi semina nella sua carne, dalla carne raccoglierà corruzione; chi semina nello Spirito, dallo Spirito raccoglierà vita eterna. E non stanchiamoci di fare il bene; se infatti non desistiamo, a suo tempo mieteremo. Poiché dunque ne abbiamo l’occasione, operiamo il bene verso tutti, soprattutto verso i fratelli nella Fede.'  Ora vi benedico e lascerò la mia pace nei vostri cuori, amen", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 30)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore e per aver piegato le vostre ginocchia nella preghiera. Figli, presto vi ritroverete in un tempo molto difficile, più di quanto immaginate. Figli miei, siate uniti e ascoltate le parole di una Madre amorevole, l’anticristo sta agendo, arriverete al punto che non potrete più acquistare nulla senza il suo permesso, fate scorte e non siate leggeri. Figli amati, pregate per i sacerdoti, satana sta agendo, farà togliere tutto ciò che è sacro, iniziando dai tabernacoli e dalle vesti sacerdotali, dicendo che siete tutti uguali. I consacrati fedeli, soffriranno molto, ma Gesù ed Io saremo vicini. Figli, vi prego, amatevi l’un l’altro e unitevi nell’amore di Dio, solo così sarete vincenti. Malattie nuove si affacceranno, ancora poco e sarete ancora nelle vostre prigioni. Figli, il disastro economico è vicino, aiutatevi l’un l’altro, invocatemi ed Io sarò con voi. Vi amo figli, pregate, pregate, pregate tanto.  Ora vi benedico nel nome della Santissima Trinità, amen.", dataset["text_it"])


# ENGLISH
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "Dear precious children to my heart and Jesus' heart, thank you for being here in prayer and for bending your knees. I look at these little ones in prayer and how I wish you too were like them with pure hearts! Remember what Jesus said: the little ones will enter my Kingdom. My children, I beseech you, it will be worse than the universal flood if you do not convert, I do not want to put fear in you but to warn you, return to God with folded hands, bending your knees and with your heart and soul turned to the only Savior, and then live in eternity in heaven. Children, there will be earthquakes, droughts and cloudbursts, in the Church, evil and the evil one has entered and is without my Son anymore. Look around you, for you will no longer recognize your brothers and sisters. I ask you for prayers, fasting and brotherly love. Now I bless you, in the name of the Father and the Son and the Holy Spirit, Amen. Many graces will descend on you today, witness!", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 5)), "Beloved children, thank you for being here in prayer and for answering my call in your hearts. My children, always be united, make reparation for all the horrors that are all over the earth, reciting the Litany of the Most Precious Blood of Jesus. My children, look at the changes that are on earth, but the spiritual ones will also be great, get used to these changes, for nothing will return as before. My children, pray, for America's head of state will be strongly attacked. I still come to give you a caress, I would like to comfort you in this unhealthy and perverse world. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 9)), "My dear children, thank you for responding to my call in your hearts. My children, have the courage to make your choice now because your life will depend on it, the closer you come to the light the more enlightened you will be, the closer you come to evil the more easily the devil will engulf you. My children, choose God forever, please My children, continue to hold prayer cenacles, open your hearts and your homes and I will bless you and I will always be with you to guide you. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen. ", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 15)), "Beloved one, daughter and sister, write to the world. Today, worse than the virus you have so feared is the lust, wickedness, confusion and selfishness that are rampant in the hearts and minds of this humanity. The apostasy reigns because my anointed ones do not believe in the existence of Satan and his tricks, they do not speak of the sin that is tearing them apart, passing it off as ordinary. I will come to divide good from evil, return to Me, before it is too late, you no longer follow My teachings, tolerate evil and bow your heads to it. Those who pass laws against those of My Father will be vomited up and feel the burning of eternal fire. The chastisements will be for the purification of this perverse humanity. Make your choice, I tell you this, so that you may be aware. Wake up, for the time is over, many reject my Mercy, yet, I have shown them miracles, but they are blind and deaf. I say to the politicians: in the name of God, stop now! I will destroy your plans, only I, can decide the end of man, your satanic plans will be swept away, together with you, My Father's justice will thunder so loudly that the whole universe will tremble. Those who follow God's laws shall not fear, but rejoice, for God's kingdom is at hand. Peace be with you, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 16)), "Dear children, thank you for being here in prayer and for bending your knees. My children, Italy will pay dearly for the decisions of politicians. Volcanoes will erupt, watch the events that will happen on earth so that you may believe and return to God. Beloved children, soon Satan's chain will be stronger, do not accept what is most dangerous that they will propose to you, they want to take your minds and manipulate you, beware!!! Children, always have your eyes fixed toward the light, that light that you will see and that will give you peace and love, the light that will transform you to live only for good. I love you children and bless you in the name of the Most Holy Trinity, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 19)), "My children, thank you for being here in prayer and for bending your knees. Children, I, your Mother will be your comfort together with my Son Jesus. My children, why are you surprised, my Son was also persecuted, you will be too. My children, you will be much attacked by evil, but listen to my words, be strong in prayer, be soldiers of light, remove fear from your hearts and minds and believe in Jesus who will save all his faithful brothers and sisters, be light for this world of darkness and when you are in despondency call upon me and I will be with you. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 23)), "My children, thank you for being here in prayer and for answering my call in your hearts. My children, this is the time of injustice, be humble and do penance. My children, the Bishopric of Rome is in serious difficulty, pray for the priests, the Church is and always will be one and holy, but some souls who dwell in it will be taken by evil.  Come here to this place blessed by the Father and drink in the fountain of my Son Jesus.  My children, hurricanes will increase, soon there will be an attack by evil, please believe my words. My children, my Son will divide the evil from the good, you continue in prayer, times will get harder and harder, new viruses will arise, your freedom hangs in the balance. Be warriors of light. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 24)), "Children, thank you for being here in prayer, I bless this house, for like the first Christians there is prayer and sharing. Prepare your shelters, for the persecution of Christians has begun, but you need not fear. (Galatians 6 -7/9) 'Make no mistake: God is not mocked, for a person will reap only what he sows, because the one who sows for his flesh will reap corruption from the flesh, but the one who sows for the spirit will reap eternal life from the spirit. Let us not grow tired of doing good, for in due time we shall reap our harvest, if we do not give up. So then, while we have the opportunity, let us do good to all, but especially to those who belong to the family of the faith'. Now I bless you and leave my peace in your hearts, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 30)), "Dear children, thank you for answering my call in your hearts and for bending your knees in prayer. My children, soon you will find yourselves in a very difficult time, more than you imagine. My children, be united and listen to the words of a loving Mother, the antichrist is acting, you will reach the point where you will not be able to buy anything without his permission, stock up and do not be reckless. Beloved children, pray for priests, Satan is acting, he will have everything sacred removed, starting with tabernacles and priestly robes, saying you are all the same. The consecrated faithful, they will suffer a lot, but Jesus and I will be near. Children, please love one another and unite in God's love, only then will you be victorious. New illnesses will arise, just a little longer and you will still be in your prisons. Children, economic disaster is near, help one another, call on Me and I will be with you. I love you children, pray, pray, pray much.  Now I bless you in the name of the Most Holy Trinity, Amen.", dataset["text_en"])


# POLISH
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 3)), "Drogie dzieci, najdroższe mojemu sercu i Sercu Jezusa, dziękuję wam, że jesteście tu na modlitwie i że uklęknęliście. Patrzę na te maleństwa w modlitwie i jakże pragnę, abyście i wy byli jak one o czystych sercach! Pamiętajcie, co powiedział Jezus: mali wejdą do mojego Królestwa. Moje dzieci, proszę was, jeśli się nie nawrócicie, przyjdzie coś gorszego niż powszechny potop, nie chcę was przerazić, chcę was ostrzec, wróćcie do Boga ze złożonymi rękami, zginając kolana, z sercem i duszą zwróconą do jedynego Zbawiciela, aby potem żyć w wieczności w raju. Moje dzieci, będą trzęsienia ziemi, susze i oberwania chmury, do Kościoła weszło zło i szatan, a mojego Syna już nie ma. Rozejrzyjcie się wokół siebie, bo nie rozpoznacie już swoich braci. Proszę Was o modlitwy, post i miłość braterską. Teraz błogosławię was, w imię Ojca i Syna i Ducha Świętego, Amen. Wiele łask zstąpi dziś na Ciebie, świadku!", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 5)), "Umiłowane dzieci, dziękuję wam, że jesteście tu na modlitwie i że odpowiadacie na moje wezwanie w waszych sercach. Moje dzieci, zawsze bądźcie zjednoczeni, czyńcie zadość za wszystkie okropności, które są na ziemi, odmawiając Koronkę do Najdroższej Krwi Pana Jezusa. Moje dzieci, patrzcie na zmiany, które zachodzą na ziemi, także te duchowe będą wielkie, przyzwyczajajcie się do tych zmian, bo nic nie będzie już jak dawniej. Moje dzieci, módlcie się, bo głowa państwa amerykańskiego będzie mocno atakowana. Przychodzę ponownie, aby cię przytulić, pragnę Cię pocieszyć w tym niezdrowym i przewrotnym świecie. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 9)), "Moje drogie dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, miejcie odwagę dokonać teraz wyboru, bo od tego będzie zależało wasze życie, im bardziej zbliżycie się do światła, tym bardziej będziecie oświeceni, im bardziej zbliżycie się do zła, tym łatwiej diabeł was pochłonie. Moje dzieci, wybierzcie Boga na zawsze, proszę moje dzieci, twórzcie nadal kręgi modlitewne, otwórzcie swoje serca i swoje domy, a ja wam pobłogosławię i zawsze będę z wami, aby was prowadzić. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 15)), "Moja ukochana córko i siostro, napisz to światu. Dziś gorsze od wirusa, którego tak się obawialiście, są żądza, niegodziwość, zamieszanie i samolubstwo, które szaleją w sercach i umysłach tej ludzkości. Apostazja panuje, ponieważ Moi konsekrowani nie wierzą w istnienie szatana i jego podstępów, nie mówią o grzechu, który pustoszy, przemilczając go jako coś normalnego. Przyjdę, aby oddzielić dobro od zła, wróćcie do Mnie, zanim będzie za późno, nie stosujecie już Moich nauk, tolerujecie zło i chylicie przed nim głowy. Ci, którzy wydają prawa sprzeczne z prawami Mojego Ojca, zostaną zwymiotowani i odczują palenie wiecznego ognia. Kary będą dla oczyszczenia tej przewrotnej ludzkości. Dokonaj wyboru, mówię do ciebie, abyś był świadomy. Obudźcie się, bo czas się skończył, wielu odrzuca Moje Miłosierdzie, a przecież pokazałem im cuda, ale są ślepi i głusi. Mówię do polityków: w imię Boga, przestańcie już! Zniszczę wasze plany, tylko Ja, mogę zadecydować o końcu człowieka, wasze szatańskie plany zostaną zmiecione, razem z wami. Sprawiedliwość mojego Ojca zagrzmi tak głośno, że zadrży cały wszechświat. Ci, którzy przestrzegają praw Bożych, nie będą się lękać, lecz radować, bo bliskie jest Królestwo Boże. Pokój niech będzie z wami, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 16)), "Drogie dzieci, dziękuję wam, że jesteście tu na modlitwie i że uklęknęliście. Moje dzieci, Włochy drogo zapłacą za decyzje polityków. Wybuchną wulkany, obserwujcie wydarzenia, które będą miały miejsce na ziemi, abyście mogli uwierzyć i wrócić do Boga. Ukochane dzieci, wkrótce sieci szatana będą silniejsze, nie zgadzajcie się na to, co jest najbardziej niebezpieczne, chcą zawładnąć waszymi umysłami i manipulować wami, uważajcie! Moje dzieci, miejcie zawsze wzrok utkwiony w światło, to światło, które zobaczycie i które da wam pokój i miłość, światło, które was przemieni, abyście żyli tylko dla dobra. Kocham was dzieci i błogosławię w imię Trójcy Przenajświętszej, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 19)), "Moje dzieci, dziękuję wam, że jesteście tu na modlitwie i że uklęknęliście. Moje dzieci, Ja, wasza Matka, będę waszą pociechą razem z moim Synem Jezusem. Dzieci moje, czemu się dziwicie, mój Syn był prześladowany, wy też będziecie prześladowani. Moje dzieci, będziecie mocno atakowani przez zło, ale słuchajcie moich słów, bądźcie mocni w modlitwie, bądźcie żołnierzami światła, usuńcie strach z waszych serc i umysłów i wierzcie w Jezusa, który uratuje wszystkich swoich wiernych braci i siostry, bądźcie światłem dla tego świata ciemności, a gdy będziecie w rozpaczy, wzywajcie mnie, a ja będę z wami. A teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 23)), "Moje dzieci, dziękuję wam, że jesteście tu na modlitwie i że odpowiadacie na moje wezwanie w waszych sercach. Moje dzieci, to jest czas niesprawiedliwości, bądźcie pokorni i czyńcie pokutę. Moje dzieci, Biskupstwo Rzymu przeżywa poważne trudności, módlcie się za kapłanów, Kościół jest i zawsze będzie jeden i święty, ale niektóre dusze w nim żyjące zostaną porwane przez zło. Przyjdźcie tutaj, na to miejsce pobłogosławione przez Ojca i pijcie ze źródła Mojego Syna Jezusa. Moje dzieci, huragany będą się nasilać, wkrótce nastąpi atak zła, błagam was, uwierzcie w moje słowa. Moje dzieci, mój Syn rozdzieli zło od dobra, wy trwajcie w modlitwie, czasy będą coraz trudniejsze, pojawią się nowe wirusy, wasza wolność wisi na włosku. Bądźcie wojownikami światła. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 24)), "Dzieci, dziękuję wam, że jesteście tu na modlitwie, błogosławię ten dom, bo jak u pierwszych chrześcijan jest tu modlitwa i dzielenie się. Przygotujcie swoje schronienia, bo rozpoczęło się prześladowanie chrześcijan, ale nie musicie się obawiać. (Galatów 6 -7/9) 'Nie łudźcie się: Bóg nie dozwoli z siebie szydzić. A co człowiek sieje, to i żąć będzie: kto sieje w ciele swoim, jako plon ciała zbierze zagładę; kto sieje w duchu, jako plon ducha zbierze życie wieczne. W czynieniu dobrze nie ustawajmy, bo gdy pora nadejdzie, będziemy zbierać plony, o ile w pracy nie ustaniemy. A zatem, dopóki mamy czas, czyńmy dobrze wszystkim, a zwłaszcza naszym braciom w wierze'.  Teraz błogosławię was i zostawiam mój pokój w waszych sercach, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 7) & (dataset["day"] == 30)), "Drogie dzieci, dziękuję wam, że odpowiadacie na moje wezwanie w waszych sercach i że klękacie do modlitwy. Moje dzieci, wkrótce znajdziecie się w bardzo trudnym czasie, trudniejszym niż sobie wyobrażacie. Moje dzieci, bądźcie zjednoczeni i słuchajcie słów kochającej Matki, antychryst działa, dojdzie do tego, że nie będziecie mogli już nic kupić bez jego zgody, róbcie zapasy i nie bądźcie lekkomyślni. Umiłowane dzieci, módlcie się za kapłanów, szatan działa, usunie wszystko, co święte, zaczynając od tabernakulum i szat kapłańskich, mówiąc, że wszyscy jesteście tacy sami. Wierni konsekrowani, będą wiele cierpieć, ale Jezus i ja będziemy blisko. Moje dzieci, błagam was, kochajcie się wzajemnie i jednoczcie się w miłości Boga, tylko w ten sposób odniesiecie zwycięstwo. Powstaną nowe choroby, jeszcze tylko chwila i znów będziecie w swoich więzieniach. Dzieci, katastrofa ekonomiczna jest bliska, pomagajcie sobie nawzajem, przyzywajcie mnie, a ja będę z wami. Kocham was dzieci, módlcie się, módlcie się mocno. Teraz błogosławię was w imię Trójcy Przenajświętszej, Amen.", dataset["text_pl"])


dataset = dataset[['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en']]

dataset_ready = pd.read_csv("july_2022.csv")
dataset_ready = dataset_ready.fillna("")

dataset = dataset.merge(dataset_ready, how="left", on=['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en'])

dataset_ok = dataset[~dataset["text_pt"].isnull()]
dataset_translate = dataset[dataset["text_pt"].isnull()]



dataset_translate["text_es"] = dataset_translate["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset_translate["text_fr"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset_translate["text_zh"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'zh'))
dataset_translate["text_de"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'de'))
dataset_translate["text_pt"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'pt'))


dataset = pd.concat([dataset_ok, dataset_translate])

dataset = dataset.sort_values(by="day")


dataset.to_csv("july_2022.csv", encoding="utf-8", index=False)









