# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator
import goslate
gs = goslate.Goslate()




dataset = pd.read_csv("august_cleaned.csv", encoding="utf-8")




# ITALIAN

dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 3)), "Cari figli benedetti, grazie per essere qui e per aver risposto alla mia chiamata nel vostro cuore. Figli, gioite perché la venuta di Gesù è vicina, aprite i vostri cuori, Io sono qui a toccare la terra per portare l’amore nelle vostre vite e prepararvi al giorno più bello, vedere il mio Gesù arrivare su una nube dal cielo. Credete in Cristo Gesù, unico profondo amore e Redentore. Figli amati, siate pronti ed Io vi metterò in prima fila per godere la meraviglia. Figli miei, amate e lodate Gesù, vostro Salvatore che verrà a donarvi la terra purificata dal male e per darvi una terra dove tutto sarà nuovo. Ora vi benedico nel nome della Santissima Trinità, amen. Oggi tante le grazie scenderanno su di voi, testimoniate!!", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 9)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli, l’umanità è in bilico, vi prego figli, tornate a Dio e alle sue leggi, Lui è misericordioso e se chiederete il perdono, ve lo concederà. Figli miei, le guerre inizieranno, finiranno, ma poi continueranno, pregate, perché non avete più tempo, che il vostro parlare sia, si si, no no. Continuo a venire a voi per istruirvi e spesso vi girate dall’altra parte. Figli miei, credete alle mie parole affinché siate preparati, il vostro cammino sarà piuttosto arduo e impervio, ma chi avrà come àncora il Santo Rosario, sarà salvato. Figli, seguite i dieci comandamenti, guardate mio Figlio e lì vedrete la luce. Figli, ci sarà un forte terremoto, nubifragi in continuazione, ma Io vi chiedo di pregare sotto la croce di mio Figlio e sarete Benedetti voi e le vostre famiglie. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo. amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 13)), "Figli amati, grazie per essere qui, Io vi ho chiamati e voi avete risposto nel vostro cuore. Figli, pregate perché il tempo della purificazione è su di voi, pregate per la Chiesa e per i giovani perché le loro anime si stanno perdendo. Guardate i movimenti della terra, sono tutti segnali per voi. Figli miei, pregate con il cuore, non solo con le parole come facevano i Pagani, le vostre preghiere siano piene d’amore per il mio Divin Figlio, solo così potrete alleviare le nostre sofferenze. Ora vi benedico nel nome della Santissima Trinità, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 14)), "Cara figlia, grazie per avere risposto alla mia chiamata nel tuo cuore. Figlia mia, domani è la festa della Mia Assunzione in cielo, Giovanni in quel momento mi era accanto, aveva adornato il mio lettino di fiori freschi e profumati. Dopo essermi addormentata, una luce folgorante ha invaso la stanzetta, ma una luce ancora più forte si è sovrapposta, rendendo la cameretta piena di lucine che brillavano di tanti colori ed ecco gli angeli che mi hanno sollevata e portata all’incontro con mio Figlio Gesù. Figlia mia, tocco ancora la terra per aiutare l’umanità a convertirsi e amare Dio, così come l’ho amato Io, siate simili a me e portate nel cuore le sofferenze di questi periodi che state vivendo e di quelli che vivrete, sappiate che Io vi sarò sempre accanto per consolarvi. Non potete neanche immaginare quanta gioia abbia provato, all’incontro con mio Figlio ed è così che vorrei fosse il vostro incontro quando presto Lui arriverà. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 20)), "Cari figli Benedetti, grazie per aver piegato le vostre ginocchia nella preghiera e per aver ascoltato la mia chiamata nel vostro cuore. Mio Figlio vi ha chiesto di abbeverarvi ai piedi della croce, ma molti non cercano acque dolci e benedette, ma acque salmastre. Nessuno o pochi vedono tutto ciò che accade sulla terra, il cielo vi invia i segnali per pregare di più, ma molti continuano nella loro cecità. Figli miei, il deserto avanza e sarete invasi da altri fratelli. Figli, pregate per i sacerdoti perché non sono tutti pastori, non portano le pecore all’ovile. Figli, udite e guardate, non siate distratti e vi prego convertitevi, è molto urgente. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 23)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, pregate, pregate tanto, perché il mondo è in grande pericolo, l’umanità è in grande pericolo, anche la Chiesa chiude le porte.  Figli miei, presto uno scisma farà tremare la Chiesa di Roma, avvolta dalle tenebre. Figli miei, ricordate che Io sono qui tutti i giorni insieme al mio Gesù, non temete perché avrete sempre il nostro conforto, quando invocherete i nostri nomi.  Figli, pregate in particolare per la Francia, perché ha perso la fede, i segnali inviati dal cielo saranno molto forti ed evidenti. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 27)), "Cari figli, grazie per aver ascoltato la mia chiamata nel vostro cuore e per aver piegato le ginocchia nella preghiera. Figlia mia, conduci il mio popolo verso Dio, non aver paura, anche Io portai un grande peso nel mio cuore, ma avrai la grazia per poter essere più forte. Pregate figli, per le centrali nucleari dell’est, perché inizia il pericolo per i miei figli. Pregate per la Chiesa e siate uniti nel nome di Gesù Cristo. Figli miei tocco la terra e cammino nel mio pellegrinaggio terreno per togliere i miei figli dal fango, eppure ancora vedo che rifiutano la grazia. Figlia mia, non temere, Io sarò sempre al tuo fianco e vi benedico tutti nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 30)), "Figlia mia, grazie per avermi accolto nel tuo cuore. L’umanità sta scendendo nell’abisso, i miei figli hanno perso la ragione, molti sacerdoti confusi lasceranno le Chiese che si stanno già svuotando di fedeli. Oh! figlia mia, tutto si sta svolgendo velocemente. Molti dovrebbero unirsi e combattere, non con le armi, ma con la preghiera, portando il gregge verso un solo Pastore che è Gesù Cristo. Chiedo ai governanti: andate per il mondo a portare la pace, altrimenti una grande guerra vi risucchierà. Ormai, si stanno preparando i tempi del Grande Monarca, che sta ultimando la sua preparazione per il suo ingresso, egli sarà rivestito di Spirito Santo e porterà la pace nel tempo dell’anticristo e della vera persecuzione cristiana. Grazie figli miei per le vostre preghiere, perché asciugano le mie lacrime. Oggi scenderanno molte grazie.  Pregate per la Chiesa e per la Russia. Il grande serpente avanzerà, ma Io, l’Immacolata Concezione, lo schiaccerò. Ora ti benedico nel nome della Santissima Trinità, amen.", dataset["text_it"])

# ENGLISH

dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 3)), "Dear blessed children, thank you for being here and answering My call in your hearts. Children, rejoice because the coming of Jesus is near, open your hearts, I am here to touch the earth to bring love into your lives and prepare you for the most beautiful day, to see my Jesus coming on a cloud from heaven. Believe in Christ Jesus, the only deep Love and Redeemer. Beloved children, be ready and I will put you in the front row to enjoy the wonder. My children, love and praise Jesus, your Savior who will come to give you the earth cleansed of evil and to give you a land where everything will be new. Now I bless you in the name of the Most Holy Trinity, Amen. Today many graces will descend upon you, witness!", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 9)), "My children, thank you for responding to my call in your hearts. My children, humanity is in the brink, please children, return to God and His laws, He is merciful and if you ask for forgiveness, He will grant it. My children, wars will begin, they will end, but then they will continue, pray, for you are running out of time, let your speech be, yes yes, no no. I keep coming to you to instruct you and you often turn away. My children, believe my words so that you may be prepared, your path will be rather arduous and impassable, but whoever has the Holy Rosary as an anchor will be saved. Children, follow the Ten Commandments, look to my Son and there you will see the light. Children, there will be a strong earthquake, cloudbursts all the time, but I ask you to pray under the cross of my Son and you and your families will be Blessed. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 13)), "Beloved children, thank you for being here, I have called you and you have responded in your hearts. Children, pray because the time of purification is upon you, pray for the Church and for the youth because their souls are being lost. Look at the movements of the Earth, they are all signs for you. My children, pray with your hearts, not only with words as the Pagans did, your prayers be full of love for my Divine Son, only in this way can you alleviate our sufferings. Now I bless you in the name of the Most Holy Trinity, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 14)), "Dear daughter, thank you for answering My call in your heart. My daughter, tomorrow is the feast of My Assumption into Heaven, John was beside me at that moment, he had adorned my little bed with fresh, fragrant flowers. After I fell asleep, a dazzling light invaded the little room, but an even stronger light superimposed itself, making the little room full of little lights that shone with many colors, and here were the angels who lifted me up and brought me to the meeting with My Son Jesus. My daughter, I am still touching the earth to help mankind to convert and love God as I have loved Him, be like Me and carry in your heart the sufferings of these times you are experiencing and those you will experience, know that I will always be beside you to console you. You cannot even imagine how much joy I felt, at the meeting with my Son and that is how I would like your meeting to be when He comes soon. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 20)), "Dear blessed children, thank you for bending your knees in prayer and listening to my call in your heart. My Son has asked you to drink at the foot of the Cross, but many do not seek fresh and blessed waters, but brackish waters. No one or few see all that is happening on earth; heaven sends you signs to pray more, but many continue in their blindness. My children, the desert is advancing and you will be invaded by more brothers. My children, pray for the priests because they are not all shepherds, they do not bring the sheep to the fold. My children, hear and watch, do not be distracted and please convert, it is very urgent. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 23)), "Dear children, thank you for responding to my call in your hearts. My children, pray, pray much, for the world is in great danger, humanity is in great danger, even the Church is closing its doors.  My children, soon a schism will shake the Church of Rome, shrouded in darkness. My children, remember that I am here every day together with my Jesus, do not fear because you will always have our comfort when you invoke our names. My children, pray especially for France, for she has lost her faith, the signs sent from heaven will be very strong and evident. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 27)), "Dear children, thank you for hearing My call in your heart and for bending your knees in prayer. My child, lead My people to God, do not be afraid, I also carried a great burden in My heart, but you will have the grace to be able to be stronger. Pray children, for the nuclear power plants in the East, for danger begins for My children. Pray for the Church and be united in the name of Jesus Christ. My children I touch the earth and walk in my earthly pilgrimage to remove my children from the mud, yet still I see that they reject grace. My child, do not fear, I will always be at your side and bless you all in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 30)), "My daughter, thank you for welcoming me into your heart. Mankind is descending into the abyss, My children have lost their reason, many confused priests will leave the Churches that are already emptying of believers. Oh! My child, everything is unfolding fast. Many should unite and fight, not with weapons, but with prayer, leading the flock to one Shepherd who is Jesus Christ. I ask the rulers: go around the world to bring peace, otherwise a great war will suck you in. By now, the time is being prepared for the Great Monarch, who is completing his preparation for his entrance, he will be clothed with the Holy Spirit and will bring peace in the time of antichrist and true Christian persecution. Thank you my children for your prayers, for they dry my tears. Many graces will descend today.  Pray for the Church and for Russia. The great serpent will advance, but I, the Immaculate Conception, will crush him. Now I bless you in the name of the Most Holy Trinity, Amen.", dataset["text_en"])

# POLISH

dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 3)), "Drogie błogosławione dzieci, dziękuję wam, że jesteście tutaj i że odpowiadacie na moje wezwanie w waszych sercach. Moje dzieci, radujcie się, bo przyjście Jezusa jest bliskie, otwórzcie swoje serca, jestem tutaj, aby poruszyć ziemię, aby wnieść miłość do waszego życia i przygotować was na najpiękniejszy dzień, aby zobaczyć mojego Jezusa przybywającego na obłoku z nieba. Uwierz w Jezusa Chrystusa, jedyną głęboką Miłość i Odkupiciela. Umiłowane dzieci, bądźcie gotowi, a Ja postawię was w pierwszym rzędzie, abyście mogli cieszyć się tym cudem. Moje dzieci, kochajcie i chwalcie Jezusa, waszego Zbawiciela, który przyjdzie, aby dać wam ziemię oczyszczoną ze zła i dać wam ziemię, w której wszystko będzie nowe. Teraz błogosławię was w imię Trójcy Przenajświętszej, Amen. Dziś wiele łask zstąpi na was, bądźcie ich świadkami!", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 9)), "Moje dzieci, dziękuję wam, że odpowiadacie na moje wezwanie w waszych sercach. Moje dzieci, ludzkość jest w zawieszeniu, błagam was dzieci, powróćcie do Boga i Jego praw, On jest miłosierny i jeśli poprosicie o przebaczenie, On go udzieli. Moje dzieci, wojny będą się zaczynać, będą się kończyć, ale potem będą trwać, módlcie się, bo nie macie już czasu, niech wasza mowa będzie: tak tak, nie nie. Ciągle przychodzę do was, aby was pouczyć, a wy często się odwracacie. Moje dzieci, wierzcie moim słowom, abyście byli przygotowani, wasza droga będzie raczej uciążliwa i nieprzejezdna, ale kto ma Różaniec Święty jako kotwicę, ten będzie uratowany. Moje dzieci, przestrzegajcie Dziesięciu Przykazań, patrzcie w stronę mojego Syna, a tam zobaczycie światło. Dzieci, cały czas będą silne trzęsienia ziemi, oberwania chmur, ale proszę was o modlitwę pod Krzyżem mojego Syna, a wy i wasze rodziny będą błogosławione. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 13)), "Umiłowane dzieci, dziękuję wam za to, że jesteście tutaj, wezwałam was i odpowiedzieliście w swoich sercach. Dzieci moje, módlcie się, bo czas oczyszczenia jest blisko, módlcie się za Kościół i za młodzież, bo ich dusze są zagrożone. Spójrz na ruchy Ziemi, one wszystkie są dla ciebie znakami. Moje dzieci, módlcie się sercem, nie tylko słowami, jak czynili to poganie, niech wasze modlitwy będą pełne miłości do mojego Boskiego Syna, tylko w ten sposób możecie ulżyć naszym cierpieniom. Teraz błogosławię was w imię Trójcy Przenajświętszej, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 14)), "Droga córko, dziękuję ci, że odpowiedziałaś na Moje wezwanie w twoim sercu. Córko, jutro jest święto Mojego Wniebowzięcia do Nieba, Jan był w tym momencie obok mnie, ozdobił moje małe łóżko świeżymi, pachnącymi kwiatami. Po tym, jak zasnęłam, do małego pokoju wtargnęło oślepiające światło, ale nałożyło się na nie jeszcze silniejsze światło, sprawiając, że mały pokój był pełen małych światełek, które świeciły wieloma kolorami, a aniołowie podnieśli mnie i poprowadzili na spotkanie z moim Synem Jezusem. Moja córko, wciąż przychodzę na ziemię, aby pomóc ludzkości nawrócić się i pokochać Boga tak, jak ja Go pokochałam, bądź podobna do mnie i noś w sercu cierpienia tych czasów, które przeżywasz i tych, które przeżyjesz, wiedz, że zawsze będę obok ciebie, aby cię pocieszyć. Nawet nie wyobrażacie sobie, jak wielką radość czułam, gdy spotkałam mojego Syna i tak chciałabym, aby wasze spotkanie było takie, gdy On przyjdzie wkrótce. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 20)), "Drogie błogosławione dzieci, dziękuję wam, że uklęknęliście do modlitwy i że posłuchaliście mojego wezwania w waszych sercach. Mój Syn prosił was o picie u stóp Krzyża, ale wielu nie szuka świeżych i błogosławionych wód, ale wód słonych. Niewielu jest w stanie zobaczyć wszystko, co się dzieje na ziemi. Niebo zsyła wam znaki, abyście się mocniej modlili, ale wielu trwa w swojej ślepocie. Moje dzieci, pustynia przybliża się i zostaniecie najechani przez innych braci. Moje dzieci, módlcie się za kapłanów, bo nie wszyscy są pasterzami, nie wszyscy wprowadzają owce do owczarni. Moje dzieci, słuchajcie i patrzcie, nie rozpraszajcie się i proszę o nawrócenie, to bardzo pilne. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 23)), "Drogie dzieci, dziękuję wam, że w waszych sercach odpowiedzieliście na moje wezwanie. Moje dzieci, módlcie się, módlcie się mocno, bo świat jest w wielkim niebezpieczeństwie, ludzkość jest w wielkim niebezpieczeństwie, nawet Kościół zamyka swoje drzwi. Moje dzieci, wkrótce schizma wstrząśnie Kościołem Rzymskim, owianym ciemnością. Moje dzieci, pamiętajcie, że jestem tu codziennie z moim Jezusem, nie lękajcie się, bo zawsze was pocieszymy, gdy będziecie przywoływać nasze imiona. Moje dzieci, módlcie się szczególnie za Francję, ponieważ straciła wiarę, znaki wysyłane z nieba będą bardzo silne i widoczne. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 27)), "Drogie dzieci, dziękuję wam, że słuchacie mojego wołania w waszym sercu i że uklęknęliście do modlitwy. Moje dziecko, prowadź mój lud ku Bogu, nie bój się, ja też noszę w sercu wielki ciężar, ale ty będziesz miała łaskę, że będziesz silniejsza. Módlcie się, moje dzieci, za elektrownie atomowe na wschodzie, bo zaczyna się niebezpieczeństwo dla moich dzieci. Módlcie się za Kościół i bądźcie zjednoczeni w imię Jezusa Chrystusa. Moje dzieci, dotykam ziemi i chodzę w mojej ziemskiej pielgrzymce, aby usunąć moje dzieci z bagna, a jednak wciąż widzę, że odrzucają łaskę. Moje dziecko, nie lękaj się, ja zawsze będę przy tobie i błogosławię was wszystkich w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 8) & (dataset["day"] == 30)), "Moja córko, dziękuję ci, że przyjęłaś mnie do swojego serca. Ludzkość zstępuje w otchłań, Moje dzieci straciły rozum, wielu zdezorientowanych kapłanów odchodzi z Kościołów, które już pustoszeją. Och! Moje dziecko, wszystko rozwija się szybko. Wielu powinno się zjednoczyć i walczyć, nie bronią, ale modlitwą, prowadząc trzodę ku jednemu Pasterzowi, którym jest Jezus Chrystus. Proszę władców: wyjdźcie na świat, aby zaprowadzić pokój, inaczej pochłonie was wielka wojna. Obecne czasy są już przygotowywane na przyjście Wielkiego Monarchy; będzie on przyobleczony Duchem Świętym i przyniesie pokój w czasach antychrysta i prześladowań prawdziwych chrześcijan. Dziękuję wam moje dzieci za wasze modlitwy, bo one osuszają moje łzy. Wiele łask zstąpi dzisiaj. Módlcie się za Kościół i za Rosję. Wielki wąż będzie się posuwał, ale Ja, Niepokalane Poczęcie, zmiażdżę go. Teraz błogosławię was w imię Trójcy Przenajświętszej, Amen.", dataset["text_pl"])

dataset = dataset[['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en']]

dataset_ready = pd.read_csv("august_2022.csv")


dataset = dataset.merge(dataset_ready, how="left", on=['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en'])

dataset_ok = dataset[~dataset["text_pt"].isnull()]
dataset_translate = dataset[dataset["text_pt"].isnull()]



dataset_translate["text_es"] = dataset_translate["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset_translate["text_fr"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset_translate["text_zh"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'zh'))
dataset_translate["text_de"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'de'))
dataset_translate["text_pt"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'pt'))


dataset = pd.concat([dataset_ok, dataset_translate])

dataset = dataset.sort_values(by="day")


dataset.to_csv("august_2022.csv", encoding="utf-8", index=False)









