# -*- coding: utf-8 -*-
"""
Created on Fri Jan  1 13:01:33 2021

@author: LukaszMalucha
"""



import pandas as pd
import numpy as np
from google_trans_new import google_translator
import goslate
gs = goslate.Goslate()




dataset = pd.read_csv("september_cleaned.csv", encoding="utf-8")




# ITALIAN

dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli, piccoli bambini miei, la vostra fede mi commuove, perché conosco le vostre difficoltà, ma quando pregate e chiedete a mio Figlio Gesù, Lui fa scendere la provvidenza, ed eccovi qui in ginocchio a pregare con il Rosario tra le mani. Figli miei, questa terra sarà purificata con il fuoco, ma sarà anche benedetta dall’acqua che sgorgherà nei luoghi Mariani per la guarigione dell’anima e del corpo. Figli, pregate per la Russia e pregate affinché non venga toccato il nucleare. Pregate per la Chiesa che regna nella confusione. Oggi tra voi c’è una persona che vuole affacciarsi al sacerdozio, devi dire che Gesù ha bisogno di Santi sacerdoti. Gesù benedice questi nuovi sposi. Oggi, tante saranno le grazie che scenderanno su di voi. Figli, non perdete la strada della via, verità e vita.  Ora vi benedico nel nome della Santissima Trinità, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 6)), "Figli miei, grazie per aver risposto alla mia chiamata nel vostro cuore, dove sono gli altri miei figli! Pregate e digiunate, il mondo è l’involucro di tanti peccati iniziando dall’aborto, l’orgoglio, la superbia, nessun rispetto per il proprio corpo, tempio dello Spirito Santo, libidine sfrenata, guerra, conflitti e materialismo. I governanti sono presi dal male, i sacerdoti non hanno più rispetto per mio Figlio Gesù. Siete presi dalle cose del mondo e non vi curate della vostra anima. Io tocco la terra per avvertirvi, l’ira di Dio sarà grande, particolarmente per l’Italia e Roma, sede di Pietro. Figli miei, Io sono qui e allargo le mie braccia in attesa del pentimento e la conversione di questi figli, ai quali sarebbe perdonato tutto se tornassero a Dio. Figli adorati, ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 12)), "Figlia mia, grazie per avermi accolta nella preghiera. Ormai sono giunti i tempi della battaglia, avete dato vita ad un’umanità senza Dio, avete permesso l’ingresso di un idolo al posto di Dio nella Chiesa e lo avete adorato al Suo posto. Figli miei, siate uniti nella vera dottrina della fede senza perdersi d’animo, aprite i vostri cuori allo Spirito Santo, siate costanti e siate guerrieri. Questo, per voi sarà causa di emarginazione e persecuzione, ma non abbiate paura, mio Figlio interverrà. Io vi sono vicina tutti i giorni e vi preserverò dai flagelli. Ora vi lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 13)), "Figli e fratelli miei, grazie per essere qui e per aver piegato le vostre ginocchia sotto la mia croce. Figli miei, Io tocco questa collina benedetta e questa terra, affinché le grazie siano tante. Fratelli miei, vi guardo tutti i giorni e quanto sono felice, quando vedo molti di voi che evitano il peccato e quando avete lo sguardo rivolto verso la luce. Ascoltate ciò che dice la mia e vostra Santissima Madre, non temete per i tempi di dolore che vi attendono perché quando verrete qui, potrete gioire della felicità pura, tutto è pronto. Ora vi benedico, nel nome del Padre, nel Mio nome e dello Spirito Santo. Io sarò con voi per tutta la preghiera, alzate i vostri rosari e avvicinatevi ai piedi della Croce ed Io li benedirò. Il vostro caro Gesù.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 15)), "Figli miei, grazie per aver onorato questa giornata con la preghiera. Figli amati, quanto è grande il mio amore per voi, ma anche il mio dolore.  Dio vi aveva dato la terra, un paradiso e voi l’avete avvelenata, mangiate il fiele credendo sia dolce, non avete più il senso del bene e del male, vi avvicinate a tutto ciò che vi uccide, eppure le mie parole alcuni di voi le hanno messe da parte e non ne avete fatto tesoro, avete perso la pace. Pregate per la Russia e per i politici che vi faranno soffrire. Ora vi lascio con la benedizione della Santissima Trinità, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 17)), "Figli miei prediletti, grazie per avere risposto alla mia chiamata del vostro cuore. Figli miei, tempi terribili vi attendono ma voi dovete lottare e continuare ad essere guerrieri di luce, non temete, la paura distrugge la fede, ma l’amore e la fiducia la rinforzerà. Figli cari, combattete per amore di Dio e vincerete nel Suo amore. Vi prego figli, non abbandonatevi alle astuzie del demonio, questi sono tempi della prova. Pregate per l’Inghilterra, dove è iniziato il suo declino. Ora vi lascio con la mia benedizione nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 20)), "Cari figli, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, quanto vorrei che in tutte le famiglie prevalesse la fede, l’amore e la speranza e tutto andrebbe meglio, invece di far entrare il demonio menzognero che porta zizzania, dubbi e lotte. Figli, guardate intorno a voi, la natura si sta ribellando, i vulcani si accenderanno, la terra tremerà tanto. Figli miei, nella Chiesa fondata da Pietro, mio Figlio non si riconosce più. Io sento i vostri dolori e vi chiedo di lasciarli in questo luogo Benedetto, ed Io interverrò. Figli miei, ora vi lascio con la mia benedizione materna nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 24)), "Cari figli benedetti, grazie per aver risposto alla mia chiamata nel vostro cuore. Figli miei, non abbiate timore, conosco i vostri cuori e so che sono immersi nella paura per tutto ciò che vi sta circondando. Figli cari, se la vostra fede sarà forte, avrete la pace nei vostri cuori altrimenti l’ansia prenderà il sopravvento. Pregate per i sacerdoti,  il fetore della casa di satana arriva fino alla Chiesa di Pietro. La guerra avanza senza pietà, le acque invaderanno le città e i vulcani faranno sentire la loro forza. Figli, pregate insieme, siate uniti fortemente, pregate Gesù affinché operi nei vostri cuori. Ora vi benedico nel nome del Padre, del Figlio e dello Spirito Santo, amen.", dataset["text_it"])
dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 27)), "Dolci bambini miei, grazie per aver risposto la mia chiamata nel vostro cuore e grazie per aver piegato le vostre ginocchia nella preghiera. Figli miei, tante sono le mie lacrime per coloro che non comprendono, non credono, bestemmiano e non si convertono, Io, come Madre​ ​voglio salvare tutti i miei figli. Il mio Gesù sta elargendo molte grazie, ma spesso si è più attratti dalle cose del mondo che invitano alla perdizione e non vi accorgete delle cose belle che si ha tutti i giorni, purtroppo l’orgoglio e la superbia vi accompagna. Figli insegnate ai vostri bambini la recita del Santo Rosario. Figli miei, vi chiedo di andare per le strade del mondo ad annunciare il Vangelo, dite a tutti che Gesù presto tornerà e dovrete essere preparati. Ora, vi benedico nel nome della Santissima Trinità, amen.", dataset["text_it"])
#dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 1)), "", dataset["text_it"])
#dataset["text_it"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 1)), "", dataset["text_it"])

# ENGLISH

dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "Dear children, thank you for responding to my call in your hearts. My little children, your faith moves me, for I know your difficulties, but when you pray and ask my Son Jesus, He brings providence down, and here you are on your knees praying with the Rosary in your hands. My children, this land will be purified by fire, but it will also be blessed by the water that will flow in Marian places for the healing of soul and body. My children, pray for Russia and pray that the nuclear power will not be touched. Pray for the Church that reigns in confusion. Today there is a person among you who wants to face the priesthood, you must say that Jesus needs holy priests. Jesus blesses these newlyweds. Today, many will be the graces that will descend upon you. Children, do not lose the way of the way, truth and life.  Now I bless you in the name of the Holy Trinity, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 6)), "My children, thank you for answering my call in your heart, where are my other children! Pray and fast, the world is the shell of so many sins starting with abortion, pride, haughtiness, no respect for one's body - temple of the Holy Spirit, unbridled lust, war, conflicts and materialism. The rulers are caught up in evil, the priests no longer have respect for my Son Jesus. You are caught up in the things of the world and do not care for your soul. I touch the earth to warn you, the Wrath of God will be great, particularly for Italy and Rome, the See of Peter. My children, I am here and I extend My arms waiting for the repentance and conversion of these children, to whom all would be forgiven if they would return to God. Beloved children, I now bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 12)), "My daughter, thank you for accepting me in prayer. Now the time of battle has come, you have given birth to a godless humanity, you have allowed an idol to enter the Church instead of God and worshipped Him in His place. My children, be united in the true doctrine of the faith without losing heart, open your hearts to the Holy Spirit, be constant and be warriors. This, for you will cause marginalization and persecution, but do not be afraid, my Son will intervene. I am near you every day and will preserve you from the scourges. Now I leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 13)), "My children and brothers, thank you for being here and for bending your knees under My cross. My children, I touch this blessed hill and this land so that graces may be many. My brothers, I look at you every day and how happy I am when I see many of you avoiding sin and when you have your eyes turned toward the light. Listen to what my and your Blessed Mother says, do not fear for the times of sorrow that await you because when you come here, you can rejoice in pure happiness, everything is ready. Now I bless you, in the name of the Father, in My name and the Holy Spirit. I will be with you throughout the prayer, raise your rosaries and approach the foot of the Cross and I will bless them. Your dear Jesus.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 15)), "My children, thank you for honoring this day with prayer. Beloved children, how great is my love for you, but also my sorrow.  God had given you the earth, a paradise, and you have poisoned it, you eat gall believing it is sweet, you no longer have a sense of good and evil, you approach everything that kills you, yet my words some of you have put aside and you have not treasured them, you have lost your peace. Pray for Russia and for the politicians who will make you suffer. Now I leave you with the blessing of the Holy Trinity, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 17)), "My beloved children, thank you for responding to my call of your heart. My children, terrible times await you but you must fight and continue to be warriors of light, do not fear, fear destroys faith, but love and trust will strengthen it. Beloved children, fight for God's sake and you will win in His love. Please children, do not give in to the wiles of the devil, these are times of trial. Pray for England, where her decline has begun. Now I leave you with my blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 20)), "Dear children, thank you for responding to my call in your hearts. My children, how I wish that faith, love and hope would prevail in all families and everything would be better, instead of letting in the lying devil who brings discord, doubt and strife. My children, look around you, nature is rebelling, volcanoes will ignite, the earth will shake so much. My children, in the Church founded by Peter, my Son is no longer recognized. I feel your sorrows and I ask you to leave them in this blessed place, and I will intervene. My children, I now leave you with my motherly blessing in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 24)), "Dear blessed children, thank you for responding to my call in your hearts. My children, do not be afraid, I know your hearts and I know that they are immersed in fear for everything that is surrounding you. Dear children, if your faith is strong, you will have peace in your hearts otherwise anxiety will take over. Pray for the priests, the stench of Satan's house reaches as far as the Church of Peter. The war advances without mercy, the waters will invade the cities and the volcanoes will make their force felt. My children, pray together, be united strongly, pray to Jesus to work in your hearts. Now I bless you in the name of the Father and the Son and the Holy Spirit, Amen.", dataset["text_en"])
dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 27)), "My sweet children, thank you for answering My call in your hearts and thank you for bending your knees in prayer. My children, many are my tears for those who do not understand, do not believe, blaspheme and are not converted, I, as Mother want to save all my children. My Jesus is bestowing many graces, but often you are more attracted by the things of the world that invite perdition and you do not notice the good things that you have every day, unfortunately pride and haughtiness accompany you. My children, teach your children the recitation of the Holy Rosary. My children, I ask you to go to the streets of the world to proclaim the Gospel, tell everyone that Jesus will soon return and you must be prepared. Now, I bless you in the name of the Most Holy Trinity, amen.", dataset["text_en"])
#dataset["text_en"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 1)), "", dataset["text_en"])

# POLISH

dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 3)), "Drogie dzieci, dziękuję wam, że odpowiadacie na moje wezwanie w waszych sercach. Moje małe dzieci, wasza wiara porusza mnie, bo znam wasze trudności, ale kiedy modlicie się i prosicie mojego Syna Jezusa, On sprowadza opatrzność i oto jesteście na kolanach, modląc się z Różańcem w rękach. Moje dzieci, ta ziemia będzie oczyszczona przez ogień, ale będzie też błogosławiona przez wodę, która popłynie z miejsc maryjnych dla uzdrowienia duszy i ciała. Moje dzieci, módlcie się za Rosję i o to, by nie została użyta siła atomowa. Módlcie się za Kościół, który przoduje w zamęcie. Dzisiaj jest wśród was osoba, która chce wejść do kapłaństwa, trzeba powiedzieć, że Jezus potrzebuje świętych kapłanów. Jezus błogosławi tym nowym małżonkom. Dziś wiele łask zstąpi na Ciebie. Moje dzieci, nie zgubcie drogi do prawdy i życia. Teraz błogosławię was w imię Trójcy Świętej, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 6)), "Moje dzieci, dziękuję wam za odpowiedź na moje wezwanie w waszych sercach, gdzie są moje inne dzieci! Módlcie się i pośćcie, świat jest otoczony skorupą wielu grzechów począwszy od aborcji, pychy, braku szacunku dla własnego ciała - świątyni Ducha Świętego, niepohamowanej żądzy, wojny, konfliktów i materializmu. Władcy uwikłani są w zło, kapłani nie mają już szacunku dla Mojego Syna Jezusa. Jesteście pochłonięci sprawami tego świata i nie dbacie o swoje dusze. Przychodzę na ziemię, aby was ostrzec, gniew Boga będzie wielki, szczególnie dla Włoch i Rzymu - Stolicy Piotrowej. Moje dzieci, jestem tu i wyciągam ręce oczekując skruchy i nawrócenia tych dzieci, którym wszystko byłoby wybaczone, gdyby powróciły do Boga. Umiłowane dzieci, błogosławię was teraz w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 12)), "Moje dziecko, dziękuję ci, że przyjęłaś mnie na modlitwie. Teraz nadszedł czas walki, zrodziliście bezbożną ludzkość, dopuściliście do Kościoła bożka w miejsce Boga i oddaliście mu cześć w Jego miejsce. Moje dzieci, bądźcie zjednoczeni w prawdziwej doktrynie wiary, nie tracąc serca, otwórzcie wasze serca na Ducha Świętego, bądźcie stali i wojowniczy. Będzie to dla was przyczyną marginalizacji i prześladowań, ale nie bójcie się, mój Syn będzie interweniował. Jestem blisko was każdego dnia i zachowam was od plag. A teraz zostawiam was z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 13)), "Moi synowie i bracia, dziękuję wam, że jesteście tutaj i klękacie pod moim krzyżem. Moje dzieci, dotykam tego błogosławionego wzgórza i tej ziemi, aby łaski były liczne. Bracia moi, patrzę na was każdego dnia i jakże się cieszę, gdy widzę, że wielu z was unika grzechu i gdy macie oczy zwrócone ku światłu. Słuchajcie tego, co mówi moja i wasza najświętsza Matka, nie lękajcie się o czasy smutku, które was czekają, bo kiedy przyjdziecie tutaj, będziecie mogli cieszyć się czystym szczęściem, wszystko jest gotowe. Teraz błogosławię was, w imię Ojca, w imię Moje i Ducha Świętego. Będę z wami podczas całej modlitwy, podnieście swoje różańce i podejdźcie do stóp Krzyża, a Ja wam pobłogosławię. Wasz kochany Jezus.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 15)), "Moje dzieci, dziękuję wam za uczczenie tego dnia modlitwą. Umiłowane dzieci, jak wielka jest moja miłość do was, ale i mój smutek. Bóg dał wam ziemię, raj, a wy ją zatruliście, jecie żółć, uważając ją za słodką, nie macie już poczucia dobra i zła, podchodzicie do wszystkiego, co was zabija, a jednocześnie moje słowa niektórzy z was odrzucili i nie cenili ich, straciliście pokój. Módlcie się za Rosję i za polityków, którzy sprawią, że będziecie cierpieć. Teraz zostawiam was z błogosławieństwem Trójcy Świętej, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 17)), "Moje kochane dzieci, dziękuję wam, że odpowiedzieliście na moje wezwanie w waszych sercach. Moje dzieci, czekają was straszne czasy, ale musicie walczyć i nadal być wojownikami światła, nie bójcie się, strach niszczy wiarę, ale miłość i zaufanie ją wzmocni. Umiłowane dzieci, walczcie o miłość Boga, a zwyciężycie w Jego miłości. Błagam was, dzieci, nie poddawajcie się podstępom diabła, to jest czas próby. Módlcie się za Anglię, gdzie rozpoczął się jej upadek. Zostawiam was teraz z moim błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 20)), "Drogie Dzieci, dziękuję Wam, że w swoich sercach odpowiadacie na moje wezwanie. Moje dzieci, jakże pragnę, aby we wszystkich rodzinach zwyciężyła wiara, miłość i nadzieja i wszystko byłoby lepsze, zamiast wpuszczać kłamliwego diabła, który wprowadza niezgodę, zwątpienie i spory. Moje dzieci, rozejrzyjcie się wokół siebie, natura się buntuje, wulkany zapłoną, ziemia mocno się zatrzęsie. Moje dzieci, w Kościele założonym przez Piotra mój Syn nie jest już uznawany. Czuję twój ból i proszę cię o pozostawienie go w tym błogosławionym miejscu, a Ja będę interweniować. Moje dzieci, zostawiam was teraz z moim matczynym błogosławieństwem w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 24)), "Drogie błogosławione dzieci, dziękuję wam, że w swoich sercach odpowiadacie na moje wezwanie. Moje dzieci, nie bójcie się, znam wasze serca i wiem, że są one zanurzone w lęku o wszystko, co was otacza. Moje drogie dzieci, jeśli wasza wiara jest silna, będziecie mieli pokój w waszych sercach, w przeciwnym razie niepokój weźmie górę. Módlcie się za kapłanów, smród domu szatana sięga aż do Kościoła Piotra. Wojna postępuje bez litości, wody wtargną do miast, a wulkany dadzą znać o swojej sile. Moje dzieci, módlcie się razem, bądźcie mocno zjednoczeni, módlcie się do Jezusa, aby działał w waszych sercach. Teraz błogosławię was w imię Ojca i Syna i Ducha Świętego, Amen.", dataset["text_pl"])
dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 27)), "Moje słodkie dzieci, dziękuję wam, że odpowiadacie na moje wezwanie w waszych sercach i dziękuję, że uklęknęliście w modlitwie. Moje dzieci, wiele jest moich łez za tych, którzy nie rozumieją, nie wierzą, bluźnią i nie nawracają się, Ja jako Matka chcę uratować wszystkie moje dzieci. Mój Jezus hojnie obdarza wieloma łaskami, ale często bardziej pociągają was rzeczy tego świata, które prowadzą was do zguby, a nie zauważacie pięknych rzeczy, które macie na co dzień, niestety pycha i arogancja wam towarzyszą. Moje dzieci, uczcie swoje dzieci odmawiania Różańca Świętego. Moje dzieci, proszę was, abyście wyszli na ulice świata, aby ogłosić Ewangelię, powiedzieć wszystkim, że Jezus wkrótce powróci i trzeba być przygotowanym. Teraz błogosławię was w imię Trójcy Przenajświętszej, amen.", dataset["text_pl"])
#dataset["text_pl"] = np.where(((dataset["month"] == 9) & (dataset["day"] == 1)), "", dataset["text_pl"])

dataset = dataset[['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en']]


dataset_ready = pd.read_csv("september_2022.csv")


dataset = dataset.merge(dataset_ready, how="left", on=['year', 'month', 'day', 'author', 'text_it', 'month_string', 'text_pl','text_en'])

dataset_ok = dataset[~dataset["text_pt"].isnull()]
dataset_translate = dataset[dataset["text_pt"].isnull()]



dataset_translate["text_es"] = dataset_translate["text_it"].apply(lambda x: gs.translate(x,'es'))
dataset_translate["text_fr"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'fr'))
dataset_translate["text_zh"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'zh'))
dataset_translate["text_de"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'de'))
dataset_translate["text_pt"] = dataset_translate["text_en"].apply(lambda x: gs.translate(x,'pt'))


dataset = pd.concat([dataset_ok, dataset_translate])

dataset = dataset.sort_values(by="day")


dataset.to_csv("september_2022.csv", encoding="utf-8", index=False)









